### ISSUE TITLE
copyToRealmOrUpdate() fails if relation is already in Realm w/ primary key

### ISSUE THREAD

**Issue by koalahamlet** [realm/realm-java#1061]
I'm currently turning a ParseObject into a RealmObject. I'm using realm-android:0.80.1
The model I'm using for Parse is
```java
@ParseClassName("Attribute")
public class Attribute extends ParseObject{

	public String getAttributeId(){
		return (String) get("attributeId");
	}

	public String getDescription(){
		return (String) get("description");
	}

	public String getImageFileUrl(){
		return (String) getParseFile("imageFile").getUrl();
	}

	public String getName(){
		return (String) get("name");
	}

}
```
The Realm Object I'm using is
```java
@RealmClass
public class rAttribute  extends RealmObject {

	@PrimaryKey
	private String attributeId;
	private String description;
	private String pictureUrl;
	private String storeId;
	private boolean isChecked;
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isChecked() {
		return isChecked;
	}

	public void setChecked(boolean isChecked) {
		this.isChecked = isChecked;
	}

	public String getAttributeId(){
		return attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public String getDescription(){
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPictureUrl() {
		return pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getStoreId() {
		return storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

}
```
and the code I'm having trouble with is here:
```java
for (Attribute a : attributeList) {
					// Add an attribute
					getAppRealm().beginTransaction();
					rAttribute attribute = getAppRealm().createObject(rAttribute.class);
					attribute.setAttributeId(a.getAttributeId());
					attribute.setDescription(a.getDescription());
					attribute.setStoreId(Session.getStoreId());
					attribute.setPictureUrl(a.getImageFileUrl());
					attribute.setName(a.getName());
					attribute.setChecked(false);
					realm.copyToRealmOrUpdate(attribute);
					getAppRealm().commitTransaction();
}
```

the above code gives me the following crash

```
04-21 11:16:51.477  12163-12163/aislefire.whitelable.demo.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: aislefire.whitelable.demo.debug, PID: 12163
    io.realm.exceptions.RealmException: Primary key constraint broken. Value already exists: topSeller
            at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:731)
            at io.realm.internal.Table.checkStringValueIsLegal(Table.java:716)
            at io.realm.internal.Row.setString(Row.java:216)
            at io.realm.rAttributeRealmProxy.setAttributeId(rAttributeRealmProxy.java:58)
            at aislefire.whitelabel.WhitelabelApplication$7.done(WhitelabelApplication.java:279)
            at aislefire.whitelabel.WhitelabelApplication$7.done(WhitelabelApplication.java:265)
            at com.parse.Parse$5$1.run(Parse.java:924)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Shouldn't copyToRealmOrUpdate() not allow this error to be thrown?

**Comment by cmelchior** [comment]
Hi @koalahamlet 
Your code is crashing because ```createObject()``` and ```copyToRealmOrUpdate()``` actually does the same but in slightly different ways.

1) ```createObject()``` creates a object inside Realm at once with all fields set to default values, then you override these values using the setters.

2) ```copyToRealmOrUpdate``` works on standalone objects, ie. objects that that are created using a normal constructor instead of ```createObject()```. So now you are effectively trying to duplicate the data you just created, which will thrown an error if an primary key is defined.

That said there seem to be a regression in our code, because ```copyToRealmOrUpdate()``` should check if the object is already in the Realm and if it is, just ignore it, which is what should happen in your case.

But removing ```realm.copyToRealmOrUpdate(attribute)``` should fix the issue in your case.

**Comment by cmelchior** [comment]
Hi @koalahamlet 

I just looked at our code, and it seems to do the right thing. I have edited the post above with corrections.

**Comment by koalahamlet** [comment]
Thanks @cmelchior !, I changed my code so that the Model has an empty constructor, and now my loop looks like this. The code now works as expected :+1: 

```java
				for (Attribute a : attributeList) {
					getAppRealm().beginTransaction();
					rAttribute attribute = new rAttribute();
					attribute.setAttributeId(a.getAttributeId());
					attribute.setDescription(a.getDescription());
					attribute.setStoreId(Session.getStoreId());
					attribute.setPictureUrl(a.getImageFileUrl());
					attribute.setName(a.getName());
					attribute.setChecked(false);
					getAppRealm().copyToRealmOrUpdate(attribute);
					getAppRealm().commitTransaction();
				}
```
