### ISSUE TITLE
Realm + Fresco Facebook Library conflicts

### ISSUE THREAD

**Issue by elikohen** [realm/realm-java#1092]
If you have this:

```
compile 'io.realm:realm-android:0.80.1'
```

Added to the build.gradle file on the Fresco Facebook Sample project a crash will appear in 64bit devices (tested on Nexus 9)

Stacktrace:
```
05-06 19:38:58.356    4382-4469/com.facebook.fresco.sample E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-2
    Process: com.facebook.fresco.sample, PID: 4382
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.facebook.fresco.sample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.fresco.sample-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
            at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
            at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:198)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
            at bolts.Task$2.run(Task.java:195)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

I've also filled a GHI on the facebook repo: https://github.com/facebook/fresco/issues/237

**Comment by cmelchior** [comment]
This seems to be related to only ARM64. It cannot be reproduced on neither x86 or armeabi-v7a.

**Comment by elikohen** [comment]
Exactly,

Maybe I wasn't specific about that, sorry. There's no conflict in all the 32bit devices we have. But that problem arises on the Nexus9 that is arm64.

**Comment by emanuelez** [comment]
The problems seems to be that Fresco does not provide direct support for ARM64. This forces the app to be run in 32 bit mode. On the other hand Realm does provide ARM64 support. The problem here is that Android is not smart enough to automatically choose the lowest common denominator and also run Realm in 32 bit mode.

One thing that might be worth a try is to take the Realm jar file (from our distribution package), unzip it and manually remove the ARM64 folder from it. That might do the trick and actually force Android to use the 32 bit version of Realm.

A more appropriate solution is of course to poke the Fresco team to add ARM64 support.

**Comment by elikohen** [comment]
Thank you @emanuelez & @cmelchior! 
We'll try removing the ARM64 folder, compile and check it. But anyway I think we will wait until fresco add the 64bit support to include their library.

Thanks also for your effort searching for the fresco 64bit pull requests that confirm your guess.

**Comment by elikohen** [comment]
@emanuelez We own you a beer ;)
Removing the 64bit folder from the jar makes the app run realm in 32bits mode and no crash appears.

**Comment by emanuelez** [comment]
I'm glad I could help! :+1: 
BTW, Realm benefits from 64 bit architectures so make sure to switch back to 64 bits when Fresco adds support for ARM64 for some extra speed in your data layer :)
