### ISSUE TITLE
mmap() failed: No such device

### ISSUE THREAD

**Issue by fjolliver** [realm/realm-java#1163]
Hi,

This issue is possibly unique to my specific use case, but nonetheless I hope you can help with an explanation.

I use Realm 0.80.3 in my Android (4.4.2) app and everything is working as expected when I run it locally on my test device. The app is an internal company app and thus, I use the tool MDX Toolkit by Citrix to wrap the app inside a container, which is then used on our MDM (mobile device management) and pushed out to our devices. When I launch the app on any of these devices, it crashes when initialising Realm (realm = Realm.getInstance(context) ). The stack trace is below. I'm curious if this is a Realm issue or if the wrapping tool is doing something bad to your library; but most of all, I'm looking for a solution so I can use Realm in my projects. 

Best regards,
Oliver

UncaughtException stack trace:

java.lang.RuntimeException: Unspecified exception. mmap() failed: No such device in io_realm_internal_SharedGroup.cpp line 100
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
	at io.realm.Realm.<init>(Realm.java:193)
	at io.realm.Realm.createAndValidate(Realm.java:498)
	at io.realm.Realm.create(Realm.java:471)
	at io.realm.Realm.getInstance(Realm.java:389)
	at io.realm.Realm.getInstance(Realm.java:351)
	at io.realm.Realm.getInstance(Realm.java:332)
	at dk.myapp.controllers.RealmGlobalController.init(RealmGlobalController.java:52)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:956)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:450)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5350)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by kneth** [comment]
In order to gain great performance, Realm memory maps realm files, and you stack trace hints that the call to `mmap()` is have problems. `mmap()` is a function in the Linux kernel in your Android system.

I have no experience with the MDX Toolkit or XenMobile, and we haven't tested Realm with that particular product. Reading http://support.citrix.com/proddocs/topic/mdxtoolkit-10/xmob-mdx-dev-android-best-practices.html#xmob-mdx-dev-android-best-practices__xmob-mdx-dev-android-bp-encryption I notice that "[m]emory mapping is not supported for encrypted files". I don't know if disabling encryption of files makes sense in your case, but it is my best suggestion so far.

Realm supports encryption of Realm files, so disabling encryption at the XenMobile level might not be as dangerous as it sounds.

**Comment by bmunkholm** [comment]
@fjolliver Has it ever worked before with the MDX Toolkit before? Or is this the first attempt at using/testing it with that product?

**Comment by fjolliver** [comment]
This is the first attempt with app wrapping. We've seen some progress (it seems Realm was successfully initialised) after disabling app encryption in our MDM software, as per your suggestion. I'll report back here once we've verified that this solves the issue with memory mapping.

**Comment by emanuelez** [comment]
Great! Let us know!

**Comment by kneth** [comment]
@fjolliver Did you have any progress to share?

**Comment by fjolliver** [comment]
I have been in contact with the XenMobile support team. They confirm that memory mapping is not possible for applications wrapped within a container if the container is being encrypted. The solution in our case is to disable "Private File Encryption" in the XenMobile app controller and build in encryption directly in the app itself instead (i.e. encrypt the realm database).

**Comment by kneth** [comment]
@fjolliver Thanks for the progress report. I'll close the issue, but don't hesitate to open new issues.

**Comment by hleeanexinet** [comment]
@fjolliver I'm having the same problem. Your solution was to disable "Private File Encryption" and to do the encryption in the app. Just to clarify, in your solution, the app encrypts data that goes into the realm database, not the realm database file itself, correct?
