### ISSUE TITLE
NullPointerException in generateMetaData()

### ISSUE THREAD

**Issue by Poeschl** [realm/realm-java#1170]
Hi,
since I use Realm in one of my project the release build of the app keeps failing on the compileReleaseJava. I was suspecting proguard and disabled it for now, but this doesn't help.
I hope you can help me here :)

The gradle stacktrace:
``` shell
Caused by: java.lang.NullPointerException
        at io.realm.processor.ClassMetaData.generateMetaData(ClassMetaData.java:96)
        at io.realm.processor.RealmProcessor.process(RealmProcessor.java:64)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
        at com.sun.tools.javac.main.Main.compile(Main.java:439)
        ... 65 more
```

My build.gradle 
``` groovy
buildscript {
    dependencies {
        classpath 'de.undercouch:gradle-download-task:1.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        classpath 'io.fabric.tools:gradle:1.18.0'
    }
}

// Manifest version information!
def versionMajor = 0
def versionMinor = 1
def versionPatch = 0

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'io.fabric'

def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
def buildTime = new Date().format("yyyy-MM-dd'T'HH:mm'Z'", TimeZone.getTimeZone("UTC"))
project.ext.set("gitSha", gitSha)

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "de.poeschl.apps.callminder"
        minSdkVersion 15
        targetSdkVersion 22

        versionCode versionMajor * 10000 + versionMinor * 1000 + versionPatch
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"

        buildConfigField "String", "GIT_SHA", "\"${gitSha}\""
        buildConfigField "String", "BUILD_TIME", "\"${buildTime}\""
    }

    signingConfigs {
        googlePlay {
            //Placeholder which gets automatically filled during project sync. Needs the right setting file.
            //This settings is not in the source control, because it contains sensitive information.
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.googlePlay

            //archivesBaseName = "Callminder - " + defaultConfig.versionName + " - " + gitSha

            lintOptions {
                abortOnError true
            }
        }

        debug {
            applicationIdSuffix '.dev'
            ext.enableCrashlytics = false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}
/*
 * All the signing stuff and external config getting.
 */

def getExternalProperties() {
    //Get environment variable of keystore settings folder location.
    def keyStorePath = System.getenv('Android_Keystore_Path')

    //Name of the properties file
    def propertiesFileName = 'Callminder.keyproperties'

    def propsFile = file(keyStorePath + '/' + propertiesFileName)

    def properties;
    if (propsFile.exists()) {
        properties = new Properties()
        properties.load(new FileInputStream(propsFile))
        properties.put('path', keyStorePath)

    } else {
        System.err.println("File " + propsFile.name + " for setup not available");
    }

    return properties
}

def setupSigning(properties) {
    if (properties == null) {
        System.err.println("Could not set signing config. No properties");
        return;
    }

    def configName = 'googlePlay'

    if (android.signingConfigs.hasProperty(configName)) {

        //Android signing information
        android.signingConfigs[configName].storeFile = file(properties['path'] + '/' + properties['storeFile'])
        android.signingConfigs[configName].storePassword = properties['storePassword']
        android.signingConfigs[configName].keyAlias = properties['keyAlias']
        android.signingConfigs[configName].keyPassword = properties['keyPassword']
    }
}

task setupSigning() {
    def props = getExternalProperties();
    setupSigning(props)
}

afterEvaluate { project ->

    def preBuild = project.tasks.getByName("preBuild")
    preBuild.dependsOn setupSigning

}

apply plugin: 'checkstyle'

checkstyle {
    configFile new File("${project.buildDir}/checkstyle.xml")
    reportsDir new File("${project.buildDir}/outputs")
    toolVersion "6.2"
}

preBuild.dependsOn('checkstyle')

task checkstyle(type: Checkstyle) {
    source 'src'
    include '**/*.java'
    exclude '**/gen/**'
    exclude '**/R.java'
    exclude '**/BuildConfig.java'

    def configProps = ['proj.module.dir': buildDir]
    configProperties configProps

    //If you are offline and the checkstyle stuff was downloaded once you can comment the next line out
    it.dependsOn 'downloadCheckstyleConfig'
    classpath = files()
}
apply plugin: 'de.undercouch.download'
import de.undercouch.gradle.tasks.download.Download

task downloadCheckstyleConfig(type: Download) {
    src([
            'https://raw.githubusercontent.com/Poeschl/Android-Checkstyle/master/checkstyle.xml',
            'https://raw.githubusercontent.com/Poeschl/Android-Checkstyle/master/suppressions.xml'
    ])
    dest buildDir
    overwrite true
    onlyIfNewer true
}

dependencies {
    compile 'com.android.support:recyclerview-v7:22.0.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.jakewharton.timber:timber:2.7.1'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.2.3') {
        transitive = true;
    }
    compile 'io.realm:realm-android:0.80.2'
    compile 'com.google.dagger:dagger:2.0'
    compile 'com.f2prateek.dart:dart:1.1.0'

    apt 'com.google.dagger:dagger-compiler:2.0'

    provided 'org.glassfish:javax.annotation:10.0-b28'

    debugCompile 'com.android.support:support-v4:22.0.0'
    debugCompile 'com.jakewharton.scalpel:scalpel:1.1.2'
}
```

The only realm model in the project
```Java
public class Reminder extends RealmObject {

    public enum COLUMN {
        ID("id");

        private String name;

        COLUMN(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    @PrimaryKey
    private int id;

    private String personName;
    private String description;
    private String phoneNumber;
    private Date remindTime;

    public Reminder() {
    }

    public Reminder(int id, String personName, String description, String phoneNumber, Date remindTime) {
        this.id = id;
        this.personName = personName;
        this.description = description;
        this.phoneNumber = phoneNumber;
        this.remindTime = remindTime;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPersonName() {
        return personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Date getRemindTime() {
        return remindTime;
    }

    public void setRemindTime(Date remindTime) {
        this.remindTime = remindTime;
    }
}
```

**Comment by cmelchior** [comment]
Hi @Poeschl 
I have tried reproducing the error you are seeing in a new project but it seems to run fine with the model class you provided. Maybe it is a caching issue? Have you tried running

```
./gradlew clean assemble
```

from the command line to see if you still see this error?

**Comment by Poeschl** [comment]
I already tried that, but without any success.
To support you in investigating I can provide a snapshot of my current repository, if needed.

**Comment by cmelchior** [comment]
That would be very helpful. You can send any files to help@realm.io if you want to keep them confidential.

**Comment by Poeschl** [comment]
I think you have a mail from me.

**Comment by cmelchior** [comment]
Hi @Poeschl 
Thank you for the project. I just imported it into Android Studio 1.3 and ran it without any problems? It also worked fine from the commandl line. I am still guessing it is some kind of cache error. If your project is in git, have you tried cloning it to a new folder and building from there instead?

**Comment by Poeschl** [comment]
This solved my problem. It seems that something was really screwing up the cache. 
Thanks for your time.

**Comment by cmelchior** [comment]
No problem. Good luck with the project.
