### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "io.realm.DefaultRealmModule"

### ISSUE THREAD

**Issue by cchcc** [realm/realm-java#1209]
I wanted to make simple pre-built realm data file to external path.
but exception occured on runtime.
```
java.lang.ClassNotFoundException: Didn't find class "io.realm.DefaultRealmModule" on path: DexPathList[[zip file "/data/app/com.all4land.osmm_pre_model_tool-2/base.apk"],nativeLibraryDirectories=[/data/app/com.all4land.osmm_pre_model_tool-2/lib/arm, /vendor/lib, /system/lib]]
```
logcat :
```
06-12 13:24:55.555: E/AndroidRuntime(10645): FATAL EXCEPTION: main
06-12 13:24:55.555: E/AndroidRuntime(10645): Process: com.all4land.osmm_pre_model_tool, PID: 10645
06-12 13:24:55.555: E/AndroidRuntime(10645): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.all4land.osmm_pre_model_tool/com.all4land.osmm_pre_model_tool.MainActivity}: java.lang.IllegalArgumentException: Book is not part of the schema for this Realm
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2366)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.ActivityThread.access$800(ActivityThread.java:149)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.os.Looper.loop(Looper.java:135)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.ActivityThread.main(ActivityThread.java:5290)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at java.lang.reflect.Method.invoke(Native Method)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
06-12 13:24:55.555: E/AndroidRuntime(10645): Caused by: java.lang.IllegalArgumentException: Book is not part of the schema for this Realm
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:118)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:71)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at io.realm.Realm.getTable(Realm.java:311)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at io.realm.Realm.createObject(Realm.java:1069)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at com.all4land.osmm_pre_model_tool.MainActivity.onCreate(MainActivity.java:32)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.Activity.performCreate(Activity.java:5977)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
06-12 13:24:55.555: E/AndroidRuntime(10645): 	... 10 more
```

model :
```java
package com.all4land.osmm.model.pre;

import io.realm.RealmObject;

public class Book extends RealmObject
{
	private String name;
	
	public String getName() {return name;}
	public void setName(String name) { this.name=name; }
}
```
using:
```java
package com.all4land.osmm_pre_model_tool;

import io.realm.Realm;
import java.io.File;
import android.app.Activity;
import android.os.Bundle;
import android.os.Environment;
import com.all4land.osmm.model.pre.Book;

public class MainActivity extends Activity
{
       @Override
	protected void onCreate(Bundle savedInstanceState)
	{
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		File folder = new File(Environment.getExternalStorageDirectory()
				+ "/download");

		Realm rlm = Realm.getInstance(folder, "pre.realm");	// exception here
		
		rlm.beginTransaction();
		Book b = rlm.createObject(Book.class);
		b.setName("a");
		rlm.commitTransaction();
		
		rlm.close();
	}
}
```
worked on
Eclipse Luna 4.4.2,
realm library built myself from downloaded source yesterday.

I tested using precompiled v0.80.3, same result.

**Comment by cmelchior** [comment]
Hi @cchcc 
If you are using Eclipse you need to add the @RealmClass annotation manually as it doesn't support inherited annotations. So you model class must look like this:

```
@RealmClass
public class Book extends RealmObject
{
  // ...
}
```

**Comment by cchcc** [comment]
Thank you for answer.
I added @RealmClass annotation, 
cleaned and rebuild project, 
removed 'pre.realm' files in device.
but still same result.

**Comment by cchcc** [comment]
Ah.. sorry, that's my bad.
I just found unchecked option 'Annotation processing' -> 'Enable project specific settings' from project settings.
It work fine after check option.

**Comment by cmelchior** [comment]
Great you got it working. Good luck with the project :)
