### ISSUE TITLE
ArrayOutOfBoundsException while opening Realm on 0.81.1

### ISSUE THREAD

**Issue by ahmedre** [realm/realm-java#1248]
hi,
while i haven't been able to repro this myself, i am getting many crashes in Crashlytics about this for many users on 4.x and 5.x.

this seems to happen from various `AsyncTask` and `AsyncLoader` classes when getting the `Realm` instance.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.support.v4.content.ModernAsyncTask$3.done(SourceFile:137)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:117)
       at io.realm.Realm.validateAgainstExistingConfigurations(SourceFile:639)
       at io.realm.Realm.createAndValidate(SourceFile:585)
       at io.realm.Realm.create(SourceFile:549)
       at io.realm.Realm.getInstance(SourceFile:522)
       at com.ayah.util.RealmUtils.getDatabase(SourceFile:37)
       at com.ayah.task.db.GetPageInfoTask.loadInBackground(SourceFile:38)
       at com.ayah.task.db.GetPageInfoTask.loadInBackground(SourceFile:26)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$42af7916(SourceFile:40)
       at android.support.v4.content.ModernAsyncTask$2.call(SourceFile:123)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

`RealmUtils.getDatabase` looks like this:

```java
  private static final String REALM_DB_NAME = "ayah.realm";

  private static final Object sLock = new Object();
  private static volatile boolean sIsInitialized;

  public static Realm getDatabase(Context context) {
    if (!sIsInitialized) {
      synchronized (sLock) {
        final File path = new File(context.getFilesDir(), REALM_DB_NAME);
        if (path.exists()) {
          sIsInitialized = true;
        } else {
          final InputStream inputStream =
              context.getResources().openRawResource(R.raw.ayahrealm);
          if (copyDatabase(inputStream, path)) {
            sIsInitialized = true;
          }
        }
      }
    }

    return Realm.getInstance(
        new RealmConfiguration.Builder(context)
            .name(REALM_DB_NAME)
            .schemaVersion(1)
            .build());
  }
```

thanks!
-ahmed

**Comment by beeender** [comment]
This might have the same root cause with #1247 which could be fixed by #1245

**Comment by beeender** [comment]
@ahmedre Would you help to test if #1245 fix this problem? Or you'd like to wait until our next release to test it?
Thanks!

**Comment by ahmedre** [comment]
i can try to release a new version with this code (but will have to wait until Friday).

**Comment by ahmedre** [comment]
looks good to me after 1 week in prod on the snapshot, thanks!
