### ISSUE TITLE
What can cause a realm to be closed other than directly calling close()?

### ISSUE THREAD

**Issue by ahmedk92** [realm/realm-java#1254]
All my realm objects are either wrapped in a try-finally block, or closed in onDestroy(). Still, I get random "java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable."

What mistake I may be making to cause this?

**Comment by cmelchior** [comment]
Hi @ahmedk92 
Without seeing your code it can be hard to tell, but one possibility is that you fail to acquire a realm instance as the first thing in your try-block, which might mean it would use a previous reference that was closed?

If you could post a stack trace and the code around that part we could give better answer.

**Comment by ahmedk92** [comment]
stack trace:
```
    java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
            at io.realm.Realm.checkIfValid(Realm.java:193)
            at io.realm.Realm.refresh(Realm.java:1414)
            at eg.com.arg.iosdev.awfarcollector2.models.Order.getTransferredOrders(Order.java:429)
            at eg.com.arg.iosdev.awfarcollector2.OrdersActivity.reloadOrderList(OrdersActivity.java:147)
            at eg.com.arg.iosdev.awfarcollector2.OrdersActivity.access$000(OrdersActivity.java:60)
            at eg.com.arg.iosdev.awfarcollector2.OrdersActivity$1.onReceive(OrdersActivity.java:107)
            at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
            at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
            at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
``` 

OrdersActivity$1.onReceive(OrdersActivity.java:107):
```
private BroadcastReceiver broadcastReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
                    ...
                    reloadOrderList(); // line 107
                   ...
        }
    };
```

OrdersActivity.reloadOrderList(OrdersActivity.java:147):
```
/*
 both realm arguments are instantiated in onCreate:
 realm = Realm.getInstance(this);
 transferredRealm = Realm.getInstance(this, ACApplication.REALM_TRANSFERRED);
*/
orders.addAll(Order.getTransferredOrders(realm, transferredRealm)); // line 147
/*
 both realms are closed in onDestroy:
 if(realm != null) {
            realm.close();
 }
if(transferredRealm != null) {
            transferredRealm.close();
}
*/
```

Order.getTransferredOrders(Order.java:429):
```
public static List<Order> getTransferredOrders(Realm activeRealm, Realm transferredRealm) {
        Collector collector = Collector.getCurrentCollector(activeRealm);

        transferredRealm.refresh();

        RealmResults<Order> orders = transferredRealm.where(Order.class).equalTo("am_collector_id", collector.getCollector_id()).findAll();

        ArrayList<Order> ordersList = new ArrayList<>();
        ordersList.addAll(orders);

        return ordersList;
    }
```

**Comment by cmelchior** [comment]
Hi @ahmedk92 
Without seeing all of the code it can be a bit tricky to get a feel for the flow, but by looking at what you have provided, it seems like you close the Realm in ```reloadOrderList()```. This means that if your BroadcastReceiver receives two events in ```onReceive``` after calling ```onCreate()```, the 2nd time it will try to access a closed Realm resulting in the error you are getting.

**Comment by ahmedk92** [comment]
Thank God, I think I found the mistake. I didn't unregister the broadcast receiver on the activity's stop, so reloadOrderList is still called upon new notifications, so calls are made to the activity's closed realm.

However another issue came up. But that's another issue. 

Thanks for your help @cmelchior .
