### ISSUE TITLE
io.realm.exceptions.RealmException: Could not map Json

### ISSUE THREAD

**Issue by stephen1706** [realm/realm-java#1269]
I'm trying to map a json into the realm. i got the json from GSON parser.

this is the log

	07-07 17:08:59.447  19382-19382/? W/System.err﹕ io.realm.exceptions.RealmException: Could not map Json
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at io.realm.Realm.createObjectFromJson(Realm.java:882)
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at io.realm.Realm.createObjectFromJson(Realm.java:932)
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at com.papyri.android.fragments.ui.MainFragment.saveFormDataToRealm(MainFragment.java:190)
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at io.realm.RealmQuestionRealmProxy.createOrUpdateUsingJsonObject(RealmQuestionRealmProxy.java:285)
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at io.realm.RealmFormRealmProxy.createOrUpdateUsingJsonObject(RealmFormRealmProxy.java:205)
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at io.realm.DefaultRealmModuleMediator.createOrUpdateUsingJsonObject(DefaultRealmModuleMediator.java:167)
	07-07 17:08:59.447  19382-19382/? W/System.err﹕ at io.realm.Realm.createObjectFromJson(Realm.java:880)

this is the realm object class

    public class RealmForm extends RealmObject {
	    private int form_id;
	    private String form_name;
	    private String form_description;
	    private RealmList<RealmQuestion> questions;

	    public int getForm_id() {
	        return form_id;
	    }

	    public void setForm_id(int form_id) {
	        this.form_id = form_id;
	    }

	    public String getForm_name() {
	        return form_name;
	    }

	    public void setForm_name(String form_name) {
	        this.form_name = form_name;
	    }

	    public String getForm_description() {
	        return form_description;
	    }

	    public void setForm_description(String form_description) {
	        this.form_description = form_description;
	    }

	    public RealmList<RealmQuestion> getQuestions() {
	        return questions;
	    }

	    public void setQuestions(RealmList<RealmQuestion> questions) {
	        this.questions = questions;
	    }
	}

	public class RealmQuestion extends RealmObject {
	    private int question_id;
	    private String question_text;
	    private int form_id;
	    private RealmList<RealmQuestionType> type;
	    private RealmList<RealmQuestionOption> options;
	    private int position;
	    private int is_mandatory;

	    public int getQuestion_id() {
	        return question_id;
	    }

	    public void setQuestion_id(int question_id) {
	        this.question_id = question_id;
	    }

	    public String getQuestion_text() {
	        return question_text;
	    }

	    public void setQuestion_text(String question_text) {
	        this.question_text = question_text;
	    }

	    public int getForm_id() {
	        return form_id;
	    }

	    public void setForm_id(int form_id) {
	        this.form_id = form_id;
	    }

	    public RealmList<RealmQuestionType> getType() {
	        return type;
	    }

	    public void setType(RealmList<RealmQuestionType> type) {
	        this.type = type;
	    }

	    public RealmList<RealmQuestionOption> getOptions() {
	        return options;
	    }

	    public void setOptions(RealmList<RealmQuestionOption> options) {
	        this.options = options;
	    }

	    public int getPosition() {
	        return position;
	    }

	    public void setPosition(int position) {
	        this.position = position;
	    }

	    public int getIs_mandatory() {
	        return is_mandatory;
	    }

	    public void setIs_mandatory(int is_mandatory) {
	        this.is_mandatory = is_mandatory;
	    }
	}

	public class RealmQuestionOption extends RealmObject {
	    private int option_id;
	    private int question_id;
	    private String option_name;
	    private String option_value;

	    public int getOption_id() {
	        return option_id;
	    }

	    public void setOption_id(int option_id) {
	        this.option_id = option_id;
	    }

	    public int getQuestion_id() {
	        return question_id;
	    }

	    public void setQuestion_id(int question_id) {
	        this.question_id = question_id;
	    }

	    public String getOption_name() {
	        return option_name;
	    }

	    public void setOption_name(String option_name) {
	        this.option_name = option_name;
	    }

	    public String getOption_value() {
	        return option_value;
	    }

	    public void setOption_value(String option_value) {
	        this.option_value = option_value;
	    }
	}

	public class RealmQuestionType extends RealmObject {
	    private int type_id;
	    private int have_option;
	    private int multiple_answer;
	    private String type_name;

	    public int getType_id() {
	        return type_id;
	    }

	    public void setType_id(int type_id) {
	        this.type_id = type_id;
	    }

	    public int getHave_option() {
	        return have_option;
	    }

	    public void setHave_option(int have_option) {
	        this.have_option = have_option;
	    }

	    public int getMultiple_answer() {
	        return multiple_answer;
	    }

	    public void setMultiple_answer(int multiple_answer) {
	        this.multiple_answer = multiple_answer;
	    }

	    public String getType_name() {
	        return type_name;
	    }

	    public void setType_name(String type_name) {
	        this.type_name = type_name;
	    }
	}

and this is the way i insert it to realm 

    private void saveFormDataToRealm() {
	        Realm realm = RealmUtil.getInstance(mContext);

	        realm.beginTransaction();
	        realm.where(RealmForm.class).findAll().clear();
	        for(int i=0;i<mFormListResponseData.length;i++) {
	            String json = new Gson().toJson(mFormListResponseData[i]);
	           
	            realm.createObjectFromJson(RealmForm.class, json);
	        }
	        realm.commitTransaction();
	}

**Comment by stephen1706** [comment]
sorry it seems that the field type is not a RealmList. it is fixed now.
