### ISSUE TITLE
crash on blackberry devices

### ISSUE THREAD

**Issue by ahmedre** [realm/realm-java#1287]
i understand that the primary focus is on supporting vanilla Android, but am just throwing this out there since some of our users took the apk and installed it on blackberry devices (which (mostly) support Android apps). just posting this stack trace, just in case it is easy to work around.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.support.v4.content.ModernAsyncTask$3.done(SourceFile:137)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 115
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SourceFile)
       at io.realm.internal.SharedGroup.(SourceFile:60)
       at io.realm.Realm.(SourceFile:209)
       at io.realm.Realm.createAndValidate(SourceFile:600)
       at io.realm.Realm.create(SourceFile:563)
       at io.realm.Realm.getInstance(SourceFile:536)
       at com.ayah.util.RealmUtils.getDatabase(SourceFile:52)
       at com.ayah.task.db.GetPageInfoTask.loadInBackground(SourceFile:38)
       at com.ayah.task.db.GetPageInfoTask.loadInBackground(SourceFile:26)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$42af7916(SourceFile:40)
       at android.support.v4.content.ModernAsyncTask$2.call(SourceFile:123)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by kneth** [comment]
RIM doesn't implement `mremap()` in the kernel, and Realm for Android uses that (as it is implemented in Android). See also #619.

**Comment by cmelchior** [comment]
@ahmedre I assume the above answered you question, so closing this for now. Please reopen if that is not the case.
