### ISSUE TITLE
Realm and ButterKnife 7.+

### ISSUE THREAD

**Issue by FHellmann** [realm/realm-java#1304]
Realm in combination with ButerKnife 7.+ there will always be an exception thrown:
```java
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
    at io.realm.processor.RealmProcessor.process(RealmProcessor.java:125)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    at com.sun.too
```
The only way to get back to a working version is to revert ButterKnife back to 6.1.0. Trying to revert Realm back does not work.

There was already an issue about this error: #885

It would be very nice if this could be fixed!

**Comment by beeender** [comment]
@FHellmann I could not to reproduce this error with butterknife 7.0.1 and Realm 0.81.1 . Would you please give some more details about this? What IDE are you using?

**Comment by FHellmann** [comment]
It was my mistake. I forgot to remove OrmLite and now it works. I can't say that this was the reason why the issue occured, but now it's gone.

**Comment by ronjumola** [comment]
Hi! I'm trying this:

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        .
        .
        .
        compile 'io.realm:realm-android:0.82.1'
        compile 'com.jakewharton:butterknife:7.0.1'
    }



And it's producing an error:

    Error:duplicate files during packaging of APK /Users/..../app-debug-unaligned.apk
    Path in archive: META-INF/services/javax.annotation.processing.Processor
	Origin 1: /Users/macbookair/.gradle/caches/modules-2/files-2.1/com.jakewharton/butterknife/7.0.1/d5d13ea991eab0252e3710e5df3d6a9d4b21d461/butterknife-7.0.1.jar
	Origin 2: /Users/macbookair/.gradle/caches/modules-2/files-2.1/io.realm/realm-android/0.82.1/3e4f47bc60063111a375200f866192bf821efa93/realm-android-0.82.1.jar

    You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'META-INF/services/javax.annotation.processing.Processor'
	  }
	}


I tried the suggestion from Android Studio but it's producing too much drawbacks so I cannot use the suggestion.


Any suggestions what to do?

**Comment by ronjumola** [comment]
Okay I found a way. I applied the suggestion by Android Studio and disabled multidex

**Comment by iraupph** [comment]
Had the same problem as @ronjumola and adding the following to `android` in my app's `build.gradle` fixed it.
```
packagingOptions {
    exclude 'META-INF/services/javax.annotation.processing.Processor'
}
```
