### ISSUE TITLE
Unable to use a realm database file created with realm 0.80.1 with 0.82.0

### ISSUE THREAD

**Issue by risayew** [realm/realm-java#1347]
Hello!
My problem actually looks pretty the same as in #1059 .

We have a realm database, which was created using the version 0.80.1 of the realm. 
And we have the following exception after migrating to the version 0.82.0:

    io.realm.exceptions.RealmMigrationNeededException: Index not defined for field 'id'
            at io.realm.UserSurveyRealmProxy.validateTable(UserSurveyRealmProxy.java:136)
            at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:77)
            at io.realm.Realm.initializeRealm(Realm.java:690)
            at io.realm.Realm.createAndValidate(Realm.java:614)
            at io.realm.Realm.create(Realm.java:562)
            at io.realm.Realm.getInstance(Realm.java:527)

The corresponding RealmObject looks like:

public class UserSurvey extends RealmObject {

    @PrimaryKey
    private long id;
    private RealmList<UserAnswer> answers;
    private String status;
    // setters and getters here
}

Can somebody help me, please?

**Comment by emanuelez** [comment]
It's something we mention in the blog post of the release. Since now Realm support indices on int fields you will need a migration block. See here for details :) https://realm.io/news/realm-java-0.82.0/

**Comment by risayew** [comment]
@emanuelez, Thank you very much! the approach works.
