### ISSUE TITLE
Make Realm class to implement an interface

### ISSUE THREAD

**Issue by mvrbensky** [realm/realm-java#1365]
Please could you make the Realm class to implement an interface with standard methods? It is impossible to mock final singleton. So it is almost impossible to unit test anything using Realm. 

Thank you
M.

**Comment by kneth** [comment]
Can you explain your use case? And which interface with which standard methods are to thinking of?

**Comment by mvrbensky** [comment]
Small example how I would like to use JUnit tests with Mockito. In example an Activity is tested. But I use the Realm in some helper methods in separate backend library. So I would invite the JUnit test a lot.

Class to test:
```java
public class AnActivity extends Activity {

    Realm mRealm;

    @Override
    protected void onResume() {
        super.onResume();
        mRealm = getRealm();
    }

    protected Realm getRealm() {
        return Realm.getInstance(this);
    }

    public void save(RealmObject x) {
        mRealm.beginTransaction();
        mRealm.copyToRealmOrUpdate(x);
        mRealm.commitTransaction();
    }

    @Override
    protected void onPause() {
        super.onPause();
        mRealm.close();
    }
}
```

JUnit test:
```java
public class AnActivityTest {

    AnActivity instance;

   // @Mock
    Realm realmMock;

    @Before
    public void setUp() {

        // Init mocks.
        MockitoAnnotations.initMocks(this);

        // Inject mock to the tested activity.
        instance= new AnActivity() {
            @Override
            protected Realm getRealm() {
                return realmMock;
            }
        };
    }

    @Test
    public void testOnPause() {

        // Run on pause.
        instance.onPause();

        // Verify Realm is closed.
        verify(realmMock, times(1)).close();
    }

    @Test
    public void testSave() {
        RealmObject x = new RealmObject() {

        };

        // Run save.
        instance.save(x);

        // Verify object has been stored.
        verify(realmMock, times(1)).beginTransaction();
        verify(realmMock, times(1)).copyToRealmOrUpdate(x);
        verify(realmMock, times(1)).beginTransaction();
    }
}
```

**Comment by mvrbensky** [comment]
And include all public, non static methods in the interface. So it is possible to emulate and verify the real work with Realm in mock object. 

Something like this:
```java

interface RealmInterface {
    void close();

    boolean isAutoRefresh();

    void setAutoRefresh(boolean autoRefresh);

    Table getTable(Class<? extends RealmObject> clazz);

    <E extends RealmObject> void createAllFromJson(Class<E> clazz, JSONArray json);

    <E extends RealmObject> void createOrUpdateAllFromJson(Class<E> clazz, JSONArray json);

    <E extends RealmObject> void createAllFromJson(Class<E> clazz, String json);

    <E extends RealmObject> void createOrUpdateAllFromJson(Class<E> clazz, String json);

    <E extends RealmObject> void createAllFromJson(Class<E> clazz, InputStream inputStream) throws IOException;

    <E extends RealmObject> void createOrUpdateAllFromJson(Class<E> clazz, InputStream in) throws IOException;

    <E extends RealmObject> E createObjectFromJson(Class<E> clazz, JSONObject json);

    <E extends RealmObject> E createOrUpdateObjectFromJson(Class<E> clazz, JSONObject json);

    <E extends RealmObject> E createObjectFromJson(Class<E> clazz, String json);

    <E extends RealmObject> E createOrUpdateObjectFromJson(Class<E> clazz, String json);

    <E extends RealmObject> E createObjectFromJson(Class<E> clazz, InputStream inputStream) throws IOException;

    <E extends RealmObject> E createOrUpdateObjectFromJson(Class<E> clazz, InputStream in) throws IOException;

    void writeCopyTo(File destination) throws IOException;

    void writeEncryptedCopyTo(File destination, byte[] key) throws IOException;

    <E extends RealmObject> E createObject(Class<E> clazz);

    <E extends RealmObject> E copyToRealm(E object);

    <E extends RealmObject> E copyToRealmOrUpdate(E object);

    <E extends RealmObject> List<E> copyToRealm(Iterable<E> objects);

    <E extends RealmObject> List<E> copyToRealmOrUpdate(Iterable<E> objects);

    <E extends RealmObject> RealmQuery<E> where(Class<E> clazz);

    <E extends RealmObject> RealmResults<E> allObjects(Class<E> clazz);

    <E extends RealmObject> RealmResults<E> allObjectsSorted(Class<E> clazz, String fieldName,
                                                             boolean sortAscending);

    <E extends RealmObject> RealmResults<E> allObjectsSorted(Class<E> clazz, String fieldName1,
                                                             boolean sortAscending1,
                                                             String fieldName2, boolean sortAscending2,
                                                             String fieldName3, boolean sortAscending3);

    <E extends RealmObject> RealmResults<E> allObjectsSorted(Class<E> clazz, String fieldNames[],
                                                             boolean sortAscending[]);

    void addChangeListener(RealmChangeListener listener);

    void removeChangeListener(RealmChangeListener listener);

    void removeAllChangeListeners();

    void refresh();

    void beginTransaction();

    void commitTransaction();

    void cancelTransaction();

    void executeTransaction(Realm.Transaction transaction);

    void clear(Class<? extends RealmObject> clazz);

    String getPath();

    RealmConfiguration getConfiguration();
}
```

**Comment by bmunkholm** [comment]
Thanks a lot for the feedback. I'm just wondering about the amount of effort needed to emulate the full database functionality?

**Comment by cmelchior** [comment]
Note that you don't need an interface to use Mockito, us removing the final classifier on the Realm class would also be enough. This will most likely happen as part of #1369.

**Comment by mvrbensky** [comment]
Hallo. 
Yes. It will be possible to use mockito on non final singleton. It would solve my problem.

Thank you. 
M.

**Comment by nhachicha** [comment]
@mvrbensky 
Minimising the accessibility of classes and members is a good practice when it comes to API design ( Effective Java Items: 13, 15 & 16) this also favour composition over inheritance.

The ideal scenario is to have a Realm interface so you can mock, test (or provide a different implementation using Dependency injection in our case).

We're considering this option, but in the mean time you can try [powermock](https://github.com/jayway/powermock/wiki/MockFinal) that allows mocking final classes

Cheers,

**Comment by mvrbensky** [comment]
Hi @nhachicha 

I know power mock. A I use it a lot. But I have not been able to set Android studio to use it. Do you use it in android projects? Shoul I just dig deeper? :-)

Thank you
M.

**Comment by kneth** [comment]
Maybe https://github.com/jaredsburrows/AndroidGradleTemplate can be of inspiration for you

**Comment by cmelchior** [comment]
Hi @mvrbensky 
We will look into creating an example showing how to setup unit testing with Realm. You can see that here #1440.

In the mean time I will close this issue. Currently having an interface provide very little value and adds a lot of extra methods, but we will consider adding it down the line if a stronger use case arise.

**Comment by zaki50** [comment]
I wrote simple unit test which uses PowerMock and robolectric
https://github.com/zaki50/realm_template/blob/master/app/src/test/java/com/example/realm_template/ExampleUnitTest.java

**Comment by mvrbensky** [comment]
Hi @zaki50 
Thank you for the example. I'll try it as soon as possible. :-)

M.

**Comment by jturolla** [comment]
@zaki50 great example! I put everything together in this gist:

https://gist.github.com/jturolla/25489e1b676957197201

**Comment by PhilippeBoisney** [comment]
@zaki50 Thanks for your sample ! I try it, but I've got this error:
`java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/9x/rjxzl3w10p5fntp7vn0l2ssr0000gn/T/android-tmp-robolectric5984527277049390066/app_lib/librealm-jni.dylib`

**Comment by zaki50** [comment]
`RealmConfiguration.Builder` tries to load `librealm-jni` but that native library does not exist on roboletric environment.
Current work-around is to set `io.realm.internal.RealmCore.libraryIsLoaded` to `true` by reflection.

**Comment by PhilippeBoisney** [comment]
@zaki50 Thanks for your response. Did you do that on your sample ? I've checked it but did not find your word-around. Could you please tell me how to do it ?

**Comment by PhilippeBoisney** [comment]
I finally found the work-around that set libraryIsLoaded to true:
```
// Setup Realm to be mocked
mockStatic(Realm.class);
mockStatic(RealmConfiguration.class);
mockStatic(RealmCore.class);

// Create the mock
final Realm mockRealm = mock(Realm.class);
final RealmConfiguration mockRealmConfig = mock(RealmConfiguration.class);

// TODO: Better solution would be just mock the RealmConfiguration.Builder class. But it seems there is some
// problems for powermock to mock it (static inner class). We just mock the RealmCore.loadLibrary(Context) which
// will be called by RealmConfiguration.Builder's constructor.
doNothing().when(RealmCore.class);
RealmCore.loadLibrary(any(Context.class));

// TODO: Mock the RealmConfiguration's constructor. If the RealmConfiguration.Builder.build can be mocked, this
// is not necessary anymore.
whenNew(RealmConfiguration.class).withAnyArguments().thenReturn(mockRealmConfig);

// Anytime getInstance is called with any configuration, then return the mockRealm
when(Realm.getInstance(any(RealmConfiguration.class))).thenReturn(mockRealm);
```

But now, problem is that work-around leads to another issue from Robolectric: https://github.com/robolectric/robolectric/issues/2208

**Issue:**
```
com.thoughtworks.xstream.converters.ConversionException: Cannot convert type org.apache.tools.ant.Project to type org.apache.tools.ant.Project
---- Debugging information ----
class               : org.apache.tools.ant.Project$1
required-type       : org.apache.tools.ant.Project$1
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/next/this$1/outer-class/dependencyResolver/dependencyResolver/project/isLoggingMessage/outer-class
line number         : 410
class[1]            : org.apache.tools.ant.Project
class[2]            : org.robolectric.internal.dependency.MavenDependencyResolver
class[3]            : org.robolectric.internal.dependency.CachedDependencyResolver
class[4]            : org.robolectric.RobolectricGradleTestRunner
class[5]            : org.robolectric.RobolectricTestRunner$HelperTestRunner
class[6]            : org.robolectric.RobolectricTestRunner$HelperTestRunner$1
class[7]            : org.junit.internal.runners.statements.RunBefores
class[8]            : org.powermock.modules.junit4.rule.PowerMockStatement
class[9]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
version             : not available
-------------------------------

	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:439)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
```

It seems that is really impossible to use both Realm & Robolectric together.. Any suggestions here ?

**Comment by zaki50** [comment]
My code worked before, but currently we beed some more work-around to skip loading of native library and checking of transformer application.
Your work-around code seems to work, but may need some more work-arounds.

Another big issue is that Realm transformer which transforms accesses to fields in model classes is not applied when building JVM test. This is tracked as https://github.com/realm/realm-java/pull/2734.

Sorry for inconvenience.

**Comment by tmtrademarked** [comment]
Using PowerMock is not always possible. Why not just make Realm/RealmQuery/RealmResults non final? This would allow developers to mock these classes with straight Mockito/etc.

**Comment by Zhuinden** [comment]
@tmtrademarked I've been thinking a lot about this and considering the Realm API design, I think the only reasonable choice would be wrapping the entire thing with an interface.
