### ISSUE TITLE
mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 115

### ISSUE THREAD

**Issue by n0m0r3pa1n** [realm/realm-java#1380]
We get this in the Crashlytics plugin. It happens on: Android 4.3, Z10 device. Any ideas for a fix?

io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 115
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
       at io.realm.Realm.<init>(Realm.java:199)
       at io.realm.Realm.createAndValidate(Realm.java:585)
       at io.realm.Realm.create(Realm.java:554)
       at io.realm.Realm.getInstance(Realm.java:401)
       at io.realm.Realm.getInstance(Realm.java:358)
       at io.realm.Realm.getInstance(Realm.java:339)

**Comment by bmunkholm** [comment]
Which version of Realm are you using?

**Comment by n0m0r3pa1n** [comment]
compile 'io.realm:realm-android:0.82.0'

**Comment by cmelchior** [comment]
Z10 is a Blackberry device. While Blackberry support Android, they don't use the standard Android kernel. This is a a problem because Realm uses `mremap` which is normally present in that kernel. This means that Realm doesn't work on those devices. Currently there is no work-around, sorry. You can also see https://github.com/realm/realm-java/issues/1287

**Comment by cmelchior** [comment]
@n0m0r3pa1n Sorry, It seemed I was a bit fast. The above statement is true. Blackberry doesn't support `mremap`, but we recently made changes to Realms native layer so it would detect that and fallback to using `mmap()/munmap` which should be supported by Blackberry devices.

Currently we plan to release this as part of `0.83.0`

**Comment by petersnoopy** [comment]
Is this fallback already integrated?

**Comment by cmelchior** [comment]
@petersnoopy Yes, this it should have been released as part of `0.83.0`. Unfortunately we don't have Blackberry devices to verify if it is an issue, even after this fix.

**Comment by n0m0r3pa1n** [comment]
It still happens on Z10. Here is the crash report for 0.83.0 from
Crashlytics:

io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed:
Function not implemented in io_realm_internal_SharedGroup.cpp line 115
       at
io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:68)
       at
io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:87)
       at io.realm.Realm.<init>(Realm.java:151)
       at io.realm.Realm.createAndValidate(Realm.java:279)
       at io.realm.Realm.create(Realm.java:247)
       at io.realm.Realm.getInstance(Realm.java:219)
       at
com.apphunt.app.receivers.InstallReceiver.onReceive(InstallReceiver.java:28)
       at
android.app.ActivityThread.handleReceiver(ActivityThread.java:2424)
       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
       at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5121)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by cmelchior** [comment]
Thank you very much for the feedback. It is interesting that the device stil attempts to call mremap() even though it has other options. We will investigate.

**Comment by petersnoopy** [comment]
Same problem happens with 0.83.1 and 0.84.0 Beta

**Comment by cmelchior** [comment]
@petersnoopy We discovered that we didn't properly detect how Blackberry reports their missing support of `mremap()`. We hope to have a fix ready today.

**Comment by cmelchior** [comment]
@petersnoopy We just released 0.84.0 with a fix for this issue. It is working on our test device. I'll close this issue now, but please reopen if you are seeing more problems in this area.
