### ISSUE TITLE
Realm Unable to Generate Proxies on Android 4.4

### ISSUE THREAD

**Issue by u3amar** [realm/realm-java#1387]
I've been using Realm in my project for the past month or so and it's worked great. 

However, I recently needed to support multipart forms using Volley, which requires that I add httpcore-4.4.1 and httpmime-4.5 to my project (compile "org.apache.httpcomponents:httpmime:4.2.3" and compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5').

When I run on Android 5.0, everything works fine. When I try on Android 4.4, I get a run time error that says that Realm wasn't able to generate proxy classes:

8-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.RiderRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.RouteRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.CarRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.LocationWrapperRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.FareRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.DriverRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.206  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.TicketRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.211  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.PaymentRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.211  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.TripRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:53.211  14577-14577/com.aluvi.android.dev E/dalvikvm﹕ Could not find class 'io.realm.ProfileRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
08-13 13:43:54.771  14577-14632/? E/GooglePlayServicesUtil﹕ The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
08-13 13:43:55.041  14577-14577/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.aluvi.android.dev, PID: 14577
    java.lang.NoClassDefFoundError: io.realm.RiderRealmProxy
            at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:81)
            at io.realm.Realm.initializeRealm(Realm.java:698)
            at io.realm.Realm.createAndValidate(Realm.java:629)
            at io.realm.Realm.create(Realm.java:564)
            at io.realm.Realm.getInstance(Realm.java:537)
            at com.aluvi.android.application.AluviRealm.<init>(AluviRealm.java:32)
            at com.aluvi.android.application.AluviRealm.initialize(AluviRealm.java:27)
            at com.aluvi.android.application.AluviApplication.onCreate(AluviApplication.java:28)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
            at android.app.ActivityThread.access$1600(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

I am running Android Studio 1.3 RC4, am on OS X 10.10.3, and have tried adding the @RealmClass annotation to all my classes.

Help would be much appreciated!

**Comment by u3amar** [comment]
Actually, I resolved this issue by removing multi-dex support.

**Comment by bdbergeron** [comment]
I'm also having this issue today with devices running KitKat. Any object I've created that extends RealmObject results in a NoClassDefFoundError. Also works fine on Lollipop and higher, but unfortunately, disabling multiDex support is not a possibility for my project.

**Comment by Queatz** [comment]
I'm having this issue also on the latest Realm, and can't remove multidex.

**Comment by VedavyasBhatNomadly** [comment]
I had the same problem, but it was because I hadn't set up multidex correctly.
I had this in my `build.gradle`:
    defaultConfig {
        multiDexEnabled true
    }
What you also need to do it is add the multidex support library (com.android.support:multidex:1.0.0) and initialize it in the `Application` class' `onCreate`
`MultiDex.install(getTargetContext());`
More info here: http://developer.android.com/tools/building/multidex.html

**Comment by derohimat** [comment]
resolved.
i just error query

thanks @VedavyasBhatNomadly :+1:
