### ISSUE TITLE
Realm Encryption armv7a.so has compat issues with libhoudini (arm to x86 translator)

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#1398]
I wouldn't consider this a bug in Realm encryption but it may reveal something inside realm encryption that is leading to bugs. 

We are testing not packaging x86.so and instead relying on libhoudini which boundled with almost all x86 android devices to dynamically translate armv7a.so's arm code to x86 code at runtime. 

This works great except with loading/using an encrypted db which causes an infinite loop situation causing test app's UI thread to stall and entire app is unresponsive. 

This is easily reproduce-able on any x86 android. we are using an Asus Zenfone2 devices and Chuwi VI8.

**Comment by kneth** [comment]
We have not tested Realm with Houdini. Is the reason for not packaging the x86 file that your app will be too large to download? We have done optimisations (see https://realm.io/news/how-we-beat-cpp-stl-binary-search/), and it would be better to use our x86 file if you can.

But thanks for bringing it to our attention. We can update the documentation to include information about Realm and Houdini.

**Comment by diegomontoya** [comment]
Our reason is not due to size but because we will be packaging our native libraries which does not support x86 instructions at the moment.

**Comment by kneth** [comment]
We don't have any experience with Houdini, and we haven't been able to find any useful information on how Houdini is implemented. Realm's encryption implementation is using UNIX signals at the C++ level. We try to be a good citizen but if other libraries don't pass on signals, we can easily imagine that Realm without encryption will work while Realm with encryption doesn't.

**Comment by kneth** [comment]
I haven't been able to find any documentation about Houdini. But Realm is loading a few functions using `dl_sym()` for encryption (C++ code). One hypothesis is that `dl_sym` get confused. In another context, we are working on embedding these functions within our `.so` file, and that might also help Houdini.

**Comment by beeender** [comment]
@diegomontoya #1430 might solve this problem (mentioned by kneth above.) If you want, maybe give it a try?

**Comment by beeender** [comment]
@diegomontoya We just released 0.82.2 with some fixes related with encryption. I do feel like it should solve the libhoudini issue as well. If you can, please help us to verify it. Thanks a lot!

**Comment by kneth** [comment]
I'm closing the issue. If the problem with Houdini still persist, please open a new issue.

**Comment by beeender** [comment]
With 0.82.2, This issue still exists. Tested with Asus K013

```
  Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
            at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
            at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
            at io.realm.Realm.<init>(Realm.java:207)
            at io.realm.Realm.createAndValidate(Realm.java:597)
            at io.realm.Realm.create(Realm.java:567)
            at io.realm.Realm.getInstance(Realm.java:540)
            at com.example.cc.enctest.MainActivity.onCreate(MainActivity.java:24)
            at android.app.Activity.performCreate(Activity.java:5387)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2199)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2285)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:149)
            at android.app.ActivityThread.main(ActivityThread.java:5061)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by cmelchior** [comment]
0.85.0 has been released with a new encryption implementation. We need to test this on houdini.
