### ISSUE TITLE
Couldn't load realm-jni from loader

### ISSUE THREAD

**Issue by joey-harward** [realm/realm-java#1422]
I keep getting the following error when calling getInstance(...)

Couldn't load realm-jni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/work.troop.troop.dev-2.apk"],nativeLibraryDirectories=[/data/app-lib/work.troop.troop.dev-2, /vendor/lib, /system/lib]]]: findLibrary returned null
...
at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:114)

**Comment by beeender** [comment]
Hi, I am duplicating this issue to #1421 and closing this one now. Let's track this problem by #1421.
Thanks a lot!

**Comment by NityaNandPandey** [comment]
**How to Resolved this error plz help me ......**  

  Process: com.mycompany.app.middleware.c, PID: 11332
    java.lang.UnsatisfiedLinkError: Couldn't load baimobile_pcsclite_client_jni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mycompany.app.middleware.c-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mycompany.app.middleware.c-1, /vendor/lib, /system/lib]]]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:358)
        at java.lang.System.loadLibrary(System.java:526)
        at com.baimobile.android.pcsclite.client.PcscLite.<clinit>(PcscLite.java:28)
        at com.mycompany.lib.ConnectActivity.onCreate(ConnectActivity.java:69)
        at android.app.Activity.performCreate(Activity.java:5322)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
        at android.app.ActivityThread.access$900(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5511)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
