### ISSUE TITLE
Unit test example

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1440]
We need to add a new test project that shows how you can unit test a project using Realm. It should also show how you can use PowerMock to mock Realm. Mockito does not do that out of the box as the Realm class is final.

JUnit3/4
InstrumentationTests
JVM Unit tests (no use of native code)
Robolectric unit tests (no use of native code)

See #1365

**Comment by jturolla** [comment]
I got the unity tests running with Robolectric and made a gist to make it easier for anyone trying to test realm:

https://gist.github.com/jturolla/25489e1b676957197201

**Comment by cmelchior** [comment]
Fixed by #1833

**Comment by LTroya** [comment]
I'm trying to test realm but I got this exception

    java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/x2/rdkt6_6s26gcw0mjm9w9v9n80000gn/T/android-tmp-robolectric6998859355455526295/app_lib/librealm-jni.dylib

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:200)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:140)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:89)
	at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:390)
	at com.ltroya.movieindex.MovieIndexApp.initDB(MovieIndexApp.java:39)
	at com.ltroya.movieindex.MovieIndexApp.onCreate(MovieIndexApp.java:35)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:165)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:423)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:254)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

This is my config:
    
    private final int DB_SCHEMA_VERSION = 1;
    private final String DB_SCHEMA_NAME = "movie.realm";

    private void initDB() {
        RealmConfiguration realmConfig = new RealmConfiguration.Builder(this)
                .deleteRealmIfMigrationNeeded()
                .name(DB_SCHEMA_NAME)
                .schemaVersion(DB_SCHEMA_VERSION)
                .build();
        Realm.setDefaultConfiguration(realmConfig);
    }

**BaseTest.java**

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);

        if (RuntimeEnvironment.application != null) {
            ShadowApplication shadowApp = Shadows.shadowOf(RuntimeEnvironment.application);
            shadowApp.grantPermissions("android.permission.INTERNET");
        }
    }

**MoviePresenterImplTest.java**

    @RunWith(RobolectricGradleTestRunner.class)
    @Config(constants = BuildConfig.class, sdk = 21)
    @PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
    @PrepareForTest({Realm.class, RealmConfiguration.class, RealmQuery.class,     RealmResults.class, RealmCore.class})
    
    public class MovieListPresenterImplTest extends BaseTest {
        @Rule
        public PowerMockRule rule = new PowerMockRule();
        Realm mockRealm;


        @Override
        public void setUp() throws Exception {
            super.setUp();

            mockRealm = MockSupport.mockRealm();
        }

        @Test
        public void testRealm_GetDefaultInstance() throws Exception {
            assertThat(Realm.getDefaultInstance(), is(mockRealm));
        }
    }

Other dependencies:

    classpath "io.realm:realm-gradle-plugin:1.1.0"
    classpath 'com.android.tools.build:gradle:2.1.0'

The dependencies are the same as **jturolla** example. Is there something that I am doing wrong?

**Comment by LTroya** [comment]
If I comment this two lines: 

    //@RunWith(PowerMockRunner.class)
   //@Config(constants = BuildConfig.class, sdk = 23)

The test passed. But I run this test:

    @Test
    public void testOnEventMainThread_DBEvent_GetMovies() throws Exception {
        RealmResults<Movie> movieList = mockRealmResults();

        when(mockRealm.where(Movie.class).findAll()).thenReturn(movieList);

        when(dbEvent.getMovie()).thenReturn(movie);
        when(dbEvent.getMovieList()).thenReturn(movies);

        when(movies.size()).thenReturn(1);

        when(dbEvent.getType()).thenReturn(DBEvent.GET_EVENT);
        presenter.onEventMainThread(dbEvent);

        assertNotNull(view);
        verify(view).hideProgress();
        verify(view).showUIElements();
        verify(view).setMovies(movieList);
    }

I got a NullPointerException on this line

    when(mockRealm.where(Movie.class).findAll()).thenReturn(movieList);

Method to mock the RealmResult class:

    @SuppressWarnings("unchecked")
    private <T extends RealmObject> RealmResults<T> mockRealmResults() {
        return mock(RealmResults.class);
    }
