### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by shashank090789** [realm/realm-java#1441]
Getting out of memory, following is the stacktrace

java.lang.RuntimeException: Unspecified exception. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 164
       at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:101)
       at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:45)
       at io.realm.Realm.commitTransaction(Realm.java:1449)
       at com.kwench.android.kfit.service.BLESyncService.handleActionSaveActivityDetails(BLESyncService.java:275)
       at com.kwench.android.kfit.service.BLESyncService.onHandleIntent(BLESyncService.java:150)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kneth** [comment]
I'm sorry to hear that you run out of memory. The obvious explanation is that you have many objects and a small device. But an less trivial explanation is that your Realm file is growing too fast. Please take a look at the (FAQ)[https://realm.io/docs/java/latest/#faq] ("Large Realm file size").

When you get such an out-of-memory error, it is safest to terminate the app.

**Comment by kneth** [comment]
I'm closing the issue. If you have further questions, don't hesitate to open a new issue.
