### ISSUE TITLE
NPE in query (getColumnIndices in RealmQuery)

### ISSUE THREAD

**Issue by markini** [realm/realm-java#1465]
This error occurred the first time a few hours ago with `0.83.0-SNAPSHOT`.
I'm convinced that the same code worked yesterday. 
Can't reproduce with `v0.82.2`.

```java
09-10 19:06:25.570  12434-18495/my.sample.app E/ServerTask﹕ Another unexpected Exception
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
            at io.realm.RealmQuery.getColumnIndices(RealmQuery.java:158)
            at io.realm.RealmQuery.equalTo(RealmQuery.java:229)
            at io.realm.RealmQuery.equalTo(RealmQuery.java:213)
            at at.rablzt.nrlogic.data.User.getUser(User.java:76)
            at at.rablzt.nrlogic.servercom.SynchronizeProjectsTask.executeServerCom(SynchronizeProjectsTask.java:65)
            at at.rablzt.nrlogic.servercom.ServerComTask$1.run(ServerComTask.java:53)
            at java.lang.Thread.run(Thread.java:818)
```

The method which fails is this one (line 76 is the query): 
```java
	public static User getUser(Realm realm, String mail) {
		if (mail == null) {
			return null;
		}
		return realm.where(User.class).equalTo("mail", mail).findFirst();
	}
```

The members of the `User` class:
```java
	@PrimaryKey
	private String mail;
	private String firstName;
	private String lastName;
	private String authToken;
	private RealmList<Project> projects;

	@Ignore
	private String fullName;
```

Any ideas?

**Comment by nhachicha** [comment]
Hi @markini thanks for reporting this

should be fixed here #1466

Cheers,

**Comment by markini** [comment]
Okidoki thx

**Comment by lucamtudor** [comment]
I'm running on `0.83.0-SNAPSHOT` and I get the same error even after [#1466](#1466) has been merged into `master`. Yesterday everything was fine...

> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
at io.realm.RealmQuery.getColumnIndices(RealmQuery.java:160)
at io.realm.RealmQuery.contains(RealmQuery.java:865)
at io.realm.RealmQuery.contains(RealmQuery.java:850)
