### ISSUE TITLE
io.realm.exceptions.RealmError is thrown

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#1478]
Why is this error getting thrown?  And how do I fix this?
    
    io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 115
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
       at io.realm.Realm.<init>(Realm.java:207)
       at io.realm.Realm.createAndValidate(Realm.java:597)
       at io.realm.Realm.create(Realm.java:567)
       at io.realm.Realm.getInstance(Realm.java:413)
       at io.realm.Realm.getInstance(Realm.java:370)
       at io.realm.Realm.getInstance(Realm.java:351)
       at com.biggu.shopsavvy.services.StoreService.saveStoresToDB(StoreService.java:78)
       at com.biggu.shopsavvy.services.StoreService.onHandleIntent(StoreService.java:49)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kneth** [comment]
You're using a BlackBerry, right? We have tried to fix it (see #619) but we don't have a physical device to test it. Which version of Realm do you use?

**Comment by lawloretienne** [comment]
This is being reported in Fabric.  It is happening on Android 4.3 on a Z10 and Z30 RIM device.  I'm not sure what those are.

**Comment by lawloretienne** [comment]
Are there any updates on this?

**Comment by cmelchior** [comment]
Z10 and Z30 are both Blackberry devices. Right now those are not supported because `mremap` isn't available on those devices (it is a kernel feature present in the standard Android kernel). However our latest core have added support for other ways of doing memory mapping which as far as we can tell from the Blackberry documentation should work, but currently we are trying to get access to a device to verify this.

**Comment by kneth** [comment]
I will close the issue as it has been covered by other issues.
