### ISSUE TITLE
RealmMigrationNeededException - (Already cleared app data)

### ISSUE THREAD

**Issue by xbroak** [realm/realm-java#1491]
Bit of a strange one here. One of my clients has come back to me that the app is crashing with RealmMigrationNeededException, despite them already clearing the apps data and wiping the old database (The normal cause for this error) even more strangely, in this particular build i have not touched ANY of the models? Is there ANY other possible reason for this error OTHER than the "Old database being different to the new one" ?

**Comment by cmelchior** [comment]
No, we only throw RealmMigrationNeededException if you try to open an existing database file and there is a problem with how you model classes look compared to the file. Do you by any chance have a  bundled file with your app you copy when opening the app for the first time?

The RealmMigrationNeededException should also have a more detailed error message. That should give some hints to what could be wrong.

**Comment by xbroak** [comment]
Thanks for the quick response, here is everything i have on the matter, sadly for my sanity, it provides an obvious point of failure. But deleting the old database does not resolve the issue!?

    Android version

    Android 4.11

Device

Galaxy S3 Mini (golden)


    io.realm.exceptions.RealmMigrationNeededException

    in io.realm.Realm.initializeRealm


    java.lang.RuntimeException: Unable to start activity      ComponentInfo{com.appreciationrewards/com.appreciationrewards.InitialPathActivity}: io.realm.exceptions.RealmMigrationNeededException: Field 'SessionToken' not found for type 'CachedCredit'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
	at android.app.ActivityThread.access$700(ActivityThread.java:134)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4867)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
	at dalvik.system.NativeStart.main(Native Method)
    Caused by: io.realm.exceptions.RealmMigrationNeededException: Field 'SessionToken' not found for type 'CachedCredit'
	at io.realm.Realm.initializeRealm(Realm.java:554)
	at io.realm.Realm.createAndValidate(Realm.java:448)
	at io.realm.Realm.create(Realm.java:418)
	at io.realm.Realm.getInstance(Realm.java:336)
	at io.realm.Realm.getInstance(Realm.java:298)
	at io.realm.Realm.getInstance(Realm.java:279)
	at com.appreciationrewards.Offline.OfflineHandler.<init>(OfflineHandler.java:21)
	at com.appreciationrewards.InitialPathActivity.onCreate(InitialPathActivity.java:23)
	at android.app.Activity.performCreate(Activity.java:5047)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)

**Comment by xbroak** [comment]
Oh and sorry, didnt see your question, i do not!

**Comment by cmelchior** [comment]
`Caused by: io.realm.exceptions.RealmMigrationNeededException: Field 'SessionToken' not found for type 'CachedCredit'`

For some reason it doesn't look like the field `SessionToken` is in your `CachedCredit` class.
If you look in the file `/app/build/intermediates/classes/debug/io/realm/CachedCreditRealmProxy.java` there is a bunch of static methods: `initTable` should create this field and `validateTable` should ensure it is actually present. It is the later that actually throws the error.

**Comment by xbroak** [comment]
Hm, looking at both files now, SessionToken is most certainly present, is it possible that it had some trouble generating the file and a simple "Clean and build" could resolve the issue?

**Comment by cmelchior** [comment]
Deleting the file should work. However i suspect if you try to use "clear app cache" while the app is actually running it might fail deleting any files that are open at that time.

Uninstalling and reinstalling app should work 100% of the time? Do you execute any kind of migration code when opening the app?

**Comment by xbroak** [comment]
Clean and rebuild sorted the issue!
