### ISSUE TITLE
It’s impossible to save the Date, that is not in unix-time range.

### ISSUE THREAD

**Issue by VasyaFromRussia** [realm/realm-java#1513]
When I try to save Date like "1889-01-01", it causes this crash:

```
RecentRepository( 4395): error saving timeline objects
E/RecentRepository( 4395): java.lang.IllegalArgumentException: Date/timestamp is outside valid range
E/RecentRepository( 4395):     at io.realm.internal.UncheckedRow.setDate(UncheckedRow.java:203)
E/RecentRepository( 4395):     at io.realm.ProfileRealmProxy.setBirthday(ProfileRealmProxy.java:434)
E/RecentRepository( 4395):     at io.realm.ProfileRealmProxy.update(ProfileRealmProxy.java:1262)
E/RecentRepository( 4395):     at io.realm.ProfileRealmProxy.copyOrUpdate(ProfileRealmProxy.java:1088)
E/RecentRepository( 4395):     at io.realm.ServerChatMessageRealmProxy.update(ServerChatMessageRealmProxy.java:730)
E/RecentRepository( 4395):     at io.realm.ServerChatMessageRealmProxy.copyOrUpdate(ServerChatMessageRealmProxy.java:655)
E/RecentRepository( 4395):     at io.realm.ServerLobbyRealmProxy.update(ServerLobbyRealmProxy.java:530)
E/RecentRepository( 4395):     at io.realm.ServerLobbyRealmProxy.copyOrUpdate(ServerLobbyRealmProxy.java:425)
E/RecentRepository( 4395):     at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:435)
E/RecentRepository( 4395):     at io.realm.Realm.copyOrUpdate(Realm.java:1584)
E/RecentRepository( 4395):     at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1152)
E/RecentRepository( 4395):     at com.playdayteam.data.model.dao.TimelineItemsDao.bulkSaveTimelineObjects(TimelineItemsDao.java:104)
E/RecentRepository( 4395):     at com.playdayteam.data.repository.RecentRepository.saveTimelineObjects(RecentRepository.java:265)
E/RecentRepository( 4395):     at com.playdayteam.data.repository.RecentRepository.processResponse(RecentRepository.java:171)
E/RecentRepository( 4395):     at com.playdayteam.data.repository.RecentRepository.access$lambda$1(RecentRepository.java)
E/RecentRepository( 4395):     at com.playdayteam.data.repository.RecentRepository$$Lambda$3.call(Unknown Source)
E/RecentRepository( 4395):     at rx.Observable$11.onNext(Observable.java:4417)
E/RecentRepository( 4395):     at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
E/RecentRepository( 4395):     at retrofit.RxSupport$2.run(RxSupport.java:56)
E/RecentRepository( 4395):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/RecentRepository( 4395):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/RecentRepository( 4395):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/RecentRepository( 4395):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/RecentRepository( 4395):     at retrofit.Platform$Android$2$1.run(Platform.java:142)
E/RecentRepository( 4395):     at java.lang.Thread.run(Thread.java:818)
```

**Comment by cmelchior** [comment]
That is a know restriction that is just about to be lifted. See #1510  and #1511.
Until it is implemented you can store your `Date` as a `long` instead.

**Comment by cmelchior** [comment]
Hi @VasyaFromRussia 
We just merged the fix for this to master. So it should be part of the next release.

**Comment by VasyaFromRussia** [comment]
That's cool, thanks a lot!

**Comment by cmelchior** [comment]
No problem :)
