### ISSUE TITLE
Wrong transactional state exception while commitTransaction 

### ISSUE THREAD

**Issue by chonamdoo** [realm/realm-java#1519]
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by: rx.exceptions.OnErrorNotImplementedException: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 179
       at rx.Observable$26.onError(Observable.java:7493)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by: io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 179
       at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:94)
       at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:45)
       at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:103)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:289)
       at io.realm.Realm.commitTransaction(Realm.java:112)
       at com.couchgram.privacycall.utils.CallStickerDecompress.initZip(CallStickerDecompress.java:177)
       at com.couchgram.privacycall.utils.CallStickerDecompress.<init>(CallStickerDecompress.java:56)
       at com.couchgram.privacycall.utils.Utils.setDefaultCallStickerResource(Utils.java:1526)
       at com.couchgram.privacycall.activity.GuideActivity.lambda$onCreate$14(GuideActivity.java:275)
       at com.couchgram.privacycall.activity.GuideActivity.access$lambda$0(GuideActivity.java)
       at com.couchgram.privacycall.activity.GuideActivity$$Lambda$1.call()
       at rx.Observable.unsafeSubscribe(Observable.java:7710)
       at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

![12313213](https://cloud.githubusercontent.com/assets/6761814/10248687/182d8d8a-695c-11e5-868d-93bf37f8ba5c.png)

**Comment by dalinaum** [comment]
Hi @chonamdoo 

You should call `Realm.beginTransaction()` prior to invoking `Realm.commitTransaction()`. Do you use try-catch-finally clauses? Check this please.

**Comment by chonamdoo** [comment]
@dalinaum Thank you

**Comment by dalinaum** [comment]
@chonamdoo I'll close this issue. Feel free to to reopen or create new one if you run into any other problems.
