### ISSUE TITLE
Add realm.inWriteTransaction()

### ISSUE THREAD

**Issue by dalinaum** [realm/realm-java#1549]
```
Caused by: java.lang.IllegalStateException: Cannot cancel a non-write transaction.
      at io.realm.internal.ImplicitTransaction.rollbackAndContinueAsRead(ImplicitTransaction.java:60)
      at io.realm.internal.SharedGroupManager.rollbackAndContinueAsRead(SharedGroupManager.java:110)
      at io.realm.BaseRealm.cancelTransaction(BaseRealm.java:329)
      at io.realm.Realm.cancelTransaction(Realm.java:112)
      at com.couchgram.privacycall.utils.CallStickerDecompress.initZip(CallStickerDecompress.java:122)
      at com.couchgram.privacycall.utils.CallStickerDecompress.<init>(CallStickerDecompress.java:56)
      at com.couchgram.privacycall.utils.Utils.setDefaultCallStickerResource(Utils.java:1526)
      at com.couchgram.privacycall.activity.GuideActivity.lambda$onCreate$12(GuideActivity.java:247)
      at com.couchgram.privacycall.activity.GuideActivity.access$lambda$0(GuideActivity.java)
      at com.couchgram.privacycall.activity.GuideActivity$$Lambda$1.call()
      at rx.Observable.unsafeSubscribe(Observable.java:7710)
      at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
      at java.util.concurrent.FutureTask.run(FutureTask.java:137)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
      at java.lang.Thread.run(Thread.java:856)
```

```
Observable.create(subscriber -> {
           Utils.setDefaultCallStickerResource(getApplicationContext(), true);
           subscriber.onCompleted();
       }).subscribeOn(Schedulers.io()).observeOn(Schedulers.newThread()).subscribe();
```

Developer who reported this: @chonamdoo

**Comment by cmelchior** [comment]
This is happening because `realm.cancelTransaction()` is called without first calling `realm.beginTransaction()`. I cannot see from that observable why that should be the case.

The error message could be a lot better though.

**Comment by dalinaum** [comment]
I think `initZip` can throw an exception before calling `realm.beginTransaction()` and try-catch-finally clause then invoke `realm.cancelTransaction()`.

**Comment by cmelchior** [comment]
Obj-C has this: https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/inWriteTransaction

We should probably add something similar.
