### ISSUE TITLE
Unspecified exception. mmap() failed

### ISSUE THREAD

**Issue by hlllmr1314** [realm/realm-java#1629]
When I repeatedly execute this code。

 RealmConfiguration examBookConfig = (new Builder(file)).name("book_exam" + trId + ".realm").setModules(new ZtyExamBookLibraryModle(), new Object[0]).migration(new ZtyExamBookMigration()).build();
      return Realm.getInstance(examBookConfig);

 java.lang.RuntimeException: An error occured while executing doInBackground()
            at com.zhitongyun.httpclient.utils.AppAsyncTask$3.done(AppAsyncTask.java:318)
            at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.RuntimeException: Unspecified exception. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 100
            at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
            at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
            at io.realm.Realm.<init>(Realm.java:207)
            at io.realm.Realm.createAndValidate(Realm.java:586)
            at io.realm.Realm.create(Realm.java:549)
            at io.realm.Realm.getInstance(Realm.java:522)
            at com.zhitongyun.syncexams.db.ZtyDBHelper.createExamHomeWorkDatabase(ZtyDBHelper.java:74)
            at com.xuehai.xhenglistbrush.db.QuestionDB.create(QuestionDB.java:29)
            at com.xuehai.xhenglistbrush.bookshelf.HomeWorkDetailActivity$LoadDetailModleData.doInBackground(HomeWorkDetailActivity.java:259)
            at com.xuehai.xhenglistbrush.bookshelf.HomeWorkDetailActivity$LoadDetailModleData.doInBackground(HomeWorkDetailActivity.java:249)
            at com.zhitongyun.httpclient.utils.AppAsyncTask$2.call(AppAsyncTask.java:305)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

**Comment by cmelchior** [comment]
It crashes because the devices has run out of memory: `Unspecified exception. mmap() failed: Out of memory `

When you say you repeatedly execute it, what does that mean? If you open a Realm on multiple threads it is important to close it again when done with the thread otherwise you risk running out of memory like you see above.

**Comment by hlllmr1314** [comment]
I found that my database is not closed immediately！I think it should be the reason you say this!

**Comment by dalinaum** [comment]
@hlllmr1314 Great. I'll close this issue. If you encounter further problem, please feel free to reopen.
