### ISSUE TITLE
Upgrading from 0.80.1 to 0.83.1 throws RealmMigrationNeededException

### ISSUE THREAD

**Issue by roms** [realm/realm-java#1638]
We have a static, read only db in our app that worked fine with 0.80.1, but when we try initializing the db in 0.83.1, we get the following exception:

io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
     at io.realm.BaseRealm.migrateRealm(BaseRealm.java:568)
     at io.realm.Realm.migrateRealm(Realm.java:1064)
     at io.realm.Realm.migrateRealm(Realm.java:1053)
    at io.realm.Realm.create(Realm.java:253)
     at io.realm.Realm.getInstance(Realm.java:219)
     at com.breezeworks.application.BaseBreezeApplication.configureRealmDatabase(BaseBreezeApplication.java:610)

Since we haven't changed the schema, I'm not clear how the migration should look?

**Comment by dalinaum** [comment]
Hello @roms.

0.83 has breaking changes. With this release, fields of the types String, Date, and byte[] are now nullable by default.
https://realm.io/news/realm-java-0.83.0/

**Comment by roms** [comment]
Thank you!
