### ISSUE TITLE
Crash: io.realm.exceptions.RealmError: Unrecoverable error. std::exception in io_realm_internal_TableQuery.cpp line 1485

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#1645]
After switching to 0.84.0-SNAPSHOT sometimes I get below exception:
`  io.realm.exceptions.RealmError: Unrecoverable error. std::exception in io_realm_internal_TableQuery.cpp line 1485
                                                          at io.realm.internal.TableQuery.nativeImportHandoverTableViewIntoSharedGroup(Native Method)
                                                          at io.realm.internal.TableQuery.importHandoverTableView(TableQuery.java:495)
                                                          at io.realm.RealmResults.swapTableViewPointer(RealmResults.java:696)
                                                          at io.realm.HandlerController.completedAsyncQueriesUpdate(HandlerController.java:218)
                                                          at io.realm.HandlerController.handleMessage(HandlerController.java:302)
                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)`

**Comment by kneth** [comment]
@roughboy Is it possible for you to share the code?

**Comment by roughboy** [comment]
One important thing  -  I'm using async query  - findAllAsync(). As regarding the code - it will be difficult as I use realm in many places and the exception itself is sporadic. What i suspect is that I am missing to call result.removeChangeListener(callback) - activity may not exist anymore when query is completed.

**Comment by nhachicha** [comment]
Hi @roughboy it's really difficult to say without seeing some code. If you're updating some views from the callback it may try to access a dead activity if the `RealmResults` is not yet GC'd and you didn't remove the callback. This is why it's important to remove callbacks according to your Activity/Fragment's lifecycle.

That being said, I don't think this is behind the native crash. Could be useful if you can identify a path to generate this crash (in a separate app) this will help us reproduce & debug the native crash.

Cheers,

**Comment by dalinaum** [comment]
Hi @roughboy Although we appreciate developers using SNAPSHOT releases, we recommend to use official releases for your app releases.

**Comment by kneth** [comment]
@roughboy I'm closing the issue. You're welcome to reopen or create a new issue if you experience problems.
