### ISSUE TITLE
java.lang.NoClassDefFoundError: io/realm/exceptions/RealmError

### ISSUE THREAD

**Issue by skptl** [realm/realm-java#1656]
I am getting the below logs on some users, unable to produce on my end.

Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.exceptions.RealmError" on path: DexPathList[[zip file "/data/app/com.lettrs.lettrs2-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.lettrs.lettrs2-2, /vendor/lib, /system/lib, /system/lib/arm]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
       at io.realm.internal.SharedGroup.nativeAdvanceRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.advanceRead(SharedGroup.java:86)
       at io.realm.internal.ImplicitTransaction.advanceRead(ImplicitTransaction.java:30)
       at io.realm.internal.SharedGroupManager.advanceRead(SharedGroupManager.java:76)
       at io.realm.BaseRealm.refresh(BaseRealm.java:256)
       at io.realm.Realm.refresh(Realm.java:112)

**Comment by diegomontoya** [comment]
Proguard/Dexguard removed the class due the native side using reflection to find it and it is not smart enough to know this.

-keep class io.realm.exceptions.* { *; }

**Comment by skptl** [comment]
Thanks, I added Proguard/Dexguard rules specified by documentation but this wasn't there.

**Comment by cmelchior** [comment]
Doh, we need to document this.

**Comment by zaki50** [comment]
@cmelchior I've grepped jni code for `"io/realm` and `Lio/realm`.
Some other classes seem to be referenced.

"io/realm/internal/async/BadVersionException"
"io/realm/internal/OutOfMemoryError"
"io/realm/internal/TableSpec"
"io/realm/internal/Mixed"
"io/realm/internal/ColumnType"

**Comment by zaki50** [comment]
I made a separate `Doc` issue #1658.
