### ISSUE TITLE
Error in executeTransaction hides underlying problem

### ISSUE THREAD

**Issue by Wattos** [realm/realm-java#1682]
I usually do all my transactions with the method *executeTransaction*. It seems that if there is a runtime error, the underlying error gets hidden. 

```
public void executeTransaction(Transaction transaction) {
        if (transaction == null)
            throw new IllegalArgumentException("Transaction should not be null");

        beginTransaction();
        try {
            transaction.execute(this);
            commitTransaction();
        } catch (RuntimeException e) {
            cancelTransaction(); <----
            throw new RealmException("Error during transaction.", e);
        } catch (Error e) {
            cancelTransaction();
            throw e;
        }
    }
```
This is part of the stack trace I receive:

```
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime: java.lang.IllegalStateException: Not inside a transaction.
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.internal.ImplicitTransaction.rollbackAndContinueAsRead(ImplicitTransaction.java:71)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.internal.SharedGroupManager.rollbackAndContinueAsRead(SharedGroupManager.java:125)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.BaseRealm.cancelTransaction(BaseRealm.java:348)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.Realm.cancelTransaction(Realm.java:113)
10-27 07:47:00.522 4419-4419/ch.beekeeper.debug E/AndroidRuntime:     at io.realm.Realm.executeTransaction(Realm.java:1037)
```

It is an issue as it hides the runtime exception I would actually like to log

**Comment by cmelchior** [comment]
Hi @Wattos The only reason it would throw an Exception there would be if the transaction was committed or canceled inside your transaction callback. Is there a chance you are doing that?

**Comment by cmelchior** [comment]
That said since we now added `Realm.isInTransaction()` in `0.84.0` we would actually be able to detect that scenario, and should probably do so so we can output a better error message.

**Comment by Wattos** [comment]
@cmelchior No, what actually happens is the following:

```
realm.executeTransaction(
                                new CompositeTransaction(
                                        new ClearResultsTransaction(results),
                                        new CopyTransaction<>(result)));
```

Where:
```
public class ClearResultsTransaction implements Realm.Transaction {

    private RealmResults<?> data;

    public ClearResultsTransaction(RealmResults<?> data) {
        this.data = data;
    }

    @Override
    public void execute(Realm realm) {
        data.clear();
    }
}
```

```
public class CompositeTransaction implements Realm.Transaction{

    private Realm.Transaction[] transactions;

    public CompositeTransaction(Realm.Transaction... transactions) {
        this.transactions = transactions;
    }

    @Override
    public void execute(Realm realm) {
        for (Realm.Transaction transaction : transactions) {
            transaction.execute(realm);
        }
    }
}
```

```
public class CopyTransaction<T extends RealmObject> implements Realm.Transaction {

    private Collection<T> realmObjects;

    public CopyTransaction(T realmObject) {
        this.realmObjects = Collections.singleton(realmObject);
    }

    public CopyTransaction(Collection<T> realmObjects) {
        this.realmObjects = realmObjects;
    }

    @Override
    public void execute(Realm realm) {
        realm.copyToRealmOrUpdate(realmObjects);
    }
}
```

The runtime exception I run into is an illegalstate exception which says that an object was deleted. I need to figure out that the problem is, but it seems that clearing realm results is not working for me

**Comment by Wattos** [comment]
@cmelchior After further investigations, I ran into this because one of my realm change listeners had a problem. This caused the transaction to fail leading to this error.

This would have been immediately obvious if the stack trace was not lost

**Comment by cmelchior** [comment]
@Wattos Ok, thanks for the feedback. We will most likely solve this by:

1) Adding a check for `isInTransaction()` in the catch clause
2) If not in a transaction, avoid calling cancel() as that would hide the original crash, but probably log a warning about it.
3) Throw the original exception
