### ISSUE TITLE
Could not find io.realm.MyApplication$DiscussModuleMediator

### ISSUE THREAD

**Issue by kalpesh-pagalguy** [realm/realm-java#1705]
I'm getting this error in my current project, when I try to run obfuscated app.

```
java.lang.RuntimeException: Unable to create application com.pagalguy.prepathon.app.MyApplication: io.realm.exceptions.RealmException: Could not find io.realm.MyApplication$DiscussModuleMediator
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4544)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:  Caused by: io.realm.exceptions.RealmException: Could not find io.realm.MyApplication$DiscussModuleMediator
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.j.b(Unknown Source)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.pagalguy.prepathon.app.MyApplication.onCreate(Unknown Source)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: io.realm.MyApplication$DiscussModuleMediator
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.forName(Class.java:251)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.forName(Class.java:216)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.j.b(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.pagalguy.prepathon.app.MyApplication.onCreate(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: io/realm/MyApplication$DiscussModuleMediator
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.forName(Class.java:251) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.forName(Class.java:216) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.j.b(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.pagalguy.prepathon.app.MyApplication.onCreate(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.MyApplication$DiscussModuleMediator" on path: DexPathList[[zip file "/data/app/com.test.discuss-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.test.discuss-1, /vendor/lib, /system/lib]]
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.forName(Class.java:251) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.Class.forName(Class.java:216) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.a(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.h.<init>(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at io.realm.j.b(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.pagalguy.prepathon.app.MyApplication.onCreate(Unknown Source) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
10-30 17:34:09.849 24915-24915/com.test.discuss E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

Proguard Config :
```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep class io.realm.exceptions.* { *; }
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

-keep class com.pagalguy.prepathon.app.** {*;}
```

MyApplication Class:
```
public class MyApplication extends Application {
    private RealmConfiguration userConfig;
    private RealmConfiguration discussConfig;
    
    @Override
    public void onCreate() {
        super.onCreate();

        discussConfig = new RealmConfiguration.Builder(MyApplication.getInstance())
                .setModules(new DiscussModule())
                .deleteRealmIfMigrationNeeded()
                .name("discuss.realm")
                .build();

        userConfig = new RealmConfiguration.Builder(MyApplication.getInstance())
                .setModules(new UserModule())
                .name("userContent.realm")
                .build();
    }

    / Create the module
    @RealmModule(classes = {
            RealmUser.class,
            RealmUserComment.class,
            RealmUserDailyQuizExercise.class,
            RealmUserDailyUpdate.class,
            RealmUserPost.class})
    public class UserModule {
    }

    // Create the module
    @RealmModule(classes = {RealmDailyUpdate.class,
            RealmPost.class,
            RealmComment.class,
            RealmUser.class,
            RealmOEmbed.class
    })
    public class DiscussModule {
    }
}
```

I am using Realm 0.82.2 . Please help to resolve this issue.

**Comment by zaki50** [comment]
Hi @kalpesh-pagalguy 

If you define module classes as an inner class, you must add `-keepattributes InnerClasses` to your ProGuard configuration.

And `io.realm.internal.Keep` annotation is very new and not available in `0.82.2`.

So, your ProGuard configuration should be

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keepattributes InnerClasses
-keep class io.realm.exceptions.* { *; }
-keep class io.realm.internal.async.BadVersionException { *; }
-keep class io.realm.internal.OutOfMemoryError { *; }
-keep class io.realm.internal.TableSpec { *; }
-keep class io.realm.internal.ColumnType { *; }
-dontwarn javax.**
-dontwarn io.realm.**

-keep class com.pagalguy.prepathon.app.** {*;}
```

But the most recommended way is avoiding inner class for module classes instead of adding `-keepattributes InnerClasses`.

**Comment by zaki50** [comment]
@kalpesh-pagalguy I'll close this issue. If you encounter further problem, please feel free to reopen this or create another issue.

**Comment by kalpesh-pagalguy** [comment]
@zaki50 Thanks for the support :+1:

**Comment by RaymondZY** [comment]
I have tried to solve the same problem for quite a long time.
In my case, I defined a inner class with Module annotation.
Changing the Module into a regular class solved the problem.

This post is really helpful.
Thanks a lot.

**Comment by Zhuinden** [comment]
Otherwise, modules should have been `public static class`
