### ISSUE TITLE
Realm,createOrUpdateUsingJsonObjec post RealmPrimaryKeyConstraintException exception

### ISSUE THREAD

**Issue by LiuDeng** [realm/realm-java#1774]
Realm,createOrUpdateUsingJsonObject still post io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: -1649667919
exception how can i fix this ?

**Comment by LiuDeng** [comment]
11-14 03:47:24.045 28135-28135/com.qiuduanribao.joke W/System.err: io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0
11-14 03:47:24.045 28135-28135/com.qiuduanribao.joke W/System.err:     at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:675)
11-14 03:47:24.045 28135-28135/com.qiuduanribao.joke W/System.err:     at io.realm.internal.Table.addEmptyRow(Table.java:409)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at io.realm.Realm.createObject(Realm.java:696)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at io.realm.JokeRealmProxy.createOrUpdateUsingJsonObject(JokeRealmProxy.java:550)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at io.realm.DefaultRealmModuleMediator.createOrUpdateUsingJsonObject(DefaultRealmModuleMediator.java:195)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at io.realm.Realm.createOrUpdateAllFromJson(Realm.java:396)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at com.qiuduanribao.joke.data.HttpClient$1.onResponse(HttpClient.java:92)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at com.qiuduanribao.joke.utils.OkHttpUtils$4.run(OkHttpUtils.java:292)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at android.os.Handler.handleCallback(Handler.java:725)
11-14 03:47:24.049 28135-28135/com.qiuduanribao.joke W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at android.os.Looper.loop(Looper.java:137)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5041)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
11-14 03:47:24.053 28135-28135/com.qiuduanribao.joke W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by LiuDeng** [comment]
for (int i = 0; i < json.length(); i++) {
            try {
                configuration.getSchemaMediator().createOrUpdateUsingJsonObject(clazz, this, json.getJSONObject(i), true);
            } catch (Exception e) {
                throw new RealmException("Could not map Json", e);
            }
        }

for this codes i hope to add option to enable throw the exception or just ignore and continue。This will be very useful in production environment。
Thank you for your great jobs。

**Comment by LiuDeng** [comment]
I find it was cause by long cast to int
