### ISSUE TITLE
java.lang.NoClassDefFoundError: io.realm.ScheduleRealmProxy

### ISSUE THREAD

**Issue by Minseung** [realm/realm-java#1779]
When application is starting, "Realm.getInstance(context)" raises exceptions. 

Most phone is not rasing exception, but Vega secret phone(im-a890k) is not working.

Android version is Jellybean(4.2.2) and realm version is (0.82.2)

error info:
    java.lang.NoClassDefFoundError: io.realm.ScheduleRealmProxy
            at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:53)
            at io.realm.Realm.initializeRealm(Realm.java:701)
            at io.realm.Realm.createAndValidate(Realm.java:632)
            at io.realm.Realm.create(Realm.java:567)
            at io.realm.Realm.getInstance(Realm.java:413)
            at io.realm.Realm.getInstance(Realm.java:370)
            at io.realm.Realm.getInstance(Realm.java:351)
            at com.followplus.kr.model.RealmHelper.getInstance(RealmHelper.java:21)
            at com.followplus.kr.activity.BaseActionBarActivity.onCreate(BaseActionBarActivity.java:80)
            at com.followplus.kr.activity.SplashActivity.onCreate(SplashActivity.java:38)
            at com.followplus.kr.activity.SplashActivity_.onCreate(SplashActivity_.java:45)
            at android.app.Activity.performCreate(Activity.java:5214)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1086)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2152)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1242)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by cmelchior** [comment]
Are you using multidex by any chance?

**Comment by Minseung** [comment]
Self answer.
I upgrade android to kitkat and solve the problem. Thanks.

**Comment by Queatz** [comment]
I'm getting this also, same error log on latest Realm.
