### ISSUE TITLE
Realm Error io.realm.Realm.getDefaultMediator

### ISSUE THREAD

**Issue by AndyDavidJoyce** [realm/realm-java#1794]
Hi Guys! 

Ive just recently released an application and checking crashalytics over the last couple of days and ive had a number of crashes relating to this error io.realm.Realm.getDefaultMediator. It seems to crash when i get the instance of realm. Ive pasted the stack trace below.

Fatal Exception: java.lang.ExceptionInInitializerError
       at com.electropages.mobile.classes.AlertBackgroundService.getAllReminders(AlertBackgroundService.java:57)
       at com.electropages.mobile.classes.AlertBackgroundService.onHandleIntent(AlertBackgroundService.java:52) 
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by io.realm.exceptions.RealmException: Could not find io.realm.DefaultRealmModuleMediator
       at io.realm.Realm.getDefaultMediator(Realm.java:256)
       at io.realm.Realm.<clinit>(Realm.java:165) 
       at com.electropages.mobile.classes.AlertBackgroundService.getAllReminders(AlertBackgroundService.java:57) 
       at com.electropages.mobile.classes.AlertBackgroundService.onHandleIntent(AlertBackgroundService.java:52) 
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.lang.ClassNotFoundException: io.realm.DefaultRealmModuleMediator
       at java.lang.Class.classForName(Class.java) 
       at java.lang.Class.forName(Class.java:251) 
       at java.lang.Class.forName(Class.java:216) 
       at io.realm.Realm.getDefaultMediator(Realm.java:251) 
       at io.realm.Realm.<clinit>(Realm.java:165) 
       at com.electropages.mobile.classes.AlertBackgroundService.getAllReminders(AlertBackgroundService.java:57) 
       at com.electropages.mobile.classes.AlertBackgroundService.onHandleIntent(AlertBackgroundService.java:52) 
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:136) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 
Caused by java.lang.NoClassDefFoundError: io/realm/DefaultRealmModuleMediator
       at java.lang.Class.classForName(Class.java) 
       at java.lang.Class.forName(Class.java:251) 
       at java.lang.Class.forName(Class.java:216) 
       at io.realm.Realm.getDefaultMediator(Realm.java:251) 
       at io.realm.Realm.<clinit>(Realm.java:165) 
       at com.electropages.mobile.classes.AlertBackgroundService.getAllReminders(AlertBackgroundService.java:57) 
       at com.electropages.mobile.classes.AlertBackgroundService.onHandleIntent(AlertBackgroundService.java:52) 
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:136) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 
Caused by java.lang.ClassNotFoundException: Didn't find class "io.realm.DefaultRealmModuleMediator" on path: DexPathList[[zip file "/data/app/com.electropages.mobile-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.electropages.mobile-2, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) 
       at java.lang.ClassLoader.loadClass(ClassLoader.java:497) 
       at java.lang.ClassLoader.loadClass(ClassLoader.java:457) 
       at java.lang.Class.classForName(Class.java) 
       at java.lang.Class.forName(Class.java:251) 
       at java.lang.Class.forName(Class.java:216) 
       at io.realm.Realm.getDefaultMediator(Realm.java:251) 
       at io.realm.Realm.<clinit>(Realm.java:165) 
       at com.electropages.mobile.classes.AlertBackgroundService.getAllReminders(AlertBackgroundService.java:57) 
       at com.electropages.mobile.classes.AlertBackgroundService.onHandleIntent(AlertBackgroundService.java:52) 
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:136) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 

Any help would be brilliant!

**Comment by cmelchior** [comment]
Extra information in StackOverflow as well: http://stackoverflow.com/questions/33775087/realm-error-io-realm-realm-getdefaultmediator?noredirect=1#comment55320261_33775087

How are users installing your app? Are they allowed to move it to the SDCard? We have seen some other issues that might be attributed to apps being allowed to run from external storage?

**Comment by AndyDavidJoyce** [comment]
Hi Christian, 

Thank you so much for the support! really appreciate it. Im currently using v0.80.3. 

With regards to the migration. This is the code i currently have: 

try {
            mRealmInstance = Realm.getInstance(mContext);
       
        } catch (RealmMigrationNeededException e) {
            Log.e(TAG, e.toString());
            Realm.deleteRealmFile(mContext);
            mRealmInstance = Realm.getInstance(mContext);
        }

I have not set anything that would stop them from moving it onto a SDCard so perhaps? Saying that iv'e never had the issue on previous versions.

**Comment by cmelchior** [comment]
That code looks a bit insecure. `Realm.deleteRealmFile()` will return false if it cannot delete the file, which is the case if another thread has opened the Realm file, and if the helper class you have that in is not properly `synchronized` you might also run into race conditions.

I you want to just delete the Realm in case of migrations I would recommend doing the below instead.

```
RealmConfiguration config = new RealmConfiguration.Builder(context)
  .deleteRealmIfConfigurationNeeded()
  .build()

Realm.getInstance(config);
``` 

You can read more about RealmConfiguration here: https://realm.io/docs/java/latest/#configuring-a-realm

**Comment by AndyDavidJoyce** [comment]
Brilliant i will make sure i implement it that way instead. So in your opinion do you think this is what is causing both the migration issue and the io.realm.Realm.getDefaultMediator issue?

**Comment by cmelchior** [comment]
No, the above line will only fix 
```
http://stackoverflow.com/questions/33775087/realm-error-io-realm-realm-getdefaultmediator?noredirect=1#comment55320261_33775087
```
The other one is a bit of mystery. We have seen it reported a few times, but nobody including ourselves have been able to reproduce it. The closest explanation so far has been class loader issues on individual devices, which could happen if the device was running from external storage. 

But that should only be possible if you set `android:installLocation` to either `auto` or `preferExternal` which it sounds like you haven't.

I won't rule out Multidex as the source though as apps running Android 5 uses ART which doesn't have multidex issues.

**Comment by AndyDavidJoyce** [comment]
Great, Well i will implement the code for the migration. Ive just implemented the code from the google developer guide which fixes the multidexing issuing on android 4 devices. I will post back in a few days to let you know if the issue is still occuring. 

Again Christian thanks for all of your help!

**Comment by cmelchior** [comment]
No problem. Good luck and let us know if it works.

**Comment by AndyDavidJoyce** [comment]
One quick question. Is RealmConfiguration in a later version of Realm? as i said im running on 0.80.3 but if theres no risk of too many issue occuring then i will update the library now.

**Comment by cmelchior** [comment]
It was introduced in `0.81.0`. Our current version is `0.84.2`.
You can see the changelog for all the releases here: https://github.com/realm/realm-java/blob/master/changelog.txt

In general we recommend upgrading, but that is of course up to you.
