### ISSUE TITLE
App crashes when calling Realm.getInstance(context)

### ISSUE THREAD

**Issue by androuis** [realm/realm-java#1800]
Note: I am using compile 'io.realm:realm-android:0.84.2'.

Calling Realm.getInstance(context) crashes the app. Here is the log:
11-27 07:41:10.469 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: VFY: unable to find class referenced in signature (Lio/realm/Realm;)
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: VFY: unable to find class referenced in signature (Ltodolist/TodoList;)
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Could not find method io.realm.Realm.getInstance, referenced from method com.andreibacalu.android.itodo.task.AddTaskFragment.onAttach
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: VFY: unable to resolve static method 63502: Lio/realm/Realm;.getInstance (Landroid/content/Context;)Lio/realm/Realm;
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: VFY: replacing opcode 0x71 at 0x0003
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Could not find method android.app.Fragment.onAttach, referenced from method com.andreibacalu.android.itodo.task.AddTaskFragment.onAttach
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: VFY: unable to resolve virtual method 195: Landroid/app/Fragment;.onAttach (Landroid/content/Context;)V
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: VFY: replacing opcode 0x6f at 0x0000
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Could not find method io.realm.Realm.getInstance, referenced from method com.andreibacalu.android.itodo.task.AddTaskFragment.onCreate
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: VFY: unable to resolve static method 63502: Lio/realm/Realm;.getInstance (Landroid/content/Context;)Lio/realm/Realm;
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: VFY: replacing opcode 0x71 at 0x0007
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Could not find method io.realm.Realm.close, referenced from method com.andreibacalu.android.itodo.task.AddTaskFragment.onDestroy
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: VFY: unable to resolve virtual method 63499: Lio/realm/Realm;.close ()V
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0005
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Failed resolving Lcom/andreibacalu/android/itodo/task/AddTaskFragment$2; interface 9337 'Lio/realm/Realm$Transaction;'
11-27 07:41:10.474 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: Link of class 'Lcom/andreibacalu/android/itodo/task/AddTaskFragment$2;' failed
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: DexOpt: unable to opt direct call 0x4dae at 0x0d in Lcom/andreibacalu/android/itodo/task/AddTaskFragment;.onAttach
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Failed resolving Lcom/andreibacalu/android/itodo/task/AddTaskFragment$3; interface 9337 'Lio/realm/Realm$Transaction;'
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: Link of class 'Lcom/andreibacalu/android/itodo/task/AddTaskFragment$3;' failed
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: DexOpt: unable to opt direct call 0x4db0 at 0x0d in Lcom/andreibacalu/android/itodo/task/AddTaskFragment;.onAttach
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo I/dalvikvm: Failed resolving Lcom/andreibacalu/android/itodo/task/AddTaskFragment$1; interface 9337 'Lio/realm/Realm$Transaction;'
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: Link of class 'Lcom/andreibacalu/android/itodo/task/AddTaskFragment$1;' failed
11-27 07:41:10.479 3452-3452/com.andreibacalu.android.itodo D/dalvikvm: DexOpt: unable to opt direct call 0x4dac at 0x11 in Lcom/andreibacalu/android/itodo/task/AddTaskFragment;.onCreate
11-27 07:41:10.489 3452-3452/com.andreibacalu.android.itodo D/AndroidRuntime: Shutting down VM
11-27 07:41:10.489 3452-3452/com.andreibacalu.android.itodo W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41cc9700)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime: FATAL EXCEPTION: main
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime: java.lang.NoClassDefFoundError: io.realm.Realm
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at com.andreibacalu.android.itodo.task.AddTaskFragment.onAttach(AddTaskFragment.java:81)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:862)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1075)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.BackStackRecord.run(BackStackRecord.java:682)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1455)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:730)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5419)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
11-27 07:41:10.494 3452-3452/com.andreibacalu.android.itodo E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by cmelchior** [comment]
It looks like a problem with the dex file. Are you using Multidex?

**Comment by androuis** [comment]
Yes.

**Comment by cmelchior** [comment]
For some reason or another it seems like the Multidex isn't doing its job properly. The problem is also mentioned here: http://developer.android.com/tools/building/multidex.html#limitations

We haven't heard of others having problems with Multidex, so perhaps it is just a unique combination of circumstances in your case. 

E.g when is the first time you access anything Realm related. Is it inside a Fragment/Activity or in something called when starting the app?

**Comment by androuis** [comment]
I tried calling Realm.getInstance(context) from both activity and fragment and the result is the same. Moreover, setting the default configuration in the application class (RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build(); Realm.setDefaultConfiguration(realmConfiguration);) also crashes with this exception:
java.lang.NoClassDefFoundError: io.realm.internal.SharedGroup$Durability
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:265)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:246)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at com.andreibacalu.android.itodo.TodoApplication.onCreate(TodoApplication.java:29)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.ActivityThread.access$1400(ActivityThread.java:159)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5419)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
11-27 08:16:28.309 11179-11179/com.andreibacalu.android.itodo E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

Anyway, I'll try to remove the multidex and compile only the really necessary APIs from google play services.

**Comment by androuis** [comment]
Yes, the multidex was the problem. Thanks :)

**Comment by pankajnimgade** [comment]
@androuis 

Hi, were you able to fix the issue. I am getting this issue but I don't think this is a multi dex issue.

this is my log cat when I call,

        Realm myRealm = Realm.getInstance(getApplicationContext());


E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.ExceptionInInitializerError
                                                     at relam.list.activities.RealmExampleOneActivity.initializeUI(RealmExampleOneActivity.java:34)
                                                     at relam.list.activities.RealmExampleOneActivity.onCreate(RealmExampleOneActivity.java:28)
                                                     at android.app.Activity.performCreate(Activity.java:5104)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.NoClassDefFoundError: io.realm.internal.async.RealmThreadPoolExecutor
                                                     at io.realm.BaseRealm.<clinit>(BaseRealm.java:59)
                                                     at relam.list.activities.RealmExampleOneActivity.initializeUI(RealmExampleOneActivity.java:34) 
                                                     at relam.list.activities.RealmExampleOneActivity.onCreate(RealmExampleOneActivity.java:28) 
                                                     at android.app.Activity.performCreate(Activity.java:5104) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511)

**Comment by androuis** [comment]
Yes, I selectively included google play services into my app: https://developers.google.com/android/guides/setup

**Comment by pankajnimgade** [comment]
@androuis, I already have google play services included as dependency but the issues still persist, I have more than 50 activities in that project does that make any sense,  Kindly help me understand what is going wrong here

**Comment by androuis** [comment]
The problem is that Realm has some problems when using multidex. In order to avoid that, try to not include the whole google play service library, but just the apis you need from it.

**Comment by zhangshoudgs** [comment]
I just want to add a new jar package.(core-3.1.0.jar,pushservice-5.0.0.66.jar),Would have reported an erro:
 Could not find class 'io.realm.RealmConfiguration$Builder
or Could not find method io.socket.client.Socket.connected.
All tips:
java.lang.NoClassDefFoundError
io.realm.RealmConfiguration$Builder
com.jw.iworker.db.DbHandler.getRealmConfiguration(DbHandler.java:77)
com.jw.iworker.db.DbHandler.getRealm(DbHandler.java:44)
com.jw.iworker.module.homepage.ui.HomePageActivity.onCreate(HomePageActivity.java:58)
android.app.Activity.performCreate(Activity.java:5304)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331)
android.app.ActivityThread.access$1000(ActivityThread.java:143)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
android.app.ActivityThread.main(ActivityThread.java:5291)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
dalvik.system.NativeStart.main(Native Method)

_private static RealmConfiguration getRealmConfiguration() {
        RealmConfiguration realmConfiguration = null;
        try {
            realmConfiguration= new RealmConfiguration.Builder(IworkerApplication.getContext())
                    .deleteRealmIfMigrationNeeded()
                    .name(getDataBaseName())
                    .build();
        }catch (Exception e){
            e.printStackTrace();
        }
        return realmConfiguration;
    }_
Can you tell me how you solve it?

**Comment by kevinvanmierlo** [comment]
@cmelchior I'm not using multidex and see these crashes come in. 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.test/com.test.test.ui.activities.FirstActivity}: java.lang.IllegalStateException: Call `Realm.init(Context)` before calling this method.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3352)
	at android.app.ActivityThread.access$1100(ActivityThread.java:223)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7231)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalStateException: Call `Realm.init(Context)` before calling this method.
	at io.realm.Realm.getDefaultInstance(Realm.java:207)
	at com.test.test.ui.activities.FirstActivity.onCreate(FirstActivity.java:77)
	at android.app.Activity.performCreate(Activity.java:6877)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3209)
	... 9 more
```

Over 20 crashes in the last month.

Some devices on which this happens:

- Samsung SM-J510FN
- Sony E6653
- Samsung SM-G900F
- Samsung SM-N910C
- Motorola Moto G (4)
- Lenovo P2a42

It looks like the `Realm.init(context)` doesn't get executed right in the Application class. What I'm going to do is in my first activity add a try catch for `IllegalStateException` and then do the `Realm.init(context)` again. This is far from ideal though.

Anybody knows what this might be?
