### ISSUE TITLE
IllegalStateException: Not inside a transaction.

### ISSUE THREAD

**Issue by xufan** [realm/realm-java#1812]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company/com.company.ui.MainActivity}: java.lang.IllegalStateException: Not inside a transaction.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3740)
	at android.app.ActivityThread.access$900(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: Not inside a transaction.
	at io.realm.internal.ImplicitTransaction.rollbackAndContinueAsRead(ImplicitTransaction.java:71)
	at io.realm.internal.SharedGroupManager.rollbackAndContinueAsRead(SharedGroupManager.java:125)
	at io.realm.BaseRealm.cancelTransaction(BaseRealm.java:348)
	at io.realm.Realm.cancelTransaction(Realm.java:113)
	at io.realm.Realm.executeTransaction(Realm.java:1040)
	at com.company.ui.MainActivity.onCreate(MainActivity.java:197)
	at android.app.Activity.performCreate(Activity.java:5248)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
	... 12 more

This is my code in MainActivity.onCreate() method;
```java
 RealmConfiguration configuration = new RealmConfiguration.Builder(this)
                .name("DbName").deleteRealmIfMigrationNeeded().build();
 Realm.setDefaultConfiguration(configuration);
 Realm realm = Realm.getDefaultInstance();
 realm.executeTransaction(new Realm.Transaction() {
       @Override
        public void execute(Realm realm) {
            ///do someting
        }
 });
 realm.close();
```
line 197:
```java
realm.executeTransaction(new Realm.Transaction() {
```

**Comment by zaki50** [comment]
Hi @xufan 

I suspect you called `Realm.commitTransaction()` or `Realm.cancelTransaction()` in `public void execute(Realm realm)`.

Is that the case?

**Comment by xufan** [comment]
@zaki50 No ,In method 
```java 
public void execute(Realm realm)
```
I Just ues ``` findFirst() ``` realmObject if null ``` createObject() ``` and modify it's value,didn't call ``` Realm.commitTransaction() ``` or ```Realm.cancelTransaction() ```

**Comment by zaki50** [comment]
What version of Realm are you using?

**Comment by xufan** [comment]
@zaki50 version 0.84.1

**Comment by zaki50** [comment]
Can you share the implementation of `Realm.Transaction` class here or private way (help@realm.io)?

**Comment by xufan** [comment]
Yes,here is my Transaction Code:
```
User user = realm.where(User.class).equalTo(User.Key_ObjectId, userId).findFirst();
if (user == null) {
   user = realm.createObject(User.class);
   user.setId(userId);
}
Recommend recommend = realm.where(Recommend.class).equalTo(RECOMMEND_KEY,id).findFirst();
if (recommend == null) {
   recommend = realm.createObject(Recommend.class);
   recommend.setUser_id(Account.getId());
}
```

**Comment by Zhuinden** [comment]
In order to modify the fields of a RealmObject that is associated with a Realm instance, you need to use `beginTransaction()` and `commitTransaction()` methods.

**Comment by zaki50** [comment]
@xufan Hmm, nothing wrong in your code.

Can you reproduce this issue?

**Comment by xufan** [comment]
As you say noting wrong with the code in Transaction.I'm confused about this issue , according to the BugReport it just appeared in very few cases.
Is that ok,modify two realmObject in one ```execute()``` method like above code.Or it can cause this issue?

**Comment by kneth** [comment]
@xufan you can do as many changes in one transaction as you like. But keep in mind that transactions mutually block each other, and a long lived transaction in one thread might course the file size to increase (see "Large Realm file size" section in https://realm.io/docs/java/latest/#faq).
