### ISSUE TITLE
Permission denied when calling getInstance

### ISSUE THREAD

**Issue by KynoYang** [realm/realm-java#1813]
Below is the log I received recently when calling Realm.getInstance(). It doesn't happen on all devices. I guess maybe I did something wrong. However, I have no idea where it is. Anyone know anything, please help me figure it out. Thanks very much!
```
Caused by io.realm.exceptions.RealmIOException: Failed to open . Permission denied. open() failed: Permission denied
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:90)
       at io.realm.Realm.<init>(Realm.java:151)
       at io.realm.Realm.createAndValidate(Realm.java:282)
       at io.realm.Realm.create(Realm.java:246)
       at io.realm.Realm.getInstance(Realm.java:219)
```

**Comment by beeender** [comment]
What `RealmConfiguration` are you using when calling `Realm.getInstance`?

**Comment by beeender** [comment]
Checked with @KynoYang offline, it might caused by the illegal character in the Realm name. Not sure if CR/LF in the file name will cause problem on some devices. More testing is going on.

**Comment by KynoYang** [comment]
Thanks @beeender. The problem is might because the realm file name I used contains "\r\n". But I need to do more test on those devices that reported the problem. 

So, I close this issue now.
