### ISSUE TITLE
Fix flaky unit tests

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1880]
```
io.realm.RealmAsyncQueryTests > testFindFirstAsync[Nexus 9 - 5.0.1] [31mFAILED [0m
	junit.framework.AssertionFailedError
	at io.realm.TestHelper.awaitOrFail(TestHelper.java:646)

io.realm.RealmTest > testInternalRealmChangedHandlersRemoved[Nexus 9 - 5.0.1] [31mFAILED [0m
	junit.framework.AssertionFailedError: expected:<1> but was:<2>
	at io.realm.RealmTest.testInternalRealmChangedHandlersRemoved(RealmTest.java:190)
```

**Comment by cmelchior** [comment]
It has not been possible to reproduce these. First failure might just be a timeout, and second failure is due to the first. Closing this for now, but will keep an eye out if they reappear,
