### ISSUE TITLE
Cant migrate primarykey from 0.82.2 to 0.86.0 because of field supporting null

### ISSUE THREAD

**Issue by deanezra** [realm/realm-java#1902]
Hi,

I have a table with a primary key in 0.82.2 android app with following field:

```
// Each uid is generated using UUID strings:
@PrimaryKey
private String uid;
```

Today I have updated to Realm 0.86.0 to get the new migration api (as I added another table and wanted to migrate existing users data).

However, it seems that the existing data from 0.82.2 realm file allowed the primarykey uid to be nullable (realm tells me this when I run app without any migration for the uid field. 

So, I tried to create a new primary key field called 'id' and then migrate the non null values overs using the following code:

```
dogSchema.removePrimaryKey();
dogSchema.addField("id", String.class, FieldAttribute.PRIMARY_KEY) 
                    .transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject obj) {

                            String oldUid = obj.getString("uid");

                            // Bring over any non null uids, generate new id to replace nulls
                            if (oldUid == null || oldUid.equals("")) {

                                // Null, so generate one as primarykey doesnt allow nulls:
                                String newUid = RealmUtils.generateUID();
                                Log.d(TAG, "### New filler dog uid = " + newUid);
                                obj.setString("id", newUid);
                            } else {
                                Log.d(TAG, "### Old dog uid = " + oldUid);
                                obj.setString("id", oldUid);

                            }
                        }
                    });

            dogSchema.removeField("uid");
```

However, after the migration runs, Realm throws exception stating: Field 'id' cant be a primaryKey as existing realm file already contains duplicate data. Even though I can see each ID value is different.

If I change the addfield line for id to be without the PrimaryKey attribute (see below), I get further, but hit another exception saying id cant be primary key, presumably because my Model has @PrimaryKey annotation.

```
dogSchema.addField("id", String.class)
```

How can I migrate the primary key over to Realm 0.86.0?

**Comment by deanezra** [comment]
I have also posted above as question on stackoverflow, just incase I am doing something stupid ;-)

http://stackoverflow.com/questions/34141155/realm-android-cant-migrate-primarykey-from-0-82-2-to-0-86-0-because-of-field-su

**Comment by kneth** [comment]
@deanezra See comment at stackoverflow.

**Comment by cmelchior** [comment]
Hi @deanezra I commented on SO, but if your current uid field might contain null values you should be able to do it like this (without needing an additional field):

```
        dogSchema.transform(new RealmObjectSchema.Function() {
            @Override
            public void apply(DynamicRealmObject obj) {
                String oldUid = obj.getString("uid");
                // Bring over any non null uids, generate new id to replace nulls
                if (oldUid == null || oldUid.equals("")) {
                    // Null, so generate one as primarykey doesnt allow nulls:
                    String newUid = RealmUtils.generateUID();
                    Log.d(TAG, "### New filler dog uid = " + newUid);
                    obj.setString("id", newUid);
                } else {
                    Log.d(TAG, "### Old dog uid = " + oldUid);
                    obj.setString("id", oldUid);
                }
            }
        })
        .setNullable("uid", false);
```

**Comment by deanezra** [comment]
thanks @cmelchior, I will give it a try and reply back with result.

**Comment by deanezra** [comment]
@cmelchior so I get a illegalstate exception with your suggested code: "java.lang.IllegalStateException: Field is already required: uid"

I dont have @Required on uid, but I assume the @PrimaryKey annotation infers it?

```
I/CrashlyticsCore(17105): Initializing Crashlytics 2.3.5.79
D/MyApplication(17105): getRealmConfig fired.
D/MyApplication(17105): getRealmConfig: config is null, creating new one. Possibly MIGRATING.
I/Migration(17105): Woof Woof Migrate fired. oldVersion:0, newVersion:1
I/Migration(17105): Woof Woof Migrating schema from oldversion 0, to 1 (adding ExpenditureEntry table)...
D/Migration(17105): ### Old dog uid = 4aff9670-19f1-471d-949d-722b14e3f811
D/AndroidRuntime(17105): Shutting down VM
W/ActivityManager(  756): getRunningAppProcesses: caller 10330 does not hold REAL_GET_TASKS; limiting output
--------- beginning of crash
E/AndroidRuntime(17105): FATAL EXCEPTION: main
E/AndroidRuntime(17105): Process: com.spottedparrot.android.woofwoof, PID: 17105
E/AndroidRuntime(17105): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.spottedparrot.android.woofwoof/com.spottedparrot.android.woofwoof.SplashScreenActivity}: java.lang.IllegalStateException: Field is already required: uid
E/AndroidRuntime(17105): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime(17105): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime(17105): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(17105): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(17105): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17105): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17105): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(17105): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17105): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17105): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(17105): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(17105): Caused by: java.lang.IllegalStateException: Field is already required: uid
E/AndroidRuntime(17105): 	at io.realm.RealmObjectSchema.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.RealmObjectSchema.b(Unknown Source)
E/AndroidRuntime(17105): 	at com.spottedparrot.android.woofwoof.realmdb.Migration.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.BaseRealm$2.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.RealmCache.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.BaseRealm.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.Realm.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.Realm.c(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.Realm.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.RealmCache.a(Unknown Source)
E/AndroidRuntime(17105): 	at io.realm.Realm.b(Unknown Source)
E/AndroidRuntime(17105): 	at com.spottedparrot.android.woofwoof.MyApplication.a(Unknown Source)
E/AndroidRuntime(17105): 	at com.spottedparrot.android.woofwoof.SplashScreenActivity.onCreate(Unknown Source)
E/AndroidRuntime(17105): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(17105): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(17105): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime(17105): 	... 10 more
```

**Comment by deanezra** [comment]
Here's my Dog Model class, its now same before and after migrate.

```
public class Dog extends RealmObject {

    // This was removed in migration to schema v1
    @PrimaryKey
    private String uid;

    /**
     * Path to a image to be used for the dogs profile picture
     */
    private String profileImagePath;

    /**
     * Common Name of the dog
     */
    @Required
    private String commonName;

    /**
     * Official dog name is the Breeder name of dog (this is usaully the name that the breeder puts on the dogs
     * pedigree family tree and other kennel certificates.
     */
    private String officialName;

    /**
     * Pedigree
     */
    private String pedigree;

    /**
     * Fathers name
     */
    private String fathersName;

    /**
     * Mothers name
     */
    private String mothersName;

    /**
     * Date of Birth (Mysql timestamp as string)
     */
    private String dob;

    /**
     * Kennel club id
     */
    private String kennelClubId;

    /**
     * Purchase date
     */
    private String purchaseDate;

    /**
     * Gender (Bitch = 0 Dog=1)
     */
    private int gender;

    /**
     * Eye colour
     */
    private String eyeColour;

    /**
     * Breeders name
     */
    private String breedersName;

    /**
     * Country of birth
     */
    private String countryOfBirth;

    /**
     * Dog colour
     */
    private String colour;

    // Getters and setters:

    public String getUid() {
        return uid;
    }
    public void setUid(String id) {
        this.uid = uid;
    }
    
    public String getKennelClubId() {
        return kennelClubId;
    }

    public void setKennelClubId(String kennelClubId) {
        this.kennelClubId = kennelClubId;
    }

    public String getProfileImagePath() {
        return profileImagePath;
    }

    public void setProfileImagePath(String profileImagePath) {
        this.profileImagePath = profileImagePath;
    }

    public String getCountryOfBirth() {
        return countryOfBirth;
    }

    public void setCountryOfBirth(String countryOfBirth) {
        this.countryOfBirth = countryOfBirth;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }

    public String getOfficialName() {
        return officialName;
    }

    public void setOfficialName(String officialName) {
        this.officialName = officialName;
    }

    public String getPedigree() {
        return pedigree;
    }

    public void setPedigree(String pedigree) {
        this.pedigree = pedigree;
    }

    public String getFathersName() { return fathersName; }

    public void setFathersName(String fathersName) { this.fathersName = fathersName; }

    public String getMothersName() { return mothersName; }

    public void setMothersName(String mothersName) { this.mothersName = mothersName; }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public String getPurchaseDate() {
        return purchaseDate;
    }

    public void setPurchaseDate(String purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public String getEyeColour() {
        return eyeColour;
    }

    public void setEyeColour(String eyeColour) {
        this.eyeColour = eyeColour;
    }

    public String getBreedersName() {
        return breedersName;
    }

    public void setBreedersName(String breedersName) {
        this.breedersName = breedersName;
    }

    public String getColour() {
        return colour;
    }

    public void setColour(String colour) {
        this.colour = colour;
    }
}

```

**Comment by cmelchior** [comment]
Yes, it does. That means leaving out `setNullable` should work?

**Comment by deanezra** [comment]
@cmelchior Yes it works when I remove the 'setNullable'. Thank you for your help, much appreciated. Plus the new migration api is much improved over old one.
