### ISSUE TITLE
no non-static method "Lio/realm/exceptions/RealmError;.<init>(Ljava/lang/String;)V"

### ISSUE THREAD

**Issue by rshah** [realm/realm-java#1936]
In my Crashlytics report, i received these errors(i'm using 0.84.1):
Is there a way to solve these errors? 
Please let me know if you need more information.
```
Fatal Exception: java.lang.NoSuchMethodError: no non-static method "Lio/realm/exceptions/RealmError;.<init>(Ljava/lang/String;)V"
       at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
       at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:60)
       at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:117)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:312)
       at io.realm.Realm.commitTransaction(Realm.java:111)
       at io.realm.BaseRealm.migrateRealm(BaseRealm.java:611)
       at io.realm.Realm.migrateRealm(Realm.java:1162)
       at io.realm.Realm.migrateRealm(Realm.java:1151)
       at io.realm.Realm.create(Realm.java:250)
       at io.realm.Realm.getDefaultInstance(Realm.java:200)
```
And
```
Fatal Exception: java.lang.NoSuchMethodError: no non-static method "Lio/realm/exceptions/RealmError;.<init>(Ljava/lang/String;)V"
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.(SharedGroup.java)
       at io.realm.internal.SharedGroupManager.(SharedGroupManager.java)
       at io.realm.BaseRealm.(BaseRealm.java)
       at io.realm.Realm.(Realm.java)
       at io.realm.Realm.createAndValidate(Realm.java:280)
       at io.realm.Realm.create(Realm.java:244)
       at io.realm.Realm.getDefaultInstance(Realm.java:200)
```

**Comment by zaki50** [comment]
Seem to be the same with #1904 
If you are using ProGuard, please update ProGuard rules(`proguard-rules.pro`).

The ProGuard configuration for Realm java 0.84.1 is described here https://realm.io/docs/java/0.84.1/#proguard

**Comment by rshah** [comment]
Thank you for the answer.
Upgrading my proguard rules now.

**Comment by zaki50** [comment]
@rshah I'll close this issue. Feel free to reopen this if you have further questions.
