### ISSUE TITLE
java.lang.IllegalArgumentException: RealmObject is not valid, so it cannot be copied.

### ISSUE THREAD

**Issue by Shajeel-Afzal** [realm/realm-java#1973]
I am getting this exception while I am trying to save the Object via the code:

```
Realm realm2 = Realm.getDefaultInstance();
realm2.beginTransaction();
realm.copyFromRealm(mVideosList.get(k));
realm2.commitTransaction();
```
My Models looks like this:

```
public class Datum extends RealmObject {

    @PrimaryKey
    @Expose
    private String id;
    @Index
    @SerializedName("created_time")
    @Expose
    private String createdTime;
    @Expose
    private String description;
    @SerializedName("embed_html")
    @Expose
    private String embedHtml;
    @Expose
    private RealmList<Format> format = new RealmList<>();
    @Expose
    private String picture;
    @Expose
    private String source;
    @SerializedName("updated_time")
    @Expose
    private String updatedTime;
    @Expose
    private Double length;
    @SerializedName("permalink_url")
    @Expose
    private String permalinkUrl;

    public Datum() {
    }

    public String getPermalinkUrl() {
        return permalinkUrl;
    }

    public void setPermalinkUrl(String permalinkUrl) {
        this.permalinkUrl = permalinkUrl;
    }

    public Double getLength() {
        return length;
    }

    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * @return The id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id The id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return The createdTime
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * @param createdTime The created_time
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * @return The description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description The description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return The embedHtml
     */
    public String getEmbedHtml() {
        return embedHtml;
    }

    /**
     * @param embedHtml The embed_html
     */
    public void setEmbedHtml(String embedHtml) {
        this.embedHtml = embedHtml;
    }

    /**
     * @return The format
     */
    public RealmList<Format> getFormat() {
        return format;
    }

    /**
     * @param format The format
     */
    public void setFormat(RealmList<Format> format) {
        this.format = format;
    }

    /**
     * @return The picture
     */
    public String getPicture() {
        return picture;
    }

    /**
     * @param picture The picture
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * @return The source
     */
    public String getSource() {
        return source;
    }

    /**
     * @param source The source
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * @return The updatedTime
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * @param updatedTime The updated_time
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime;
    }
}
```
```
public class Format extends RealmObject {

    @PrimaryKey
    private String primaryKey;
    @Expose
    private String filter;
    @Expose
    private Long height;
    @Expose
    private String picture;
    @Expose
    private Long width;

    public Format() {
    }

    public String getPrimaryKey() {
        return primaryKey;
    }

    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

    /**
     * @return The filter
     */
    public String getFilter() {
        return filter;
    }

    /**
     * @param filter The filter
     */
    public void setFilter(String filter) {
        this.filter = filter;
    }

    /**
     * @return The height
     */
    public Long getHeight() {
        return height;
    }

    /**
     * @param height The height
     */
    public void setHeight(Long height) {
        this.height = height;
    }

    /**
     * @return The picture
     */
    public String getPicture() {
        return picture;
    }

    /**
     * @param picture The picture
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * @return The width
     */
    public Long getWidth() {
        return width;
    }

    /**
     * @param width The width
     */
    public void setWidth(Long width) {
        this.width = width;
    }
}
```
Please tell which step i am doing incorrectly.

**Comment by Shajeel-Afzal** [comment]
I tried to manually set the values using setters and getters and while setting the format object i got the following exception:

`java.lang.IllegalArgumentException: Each element of 'value' must be a valid managed object.`

**Comment by zaki50** [comment]
Hi @Shajeel-Afzal 

```
Realm realm2 = Realm.getDefaultInstance();
realm2.beginTransaction();
realm.copyFromRealm(mVideosList.get(k));
realm2.commitTransaction();
```

You are using `copyFromRealm()` which is the method to create unmanaged copy from managed object.
I think you'd like to persist the data in `mVideosList.get(k)`.
If so, you can use `copyToRealm()` method instead.

**Comment by Shajeel-Afzal** [comment]
OOPs Sorry, Thanks for correcting, Actually i was using `copyToRealm()` but since the `Datum` object had `RealList` object as well it was needed to be added separately.

This is how the transaction looks like now:

```
Realm realm2 = Realm.getDefaultInstance();
                                        realm2.beginTransaction();

                                        Datum realmDatum = mRealm.createObject(Datum.class);
                                        realmDatum.setId(mDatum[0].getId());
                                        realmDatum.setCreatedTime(mDatum[0].getCreatedTime());
                                        realmDatum.setDescription(mDatum[0].getDescription());
                                        realmDatum.setEmbedHtml(mDatum[0].getEmbedHtml());
                                        realmDatum.setLength(mDatum[0].getLength());
                                        realmDatum.setPermalinkUrl(mDatum[0].getPermalinkUrl());
                                        realmDatum.setPicture(mDatum[0].getPicture());
                                        realmDatum.setSource(mDatum[0].getSource());
                                        realmDatum.setUpdatedTime(mDatum[0].getUpdatedTime());

                                        for (int q = 0; q < videosList.get(k).getFormat().size(); q++) {
                                            Format formatAddResult = mRealm.copyToRealm(videosList.get(k).getFormat().get(q));
                                            realmDatum.getFormat().add(formatAddResult);
                                        }

                                        realm2.commitTransaction();
``` 

Please correct if this can be improved.

**Comment by cmelchior** [comment]
It looks like you already have a standalone `Datum` object. In that case you can also do something like this:

```
Datum datum = mDatum[0];
datum.setFormat(new RealmList());
for (int q = 0; q < videosList.get(k).getFormat().size(); q++) {
  Format formatAddResult = videosList.get(k).getFormat().get(q);
  datum.getFormat().add(formatAddResult);
}
realm.beginTransaction();
realm.copyToRealm(datum);
realm.commitTransaction();
```

**Comment by cmelchior** [comment]
I assume the above answered your question. If that was not the case, please reopen this.

**Comment by Shajeel-Afzal** [comment]
Yes it helped. Thanks. Can you please take a look at my another question on Stackoverflow? http://stackoverflow.com/questions/34886660/illegalargumentexception-field-name-doesnt-exist-on-object-while-doing-migrati/34890047?noredirect=1#comment57569239_34890047

**Comment by Suresh-Reddevil** [comment]
I have a similar issue,

```
public class CreatePurchaseOrderRow extends RealmObject  {
    @PrimaryKey
    public int test_Id;
    private int serialNumber;
    @Ignore
    private PurchaseItemModel purchaseItemModel;
    private String specification;
    private float quantity;
//    @Ignore
    private AddUnitModel units;
    private float rate;
    private String remarks;
    private boolean fulfilled;
    @Ignore
    private CreatePurchaseOrder createPurchaseOrder;

    public int getTest_Id() {
        return test_Id;
    }

    public void setTest_Id(int test_Id) {
        this.test_Id = test_Id;
    }

    public int getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(int serialNumber) {
        this.serialNumber = serialNumber;
    }

    public PurchaseItemModel getPurchaseItemModel() {
        return purchaseItemModel;
    }

    public void setPurchaseItemModel(PurchaseItemModel purchaseItemModel) {
        this.purchaseItemModel = purchaseItemModel;
    }

    public String getSpecification() {
        return specification;
    }

    public void setSpecification(String specification) {
        this.specification = specification;
    }

    public float getQuantity() {
        return quantity;
    }

    public void setQuantity(float quantity) {
        this.quantity = quantity;
    }

    public AddUnitModel getUnits() {
        return units;
    }

    public void setUnits(AddUnitModel units) {
        this.units = units;
    }

    public float getRate() {
        return rate;
    }

    public void setRate(float rate) {
        this.rate = rate;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public boolean isFulfilled() {
        return fulfilled;
    }

    public void setFulfilled(boolean fulfilled) {
        this.fulfilled = fulfilled;
    }

    public CreatePurchaseOrder getCreatePurchaseOrder() {
        return createPurchaseOrder;
    }

    public void setCreatePurchaseOrder(CreatePurchaseOrder createPurchaseOrder) {
        this.createPurchaseOrder = createPurchaseOrder;
    }
}



```
```
public class AddUnitModel extends RealmObject {
    @PrimaryKey
    public int id;
    public String name;
    public String namene;
    public String nameEn;
    public String shortName;

    public AddUnitModel() {
    }
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNamene() {
        return namene;
    }

    public void setNamene(String namene) {
        this.namene = namene;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
}

```

``` ```
@OnClick(R.id.newPurchaseOrderTolbatSubmitButton)
    public void onSubmit() {
        realm.beginTransaction();
        createPurchaseOrderDB = realm.createObject(CreatePurchaseOrderRow.class);

        for (int i = 0; i < createPurchaseOrderRowArrayList.size(); i++) {
            createPurchaseOrderRowArrayList.get(i).setTest_Id(RealmAutoIncrement.getInstance(CreatePurchaseOrderRow.class).getNextIdFromModel());
            CreatePurchaseOrderRow data = createPurchaseOrderRowArrayList.get(i);
            createPurchaseOrderDB.setPurchaseItemModel(data.getPurchaseItemModel());
            createPurchaseOrderDB.setCreatePurchaseOrder(data.getCreatePurchaseOrder());
            createPurchaseOrderDB.setUnits(data.getUnits());
            createPurchaseOrderDB.setTest_Id(RealmAutoIncrement.getInstance(CreatePurchaseOrderRow.class).getNextIdFromModel());
            createPurchaseOrderDB.setSerialNumber(2);
            createPurchaseOrderDB.setFulfilled(true);
            createPurchaseOrderDB.setQuantity(24);
            createPurchaseOrderDB.setRate(5);
            realm.copyToRealmOrUpdate(createPurchaseOrderDB);
            Log.v("TEST","Saved");
        }

        realm.commitTransaction();
    }

```

And the logcat is,

rocess: com.example.suresh.awecounting, PID: 18373
                                                                                java.lang.IllegalArgumentException: 'value' is not a valid managed object.
                                                                                    at io.realm.CreatePurchaseOrderRowRealmProxy.realmSet$units(CreatePurchaseOrderRowRealmProxy.java:155)
                                                                                    at com.example.suresh.awecounting.model.CreatePurchaseOrderRow.setUnits(CreatePurchaseOrderRow.java:75)
                                                                                    at com.example.suresh.awecounting.view.purchase.NewPurchaseOrderActivity.onSubmit(NewPurchaseOrderActivity.java:317)
                                                                                    at com.example.suresh.awecounting.view.purchase.NewPurchaseOrderActivity$$ViewBinder$1.doClick(NewPurchaseOrderActivity$$ViewBinder.java:30)
                                                                                    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                    at android.view.View.performClick(View.java:4783)


```

can you please help with this, 
thanks in advance

**Comment by beeender** [comment]
@Suresh-Reddevil How did you get `createPurchaseOrderRowArrayList`? It is not managed by Realm yet, so you can not set it as a `RealmObject` field on a managed `RealmObject`.

**Comment by Suresh-Reddevil** [comment]
@beeender  `createPurchaseOrderRowArrayList` is just a arrayList holding the values provided by user. It is not managed by realm. What can i do for that? Do i have to save the arrayList too. 

```
 createPurchaseOrderRow= new CreatePurchaseOrderRow();
            createPurchaseOrderRow.setPurchaseItemModel(rPurchaseItemModel);
            createPurchaseOrderRow.setSpecification(addPurchaseSpecification.getText().toString());
            createPurchaseOrderRow.setRemarks(addPurchaseRemarks.getText().toString());
            if (addPurchaseFulfilledCheckbox.isChecked())
                createPurchaseOrderRow.setFulfilled(true);
            else
                createPurchaseOrderRow.setFulfilled(false);
            if (addPurchaseItemRate.getText().toString().isEmpty())
                createPurchaseOrderRow.setRate(0);
            else
                createPurchaseOrderRow.setRate(Float.parseFloat(addPurchaseItemRate.getText().toString()));
            createPurchaseOrderRow.setUnits(unitModel);
            createPurchaseOrderRow.setQuantity(Float.parseFloat(addPurchaseItemQuantity.getText().toString()));
            createPurchaseOrderRow.setCreatePurchaseOrder(createPurchaseOrder);
createPurchaseOrderRowList.add(createPurchaseOrderRow);
```

**Comment by beeender** [comment]
It depends what do you want.
You can save the relevant object to realm first like:
```java
Units units = realm.copyToRealmOrUpdate(data.getUnits());
createPurchaseOrderDB.setUnits(units);
```
NOTE: If the Units doesn't have a `@PrimaryKey`, with doing this, you might end with some duplicated objects in Realm.

**Comment by Suresh-Reddevil** [comment]
Thanks, it worked.
