### ISSUE TITLE
ConcurrentModificationException while saving

### ISSUE THREAD

**Issue by VasyaFromRussia** [realm/realm-java#2013]
I try to save data in Realm:
```java
public Observable<List<ChatContainer>> loadMoreRecent(Integer fromMessageId, String query,
                                                          Integer limit, PublicType publicType) {
        return cloud
                .getRecent(fromMessageId, limit, query, publicType)
                .observeOn(realmScheduler)
                .doOnNext(timelineItemsDao::bulkSaveTimelineObjects)
                .doOnNext(this::updatePagingData)
                .map(baseTimelineObjectMapper);
    }
```

`TimelineItemsDao::bulkSaveTimelineObjects`:
```java
 public void bulkSaveTimelineObjects(final List<BaseTimelineObject> list) {
        Realm realm = getRealm();
        realm.executeTransaction(trRealm -> {
            for (BaseTimelineObject item : list) {
                if (item instanceof ServerPost) {
                    trRealm.copyToRealmOrUpdate((ServerPost) item);
                } else if (item instanceof ServerDialog) {
                    trRealm.copyToRealmOrUpdate((ServerDialog) item);
                } else if (item instanceof ServerEvent) {
                    trRealm.copyToRealmOrUpdate((ServerEvent) item);
                } else if (item instanceof ServerLobby) {
                    trRealm.copyToRealmOrUpdate((ServerLobby) item);
                }
            }
        });
        BaseDao.closeRealm(realm);
    }
```

And it causes ConcurrentModificationException:
```
java.util.ConcurrentModificationException
at java.util.IdentityHashMap$IdentityHashMapIterator.checkConcurrentMod(IdentityHashMap.java:164)
at java.util.IdentityHashMap$IdentityHashMapIterator.next(IdentityHashMap.java:169)
at io.realm.HandlerController.notifyRealmResultsCallbacks(HandlerController.java:240)
at io.realm.HandlerController.notifySyncRealmResultsCallbacks(HandlerController.java:235)
at io.realm.HandlerController.notifyTypeBasedListeners(HandlerController.java:206)
at io.realm.BaseRealm.commitTransaction(BaseRealm.java:302)
at io.realm.Realm.commitTransaction(Realm.java:108)
at io.realm.Realm.executeTransaction(Realm.java:1056)
at com.playdayteam.data.model.dao.TimelineItemsDao.bulkSaveTimelineObjects(TimelineItemsDao.java:99)
at com.playdayteam.data.repository.RecentRepository$$Lambda$5.call(Unknown Source)
at rx.Observable$11.onNext(Observable.java:4417)
at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

Realm version 0.87.1. All interactions with Realm are performed in single thread.
Is it bug or my fault?

**Comment by beeender** [comment]
Realm version is `0.72.1`? The version number doesn't seem to be correct, could you please check it again?

**Comment by VasyaFromRussia** [comment]
Sorry, typo :) version is 0.87.1

**Comment by beeender** [comment]
#1970 could be the same problem. We are checking.

**Comment by beeender** [comment]
Quick note here, `deleteWeakReferences` should be moved to the `commitTransaction` before calling sharedGourp's commit transaction to make sure it will only be modified inside the transaction lock.

**Comment by beeender** [comment]
#2026 will fix this. #1970 is the dup issue. Close this one for easy tracking.
