### ISSUE TITLE
How to rollback the Migration operation?

### ISSUE THREAD

**Issue by HsiangLeekwok** [realm/realm-java#2018]
Hi, Guys:

I have a problem of realm migration operation:

In some case I got some mistake during migration operation(data type error or other error caused the operation failed), but the schemaVersion has added to new value(ex. 10).

When I fix errors and debug it again, I must change the schemaVersion to a new number bigger than the failed operation(ex. 11), and the old version code(10) was wasted.

Is there any function like blow:
```Java
try {
  migration version xx to xx+1
  .....
}
catch (Exception e) {
  rollback to version xx
}
```

@cmelchior

**Comment by cmelchior** [comment]
Hi @HsiangLeekwok 
Everything inside a migration is executed as one transaction, that means that if an exception is thrown, the entire transaction will be canceled and nothing will be saved, so you shouldn't "waste" a version code in case of errors. You can see the relevant code here: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L609-Lundefined

**Comment by HsiangLeekwok** [comment]
Sorry to trouble you again @cmelchior 
This is a sample:
```java
// object to be add...
public class Test extends RealmObject{
    @PrimaryKey
    private long id;
    private String name;
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
// migration...
public class Migration implements RealmMigration {
    private static final String TAG = "Migration";
    @Override
    public void migrate(DynamicRealm dynamicRealm, long oldVersion, long newVersion) {
        // log the version number before migrate
        Log.e(TAG, String.format("local realm version: %d", dynamicRealm.getVersion()));
        try {
            RealmSchema schema = dynamicRealm.getSchema();
            if (oldVersion == 0) {
                upgrade0to1(schema);
                oldVersion++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // log the version number after migrate
        Log.e(TAG, String.format("local realm version: %d", dynamicRealm.getVersion()));
    }
    private void upgrade0to1(RealmSchema realm) {
        realm.create("Test")
                .addField("id", Long.class) // exception here, id is a primary key(will fire an exception: Field 'id' does support null values in the existing Realm file. Use corresponding boxed type for field 'id' or migrate using io.realm.internal.Table.convertColumnToNotNullable())
                .addField("name", String.class);
    }
}
```
so, I changed the upgrade0to1 progress to:
```java
    private void upgrade0to1(RealmSchema realm) {
        if (!realm.contains("Test")) {
            realm.create("Test")
                    .addField("id", Long.TYPE, FieldAttribute.PRIMARY_KEY)
                    .addField("name", String.class);
        } else {
            realm.remove("Test");// remove the table first and re-create it
            realm.create("Test")
                    .addField("id", Long.TYPE, FieldAttribute.PRIMARY_KEY)
                    .addField("name", String.class);
        }
    }
```
and debug again, It will print a exception:
```java
Caused by: io.realm.exceptions.RealmMigrationNeededException: Field count does not match - expected 2 but was 0
   at io.realm.TestRealmProxy.validateTable(TestRealmProxy.java:106)
   at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:98)
   at io.realm.Realm.initializeRealm(Realm.java:287)
   at io.realm.Realm.createAndValidate(Realm.java:255)
   at io.realm.Realm.createInstance(Realm.java:234)
   at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
   at io.realm.Realm.getInstance(Realm.java:191)
```
and the local realm version is:
```java
E/Migration: local realm version: 1
```
seems version number has been changed to 1.
So, the way I have to do is add a new version number 2, and a new progress of "upgrade1to2":
```java
private void upgrade1to2(RealmSchema realm) {
    if (realm.contains("Test"))
        realm.remove("Test");
    realm.create("Test").addField("id", Long.TYPE, FieldAttribute.PRIMARY_KEY)
        .addField("name", String.class);
}
```
Finally, version will be change to 2.
But, for the hole project, the version 1 was wasted, because from 0 to 1 has nothing to do
Do you have any tips? Thanks very much!

**Comment by cmelchior** [comment]
The error is happening because you are catching the exception yourself. That way "our" code doesn't know that anything was wrong and we commit whatever was in the transaction when your method ended (which most likely makes it very hard to recover). 

So the reason the version is "1" is because your first migration succeed from the point of view of Realm, and it thus increased the version number to 1.

If you started over with an original Realm file and the correct migration code it should work. Also note you can use:

```
schema.setNullable("fieldName", false);
schema.addPrimaryKey("fieldName");
```

instead of removing the old class and creating it again.

**Comment by HsiangLeekwok** [comment]
Great!
I changed my code to:
```java
    /**
     * migration
     * add another function to handle the lost field attributes,
     * and remove try...catch block
     */
     ... if(oldVersion==0)... //upgrade 0 to 1
     if (oldVersion == 1) {// because the local realm version is 1 now
         upgrade1to1_handlingLostAttributes(schema);
     }

    // function upgrade1to1
    private void upgrade1to1_handlingLostAttributes(RealmSchema realm) {
        RealmObjectSchema schema = realm.get("Test");
        if (!schema.hasPrimaryKey()) {
            if (schema.hasField("id")) {
                schema.addPrimaryKey("id");
                schema.setNullable("id", false);
                //schema.addIndex("id"); comment this line to try again
            } else {
                schema.addField("id", Long.class, FieldAttribute.PRIMARY_KEY);
            }
        }
        if (!schema.hasIndex("id")) {
            schema.addIndex("id"); // add the index of primary key
        }
        if (!schema.hasField("name")) {
            schema.addField("name", String.class);
        }
    }
```
No more exception, and worked fine.

Thank you very much.
Oh, Happy New Year.

**Comment by cmelchior** [comment]
No problem :) Happy coding.
