### ISSUE TITLE
No default RealmConfiguration was found. Call setDefaultConfiguration() first

### ISSUE THREAD

**Issue by McManusds** [realm/realm-java#2131]
Hello i have weird  issue with Realm in some low performance Android devices. 

I set 
```
final RealmConfiguration config = new RealmConfiguration.Builder(this).build();        

Realm.setDefaultConfiguration(config);
```
In my first Activity. Everything looks ok in all devices but in some cases in some devices i got realm crashes. 

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{"packName"/"packName".splash.ChooseDistrictActivity}: java.lang.NullPointerException: No default RealmConfiguration was found. Call setDefaultConfiguration() first
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by java.lang.NullPointerException: No default RealmConfiguration was found. Call setDefaultConfiguration() first
       at io.realm.Realm.getDefaultInstance(Realm.java:199)
       at "packName".splash.ChooseDistrictActivity.onCreate(ChooseDistrictActivity.java:143)
       at android.app.Activity.performCreate(Activity.java:6221)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

Those users told me app continue working fine and realm bring to app data normally after those crashes. 
Can anyone helps me understand what's going on here ? 
Thank you.

**Comment by cmelchior** [comment]
Where are you setting the default configuration?

**Comment by McManusds** [comment]
I set it in my First Main, Launcher Activity Inside of

```
 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

```

**Comment by McManusds** [comment]
In some cases this happen just in second Activity on the flow

**Comment by cmelchior** [comment]
You shouldn't do that inside an Activity as Android might start the activity that was last open first. You should instead use the Application class for that. There is an example in our documentation here: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

**Comment by McManusds** [comment]
Thank you

**Comment by McManusds** [comment]
Yeah it's solved . Thank you . You can close it .

**Comment by cmelchior** [comment]
No problem. Good luck with the app.

**Comment by MichaelObi** [comment]
I get this randomly sometimes. I still cant figure out why a change in my layout files that have nothing to do with the activity i'm launching will trigger this error. Just got another one a few minutes ago.

**Comment by cmelchior** [comment]
In which class are you calling `setDefaultConfiguration()`?

**Comment by MichaelObi** [comment]
I call `setDefaultConfiguration()` in the `onCreate()` method in my Application class

**Comment by calmcc** [comment]
I have the same problem. I call `setDefaultConfiguration()`  in my Application class.
I also try change android:allowBackup="false"

**Comment by cmelchior** [comment]
@MichaelObi Are you using Instant Run?

**Comment by calmcc** [comment]
@cmelchior can't use Android Studio 2.0.0-preview?

**Comment by cmelchior** [comment]
You can, but it is preview for a reason. It still contain bugs, so if you see your app crashing after a change to a layout file, there is not much else to do than a clean build.
If you experience something that can reproduced like that I would encourage you to create a bug report at Google so they have a chance of fixing it: https://code.google.com/p/android/issues/entry?template=Android%20Studio%20Instant%20Run%20Bug

**Comment by calmcc** [comment]
ok,thank you!

**Comment by MichaelObi** [comment]
Yes, I  use instant run. I'll try to reproduce the error. Thanks @cmelchior

**Comment by danijax** [comment]
I started getting this error when I added a content provider class. I called ```setDefaultInstance``` in the application class

**Comment by jraczak** [comment]
@cmelchior I'm having this issue in Android Studio 1.5.1. I call `setDefaultConfiguration` in  class extending my Application and then call `getDefaultInstance` in `onCreate

**Comment by cmelchior** [comment]
The Activity context should always be created first, even if you restart your app from the middle of a flow somewhere, but please make a new issue. It is easier for us to track there than in closed one. Especially any information about which devices you see this on, and the relevant code snippets from the Activity/ApplicationContext would also be great.

**Comment by jraczak** [comment]
@cmelchior I'll have a new issue up with all the details in 2 minutes. Thanks for the quick response - this is a blocking issue right now :)

**Comment by Suresh-Reddevil** [comment]
May be you are missing to include your Application class in manifests. 

  <application
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:name=".Your_Application_class"
        android:label="@string/app_name"
      .
      .
      .

**Comment by danijax** [comment]
oh Thanks, I figured out the problem. The problem was caused by trying to access `Realm` in the constructor of a `ContentProvider` which normally runs before the application class

**Comment by androidHRTZ** [comment]
I got the same problem，but solved way is about RealmConfiguration, is due to state UrApplication in AndroidManifest.xml          add it as <application
        android:name=".MyApplication"
