### ISSUE TITLE
DynamicRealmObject / Reusing String incorrectly

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2141]
```   
@Test
    public void dynamicRealmObject() {
        testRealm.beginTransaction();
        RealmDemoData obj = testRealm.createObject(RealmDemoData.class);
        for (int i = 0; i < 10; i++) {
            RealmFloat object = testRealm.createObject(RealmFloat.class);
            object.setFloatValue((float) i);
            obj.getStackValues().add(object);
        }
        testRealm.commitTransaction();

        DynamicRealmObject o = new DynamicRealmObject(obj);
        RealmList<DynamicRealmObject> list = o.getList("stackValues");

        float[] values = new float[list.size()];
        for (int i = 0; i < list.size(); i++) {
            values[i] = o.getFloat("floatValue"); // Note that "o" is not a RealmFloat object so this should throw.
        }
    }
```
It throws with this:

```
java.lang.IllegalArgumentException: Illegal Argument: Field not found: floatValuealm_internal_LinkView_nativeSize__J
at io.realm.internal.CheckedRow.nativeGetColumnIndex(Native Method)
at io.realm.internal.UncheckedRow.getColumnIndex(UncheckedRow.java:122)
at io.realm.DynamicRealmObject.getFloat(DynamicRealmObject.java:184)
at io.realm.RealmListTests.dynamicRealmObject(RealmListTests.java:1041)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at io.realm.rule.TestRealmConfigurationFactory$1.evaluate(TestRealmConfigurationFactory.java:49)
at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
```

2nd crash, this time without exception:

```
   public void testGetList() {
        realm.beginTransaction();
        AllTypes obj = realm.createObject(AllTypes.class);
        Dog dog = realm.createObject(Dog.class);
        dog.setName("fido");
        obj.getColumnRealmList().add(dog);
        realm.commitTransaction();

        DynamicRealmObject dynamicAllTypes = new DynamicRealmObject(obj);
        RealmList<DynamicRealmObject> list = dynamicAllTypes.getList(AllTypes.FIELD_REALMLIST);
        DynamicRealmObject listObject = list.get(0);

        assertEquals(1, list.size());
        assertEquals(Dog.CLASS_NAME, listObject.getType());
        assertEquals("fido", listObject.getString(Dog.FIELD_NAME));
    }
```

**Comment by cmelchior** [comment]
Fixed by #2146
