### ISSUE TITLE
RealmUser is not part of the schema for this Realm

### ISSUE THREAD

**Issue by itrufeng** [realm/realm-java#2162]
I use `kotlin`
but always error.
My ProGuard here

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**
```

My Exception here.

```
01-26 23:14:49.942 13155-13155/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.thoughtworks.jizhang.realmdemo, PID: 13155
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thoughtworks.jizhang.realmdemo/com.thoughtworks.jizhang.realmdemo.MainActivity}: java.lang.IllegalArgumentException: RealmUser is not part of the schema for this Realm
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:159)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5313)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
                                                    Caused by: java.lang.IllegalArgumentException: RealmUser is not part of the schema for this Realm
                                                       at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:122)
                                                       at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:79)
                                                       at io.realm.Realm.getTable(Realm.java:1274)
                                                       at io.realm.Realm.createObject(Realm.java:660)
                                                       at com.thoughtworks.jizhang.realmdemo.MainActivity$setupSaveButton$1.invoke(MainActivity.kt:96)
                                                       at com.thoughtworks.jizhang.realmdemo.MainActivity.setupSaveButton(MainActivity.kt:136)
                                                       at com.thoughtworks.jizhang.realmdemo.MainActivity.setup(MainActivity.kt:40)
                                                       at com.thoughtworks.jizhang.realmdemo.MainActivity.onCreate(MainActivity.kt:34)
                                                       at android.app.Activity.performCreate(Activity.java:6036)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:159) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5313) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809) 
```

**Comment by cmelchior** [comment]
How does your `RealmUser` class look like?

**Comment by itrufeng** [comment]
@cmelchior 
like this.
```kotlin
public open class RealmUser: RealmObject() {
    public open var username: String? = null
    public open var age: Int? = null

    init {
        this.username = username
        this.age = age
    }
}
```

**Comment by cmelchior** [comment]
That looks fine. It sounds like the annotation processor isn't running for some reason.

1) Check the Gradle log. It should output something like "Note: Processing RealmUser". If that is not the case, our annotation processor isn't running.

2) How did you add Realm to the project? You can see a working sample here: https://github.com/realm/realm-java/blob/master/examples/kotlinExample/build.gradle

**Comment by itrufeng** [comment]
@cmelchior 
Thanks for you answer,
My code here, just a simple demo.
https://github.com/itrufeng/RealmDemo.

**Comment by cmelchior** [comment]
Hi @itrufeng 
Your `app/build.gradle` file looks a bit wrong as you include both the Realm Jar and AAR. Try to change it to:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version" // Kotlin
    compile 'io.reactivex:rxkotlin:0.30.1' // Rx for Kotlin
    compile 'com.jakewharton.rxbinding:rxbinding-kotlin:0.3.0' // Rx for UI Widget
    compile 'com.joanzapata.android:base-adapter-helper:1.1.11' // Adapter for View
//    compile 'io.reactivex:rxjava:1.0.10' // Realm Dependent
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile "io.realm:realm-android-library:0.87.4@aar"
    compile "io.realm:realm-annotations:0.87.4"
    kapt "io.realm:realm-annotations:0.87.4"
    kapt "io.realm:realm-annotations-processor:0.87.4"
}
```

**Comment by itrufeng** [comment]
@cmelchior 
It works.
Thank you very much.
:+1:

**Comment by Vaishnavi-optisol** [comment]
I tried all possible options. I'm using Kotlin with Dagger and Realm i'm getting same error still.

**Comment by Zhuinden** [comment]
Did you apply Kotlin-kapt?

**Comment by saecmca** [comment]
Hi, anyone help me to store the json file to model class using Realm, this is the module project. I have created simple Application its working fine but if using module project it wont work
//Model class
open class Sample(
        var test1: String,
        var test2: String,
        var test3: String 
): RealmObject()

//sample json
val json = """
            {             
            "test":"test",
            "test1":1 ,
            "test2":1 
            }
            """.trimIndent()


//storing class
realm= Realm.getDefaultInstance() 
            realm.executeTransactionAsync ({
                it.createObjectFromJson(Sample::class.java,json) 
            },{
                Log.d("TAG","On Success: Data Written Successfully!")
                //readData()
            },{
                Log.d("TAG","On Error: Error in saving Data!")
            })



//dependencies
apply plugin: 'com.android.library'
apply plugin: 'realm-android'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0' 
    implementation 'com.google.code.gson:gson:2.8.6'
}
buildscript {     
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'io.realm:realm-gradle-plugin:10.0.1'
    }
}


ERROR:
io.realm.exceptions.RealmException: Sample is not part of the schema for this Realm

Please can any one share the module project using realm

**Comment by Zhuinden** [comment]
You need to use `@RealmModule` for library stuff
