### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#2211]
I just got this error on a device, and I'm not sure what to make of it. Realm 0.82.2.

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 115
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.(SharedGroup.java)
       at io.realm.Realm.(Realm.java)
       at io.realm.Realm.createAndValidate(Realm.java:597)
       at io.realm.Realm.create(Realm.java:567)
       at io.realm.Realm.getInstance(Realm.java:540)
       at ... //start up of application
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4451)
       at android.app.ActivityThread.access$1300(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5121)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
```

**Comment by Zhuinden** [comment]
It's actually on a RIM Passport.

So it's blackberry.

So it's the same bug as this one.

https://github.com/realm/realm-java/issues/1380

**Comment by beeender** [comment]
@Zhuinden  Try the latest version :)

**Comment by Zhuinden** [comment]
@beeender 
Well I also got the `Unsatisfied Link Error`

Fatal Exception: java.lang.ExceptionInInitializerError

```
io.realm.Realm. (Realm.java:207)
io.realm.Realm.createAndValidate (Realm.java:597)
io.realm.Realm.create (Realm.java:567)
io.realm.Realm.getInstance (Realm.java:540)
...(CustomApplication.java:358)
....onCreate (CustomApplication.java:262)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:969)
dalvik.system.NativeStart.main (NativeStart.java)
Caused by java.lang.UnsatisfiedLinkError
java.lang.Runtime.loadLibrary (Runtime.java:365)
java.lang.System.loadLibrary (System.java:535)
io.realm.internal.RealmCore.loadLibrary (RealmCore.java:117)
io.realm.internal.SharedGroup. (SharedGroup.java:35)
io.realm.Realm. (Realm.java:207)
io.realm.Realm.createAndValidate (Realm.java:597)
io.realm.Realm.create (Realm.java:567)
io.realm.Realm.getInstance (Realm.java:540)
...
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:969)
dalvik.system.NativeStart.main (NativeStart.java)
```

So I'll probably have to go with the 0.88.0-SNAPSHOT for that.

**Comment by beeender** [comment]
@Zhuinden Do you know which device and what is the android version for those "Unsatisfied Link Error" ?

**Comment by Zhuinden** [comment]
@beeender ZTE Blade III, Android version 4.0.4
