### ISSUE TITLE
DexException: RealmCache#Callback

### ISSUE THREAD

**Issue by PaulWoitaschek** [realm/realm-java#2244]
# Problem
I can't get realm to run. I tried it with gradle plugin `2.0.0-beta2`, `1.5.0`, `Android Studio 1.5` and `2 beta 2`.
# Exception
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lio/realm/RealmCache$Callback;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
```
# Top build.gradle
```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.realmVersion = "0.87.4"

    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'me.tatarka:gradle-retrolambda:3.2.4'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath "io.realm:realm-gradle-plugin:$realmVersion"
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
# Module build.gradle:
```groovy
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "de.paul_woitaschek.notes"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled = true
    }
}

dependencies {
    testCompile "junit:junit:4.12"

    def supportVer = "23.1.1"
    compile "com.android.support:design:$supportVer"
    compile "com.android.support:appcompat-v7:$supportVer"
    compile "com.android.support:cardview-v7:$supportVer"

    // rx extensions
    compile "io.reactivex:rxandroid:1.1.0"
    compile "io.reactivex:rxjava:1.1.0"

    // injection
    def daggerVersion = "2.0.2"
    compile "com.google.dagger:dagger:$daggerVersion"
    apt "com.google.dagger:dagger-compiler:$daggerVersion"
    provided 'javax.annotation:jsr250-api:1.0'

    // logging
    compile 'com.jakewharton.timber:timber:4.1.0'

    // dialogs
    compile('com.github.afollestad.material-dialogs:core:0.8.5.4@aar') {
        transitive = true
    }

    // storage
    compile "io.realm:realm-android:$realmVersion"
}
```

**Comment by kneth** [comment]
You have apply the Realm Gradle plugin and add Realm as dependency.

**Comment by PaulWoitaschek** [comment]
And how do I do that?

**Comment by kneth** [comment]
Try to remove the `compile "io.realm:realm-android:$realmVersion"` line.

**Comment by cmelchior** [comment]
@PaulWoitaschek All our examples also use the Gradle plugin so you can see how here: https://github.com/realm/realm-java/tree/master/examples

It is also described in this blog post: https://realm.io/news/android-installation-change/

**Comment by PaulWoitaschek** [comment]
Thanks. I kind of mixed the two installation ways.
