### ISSUE TITLE
Generics in RealmObjects doesn't fail correctly

### ISSUE THREAD

**Issue by maannajjar** [realm/realm-java#2265]
Hello,

This scenario is happening only when using Kotlin. Not sure if I'm missing something. Suppose I have those two classes:

``` kotlin
open class PetContainer<T : RealmObject> : RealmObject() {
    open var containerName : String? = null;
    open var content : RealmList<T>? = null;
}

open class House<T: RealmObject> : RealmObject() {
    open var petContainer : PetContainer<T>? = null;
}
```

The annotation processor will throw an exception during the processing of _House_ class
java.lang.IllegalArgumentException: com.app.model.PetContainer<T>

> Caused by: java.lang.IllegalArgumentException: com.app.model.PetContainer<T>
>     at com.squareup.javawriter.JavaWriter.emitImports(JavaWriter.java:111)
>     at io.realm.processor.RealmProxyClassGenerator.generate(RealmProxyClassGenerator.java:94)
>     at io.realm.processor.RealmProcessor.process(RealmProcessor.java:145)
>     at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:136)

Generics seem only to be working when using RealmList. Although the above code will work fine if written in normal java.

I'm using the following in my build.gradle:

``` groovy
    compile "io.realm:realm-android-library:0.87.4"
    compile "io.realm:realm-annotations:0.87.4"
    kapt "io.realm:realm-annotations:0.87.4"
    kapt "io.realm:realm-annotations-processor:0.87.4"
```

Kotlin version is 1.0.0-rc-1036

Thanks,
Maan

**Comment by cmelchior** [comment]
I am no Kotlin expert, but from what I remember Kotlin generics work a bit different than Java generics: https://kotlinlang.org/docs/reference/generics.html, but we will look into it.

**Comment by cmelchior** [comment]
@maannajjar 

Also note that that level of generics are not really supported by Realm, since we need to know the exact types in order to create the underlying schema.

If our annotation processor doesn't throw an error, it sounds like a bug from our side.

**Comment by maannajjar** [comment]
@cmelchior aah I didn't know that, it makes sense. Thanks for the info, I'll fix my code in that case :)

**Comment by cmelchior** [comment]
Just tested the Java version of this:

```
public class GenericList<T extends RealmObject> extends RealmObject {
    private RealmList<T> fieldList;
}
```

The annotation processor completes, but generates an invalid Proxy class.

```
package io.realm;


import T;
import android.util.JsonReader;
import android.util.JsonToken;
import io.realm.RealmFieldType;
import io.realm.entities.GenericList;
import io.realm.exceptions.RealmMigrationNeededException;
import io.realm.internal.ColumnInfo;
import io.realm.internal.ImplicitTransaction;
import io.realm.internal.LinkView;
import io.realm.internal.RealmObjectProxy;
import io.realm.internal.Table;
import io.realm.internal.TableOrView;
import io.realm.internal.android.JsonUtils;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class GenericListRealmProxy extends GenericList
    implements RealmObjectProxy {

    static final class GenericListColumnInfo extends ColumnInfo {

        public final long fieldListIndex;

        GenericListColumnInfo(String path, Table table) {
            final Map<String, Long> indicesMap = new HashMap<String, Long>(1);
            this.fieldListIndex = getValidColumnIndex(path, table, "GenericList", "fieldList");
            indicesMap.put("fieldList", this.fieldListIndex);

            setIndicesMap(indicesMap);
        }
    }

    private final GenericListColumnInfo columnInfo;
    private RealmList<T> fieldListRealmList;
    private static final List<String> FIELD_NAMES;
    static {
        List<String> fieldNames = new ArrayList<String>();
        fieldNames.add("fieldList");
        FIELD_NAMES = Collections.unmodifiableList(fieldNames);
    }

    GenericListRealmProxy(ColumnInfo columnInfo) {
        this.columnInfo = (GenericListColumnInfo) columnInfo;
    }

    @Override
    public RealmList<T> getFieldList() {
        realm.checkIfValid();
        // use the cached value if available
        if (fieldListRealmList != null) {
            return fieldListRealmList;
        } else {
            LinkView linkView = row.getLinkList(columnInfo.fieldListIndex);
            fieldListRealmList = new RealmList<T>(T.class, linkView, realm);
            return fieldListRealmList;
        }
    }

    @Override
    public void setFieldList(RealmList<T> value) {
        realm.checkIfValid();
        LinkView links = row.getLinkList(columnInfo.fieldListIndex);
        links.clear();
        if (value == null) {
            return;
        }
        for (RealmObject linkedObject : (RealmList<? extends RealmObject>) value) {
            if (!linkedObject.isValid()) {
                throw new IllegalArgumentException("Each element of 'value' must be a valid managed object.");
            }
            if (linkedObject.realm != this.realm) {
                throw new IllegalArgumentException("Each element of 'value' must belong to the same Realm.");
            }
            links.add(linkedObject.row.getIndex());
        }
    }

    public static Table initTable(ImplicitTransaction transaction) {
        if (!transaction.hasTable("class_GenericList")) {
            Table table = transaction.getTable("class_GenericList");
            if (!transaction.hasTable("class_T")) {
                TRealmProxy.initTable(transaction);
            }
            table.addColumnLink(RealmFieldType.LIST, "fieldList", transaction.getTable("class_T"));
            table.setPrimaryKey("");
            return table;
        }
        return transaction.getTable("class_GenericList");
    }

    public static GenericListColumnInfo validateTable(ImplicitTransaction transaction) {
        if (transaction.hasTable("class_GenericList")) {
            Table table = transaction.getTable("class_GenericList");
            if (table.getColumnCount() != 1) {
                throw new RealmMigrationNeededException(transaction.getPath(), "Field count does not match - expected 1 but was " + table.getColumnCount());
            }
            Map<String, RealmFieldType> columnTypes = new HashMap<String, RealmFieldType>();
            for (long i = 0; i < 1; i++) {
                columnTypes.put(table.getColumnName(i), table.getColumnType(i));
            }

            final GenericListColumnInfo columnInfo = new GenericListColumnInfo(transaction.getPath(), table);

            if (!columnTypes.containsKey("fieldList")) {
                throw new RealmMigrationNeededException(transaction.getPath(), "Missing field 'fieldList'");
            }
            if (columnTypes.get("fieldList") != RealmFieldType.LIST) {
                throw new RealmMigrationNeededException(transaction.getPath(), "Invalid type 'T' for field 'fieldList'");
            }
            if (!transaction.hasTable("class_T")) {
                throw new RealmMigrationNeededException(transaction.getPath(), "Missing class 'class_T' for field 'fieldList'");
            }
            Table table_0 = transaction.getTable("class_T");
            if (!table.getLinkTarget(columnInfo.fieldListIndex).hasSameSchema(table_0)) {
                throw new RealmMigrationNeededException(transaction.getPath(), "Invalid RealmList type for field 'fieldList': '" + table.getLinkTarget(columnInfo.fieldListIndex).getName() + "' expected - was '" + table_0.getName() + "'");
            }
            return columnInfo;
        } else {
            throw new RealmMigrationNeededException(transaction.getPath(), "The GenericList class is missing from the schema for this Realm.");
        }
    }

    public static String getTableName() {
        return "class_GenericList";
    }

    public static List<String> getFieldNames() {
        return FIELD_NAMES;
    }

    @SuppressWarnings("cast")
    public static GenericList createOrUpdateUsingJsonObject(Realm realm, JSONObject json, boolean update)
        throws JSONException {
        GenericList obj = realm.createObject(GenericList.class);
        if (json.has("fieldList")) {
            if (json.isNull("fieldList")) {
                obj.setFieldList(null);
            } else {
                obj.getFieldList().clear();
                JSONArray array = json.getJSONArray("fieldList");
                for (int i = 0; i < array.length(); i++) {
                    T item = TRealmProxy.createOrUpdateUsingJsonObject(realm, array.getJSONObject(i), update);
                    obj.getFieldList().add(item);
                }
            }
        }
        return obj;
    }

    @SuppressWarnings("cast")
    public static GenericList createUsingJsonStream(Realm realm, JsonReader reader)
        throws IOException {
        GenericList obj = realm.createObject(GenericList.class);
        reader.beginObject();
        while (reader.hasNext()) {
            String name = reader.nextName();
            if (name.equals("fieldList")) {
                if (reader.peek() == JsonToken.NULL) {
                    reader.skipValue();
                    obj.setFieldList(null);
                } else {
                    reader.beginArray();
                    while (reader.hasNext()) {
                        T item = TRealmProxy.createUsingJsonStream(realm, reader);
                        obj.getFieldList().add(item);
                    }
                    reader.endArray();
                }
            } else {
                reader.skipValue();
            }
        }
        reader.endObject();
        return obj;
    }

    public static GenericList copyOrUpdate(Realm realm, GenericList object, boolean update, Map<RealmObject,RealmObjectProxy> cache) {
        if (object.realm != null && object.realm.getPath().equals(realm.getPath())) {
            return object;
        }
        return copy(realm, object, update, cache);
    }

    public static GenericList copy(Realm realm, GenericList newObject, boolean update, Map<RealmObject,RealmObjectProxy> cache) {
        GenericList realmObject = realm.createObject(GenericList.class);
        cache.put(newObject, (RealmObjectProxy) realmObject);

        RealmList<T> fieldListList = newObject.getFieldList();
        if (fieldListList != null) {
            RealmList<T> fieldListRealmList = realmObject.getFieldList();
            for (int i = 0; i < fieldListList.size(); i++) {
                T fieldListItem = fieldListList.get(i);
                T cachefieldList = (T) cache.get(fieldListItem);
                if (cachefieldList != null) {
                    fieldListRealmList.add(cachefieldList);
                } else {
                    fieldListRealmList.add(TRealmProxy.copyOrUpdate(realm, fieldListList.get(i), update, cache));
                }
            }
        }

        return realmObject;
    }

    public static GenericList createDetachedCopy(GenericList realmObject, int currentDepth, int maxDepth, Map<RealmObject, CacheData<RealmObject>> cache) {
        if (currentDepth > maxDepth || realmObject == null) {
            return null;
        }
        CacheData<GenericList> cachedObject = (CacheData) cache.get(realmObject);
        GenericList standaloneObject;
        if (cachedObject != null) {
            // Reuse cached object or recreate it because it was encountered at a lower depth.
            if (currentDepth >= cachedObject.minDepth) {
                return cachedObject.object;
            } else {
                standaloneObject = cachedObject.object;
                cachedObject.minDepth = currentDepth;
            }
        } else {
            standaloneObject = new GenericList();
            cache.put(realmObject, new RealmObjectProxy.CacheData<RealmObject>(currentDepth, standaloneObject));
        }

        // Deep copy of fieldList
        if (currentDepth == maxDepth) {
            standaloneObject.setFieldList(null);
        } else {
            RealmList<T> managedfieldListList = realmObject.getFieldList();
            RealmList<T> standalonefieldListList = new RealmList<T>();
            standaloneObject.setFieldList(standalonefieldListList);
            int nextDepth = currentDepth + 1;
            int size = managedfieldListList.size();
            for (int i = 0; i < size; i++) {
                T item = TRealmProxy.createDetachedCopy(managedfieldListList.get(i), nextDepth, maxDepth, cache);
                standalonefieldListList.add(item);
            }
        }
        return standaloneObject;
    }

    @Override
    public String toString() {
        if (!isValid()) {
            return "Invalid object";
        }
        StringBuilder stringBuilder = new StringBuilder("GenericList = [");
        stringBuilder.append("{fieldList:");
        stringBuilder.append("RealmList<T>[").append(getFieldList().size()).append("]");
        stringBuilder.append("}");
        stringBuilder.append("]");
        return stringBuilder.toString();
    }

    @Override
    public int hashCode() {
        String realmName = realm.getPath();
        String tableName = row.getTable().getName();
        long rowIndex = row.getIndex();

        int result = 17;
        result = 31 * result + ((realmName != null) ? realmName.hashCode() : 0);
        result = 31 * result + ((tableName != null) ? tableName.hashCode() : 0);
        result = 31 * result + (int) (rowIndex ^ (rowIndex >>> 32));
        return result;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GenericListRealmProxy aGenericList = (GenericListRealmProxy)o;

        String path = realm.getPath();
        String otherPath = aGenericList.realm.getPath();
        if (path != null ? !path.equals(otherPath) : otherPath != null) return false;;

        String tableName = row.getTable().getName();
        String otherTableName = aGenericList.row.getTable().getName();
        if (tableName != null ? !tableName.equals(otherTableName) : otherTableName != null) return false;

        if (row.getIndex() != aGenericList.row.getIndex()) return false;

        return true;
    }

}
```

It should be fixed so we instead abort the annotation processor with a correct error message.
