### ISSUE TITLE
BadVersionException

### ISSUE THREAD

**Issue by sergeyfitis** [realm/realm-java#2322]
Hi. Sometimes I am receiving this error on fabric:
```java
Fatal Exception: java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in 
io_realm_internal_TableQuery.cpp line 1094
       at io.realm.RealmQuery$5.call(RealmQuery.java:1847)
       at io.realm.RealmQuery$5.call(RealmQuery.java:1817)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1094
       at io.realm.internal.TableQuery.nativeFindWithHandover(TableQuery.java)
       at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:438)
       at io.realm.RealmQuery$5.call(RealmQuery.java:1829)
       at io.realm.RealmQuery$5.call(RealmQuery.java:1817)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```
But I can't reproduce it myself. Do you have some ideas about it?

**Comment by nhachicha** [comment]
Hi @sergeyfitis 
looks similar to #2115 we have a PR fixing this, that should be released soon
Cheers

**Comment by sergeyfitis** [comment]
@nhachicha Thank you.
