### ISSUE TITLE
Error while in instantiating Realm Object

### ISSUE THREAD

**Issue by pankajnimgade** [realm/realm-java#2344]
In my build.gradle dependency, this is how I am adding the realm to my **Android **project
        `compile 'io.realm:realm-android:0.87.5'`
this is my log cat when I call,

       ` Realm myRealm = Realm.getInstance(getApplicationContext());`

Error:
```

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.ExceptionInInitializerError
                                                     at relam.list.activities.RealmExampleOneActivity.initializeUI(RealmExampleOneActivity.java:34)
                                                     at relam.list.activities.RealmExampleOneActivity.onCreate(RealmExampleOneActivity.java:28)
                                                     at android.app.Activity.performCreate(Activity.java:5104)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.NoClassDefFoundError: io.realm.internal.async.RealmThreadPoolExecutor
                                                     at io.realm.BaseRealm.<clinit>(BaseRealm.java:59)
                                                     at relam.list.activities.RealmExampleOneActivity.initializeUI(RealmExampleOneActivity.java:34) 
                                                     at relam.list.activities.RealmExampleOneActivity.onCreate(RealmExampleOneActivity.java:28) 
                                                     at android.app.Activity.performCreate(Activity.java:5104) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
```

**Comment by cmelchior** [comment]
That sounds really strange. Can you reproduce this error? Also are you using Instant Run? That is currently known to be buggy with Realm, so uninstalling the app and installing it again can help.

**Comment by pankajnimgade** [comment]
@cmelchior 

Hi, I am not sure what exactly the instance run is but I am trying to instantiate the instance of Realm Type but unfortunately I get this error, I tried getting the default instance as well but it throws same error. 

I have tried cleaning the project and reinstalling the app so far but the issue persist.
should i be using different library, I tried `realm-android-0.87.4.jar` jar file but i still get the same error

**Comment by cmelchior** [comment]
Hi @pankajnimgade 
Can you create a sample project that can reproduce the error? If that is the case you can send it to help@realm.io so we can look at.

**Comment by pankajnimgade** [comment]
@cmelchior, I tried several time to reproduce the error with fresh project but could not. Apparently I would have to conclude that there must be something going wrong in my project. With new ones I am not facing this issue.

**Comment by hohnamkung** [comment]
I'm using Realm v0.87.5 and have a similar issue.
Sorry about reproducing but it's reported from crash reporting system and i couldn't.
Interesting thing is this exception happens only Android 4


    Fatal Exception: java.lang.ExceptionInInitializerError
       at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:325)
       at io.realm.RealmConfiguration$Builder.(RealmConfiguration.java)
       at kr.co.vcnc.android.couple.core.CoupleApplication.getDefaultRealmConfiguration(CoupleApplication.java:317)
       at kr.co.vcnc.android.couple.core.CoupleApplication.onCreate(CoupleApplication.java:142)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
       at android.app.ActivityThread.access$1600(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
    Caused by io.realm.exceptions.RealmException: Could not find io.realm.DefaultRealmModuleMediator
       at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:231)
       at io.realm.RealmConfiguration.(RealmConfiguration.java)
       at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:325)
       at io.realm.RealmConfiguration$Builder.(RealmConfiguration.java)
       at kr.co.vcnc.android.couple.core.CoupleApplication.getDefaultRealmConfiguration(CoupleApplication.java:317)
       at kr.co.vcnc.android.couple.core.CoupleApplication.onCreate(CoupleApplication.java:142)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
       at android.app.ActivityThread.access$1600(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
    Caused by java.lang.ClassNotFoundException: io.realm.DefaultRealmModuleMediator
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:251)
       at java.lang.Class.forName(Class.java:216)
       at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:226)
       at io.realm.RealmConfiguration.(RealmConfiguration.java)
       at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:325)
       at io.realm.RealmConfiguration$Builder.(RealmConfiguration.java)
       at kr.co.vcnc.android.couple.core.CoupleApplication.getDefaultRealmConfiguration(CoupleApplication.java:317)
       at kr.co.vcnc.android.couple.core.CoupleApplication.onCreate(CoupleApplication.java:142)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
       at android.app.ActivityThread.access$1600(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
    Caused by java.lang.NoClassDefFoundError: kr.co.vcnc.android.couple.between.api.model.chat.RMessage
       at io.realm.DefaultRealmModuleMediator.(DefaultRealmModuleMediator.java)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:251)
       at java.lang.Class.forName(Class.java:216)
       at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:226)
       at io.realm.RealmConfiguration.(RealmConfiguration.java)
       at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:325)
       at io.realm.RealmConfiguration$Builder.(RealmConfiguration.java)
       at kr.co.vcnc.android.couple.core.CoupleApplication.getDefaultRealmConfiguration(CoupleApplication.java:317)
       at kr.co.vcnc.android.couple.core.CoupleApplication.onCreate(CoupleApplication.java:142)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
       at android.app.ActivityThread.access$1600(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

![screen shot 2016-03-08 at 11 57 33 pm](https://cloud.githubusercontent.com/assets/1873136/13605160/86dd3bb4-e589-11e5-9878-e399c32c9cd0.png)

**Comment by gorje001** [comment]
I received the same error after I upgraded to 0.88.1.   I reverted back to 0.87.5 and everything works.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:56982 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflgH-001eHs-2C
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:54:25 -0400
Date: Mon, 14 Mar 2016 13:54:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457988846;
	bh=jAbgBEJrIaHIoc1rYXPmfF5b7SeDAXks0diDXrITCDA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=DHiFaR5/vJcduLmjSc2uytMCaeKf2pkf2ZU1wLtC0JBUH01p/6UP9LAQB7bFZhUpE
	 +7E5LTbaTKNEheI0RyBfqHcl1ZZaF2B3/LwgFD9zqMvyT2+Tv+ZYBXN2diJaVVGPx0
	 rkpl1zXwgQjE1+7qXh1hLhq19/9Ge6AHyUquw/pg=
