### ISSUE TITLE
DynamicRealmObject can't set the list field

### ISSUE THREAD

**Issue by misha-vakulich** [realm/realm-java#2368]
I have DynamicRealmObject instance that has list field that is connected to some scheme,
but when I use DynamicRealmObject.setList - I have an exception that says that list items should be the same type as original object is

`java.lang.IllegalArgumentException: Element at index 0 is not the proper type. Was class_testInnerWithList3_details expected class_testInnerWithList3.
at io.realm.DynamicRealmObject.setList(DynamicRealmObject.java:595)
at com.kinvey.android.cache.ClassHash.saveData(ClassHash.java:209)
at com.kinvey.android.cache.RealmCache.insertOrUpdate(RealmCache.java:285)
at com.kinvey.android.cache.RealmCache.save(RealmCache.java:155)
at com.kinvey.androidTest.cache.CacheTest.testSaveWithInnerList(CacheTest.java:179)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1873)
`

in my test I create object with scheme name testInnerWithList3 and list items are expected to be testInnerWithList3_details

and when I'm trying to use DynamicRealmObject.setList(RealmList) I got following exception

**Comment by beeender** [comment]
Could you please share some relevant code here? Your Model class definition and code close to where the exception happens.

**Comment by misha-vakulich** [comment]
[realmissue 3.zip](https://github.com/realm/realm-java/files/153530/realmissue.3.zip)
here is the sample android project that contains single jUnit that reproduce the given issue

**Comment by beeender** [comment]
Thanks a lot for the sample project! We can confirm it is a bug, I am fixing it right now.
