### ISSUE TITLE
java.lang.NoClassDefFoundError: io.realm.internal.async.RealmThreadPoolExecutor

### ISSUE THREAD

**Issue by mystreamforyou** [realm/realm-java#2509]
java.lang.NoClassDefFoundError: io.realm.internal.async.RealmThreadPoolExecutor

E/dalvikvm: Could not find class 'io.realm.internal.Table', referenced from method io.realm.Realm.getTable

**Comment by stk1m1** [comment]
@mystreamforyou Could you share the stacktrace and the version of realm you're using?

**Comment by stk1m1** [comment]
@mystreamforyou Hi, any progress so far? We'd highly appreciate your input.

**Comment by beeender** [comment]
Close due to no response

**Comment by gmartinsribeiro** [comment]
FATAL EXCEPTION: main
                                                                 java.lang.ExceptionInInitializerError
                                                                     at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:428)
                                                                     at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:391)
                                                                     at packagename.onCreate(Application.java:85)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1010)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.ExceptionInInitializerError
                                                                     at io.realm.RealmConfiguration.<clinit>(RealmConfiguration.java:73)
                                                                     at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:428) 
                                                                     at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:391) 
                                                                     at packagename.Application.onCreate(Application.java:85) 
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1010) 
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: java.lang.NoClassDefFoundError: io.realm.internal.async.RealmThreadPoolExecutor
                                                                     at io.realm.BaseRealm.<clinit>(BaseRealm.java:70)
                                                                     at io.realm.RealmConfiguration.<clinit>(RealmConfiguration.java:73) 
                                                                     at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:428) 
                                                                     at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:391) 
                                                                     at packagename.Application.onCreate(Application.java:85) 
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1010) 
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by mahdisml** [comment]
i got this error now :(

**Comment by Zhuinden** [comment]
@mahdisml stack trace and Realm version
