### ISSUE TITLE
Rx + Realm at random throws "Realm access from incorrect thread"

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#2537]
Hey there,

The code below at random throws `java.lang.IllegalStateException: Realm access from incorrect thread.` if you execute it one by one some amount of consecutive times.

_P.S. The code itself is a simplified version of the production code, that's why there is subscribe() right after observeOn(Schedulers.io())._

```java
private void execute() {
        Realm realm = null;
        try {
            realm = getDefaultInstance();
            realm.where(UserRealm.class)
                    .equalTo("name", "[this condition will never be true]") // so the resulted RealmResult is empty
                    .findAll()
                    .asObservable()
                    .take(1)
                    .flatMap(users -> Observable.<UserRealm>from(users).map(UserRealm::getName).toList()) // essential part to reproduce the issue
                    .observeOn(Schedulers.io())
                    .subscribe(new Observer<List<String>>() {
                        @Override
                        public void onCompleted() {
                        }

                        @Override
                        public void onError(Throwable e) {
                        }

                        @Override
                        public void onNext(List<String> objects) {
                        }
                    });
        } finally {
            if (realm != null) realm.close();
        }
    }
```

Full Stacktrace:
```java
03-31 14:21:34.723 18206-18206/com.playground E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                                 Process: com.playground, PID: 16717
                                                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: rx.exceptions.UnsubscribeFailedException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
                                                                                     at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:98)
                                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:195)
                                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                                  Caused by: java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
                                                                                     at io.realm.BaseRealm.checkIfValid(BaseRealm.java:374)
                                                                                     at io.realm.RealmResults.removeChangeListener(RealmResults.java:911)
                                                                                     at io.realm.rx.RealmObservableFactory$3$2.call(RealmObservableFactory.java:128)
                                                                                     at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                                                     at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                                     at rx.internal.util.SubscriptionList.unsubscrib®eFromAll(SubscriptionList.java:124)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                                                     at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                                                     at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
                                                                                     at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
                                                                                     at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                                     at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:95)
                                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:195) 
                                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162) 
                                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
```
#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 1.5.0

Which Android version and device: Genymotion 6.0

**Comment by cmelchior** [comment]
Hi @RobertoArtiles 

I am suspecting it is happening because your subscription runs on the `Schedulers.io()` thread and RealmObservable is on the UI thread, so when you unsubsubscribe (or the stream complete), it will try to unsubscribe on the `Schedulers.io` thread as well, which will throw the exception.

Have you tried adding a 

`
.unsubscribeOn(AndroidSchedulers.mainThread())
```
?

**Comment by RobertoArtiles** [comment]
@cmelchior I tried calling observeOn(AndroidSchedulers.mainThread()) right before subscribe and it helped. But what I think is the problem, that it's not 100% reproducible, and it's very dependable on the timing. That's what is scaring, because you might miss it during the development stage. It preferably should either 100% times fail, or 100% times work.

**Comment by cmelchior** [comment]
Testing this with:

```
    @Test
    @UiThreadTest
    public void rxJavaProblem() {

        for (int i = 0; i < 10; i++) {
            runTest(i);
        }
    }

    private void runTest(final long id) {
        realm.where(AllTypes.class)
                .equalTo(AllTypes.FIELD_STRING, "[this condition will never be true]") // so the resulted RealmResult is empty
                .findAll()
                .asObservable()
                .doOnSubscribe(new Action0() {
                    @Override
                    public void call() {
                        Log.i("RxTest", "Subscribe:" + id);
                        Log.i("RxTest", Thread.currentThread().getName());
                    }
                })
                .doOnUnsubscribe(new Action0() {
                    @Override
                    public void call() {
                        Log.i("RxTest", "UnSubscribe:" + id);
                        Log.i("RxTest", Thread.currentThread().getName());
                    }
                })
                .take(1)
                .flatMap(new Func1<RealmResults<AllTypes>, Observable<List<String>>>() {
                    @Override
                    public Observable<List<String>> call(RealmResults<AllTypes> results) {
                        return Observable.from(results).map(new Func1<AllTypes, String>() {
                            @Override
                            public String call(AllTypes allTypes) {
                                return allTypes.getColumnString();
                            }
                        }).toList();
                    }
                })
                .observeOn(Schedulers.io())
                .subscribe(new Observer<List<String>>() {
                    @Override
                    public void onCompleted() {
                        Log.i("RxTest", "Done:" + id);
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.i("RxTest", "Done:" + id);
                    }

                    @Override
                    public void onNext(List<String> strings) {

                    }
                });
    }
```

And it does indeed crash:

```
04-05 11:30:58.418 3381-3381/io.realm.test I/RxTest: Subscribe:0
04-05 11:30:58.418 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.419 3381-3381/io.realm.test I/RxTest: UnSubscribe:0
04-05 11:30:58.419 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.420 3381-3401/io.realm.test I/RxTest: Done:0
04-05 11:30:58.421 3381-3381/io.realm.test I/RxTest: Subscribe:1
04-05 11:30:58.421 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.421 3381-3381/io.realm.test I/RxTest: UnSubscribe:1
04-05 11:30:58.421 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.427 3381-3381/io.realm.test I/RxTest: Subscribe:2
04-05 11:30:58.427 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.427 3381-3381/io.realm.test I/RxTest: UnSubscribe:2
04-05 11:30:58.427 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.429 3381-3381/io.realm.test I/RxTest: Subscribe:3
04-05 11:30:58.429 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.429 3381-3381/io.realm.test I/RxTest: UnSubscribe:3
04-05 11:30:58.430 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.434 3381-3381/io.realm.test I/RxTest: Subscribe:4
04-05 11:30:58.435 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.436 3381-3381/io.realm.test I/RxTest: UnSubscribe:4
04-05 11:30:58.436 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.436 3381-3381/io.realm.test I/RxTest: Subscribe:5
04-05 11:30:58.436 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.436 3381-3381/io.realm.test I/RxTest: UnSubscribe:5
04-05 11:30:58.436 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.451 3381-3381/io.realm.test I/RxTest: Subscribe:6
04-05 11:30:58.452 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.452 3381-3381/io.realm.test I/RxTest: UnSubscribe:6
04-05 11:30:58.452 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.466 3381-3406/io.realm.test I/RxTest: Done:5
04-05 11:30:58.466 3381-3402/io.realm.test I/RxTest: Done:1
04-05 11:30:58.467 3381-3381/io.realm.test I/RxTest: Subscribe:7
04-05 11:30:58.467 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.467 3381-3381/io.realm.test I/RxTest: UnSubscribe:7
04-05 11:30:58.467 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.467 3381-3381/io.realm.test I/RxTest: Subscribe:8
04-05 11:30:58.467 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.468 3381-3381/io.realm.test I/RxTest: UnSubscribe:8
04-05 11:30:58.468 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.469 3381-3381/io.realm.test I/RxTest: Subscribe:9
04-05 11:30:58.469 3381-3381/io.realm.test I/RxTest: main
04-05 11:30:58.470 3381-3406/io.realm.test I/RxTest: Done:9
04-05 11:30:58.470 3381-3406/io.realm.test I/RxTest: UnSubscribe:9
04-05 11:30:58.470 3381-3406/io.realm.test I/RxTest: RxCachedThreadScheduler-6
```

That is not unsurprising though as ID: 9 tries to unsubscribe on a non-main thread. I am a bit perplexed why that is though. Most likely something about RxJava I don't fully understand.

**Comment by cmelchior** [comment]
Adding `unsubscribeOn` seems to fix it though:

```
...
.observeOn(Schedulers.io())
.unsubscribeOn(AndroidSchedulers.mainThread())
.subscribe(...);
```

**Comment by RobertoArtiles** [comment]
@cmelchior Yeah, I don't know how far you want to go with investigating it, since it's a third party integration. But maybe it's at least something you would want to mention in the docs.

**Comment by nhachicha** [comment]
thanks for the feedback @RobertoArtiles  :+1:
