### ISSUE TITLE
Unexpected Realm Exceptions

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2543]
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. bad optional access in io_realm_internal_tableview.cpp line 660
       at io.realm.internal.TableView.nativeSumInt(TableView.java)
       at io.realm.internal.TableView.sumLong(TableView.java:601)
       at io.realm.RealmResults.sum(RealmResults.java:490)
       at com.workoutguru.workoutcash.SweatPoints_Current_Fragment.fetchFitnessDataFromDatabase(SweatPoints_Current_Fragment.java:519)
       at com.workoutguru.workoutcash.SweatPoints_Current_Fragment.onResume(SweatPoints_Current_Fragment.java:244)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2005)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:545)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:607)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:674)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
       at android.view.View.measure(View.java:18804)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by Sutirth** [comment]
This is 2nd Error

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 157
       at io.realm.internal.SharedGroup.nativeAdvanceRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.advanceRead(SharedGroup.java:86)
       at io.realm.internal.ImplicitTransaction.advanceRead(ImplicitTransaction.java:33)
       at io.realm.internal.SharedGroupManager.advanceRead(SharedGroupManager.java:74)
       at io.realm.HandlerController.realmChanged(HandlerController.java:333)
       at io.realm.HandlerController.handleMessage(HandlerController.java:100)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Sutirth** [comment]
This is 3rd error

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: rowIndex is less than 0.
       at io.realm.internal.TableView.nativeGetSourceRowIndex(TableView.java)
       at io.realm.internal.TableView.getSourceRowIndex(TableView.java:127)
       at io.realm.RealmResults.get(RealmResults.java:174)
       at com.workoutguru.workoutcash.CompanyGoals_AllGoals_Fragment$CompanyAllGoalsAdapter$CompanyAllGoalsAdapterViewHolder$2$1.onResponse(CompanyGoals_AllGoals_Fragment.java:808)
       at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$1.run(ExecutorCallAdapterFactory.java:86)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Sutirth** [comment]
All this errors are logged in my crashlytics. Faced by my beta users

**Comment by cmelchior** [comment]
@Sutirth 
Please create an separate issue for each. That way it is easier for us to help you.

**Comment by Sutirth** [comment]
@cmelchior  ahh My bad I will close this and will post separately .

**Comment by Garador** [comment]
I've faced a similar problem recently... It turns out is quite a general error, which was being caught by a try-catch block, therefore, not rendering the details (in Android Studio). Removing the try-catch, I could see what was wrong with my code (a lot of things, to be honest...), and could finally debug it. This might help someone.
```
try{
          //Function storing the Object test into the local database. After I got it out, I could see
          //the details of the error.
          dataB.storeTestsData(test, realmS);
}catch(Exception e){
          Log.i(LOG_LABEL, "Exception storing test!!");
          e.printStackTrace();
}
```
