### ISSUE TITLE
create DynamicRealmObject error:The class class_Event doesn't exist in this Realm.

### ISSUE THREAD

**Issue by cpoopc** [realm/realm-java#2547]
i try to create a DynamicRealmObject as doc descript,but got a exception.

#### exception

Caused by: java.lang.IllegalArgumentException: The class class_Event doesn't exist in this Realm.
                                                                           at io.realm.RealmSchema.getTable(RealmSchema.java:194)
                                                                           at io.realm.DynamicRealm.createObject(DynamicRealm.java:80)
                                                                           at com.cpoopc.hellorequery.MainActivity.onCreate(MainActivity.java:21)
                                                                           at android.app.Activity.performCreate(Activity.java:5231)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:136) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5045) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 

#### Code Sample

```java

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();
        DynamicRealm dynamicRealm = DynamicRealm.getInstance(realmConfiguration);
        dynamicRealm.beginTransaction();
        DynamicRealmObject event = dynamicRealm.createObject("Event");// line 21 exception here:IllegalArgumentException: The class class_Event doesn't exist in this Realm.
        event.set("name", "test");
        dynamicRealm.commitTransaction();

```

#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 2.1 preview 3

Which Android version and device: 19

**Comment by dalinaum** [comment]
Hello @cpoopc. Do you have `Event` class? `Event` class is needed before you `dynamicRealm.createObject("Event")`.

**Comment by cpoopc** [comment]
@dalinaum thanks for your reply.
I throught the dynamic objects's schema also dynamic..
now i create a Event class,
but i still could not set("name", "test"),because Event class does not has "name" field.
how can i store a key/value dynamic?

**Comment by kneth** [comment]
@cpoopc Can you show us the `Event` class?

**Comment by cpoopc** [comment]
Event class may has some dynamic "Field" like 'content','scence' or anything else..(it will be config by backend,it can't be define at compile time.)
so my purpose is save the dynamic field into Realm.

```
public class Event extends RealmObject {
    private String id;
    private String name;
    private RealmList<Audio> audios;

    public RealmList<Audio> getAudios() {
        return audios;
    }

    public void setAudios(RealmList<Audio> audios) {
        this.audios = audios;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
``` 

I had try many ways finally i find the key point is the ``RealmObjectSchema``.
whitch the docs does not mention about it.
I check if schama has Field and dynamic add field.
I don't know if this usage is right..

```
        DynamicRealm dynamicRealm = DynamicRealm.getInstance(App.getConfiguration());
        dynamicRealm.beginTransaction();
        DynamicRealmObject dyEvent = dynamicRealm.createObject("Event");
        RealmObjectSchema eventSchama = dynamicRealm.getSchema().get("Event");
        if (!eventSchama.hasField("content")) {
            DebugLog.i("eventSchama.has not Field content");
            eventSchama.addField("content", String.class);
        } else {
            DebugLog.i("eventSchama.hasField content");
        }
        RealmResults<DynamicRealmObject> dyEventResult = dynamicRealm.allObjects("Event");
        DebugLog.i("dyEventResult.size:" + dyEventResult.size());
        dyEvent.setString("name", "testName_" + dyEventResult.size());
        dyEvent.setString("content", "testContent_" + dyEventResult.size());

        dynamicRealm.commitTransaction();
```

**Comment by beeender** [comment]
The usage is fine. But usually the schema modification happens in the Migration block.
Can I ask why do you use `DynamicRealm` instead of typed normal `Realm`?

**Comment by cpoopc** [comment]
@beee because **DynamicRealmObject** need to be created by **DynamicRealm** instance.
``` DynamicRealmObject dyEvent = dynamicRealm.createObject("Event") ```
``` dyEvent.setString("content", "testContent_" + dyEventResult.size()); ```

**Comment by beeender** [comment]
When you have a `RealmObject` `Event` declared and the schema created, you actually can do
```
Event event = realm.createObject(Event.class);
event.setContent("testContent_" + dyEventResult.size());
```
Dynamic API would be a bit slower.

Do you always use Dynamic APIs instead of using any typed APIs like above?

**Comment by cpoopc** [comment]
because **Event** class has not **content** field,
fields like **content**,**scene** etc are dynamic config by back-end.
only in this case  i use the Dynamic API

**Comment by beeender** [comment]
@cpoopc Be careful, if the `Event` doesn't have `content` field, and you are using Dynamic API after open a typed Realm instance, you might probably messed the data in the database, since the cached schema for typed realm will be different from the one changed by DynamicAPI. And that is the reason we suggest changing the schema in the migration.

**Comment by cpoopc** [comment]
thanks,I will be careful while using Dynamic API.

**Comment by IgorGanapolsky** [comment]
Is there a solution to using `DynamicRealm` properly?
