### ISSUE TITLE
Restore RealmDB from backup

### ISSUE THREAD

**Issue by nachogarrone** [realm/realm-java#2552]
Hi, I'm trying to achieve backup up of my Realm DB.

In my MyApplication class:
```
static RealmConfiguration backupConfiguration;

    public static String REALM_NAME_BACKUP = "backup.realm";
    public static String REALM_NAME_DEFAULT = "default.realm";

    @Override
    public void onCreate() {
        super.onCreate();

        int schemaVersion = 10;

        RealmConfiguration realmConfiguration = new RealmConfiguration
                .Builder(this)
                .name(REALM_NAME_DEFAULT)
                .deleteRealmIfMigrationNeeded()
                .schemaVersion(schemaVersion)
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);

        backupConfiguration = new RealmConfiguration
                .Builder(this)
                .name(REALM_NAME_BACKUP)
                .schemaVersion(schemaVersion)
                .build();
    }

    public static RealmConfiguration getBackupConfiguration() {
        return backupConfiguration;
    }
```

And in my MyBackupAgentHelper i do backup the file correct, and recover it correctly too. I created another realmConf to separate the backup and the actual data.

I use a SplashScreen to look for a backup and restore it, so i never called getInstance yet.

OnRestore i try this: 
```
// Be sure default realm is closed
            Realm defaultRealm = Realm.getDefaultInstance();
            defaultRealm.close();
            // Delete default realm file
            Realm.deleteRealm(Realm.getDefaultInstance().getConfiguration());
            // Restore default from backup file
            Realm backup = Realm.getInstance(MyApplication.getBackupConfiguration());
            File defaultDB = new File(realmPath(), MyApplication.REALM_NAME_DEFAULT);
            try {
                backup.writeCopyTo(defaultDB);
            } catch (IOException e) {
                e.printStackTrace();
            }
            backup.close();
```

As you see, i never called Real.getDefaultInsance() without calling close()
I get always 
```
D/BackupServiceBinder: onRestore (com.damian.libros.backup.MyBackupAgent) threw
                                                                      java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file: /data/data/com.damian.libros/files/default.realm
                                                                          at io.realm.BaseRealm$1.onResult(BaseRealm.java:578)
                                                                          at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:249)
                                                                          at io.realm.BaseRealm.deleteRealm(BaseRealm.java:573)
                                                                          at io.realm.Realm.deleteRealm(Realm.java:1469)
                                                                          at com.damian.libros.backup.MyBackupAgent.restore(MyBackupAgent.java:145)
                                                                          at com.damian.libros.backup.MyBackupAgent.onRestore(MyBackupAgent.java:77)
                                                                          at android.app.backup.BackupAgent$BackupServiceBinder.doRestore(BackupAgent.java:653)
                                                                          at android.app.IBackupAgent$Stub.onTransact(IBackupAgent.java:106)
                                                                          at android.os.Binder.execTransact(Binder.java:446)
04-04 20:08:52.741 2808-2823/com.damian.libros W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                         java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file: /data/data/com.damian.libros/files/default.realm
                                                             at io.realm.BaseRealm$1.onResult(BaseRealm.java:578)
                                                             at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:249)
                                                             at io.realm.BaseRealm.deleteRealm(BaseRealm.java:573)
                                                             at io.realm.Realm.deleteRealm(Realm.java:1469)
                                                             at com.damian.libros.backup.MyBackupAgent.restore(MyBackupAgent.java:145)
                                                             at com.damian.libros.backup.MyBackupAgent.onRestore(MyBackupAgent.java:77)
                                                             at android.app.backup.BackupAgent$BackupServiceBinder.doRestore(BackupAgent.java:653)
                                                             at android.app.IBackupAgent$Stub.onTransact(IBackupAgent.java:106)
                                                             at android.os.Binder.execTransact(Binder.java:446)
```

#### Version of Realm and tooling
Realm version(s): 0.88.0

Android Studio version: 1.5.1

Which Android version: Testes in 5.1 and 6.0

**Comment by dalinaum** [comment]
Hello, @nachogarrone. Realm instance will be closed if there is no more local reference to itself in the current thread. You cannot close your Realm instance like the following:

```
Realm defaultRealm = Realm.getDefaultInstance();
defaultRealm.close();
```

You should match `close()` to the exist Realm instance instead of another `Realm.getDefaultInstance()`.

**Comment by nachogarrone** [comment]
@dalinaum thanks for your response. I know those 2 lines doesn't close any other instance than the one instantiating in that line, i just wrote them to verify the instance is getting correctly and closing correct. 
The problem is, i never called getDefaultInstance() before and i get that error message.

Is there any way an instance could be created with .getRealmFolder() or .getRealmPath()?

**Comment by beeender** [comment]
@nachogarrone 
`Realm.deleteRealm(Realm.getDefaultInstance().getConfiguration());` I think this is the problem. Before calling into the ``Realm.deleteRealm()`, `Realm.getDefaultInstance()` will be first executed and that will created a anonymous Realm instance. The problem is, then there is no place to call `close()` on the anonymous instance.

**You could just make `realmConfiguration` as a static field somewhere and call `Realm.deleteRealm(realmConfiguration)`** or by following your current pattern, you can:

```
Realm realm = Realm.getDefaultInstance();
RealmConfiguration tempConfig = realm.getConfiguration();
realm.close();
Realm.deleteRealm(tempConfig);
```

**But I don't suggest above since it create unnecessary overhead when getting/closing Realm instance.**

**Comment by nachogarrone** [comment]
@beeender you are right! 
Realm.deleteRealm(Realm.getDefaultInstance().getConfiguration()); keeps an anonymous instance.

Thanks!

**Comment by mikemee** [comment]
@nachogarrone did you end up with a solution that works for you?  This sounds like something useful to add to https://github.com/eggheadgames/android-realm-asset-helper/ as we would like to do something like this in our Android apps, and I'm guessing others will too.  (For now I will be happy to stop Android backing up our realm dbs!)

**Comment by nachogarrone** [comment]
@mikemee I ended up not backing up the db :\  I came up with another solution to "backup" the data, exporting it to csv. My client didn't wanted the backup so bad, so i didn't dig up a lot more. But i think it should be in the best practices document, as it is crucial.

**Comment by nachogarrone** [comment]
Check out this post, it has been very usefull to backup my Realm DB. 
[https://medium.com/glucosio-project/example-class-to-export-import-a-realm-database-on-android-c429ade2b4ed#.ups9hgxdh](url)
