### ISSUE TITLE
Realm Shared Group Crash

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2553]
The exception I am getting is as follows

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 157
       at io.realm.internal.SharedGroup.nativeAdvanceRead(SharedGroup.java)
       at io.realm.internal.SharedGroup.advanceRead(SharedGroup.java:86)
       at io.realm.internal.ImplicitTransaction.advanceRead(ImplicitTransaction.java:33)
       at io.realm.internal.SharedGroupManager.advanceRead(SharedGroupManager.java:74)
       at io.realm.HandlerController.realmChanged(HandlerController.java:333)
       at io.realm.HandlerController.handleMessage(HandlerController.java:100)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by cmelchior** [comment]
Hi @Sutirth 
What version of Realm are you using? The error seems to be happening because it tries to update a closed Realm (which we fixed some versions ago).

**Comment by Sutirth** [comment]
hi @cmelchior  I am using  compile 'io.realm:realm-android:0.87.5' this version atm

**Comment by cmelchior** [comment]
Hmm, that is strange then. Do you use other LooperThreads than the main thread?

**Comment by Sutirth** [comment]
@cmelchior I am using Intent Service as well if thats what are you asking.

**Comment by cmelchior** [comment]
Yes, that would be a LooperThread other than the main thread. Thanks.

**Comment by cmelchior** [comment]
Do you have any additional data about the crash? How often is it happening? On which devices/versions of Android?

**Comment by cmelchior** [comment]
Also, can you post your code in the IntentService?

**Comment by Sutirth** [comment]
75 % Xiaomi android (4.4.4)
25% LGE nexus 5 (6.0.1)

Crash are very intermittent I am still in development phase the thing is whenever I release my build for testing purpose it definitely crashes

**Comment by Sutirth** [comment]
@cmelchior  Intent service code would be too long here would like me to mail it ??

**Comment by cmelchior** [comment]
help@realm.io. Thanks a lot.

**Comment by cmelchior** [comment]
Closing due to no response
