### ISSUE TITLE
create DynamicRealmObject error:throws class class_Person doesn't exist in this Realm.

### ISSUE THREAD

**Issue by chenzj-king** [realm/realm-java#2623]
i create the DynamicRealmObject will got a exception.like [https://github.com/realm/realm-java/issues/2547](url)

### Exception ###
04-20 09:14:58.930 22147-22147/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.sq580.followup, PID: 22147
                                                   java.lang.IllegalArgumentException: The class class_Person doesn't exist in this Realm.
                                                       at io.realm.RealmSchema.getTable(RealmSchema.java:194)
                                                       at io.realm.DynamicRealm.createObject(DynamicRealm.java:80)
                                                       at com.sq580.followup.database.RealmManager.createObject(RealmManager.java:75)
                                                       at com.sq580.followup.ui.activity.main.MainActivity$3.run(MainActivity.java:163)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

i had create the Person class.
    
	public class Person extends RealmObject {
	
	    @PrimaryKey
	    private String _id;
	
	    @Required
	    private String _ver;
	    @Required
	    private String collection;
	
	    public String get_id() {
	        return _id;
	    }
	
	    public void set_id(String _id) {
	        this._id = _id;
	    }
	
	    public String get_ver() {
	        return _ver;
	    }
	
	    public void set_ver(String _ver) {
	        this._ver = _ver;
	    }
	
	    public String getCollection() {
	        return collection;
	    }
	
	    public void setCollection(String collection) {
	        this.collection = collection;
	    }
	
	    @Override
	    public String toString() {
	        return "Person{" +
	                "_id='" + _id + '\'' +
	                ", _ver='" + _ver + '\'' +
	                ", collection='" + collection + '\'' +
	                '}';
	    }
	}

Code Sample

    RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(AppContext.getInstance())
                .name("followup.realm")
                .build();
    mDynamicRealm = DynamicRealm.getInstance(realmConfiguration);
	mDynamicRealm.beginTransaction();
    DynamicRealmObject dynamicRealmObject = mDynamicRealm.createObject("Person");
    mDynamicRealm.commitTransaction();

also i find that the RealmConfiguration must has a name.wiki didn't tell me about that.

### Version of Realm and tools ###
Realm version(s): 0.88.3

Android Studio version: 2.1beta3

Which Android version and device: 21

**Comment by beeender** [comment]
The Object schema will be automatically created when the first time open a typed Realm instance like `Realm.getInstance(configuration)`. it won't be created when opening a dynamic Realm instance.

You can:
1. Open a type Realm instance first to let Realm handle the object schema creation.
or 
2. Create schema manually through `RealmSchema` and `RealmObjectSchema` API.

**Comment by chenzj-king** [comment]
thanks for you answer. @beeender 

i init Realm then init Dynamicrealm.it work.

    RealmConfiguration config = new RealmConfiguration.Builder(AppContext.getInstance())
                .name("followup.realm")
                .setModules(new CustomModule())
                .build();
        mRealm = Realm.getInstance(config);

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(AppContext.getInstance())
                .name("followup.realm")
                .setModules(new CustomModule())
                .build();
        mDynamicRealm = DynamicRealm.getInstance(realmConfiguration);

but i have a new problem.

### Exception ###
04-21 10:16:39.820 4988-4988/com.sq580.followup E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.sq580.followup, PID: 4988
                                                                  io.realm.exceptions.RealmError: Unrecoverable error. Column index out of range in io_realm_internal_UncheckedRow.cpp line 298
                                                                      at io.realm.internal.UncheckedRow.nativeSetString(Native Method)
                                                                      at io.realm.internal.UncheckedRow.setString(UncheckedRow.java:229)
                                                                      at io.realm.DynamicRealmObject.setString(DynamicRealmObject.java:499)
                                                                      at com.sq580.followup.database.RealmManager.createObject(RealmManager.java:88)
                                                                      at com.sq580.followup.ui.activity.main.MainActivity$2.run(MainActivity.java:122)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

when i run this code.will throws RealmError Exception

    for (Map.Entry<String, String> entry : fieldMaps.entrySet()) {
            dynamicRealmObject.setString(entry.getKey(), entry.getValue());
    }

because my fields is dynamics.so i use the map to save new field.but i look like can't support this features.

RealmObject need define all field before use that.so i can't create schema manually through RealmSchema and RealmObjectSchema API.

**Comment by beeender** [comment]
Did you change the schema after opening a typed Realm? That basically won't work since typed Realm relies on a fixed schema. Why do you us dynamic Realm instead of typed Realm? Dynamic API will be slower and has less safety checks. If you don't have a special reason (like the schema needs to be changed dynamically), we strongly suggest you to use normal typed Realm API.

**Comment by chenzj-king** [comment]
Yes.I have a special reason to dynamically changed  schema. How can i do this?
Can i do like this.

1. init typed Realm to automatically created schema by Person class etc.
2. close the typed Realm and open the DynamicRealm.
3. dynamically changed schema normal.

**Comment by beeender** [comment]
yes, you can.
But notice, after step 3, the Realm schema has been changed which won't match your model definition anymore, then next time (re-launch the app) you open  the typed Realm, an migration exception will be thrown and in your case, it would be no way to solve that since you actually except to have a different schema than the one defined in the model.

**Comment by beeender** [comment]
If you can explain the reason why you need the dynamic Realm, maybe we can give you a better suggestion.

**Comment by chenzj-king** [comment]
Like Person class. First I have name/age/sex field. Our app is hybrid app. The h5 will add some field when our business change. Such like add facebookAccount/githubAccount field. If I use typed Realm. It can't support this operate. Also I should update some dictionary by my server Api. In conclusion. I need to ues DynamicRealm. Though it slower and has less safety checks.

**Comment by beeender** [comment]
Oh, OK. Then I understand. You could also define something like
```
public class Attribute extends RealmObject {
    String attrID;
    String attrValue;
}

public class Person {
    RealmList<Attribute> attributes;
}
```

Then you can use typed Realm. But you won't be able to sort by the attribute value which is a big drawback.

But anyway, I think it is OK for you to use Dynamic API, but in your case, it is better to create all the schemas by yourself.

**Comment by chenzj-king** [comment]
@beeender Thanks.I get it.
