### ISSUE TITLE
UnsatisfiedLinkError from nativeGetTablePrefix

### ISSUE THREAD

**Issue by amphora001** [realm/realm-java#2647]
#### Goal

Update application to Realm 0.89.0 from 0.83.1, and encrypt the database

#### Expected Results

App should not crash

#### Actual Results

04-22 12:30:51.554 30305-30379/com.locationlabs.android_stallone E/FamilyGraph: ll.u.a.LLUncaughtExceptionHandler.uncaughtException:69 | UNCAUGHT EXCEPTION IN Thread[pool-4-thread-3,5,main] @ [r.i.s.ScheduledAction.run:62]
                                                                                java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                    at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String io.realm.internal.Util.nativeGetTablePrefix() (tried Java_io_realm_internal_Util_nativeGetTablePrefix and Java_io_realm_internal_Util_nativeGetTablePrefix__)
                                                                                    at io.realm.internal.Util.nativeGetTablePrefix(Native Method)
                                                                                    at io.realm.internal.Util.getTablePrefix(Util.java:47)
                                                                                    at io.realm.internal.Table.<clinit>(Table.java:38)
                                                                                    at io.realm.RealmSchema.<clinit>(RealmSchema.java:40)
                                                                                    at io.realm.BaseRealm.<init>(BaseRealm.java:78)
                                                                                    at io.realm.Realm.<init>(Realm.java:138)
                                                                                    at io.realm.Realm.createAndValidate(Realm.java:269)
                                                                                    at io.realm.Realm.createInstance(Realm.java:249)
                                                                                    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
                                                                                    at io.realm.Realm.getDefaultInstance(Realm.java:195)
                                                                                    at com.locationlabs.android_stallone.persistence.stores.RealmPersistStore.getStore(RealmPersistStore.java:39)
                                                                                    at com.locationlabs.android_stallone.persistence.stores.RealmPersistStore.access$000(RealmPersistStore.java:37)
                                                                                    at com.locationlabs.android_stallone.persistence.stores.RealmPersistStore$3.call(RealmPersistStore.java:100)
                                                                                    at com.locationlabs.android_stallone.persistence.stores.RealmPersistStore$3.call(RealmPersistStore.java:97)
                                                                                    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                                    at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:115)
                                                                                    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                    at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                    at java.lang.Thread.run(Thread.java:818) 

#### Steps & Code to Reproduce

I created a brand new app and tried out 0.89.0 and everything was fine. I even used Rx to do a query on a separate thread just as I do on my actual application. In the brand new app, it works, but in my app it doesn't.

My app is big so it's multi-dex enabled. But I ran the app on an M phone and it didn't make a difference and I thought it might if it's a multi-dex problem.

I tried calling RealmCore.loadLibrary(); at the onCreate of my Application class and it ran without throwing an exception.

All realm codes are running in a single worker thread via RxJava 'io.reactivex:rxandroid:1.0.1' and 'com.jakewharton.rxbinding:rxbinding:0.4.0'

I revert it back to using 0.83.1 with dependency rather than plugin way of 0.89.0 and everything went back normal. But I don't want to get stuck on 0.83.1 as documentation suggest that encryption is not supported on all devices until at least 0.85, which I also tried without any success.

#### Version of Realm and tooling
Realm version(s): 0.89

Android Studio version: 2.0

Which Android version and device: Galaxy GS5 Android version 5.0

**Comment by amphora001** [comment]
I tried adding this and I got the same error

   splits {
      abi {
         enable true
         reset()
         include 'arm', 'arm-v7a', 'arm64'
      }
   }

**Comment by amphora001** [comment]
I also tried calling  ReLinker.loadLibrary(getApplicationContext(), "realm-jni"); but it did not help

**Comment by beeender** [comment]
Did you remove `compile 'io.realm:realm-android:0.83.1'` from your app's `build.gradle`?
It seems you have wrong `.so` packed with the apk file.

**Comment by amphora001** [comment]
Yes i removed compile dependency and only use plugin when I use 0.89.

**Comment by beeender** [comment]
@amphora001 Can you please share your apk file with us? to help@realm.io

**Comment by amphora001** [comment]
Ok I can do that tomorrow morning when I get back to my office computer. Thanks in advance for helping us out!

**Comment by beeender** [comment]
@amphora001 The so files in the apk you sent are not for version `v0.89.0`. Instead, they are from `v0.83.1` release.

md5sum of x86_64/librealm-jni.so for `v0.83.1` (And the same so in the apk you sent)
```
f5094cce4493da5c696e58a9d02bd2ac
```

md5sum of x86_64/librealm-jni.so for `v0.89.0`
```
d3792eaaf9ed05cd423cbbab477c371b
```

Did you remove compile 'io.realm:realm-android:0.83.1' from your app's build.gradle?
And you don't need `'io.realm:realm-android:0.89.0'`, instead, you just follow instructions here https://realm.io/docs/java/latest/#installation

And clean the project before build.

**Comment by amphora001** [comment]
I definitely removed "compile 'io.realm:realm-android:0.83.1'"
I then added "classpath "io.realm:realm-gradle-plugin:0.89.0" to build script block in my top level gradle file, and after that I apply plugin: 'realm-android' in my app grade file.

I then did a ./gradlew clean assembleDebug before sending you the file from my app/build/output/apk folder.

I'll try to clone my repo branch in a new local directory to see if it's a local issue tomorrow and get back to you.

How does the plugin work? Does it just setup the dependency for you instead of having me manually type in compile 'io.realm:realm-android:0.93.0'? Is the jar/aar stored in the normal place, ~/gradle/cache or do you put it somewhere else? What should I do other than ./gradlew clean to ensure that no trace of the old jar/aar is in my machine?

**Comment by beeender** [comment]
An aar will be downloaded to `.gradle/caches/modules-2/files-2.1/io.realm` (at least on my machine)

The plugin is actually very simple, you can take a look at the source code here https://github.com/realm/realm-java/blob/master/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy#L52 

I think `./gradlew clean` is enough, but, who knows... Gradle has too much magic to me... Usually i will just delete the `build` folder.

**Comment by amphora001** [comment]
That's interesting. You guys are adding jcenter() to the repository list. But we actually use Artifactory to cache all of the dependencies. We don't actually want to connect to jcenter directly.

If I write the following and not apply the plugin, would I be doing the same thing? Maybe it's another thing I can try...

compile "io.realm:realm-android-library:0.89.0"
compile "io.realm:realm-annotations:0.89.0"
apt "io.realm:realm-annotations:0.89.0"
apt "io.realm:realm-annotations-processor:0.89.0"

**Comment by cmelchior** [comment]
@amphora001 The plugin also register our bytecode transformer, so the above is not quite enough.
From what I know Gradle also goes through the repositories in order. So I _think_ that us adding jcenter shouldn't be a big problem since it will be added last,  after your Artifactory.

That doesn't help much figuring out what is wrong in your case though.

**Comment by emanuelez** [comment]
@amphora001 As @cmelchior says you will also have to add the transformer to the classpath and register it like we do here: https://github.com/realm/realm-java/blob/master/realm/realm-library/build.gradle#L39

**Comment by amphora001** [comment]
I found the issue with my code. Someone had previously added the .so files manually into the src. The commit comment indicate that he was resolving some issue with multidex. Thanks for all the help!
