### ISSUE TITLE
java.lang.IllegalArgumentException: b is not part of the schema for this Realm

### ISSUE THREAD

**Issue by jaypoojara** [realm/realm-java#2719]
I just want to sync all contacts of android device to my realm database.
but exception occurred on runtime.
this is the Error
`Process: droid.search, PID: 3795
java.lang.RuntimeException: An error occured while executing doInBackground()
at io.a.a.a.a.c.d.done(Unknown Source)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at io.a.a.a.a.c.i.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.IllegalArgumentException: b is not part of the schema for this Realm
at io.realm.internal.d.a.b(Unknown Source)
at io.realm.internal.d.a.a(Unknown Source)
at io.realm.d.c(Unknown Source)
at io.realm.d.d(Unknown Source)
at io.realm.d.a(Unknown Source)
at droid.search.activity.SplashActivity.a(Unknown Source)
at droid.search.activity.SplashActivity.a(Unknown Source)
at droid.search.activity.i.a(Unknown Source)
at droid.search.activity.i.a(Unknown Source)
at io.a.a.a.a.c.c.call(Unknown Source)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at io.a.a.a.a.c.i.run(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
at java.lang.Thread.run(Thread.java:818) `
Here is my code

**Model**
`    @PrimaryKey
    private int id;
    private String name, mobileNumber,photoUri;

    public String getPhotoUri() {
        return photoUri;
    }

    public void setPhotoUri(String photoUri) {
        this.photoUri = photoUri;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
}`
**using**
`public class GetContacts extends AsyncTask<Void,Void,Void>{
        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            llSyncingContact.setVisibility(View.VISIBLE);
        }

        @Override
        protected Void doInBackground(Void... voids) {
            RealmConfiguration realmConfig = new RealmConfiguration.Builder(SplashActivity.this).build();
            Realm realm = Realm.getInstance(realmConfig);
            syncContact(realm);
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            HandlerThread thread = new HandlerThread("MyHandlerThread");
            thread.start();
            Handler handler = new Handler(thread.getLooper());
            getContentResolver().
                    registerContentObserver(
                            ContactsContract.CommonDataKinds.Phone.CONTENT_URI,
                            true,
                            new ContactObserver(handler,SplashActivity.this));
            llSyncingContact.setVisibility(View.GONE);
            startActivity(new Intent(SplashActivity.this, MainActivity.class));
            finish();
        }
    }`
`private void syncContact(Realm realm) {
        Cursor phones = getContentResolver().query(ContactsContract.CommonDataKinds.Phone.CONTENT_URI, null, null, null, null);

        while (phones.moveToNext()) {
            int id = phones.getInt(phones.getColumnIndex(ContactsContract.CommonDataKinds.Phone.CONTACT_ID));
            String name = phones.getString(phones.getColumnIndex(ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME));
            String phoneNumber = phones.getString(phones.getColumnIndex(ContactsContract.CommonDataKinds.Phone.NUMBER));
            String photoUri = phones.getString(phones.getColumnIndex(ContactsContract.CommonDataKinds.Phone.PHOTO_URI));
            Log.d("realmError",id + " " + name + " " + phoneNumber + " " + photoUri);
            realm.beginTransaction();
            ContactModel contactModel = new ContactModel();
            contactModel.setId(id);
            contactModel.setName(name);
            contactModel.setMobileNumber(phoneNumber);
            contactModel.setPhotoUri(photoUri);
            realm.copyToRealmOrUpdate(contactModel);
            realm.commitTransaction();
        }

        phones.close();
        mTinyDB.putBoolean(Constants.PREFERENCE_IS_FIRST_USE, false);

    }`

Worked on android studio 2.1
Realm library : io.realm:realm-android:0.84.1

**Comment by jaypoojara** [comment]
Proguard was creating problem.
its solved now.
thank you.
