### ISSUE TITLE
Error when deleting last item on RecyclerView

### ISSUE THREAD

**Issue by aerohugo** [realm/realm-java#2725]
Hello

I'm getting an error when trying to delete the last item from a RecyclerView.

With realm version 0.87.1 I use this code:  

`mRealm.beginTransaction();`
`mResults.get(position).removeFromRealm();`
`mRealm.commitTransaction();`
`notifyItemRemoved(position);`

And everythings works fine.

If use the same code with realm version 0.89.1 everything works fine but when I delete last item on Recycler View  I'm getting this error:

```
05-01 13:50:47.232 1837-1837/slidenerd.vivz.bucketdrops E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: slidenerd.vivz.bucketdrops, PID: 1837
                                                                          java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
                                                                              at io.realm.internal.InvalidRow.getStubException(InvalidRow.java:192)
                                                                              at io.realm.internal.InvalidRow.getString(InvalidRow.java:88)
                                                                              at io.realm.DropRealmProxy.realmGet$what(DropRealmProxy.java:77)
                                                                              at slidenerd.vivz.bucketdrops.beans.Drop.getWhat(Drop.java:27)
                                                                              at slidenerd.vivz.bucketdrops.adapters.AdapterDrops.onBindViewHolder(AdapterDrops.java:73)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
                                                                              at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5250)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4487)
                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                              at android.view.View.layout(View.java:14817)
                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                              at android.os.Handler.handleCallback(Handler.java:733)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.sy
```

Thank you for your help.

**Comment by cmelchior** [comment]
You are getting that error because you cannot access any data on the object you deleted. It seems you are reading some String field called `what` after the object was deleted.

**Comment by beeender** [comment]
I am closing this issue now. Please let us know if you still need help.
Thanks!

**Comment by shaunty21** [comment]
> I am closing this issue now. Please let us know if you still need help.
> Thanks!

@beeender how to resolved above issue can u share me the snippest of your code

**Comment by Zhuinden** [comment]
Use `RealmChangeListener` to update your views when a change happens in the database

**Comment by shaunty21** [comment]
But the main problem is that I'm using section recyclerview and we pass two separate models to sectionAdapter So at the time of RealmChangeListener to update view we just pass only one Realm model so the view should be updated for that particular list and other model problem get remain same.

  private class ContactsSection extends StatelessSection implements RealmChangeListener<RealmResults<SymptomsDbModel>> {
        String title;
        ArrayList<SymptomsDbModel> symptomsDbModels;
        ArrayList<LogAttackDbModel> symptomsDbModels1;
        StringBuilder stringBuilder;
        Gson gson;

        public ContactsSection(String key, ArrayList<SymptomsDbModel> symptomsDbModels, ArrayList<LogAttackDbModel> symptomsDbModels1) {
            super(SectionParameters.builder()
                    .itemResourceId(R.layout.symptomlog_item_row)
                    .headerResourceId(R.layout.symptom_log_row)
                    .build());
            this.title = key;
            this.symptomsDbModels = symptomsDbModels;
            this.symptomsDbModels1 = symptomsDbModels1;
            gson = new Gson();
        }

**Comment by Zhuinden** [comment]
Well then you have to rebuild both of your ArrayLists when Realm changes.

**Comment by shaunty21** [comment]
refresh the adapter page or both the list should be clear and add again
i doesn't understand what u exactly telling me?
