### ISSUE TITLE
java.lang.IllegalStateException: Illegal State: Table is no longer valid to operate on.

### ISSUE THREAD

**Issue by berkayturanci** [realm/realm-java#2739]
Hi there, I got an exception on a simple realm query. It is rarely happens but important for us. Thanks for your support.

#### Goal

> To query on a table and get realm result

#### Expected Results

> Get realm result

#### Actual Results

```
java.lang.IllegalStateException: Illegal State: Table is no longer valid to operate on.
at io.realm.internal.Table.nativeWhere(Native Method)
at io.realm.internal.Table.where(Table.java:1412)
at io.realm.RealmQuery.<init>(RealmQuery.java:76)
at io.realm.Realm.where(Realm.java:1198)
at com.infoline.firmcatalog.fragment.ControlRequiredFirmsFragment.onCreateView(ControlRequiredFirmsFragment.java:68)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
at android.view.View.measure(View.java:15619)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:15619)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
at android.view.View.measure(View.java:15619)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
at android.view.View.measure(View.java:15619)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:15619)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:15619)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4919)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2191)
at android.view.View.measure(View.java:15619)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2165)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1249)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1443)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
at android.view.Choreographer.doCallbacks(Choreographer.java:579)
at android.view.Choreographer.doFrame(Choreographer.java:548)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:5293)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

#### Steps & Code to Reproduce

> On each view pager I have some fragments to fill, each fragment has its own realm lists. This exception happens very rarely.

#### Code Sample

```     
private Realm realm;
.........
realm = Realm.getDefaultInstance();
realmResultsPerson = realm.where(Person.class).equalTo("status", Const.STATUS_ACTIVE)
                .equalTo("onlineCheckStatus", Const.FIRM_CREATED_OFFLINE).findAll();
```

#### Version of Realm and tooling
Realm version(s): realm-android:0.82.1

Android Studio version: Android Studio 2.1

Which Android version and device: 4.4.2 , General Mobile

**Comment by Zhuinden** [comment]
In what lifecycle method do you open the realm? In what lifecycle method do you close the realm? Do you use the realm results in an adapter?

**Comment by berkayturanci** [comment]
Fragment lifecyle;

```

    private RealmResults<Person> realmResultsPerson;
    private RealmResults<Company> realmResultsCompany;
    private Realm realm;

    @Override
    public View onCreateView(LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {

		......

		realm = Realm.getDefaultInstance();
		realmResultsPerson = realm.where(Person.class).equalTo("status", Const.STATUS_ACTIVE)
					.equalTo("onlineCheckStatus", Const.FIRM_CREATED_OFFLINE).findAll();
		realmResultsCompany = realm.where(Company.class).equalTo("status", Const.STATUS_ACTIVE)
					.equalTo("onlineCheckStatus", Const.FIRM_CREATED_OFFLINE).findAll();

		gridViewPeople.setAdapter(new FirmAdapter(getActivity(), realmResultsPerson, true, Person.class, true));
		gridViewCompany.setAdapter(new FirmAdapter(getActivity(), realmResultsCompany, true, Company.class, true));
		
		initPage();
		return rootView;
	}


	@Override
    public void onDestroyView() {
        super.onDestroyView();
        realm.close();
    }

    @Override
    public void onResume() {
        super.onResume();

        realm = Realm.getDefaultInstance();
        realmResultsPerson = realm.where(Person.class).equalTo("status", Const.STATUS_ACTIVE)
                .equalTo("onlineCheckStatus", Const.FIRM_CREATED_OFFLINE).findAll();
        realmResultsCompany = realm.where(Company.class).equalTo("status", Const.STATUS_ACTIVE)
                .equalTo("onlineCheckStatus", Const.FIRM_CREATED_OFFLINE).findAll();

        if (realmResultsPerson.size() > 0) {
            txtViewEmptyPeople.setVisibility(View.GONE);
        } else {
            txtViewEmptyPeople.setVisibility(View.VISIBLE);
        }

        if (realmResultsCompany.size() > 0) {
            txtViewEmptyCompany.setVisibility(View.GONE);
        } else {
            txtViewEmptyCompany.setVisibility(View.VISIBLE);
        }

        ((FirmAdapter) gridViewPeople.getAdapter()).refreshList();
        ((FirmAdapter) gridViewCompany.getAdapter()).refreshList();
    }
```
Realm Adapter;

```
public class FirmAdapter<E extends RealmObject> extends RealmBaseAdapter<RealmObject> implements ListAdapter {
```

**Comment by Zhuinden** [comment]
You should not have `realm = Realm.getDefaultInstance()` in `onResume()`

**Comment by berkayturanci** [comment]
Is it really related with the exception that occurs on `onCreateView` not on `onReslme` ?

**Comment by Zhuinden** [comment]
I think so yes

**Comment by berkayturanci** [comment]
It seems strange to me, since `onCreateView` is called before `onResume` in fragment's lifecycle. So, exception occurs before even `onResume` method is called.

**Comment by beeender** [comment]
1. Is it something your can reproduce or just crash seen from the crash log server?
2. Do you use Realm dynamic API to change the Realm schema? If yes, how do you use them? Do you ever change Realm's schema when a typed Realm is opened?
3. Do you use Realm in multi-processes?
4. Do you have any logic to restart the app which means "quit the current activity" -> "send intent to start a new activity" -> "open realm in the new activity" ?

**Comment by berkayturanci** [comment]
Hi @beeender 

1- I cannot reproduce this error. I observe this from crash log server.
2- No, just sometimes migration (but done in start of the app)
3- Yes, example; after the web service call results. But this error happens in the beginning of the application running (first activity), so there is no web service calls at that moment.
4- No. I don't kill activities, they are stored on back stack. Moreover, this error happens in the first activity on the application.

My application flow; in first activity, I have tabLayout (4 item) and 4 fragments (1 for each).  I use FragmentStatePagerAdapter to attach them to my tablayout's viewpager. Each fragment has its own adapter which populates realm objects to list.

Error happens in the `onCreate `of the last (fourth) fragment, `ControlRequiredFirmsFragment`.

**Comment by beeender** [comment]
Hi @berkayturanci 

We don't support multi-process yet, although it might be working for most of times.
If you are using Realm in multi-processes, you need to be really careful. Especially there might be a race condition that migration is happening while the other process is still holding a opened instance of Realm which could trigger a problem like you described.

**Comment by berkayturanci** [comment]
Thanks @beeender
