### ISSUE TITLE
io.realm.internal.SharedGroup$Durability

### ISSUE THREAD

**Issue by MahmoudAlnouno** [realm/realm-java#2740]
>  Process: android.opex, PID: 14647
                                                              java.lang.NoClassDefFoundError: io.realm.internal.SharedGroup$Durability
                                                                  at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:266)
                                                                  at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:247)
                                                                  at android.opex.OpexApplication.onCreate(OpexApplication.java:21)

`  config = new RealmConfiguration.Builder(this).name("myApp.realm").build();`

when run in android Kit kat ?

`    compile 'io.realm:realm-android:0.84.1'
`

**Comment by beeender** [comment]
Are you using multi dex? Does it only happen on specific device?

**Comment by beeender** [comment]
@MahmoudAlnouno  Do you have more information on this issue?

**Comment by MahmoudAlnouno** [comment]
@beeender  I have resolved this problem ,, yes I'm using multi dex 
I added 
`-keep class android.opex.models.**
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**`

in proguard-rules.pro 
and this in Gradle
`  debug {
   minifyEnabled false
   proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
   }`

**Comment by MahmoudAlnouno** [comment]
@beeender  thank you
