### ISSUE TITLE
RealmObject with RxJava error

### ISSUE THREAD

**Issue by ramanbranavitski** [realm/realm-java#2742]
I am trying to use `RealmObject` on another thread using RxJava and I get the exception that `Realm object can only be accessed from the thread it was created`. Its fine, `RealmObject` attachs to the thread where it was created. But according to documentation method `Realm.copyFromRealm(RealmObject)` must create a full copy of the object and detach it from Realm. But I still receive this exception.

```
taskDetails = TaskDetailsManager.getInstance().getById(realm, id);
Observable<TaskDetails> taskDetailsObs = Observable.just(realm.copyFromRealm(taskDetails));
taskDetailsObs.subscribeOn(Schedulers.newThread()
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(task -> doSmth),
                        error ->showError));
```

**Comment by beeender** [comment]
Which thread created `mainThreadRealm` and which thread is calling `copyFromRealm`?

`copyFromRealm` needs to be called from the same thread which created `mainThreadRealm`.

**Comment by ramanbranavitski** [comment]
Refactor the code above. Yes, it's the same realm instance.

**Comment by beeender** [comment]
Can you post the whole stack trace here?

**Comment by ramanbranavitski** [comment]
Does `copyFromRealm()` method detach nested `RealmList` objects?

**Comment by beeender** [comment]
Yes, it does.

How deep your object could be? See https://realm.io/docs/java/latest/api/io/realm/Realm.html#copyFromRealm-E-int-

**Comment by ramanbranavitski** [comment]
I use `copyFromRealm(E realmObject)` that use `Integer.MAX_VALUE` as `maxDepth` parameter.

**Comment by beeender** [comment]
Would you please share the full stack trace and related definitions of you model classes?

**Comment by ramanbranavitski** [comment]
```
public class Task extends RealmObject {
    @PrimaryKey
    private long id;
    private RealmList<Question> questions;
}
```
```
public class Question extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private RealmList<Field> fields;
}
```
```
public class Field extends RealmObject {
    @PrimaryKey
    private long id;
    private long questionId;
    private boolean isVisible = true;
    private RealmList<Condition> conditions;
}
```

```
Caused by: java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
                                                                              at io.realm.BaseRealm.checkIfValid(BaseRealm.java:375)
                                                                              at io.realm.FormRealmProxy.realmGet$questions(FormRealmProxy.java:78)
                                                                              at packadgeNameTask.getQuestions(Task.java:29)
                                                                              rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:264)
                                                                              at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:335)
                                                                              at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:266)
                                                                              at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
                                                                              at rx.Observable.unsafeSubscribe(Observable.java:8741)
                                                                              at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:214)
                                                                              at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:156)
                                                                              at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:122)
                                                                              at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:266)
                                                                              at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:79)
                                                                              at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:75)
                                                                              at rx.Observable$2.call(Observable.java:233)
                                                                              at rx.Observable$2.call(Observable.java:225)
                                                                              at rx.Observable.unsafeSubscribe(Observable.java:8741)
                                                                              at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: rx.exceptions.OnErrorThrowable$OnNextValue:
```
