### ISSUE TITLE
Invalid format of Realm file.

### ISSUE THREAD

**Issue by yashthakerlearns** [realm/realm-java#2746]
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
                                                                               at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                                               at io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
                                                                               at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:47)
                                                                               at io.realm.BaseRealm.<init>(BaseRealm.java:76)
                                                                               at io.realm.Realm.<init>(Realm.java:126)
                                                                               at io.realm.Realm.createAndValidate(Realm.java:246)
                                                                               at io.realm.Realm.createInstance(Realm.java:231)
                                                                               at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
                                                                               at io.realm.Realm.getDefaultInstance(Realm.java:181)
                                                                               at com.example.yash.resourcify.BarChartSales.onCreate(BarChartSales.java:92)
                                                                               at android.app.Activity.performCreate(Activity.java:6092)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5624) 
                                                                               at java.lang.reflect.Method.invoke(Native Method)

Realm.io version:0.87.5
Android studio version:2.0
plz help

**Comment by beeender** [comment]
Hi, do you have more information about this issue? Is it possible for you to reproduce it?

**Comment by beeender** [comment]
@yashthakerlearns Do you have more details about the issue?

**Comment by yashthakerlearns** [comment]
I later found out that the new android version,has a feature that instead of uninstalling whole app,now just installs changes and restart patches. this seemed to have a problem with library. When I uninstalled my app and then installed it again and also clearing app data,it worked like a charm @beeender

**Comment by mihirjoshi21** [comment]
Is there a solution for this. I am receiving lots of crashes regarding this in the production build. http://crashes.to/s/305f76efbc2

**Comment by dinhthaidaica** [comment]
I have the same issue, my app get a lot of crash which reported from our user. I can not reproduce while develop. So could any one can help to re-open issue and give me a solution.
The log was :
`EXCEPTION java.lang.IllegalArgumentException
LOCATION SourceFile line -2 in SharedGroup.createNativeWithImplicitTransactions()
TIME Today, 6:54
MESSAGE Illegal Argument: Invalid format of Realm file.`

**Comment by mihirjoshi21** [comment]
+1. I am not been able to reproduce this issue. This is the link. http://crashes.to/s/305f76efbc2.
The total number of user who faced this issue are only 1% but still it is the most prominent bug in my application.
