### ISSUE TITLE
ArrayIndexOutOfBoundsException: rowIndex > available rows: 7 > 7

### ISSUE THREAD

**Issue by changxiangzhong** [realm/realm-java#2753]
- We are using version 0.88.3.

- The autoUpdate option for `RealmBaseAdapter` is turned on

- The exception is thrown while `RealmBaseAdapter::getItem()` is called in `ListAdapter::getView()`.

- The realm instance is opened & closed in `onCreate()` and `onDestroy()` respectively. 

- The data model change, which introduce this issue happens in one transaction.

My analysis is the `BaseAdapter::notifyDataSetChanged()` (defined in the `RealBaseAdapter` constructor) was not yet called, which leads to this OutOfIndex issue. Any suggestions?
Here's the code for model updating. Some of the properties classes don't have a primary key and we don't want to leave garbages so we clear everything and insert everything.

        realm.executeTransaction(new Realm.Transaction() {

            @Override
            public void execute(Realm realm) {
                for(Class temp: cascadeRemoval) {
                    realm.clear(temp);
                }
                realm.clear(type);
                realm.copyToRealmOrUpdate(items);

            }
        });

Here's the code for Adapter.

        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            ViewHolder holder;
            if (convertView == null) {
                convertView = LayoutInflater.from(parent.getContext()).inflate(R.layout.view_campaign_item, parent, false);
                holder = new ViewHolder();
                // Other viewholder setup...
                convertView.setTag(holder);
            } else {
                holder = (ViewHolder) convertView.getTag();
            }
            // Bind view model.
            bind(convertView.getContext(), holder, getItem(position)); // Exception thrown here!
            return convertView;
        }

Here's the full exception stack

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 7 > 7
       at io.realm.internal.TableView.nativeGetSourceRowIndex(TableView.java)
       at io.realm.internal.TableView.getSourceRowIndex(TableView.java:127)
       at io.realm.RealmResults.get(RealmResults.java:207)
       at io.realm.RealmBaseAdapter.getItem(RealmBaseAdapter.java:84)
       at no.hyper.campaign.ui.fragment.CampaignListFragment$CampaignListAdapter.getView(CampaignListFragment.java:224)
       at android.widget.AbsListView.obtainView(AbsListView.java:2929)
       at android.widget.ListView.makeAndAddView(ListView.java:1945)
       at android.widget.ListView.fillDown(ListView.java:719)
       at android.widget.ListView.fillGap(ListView.java:683)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:7293)
       at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:4391)
       at android.widget.AbsListView.startScrollIfNeeded(AbsListView.java:4319)
       at android.widget.AbsListView.onTouchMove(AbsListView.java:5755)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:5610)
       at android.view.View.dispatchTouchEvent(View.java:9993)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2828)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2499)
       at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5547)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
       at android.view.View.dispatchPointerEvent(View.java:10228)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5350)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5186)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4787)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4844)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7312)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7190)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7151)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7422)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7386)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7449)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:625)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by beeender** [comment]
Is it 100% reproducible? If it is, is it possible to share your project with us privately? To help@realm.io. thanks!

**Comment by changxiangzhong** [comment]
Thanks for your reply. Unfortunately (Fortunately?) It's not 100% reproducible. Our QAs have never ever managed to reproduce this. It only happens not very often in production environment.

**Comment by beeender** [comment]
@changxiangzhong Can you share the apk with us?

**Comment by changxiangzhong** [comment]
Oh sure.

**Comment by beeender** [comment]
@changxiangzhong #2408 has been reported before which should be the same issue. I will just dup this one to it and track it there. thanks!

**Comment by changxiangzhong** [comment]
Thank you.

**Comment by changxiangzhong** [comment]
@beeender Concerning the frequency of the issue: Here are the numbers:

We have around 400 active users everyday. During the past 30 days, we had 2 crash reports of this kind of issue.

**Comment by adnan-SM** [comment]
I seem to be having a similar problem. This has been reported as a crash around 11 times among 60k active users in a week's time. Stack trace for the same - 

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0
       at io.realm.internal.TableView.nativeGetSourceRowIndex(SourceFile)
       at io.realm.internal.TableView.getSourceRowIndex(SourceFile:128)
       at io.realm.RealmResults.get(SourceFile:206)
       at com.movie.bms.database.DeInitDataAccessObject.getSeatRangeDetails(SourceFile:132)
       at com.movie.bms.database.DatabaseManager.readSeatRangeDetails(SourceFile:151)
       at com.movie.bms.views.adapters.ShowTimeRecyclerViewAdapter.onBindViewHolder(SourceFile:123)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(SourceFile:5822)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:5855)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5091)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:4967)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(SourceFile:2029)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1414)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1377)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:578)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3315)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3124)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3568)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.support.v4.view.ViewPager.onLayout(SourceFile:1767)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2934)
       at android.view.View.layout(View.java:16639)
       at android.view.ViewGroup.layout(ViewGroup.java:5437)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:606)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

The issue seems to persist majorly on Android 6.0.

**Comment by Zhuinden** [comment]
@adnan-SM I think this is when scrolling occurs while the underlying data set is cleared.

**Comment by adnan-SM** [comment]
@Zhuinden Looks like you are right, that was the problem.

**Comment by Zhuinden** [comment]
@adnan-SM I have encountered this before but I did not find a fix, this is something that the `LinearLayoutManager` is supposed to handle but it doesn't. :slightly_frowning_face:
