### ISSUE TITLE
Unrecoverable Error: Bad Transaction Log

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#2798]
#### Goal

> What do you want to achieve?

Be notified of Realm update.

#### Expected Results

Not crash

#### Actual Results

Crash

>  E.g. full stack trace with exception

    io.realm.exceptions.RealmError: Unrecoverable error. Bad transaction log in io_realm_internal_SharedGroup.cpp line 157
	at io.realm.internal.SharedGroup.nativeAdvanceRead(Native Method)
	at io.realm.internal.SharedGroup.advanceRead(SharedGroup.java:83)
	at io.realm.internal.ImplicitTransaction.advanceRead(ImplicitTransaction.java:35)
	at io.realm.internal.SharedGroupManager.advanceRead(SharedGroupManager.java:76)
	at io.realm.HandlerController.realmChanged(HandlerController.java:377)
	at io.realm.HandlerController.handleMessage(HandlerController.java:110)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5317)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)

#### Steps & Code to Reproduce

Crash reporting tool picked up on it.

#### Code Sample

I do not know where it happened exactly.

#### Version of Realm and tooling
Realm version(s): ?

0.89.1

Android Studio version: ?

1.5.1

Which Android version and device: ?

GT-S7580
4.2.2

**Comment by Zhuinden** [comment]
Oh, it's the same as this one.

https://github.com/realm/realm-java/issues/2567

**Comment by Zhuinden** [comment]
Ah, interesting facts though:

1.) I do not use Async Queries

2.) I do not use Rx

3.) I do not use RealmResults change listeners, only Realm listener

**Comment by beeender** [comment]
We got a core update in `v0.90.1` inlcuding fix of

> Opening a Realm while closing a Realm in another thread could lead to a race condition.

which is a potential fix of this issue.

I will just close and dup this issue to #2567 and monitor that one for a little while. If it is possible, please update the Realm and see if it still happens.
