### ISSUE TITLE
Compiler Error : com.sun.tools.javac.code.Symbol$CompletionFailure: class file for rx.Observable not found

### ISSUE THREAD

**Issue by paragones** [realm/realm-java#2810]
**Bugs** Not exactly sure if this is  a bug. But I think this might be.. 

I was just making a basic realm file using the latest REALM version but the compiler throws this error:

    An exception has occurred in the compiler (1.8.0). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
    com.sun.tools.javac.code.Symbol$CompletionFailure: class file for rx.Observable not found

The app I made is still relatively **small and it works on Realm ver 0.82.0 I still don't know what has caused this problem.** I wanted to use the latest version but this error is blocking it. Do you have any ideas on how to work on this?

This is the compiler error stacktrace :

    Executing tasks: [:app:assembleDebug]
    
    Configuration on demand is an incubating feature.
    Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location 'C:\Users\Paul.Aragones\AppData\Local\Android\sdk\add-ons\addon-google_apis-google-19-1' (Expected 'C:\Users\Paul.Aragones\AppData\Local\Android\sdk\add-ons\addon-google_apis-google-19')
    Incremental java compilation is an incubating feature.
    :app:preBuild UP-TO-DATE
    :app:preDebugBuild UP-TO-DATE
    :app:checkDebugManifest
    :app:preReleaseBuild UP-TO-DATE
    :app:prepareComAndroidSupportAnimatedVectorDrawable2400Alpha2Library UP-TO-DATE
    :app:prepareComAndroidSupportAppcompatV72400Alpha2Library UP-TO-DATE
    :app:prepareComAndroidSupportCardviewV72400Alpha2Library UP-TO-DATE
    :app:prepareComAndroidSupportDesign2400Alpha2Library UP-TO-DATE
    :app:prepareComAndroidSupportMediarouterV72300Library UP-TO-DATE
    :app:prepareComAndroidSupportMultidex101Library UP-TO-DATE
    :app:prepareComAndroidSupportRecyclerviewV72400Alpha2Library UP-TO-DATE
    :app:prepareComAndroidSupportSupportV42400Alpha2Library UP-TO-DATE
    :app:prepareComAndroidSupportSupportVectorDrawable2400Alpha2Library UP-TO-DATE
    :app:prepareComGetkeepsafeRelinkerRelinker121Library UP-TO-DATE
    :app:prepareComGithubRey5137Material122Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServices840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesAds840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesAnalytics840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesAppindexing840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesAppinvite840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesAppstate840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesAuth840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesCast840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesDrive840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesFitness840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesGames840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesIdentity840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesLocation840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesNearby840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesPanorama840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesPlus840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesSafetynet840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesVision840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesWallet840Library UP-TO-DATE
    :app:prepareComGoogleAndroidGmsPlayServicesWearable840Library UP-TO-DATE
    :app:prepareDeHdodenhofCircleimageview130Library UP-TO-DATE
    :app:prepareIoRealmRealmAndroidLibrary0901Library UP-TO-DATE
    :app:prepareNetDanlewAndroidJoda292Library UP-TO-DATE
    :app:prepareDebugDependencies
    :app:compileDebugAidl UP-TO-DATE
    :app:compileDebugRenderscript UP-TO-DATE
    :app:generateDebugBuildConfig UP-TO-DATE
    :app:mergeDebugShaders UP-TO-DATE
    :app:compileDebugShaders UP-TO-DATE
    :app:generateDebugAssets UP-TO-DATE
    :app:mergeDebugAssets UP-TO-DATE
    :app:generateDebugResValues UP-TO-DATE
    :app:processDebugGoogleServices
    :app:generateDebugResources
    :app:mergeDebugResources UP-TO-DATE
    :app:processDebugManifest UP-TO-DATE
    :app:processDebugResources UP-TO-DATE
    :app:generateDebugSources UP-TO-DATE
    :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
    :app:compileDebugJavaWithJavac
    Note: Processing class LeaveApplication
    Note: Creating DefaultRealmModule
    An exception has occurred in the compiler (1.8.0). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
    com.sun.tools.javac.code.Symbol$CompletionFailure: class file for rx.Observable not found
    
     FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.
    
    * Try:
    Run with --info or --debug option to get more log output.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
    	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
    	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
    	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
    	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
    	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
    	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
    	at org.gradle.internal.Factories$1.create(Factories.java:22)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
    	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
    	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:47)
    	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
    	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
    	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
    	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
    	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
    	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
    	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
    	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
    	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
    	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
    	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
    	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    	... 70 more
    
    
    BUILD FAILED
    
    Total time: 3.357 secs

I made this LeaveApplication.class 

    package com.pointwest.timetracker.leaves.Models;
    
    import io.realm.RealmObject;
    
    public class LeaveApplication extends RealmObject {
    
        private int chosenLeave;
        private int chosenReason;
        private boolean isHalfDay;
        private String comment;
        private String contactNumber;
    
        public int getChosenLeave() {
            return chosenLeave;
        }
    
        public void setChosenLeave(int chosenLeave) {
            this.chosenLeave = chosenLeave;
        }
    
        public int getChosenReason() {
            return chosenReason;
        }
    
        public void setChosenReason(int chosenReason) {
            this.chosenReason = chosenReason;
        }
    
        public boolean isHalfDay() {
            return isHalfDay;
        }
    
        public void setIsHalfDay(boolean isHalfDay) {
            this.isHalfDay = isHalfDay;
        }
    
        public String getComment() {
            return comment;
        }
    
        public void setComment(String comment) {
            this.comment = comment;
        }
    
        public String getContactNumber() {
            return contactNumber;
        }
    
        public void setContactNumber(String contactNumber) {
            this.contactNumber = contactNumber;
        }
    }

Build.gradle app level: 

    apply plugin: 'com.android.application'
    apply plugin: 'realm-android'
    
    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.2"
    
        defaultConfig {
            applicationId "com.pointwest.timetracker.leaves"
            minSdkVersion 15
            targetSdkVersion 23
            versionCode 1
            versionName "1.0"
            multiDexEnabled true
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }
    
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
    }
    
    dependencies {
        //Updated dependencies to support Andriod lower than Lollipop
        compile 'com.android.support:appcompat-v7:24.0.0-alpha2'
        compile 'com.android.support:design:24.0.0-alpha2'
        compile 'com.android.support:cardview-v7:24.0.0-alpha2'
        compile 'com.android.support:support-v4:24.0.0-alpha2'
    
        // Google Play
        compile 'com.google.android.gms:play-services:8.4.0'
    
        compile 'com.github.bumptech.glide:glide:3.6.0'
        compile 'de.hdodenhof:circleimageview:1.3.0'
    
        // Material Designs
        compile 'com.github.rey5137:material:1.2.2'
    
        //Multidex Support
        compile 'com.android.support:multidex:1.0.1'
    
        //Joda Time
        compile 'net.danlew:android.joda:2.9.2'
    
        //EventBus
        compile 'org.greenrobot:eventbus:3.0.0'
    
        //Realm for now
    //    compile 'io.realm:realm-android:0.82.0'
    }
    
    apply plugin: 'com.google.gms.google-services'

Build.gradle project level 

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.1.0'
            classpath 'com.google.gms:google-services:2.0.0-alpha6'
            classpath "io.realm:realm-gradle-plugin:0.90.1"
        }
    }
    
    allprojects {
        repositories {
            jcenter()
        }
    }

gradle.properties

    # Project-wide Gradle settings.
    
    # IDE (e.g. Android Studio) users:
    # Gradle settings configured through the IDE *will override*
    # any settings specified in this file.
    
    # For more details on how to configure your build environment visit
    # http://www.gradle.org/docs/current/userguide/build_environment.html
    
    # Specifies the JVM arguments used for the daemon process.
    # The setting is particularly useful for tweaking memory settings.
    # Default value: -Xmx10248m -XX:MaxPermSize=256m
     org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
    
    # When configured, Gradle will run in incubating parallel mode.
    # This option should only be used with decoupled projects. More details, visit
    # http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
    # org.gradle.parallel=true

AndroidManifest.xml

    <?xml version="1.0" encoding="utf-8"?>
    
    
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.pointwest.timetracker.leaves">
    
        <uses-permission android:name="android.permission.INTERNET" />
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    
        <application
            android:name="android.support.multidex.MultiDexApplication"
            android:allowBackup="true"
            android:icon="@mipmap/ic_launcher"
            android:label="@string/app_name"
            android:theme="@style/Theme.DesignDemo">
    
            <activity android:name=".Activity.SignInActivity">
                <intent-filter>
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.DEFAULT" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
    
            <activity
                android:name=".Activity.MainActivity"
                android:configChanges="orientation|keyboardHidden"
                android:screenOrientation="portrait"
                android:windowSoftInputMode="stateHidden"
                android:parentActivityName=".Activity.SignInActivity" >
                <meta-data
                    android:name="android.support.PARENT_ACTIVITY"
                    android:value=".Activity.SignInActivity" />
            </activity>
    
            <service
                android:name=".Service.ConnectivityOutsideAppService"
                android:exported="false"/>
    
            <receiver android:name=".Utilities.ConnectivityOutsideAppReceiver"
                android:enabled="true"
                android:process=":remote">
    
                <intent-filter android:priority="1000" >
                    <action android:name="android.net.conn.CONNECTIVITY_CHANGE"/>
                </intent-filter>
            </receiver>
    
        </application>
    
    </manifest>

#### Version of Realm and tooling
Realm version(s): lastest 0.90.0

Android Studio version: 1.3.2

Which Android version and device: Any

**Comment by Zhuinden** [comment]
I think you are running into this problem:

https://realm.io/docs/java/latest/#jackson-databind

**Comment by zaki50** [comment]
Hi @paragones

Please try to add empty `Observable` class as described in https://realm.io/docs/java/latest/#jackson-databind

**Comment by paragones** [comment]
Jackson workaround seemed to have solved this issue. Thanks!
