### ISSUE TITLE
@RealmClass is required to process RealmObject correctly.

### ISSUE THREAD

**Issue by YoungjaeKim** [realm/realm-java#2822]
# Bugs

I got weird problem and now can reproduce issue.
**SomeModel is not part of the schema for this Realm** error was occurred so randomly during development, and finally found the cause. I say random as it works little time, but don't know why it did as such. Anyway, I can reproduce it in on/off manner.

Despite the https://github.com/realm/realm-java/issues/1283#issuecomment-120329940 says `@RealmClass` is not required, but for me it should be.

The gradle results also show that `Note: Processing class ModelSomething` red colored log does not appeared when the annotation is _not_ attached. It _seems_ that annotator forces to process model.

I recommend you to test with two or more models. When I created two models, only one model or nothing shows processed in log.
# stacktrace

```
05-17 11:14:17.600 8532-8532/net.xxx I/CrashlyticsCore: Initializing Crashlytics 2.3.8.97
05-17 11:14:17.638 8532-8532/net.xxx I/GAv4: Google Analytics 8.4.87 is starting up. To enable debug logging on a device run:
                                                          adb shell setprop log.tag.GAv4 DEBUG
                                                          adb logcat -s GAv4
05-17 11:14:17.719 8532-8532/net.xxx D/barovoca: updated version: 3, current version: 3
05-17 11:14:17.870 8532-8532/net.xxx D/ContextHelper: convertTheme. context->name=net.xxx themeResourceId=2131427387
05-17 11:14:17.920 8532-8583/net.xxx D/libc-netbsd: [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
05-17 11:14:17.920 8532-8583/net.xxx D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
05-17 11:14:17.921 8532-8583/net.xxx D/libc-netbsd: [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
05-17 11:14:17.921 8532-8583/net.xxx D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=1024; ai_family=0
05-17 11:14:17.964 8532-8532/net.xxx D/ContextHelper: convertTheme. context->name=net.xxx themeResourceId=2131427387
05-17 11:14:17.993 8532-8583/net.xxx I/System.out: propertyValue:false
05-17 11:14:18.031 8532-8532/net.xxx I/PhoneWindow: [generateLayout] setColorNavigationBar => color=0x ff000001
05-17 11:14:18.037 8532-8532/net.xxx D/PhoneWindowEx: [PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
05-17 11:14:18.037 8532-8532/net.xxx I/PhoneWindow: [setNavigationBarColor2] color=0x ff000000
05-17 11:14:18.081 8532-8532/net.xxx W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-17 11:14:18.104 8532-8626/net.xxx D/OpenGLRenderer: Render dirty regions requested: true
05-17 11:14:18.106 8532-8626/net.xxx I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
                                                              OpenGL ES Shader Compiler Version: E031.25.03.00
                                                              Build Date: 12/12/14 금
                                                              Local Branch: LA.BF.1.1_RB1.05.00.00.002.031_20141212_01821442
                                                              Remote Branch: 
                                                              Local Patches: 
                                                              Reconstruct Branch: 
05-17 11:14:18.106 8532-8626/net.xxx I/OpenGLRenderer: Initialized EGL, version 1.4
05-17 11:14:18.123 8532-8626/net.xxx D/OpenGLRenderer: Enabling debug mode 0
05-17 11:14:18.130 8532-8532/net.xxx D/Atlas: Validating map...
05-17 11:14:18.149 8532-8532/net.xxx D/barovoca: reset notification
05-17 11:14:18.720 8532-8532/net.xxx I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@31997f45 time:63397910
05-17 11:14:20.095 8532-8532/net.xxx I/Timeline: Timeline: Activity_launch_request id:net.xxx time:63399285
05-17 11:14:20.333 8532-8532/net.xxx D/ContextHelper: convertTheme. context->name=net.xxx themeResourceId=2131427474
05-17 11:14:20.335 8532-8532/net.xxx D/ContextHelper: convertTheme. context->name=net.xxx themeResourceId=2131427474
05-17 11:14:20.338 8532-8532/net.xxx I/PhoneWindow: [generateLayout] setColorNavigationBar => color=0x ff000001
05-17 11:14:20.339 8532-8532/net.xxx D/PhoneWindowEx: [PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
05-17 11:14:20.339 8532-8532/net.xxx I/PhoneWindow: [setNavigationBarColor2] color=0x ff000000
05-17 11:14:20.809 8532-8532/net.xxx W/FragmentManager: moveToState: Fragment state for MemorizedVocabularyListFragment{3652107f #0 id=0x7f10007a android:switcher:2131755130:1} not updated inline; expected state 3 found 2
05-17 11:14:20.838 8532-8532/net.xxx D/AndroidRuntime: Shutting down VM
05-17 11:14:20.854 8532-8593/net.xxx I/Configs: The framework log level is 1.
05-17 11:14:24.842 8532-8532/net.xxx E/CrashlyticsCore: Failed to execute task.
                                                                   java.util.concurrent.TimeoutException
                                                                       at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                                       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
                                                                       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)


                                                                   --------- beginning of crash
05-17 11:14:24.843 8532-8532/net.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: net.xxx, PID: 8532
                                                                  io.realm.exceptions.RealmException: class net.xxx.dictionary.Vocabulary is not part of the schema for this Realm.
                                                                      at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:174)
                                                                      at io.realm.DefaultRealmModuleMediator.getTableName(DefaultRealmModuleMediator.java:54)
                                                                      at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:235)
                                                                      at io.realm.RealmQuery.<init>(RealmQuery.java:136)
                                                                      at io.realm.RealmQuery.createQuery(RealmQuery.java:85)
                                                                      at io.realm.Realm.where(Realm.java:953)
                                                                      at net.xxx.dictionary.VocabularyManager.results(VocabularyManager.kt:65)
                                                                      at net.xxx.dictionary.VocabularyManager.list(VocabularyManager.kt:53)
                                                                      at net.xxx.fragment.VocabularyListFragment.refresh(VocabularyListFragment.kt:124)
                                                                      at net.xxx.fragment.VocabularyListFragment.onResume(VocabularyListFragment.kt:89)
                                                                      at android.support.v4.app.Fragment.performResume(Fragment.java:2020)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                      at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
                                                                      at android.view.View.measure(View.java:17487)
                                                                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
                                                                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1400)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                    at android.os.Handler.h

```
# gradle

``` gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.0.1-2'
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.fabric.tools:gradle:1.21.2'
        classpath "io.realm:realm-gradle-plugin:0.90.1"
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "net.xx"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 5
        versionName "1.1.1.debug"
        multiDexEnabled = true

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }
    lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }
    signingConfigs {
        release {
            storeFile file('bapul.keystore')
            storePassword 'bapul0904'
            keyAlias 'bapul'
            keyPassword 'bapul0904'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'LICENSE.txt'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'], exclude: 'android-support-v4.jar')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:multidex:1.0.1'
    compile ('com.android.support:support-v4:23.2.1'){
        force = true;
    }
    compile ('com.android.support:appcompat-v7:23.2.1'){
        force = true;
    }
    compile ('com.android.support:design:23.2.1'){
        force = true;
    }
    compile ('com.android.support:cardview-v7:23.2.1'){
        force = true;
    }
    compile ('com.android.support:recyclerview-v7:23.2.1'){
        force = true;
    }


    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }

    compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.0-RC1'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'

    // anko
    compile 'org.jetbrains.anko:anko-sdk15:0.8.2' // sdk19, sdk21, sdk23 are also available
    compile 'org.jetbrains.anko:anko-support-v4:0.8.2' // In case you need support-v4 bindings
    compile 'org.jetbrains.anko:anko-appcompat-v7:0.8.2' // For appcompat-v7 bindings

    kapt "io.realm:realm-annotations:0.90.1"
    kapt "io.realm:realm-annotations-processor:0.90.1"

    compile 'de.greenrobot:eventbus:2.4.0'

    compile "com.daimajia.swipelayout:library:1.2.0@aar"
    compile 'com.gordonwong:material-sheet-fab:1.2.1'

    compile 'it.sephiroth.android.library.targettooltip:target-tooltip-library:1.3.11'
    compile 'com.rmtheis:tess-two:5.4.0'
    compile('com.github.afollestad.material-dialogs:core:0.8.5.3@aar') {
        transitive = true
    }

    compile 'com.nobrain.android.permissions:library:1.1.0'
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
# model

``` java
package net.dictionary;

import java.util.Date;
import io.realm.RealmObject;

// @RealmClass // <- THIS MAKES DIFFERENCE in gradle processing.
public class Vocabulary extends RealmObject {
    private DictionaryWord word = null;
    private Boolean memorized = false;
    private Date created = new Date();

    public DictionaryWord getWord() {
        return word;
    }

    public void setWord(DictionaryWord word) {
        this.word = word;
    }

    public Boolean getMemorized() {
        return memorized;
    }

    public void setMemorized(Boolean memorized) {
        this.memorized = memorized;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }
}

```
#### Version of Realm and tooling

Realm version(s): ? 
0.87.1 and 0.90.1 with Kotlin 1.0.0 and 1.0.1-2
Four combinations make same issue.

Android Studio version: ?
2.1.1 JRE 1.8 64bit under Windows 10 64bit.

Which Android version and device: ?
5.0.1, LG G2 and 6.0.1 Nexus 5.

**Comment by emanuelez** [comment]
At a first glance this looks like a problem with the Kotlin annotation processor not respecting the [`@Inherited`](https://github.com/realm/realm-java/blob/master/realm-annotations/src/main/java/io/realm/annotations/RealmClass.java#L28) annotation.

Scouting the net a bit I found this blog post that seems to confirm my theory: http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/

So, it looks like right now the `@RealmClass` annotation is the only workaround for this Kotlin limitation.

**Comment by kneth** [comment]
@emanuelez Should we add a comment about the workaround in the documentation?

**Comment by cmelchior** [comment]
Our example doesn't use the `@RealmClass` annotation and it works fine. Not saying there isn't a problem, but it might be more subtle. Having it mentioned in the docs that this might be needed is probably a good idea until we can figure out what exactly is wrong.

**Comment by kneth** [comment]
We have added a Kotlin section to the documentation and this issue is mentioned. I move it to P2 so we don't forget about it.

**Comment by YoungjaeKim** [comment]
@kneth  thanks for your consideration.

**Comment by cmelchior** [comment]
Closing this as fixing this is outside our control and we have documented that it might be required anyway due to bugs on certain versions of Kotlin/Kapt
