### ISSUE TITLE
Deleting from realm throws exception.

### ISSUE THREAD

**Issue by VishnuTB** [realm/realm-java#2882]
#### Goal

> Delete a element(row)

#### Expected Results

> item should be deleted

#### Actual Results

> java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

Realm realm = Realm.getInstance(new RealmConfiguration.Builder(context).build());
            final RealmResults<Alarm> realmResults = realm.where(Alarm.class).equalTo("mAlarmId", alarmId).findAll();
            if (realmResults.size() == 1) {
                realm.beginTransaction();
                realmResults.get(0).deleteFromRealm();
                realm.commitTransaction();
             }

```

#### Version of Realm and tooling
Realm version(s): realm-gradle-plugin:1.0.0

Android Studio version: 2.1.1

Which Android version and device: API 16+

**Comment by VishnuTB** [comment]
a bit of misunderstanding with the adapter
