### ISSUE TITLE
Proguard doesn´t work with newest version

### ISSUE THREAD

**Issue by FabianTerhorst** [realm/realm-java#2906]
> What do you want to achieve?

project to build with minifyEnabled true

#### Actual Results

```
Note: the configuration keeps the entry point 'io.realm.internal.CheckedRow { void nativeSetMixed(long,long,io.realm.internal.Mixed); }', but not the descriptor class 'io.realm.internal.Mixed'
```

and when ignoring the warning:
```
rx.b.j: Please provide a constructor that takes a model as an argument
                                                                              at rx.d.d.c.a(Unknown Source)
                                                                              at rx.d.d.c.a(Unknown Source)
                                                                              at rx.d.d.a.a(Unknown Source)
                                                                              at rx.f.a.b(Unknown Source)
                                                                              at rx.f.a.a(Unknown Source)
                                                                              at rx.b.f.a(Unknown Source)
                                                                              at rx.f.a.a(Unknown Source)
                                                                              at rx.f.b.a(Unknown Source)
                                                                              at rx.f.d.a(Unknown Source)
                                                                              at rx.d.a.ah$1.a(Unknown Source)
                                                                              at io.realm.a.a$3$1.a(Unknown Source)
                                                                              at io.realm.a.a$3$1.a(Unknown Source)
                                                                              at io.realm.bl.a(Unknown Source)
                                                                              at io.realm.bl.e(Unknown Source)
                                                                              at io.realm.z.a(Unknown Source)
                                                                              at io.realm.z.handleMessage(Unknown Source)
```
#### Steps & Code to Reproduce

I have added the classpath 'io.realm:realm-gradle-plugin:1.1.0-SNAPSHOT' and applied the plugin.

#### Code Sample

```java

proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
minifyEnabled true

```

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.2

**Comment by FabianTerhorst** [comment]
here is the readable log:

```
rx.exceptions.OnErrorNotImplementedException: Please provide a constructor that takes a model as an argument
                                                       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.a(Unknown Source)
                                                       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.a(Unknown Source)
                                                       at rx.internal.util.ActionSubscriber.a(Unknown Source)
                                                       at rx.observers.SafeSubscriber.b(Unknown Source)
                                                       at rx.observers.SafeSubscriber.a(Unknown Source)
                                                       at rx.exceptions.Exceptions.a(Unknown Source)
                                                       at rx.observers.SafeSubscriber.a_(Unknown Source)
                                                       at rx.observers.SerializedObserver.a_(Unknown Source)
                                                       at rx.observers.SerializedSubscriber.a_(Unknown Source)
                                                       at rx.internal.operators.OperatorTakeUntil$1.a_(Unknown Source)
                                                       at io.realm.rx.RealmObservableFactory$5$1.a(Unknown Source)
                                                       at io.realm.rx.RealmObservableFactory$5$1.a(Unknown Source)
                                                       at io.realm.RealmResults.a(Unknown Source)
                                                       at io.realm.RealmResults.e(Unknown Source)
                                                       at io.realm.HandlerController.a(Unknown Source)
                                                       at io.realm.HandlerController.handleMessage(Unknown Source)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:525)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.RuntimeException: Please provide a constructor that takes a model as an argument
                                                       at com.b.a.a.c.a(Unknown Source)
                                                       at com.b.a.a.b.a(Unknown Source)
                                                       at com.b.a.a.b.b(Unknown Source)
                                                       at com.b.a.a.b.a(Unknown Source)
                                                       at com.b.a.a.a.a(Unknown Source)
                                                       at rx.internal.util.ActionSubscriber.a_(Unknown Source)
                                                       at rx.observers.SafeSubscriber.a_(Unknown Source) 
                                                       at rx.observers.SerializedObserver.a_(Unknown Source) 
                                                       at rx.observers.SerializedSubscriber.a_(Unknown Source) 
                                                       at rx.internal.operators.OperatorTakeUntil$1.a_(Unknown Source) 
                                                       at io.realm.rx.RealmObservableFactory$5$1.a(Unknown Source) 
                                                       at io.realm.rx.RealmObservableFactory$5$1.a(Unknown Source) 
                                                       at io.realm.RealmResults.a(Unknown Source) 
                                                       at io.realm.RealmResults.e(Unknown Source) 
                                                       at io.realm.HandlerController.a(Unknown Source) 
                                                       at io.realm.HandlerController.handleMessage(Unknown Source) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5103)
```
