### ISSUE TITLE
error while trying to get realmList from json Array

### ISSUE THREAD

**Issue by pankajnimgade** [realm/realm-java#2913]
I am not able to get RealmList for an Object which I am trying to populate from the JSON array. I am getting following error. I know what I am doing is wrong and should not be trying to save the response itself in the realm database. but what I would like to inquire is that why I am not able to use `RealmList`  in this case

```
{
  "success": true,
  "data": [
    {
      "id": 1,
      "username": "test1",
      "email": "test1@test.com",
      "password_hash": "$2y$10$ZUnXuiGI0wgegP8NtBZCXuLZSznrOqSNfxrIYjj4/45iC5iJa5SXG",
      "auth_key": "iXrbxQgtf5k2is7lvz0X3HZoFH3c2Ozg",
      "confirmed_at": null,
      "unconfirmed_email": null,
      "blocked_at": null,
      "registration_ip": "::1",
      "created_at": 1463711098,
      "updated_at": 1463711099,
      "flags": 0,
      "rabbitmq_exchange_name": "chat.message.exchange",
      "rabbitmq_queue_name": "chat.message.user.1",
      "rabbitmq_routing_key": "chat.message.user.1"
    },
    {
      "id": 2,
      "username": "test2",
      "email": "test2@test.com",
      "password_hash": "$2y$10$09UCjf0N.dxphlo.7pFoN.A8Vs/g4D.wYu0zONYkiy4iLZ5ZrIvs6",
      "auth_key": "frCdN9ShN7C_ogcHThypyRPplJLbnd46",
      "confirmed_at": null,
      "unconfirmed_email": null,
      "blocked_at": null,
      "registration_ip": "::1",
      "created_at": 1463711241,
      "updated_at": 1463711242,
      "flags": 0,
      "rabbitmq_exchange_name": "chat.message.exchange",
      "rabbitmq_queue_name": "chat.message.user.2",
      "rabbitmq_routing_key": "chat.message.user.2"
    },
    {
      "id": 3,
      "username": "pankaj",
      "email": "pankaj@test.com",
      "password_hash": "$2y$10$mDlqF5eGUT.tis/CeKqFj.ha.OAwlAdw79Ia72l0Y4UNSkH0zDyOW",
      "auth_key": "gv7DQqToNxWYgS3GnXU8N9PCXbSxhTR3",
      "confirmed_at": null,
      "unconfirmed_email": null,
      "blocked_at": null,
      "registration_ip": "223.225.226.1",
      "created_at": 1464518706,
      "updated_at": 1464518709,
      "flags": 0,
      "rabbitmq_exchange_name": "chat.message.exchange",
      "rabbitmq_queue_name": "chat.message.user.3",
      "rabbitmq_routing_key": "chat.message.user.3"
    },
    {
      "id": 4,
      "username": "mahabir",
      "email": "mahabir@test.com",
      "password_hash": "$2y$10$vCm4wTmtYvkc0ZbPuawjMuS/q8a9proOheJo4oNQb70h5C3YhK9Uq",
      "auth_key": "odFDUnZLBMOm71CCjP5PSRq6oEAF0fgx",
      "confirmed_at": null,
      "unconfirmed_email": null,
      "blocked_at": null,
      "registration_ip": "223.225.226.1",
      "created_at": 1464518813,
      "updated_at": 1464518814,
      "flags": 0,
      "rabbitmq_exchange_name": "chat.message.exchange",
      "rabbitmq_queue_name": "chat.message.user.4",
      "rabbitmq_routing_key": "chat.message.user.4"
    }
  ]
}
```

```
06-01 01:15:49.243 7395-7419/pk.nimgade.mycredentials E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                        io.realm.exceptions.RealmException: Could not create JSON array from string
                                                                            at io.realm.Realm.createAllFromJson(Realm.java:386)
                                                                            at pk.nimgade.mycredentials.MainActivity$2.onResponse(MainActivity.java:65)
                                                                            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:150)
                                                                            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                            at java.lang.Thread.run(Thread.java:856)
                                                                         Caused by: org.json.JSONException: Value {"data":[{"flags":0,"rabbitmq_routing_key":"chat.message.user.1","password_hash":"$2y$10$ZUnXuiGI0wgegP8NtBZCXuLZSznrOqSNfxrIYjj4\/45iC5iJa5SXG","rabbitmq_queue_name":"chat.message.user.1","registration_ip":"::1","auth_key":"iXrbxQgtf5k2is7lvz0X3HZoFH3c2Ozg","confirmed_at":null,"id":1,"username":"test1","updated_at":1463711099,"blocked_at":null,"email":"test1@test.com","rabbitmq_exchange_name":"chat.message.exchange","created_at":1463711098,"unconfirmed_email":null},{"flags":0,"rabbitmq_routing_key":"chat.message.user.2","password_hash":"$2y$10$09UCjf0N.dxphlo.7pFoN.A8Vs\/g4D.wYu0zONYkiy4iLZ5ZrIvs6","rabbitmq_queue_name":"chat.message.user.2","registration_ip":"::1","auth_key":"frCdN9ShN7C_ogcHThypyRPplJLbnd46","confirmed_at":null,"id":2,"username":"test2","updated_at":1463711242,"blocked_at":null,"email":"test2@test.com","rabbitmq_exchange_name":"chat.message.exchange","created_at":1463711241,"unconfirmed_email":null},{"flags":0,"rabbitmq_routing_key":"chat.message.user.3","password_hash":"$2y$10$mDlqF5eGUT.tis\/CeKqFj.ha.OAwlAdw79Ia72l0Y4UNSkH0zDyOW","rabbitmq_queue_name":"chat.message.user.3","registration_ip":"223.225.226.1","auth_key":"gv7DQqToNxWYgS3GnXU8N9PCXbSxhTR3","confirmed_at":null,"id":3,"username":"pankaj","updated_at":1464518709,"blocked_at":null,"email":"pankaj@test.com","rabbitmq_exchange_name":"chat.message.exchange","created_at":1464518706,"unconfirmed_email":null},{"flags":0,"rabbitmq_routing_key":"chat.message.user.4","password_hash":"$2y$10$vCm4wTmtYvkc0ZbPuawjMuS\/q8a9proOheJo4oNQb70h5C3YhK9Uq","rabbitmq_queue_name":"chat.message.user.4","registration_ip":"223.225.226.1","auth_key":"odFDUnZLBMOm71CCjP5PSRq6oEAF0fgx","confirmed_at":null,"id":4,"username":"mahabir","updated_at":1464518814,"blocked_at":null,"email":"mahabir@test.com","rabbitmq_exchange_name":"chat.message.exchange","created_at":1464518813,"unconfirmed_email":null}],"success":true} of type org.json.JSONObject cannot be converted to JSONArray
                                                                            at org.json.JSON.typeMismatch(JSON.java:111)
                                                                            at org.json.JSONArray.<init>(JSONArray.java:91)
                                                                            at org.json.JSONArray.<init>(JSONArray.java:103)
                                                                            at io.realm.Realm.createAllFromJson(Realm.java:384)
                                                                            at pk.nimgade.mycredentials.MainActivity$2.onResponse(MainActivity.java:65) 
                                                                            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:150) 
                                                                            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                            at java.lang.Thread.run(Thread.java:856) 

I have a Response class 
```

public class MyResponse extends RealmObject {

    private boolean success;

    private RealmList<Data> data;

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public RealmList<Data> getData() {
        return data;
    }

    public void setData(RealmList<Data> data) {
        this.data = data;
    }
}

and Data.java
```

public class Data extends RealmObject{

    private int id;
    private String username;
    private String email;
    private String password_hash;
    private String auth_key;
    private String confirmed_at;
    private String unconfirmed_email;
    private String blocked_at;
    private String registration_ip;
    private int created_at;
    private int updated_at;
    private int flags;
    private String rabbitmq_exchange_name;
    private String rabbitmq_queue_name;
    private String rabbitmq_routing_key;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword_hash() {
        return password_hash;
    }

    public void setPassword_hash(String password_hash) {
        this.password_hash = password_hash;
    }

    public String getAuth_key() {
        return auth_key;
    }

    public void setAuth_key(String auth_key) {
        this.auth_key = auth_key;
    }

    public String getConfirmed_at() {
        return confirmed_at;
    }

    public void setConfirmed_at(String confirmed_at) {
        this.confirmed_at = confirmed_at;
    }

    public String getUnconfirmed_email() {
        return unconfirmed_email;
    }

    public void setUnconfirmed_email(String unconfirmed_email) {
        this.unconfirmed_email = unconfirmed_email;
    }

    public String getBlocked_at() {
        return blocked_at;
    }

    public void setBlocked_at(String blocked_at) {
        this.blocked_at = blocked_at;
    }

    public String getRegistration_ip() {
        return registration_ip;
    }

    public void setRegistration_ip(String registration_ip) {
        this.registration_ip = registration_ip;
    }

    public int getCreated_at() {
        return created_at;
    }

    public void setCreated_at(int created_at) {
        this.created_at = created_at;
    }

    public int getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(int updated_at) {
        this.updated_at = updated_at;
    }

    public int getFlags() {
        return flags;
    }

    public void setFlags(int flags) {
        this.flags = flags;
    }

    public String getRabbitmq_exchange_name() {
        return rabbitmq_exchange_name;
    }

    public void setRabbitmq_exchange_name(String rabbitmq_exchange_name) {
        this.rabbitmq_exchange_name = rabbitmq_exchange_name;
    }

    public String getRabbitmq_queue_name() {
        return rabbitmq_queue_name;
    }

    public void setRabbitmq_queue_name(String rabbitmq_queue_name) {
        this.rabbitmq_queue_name = rabbitmq_queue_name;
    }

    public String getRabbitmq_routing_key() {
        return rabbitmq_routing_key;
    }

    public void setRabbitmq_routing_key(String rabbitmq_routing_key) {
        this.rabbitmq_routing_key = rabbitmq_routing_key;
    }
}
```
```
```

**Comment by cmelchior** [comment]
How are you calling the `createAllFromJson`? Are you using `realm.createAllFromJson(MyResponse.class, json)` ?

**Comment by pankajnimgade** [comment]
`realm.createAllFromJson(MyResponse.class, result);`

       where, 
                  result is the JSON response

**Comment by pankajnimgade** [comment]
does realm prefers making JSON array conversion prior to other elements, 

As I have written this code to check the JSON representation of my RealmObjects 

 MyResponse myResponse = new MyResponse();
                myResponse.setSuccess(true);
                RealmList<Data> datas = new RealmList<Data>();
                for (int i = 0; i < 3; i++) {
                    Data data = new Data();
                    data.setId(1);
                    data.setUsername("username_" + i);
                    data.setEmail("email_" + i);
                    datas.add(data);
                }
                myResponse.setData(datas);
                String json_result = (new Gson()).toJson(myResponse);
                Log.d(TAG, "onResponse: \n"+json_result);
```
And this is what I get 

{
  "data": [
    {
      "username": "username_0",
      "email": "email_0",
      "id": 1,
      "flags": 0,
      "updated_at": 0,
      "created_at": 0
    },
    {
      "username": "username_1",
      "email": "email_1",
      "id": 1,
      "flags": 0,
      "updated_at": 0,
      "created_at": 0
    },
    {
      "username": "username_2",
      "email": "email_2",
      "id": 1,
      "flags": 0,
      "updated_at": 0,
      "created_at": 0
    }
  ],
  "success": true
}
```

**Comment by nhachicha** [comment]
Hi @pankajnimgade 
you should call instead,
```java
realm.createObjectFromJson(MyResponse.class, json);
```
 as your root _json_ element is a `JSONObject` (`MyResponse`)

Cheers

**Comment by pankajnimgade** [comment]
@nhachicha  and @cmelchior , Thank you for helping me out. I should have taken a better look at API's.

My code is working now. 

your database is regarded highly and made my work quite easier, Thank you so much.
