### ISSUE TITLE
Can it support fastjson ？

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#2925]
How to use it?

**Comment by stk1m1** [comment]
If you referring [FastJson](https://github.com/alibaba/fastjson) from Alibaba, you can definitely do that with gradle. Here's an example provided from Bintray.

```gradle
compile 'com.alibaba:fastjson:1.2.12'
```
> References

- <https://bintray.com/bintray/jcenter/com.alibaba:fastjson>  
- <http://mvnrepository.com/artifact/com.alibaba/fastjson/1.2.12>  

We'd highly appreciate if you fill up the template following [our guide](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) for filing an issue.

**Comment by gushoubang** [comment]
but it cause a problem like this

 `User  user = JSON.parseObject(jsonString, User.class);`

```
public class User extends RealmObject implements Serializable {
    private String id = "";
    private String token = "";
    public String phone = "";
    private String nickname = "";
    private String avatar = "";
    private String created_at = "";
    private String updated_at = "";
    private boolean isFirstLogin = true;

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Boolean isFirstLogin() {
        return isFirstLogin;
    }

    public void setFirstLogin(Boolean isFirstLogin) {
        this.isFirstLogin = isFirstLogin;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
}

```

```
                                                               Process: com.dituwuyou, PID: 29213
                                                               java.lang.NoClassDefFoundError: rx/Observable
                                                                   at java.lang.Class.getDeclaredMethods(Native Method)
                                                                   at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
                                                                   at java.lang.Class.getMethods(Class.java:877)
                                                                   at com.alibaba.fastjson.util.JavaBeanInfo.build(JavaBeanInfo.java:134)
                                                                   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:40)
                                                                   at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:545)
                                                                   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:433)
                                                                   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:288)
                                                                   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:607)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:327)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:231)
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:444)
                                                                   at com.dituwuyou.util.AnalysisJsonUtils.getUser(AnalysisJsonUtils.java:93)
                                                                   at com.dituwuyou.uipresenter.LoginPress$1.onSuccess(LoginPress.java:57)
                                                                   at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:276)
                                                                   at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:134)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.Observable" on path: DexPathList[[zip file "/data/app/com.dituwuyou-1.apk", zip file "/data/data/com.dituwuyou/code_cache/secondary-dexes/com.dituwuyou-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.dituwuyou-1, /vendor/lib, /data/datalib, /system/lib]]
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                   at java.lang.Class.getDeclaredMethods(Native Method) 
                                                                   at java.lang.Class.getPublicMethodsRecursive(Class.java:894) 
                                                                   at java.lang.Class.getMethods(Class.java:877) 
                                                                   at com.alibaba.fastjson.util.JavaBeanInfo.build(JavaBeanInfo.java:134) 
                                                                   at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.<init>(JavaBeanDeserializer.java:40) 
                                                                   at com.alibaba.fastjson.parser.ParserConfig.createJavaBeanDeserializer(ParserConfig.java:545) 
                                                                   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:433) 
                                                                   at com.alibaba.fastjson.parser.ParserConfig.getDeserializer(ParserConfig.java:288) 
                                                                   at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:607) 
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:327) 
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:231) 
                                                                   at com.alibaba.fastjson.JSON.parseObject(JSON.java:444) 
                                                                   at com.dituwuyou.util.AnalysisJsonUtils.getUser(AnalysisJsonUtils.java:93) 
                                                                   at com.dituwuyou.uipresenter.LoginPress$1.onSuccess(LoginPress.java:57) 
                                                                   at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:276) 
                                                                   at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:134) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 


```

**Comment by stk1m1** [comment]
@gushoubang

Since I don't have your `build.gradle` I'd like to be cautious about how you come to this error. But from the trace, I see the error ends with following.

> java.lang.NoClassDefFoundError: rx/Observable`

I would urge you to check your `build.gradle` to see if it is properly setup.

**Comment by gushoubang** [comment]
```
apply plugin: 'com.android.application'//添加用于Gradle构建过程的Android插件
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'android-apt'
apply plugin: 'bugly'   //添加Bugly符号表插件
apply plugin: 'realm-android'
def AAVersion = '3.2'


android {
    compileSdkVersion 22
    buildToolsVersion '23.0.2'
    defaultConfig {
        applicationId "XXXX"
        minSdkVersion 15
        targetSdkVersion 22
        multiDexEnabled true
        ndk {
            //设置支持的SO库架构 bugley
            abiFilters 'armeabi', 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }
        versionName '2.1.0test'
        versionCode 2101
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java', 'build/generated/source/apt/${variant.dirName}']
            resources.srcDirs = ['src/main/resources']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            zipAlignEnabled false
        }
    }
    productFlavors {
        xiaomi {
            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "xiaomi"]
        }
//        _360 {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "360"]
//        }
//        baidu {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "baidu"]
//        }
//        wandoujia {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "wandoujia"]
//        }
//        official {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "official"]
//        }
//        qq {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "qq"]
//        }
//        huawei {
//            manifestPlaceholders = [UMENG_CHANNEL_VALUE: "huawei"]
//        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'

        exclude 'META-INF/maven/com.squareup.okio/okio/pom.xml'
        exclude 'META-INF/maven/com.squareup.okio/okio/pom.properties'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.viewpagerindicator:library:2.4.1@aar'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.facebook.fresco:fresco:0.7.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.4'
    compile 'com.alibaba:fastjson:1.2.7'
    compile 'com.google.guava:guava:19.0-rc2'
    //上拉显示
    compile 'com.sothree.slidinguppanel:library:3.2.0'
    //圆形图片显示
    compile 'de.hdodenhof:circleimageview:2.0.0'
    //其中<version>替换为当前最新的Bugly SDK版本号
    compile 'com.tencent.bugly:crashreport:1.2.9'
    compile 'com.umeng.analytics:analytics:latest.integration'
    compile 'com.android.support:cardview-v7:23.2.0'
    compile files('libs/activation.jar')
    compile files('libs/additionnal.jar')
    compile files('libs/android-async-http-1.4.5.jar')
    compile files('libs/android-viewbadger.jar')
    compile files('libs/BaiduLBS_Android.jar')
    compile files('libs/com.umeng.message.lib_v2.5.0.jar')
    compile files('libs/commons-lang3-3.3.2.jar')
    compile files('libs/galaxy_mini.jar')
    compile files('libs/lite-orm-1.5.2.jar')
    compile files('libs/umeng-update-v2.6.0.1.jar')
    //显示百分比的进度条
    compile 'com.daimajia.numberprogressbar:library:1.2@aar'
    //facebook抓包
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.google.android.gms:play-services-appindexing:8.1.0'
    //显示图片控件
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.caverock:androidsvg:1.2.1'
    //裁剪图片控件
    compile 'com.soundcloud.android:android-crop:1.0.1@aar'
}
bugly {
    appId = 'XXX'    //注册时分配的App ID
    appKey = 'XXX'  //注册时分配的App Key
}

apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        // if you have multiple outputs (when using splits), you may want to have other index than 0

        resourcePackageName 'com.dituwuyou'

        // If you're using Android NBS flavors you should use the following line instead of hard-coded packageName
        // resourcePackageName android.defaultConfig.applicationId

        // You can set optional annotation processing options here, like these commented options:
        // logLevel 'INFO'
        // logFile '/var/log/aa.log'
    }
}
```

**Comment by cmelchior** [comment]
Another option is that FastJson is doing some reflection magic Like Jackson Databind. So perhaps the same workaround will do here: https://realm.io/docs/java/latest/#jackson-databind

**Comment by gushoubang** [comment]
It's OK,thanks

**Comment by stk1m1** [comment]
@gushoubang 

Has @cmelchior's suggestion helped you?

**Comment by gushoubang** [comment]
Oh,Yes,thanks
