### ISSUE TITLE
Outofmemory with IntentService.

### ISSUE THREAD

**Issue by SumitKumarTiawri** [realm/realm-java#2967]
Hi Realm team,
 First of all thank you guys for making this beautiful ORM +1: 

 I am developing an application which need to sync local data to server. while i am using IntentService to perform background task and everything runs great but something realm getting crashed because of memory leak. I tried to close realm instance properly within activities and fragments but in intent service if i close the realm instance then it cause a crash i.e. realm instance has been already closed.

**Realm Version-** 1.0
**Device**- Moto G4 plus

My code snippet is as follows-

```java
public class UploadService extends IntentService {
    private String TAG = "UploadService";
    public static int UPLOAD_TIME_INTERVAL = 5;

    public UploadService(String name) {
        super(name);
    }

    public UploadService() {
        super("UpdateService");
    }


    @Override
    public void onCreate() {
        super.onCreate();
    }

    @Override
    protected void onHandleIntent(Intent intent) {
        if (Connectivity.isConnected(this))
            launchUpdateTask();
    }


    private void launchUpdateTask() {
        updateTask();
        updateSignature();
        attachSignatureToTask();
        uploadPhoto();
        attachPhoto();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
    }

    private void updateTask() {
        Realm realm = Realm.getDefaultInstance();
        RealmResults<TaskInfo> results = realm.where(TaskInfo.class).equalTo("isModified", true).findAllSorted("lastUpdated", Sort.DESCENDING);
        if (results == null || results.size() == 0) {
            return;
        }
        TaskInfo taskInfo = results.first();
        if (taskInfo == null)
            return;
        final String taskId = taskInfo.getNid();
        Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.where(TaskInfo.class).equalTo("nid", taskId).findFirst().setLastUpdated(CommonUtil.getDateHMS());

            }
        });

        Log.e(TAG, "Task Update:Start" + taskInfo.getNid());

        JsonObjectRequest jsonObject = new JsonObjectRequest(Request.Method.PUT, ApiInfo.getTaskUpdateUrl(taskInfo.getNid()), ApiInfo.Builder.uploadTaskBody(taskInfo.getNid()), new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(final JSONObject response) {
                Log.e(TAG, "Task Update:End-" + response.toString());
                if (response.has("nid"))
                    Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            try {
                                realm.where(TaskInfo.class).equalTo("nid", response.getString("nid")).findFirst().setModified(false);
                            } catch (JSONException e) {
                                e.printStackTrace();
                            }
                        }
                    });
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                error.printStackTrace();
                Log.e(TAG, "Task Update:End-" + error.toString());
            }
        }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                return ApiInfo.getHeaders();
            }

            @Override
            public String getBodyContentType() {
                return ApiInfo.getBodyContentType();
            }
        };
        jsonObject.setShouldCache(false);
        jsonObject.setRetryPolicy(Constants.getRetryPolicy(Constants.TimeOut._HIGH));
        BaseApp.getInstance().addToRequestQueue(jsonObject, RequestTag.UPLOAD_TASK);

    }

    private void updateSignature() {
        RealmResults<SignatureModel> results = Realm.getDefaultInstance().where(SignatureModel.class).equalTo("isSyned", false).findAllSorted("lastUpdated", Sort.DESCENDING);
        if (results == null || results.size() == 0)
            return;
        final SignatureModel signatureModel = results.first();
        if (signatureModel == null || TextUtils.isEmpty(signatureModel.getSignatureImage())) {
            return;
        }
        Log.e(TAG, "Signature Update:Start-" + signatureModel.getSignatureId());
        final String signatureId = signatureModel.getSignatureId();
        Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.where(SignatureModel.class).equalTo("signatureId", signatureId).findFirst().setLastUpdated(CommonUtil.getDateHMS());
            }
        });

        JsonObjectRequest jsonObject = new JsonObjectRequest(Request.Method.POST, ApiInfo.getFileUrl(), ApiInfo.Builder.getImageBody(signatureModel.getSignatureImage(), signatureModel.getSignatureId()), new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(final JSONObject response) {
                Log.e(TAG, "Signature Update:End-" + response.toString());
                if (!TextUtils.isEmpty(signatureId) && response.has("fid")) {
                    Realm.getDefaultInstance().executeTransactionAsync(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            try {
                                SignatureModel updatedSig = realm.where(SignatureModel.class).equalTo("signatureId", signatureId).findFirst();
                                if (updatedSig != null) {
                                    updatedSig.setSyned(true);
                                    updatedSig.setFid(response.getString("fid"));
                                }
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    });
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                error.printStackTrace();
                Log.e(TAG, "Signature Update:End-" + error.toString());
            }
        }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                return ApiInfo.getHeaders();
            }

            @Override
            public String getBodyContentType() {
                return ApiInfo.getBodyContentType();
            }
        };
        jsonObject.setShouldCache(false);
        jsonObject.setRetryPolicy(Constants.getRetryPolicy(Constants.TimeOut._HIGH));
        BaseApp.getInstance().addToRequestQueue(jsonObject, RequestTag.IMAGE_TASK);
    }

    private void attachSignatureToTask() {

        RealmResults<SignatureModel> results = Realm.getDefaultInstance().where(SignatureModel.class).equalTo("isSyned", true).equalTo("attached", false).findAllSorted("lastUpdated", Sort.DESCENDING);
        if (results == null || results.size() == 0)
            return;
        final SignatureModel signatureModel = results.first();
        if (signatureModel == null)
            return;

        Log.e(TAG, "Signature Attach:Start-" + signatureModel.getSignatureId());
        final String signatureId = signatureModel.getSignatureId();
        Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.where(SignatureModel.class).equalTo("signatureId", signatureId).findFirst().setLastUpdated(CommonUtil.getDateHMS());
            }
        });

        JsonObjectRequest jsonObject = new JsonObjectRequest(Request.Method.PUT, ApiInfo.getTaskUpdateUrl(signatureModel.getTaskId()), ApiInfo.Builder.getSignatureBody(signatureModel.getFid()), new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(final JSONObject response) {
                Log.e(TAG, "Signature Attach:End-" + response.toString());
                if (!TextUtils.isEmpty(signatureId) && response.has("nid"))
                    Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            realm.where(SignatureModel.class).equalTo("signatureId", signatureId).findFirst().setAttached(true);
                        }
                    });
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                error.printStackTrace();
                Log.e(TAG, "Signature Attach:End-" + error.toString());
            }
        }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                return ApiInfo.getHeaders();
            }

            @Override
            public String getBodyContentType() {
                return ApiInfo.getBodyContentType();
            }
        };
        jsonObject.setShouldCache(false);
        jsonObject.setRetryPolicy(Constants.getRetryPolicy(Constants.TimeOut._HIGH));
        BaseApp.getInstance().addToRequestQueue(jsonObject, RequestTag.UPLOAD_TASK);
    }


    private void uploadPhoto() {
        Log.e(TAG, "Photo Update:Method");
        RealmResults<PhotoModel> results = Realm.getDefaultInstance().where(PhotoModel.class).equalTo("isSyned", false).findAllSorted("lastUpdated", Sort.DESCENDING);
        if (results == null || results.size() == 0)
            return;
        final PhotoModel photoModel = results.first();
        if (photoModel == null || TextUtils.isEmpty(photoModel.getPhotoImage()) || !(new File(photoModel.getPhotoImage()).exists())) {
            return;
        }
        Log.e(TAG, "Photo Update:Start-" + photoModel.getPhotoId());
        final String photoId = photoModel.getPhotoId();
        Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.where(PhotoModel.class).equalTo("photoId", photoId).findFirst().setLastUpdated(CommonUtil.getDateHMS());
            }
        });

        JsonObjectRequest jsonObject = new JsonObjectRequest(Request.Method.POST, ApiInfo.getFileUrl(), ApiInfo.Builder.getImageBodyPath(photoModel.getPhotoImage(), photoModel.getPhotoId()), new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(final JSONObject response) {
                Log.e(TAG, "Photo Update:End-" + response.toString());
                if (!TextUtils.isEmpty(photoId) && response.has("fid")) {
                    Realm.getDefaultInstance().executeTransactionAsync(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            try {
                                PhotoModel updatedSig = realm.where(PhotoModel.class).equalTo("photoId", photoId).findFirst();
                                if (updatedSig != null) {
                                    updatedSig.setSyned(true);
                                    updatedSig.setFid(response.getString("fid"));
                                    updatedSig.setPhotoImage(String.format(ApiInfo.PHOTO_URL, updatedSig.getPhotoId()));
                                }
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    });
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                error.printStackTrace();
                Log.e(TAG, "Photo Update:End-" + error.toString());
            }
        }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                return ApiInfo.getHeaders();
            }

            @Override
            public String getBodyContentType() {
                return ApiInfo.getBodyContentType();
            }
        };
        jsonObject.setShouldCache(false);
        jsonObject.setRetryPolicy(Constants.getRetryPolicy(Constants.TimeOut._MEDIUM));
        BaseApp.getInstance().addToRequestQueue(jsonObject, RequestTag.IMAGE_TASK);
    }

    private void attachPhoto() {
        RealmResults<PhotoModel> results = Realm.getDefaultInstance().where(PhotoModel.class).equalTo("isSyned", true).equalTo("attached", false).findAllSorted("lastUpdated", Sort.DESCENDING);
        if (results == null || results.size() == 0)
            return;
        PhotoModel randomModel = results.first();
        if (randomModel == null)
            return;
        RealmResults<PhotoModel> taskResults = Realm.getDefaultInstance().where(PhotoModel.class).equalTo("taskId", randomModel.getTaskId()).equalTo("isSyned", true).findAllSorted("lastUpdated", Sort.DESCENDING);
        if (taskResults == null || taskResults.size() == 0)
            return;

        final HashMap<String, String> idBundle = new HashMap<>();
        for (PhotoModel singleResult : taskResults)
            idBundle.put(singleResult.getFid(), singleResult.getPhotoId());



        Log.e(TAG, "Photo Attach:Start-" + taskResults.size());
        Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                for (String id : idBundle.keySet())
                    realm.where(PhotoModel.class).equalTo("photoId", idBundle.get(id)).findFirst().setLastUpdated(CommonUtil.getDateHMS());
            }
        });

        JsonObjectRequest jsonObject = new JsonObjectRequest(Request.Method.PUT, ApiInfo.getTaskUpdateUrl(randomModel.getTaskId()), ApiInfo.Builder.getPhotosBody(idBundle), new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(final JSONObject response) {
                Log.e(TAG, "Photo Attach:End-" + response.toString());
                if (response.has("nid"))
                    Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            for (String id : idBundle.keySet())
                                realm.where(PhotoModel.class).equalTo("photoId", idBundle.get(id)).findFirst().setAttached(true);
                        }
                    });
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                error.printStackTrace();
                Log.e(TAG, "Photo Attach:End-" + error.toString());
            }
        }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                return ApiInfo.getHeaders();
            }

            @Override
            public String getBodyContentType() {
                return ApiInfo.getBodyContentType();
            }
        };
        jsonObject.setShouldCache(false);
        jsonObject.setRetryPolicy(Constants.getRetryPolicy(Constants.TimeOut._MEDIUM));
        BaseApp.getInstance().addToRequestQueue(jsonObject, RequestTag.UPLOAD_TASK);
    }
}
```

**Exception trace-**
```
  io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 503316480 offset: 0 in io_realm_internal_SharedGroup.cpp line 188
            at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
            at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:95)
            at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:62)
            at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:118)
            at io.realm.BaseRealm.commitTransaction(BaseRealm.java:340)
            at io.realm.BaseRealm.commitTransaction(BaseRealm.java:327)
            at io.realm.Realm.commitTransaction(Realm.java:120)
            at io.realm.Realm.executeTransaction(Realm.java:965)
            at com.opensource.fieldteam.service.UploadService.updateTask(UploadService.java:88)
            at com.opensource.fieldteam.service.UploadService.launchUpdateTask(UploadService.java:66)
            at com.opensource.fieldteam.service.UploadService.onHandleIntent(UploadService.java:61)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

Please help me how can i rid this problem. Any help would be appreciated.
Thanks

**Comment by Zhuinden** [comment]
`Realm realm = Realm.getDefaultInstance();` opens a new instance of the Realm.

In fact, every call to `Realm.getDefaultInstance().` opens a new instance of the Realm.

On background threads, this will make Realm retain old versions of the Realm until these Realm instances are closed.

You're not closing them, so you're retaining many old versions of the Realm.

Solution: you should close the Realms that you open.

**Comment by beeender** [comment]
:+1:  For above comment

And eg.:

```
Realm.getDefaultInstance().executeTransaction();
```

will created an anonymous realm instance and cannot be closed.
You need to call `Realm.close()` every time corresponding to every `Realm.getInstance()`/`Realm.getDefaultInstance()` .

**Comment by SumitKumarTiawri** [comment]
:+1:
Thanks you guys. Let me try  :relaxed:

**Comment by SumitKumarTiawri** [comment]
@Zhuinden @beeender thanks :+1:
Everything running fine.
