### ISSUE TITLE
Exception parsing classes : realm-optional-api

### ISSUE THREAD

**Issue by osayilgan** [realm/realm-java#3033]
Hi,

Right after the update to Realm 1.0.1 from 0.82, I started getting this Exception below. I tried building my project with Android Studio 2.1 and 2.2-Preview3 but the result is the same. Any idea why this is happening ?

I'm using RetroLambda so the compiler options is as below:

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8 
}

```

Thanks.

Android Studio : 2.2 Preview3
Gradle Version : 2.13
Android Gradle Plugin : 2.1.0 (tried with 2.2.0-alpha3 as well)
compileSdkVersion : 23
buildToolsVersion : 23.0.3

```
[DEBUG] [com.android.build.gradle.internal.ApplicationTaskManager] processing /Users/.../app/build/intermediates/transforms/RealmOptionalAPITransformer/airwatch/debug/folders/1/10/realm-optional-api/./retrofit/mime/TypedInput.class...
[DEBUG] [com.android.build.gradle.internal.ApplicationTaskManager] processing /Users/.../app/build/intermediates/transforms/RealmOptionalAPITransformer/airwatch/debug/folders/1/10/realm-optional-api/./retrofit/mime/TypedOutput.class...
[DEBUG] [com.android.build.gradle.internal.ApplicationTaskManager] processing /.../app/build/intermediates/transforms/RealmOptionalAPITransformer/airwatch/debug/folders/1/10/realm-optional-api/./retrofit/mime/TypedString.class...
[ERROR] [org.gradle.api.Project] Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Exception parsing classes
        at com.android.dx.command.dexer.Main.processClass(Main.java:752)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:672)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
        at com.android.dx.command.dexer.Main.run(Main.java:275)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
        at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
        at com.android.dx.command.dexer.Main.processClass(Main.java:749)
        ... 17 more
```

**Comment by beeender** [comment]
The related transformer has been disabled by #3028 . You could try the snapshot (probably still need a few hours for snapshot release to include it) before we release it.

**Comment by osayilgan** [comment]
@beeender , what is the latest version includes this fix ? Snapshot still seems to be 1.1.0-SNAPSHOT in version.txt file.

**Comment by beeender** [comment]
@osayilgan It is `1.1.0-SNAPSHOT`, it should contain the fix.

**Comment by osayilgan** [comment]
@beeender Thanks for the quick fix

**Comment by beeender** [comment]
realm-optional-api has been removed.
