### ISSUE TITLE
FATAL EXCEPTION: main This Realm instance has already been closed, making it unusable when you resume to fragment

### ISSUE THREAD

**Issue by pkegashira** [realm/realm-java#3036]
I am using the latest version of realm `1.0.1`. I have this bug on one of my fragments and i cant seem to find the reason.

this is where i am opening my realm as per recomendations:
```@Override
    public void onStart() {
        super.onStart();

        // get hold of realm
        realm = Realm.getDefaultInstance();
        evaluateFilterSelections(null);
    }
```

and closing it here:
```@Override
    public void onStop() {
        super.onStop();

        try {

            if (retailerResults != null && !realm.isClosed()) {
                retailerResults.removeChangeListener(retailerCallback);
            }

            if (industryResults != null && !realm.isClosed()) {
                industryResults.removeChangeListener(industryCallback);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //clear adapters
        mCustomerRecyclerView.setAdapter(null);
        realm.close();
    }
```

this is my `evaluateFilterSelections` method:
```
RealmResults<RetailerRoute> routes = realm.where(RetailerRoute.class)
                        .equalTo(getWeekday(), true).findAll();
                RealmQuery<Retailer> query = realm.where(Retailer.class);

                // filter
                if (!TextUtils.isEmpty(searchQuery)) {
                    query = query.contains("name", searchQuery, Case.INSENSITIVE)
                            .beginGroup();
                }

                if (routes.size() > 0 && routeFilter.size() > 0) {

                    for (int a = 0; a < routes.size(); a++) {

                        if (routeFilter.get(0).getTitle().equals(Constants.IN_ROUTE)) {

                            if (a > 0) {
                                query = query.or();
                            }

                            query = query.equalTo("id", routes.get(a).getRetailerId());

                        } else {
                            query = query.notEqualTo("id", routes.get(a).getRetailerId());
                        }
                    }
                }

                if (!TextUtils.isEmpty(searchQuery)) {
                    query = query.endGroup();
                }

 retailerResults = query.findAllAsync();
 retailerResults.addChangeListener(retailerCallback);
```

and my change listener:

```
private RealmChangeListener retailerCallback = new RealmChangeListener<RealmResults<Retailer>>() {

        @Override
        public void onChange(RealmResults<Retailer> results) {

            //update retailerAdapter
            retailerAdapter.update(results);
        }
    };
```
in my adapter inside `onBindViewHolder` i do this:
```
if(!realm.isClosed()){
                    route = realm.where(RetailerRoute.class).equalTo("retailerId", retailer.getId()).findFirst();
                }
```
the application works okey except when i pause my app to open another, then come back. even though am checking if the realm is closed , i still get the exception. I put a try catch around it but now am getting the same exception around here: 

```
@Override
        public long getItemId(int position) {
            return retailerArrayList.get(position).getId();
        }
```
Please help me where am doing wrong. here is my [fragment ](https://gist.github.com/pkegashira/9d9b546e4193264d2d3bf0e9ce5bb044)and stacktrace:

```
06-21 08:41:43.499 21478-21478/com.prismbit.marketmapping E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.prismbit.marketmapping, PID: 21478
                                                                            java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
                                                                                at io.realm.BaseRealm.checkIfValid(BaseRealm.java:437)
                                                                                at io.realm.RetailerRealmProxy.realmGet$id(RetailerRealmProxy.java:141)
                                                                                at com.prismbit.marketmapping.realm.Retailer.getId(Retailer.java:37)
                                                                                at com.prismbit.marketmapping.app.main.fragments.RoutesFragment$RetailerAdapter.getItemId(RoutesFragment.java:758)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4963)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1759)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:120)
                                                                                at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1319)
                                                                                at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:815)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
                                                                                at android.view.View.layout(View.java:15140)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2323)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2029)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                            	at android.view.Choreo
```

**Comment by stk1m1** [comment]
Hi @pkegashira 

Sorry for your trouble. Could you somehow build a small sample project to reproduce your issue? I've tried to get the crash by rebuilding your project with the fragment you've provided, but not been successful as the fragment is a small part of a project. 

If you could share with us a rather complete sample project at help@realm.io, our job could be much more easier to help you. 😅 I'll strongly look forward.

**Comment by pkegashira** [comment]
@stk1m1 thanks alot for your response i have sent the project and tagged the issue number.

**Comment by pkegashira** [comment]
@stk1m1 i can confirm the bug is resolved. for the sake of future novices like me, i post your solution below.

>I've noticed that realm instance gets created & closed at onStart() and onStop() for lifecycle control. I'd suggest to move the control to onCreate() (onActivityCreated() if you are in need to respect Activity's cycle) and onDestroy() instead.

>Fragment.onStop() is generally controlled by Activity.onClose(), and according to Android Doc, Activity.onClose() is Called when you are no longer visible to the user. You will next receive either onRestart(), onDestroy(), or nothing, depending on later user activity.

>By moving Realm contols close to the lifecycle of Fragment, you can expect rather consistent Realm behavior as it stays away from complex view controls by Android as depicted here. https://developer.android.com/images/activity_fragment_lifecycle.png

>Here's a code I've tried.

```
// onCreate
@Override
public void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // get hold of realm
    realm = Realm.getDefaultInstance();
    setHasOptionsMenu(true);
}


// onDestory
@Override
public void onDestroy() {
    super.onDestroy();
    if (mCustomerRecyclerView != null) {
        mCustomerRecyclerView.setAdapter(null);
    }
    realm.close();
}
```

Thanks alot cheers!

**Comment by stk1m1** [comment]
Glad it helps. I'm closing the issue fow now.

**Comment by zachtom** [comment]
Hi,
I am having similar issue. When I close app by pressing home button and open again the application crashes throwing same error when I switch around screens. Seeing this thread I moved Realm initialisation to onCreate and close to onDestroy() . But nothing has changed.

When I referred here https://realm.io/docs/java/latest/#best-practices it says realm initialisation and close should be in onStart() and onStop() of Fragments.

Whats the best way forward?

**Comment by LPFinch** [comment]
Similar issue #3891

**Comment by koukoucai** [comment]
Similar issue

`
        final List<User> users = new ArrayList<>();
        ((Button)findViewById(R.id.updatebt)).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                realm = Realm.getDefaultInstance();

                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        List<User> user = realm.where(User.class).equalTo("isUpload",false).findAll();
                        users.addAll(user);
                        Log.e(TAG,"update over ::: +user "+user.size()+"  users:  "+users.size());
                    }
                });
                realm.close();
                Log.e("","users.get : "+users.get(0).getName());

            }
        });
`

I get exception  on "  Log.e("","users.get : "+users.get(0).getName());" 
` java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.`


I want to confirm that  User extends RealmObject after realm close that User 's getName()  will not work?

**Comment by beeender** [comment]
@koukoucai No. All the Realm accessors will NOT work if the corresponding Realm instance is closed.

**Comment by koukoucai** [comment]
@beeender get it,thanks

**Comment by tahir-mahmood-10p** [comment]
similar issue, realm got crashed on checkIfValid (as it is getting closed realm), when is it closed on onDestory while navigating screen (Activity) 
Should I put delay in while closing? but that isnt a good solution

**Comment by Zhuinden** [comment]
Well `RealmRecyclerViewAdapter` checks `realmResults.isValid()` in `getItemCount()` so probably you could do the same?
