### ISSUE TITLE
slf4j error after upgrading to realm 1.0.1

### ISSUE THREAD

**Issue by gilcarmel** [realm/realm-java#3043]
#### Goal

I upgraded Realm from 0.88.3 to 1.0.1 in my Android app. I retrofitted for the few breaking changes and got everything to build.

#### Expected Results

Realm run as expected.

#### Actual Results

I got a seemingly unrelated NoClassDefFoundError during initialization of pubnub (stack trace below).
This appears to be the same issue described by another user in this Stackoverflow question: 
http://stackoverflow.com/questions/37226059/realm-doesnt-work-with-slf4j

06-21 15:35:33.080 30963-30963/com.detour.detour E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.detour.detour, PID: 30963
                                                                   java.lang.NoClassDefFoundError: org.gradle.logging.internal.slf4j.OutputEventListenerBackedLoggerContext
                                                                       at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:30)
                                                                       at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:27)
                                                                       at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
                                                                       at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
                                                                       at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
                                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
                                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
                                                                       at com.pubnub.api.PubNub.<clinit>(PubNub.java:37)
                                                                       at com.detour.groupkit.PubNubService.<init>(PubNubService.java:46)
                                                                       at com.detour.groupkit.Session.<init>(Session.java:106)
                                                                       at com.detour.detour.sync.SyncService.createSession(SyncService.java:184)
                                                                       at com.detour.detour.sync.SyncService.setAvailable(SyncService.java:244)
                                                                       at com.detour.detour.sync.SyncService.<init>(SyncService.java:173)
                                                                       at com.detour.detour.sync.SyncService.create(SyncService.java:160)
                                                                       at com.detour.detour.DetourApplication.onCreate(DetourApplication.java:43)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                       at dalvik.system.NativeStart.main(Native Method)

#### Version of Realm and tooling
Realm version(s): 1.0.1

Android Studio version: 2.1.2

Which Android version and device: All

**Comment by stk1m1** [comment]
Hi @gilcarmel 

Would you mind if I ask your `build.gradle` for us to reproduce? Like you pointed, we have SO case but like to make sure this issue is reproducible with more sample cases. You input will be highly appreciated.

**Comment by gilcarmel** [comment]
Sure! You can repro here:
https://github.com/gilcarmel/RealmPubnub

Thanks,
Gil

**Comment by stk1m1** [comment]
@gilcarmel 

We have addressed the issue internally, and there will be a version resolving the issue. 
At this moment, we have two suggestions

1. Add `slf4j` one more time in `app.gradle` that it would look like  
  ```groovy
  compile 'org.slf4j:slf4j-nop:1.7.21'
  compile 'com.pubnub:pubnub:4.0.3'  
  ```  

2. You can use realm `1.0.0` to avoid the issue.  

Sorry for your inconvenience.

**Comment by kneth** [comment]
I am closing the issue - it is basically the same as #3018.
