### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error.

### ISSUE THREAD

**Issue by chenzj-king** [realm/realm-java#3053]
I run the app and do some normal operate. Like new realmObject or update some realmeObject. It was very normal. But sometime I didn't operate the phone. Just take the phone on the one side. It will like crash but didn't kill the app.  

It happend in `com.sq580.followup:leakcanary#main(1)`. I think is the leakcanary's problem.  

### the crash screen shot ###
![](http://i.imgur.com/ynsIwbC.png)

### the logcat Message ###

    06-23 09:28:48.152 28105-28105/com.sq580.followup:leakcanary E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.sq580.followup:leakcanary, PID: 28105
                                                                               io.realm.exceptions.RealmError: Unrecoverable error. /data/data/com.sq580.followup/files/followup.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 25520. Current pid is 28105. in io_realm_internal_SharedGroup.cpp line 113
                                                                                   at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                                                   at io.realm.internal.SharedGroup.<init>(SharedGroup.java:64)
                                                                                   at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
                                                                                   at io.realm.BaseRealm.<init>(BaseRealm.java:79)
                                                                                   at io.realm.Realm.<init>(Realm.java:138)
                                                                                   at io.realm.Realm.createAndValidate(Realm.java:248)
                                                                                   at io.realm.Realm.createInstance(Realm.java:228)
                                                                                   at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
                                                                                   at io.realm.Realm.getInstance(Realm.java:192)
                                                                                   at com.sq580.followup.database.RealmManager.<init>(RealmManager.java:46)
                                                                                   at com.sq580.followup.database.RealmManager.getInstanse(RealmManager.java:70)
                                                                                   at com.sq580.followup.AppContext.initDataBase(AppContext.java:153)
                                                                                   at com.sq580.followup.AppContext.onCreate(AppContext.java:72)
                                                                                   at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369)
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4632)
                                                                                   at android.app.ActivityThread.access$1800(ActivityThread.java:141)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                                                                                   at dalvik.system.NativeStart.main(Native Method)

### the crash more message ###
[bugly crash Message](http://bugly.qq.com/share/THhOX5)  

can you guide me to solve this problem.  

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.2

Which Android version and device: 4.4.4 & 5.0.1

**Comment by beeender** [comment]
Are you using multi-processes in your application? Like having a service in a "remote" process?

**Comment by beeender** [comment]
hmmm, it seems `leakcanary` is running in a different process. I will check this.

**Comment by chenzj-king** [comment]
hi. @beeender 

I try to build release apk [remove the `leakcanary`] and try to run about 0.5h. It look like well. 
So It maybe is the `leakcanary` problem.

**Comment by beeender** [comment]
@chenzj-king Can you share your debug apk with us? Even it might be the leakcanary problem, we are still happy to know the root cause. Thanks! You can share the debug apk to help@realm.io

**Comment by chenzj-king** [comment]
@beeender I had send the debug apk and release apk to [help@realm.io](help@realm.io). Thanks for you help.

**Comment by beeender** [comment]
@chenzj-king The root cause is LeakCanary is running the `HeapAnalyzerService` in a separated process which is in the same application as yours. Thus, the init functions in the `Application` class will be called as well. So, if you are creating a Realm instance in the Application, try to do like something below:

```java
public class MyApplication extends Application{
    @Override
    public void onCreate() {
        super.onCreate();
        LeakCanary.install(this);

       // No need to create Realm instance for LeakCanary process
        if (!LeakCanary.isInAnalyzerProcess(this)) {
            byte[] key = new byte[64];
            Arrays.fill(key, (byte) 0);

            config = new RealmConfiguration.Builder(this).encryptionKey(key).build();
            realm = DynamicRealm.getInstance(config);
        }
    }
}
```

Also the same pattern can be applied to your other initialization code -- they won't be needed for LeakCanary process IMO.

Please try above and let me know the result. Thanks a lot!

**Comment by chenzj-king** [comment]
hi.@beeender 
I can't do this. because when i build release apk. it will 
 `releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'`.It didn't have `LeakCanary.isInAnalyzerProcess(this)` method. So it will build fail.

In my project. I will get creating a Realm instance like this  

    public RealmManager() {

        RealmConfiguration config = new RealmConfiguration.Builder(AppContext.getInstance())
                .schemaVersion(1)
                .name("test.realm")
                .encryptionKey(getKeys())
                .modules(new CustomModule())
                .migration(mRealmMigration)
                .build();
        mRealm = Realm.getInstance(config);
    }

    public static RealmManager getInstanse() {
        if (singleton == null) {
            synchronized (RealmManager.class) {

                if (singleton == null) {
                    singleton = new RealmManager();
                }
            }
        }
        return singleton;
    }

    public static Realm getRealm() {
        if (null == mRealm) {
            getInstanse();
        }
        return mRealm;
    }

Now my logic all get Realm instance like this. In addition to you above advice. How can I do will in debug and release apk.

**Comment by beeender** [comment]
You can  create two different application classes  for debug and release. I am not quite sure if there are better ways.

**Comment by chenzj-king** [comment]
Thanks. My project is release V1.0. Mabe I can del the leakcanary to fix the problem.
