### ISSUE TITLE
Out of memory in SharedGroup.cpp

### ISSUE THREAD

**Issue by maxmaxandr** [realm/realm-java#3065]
Hi., I have got OOM if  I doing a few transaction in the foreach. 
The data for each transaction is the same so I don't think that is issue with too large transaction. The first  few is commited succesfull. 

#### Actual Results
06-24 15:58:42.235 12857-12857/com.saritasa.testrealm D/REALM: jni: ThrowingException 11, mremap() failed: Out of memory old size: 301989888 new size: 335544320 in io_realm_internal_SharedGroup.cpp line 188, .
06-24 15:58:42.236 12857-12857/com.saritasa.testrealm D/REALM: Exception has been throw: Unrecoverable error. mremap() failed: Out of memory old size: 301989888 new size: 335544320 in io_realm_internal_SharedGroup.cpp line 188
06-24 15:58:42.263 12857-12857/com.saritasa.testrealm D/AndroidRuntime: Shutting down VM
06-24 15:58:42.264 12857-12857/com.saritasa.testrealm E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.saritasa.testrealm, PID: 12857
                                                                        io.realm.exceptions.RealmError: Unrecoverable error. mremap() failed: Out of memory old size: 301989888 new size: 335544320 in io_realm_internal_SharedGroup.cpp line 188
                                                                            at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
                                                                            at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:149)
                                                                            at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:62)
                                                                            at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:118)
                                                                            at io.realm.BaseRealm.commitTransaction(BaseRealm.java:362)
                                                                            at io.realm.BaseRealm.commitTransaction(BaseRealm.java:349)
                                                                            at io.realm.Realm.commitTransaction(Realm.java:121)
                                                                            at io.realm.Realm.executeTransaction(Realm.java:967)
                                                                            at com.saritasa.testrealm.MainActivity.onNavigationItemSelected(MainActivity.java:106)
                                                                            at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:152)
                                                                            at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
                                                                            at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                            at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
                                                                            at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:318)
                                                                            at android.view.View.performClick(View.java:5204)
                                                                            at android.view.View$PerformClick.run(View.java:21153)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample
            StringBuilder data1 = new StringBuilder();
            for(int j = 0; j <= 1; j++){
                data1.append(
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque purus neque, ut laoreet libero dignissim id. Mauris egestas, lorem eget viverra finibus, augue leo varius leo, ut elementum dolor nunc et leo. Nullam vitae volutpat turpis. Duis ut elit vitae nibh posuere sollicitudin quis in dui. Cras eu finibus turpis. Aenean id odio a dolor consectetur euismod. Aenean consequat a nibh vel vulputate. Fusce facilisis imperdiet elit id fringilla. Sed vel erat convallis, gravida turpis et, volutpat elit. Praesent sed iaculis nisi, consectetur semper metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque cursus bibendum urna, a ultricies ipsum lobortis at. Nunc varius semper justo, aliquet scelerisque dui fermentum eget.\n" +
                                "\n" +
                                "Vestibulum felis nulla, facilisis at volutpat scelerisque, varius vel lectus. Cras nibh urna, tincidunt sed nulla non, posuere commodo quam. Phasellus aliquam consequat diam, ut fermentum lacus sagittis vulputate. Aliquam ut neque quam. Curabitur tincidunt velit et orci iaculis dignissim. Pellentesque porttitor sapien tristique purus fermentum, id imperdiet tellus tincidunt. Mauris iaculis faucibus blandit. Fusce at mauris ac odio imperdiet gravida ut et nulla. Pellentesque sit amet egestas dui. Sed ac sollicitudin elit.\n" +
                                "\n" +
                                "Etiam ex magna, efficitur ac iaculis quis, fringilla et tellus. Cras congue consectetur gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis ut malesuada magna. Morbi nec interdum ligula, eget porttitor libero. Cras fringilla accumsan fringilla. Fusce eu finibus sem. Nulla vel leo quis sem consectetur euismod in in tortor.\n" +
                                "\n" +
                                "Praesent in nisl eget ipsum vulputate convallis. Mauris nunc urna, maximus et pharetra a, venenatis id ligula. Vestibulum iaculis orci et vehicula blandit. Ut sit amet lectus nec mauris maximus lacinia. Sed nec malesuada nulla. Nullam ac justo ac arcu facilisis egestas. Nullam iaculis, lorem vel semper fermentum, erat nisi placerat nisi, quis consectetur ante leo vitae ligula.\n" +
                                "\n" +
                                "Etiam iaculis facilisis arcu, sit amet volutpat felis rhoncus eu. Maecenas commodo efficitur viverra. Sed blandit nisl sed odio varius, at feugiat est elementum. Ut volutpat tortor felis, consectetur hendrerit ipsum tristique eget. Sed volutpat lacus vel pretium porta. Morbi eleifend tortor ligula, sit amet volutpat tellus tristique eu. Aliquam quam leo, posuere id accumsan a, viverra id lorem. Fusce ut blandit nisi. Donec facilisis sem sit amet est fringilla, a placerat erat rhoncus. Quisque sollicitudin nulla massa, a faucibus augue porttitor feugiat. Sed et lobortis tortor. Mauris nunc lorem, iaculis a sagittis sit amet, vestibulum et sem. Proin vel quam diam. Sed et arcu eget erat porttitor bibendum. Integer consequat porttitor sapien, et egestas mi scelerisque at.");
            }
            final String data = data1.toString();

            for(int k = 0; k <= 1000; k++){
                realm.executeTransaction(new Realm.Transaction(){

                    @Override
                    public void execute(final Realm realm){
                        test(realm, data);
                    }
                });

            }

    private void test(final Realm realm, final String aData){
        for(int k = 0; k <= 1000; k++){
            Event event = realm.createObject(Event.class);
            event.setName("EventName" + k);
            event.setId((long) k);
            event.setUuid("sdwwdwdwdwdw");
            event.setData(new String(aData));
        }
    }

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
1.0.1
Android Studio version: ?

Which Android version and device: 
Nexus 6/ Android 6.0.1

**Comment by zaki50** [comment]
Hi @maxmaxandr 

I think it's just an OOM.
Realm maps entire database file to memory by calling `mmap()`.

You are trying to create 1,000,000 objects and each object has about 5k bytes data.
That requires at least 5 giga bytes to be mapped to the memory.

**Comment by maxmaxandr** [comment]
@zaki50 
Does Realm store file on the disk?  or all db must be in the memory? 
What are memory limit for realm?

**Comment by zaki50** [comment]
@maxmaxandr 

Realm stores all data on the disk (if not in in-memory mode).
But at the same time, that file must be mmapped to the memory space.

The Limit of mmap is around 300M bytes on 32 bit android devices (not guaranteed, but in most devices).

**Comment by maxmaxandr** [comment]
@zaki50  ok. thank you.
