### ISSUE TITLE
java.lang.NullPointerException: name == null

### ISSUE THREAD

**Issue by ashk3156** [realm/realm-java#3067]
My RealmObjec class is this.

public enum ProductType {
        ACTIVE, IN_ACTIVE, OUT_OF_STOCK;
}
public void saveEnum(ProductType val) {
        if (!this.isValid) {
            this.enumvalue = val.IN_ACTIVE.toString().toUpperCase();
        } else if (this.quantity_ <= 0) {
            this.enumvalue = val.OUT_OF_STOCK.toString().toUpperCase();
        } else {
            this.enumvalue = val.ACTIVE.toString().toUpperCase();
        }
    }
 public ProductType getEnum() {
        return ProductType.valueOf(enumvalue);
    }

when i am calling getEnum ,it is giving error,

java.lang.NullPointerException: name == null
                                                             at java.lang.Enum.valueOf(Enum.java:189)
                                                             at com.localwizard.realm_db.SellerProducts$ProductType.valueOf(SellerProducts.java:322)
                                                             at com.localwizard.realm_db.SellerProducts.getEnum(SellerProducts.java:350)
                                                             at com.localwizard.seller.fragment.SellerProductsTabFragment.notifyDataUpdate(SellerProductsTabFragment.java:337)

why saveEnum is not initializing?

**Comment by Zhuinden** [comment]
Because when you call `getEnum()`, you had not called `saveEnum()` before. And therefore the `enumvalue` field is `null`.

Also I don't see where Realm comes into this, this error is not Realm-specific.

**Comment by ashk3156** [comment]
where should i call saveEnum ? my RealmObject class is directly mapping from server json response.
