### ISSUE TITLE
Crash while Creating Realm instance "Caused by java.lang.VerifyError"

### ISSUE THREAD

**Issue by AamirAbro** [realm/realm-java#3071]
#### Goal

> I am seeing verify error while creating Realm Instance. I am only seeing this in crashlytics and still don't know how to reproduce it.

#### Expected Results

> I should not crash and should return a valid realm instance

#### Actual Results

>  Caused by java.lang.VerifyError: io/realm/DbLocationRealmProxy
       at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:53)
       at io.realm.Realm.initializeRealm(Realm.java:315)
       at io.realm.Realm.createAndValidate(Realm.java:283)
       at io.realm.Realm.createInstance(Realm.java:248)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:213)

#### Steps & Code to Reproduce

> I have not been able to reproduce it but I am seeing this crashlytics. Note: I have not change the model lately

#### Code Sample

```
// this is initialization code
Realm.getInstance(new RealmConfiguration.Builder(appContext)
                    .deleteRealmIfMigrationNeeded()
                    .build());
```

#### Version of Realm and tooling
Realm version(s): "io.realm:realm-gradle-plugin:0.88.2"

Android Studio version: 2.1. and 2.2 preview

Which Android version and device: This is mostly crashing on HUAWEI phones (97%) using Android os  4.2.1 (97%)

**Comment by Zhuinden** [comment]
Can you share code for DbLocation realm object?

**Comment by AamirAbro** [comment]
Some names are redacted also Some code removed for brevity.
We have only this one model stored in Realm

```
public class DbLocation extends RealmObject {

    private static final NumberFormat format;

    static {
        format = NumberFormat.getInstance(Locale.ENGLISH);
       /** some format initialization code here **/
    }

    @PrimaryKey private String cPK;
    private int id;
    @Index private String a;
    private String b;
    private String c;
    private double d;
    private double e;
    private int f;
    private int g;
    private String h;
    private int i;
    private String j;
    private int k;
    @Nullable private RealmList<StringObject> l;
    private String m;
    private boolean n;
    private long o;

    public DbLocation() {
       // required for realm
    }

    public static DbLocation create (SomeClass model, String a, boolean n) {
        return new DbLocation(model.getId(), model.xxx()..., a, n, System.currentTimeMillis());
    }

    public DbLocation(params ..... ) {
        this.id = id;
        this.a = a;
        this.b = b;
        ....
        this.l = Utils.convertToRealmList(l /** "l" here is List<String> and this method coverts it to RealmList<StringObject> **/ );
        this.cPK = createPrimaryKey(params);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

   // rest of setter & getter

    public static String createPrimaryKey (ILocation iLocation) {
        return createPrimaryKey(iLocation ....);
    }

    public static String createPrimaryKey ( int s, double t, double u) {
        return source + "_" + format.format(t) + "_" + format.format(u);
    }
}
```

Let me know if you need any thing else and thanks for looking into it.

**Comment by stk1m1** [comment]
@AamirAbro 

Thanks for the report! It's hard to make a judgement when we only have scant details. Could you possibly update Realm version to the latest and see if the error persists? 0.88.2 is a bit dated at this point.

**Comment by Zhuinden** [comment]
Ah, when you upgrade, make sure you pay close attention to the changes in 0.89.0, those breaking changes were pretty rough.

**Comment by AamirAbro** [comment]
Okay I will try updating and would let you guys know if the problem persists.

**Comment by stk1m1** [comment]
Hi @AamirAbro, 

Has upgrading eliminated the issue you've experienced?

**Comment by stk1m1** [comment]
Hi @AamirAbro,

In case the same issue arise again, please don't hesitate to reopen this issue. We will be all ears to hear from you! Thanks!

**Comment by AamirAbro** [comment]
I have updated to latest realm and its working fine, but as I am not able to reproduce the crash so we need to release it and check for crash logs before saying any think certain.
Thanks for help and would update you guys when we release it - most probably next week.

**Comment by peshkira** [comment]
Hi @AamirAbro, @stk1m1 Have you been able to resolve this issue? I have a Samsung Galaxy Nexus 4.2.1 device and I get the same issue.

We use Realm via the gradle plugin 2.2.1 and it works like a charm on all our other devices. Any input and/or help is highly appreciated!

**Comment by beeender** [comment]
@peshkira Can you please create a new issue with your crash log and some description of your issue?

**Comment by peshkira** [comment]
Thanks for the response. We fixed the issue, it was a multidex issue.

**Comment by Zhuinden** [comment]
`MultiDex.install(this)` was missing from Application class?

**Comment by peshkira** [comment]
it was invoked too late apparently.

**Comment by ImranAtArbisoft** [comment]
I am still facing this issue and is not resolved in latest version.
**Stacktrace**
FATAL EXCEPTION: main
                                                               java.lang.VerifyError: io/realm/Realm
                                                                   at com.save.coinch.rebranding.CoinchApplication.onCreate(CoinchApplication.java:28)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1069)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4640)
                                                                   at android.app.ActivityThread.access$1300(ActivityThread.java:165)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5391)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:525)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                   at dalvik.system.NativeStart.main(Native Method)

**Code**
`Realm.init(this);
  RealmConfiguration realmConfig = new RealmConfiguration
       .Builder()
        .deleteRealmIfMigrationNeeded()
         .name("CoinchDb")
          .build();
  Realm.setDefaultConfiguration(realmConfig);`

It is working on OS version : 5.0 (LG G3)
**Not working on OS: 4.2.2 (QMobile i5)**

**Also multiDex is enabled.**

**Comment by cmelchior** [comment]
@ImranAtArbisoft VerifyError is not caused by Realm, but by something in your packaging. Most likely multidex doing something wrong or being used incorrectly as reported above.

**Comment by Zhuinden** [comment]
@ImranAtArbisoft it means you didn't extend `MultiDexApplication` class with your application class

**Comment by ImranAtArbisoft** [comment]
@Zhuinden @cmelchior Thanks, I just added line `MultiDex.install(this);` in My Application and now its working.

**Comment by imvikasrai** [comment]
I m using MultiDex.install(this); in attachBaseContext but facing the same issue.According to crashlytics here is the device information
Brand: samsung
Model: Galaxy Tab3 7.0
Orientation: Portrait
RAM free: 135.28 MB
Disk free: 3.1 GB
plat_android Operating System
Version: 4.4.2
Orientation: Portrait
Rooted: No
