### ISSUE TITLE
Decryption failed error

### ISSUE THREAD

**Issue by Snakeice** [realm/realm-java#3097]
Hello!

I have a problem and can not find a solution

stacktrace:
```
java.lang.IllegalArgumentException: Illegal Argument: Decryption failed path:  in io_realm_internal_SharedGroup.cpp line 188
	at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
	at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:95)
	at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:62)
	at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:118)
	at io.realm.BaseRealm.commitTransaction(BaseRealm.java:340)
	at io.realm.BaseRealm.commitTransaction(BaseRealm.java:327)
	at io.realm.Realm.commitTransaction(Realm.java:120)
```

in this method:

```Java
UtilsDB.getInstance ().GetRealm ().ExecuteTransaction (new.Realm.Transaction () {
            @Override
            public void run (Realm Realm) {
                for (e ProtocoloInteracoes: Interacoes) {
                    e.setLido (v);
                }
            }
        });

```

**Comment by Zhuinden** [comment]
What is your RealmConfiguration?

**Comment by stk1m1** [comment]
Hi @Snakeice 

Thanks for the issue report. If you can fill up the template with Realm version you are using and how you pass encryption key to Realm, we can help you in an accelerated manner.

There is more examples in <https://realm.io/docs/java/latest/#encryption>. We'll look forward.

**Comment by Snakeice** [comment]
the setting is this:

```JAVA
    return new RealmConfiguration
                .Builder(new File(BaseApp.getInstance().getPathDB(Boolean.FALSE)))
                .encryptionKey(UtilsSeguranca.getKey())
                .name(Constants.files.DB)
                .schemaVersion(BuildConfig.DB_VERSION)
                .modules(new InitialVersion())
                .migration(new MigrationDB())
                .build();

```


And getKey method:

```JAVA

 public static byte[] getKey() {
        String sKey = "N8S*mM4Rl{+!$@(ElL:[xE$ql6E[$<k[549J(ebTWM^A;$Ea?CSnH:^s4|li<,b3";
        final String MD5 = "MD5";
        // Create MD5 Hash
        MessageDigest digest = null;
        try {
            digest = MessageDigest
                    .getInstance(MD5);
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        assert digest != null;
        digest.update(sKey.getBytes());
        byte messageDigest[] = digest.digest();

        // Create Hex String
        StringBuilder hexString = new StringBuilder();
        for (byte aMessageDigest : messageDigest) {
            String h = Integer.toHexString(0xFF & aMessageDigest);
            while (h.length() < 2)
                h = "0" + h;
            hexString.append(h);
        }
        String geratedKEY = hexString.toString() + hexString.toString();
        return geratedKEY.getBytes();
    }

```

**Comment by Snakeice** [comment]
But it is working, only two devices are the problem..

**Comment by stk1m1** [comment]
@Snakeice 

1. Could you upgrade your Realm to latest version to see if this issue persists? 
2. Plus, I would compare the values of `getKey()` between a working device vs a non-working device to see if keys get generated as you've expected.

**Comment by Snakeice** [comment]
Sorry, I thought I had put the version of the Realm in the first post. I have 1.0.1.
Updated and changed the default method to that found on the site, and the error was eliminated ...
And the old method returns the same values on both devices.

Thank you for your help!
