### ISSUE TITLE
Adding Realm Dependency causes Error

### ISSUE THREAD

**Issue by Shubhamsinghsky** [realm/realm-java#3119]
> **Questions**: As soon i add the classpath n apply plugin , i get the following error 
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.linktop.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.linktop.demo-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "liboxygen.so"

:41:20.861 14079-14079/com.linktop.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.linktop.demo, PID: 14079
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.linktop.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.linktop.demo-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "liboxygen.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                      at java.lang.System.loadLibrary(System.java:988)
                                                                      at whealthService.OnBLEService.<clinit>(Unknown Source)
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                      at java.lang.Class.newInstance(Class.java:1606)
                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2773)
                                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:155)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

I am building a Health Device App that starts a service using some jar and so files. 
When i dont add the depencies of realm it works fine but as soon as i add and run the activity it shows this error.. Please Help i dont want to use SQLite.

#### Version of Realm and tooling
Realm version(s): 1.1.0 and also on 0.82.1

Android Studio version: 2.1.2

Which Android version and device: Lollipop API 22

**Comment by Zhuinden** [comment]
I believe you are running into this issue 

https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

You can also try loading that library using ReLinker.

**Comment by Shubhamsinghsky** [comment]
The soln :
android {
    //...
    packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
    }
    //...
}

Didnt help me.
I tested the app on 32 as well as 64 bit device , it crashes on both.

**Comment by Zhuinden** [comment]
How are you loading liboxygen.so?

**Comment by Shubhamsinghsky** [comment]
I have it in the jniLibs folder , and a healthService,jar file that has an api that calls a service that loads the .so libraries internally..  it works fine without the realm dependency.
I tried setting the usedeprecatendk=true in gradle.properties but id didnt helped..

**Comment by Shubhamsinghsky** [comment]
Shall i send you the entire project to review ?

**Comment by Zhuinden** [comment]
Technically you should send it to help@realm.io

**Comment by Shubhamsinghsky** [comment]
The whole project zipped...  Right ?

**Comment by Zhuinden** [comment]
Yeah, and explain your problem there too in the email. I hope they'll find a solution.

**Comment by beeender** [comment]
@Shubhamsinghsky since you only have `armeabi` so for other lib, you have to keep only `armeabi` for Realm as well.

Try:

```
packagingOptions {
    exclude "lib/arm64-v8a/librealm-jni.so"
    exclude "lib/armeabi-v7a/librealm-jni.so"
    exclude "lib/mips/librealm-jni.so"
    exclude "lib/x86/librealm-jni.so"
    exclude "lib/x86_64/librealm-jni.so"
}
```

To verify if everything is correct, you can open the output apk file with archive tools, and check if there are only `armeabi` so files left in the lib folder.

**Comment by Shubhamsinghsky** [comment]
I changed the buil.gradle(module) to :  

apply plugin: 'com.android.application'
apply plugin: 'realm-android'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.linktop.demo"
        minSdkVersion 18
        targetSdkVersion 18
        multiDexEnabled true
    }

    packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
        exclude "lib/armeabi-v7a/librealm-jni.so"
        exclude "lib/mips/librealm-jni.so"
        exclude "lib/x86/librealm-jni.so"
        exclude "lib/x86_64/librealm-jni.so"
    }



    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}
repositories {
    maven { url "https://jitpack.io" }
    jcenter()
}


dependencies {
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile files('libs/HealthSDK_Va0.0.4_out.jar')
    compile files('libs/libTGECG.jar')
    compile fileTree(dir: 'libs', include: ['.jar','.so'])
    compile 'com.github.medyo:fancybuttons:1.8.1'
    compile('com.mikepenz:materialdrawer:5.3.0@aar') {
        transitive = true
    }
    compile 'com.mikepenz:google-material-typeface:2.2.0.1.original@aar'
    compile 'com.android.support:design:23.4.0'
     compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'com.android.support:multidex:1.0.1'

}

But the apk's lib folder  still has files other than armeabi.
Why are the exclude statements not working ?

**Comment by Shubhamsinghsky** [comment]
This is the error i get : 

FATAL EXCEPTION: main
                                                                  Process: com.linktop.demo, PID: 29866
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.linktop.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.linktop.demo-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "liboxygen.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                      at java.lang.System.loadLibrary(System.java:988)
                                                                      at whealthService.OnBLEService.<clinit>(Unknown Source)
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                      at java.lang.Class.newInstance(Class.java:1606)
                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2773)
                                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:155)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

Note :
Whereas the liboxygen.so loads successfully without the realm dependency..

**Comment by stk1m1** [comment]
Hi @Shubhamsinghsky 

Could you share a simple project to reproduce your issue at help@realm.io please? I've tried to reproduce your issue with the gradle you provided but have not been successful. 

We'll be looking forward! Thanks!

**Comment by Shubhamsinghsky** [comment]
I had shared my entire project to help@realm.io

**Comment by stk1m1** [comment]
@Shubhamsinghsky 

Sorry. I've checked our inbox and there is nothing there. It might be that the project file was too big to be transmitted from your email provider. Plus, it would be really helpful for us if you could reduce the project to a crux where the issue persists. In that way, we can support you in an accelerated manner. We'll look forward. Thanks!

**Comment by Shubhamsinghsky** [comment]
It is working now :)
Cleaning  and building again ,the files othe than armeabi were removed and now the app works fine.
Thank you guys for such a prompt solution.. Keep it up !
( You may close the issue)
