### ISSUE TITLE
Migrate from unencrypted realm to encrypted realm

### ISSUE THREAD

**Issue by geethgubi** [realm/realm-java#3143]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

I want to migrate from unencrypted realm to encrypted realm. 

> What do you want to achieve?

#### Expected Results

> Seamless realm migration from unencrypted realm to encrypted realm

#### Actual Results

>  E.g. full stack trace with exception

Process: com.clinicloud.app, PID: 10382
                                                                    java.lang.RuntimeException: Unable to create application com.clinicloud.app.MainApp: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4331)
                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
                                                                        at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                                        at io.realm.internal.SharedGroup.<init>(SharedGroup.java:64)
                                                                        at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
                                                                        at io.realm.BaseRealm.<init>(BaseRealm.java:79)
                                                                        at io.realm.Realm.<init>(Realm.java:138)
                                                                        at io.realm.Realm.createAndValidate(Realm.java:248)
                                                                        at io.realm.Realm.createInstance(Realm.java:228)
                                                                        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
                                                                        at io.realm.Realm.getDefaultInstance(Realm.java:174)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

We already have a version of app in google play store with Unencrypted realm. But we want to move to encrypted realm. So the following method is written and called in the onCreate of Application class. 

But when Realm.getDefaultInstance is called, I am getting the above mentioned exception. 

Secenerio: The old version of app is available. The new version containing encryption code is updating now. The source code that gets called in Application class onCreate is given in #Code Sample

#### Code Sample

fun setRealmMigrationConfiguration() {

        realmConfiguration = RealmConfiguration.Builder(this)
                .schemaVersion(1)
                .migration(RealmMigrationClass())
                .build()

        Realm.setDefaultConfiguration(realmConfiguration)

        keyStore.load(null)
        val realmKey = "realmKey"

        val realmKeyFile = File("${this.filesDir}/$realmKey")

        if(keyStore.containsAlias(alias)) {
            if(!realmKeyFile.exists()) {
                keyStore.deleteEntry(alias)
            }
        }

        val encryptedRealmFileName = "default.realm.enc"

        if (!keyStore.containsAlias(alias)) {
            //Generates key pair in key store
            generateKeyPairInKeyStore(alias)

            val privateKeyEntry = keyStore.getEntry(alias, null) as KeyStore.PrivateKeyEntry
            val publicKey = privateKeyEntry.certificate.publicKey

            val key = generateKey()

            val encryptedKey = encryptKey(publicKey,key)

            realmKeyFile.writeBytes(encryptedKey)

            val unencryptedRealm = File("${this.filesDir}/default.realm")
            val encryptedRealm = File("${this.filesDir}/$encryptedRealmFileName")

            if (unencryptedRealm.exists() && !encryptedRealm.exists()) {
                val realm = Realm.getDefaultInstance()
                realm.writeEncryptedCopyTo(encryptedRealm, key)
                realm.close()

                Realm.deleteRealm(realmConfiguration)
                Realm.removeDefaultConfiguration()
                realmConfiguration = null
            }
            val realmConfiguration1 = RealmConfiguration.Builder(this)
                                        .schemaVersion(1)
                                        .migration(RealmMigrationClass())
                                        .name(encryptedRealmFileName)
                                        .encryptionKey(MessageDigest.getInstance("SHA-512").digest(key))
                                        .build()

            Realm.setDefaultConfiguration(realmConfiguration1)

            info { "Realm file1 =>${realmConfiguration1?.realmFileName}" }

            info { "Realm file3 =>${Realm.getDefaultInstance().path}" }
        } else {
            val privateKeyEntry = keyStore.getEntry(alias, null) as KeyStore.PrivateKeyEntry
            val privateKey = privateKeyEntry.privateKey

            val keyFile = realmKeyFile.readBytes()
            val buffer = decryptKey(privateKey,keyFile)

            realmConfiguration = RealmConfiguration.Builder(this)
                    .name(encryptedRealmFileName)
                    .encryptionKey(MessageDigest.getInstance("SHA-512").digest(buffer))
                    .build()

            Realm.setDefaultConfiguration(realmConfiguration)
        }
    }

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ? 1.0.0

Android Studio version: ? 2.0

Which Android version and device: ? 4.4.4 Nexus 4

**Comment by beeender** [comment]
Solved on SO
