### ISSUE TITLE
Crash on Application launch thrown by Relinker on 4.x

### ISSUE THREAD

**Issue by lisawray** [realm/realm-java#3175]
#### Goal

I'd like to run my application successfully with Realm for all users.

#### Expected Results

The application opens and loads Realm successfully.

#### Actual Results

We have reports of crashes on application start when building Realm for users on Android 4.x.

http://crashes.to/s/1a5140e4841

```Fatal Exception: java.lang.RuntimeException: Unable to create application com.genius.android.GeniusApplication: com.d.a.b: lib/armeabi-v7a/librealm-jni.so
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by com.d.a.b: lib/armeabi-v7a/librealm-jni.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary$757ca6fb(SourceFile:85)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal$62dc3a79(SourceFile:182)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary$11a583b2(SourceFile:140)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(SourceFile:1070)
       at io.realm.internal.RealmCore.loadLibrary(SourceFile:89)
       at io.realm.RealmConfiguration$Builder.(SourceFile:388)
       at com.genius.android.GeniusApplication.onCreate(SourceFile:48)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4564)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)```

#### Steps & Code to Reproduce

Of course, we can't seem to reproduce.  *sigh*.  It does seem to happen repeatedly for individual users -- an average of 5 crashes per user.  I assume the app is completely unusable for these users.

#### Code Sample

I don't think our code will be relevant here, but we do generate a split APK if that is relevant.  (I see armeabi-v7a in the stack trace)

#### Version of Realm and tooling
Realm version(s): 1.0.1

Android Studio version: 2.2 Preview 3

Which Android version and device: 4.x, see Crashlytics link for individual breakdown -- primarily one Motorola device but also Samsung and others.

**Comment by Zhuinden** [comment]
@xiphirx I wonder if I can notify a person like this.

**Comment by xiphirx** [comment]
>  but we do generate a split APK if that is relevant

Quite relevant. It is possible that your application was manually installed, and that the user installed the wrong APK for their architecture. This is what the exception is telling you in the stack trace, it cannot find the correct library .so in the APK installed on the user's device. 

You can figure out what package name installed your app via `Context.getPackageManager().getInstallerPackageName(Context.getPackageName());`, a value of `null` will signify a manual install. Typically you should see `com.android.vending` for Google Play.

P.S. In the future, it might be beneficial to exclude ReLinker from Proguard so the exception names are not obfuscated.

To whoever is a member from realm, this is not an issue with realm and this issue can be closed.

**Comment by lisawray** [comment]
Thanks @xiphirx!  That possibility hadn't occurred to me.  I'll add the check in our logging!

**Comment by beeender** [comment]
@xiphirx Big thanks for answering that! @lisawray I am closing this issue now. Please let us know if there is any help needed from our side. 
:dancers:
