### ISSUE TITLE
java.lang.IllegalArgumentException: *Object* is not part of the schema for this Realm

### ISSUE THREAD

**Issue by Coletz** [realm/realm-java#3196]
I'm trying to use kotlin and realm, and I'm getting a crash when opening my app.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.coletz.appname/com.coletz.appname.activity.Login}: java.lang.IllegalArgumentException: RealmUser is not part of the schema for this Realm
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.IllegalArgumentException: RealmUser is not part of the schema for this Realm
                                                       at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:157)
                                                       at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:80)
                                                       at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:235)
                                                       at io.realm.RealmQuery.<init>(RealmQuery.java:136)
                                                       at io.realm.RealmQuery.createQuery(RealmQuery.java:85)
                                                       at io.realm.Realm.where(Realm.java:1026)
                                                       at com.coletz.appname.Utils$Companion.getUser(Utils.kt:24)
                                                       at com.coletz.appname.activity.Login.onCreate(Login.kt:45)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

The class RealmUser:
```
import io.realm.RealmObject
import io.realm.annotations.PrimaryKey

open class RealmUser : RealmObject() {
    @PrimaryKey
    var email: String? = null
    var name: String? = null
    var surname: String? = null
}
```

the getUser function:
```
fun getUser(realm: Realm, email: String): RealmUser? {
            return realm.where<RealmUser>(RealmUser::class.java).equalTo("email", email).findFirst()
        }
```

and build.gradle (app)
```
buildscript {
    ext.kotlin_version = '1.0.3'
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
    }
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'


android {
    compileSdkVersion 24
    buildToolsVersion "24"

    defaultConfig {
        applicationId "com.coletz.appname"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "0.1"
    }
    lintOptions {
        checkReleaseBuilds false
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    // Kotlin
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    // MPChart and Realm extension
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.0-beta1'
    compile 'com.github.PhilJay:MPAndroidChart-Realm:v1.1.0@aar'
}
```

I'm probably having problem with annotation processor, there're no info about that process in the gradle console. I've tried to clean the project but nothing changed

**Comment by Zhuinden** [comment]
What version is your build.gradle tool and Android Studio? There are known issues about alpha5 acting weird.

**Comment by Coletz** [comment]
Android Studio and build.gradle are on 2.1.2 stable, I've spent 4 hours this morning to get rid of this but nothing is working

**Comment by Zhuinden** [comment]
Is it a Java/Kotlin mixed project, or a pure Kotlin project?

**Comment by Zhuinden** [comment]
Can you try running `apply plugin: 'realm-android'` *after* `apply plugin: 'kotlin-android'` (and extensions)?

**Comment by Zhuinden** [comment]
Also add 

    android {
        dexOptions {
            incremental false
        }
    }

**Comment by Coletz** [comment]
Not sure if it was a problem from the plugin order or the incremental dex option, but that two advice fixed the issue. Thanks!

**Comment by Zhuinden** [comment]
Glad I could help :smile:
