### ISSUE TITLE
java.lang.NullPointerException while building with gradle

### ISSUE THREAD

**Issue by tihomirleka** [realm/realm-java#3218]
As the title says, I get a NullPointerException when building my project with gradle in Android Studio. Below is the stacktrace. I can assume the problem is with one of my RealmObject classes, but error doesn't give me a hint which one.  I'm using Realm 1.1.0.

Can you help please?

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileBetaDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 70 more
Caused by: java.lang.NullPointerException
	at io.realm.processor.ClassMetaData.checkListTypes(ClassMetaData.java:175)
	at io.realm.processor.ClassMetaData.generate(ClassMetaData.java:118)
	at io.realm.processor.RealmProcessor.process(RealmProcessor.java:143)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 89 more

```

**Comment by Zhuinden** [comment]
What is your android build gradle tool version?

For example,

        classpath 'com.android.tools.build:gradle:2.1.2'

But these are also important:

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
```

Also your Android Studio version

**Comment by Zhuinden** [comment]
@beeender but it's weird because it's in [this line](https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java#L175) according to the source

                if (typeElement.getSuperclass().getKind() == TypeKind.NONE) {

So I guess `typeElement.getSuperclass()` is null? What does that mean?

**Comment by tihomirleka** [comment]
gradle build tool version is 
```classpath 'com.android.tools.build:gradle:2.1.2'``` and rest is
```
compileSdkVersion 23
buildToolsVersion '23.0.3'
```

I couldn't find anything online regarding this error.

**Comment by Zhuinden** [comment]
Based on source, it seems to do something with one of your `RealmObject`s that has a `RealmList` field.

Any guesses which one could be the odd one out?

**Comment by tihomirleka** [comment]
I suspect this one, but not sure where is the problem...

```
import io.realm.OrderedRealmCollection;
import io.realm.RealmList;
import io.realm.RealmModel;
import io.realm.RealmObject;
import java.util.Iterator;
import java.util.Map;

public class RealmHashMap<V extends RealmModel> extends RealmObject {

    private RealmList<RealmString> keys = new RealmList<>();
    private RealmList<V> values = new RealmList<V>();

    public RealmHashMap() {
    }

    public RealmHashMap(Map<String, V> map) {
        Iterator<Map.Entry<String, V>> it = map.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry<String, V> pair = it.next();
            keys.add(new RealmString(pair.getKey()));
            values.add(pair.getValue());
            it.remove(); // avoids a ConcurrentModificationException
        }
    }

    public RealmList<RealmString> getKeys() {
        return keys;
    }

    public void setKeys(RealmList<RealmString> keys) {
        this.keys = keys;
    }

    public RealmList<V> getValues() {
        return values;
    }

    public void setValues(RealmList<V> values) {
        this.values = values;
    }

    public void clear() {
        keys.clear();
        values.clear();
    }

    public boolean containsKey(String key) {
        return keys.indexOf(new RealmString(key)) >= 0;
    }

    public boolean containsValue(V value) {
        return values.indexOf(value) >= 0;
    }

    public String getKey(int location) {
        if (location < 0 || location > keys.size() - 1) return null;
        return keys.get(location).getVal();
    }

    public V getValue(int location) {
        if (location < 0 || location > values.size() - 1) return null;
        return values.get(location);
    }

    public V get(String key) {
        final int location = keys.indexOf(new RealmString(key));
        return location > 0 ? null : values.get(location);
    }

    public boolean isEmpty() {
        return keys.isEmpty();
    }

    public V put(String key, V value) {
        final V result;
        if (containsKey(key)) {
            final int location = keys.indexOf(new RealmString(key));
            result = values.get(location);
            values.set(location, value);
        } else {
            result = null;
            keys.add(new RealmString(key));
            values.add(value);
        }
        return result;
    }

    public void putAll(Map<String, V> map) {
        Iterator<Map.Entry<String, V>> it = map.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry<String, V> pair = it.next();
            put(pair.getKey(), pair.getValue());
            it.remove(); // avoids a ConcurrentModificationException
        }
    }

    public V remove(String key) {
        final int location = keys.indexOf(new RealmString(key));
        if (location > 0) {
            keys.remove(location);
            return values.remove(location);
        } else {
            return null;
        }
    }

    public int size() {
        return keys.size();
    }

    public OrderedRealmCollection<V> values() {
        return values;
    }
}
```

**Comment by tihomirleka** [comment]
Here is RealmString, but I used that class before introducing  RealmHashMap and it compiled OK

```
import io.realm.RealmObject;

public class RealmString extends RealmObject {
    private String val;

    public RealmString() {
    }

    public RealmString(String val) {
        this.val = val;
    }

    public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }

    @Override public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RealmString)) return false;

        RealmString that = (RealmString) o;

        return val.equals(that.val);
    }

    @Override public int hashCode() {
        return val.hashCode();
    }

    @Override public String toString() {
        return val;
    }
}
```

**Comment by tihomirleka** [comment]
It looks like RealmHashMap is the one that invokes the crash because I just created a new project and tried to add it and it failed with the same error, but I still don't understand what the problem is :|.

**Comment by Zhuinden** [comment]
Umm how do you use `RealmHashMap`?

Although I have this wild guess that the problem is that it's a generic class and also a `RealmObject`

Does Realm support generics?

**Comment by Zhuinden** [comment]
This is really similar to https://github.com/realm/realm-java/issues/2265#issuecomment-184085413

**Comment by tihomirleka** [comment]
Good question... I didn't found anywhere that they's not supported and I did looked for it in the documentation.

**Comment by tihomirleka** [comment]
Yes, looks realy similar. I'll try to remove generics and see the results.

**Comment by tihomirleka** [comment]
Yep, it passed compilation when I remove generics. I guess I'll need to make concrete classes for any specific type I need.

Anyway, thanks for the effort.

**Comment by Zhuinden** [comment]
This is clearly a bug in the Realm annotation processor though, so the Realm people will prioritize this accordingly when they see it.

**Comment by stk1m1** [comment]
@tihomirleka 
Thanks for the detailed issue report! This is now priortized and I'd like to ask which version of Realm you are using to experience this. 

@Zhuinden 
Thanks for the comments 😉

**Comment by beeender** [comment]
I don't think we can support generics in an easy way since it requires analyse the usage of generic class in the source code, and generate proper proxy (especially schema) for every different usage of the generic class. 

I will just dup this to #2265, throw a proper exception during building instead. 

Thanks a lot for the report!!!!

**Comment by Zhuinden** [comment]
@stk1m1 he uses 1.1.0

**Comment by tihomirleka** [comment]
Thanks for the replies, I ended up creating two separate classes for two different `RealmObject`s I needed in my project. Anyway, I'm not sure will it be possible to support generics in the future but it would be a real time saver. Also, since I tried to simulate `HashMap` with my class, maybe this is something Realm could implement more easily. Keep up the good work.

Cheers

**Comment by stk1m1** [comment]
@tihomirleka 

It's not likely that we're oppose to providing lean but powerful APIs with generics. But like @beeender pointed above, it takes quite a bit of resource to do so while we have plenty of higher priority issues on our plate. As this is linked in #2265, we'll keep track of it. 

Thanks for using Realm!
