### ISSUE TITLE
Object is not part of the schema for this Realm

### ISSUE THREAD

**Issue by arifinbardansyah** [realm/realm-java#3219]
how to fix it

Error:

```
07-28 02:43:17.729 29278-29278/commerce.product E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: commerce.product, PID: 29278
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{commerce.product/commerce.product.MainActivity}: io.realm.exceptions.RealmException: class commerce.product.Product is not part of the schema for this Realm.
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                   Caused by: io.realm.exceptions.RealmException: class commerce.product.Product is not part of the schema for this Realm.
                                                                      at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:217)
                                                                      at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:101)
                                                                      at io.realm.Realm.copyOrUpdate(Realm.java:1272)
                                                                      at io.realm.Realm.copyToRealm(Realm.java:727)
                                                                      at commerce.product.MainActivity.onCreate(MainActivity.java:71)
                                                                      at android.app.Activity.performCreate(Activity.java:5990)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

Model

```java
public class Product extends RealmObject {
    String _id;
    String product;
    String brand;
    RealmList< RealmString > image = new RealmList<>();

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public RealmList<RealmString> getImage() {
        return image;
    }

    public void setImage(RealmList<RealmString> image) {
        this.image = image;
    }
}


public class RealmString extends RealmObject {
    private String stringValue;

    public RealmString(){}

    public RealmString(String stringValue){
        this.stringValue =  stringValue;
    }


    public String getStringValue() {
        return stringValue;
    }

    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }
}
```

**Comment by Zhuinden** [comment]
Are you using Kotlin?

**Comment by arifinbardansyah** [comment]
no, i use java.

**Comment by arifinbardansyah** [comment]
I've uncheck instant run, but still error

**Comment by arifinbardansyah** [comment]
@Zhuinden

**Comment by stk1m1** [comment]
Hi @arifinbardansyah 

Since your is duplicated in #3139, I'm closing this for focused support. Please post your quetion over there. Thanks!

**Comment by Zhuinden** [comment]
@arifinbardansyah then Clean + Rebuild
