### ISSUE TITLE
 between() does not support queries using child object fields. 

### ISSUE THREAD

**Issue by shannavas** [realm/realm-java#3266]
RealmResults<Person> results = realm.where(Person.class).between("info.age",15,20).findAll();
   
  RealmResult <root>result = realm.where(root.class).between("child.element",max,min).findAll();

it throws 
 Caused by: java.lang.IllegalArgumentException: Illegal Argument: between() does not support queries using child object fields.
 at io.realm.internal.TableQuery.nativeBetween(Native Method)
 at io.realm.internal.TableQuery.between(TableQuery.java:169)
 at io.realm.RealmQuery.between(RealmQuery.java:880)

**Comment by cmelchior** [comment]
Yes, that is a known limitation. Hence the `IllegalArgumentException`. We are tracking it here https://github.com/realm/realm-java/issues/2204.

I'll close this issue as an duplicate, but you can follow progress in #2204.
