### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: columnIndex > available columns.

### ISSUE THREAD

**Issue by paozhuanyinyu** [realm/realm-java#3329]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

#### Goal

> What do you want to achieve?

#### Expected Results

> Using a Realm across Threads, query UserInfo
#### Actual Results

>  D/REALM: columnIndex 0 > 0 - invalid!
08-22 17:07:46.197 28302-28631/com.zhanyou.yeyeshow D/REALM: jni: ThrowingException 7, columnIndex > available columns., .
08-22 17:07:46.197 28302-28402/com.zhanyou.yeyeshow I/TEAM_CACHE: 1664/build TeamDataCache completed, team count = 0
08-22 17:07:46.197 28302-28631/com.zhanyou.yeyeshow D/REALM: Exception has been throw: columnIndex > available columns.
08-22 17:07:46.200 28302-28631/com.zhanyou.yeyeshow E/AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
                                                                      Process: com.zhanyou.yeyeshow, PID: 28302
                                                                      java.lang.ArrayIndexOutOfBoundsException: columnIndex > available columns.
                                                                          at io.realm.internal.Table.nativeGetLong(Native Method)
                                                                          at io.realm.internal.Table.getLong(Table.java:736)
                                                                          at io.realm.BaseRealm.getVersion(BaseRealm.java:491)
                                                                          at io.realm.Realm.getVersion(Realm.java:122)
                                                                          at io.realm.Realm.createAndValidate(Realm.java:234)
                                                                          at io.realm.Realm.createInstance(Realm.java:214)
                                                                          at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
                                                                          at io.realm.Realm.getInstance(Realm.java:178)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 1.2

Android Studio version: 2.1.2

Which Android version and device: Android5.1, MX5

**Comment by kneth** [comment]
Please fill out everything in the template. Without enough information, we cannot give a good answer.

**Comment by Zhuinden** [comment]
You need to provide the code that produces this problem

**Comment by beeender** [comment]
close due to no response.
