### ISSUE TITLE
No default RealmConfiguration was found. Call setDefaultConfiguration() first

### ISSUE THREAD

**Issue by donnguyen** [realm/realm-java#3336]
#### Expected Results
> Should not crash

#### Actual Results

> ```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{removed.MainActivity}: java.lang.NullPointerException: No default RealmConfiguration was found. Call setDefaultConfiguration() first
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: No default RealmConfiguration was found. Call setDefaultConfiguration() first
       at io.realm.Realm.getDefaultInstance(Realm.java:158)
       at removed.MainActivity.onCreate(MainActivity.java:73)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)```

#### Steps & Code to Reproduce

> I couldn't reproduce this on my side but a lot of crashes on production app. Just 1 more thing: this issue has happened after I upgraded to `v1.1.1` and `v1.2.0 (current version)`, it never happen before (I used to use `v1.1.0`) so I am sure everything is in place (`setDefaultConfiguration` on Application class already and registered this class on Manifest file for sure). So could you please have a look. Thanks

#### Version of Realm and tooling
Realm version(s): 1.1.1, 1.2.0

Android Studio version: 2.2 beta

Which Android version and device: SM-G9287C (6.0.1), D6603 (6.0.1), Nexus 6P (6.0.1), LGLS991 (6.0)...

**Comment by beeender** [comment]
can you share the code where the `setDefaultConfiguration()` gets called?

**Comment by donnguyen** [comment]
Sure. Here is my whole Application class:

```java
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .schemaVersion(4)
                .migration(new Migration())
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }
}
```

**Comment by Zhuinden** [comment]
Do you by chance use firebase crash reporting?

**Comment by donnguyen** [comment]
@Zhuinden No, but I am using Crashlytics

**Comment by beeender** [comment]
Did you ever call `removeDefaultConfiguration()` ?

**Comment by donnguyen** [comment]
@beeender No, I didn't.

**Comment by beeender** [comment]
can you share your apk with us?

**Comment by donnguyen** [comment]
@beeender sure, should I upload it here?

**Comment by Zhuinden** [comment]
Technically you should send it over to help[at]realm.io

**Comment by beeender** [comment]
You can upload to anywhere we can reach. Or send to help@realm.io if you want to share it privately.

**Comment by donnguyen** [comment]
@beeender @Zhuinden I have just sent APK to help@realm.io, thanks for your great support!

**Comment by Zhuinden** [comment]
@beeender can this be some kind of threading issue, that `static RealmConfiguration` is not in an AtomicReference or something?

**Comment by zaki50** [comment]
@Zhuinden `Application#onCreate()` which calls `Realm.setDefaultConfiguration()` and `Activity#onCreate()` which calls `Realm.getDefaultInstance()` are both executed on UI thread.

So it doesn't seem a thread issue.

**Comment by zaki50** [comment]
internal note: relevant apk can be found at
https://secure.helpscout.net/conversation/241988898

**Comment by donnguyen** [comment]
Hi guys, any updates on this? So many crashes on production app :|

**Comment by beeender** [comment]
Does it only happen to Android 6? Seems there was a bug in Android 6 :sweat: http://stackoverflow.com/questions/32066873/custom-application-not-created-on-android-m-final-preview

**Comment by beeender** [comment]
@donnguyen If the above is the case, maybe you can consider to call the `setDefaultConfiguration()` in the main activity as well. But you need to be careful since the API is not thread safe.

**Comment by donnguyen** [comment]
@beeender yes, maybe you're right, the issue just happens on Android 6 (6.0 and 6.0.1) but not sure on preview version or final release also. I have switched back to use Realm version `1.0.0` and the issue seems not happen anymore.

**Comment by beeender** [comment]
That is strange ... i checked the changes between `1.0.0` and `1.2.0`, didn't find any thing could be related with this issue. But anyway, I am closing this issue now. Feel free to reopen it if you still have further questions about it.
