### ISSUE TITLE
This Realm instance has already been closed, making it unusable.

### ISSUE THREAD

**Issue by zachtom** [realm/realm-java#3362]
Hi,
I have Realm implemented in my project which works fine when the application is open and running.
When I close app by pressing home button and open again the application crashes throwing above error when I switch around screens. I have seen few threads with similar issues and they suggested to have  Realm initialisation in onCreate and close to onDestroy() . But still I am  getting same issues.

I am using Fragments, So I have

```
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
       realm = Realm.getDefaultInstance();
}

Now I close like this,
@Override
    public void onDestroy()
    {
realm.close();
    }
```

When I referred here https://realm.io/docs/java/latest/#best-practices it says realm initialisation and close should be in onStart() and onStop() of Fragments.

Whats the best way forward?

here is my crash log,

```
Fatal Exception: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
       at io.realm.BaseRealm.checkIfValid(BaseRealm.java:457)
       at io.realm.CardRealmProxy.realmGet$cardName(CardRealmProxy.java:198)
       at Card.getCardName(Card.java:97)
       at cardChanged(WalletPresenter.java:345)
       at wallet.WalletFragment$2.onScrolledToPosition(WalletFragment.java:190)
       at it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow.dispatchDraw(FeatureCoverFlow.java:476)
       at android.view.View.updateDisplayListIfDirty(View.java:16464)
       at android.view.View.draw(View.java:17245)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
       at android.view.View.updateDisplayListIfDirty(View.java:16464)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
       at android.view.View.updateDisplayListIfDirty(View.java:16429)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3184)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2983)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2572)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

#### Version of Realm and tooling
Realm version(s): 1.1.1

**Comment by Zhuinden** [comment]
Honestly, I'd recommend putting them in `onCreateView()` and `onDestroyView()`.

Or go with the [retained fragment](https://github.com/Zhuinden/realm-book-example/blob/master/app/src/main/java/com/zhuinden/realmbookexample/paths/books/BooksScopeListener.java) + [manual reference counting](https://github.com/Zhuinden/realm-book-example/blob/master/app/src/main/java/com/zhuinden/realmbookexample/application/RealmManager.java) that I do for the UI thread.

**Comment by zaki50** [comment]
As @Zhuinden said, using `Fragment#onCreateView()/onDestroyView()` is a good way and I think we should mention it in out documentation. And we should avoid to use `Fragment#onCreate()/onDestroy()` since `Fragment#/onDestroy()` is never called in some cases (details are described below).

The only way to avoid that exception is not to use the `realm` instance and `RealmObject`s after closing the `Realm` instance.
If you have a chance to access those instances, you can check whether those are closed or not by using `Realm#isClosed()` or `RealmObject#isValid()`

@Zhuinden Please note that `Fragment#onDestroy()` is never called for a Fragment whose `setRetainInstance(true);` was called and which is in the fragment backstack.

**Comment by Zhuinden** [comment]
@zaki50 ah, my retained fragment solution doesn't add it to the backstack, so `onDestroy()` is called only when the Activity is finished

I've tested this before :smile:

**Comment by zachtom** [comment]
Thanks. This has fixed my issue.

**Comment by levibostian** [comment]
@zaki50, switching where I close my realm instance in Fragments from onStop() to onDestroyView() fixed this exception for me. 

Anyway we can get the docs updated to reflect this for others? Is the site open source I can do take care of it?

**Comment by Zhuinden** [comment]
@levibostian I agree, `onStart()` and `onStop()` doesn't make sense as I said above exactly 3 months ago

**Comment by egpayawal** [comment]
hi @Zhuinden. I have the same in my project. Please I need your help. Thanks. Please see below my code. 

```
BookingDao.class
public RealmBookingDetailList getRealmBookingDetails(long bookingId) {
        Realm realm = Realm.getDefaultInstance();
        RealmBookingDetailList obj = realm.where(RealmBookingDetailList.class).equalTo("BookingId", bookingId).findFirst();
        realm.close();
        return obj;
    }
```
```
BookingDataSource.class
public RealmBookingDetailList getBookingDetails(long bookingId) {
        return mBookingDao.getRealmBookingDetails(bookingId);
    }
```
```
ScanHistoryActivityPresenter.class
private void loadBookingDetails(long bookingId) {
        RealmBookingDetailList realmBookingDetail = mBookingDataSource.getBookingDetails(bookingId);

        if (realmBookingDetail != null) {
            if (!TextUtils.isEmpty(realmBookingDetail.getFirstName())) {
                mFirstName = realmBookingDetail.getFirstName();
            }

            if (!TextUtils.isEmpty(realmBookingDetail.getLastName())) {
                mLastName = realmBookingDetail.getLastName();
            }
        }
    }
```
**Below is the error from fabric:**
```
Caused by java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
       at io.realm.BaseRealm.checkIfValid(BaseRealm.java:380)
       at io.realm.RealmBookingDetailListRealmProxy.realmGet$FirstName(RealmBookingDetailListRealmProxy.java:148)
       at com.trybooking.scanapp.model.RealmBookingDetailList.getFirstName(RealmBookingDetailList.java:33)
       at com.trybooking.scanapp.presenter.ScanHistoryActivityPresenter.loadBookingDetails(ScanHistoryActivityPresenter.java:194)
       at com.trybooking.scanapp.presenter.ScanHistoryActivityPresenter.init(ScanHistoryActivityPresenter.java:64)
       at com.trybooking.scanapp.ui.activity.ScanHistoryActivity.onCreate(ScanHistoryActivity.java:61)
       at android.app.Activity.performCreate(Activity.java:6984)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2783)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2909)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by TharinduPunchihewa** [comment]
I had the same problem. after close using realm.close() it's work  Thanks.

**Comment by tfkci** [comment]
Hi there

 if (defaultRealm != null && !defaultRealm.isClosed())
{
            if (defaultRealm.where(FactUserDataRM.class).equalTo("id", theFact.getUserData().getId()).findFirst().isLiked() == b)
            {
}
}

Even I do close check, I take this fault. What could be the reason, I am totally lost

**Comment by cmelchior** [comment]
@tfkci Please create a new issue with steps on how to reproduce the problem.

**Comment by bmunkholm** [comment]
@Abena1997 Same for you: Please create a new issue with full details on how to reproduce your problem.
