### ISSUE TITLE
RealmPrimaryKeyConstraintException: Value already exists: 0

### ISSUE THREAD

**Issue by mehrdaad** [realm/realm-java#3391]
Sorry for creating a similar issue which exists on issue tracker already.
My problem is with auto increment feature of primary keys.  
Should I increment the primary key value every time I create a new record or will that be handled automatically?
my code is:  

     realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Step step = new Step();
                step.setSteps(steps);
                if (realm.where(Step.class).equalTo("date", -1).count() == 0) {
                    step.setDate(-1);
                    Log.d(TAG, "execute " + step.getDate() + " " + step.getSteps() + " " + step.id);
                    realm.copyToRealm(step);
                }
            }
        });

  Which throws ``RealmPrimaryKeyConstraintException: Value already exists: 0``  
My full stack trace is:  
``  09-04 09:14:46.234 8669-8669/com.xyz.moorche.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.xyz.moorche.android.debug, PID: 8669
                                                                             io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0
                                                                                 at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:727)
                                                                                 at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:473)
                                                                                 at io.realm.Realm.createObject(Realm.java:701)
                                                                                 at io.realm.StepRealmProxy.copy(StepRealmProxy.java:301)
                                                                                 at io.realm.StepRealmProxy.copyOrUpdate(StepRealmProxy.java:291)
                                                                                 at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:99)
                                                                                 at io.realm.Realm.copyOrUpdate(Realm.java:1292)
                                                                                 at io.realm.Realm.copyToRealm(Realm.java:720)
                                                                                 at com.xyz.moorche.android.database.RealmDatabase$3.execute(RealmDatabase.java:220)
                                                                                 at io.realm.Realm$1.run(Realm.java:1187)
                                                                                 at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                             --------- beginning of system``

I have set my primary key public, as you can see I also use ``copyToRealm`` instead of ``createObject`` but the problem persists.  
Should I increment id myself or the problem is sth else?

**Comment by cmelchior** [comment]
You need to auto-increment it yourself. You can find some ideas on how to go about it in this thread: https://github.com/realm/realm-java/issues/469

**Comment by Zhuinden** [comment]
``` java
    // in transaction
            Cat defaultCat = new Cat();
            long autoIncrementId;
            if(realm.where(Cat.class).count() > 0) {
                autoIncrementId = realm.where(Cat.class).max(CatFields.ID.getField()).longValue();
            } else {
                autoIncrementId= 0;
            }
            defaultCat.setId(++autoIncrementId);
```

**Comment by timi-codes** [comment]
Hello @Zhuinden I'm getting the same error. 
I want to be able to store data in the realm object if there is no such data or update it if it exist
Here is my code:
`mRealm.executeTransactionAsync(realm->{

                for(TradeList tradeItem : tradeLists) {
                    //Trade trade = realm.createObject(Trade.class);
                    Trade trade = realm.where(Trade.class).equalTo("SecurityID",tradeItem.getSecurityID()).findFirst();
                    trade.setMin(tradeItem.getMin());
                    trade.setMax(tradeItem.getMax());
                    trade.setBuyPrice(tradeItem.getBuyPrice());
                    trade.setSellPrice(tradeItem.getSellPrice());

                    RealmList<ChartData> charts = new RealmList<>();

                    for (TradeItem.ChartData chartData_ : tradeItem.getChart_data()){
                        ChartData chartData = realm.createObject(ChartData.class);

                        chartData.setYield(chartData_.getYield());
                        chartData.setProductID(chartData_.getProductID());
                        chartData.setClosingDate(chartData_.getClosingDate());
                        chartData.setMaturity(chartData_.getMaturity());
                        chartData.setDate(chartData_.getDate());
                        charts.add(chartData);
                    }

                    trade.setChart_data(charts);

                    trade.setDescription(tradeItem.getDescription());

                    trade.setBuyYield(tradeItem.getBuyYield());
                    trade.setSellYield(tradeItem.getSellYield());

                    trade.setDirtyprice_buy(tradeItem.getDirtyprice_buy());
                    trade.setDirtyprice_sell(tradeItem.getDirtyprice_sell());

                    trade.setProductID(tradeItem.getProductID());
                    trade.setProduct_type(tradeItem.getProduct_type());

                    //trade.setSecurityID(tradeItem.getSecurityID());
                    trade.setSecurity_balance(tradeItem.getSecurity_balance());

                    //trades.add(trade);
                    realm.copyToRealmOrUpdate(trade);
                }
           // }
        });`
Here is my error 
`  Process: com.cavidel.tradefi, PID: 31413
    io.realm.exceptions.RealmException: Async transaction failed
        at io.realm.Realm$1$2.run(Realm.java:1583)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.cavidel.tradefi.data.db.model.Trade.setMin(java.lang.String)' on a null object reference
        at com.cavidel.tradefi.data.db.AppDbHelper.lambda$setTradeItem$1(AppDbHelper.java:292)
        at com.cavidel.tradefi.data.db.-$$Lambda$AppDbHelper$mteO-IrX6VenTw-2a5iaffh87E8.execute(Unknown Source:2)
        at io.realm.Realm$1.run(Realm.java:1527)
        at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by Zhuinden** [comment]
> Trade trade = realm.where(Trade.class).equalTo("SecurityID",tradeItem.getSecurityID()).findFirst();

This line returns `null` so the next line crashes. This means trade item does not yet exist for this realm with this security ID.

**Comment by timi-codes** [comment]
how do i populate the realm object with a data if it does exist already and update if it exist?

**Comment by timi-codes** [comment]
Here is my new code 
`for(TradeList tradeItem : tradeLists) {

                    Trade trade =  realm.createObject(Trade.class,tradeItem.getSecurityID());

                   // Trade trade = new Trade();

                    trade.setMin(tradeItem.getMin());
                    trade.setMax(tradeItem.getMax());
                    trade.setBuyPrice(tradeItem.getBuyPrice());
                    trade.setSellPrice(tradeItem.getSellPrice());

                    RealmList<ChartData> charts = new RealmList<>();

                    for (TradeItem.ChartData chartData_ : tradeItem.getChart_data()){
                        ChartData chartData = realm.createObject(ChartData.class);

                        chartData.setYield(chartData_.getYield());
                        chartData.setProductID(chartData_.getProductID());
                        chartData.setClosingDate(chartData_.getClosingDate());
                        chartData.setMaturity(chartData_.getMaturity());
                        chartData.setDate(chartData_.getDate());
                        charts.add(chartData);
                    }

                    trade.setChart_data(charts);

                    trade.setDescription(tradeItem.getDescription());

                    trade.setBuyYield(tradeItem.getBuyYield());
                    trade.setSellYield(tradeItem.getSellYield());

                    trade.setDirtyprice_buy(tradeItem.getDirtyprice_buy());
                    trade.setDirtyprice_sell(tradeItem.getDirtyprice_sell());

                    trade.setProductID(tradeItem.getProductID());
                    trade.setProduct_type(tradeItem.getProduct_type());

                    //trade.setSecurityID(tradeItem.getSecurityID());
                    trade.setSecurity_balance(tradeItem.getSecurity_balance());

                    //trades.add(trade);
                    realm.insertOrUpdate(trade);
                }`


and i get this error
`     Caused by: io.realm.exceptions.RealmPrimaryKeyConstraintException: Primary key value already exists: 76 .
`

**Comment by Zhuinden** [comment]
Combine the two approaches and call createObject only if findFirst returned null

**Comment by timi-codes** [comment]
Thanks. it worked.
