### ISSUE TITLE
Problem updating my mRealmAdapter data when using a recyclerview and a RealmList

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-java#3407]
I have an activity where I am displaying some realmObject using my custom RealmAdapter. My database structure is as follows: 
```
public class User extends RealmObject {
  ...
  RealmList<Tags> userTags;
}
```
```
public class Tags extends RealmObject {
  ...
  RealmList<Results> tagResults;
}
```
```
public class Results extends RealmObject {
  ...
}
```
The desired result is to obtain all the Tags and all the containing Results from a specific User. For example:
user1 -> tag1 -> result1
user1 -> tag1 -> result2
user1 -> tag2 -> result3
user1 -> tag2 -> result4

The desired result should be: result1, result2, result3, result4.

Because of the lack of [inverse relationships](https://github.com/realm/realm-java/issues/607). I am doing it in the following way: 
```
private void loadResults(){
...
RealmList<Results> tagResults = new RealmList<>;
RealmList<Tags> userTags= user1.getTags();

if(!userTags.isEmpty){
     for (Tags tag : userTags)
      {
        tagResults.addAll(tag.getResults().where().findAll());
      }
}
mRealmAdapter = new RealmResultsAdapter(this, tagResults);
}
```

Since my database structure doesn't not allow me to create my  mRealmAdapter with RealmResults, I am not working directly with Realm, but with a copy of the objects. So, I can't set a RealmChangeListener to see when new objects have been created. 

Now, the problem is that the user can go to a child activity, without destroying the parent activity due to activity transitions, where new tagResults will be added to the database. So, when the user goes back to the previous activity, results wont be updated. 

To solve this, I have created a flag that is to true in onStop method. Then, my onResume method looks like this: 

```
@Override
    protected void onResume(){
        super.onResume();
        if (flagUpdatetagResultList){
            loadResults();
        }
    }
```

This solve the problem with the recyclerview and shows the new Result RealmObject that has been created. The problem is that when the user is deleting (onItemDismiss) the new Result RealmObject, I get an indexoutofboundsexception.

I have done several things assuming we have 5 results objects after going back: 
1) 
```
onResume(){
...
mRealmAdapter.getItemCount(); // return 4 results.
mRealmAdapter.getData().size();// return 4 results.
loadResults();
mRealmAdapter.getItemCount(); // return 5 results.
mRealmAdapter.getData().size();// return 5 results.
...

onItemDismiss{
getData().size() // return 4
}
```

2) 
```
private void loadResults(){
...
RealmList<Results> tagResults = new RealmList<>;
RealmList<Tags> userTags= user1.getTags();

if(!userTags.isEmpty){
     for (Tags tag : userTags)
      {
        tagResults.addAll(tag.getResults().where().findAll());
      }
}

if(flagUpdateArticlesList){
            mRealmAdapter.updateData(tagResults);
        } else mRealmAdapter = new RealmResultsAdapter(this, tagResults);
}
```

This one throws the following exception: 
`
java.lang.RuntimeException: Unable to resume activity {Screens.DetailActivity}: java.lang.NullPointerException: Attempt to read from field 'io.realm.HandlerController io.realm.BaseRealm.handlerController' on a null object reference
                                                                                        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                                        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                     Caused by: java.lang.NullPointerException: Attempt to read from field 'io.realm.HandlerController io.realm.BaseRealm.handlerController' on a null object reference
                                                                                        at io.realm.RealmRecyclerViewAdapter.removeListener(RealmRecyclerViewAdapter.java:171)
                                                                                        at io.realm.RealmRecyclerViewAdapter.updateData(RealmRecyclerViewAdapter.java:139)
                                                                                        at Screens.DetailActivity.getProjectArticles(DetailActivity.java:229)
                                                                                        at Screens.DetailActivity.loadArticles(DetailActivity.java:212)
                                                                                        at Screens.DetailActivity.onResume(DetailActivity.java:148)
                                                                                        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
                                                                                        at android.app.Activity.performResume(Activity.java:6312)
                                                                                        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                                        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
`

I have run out of ideas to solve it. 

Thanks in advance

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.1.0

Which Android version and device: API 21 +

**Comment by Zhuinden** [comment]
If you use the answer I specified here http://stackoverflow.com/questions/39327905/how-do-i-obtain-all-the-realmobjects-from-a-realmlist-which-is-within-another-re/39329907#39329907 then this won't come up

**Comment by beeender** [comment]
By creating `RealmList` with `RealmList<Results> tagResults = new RealmList<>;`, you are just create a non-managed `RealmList` which cannot be auto updated and it is just a normal list.

If you want to do in that way, you don't have to use `RealmRecyclerViewAdapter` at all since you don't benefit any. Just write your own adapter.

Or you could use what @Zhuinden said.

But it is true that we should throw earlier when creating the `RealmRecyclerViewAdapter` with a non-managed `RealmList`.

**Comment by ojarabo** [comment]
Hi @Zhuinden and @beeender. Thanks for both answers and sorry for my late reply.

@Zhuinden my intention was to do it in that way, but since the Realm team has inverse relationships in the backlog, I preferred to spend the less possible time refactoring the code until Reaml come with an standard solution. However, I have already spent more time than the time I would have spent if I had done what you suggested at the first place. So, I will follow your advice. Thanks. 

@beeender I understand what you explain. However, I don't really understand why, even if I set my mRealmAdapter to null, reload the results in the RealmList and do `mRealmAdapter = new RealmResultsAdapter(this, tagResults);`, the data is still not updated. I am just curious if I am doing something wrong, because I am creating a new object containing the new results. 

Thanks again for your quick answer. I really appreciate.

**Comment by Zhuinden** [comment]
@ojarabo the `RealmRecyclerViewAdapter` cannot display unmanaged `RealmList<T>`, and a `RealmList` is managed only if it's a many relation of a managed RealmObject.

I'm not sure how the timeline will work after 2.0, but I wouldn't really **wait** for backlinks because in my estimation it would be at least 4 months (the query syntax is in design stage, after all).

**Comment by ojarabo** [comment]
@Zhuinden thanks for the clarification. 
Ok then, I will adapt the code to your solution. 
Thanks again to both of you.
