### ISSUE TITLE
OrderDB is not part of the schema for this Realm

### ISSUE THREAD

**Issue by Ivanzar** [realm/realm-java#3439]
Help! it's work for realm 0.84.1 but doesn't work for realm 1.3.0

```java
import io.realm.RealmObject;

public class OrderDB extends RealmObject {

    private String title;
    private String subtitle;
    private long id;
    private double price;
    private String date;
    private String text;

    ////SETTERS\\\\\


    public void setText(String text) {
        this.text = text;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setDate(String data) {
        this.date = data;
    }

    ////GETTERS\\\\\


    public String getText() {
        return text;
    }

    public String getTitle() {
        return title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public String getDate() {
        return date;
    }

    public long getId() {
        return id;
    }

    public double getPrice() {
        return price;
    }
}

```
```java
import android.content.Context;
import io.realm.Realm;
import io.realm.RealmConfiguration;

public class OrderDBUtil {

    public void addOrder(Context context, final double price, final String title, final String subtitle,
                         final String date, final long id)
    {
        Realm realm =
                Realm.getInstance(
                        new RealmConfiguration.Builder(context)
                                .name("order.realm")
                                .build()
                );

        realm.beginTransaction();
                OrderDB order = realm.createObject(OrderDB.class);
                order.setPrice(price);
                order.setTitle(title);
                order.setSubtitle(subtitle);
                order.setDate(date);
                order.setId(id);
        realm.commitTransaction();
    }

}
```

build.gradle
```gradle
apply plugin: 'com.android.application'


android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "ivanzar.cameraclient"
        minSdkVersion 17
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:design:24.2.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'io.realm:android-adapters:1.3.0'
//    compile 'io.realm:realm-android:0.84.1'
}

```
Error:
```
FATAL EXCEPTION: main
                                                        Process: ivanzar.cameraclient, PID: 7568
                                                        java.lang.IllegalArgumentException: OrderDB is not part of the schema for this Realm
                                                                        at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:132)
                                                                        at io.realm.internal.modules.CompositeMediator.copyOrUpdate(CompositeMediator.java:96)
                                                                        at io.realm.Realm.copyOrUpdate(Realm.java:1164)
                                                                        at io.realm.Realm.copyToRealm(Realm.java:737)
                                                                        at ivanzar.cameraclient.db.OrderDBUtil.addOrder(OrderDBUtil.java:30)
                                                                        at ivanzar.cameraclient.fragment.OrderFragment.onCreateView(OrderFragment.java:52)
                                                                        at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:833)
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:949)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:744)
```

**Comment by Zhuinden** [comment]
You need to clean and rebuild the project after you update Realm from such an old version to the new version

**Comment by Zhuinden** [comment]
...oh and more importantly, you should add `Realm 1.2.0` as a dependency, see here:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:1.2.0" //<-- this line
    }
}
```

And then apply plugin

```
apply plugin: 'com.android.application'
apply plugin: 'realm-android' // this line

android {
```

**Comment by zaki50** [comment]
As @Zhuinden said, setup instruction changed around 1.0.

Please see https://realm.io/docs/java/latest/#installation for the detail.

**Comment by Ivanzar** [comment]
Thank @Zhuinden   @zaki50 . I found bug. I install android-adapter xD

**Comment by Zhuinden** [comment]
Glad we could help :smile: 

@zaki50 technically it was 0.88.0, but yes
