### ISSUE TITLE
Unable to create application lib/armeabi-v7a/librealm-jni.so

### ISSUE THREAD

**Issue by blackkara** [realm/realm-java#3447]
#### Goal

To find a solution for abi related problems

#### Expected Results

To run all split versions  of app successfully 

#### Actual Results
[Crashlytics http://crashes.to/s/25d21237c1a](http://crashes.to/s/25d21237c1a)

`Fatal Exception: java.lang.RuntimeException: Unable to create application com.blackkara.mockation.MockerApp: com.b.a.b: lib/armeabi-v7a/librealm-jni.so
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3957)
       at android.app.ActivityThread.access$1300(ActivityThread.java:123)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1185)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)`

#### Version of Realm and tooling
Realm version(s):  **1.2.0**

Android Studio version: **2.1.3**

Which Android version and device: **Related values could be seen in the Crashlytics above link** 

#### My Question
I saw a related link https://github.com/realm/realm-java/issues/3175 about this issue, but they are saying that user(s) trying to install an split version of app on wrong device manually.

1. Does converting to universal app instead of split version make sense ?
2. After first step, all devices on market can open the app ?

**Comment by beeender** [comment]
Discussion in #3484

**Comment by Mihir3646** [comment]
Try this, might be helpful.
https://realm.io/docs/java/latest/#faq-librealm-jni
For detail:
https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html

**Comment by omidraha** [comment]
Hi,
I think, I have the same issue for one of my client.

**Message:**
```
RuntimeExceptionandroid.app.ActivityThread in handleBindApplication
fatalUnable to create application org.***.app.MainApp: b.e.a.b: librealm-jni.so
```

**Info:**

Realm Version: 5.9.0

Android Version: 6.0.1
  _Version | 6.0.1 (MMB29M release-keys)
  Kernel Version | Linux version 3.4.0-perf-g7e91e8f (and@AABM) (gcc version 4.8 (GCC) ) 2 SMP PREEMPT Wed Feb 17 14:44:15 CST 2016_

Device: HTC Desire EYE Arch: armeabi-v7a

**Traceback:**

```
b.e.a.b: librealm-jni.so
    at b.e.a.a.a(ApkLibraryInstaller.java:37)
    at b.e.a.d.c(ReLinkerInstance.java:15)
    at b.e.a.d.a(ReLinkerInstance.java:5)
    at b.e.a.c.a(ReLinker.java:2)
    at b.e.a.c.a(ReLinker.java:1)
    at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:3)
    at io.realm.Realm.initializeRealm(Realm.java:3)
    at io.realm.Realm.init(Realm.java:1)
    at org.**.app.MainApp.onCreate(MainApp.java:6)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1026)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5099)
    at android.app.ActivityThread.access$1600(ActivityThread.java:150)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1464)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:168)
    at android.app.ActivityThread.main(ActivityThread.java:5885)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

java.lang.RuntimeException: Unable to create application org.**.app.MainApp: b.e.a.b: librealm-jni.so
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5102)
    at android.app.ActivityThread.access$1600(ActivityThread.java:150)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1464)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:168)
    at android.app.ActivityThread.main(ActivityThread.java:5885)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```
