### ISSUE TITLE
List<E> to RealmList<E>

### ISSUE THREAD

**Issue by Hesamedin** [realm/realm-java#3486]
Hi and sorry if this is stupid question but I'm trying to figure out what's the problem in last 3-4 hours.

I have a RealmManaget class that contains a `save` method.
````java    
    public void save(final List<PointOfInterest> pointOfInterestList) {
        if (mRealm == null || pointOfInterestList == null || pointOfInterestList.isEmpty()) {
            return;
        }

        mRealm.executeTransaction(new Realm.Transaction() { // <= line 154
            @Override
            public void execute(Realm realm) {
                RealmList<PointOfInterest> poiList = new RealmList<>(pointOfInterestList.toArray(
                        new PointOfInterest[pointOfInterestList.size()]));
                realm.insertOrUpdate(poiList);
            }
        });
    }
```

I have a Test class that tries to test this method.
```java
    @Test
    public void shouldVerifyCRUD()
    {
        List<PointOfInterest> poiList = getCollectionOfPOIs();

        // Create list elements
        RealmPOIManager.getInstance().save(poiList); // <= line 112
    ....
    }

    private List<PointOfInterest> getCollectionOfPOIs()
    {
        List<PointOfInterest> poiList = new ArrayList<>(3);

        PointOfInterest poi1 = new PointOfInterest();
        poi1.setUid("1");

        PointOfInterest poi2 = new PointOfInterest();
        poi2.setUid("2");

        PointOfInterest poi3 = new PointOfInterest();
        poi3.setUid("3");

        poiList.add(poi1);
        poiList.add(poi2);
        poiList.add(poi3);

        return poiList;
    }
```

This is part of my model class.
```java
@Parcel
@RealmClass
public class PointOfInterest implements RealmModel {
    public static final String REALM_KEY_UID = "uid";

    @Required // Throw exception if BookingId is `null`
    @PrimaryKey
    String uid;

    ....
```

I get following error log after I run the Test.
```
java.lang.NullPointerException
	at io.realm.BaseRealm.beginTransaction(BaseRealm.java:337)
	at io.realm.Realm.beginTransaction(Realm.java:122)
	at io.realm.Realm.executeTransaction(Realm.java:1087)
	at com.my.package.db.dao.RealmPOIManager.save(RealmPOIManager.java:154)
	at com.my.package.sdk.db.dao.RealmPOIManagerTest.shouldVerifyCRUD(RealmPOIManagerTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1873)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:773)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:57)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)


Process finished with exit code 255
```

Any idea would be appreciated. Thanks.

**Comment by Zhuinden** [comment]
Realm doesn't work in unit tests, only instrumentation tests

**Comment by Hesamedin** [comment]
Thanks @Zhuinden. I'm following your sample at https://github.com/realm/realm-java/blob/master/examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleRealmTest.java
This sample resides in `test` folder and not `androidTest`, that's why I thought I'm able to unit test it.
This is bad that I see I'm not able to unit test it :(

**Comment by Zhuinden** [comment]
Technically that unit test verifies that the right methods were called on the mock, but the real methods of the Realm don't work on the JVM outside of Android.
