### ISSUE TITLE
Too many open files path: /data/data/com.application.zomato.base/files/default.realm.lock

### ISSUE THREAD

**Issue by sonuzomato** [realm/realm-java#3493]
Facing the same issue like https://github.com/realm/realm-java/issues/3197 and followed the steps as mentioned in that issue but still getting this error

Process: com.application.zomato.base:remote, PID: 16908
                                                                                    io.realm.exceptions.RealmIOException: Failed to access: . open("/data/data/com.application.zomato.base/files/default.realm.lock") failed: Too many open files path: /data/data/com.application.zomato.base/files/default.realm.lock
                                                                                        at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                                                        at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
                                                                                        at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
                                                                                        at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
                                                                                        at io.realm.BaseRealm.<init>(BaseRealm.java:86)
                                                                                        at io.realm.Realm.<init>(Realm.java:135)
                                                                                        at io.realm.Realm.createAndValidate(Realm.java:233)
                                                                                        at io.realm.Realm.createInstance(Realm.java:214)
                                                                                        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
                                                                                        at io.realm.Realm.getDefaultInstance(Realm.java:160)
                                                                                        at com.application.zomato.base.helpers.RealmHelper.insertOrUpdate(RealmHelper.java:54)
                                                                                        at com.application.zomato.base.contentProvider.CPWrapper.updateSharedPrefs(CPWrapper.java:30)
                                                                                        at com.application.zomato.base.contentProvider.CPWrapper.updateSharedPrefs(CPWrapper.java:35)
                                                                                        at com.application.zomato.base.modules.factory.ParseDevice.isBaseMasterDevice(ParseDevice.java:171)
                                                                                        at com.application.zomato.base.connections.socket.SocketServerService.performTask(SocketServerService.java:474)
                                                                                        at com.application.zomato.base.connections.socket.SocketServerService.access$700(SocketServerService.java:62)
                                                                                        at com.application.zomato.base.connections.socket.SocketServerService$ServerPost.run(SocketServerService.java:464)
                                                                                        at java.util.Timer$TimerImpl.run(Timer.java:284)

**this is the output after doing the RealmUtils thing:**
09-26 15:08:05.743 2879-3066/com.application.zomato.base:remote E/realm-error: total: 5 instance(s). /data/data/com.application.zomato.base/files/default.realm(TYPED_REALM) has 5 instance(s). /data/data/com.application.zomato.base/files/default.realm(DYNAMIC_REALM) has 0 instance(s).

**Comment by Zhuinden** [comment]
What version is this? This should have been fixed in 1.1.1

**Comment by sonuzomato** [comment]
I tried both versions 1.1.1 and 1.2.0. It works fine with most of the devices except this one.
http://www.posiflexindia.com/en-global/Product/products/Item/XT-2614Q

**Comment by kneth** [comment]
The website seems to either down or very slow. Can you provide us with details? Details like CPU, memory, version of Android?

**Comment by sonuzomato** [comment]
I am sharing the screenshots having device information. 
https://drive.google.com/file/d/0B5F-NIP21oU8NFA5Z1FISzJkdE0/view?usp=sharing
CPU Main: armeabi-v7a
Processor: ARMV7 rev 3 (v7I) quad-core 
Android version: 4.4.2
RAM: 1595 MB

**Comment by kneth** [comment]
@sonuzomato Thank for the info.

Each process can open have a limited number of files open. Question is, do you have other files open too? As network connections (sockets) also count, you should also take that into consideration. I know it is not answer, just something to check in your app.

**Comment by sonuzomato** [comment]
Yes I am using sockets and other stuff that open file but I am closing it wisely. For now I am reducing the number of threads that I am using. Let's see if that helps. What you suggest?

**Comment by kneth** [comment]
Closing files and sockets wisely is definitely a good idea. Since you only have 5 Realm instances, you must have many open files/sockets. Maybe you can check which files are open (see `/proc/*PID*/fd` where `*PID*` is the process ID).

**Comment by sonuzomato** [comment]
Its working fine after I closed all the files that were open and reduced the number of threads in the app. Right now I am using Realm 2.0. No issue faced till now. I think I can close the issue.

**Comment by Zhuinden** [comment]
@sonuzomato make sure you use 2.0.1, and not 2.0.0

**Comment by sonuzomato** [comment]
Okay! I will use that
Thanks :)
