### ISSUE TITLE
Exceptions in Custom loggers crash JNI

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3528]
Correction: Was caused by a Custom Logger that crashed, but we should provide a much better exception in that case.

```
art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI GetStringChars called with pending exception 'java.lang.IllegalArgumentException' thrown in unknown throw location
art/runtime/check_jni.cc:65]     in call to GetStringChars
art/runtime/check_jni.cc:65]     from long io.realm.internal.SharedRealm.nativeCreateConfig(java.lang.String, byte[], byte,boolean, boolean, boolean, boolean, java.lang.String, java.lang.String)

art/runtime/check_jni.cc:65]   native: #08 pc 00055915  /data/app/com.invoice2go.dev-1/lib/arm/librealm-jni.so (???)
art/runtime/check_jni.cc:65]   native: #09 pc 0001f537  /data/app/com.invoice2go.dev-1/lib/arm/librealm-jni.so (Java_io_realm_internal_SharedRealm_nativeCreateConfig+54)
art/runtime/check_jni.cc:65]   native: #10 pc 006df8f7  /data/dalvik-cache/arm/data@app@com.invoice2go.dev-1@base.apk@classes.dex (Java_io_realm_internal_SharedRealm_nativeCreateConfig__Ljava_lang_String_2_3BBZZZZLjava_lang_String_2Ljava_lang_String_2+218)
art/runtime/check_jni.cc:65]   at io.realm.internal.SharedRealm.nativeCreateConfig(Native method)
art/runtime/check_jni.cc:65]   at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:166)
art/runtime/check_jni.cc:65]   at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:155)
```

From this configuration in Kotlin:

```
RealmConfiguration.Builder()
                        .name(realmName)
                        .modules(myModule)
                        .deleteRealmIfMigrationNeeded()
                        .build()
```

**Comment by beeender** [comment]
i am making changes on loggers, will fix this together.
