### ISSUE TITLE
copyToRealmOrUpdate fails with RealmPrimaryKeyConstraintException: Value already exists

### ISSUE THREAD

**Issue by chrisolsen** [realm/realm-java#3593]
#### Goal

The first insertion of the data works fine, but upon restarting the app the data syncing throws the RealmPrimaryKeyConstraintException exception.

#### Actual Results

```
io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: ahJkZXZ-Y2hyaXNjYW1wLTEzMTlyDAsSCHByb2dyYW1zDA
                                                                                at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:664)
                                                                                at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:435)
                                                                                at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:387)
                                                                                at io.realm.Realm.createObjectInternal(Realm.java:865)
                                                                                at io.realm.Realm.createObject(Realm.java:845)
```

#### Code Sample

```java
Response<List<ApiContract.ProgramCache>> resp = Endpoints.getProgramsApi(this).getAllPrograms().execute();
if (resp.isSuccessful()) {
    realm.beginTransaction();
    for (ApiContract.ProgramCache p : resp.body()) {
        ProgramCache model = realm.createObject(ProgramCache.class, p.key);
        model.createdAt = p.createdAt;
        model.description = p.description;
        model.level = p.level;
        model.name = p.name;
        model.photoUrl = p.photoUrl;
        for (String tag : p.tags) {
            model.tags.add(new Tag(tag));
        }

        // realm.insertOrUpdate(model); // fails with same error
        realm.copyToRealmOrUpdate(model);
    }
    realm.commitTransaction();
}
   
```

#### Version of Realm and tooling
Realm version(s): ?
2.0.1

Android Studio version: ?
2.2

Which Android version and device: ?
4.2.1 Samsung Nexus 4

**Comment by Sirrah** [comment]
This seems to be correct. By calling `ProgramCache model = realm.createObject(ProgramCache.class, p.key);` you're asking Realm to create a new instance with an already existing primary key.

In this case you could either create a new instance using a normal constructor:
```
    realm.beginTransaction();
    for (ApiContract.ProgramCache p : resp.body()) {
        ProgramCache model = new ProgramCache();
        model.id = p.key;
        ...
        // realm.insertOrUpdate(model); // fails with same error
        realm.copyToRealmOrUpdate(model);
    }
    realm.commitTransaction();
```

If the primary key already exists, Realm will update the existing value with the new values.

Also see, f.e. #1061

**Comment by chrisolsen** [comment]
Thanks for the help @Sirrah 

Making the change you suggested works as hoped for. Sorry for the false report.
