### ISSUE TITLE
Distinct values in nested queries

### ISSUE THREAD

**Issue by jimitpatel** [realm/realm-java#3631]
I have the following RealmObject classes

```
public class NewCategory extends RealmObject {
    @PrimaryKey
    public long category_id;
    public RealmList<NewFilter> filterObject;
}
```

And the other

```
public class NewFilter extends RealmObject {

    @PrimaryKey
    public long filter_id;
    public String name;
    @Index
    public String filterType;

    @Index
    public long categoryId;
}
```

Now while querying

```
RealmResults<NewCategory> categoryList = realm.where(NewCategory.class)
                .equalTo("category_id", getCategory_id())
                .distinct("filterObject.filterType");
```

I am getting error as below -

```
FATAL EXCEPTION: main
                                                                       Process:  PID: 22598
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{Activity}: java.lang.IllegalArgumentException: Field name 'filterObject.filterType' does not exist.
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                        Caused by: java.lang.IllegalArgumentException: Field name 'filterObject.filterType' does not exist.
                                                                           at io.realm.RealmQuery.getAndValidateDistinctColumnIndex(RealmQuery.java:1446)
                                                                           at io.realm.RealmQuery.distinct(RealmQuery.java:1336)
                                                                           at getDistinctFilterType(NewCategory.java:396)
                                                                           at (Activity.java:469)
                                                                           at (Activity.java:345)
                                                                           at (Activity.java:125)
                                                                           at android.app.Activity.performCreate(Activity.java:6664)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

In short, it's not supporting nested query with distinct or may be I am not using it properly.

The query I am trying to run is something like this:

`SELECT DISTINCT filterType FROM NewCategory a, NewFilter b WHERE a.category_id = b.categoryId AND a.category_id = 100`

**Comment by Zhuinden** [comment]
What version of Realm is this on?

**Comment by jimitpatel** [comment]
I have recently started using realm. And using 1.2.0 version

**Comment by Zhuinden** [comment]
Seems to be caused by https://github.com/realm/realm-java/issues/1906

Solution: have `NewFilter` per `NewCategory` (no primary key on new filter), and have an object link (`NewCategory category;` field) set up in your filter to `NewCategory`, then you can do

    RealmResults<NewFilter> filterList = realm.where(NewFilter.class)
                .equalTo("categoryId", getCategory_id())
                .distinct("filterType");

**Comment by jimitpatel** [comment]
Cool this solved my issue. I faced issue with duplicate values while inserting, but then used the solution by [ @vuhung3990](https://github.com/realm/realm-java/issues/469). Then it worked. Thanks a lot. Closing it
