### ISSUE TITLE
io.realm.exceptions.RealmException class XXX.UserInfo is not part of the schema for this Realm.

### ISSUE THREAD

**Issue by yygutn** [realm/realm-java#3656]
![image](https://cloud.githubusercontent.com/assets/8274198/19512419/613aa1c6-961e-11e6-89ad-ade28ff564bb.png)

![image](https://cloud.githubusercontent.com/assets/8274198/19512429/6c32d9d6-961e-11e6-9325-c4dd88310628.png)

![image](https://cloud.githubusercontent.com/assets/8274198/19512438/7fd60706-961e-11e6-9f28-87e4c8271565.png)

![image](https://cloud.githubusercontent.com/assets/8274198/19512475/a87310a0-961e-11e6-97e2-aac97c7d7843.png)

how to fix it?

**Comment by Zhuinden** [comment]
Could this be because of https://github.com/realm/realm-java/issues/3448 ?

**Comment by zaki50** [comment]
@yygutn 
What version of Realm are you using?

**Comment by yygutn** [comment]
@zaki50 
the latest version 2.0.2

**Comment by zaki50** [comment]
If you are using `InstantRun`, could you disable it and clean the project?
There are many problems around `Instant Run` for now.

**Comment by yygutn** [comment]
@zaki50 
it's sure i closed the instant run and clean the project and rebuild it, but it dose not work.

**Comment by zaki50** [comment]
Can I see the stacktrace?

**Comment by yygutn** [comment]
@zaki50 
`io.realm.exceptions.RealmException: class com.ree.net.netBean.UserInfo is not part of the schema for this Realm.
    at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:241)
    at io.realm.DefaultRealmModuleMediator.getTableName(DefaultRealmModuleMediator.java:118)
    at io.realm.RealmSchema.getTable(RealmSchema.java:296)
    at io.realm.Realm.checkHasPrimaryKey(Realm.java:1470)
    at io.realm.Realm.copyToRealmOrUpdate(Realm.java:903)
    at com.ree.presenter.LoginPresenter$saveUserInfo$1.execute(LoginPresenter.kt:60)
    at io.realm.Realm.executeTransaction(Realm.java:1254)
    at com.ree.presenter.LoginPresenter.saveUserInfo(LoginPresenter.kt:59)
    at com.ree.presenter.LoginPresenter.access$saveUserInfo(LoginPresenter.kt:19)
    at com.ree.presenter.LoginPresenter$login$1.call(LoginPresenter.kt:35)
    at com.ree.presenter.LoginPresenter$login$1.call(LoginPresenter.kt:19)
    at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:81)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.ree.net.netBean.UserInfo.class
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:83)
	... 10 more`

**Comment by kneth** [comment]
Please try to add `@RealmClass` to your model classes: https://realm.io/docs/java/latest/#kotlin

**Comment by beeender** [comment]
@yygutn Hope https://github.com/realm/realm-java/issues/3656#issuecomment-255695018 solved your issue. Feel free to reopen this issue if needed. Thanks! 😄

**Comment by Kharlos** [comment]
I have the same error with my kotlin class 

01-09 15:38:08.657 25742-25742/com.example.peruapps1.cajaarequipa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.peruapps1.cajaarequipa, PID: 25742
    io.realm.exceptions.RealmException: 'class com.example.peruapps1.cajaarequipa.menuItems.account.model.ServiceEntity' is not part of the schema for this Realm.
        at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:232)
        at io.realm.DefaultRealmModuleMediator.getSimpleClassNameImpl(DefaultRealmModuleMediator.java:81)
        at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:71)
        at io.realm.RealmSchema.getTable(RealmSchema.java:177)
        at io.realm.Realm.delete(Realm.java:1627)
        at com.example.peruapps1.cajaarequipa.menuItems.account.model.ServiceEntity$Companion$delete$1.execute(ServiceEntity.kt:48)
        at io.realm.Realm.executeTransaction(Realm.java:1431)
        at com.example.peruapps1.cajaarequipa.menuItems.account.model.ServiceEntity$Companion.delete(ServiceEntity.kt:47)
        at com.example.peruapps1.cajaarequipa.menuItems.payment.presenter.PresenterPaymentImpl$onSuccess$1.run(PresenterPaymentImpl.kt:59)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
what should i do?

**Comment by Zhuinden** [comment]
Are you applying `kotlin-kapt`?

**Comment by Kharlos** [comment]
Thanks i apply kotlin-android and kotlin-android-extensions before realm and that's all kapt I didn't apply it because I'm using butterknife ty

**Comment by Zhuinden** [comment]
> and that's all kapt I didn't apply it because I'm using butterknife ty

Time to apply `kotlin-kapt` and make it work with ButterKnife otherwise this will never work :smile:
