### ISSUE TITLE
copyOrUpdate() throws Illegal Argument: This field is not nullable (String)

### ISSUE THREAD

**Issue by MariusBoepple** [realm/realm-java#3680]
#### Goal
We're using Realm in a library project. For synchronization, we're using a SyncAdapter. In the synchronization process, we update a list of Trips. The name of the start address may be `null` locally or it should be updated with `null`.

#### Expected Results

The `String` field `start_address_name` is updated accordingly.

#### Actual Results
The crash is pretty rare. We got 6 crashes in the last week with a few hundred synchronizations a day.

The crash occurs only after we put everthing in a remote process.

Stack Trace:
````
#0. Crashed: SyncAdapterThread-229: 0 0 0x0000000000000000
       at io.realm.internal.UncheckedRow.nativeSetNull(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.setNull(UncheckedRow.java:264)
       at io.realm.TripRealmProxy.realmSet$start_address_name(TripRealmProxy.java:731)
       at io.realm.TripRealmProxy.update(TripRealmProxy.java:4883)
       at io.realm.TripRealmProxy.copyOrUpdate(TripRealmProxy.java:3937)
       at io.realm.ExampleAppModuleMediator.copyOrUpdate(ExampleAppModuleMediator.java:191)
       at io.realm.Realm.copyOrUpdate(Realm.java:1455)
       at io.realm.Realm.copyToRealmOrUpdate(Realm.java:904)
       at com.example.app.data.DataBase.storeTrip(DataBase.java:410)
       at com.example.app.data.DataBase.storeTrips(DataBase.java:425)
       at com.example.app.data.DataStore.getTrips(DataStore.java:463)
       at com.example.app.sync.SyncAdapter.syncTrips(SyncAdapter.java:441)
       at com.example.app.sync.SyncAdapter.syncComplete(SyncAdapter.java:145)
       at com.example.app.sync.SyncAdapter.onPerformSync(SyncAdapter.java:103)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)

--

Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: This field is not nullable.
       at io.realm.internal.UncheckedRow.nativeSetNull(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.setNull(UncheckedRow.java:264)
       at io.realm.TripRealmProxy.realmSet$start_address_name(TripRealmProxy.java:731)
       at io.realm.TripRealmProxy.update(TripRealmProxy.java:4883)
       at io.realm.TripRealmProxy.copyOrUpdate(TripRealmProxy.java:3937)
       at io.realm.ExampleAppModuleMediator.copyOrUpdate(ExampleAppModuleMediator.java:191)
       at io.realm.Realm.copyOrUpdate(Realm.java:1455)
       at io.realm.Realm.copyToRealmOrUpdate(Realm.java:904)
       at com.example.app.data.DataBase.storeTrip(DataBase.java:410)
       at com.example.app.data.DataBase.storeTrips(DataBase.java:425)
       at com.example.app.data.DataStore.getTrips(DataStore.java:463)
       at com.example.app.sync.SyncAdapter.syncTrips(SyncAdapter.java:441)
       at com.example.app.sync.SyncAdapter.syncComplete(SyncAdapter.java:145)
       at com.example.app.sync.SyncAdapter.onPerformSync(SyncAdapter.java:103)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```
#### Steps & Code to Reproduce

Cannot reproduce...

#### Code Sample
The SyncAdapter is running in a separated process, like the rest of the library. The trip which should be updated may have it's `start_address_name` updated with `null`. Also the field could be `null` already.

DataBase:
```java
static void storeTrip(@NonNull Trip trip) {
        Realm realm = Realm.getInstance(MyApp.getRealmConfig());
        realm.beginTransaction();

        // Make it storable (convert some fields to byte[]).
        trip.makeStorable();

        // Check if trip exists locally.
        Trip localTrip = realm.where(Trip.class)
                .equalTo(Trip.REMOTE_ID, trip.getRemoteId())
                .findFirst();

        // If trip does not exist, create it locally.
        if (localTrip == null) {
            // Generate a new local ID.
            trip.setLocalId(UUID.randomUUID().toString().toUpperCase());
            trip.setFinished(true);

            // Copy the trip to Realm.
            realm.copyToRealm(trip);

        } else {
            // Keep the local ID.
            trip.setLocalId(localTrip.getLocalId());

            // Update the trip in Realm.
            realm.copyToRealmOrUpdate(trip);

        }
        // Here's the crash:
        realm.commitTransaction();
        realm.close();
    }
```
Trip:
```java
@RealmClass
public class Trip implements RealmModel, Parcelable {
    public static final String REMOTE_ID = "remote_id";

    @PrimaryKey
    private String local_id;
    private String start_address_name, start_address_street, ...
```

#### Version of Realm and tooling
Realm version(s): `2.0.2`

Realm sync feature enabled: no

Android Studio version: `2.2.2`

Which Android version and device: `6.0`, `6.0.1` (Samsung, Sony, Huawei)

**Comment by cmelchior** [comment]
Hi @MariusBoepple 
Realm Java currently doesn't support multiple processes fully yet: https://realm.io/docs/java/latest/#realm-files-cannot-be-accessed-by-concurrent-processes

**Comment by MariusBoepple** [comment]
I thought it's working as long as I'm using the same process everywhere? I discovered that the `process=":remote"` tag was missing in the `<application>` element and I got `Realm.init(this)` in the applications `onCreate()`. May this be the cause?

**Comment by cmelchior** [comment]
Yes, if all access happens from the same process it should be fine. `Realm.init()` needs to be called in the same process, although I would expect more severe errors than the one your reported if this wasn't done.

**Comment by MariusBoepple** [comment]
We got more than 10 issues similar to this one, which occurred just 1 or 2 times (#3679):
```
- IllegalArgumentException: type mismatch. Was LIST, expected [BOOLEAN]
- Encrypted interprocess sharing is currently unsupported
- Failure when converting short string to UTF-16 error_code = 2; retcode = 0
- IllegalArgumentException: native Realm type: 11
- ArrayIndexOutOfBoundsException: columnIndex > available columns
- IllegalArgumentException: Field name '...' does not exist
- IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
- IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
```
Could the missed `process` attribute be the cause of all these errors?

**Comment by Zhuinden** [comment]
If you're calling `Realm.init(this) ` from the application instance, that would explain this issue.

**Comment by cmelchior** [comment]
Most of them yes. The underlying Realm file is actually process safe, but our API's on top are not (yet). This especially mean that all errors related to schemas are likely a result of interprocess interactions.

```
- IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
- IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
``

These two should not be to the best of my knowledge though, but then again we haven't really done serious interprocess testing yet.

**Comment by MariusBoepple** [comment]
There was a reason why I did not add the `process` attribute to the application element of the library: our app which is using the library should run in the default process 😄  I moved `Realm.init()` to the service's `onCreate()` (the service runs in the remote process). The application class is no longer used for anything. I hope it's getting better now.

**Comment by cmelchior** [comment]
Ok. I'll close this issue then. Feel free to reopen if the issue persists.
