### ISSUE TITLE
Caused by: io.realm.exceptions.RealmIOException: Failed to access: . open

### ISSUE THREAD

**Issue by zhangwenjia616** [realm/realm-java#3684]
Caused by: io.realm.exceptions.RealmIOException: Failed to access: . open("/data/data/com.zwj/files/default.realm.management/log_access") failed: No space left on device path: /data/data/com.zwj/files/default.realm.management/log_access
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
	at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
	at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
	at io.realm.BaseRealm.<init>(BaseRealm.java:86)
	at io.realm.Realm.<init>(Realm.java:135)
	at io.realm.Realm.createAndValidate(Realm.java:233)
	at io.realm.Realm.createInstance(Realm.java:214)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
	at io.realm.Realm.getDefaultInstance(Realm.java:160)

**Comment by cmelchior** [comment]
Hi @zhangwenjia616 The device seems to have run out of space as indicated by the exception message. Not much we can do about that?

**Comment by Zhuinden** [comment]
Consider compacting the Realm when you close the application, and also consider checking if you close EVERY realm instance that you open on background threads.

**Comment by zhangwenjia616** [comment]
Ok. Thank you guys.
