### ISSUE TITLE
RealmError: Unrecoverable error. Bad transaction

### ISSUE THREAD

**Issue by thuat26** [realm/realm-java#3702]
#### Goal

Fix bug
#### Expected Results

No crash
#### Actual Results

``` java

io.realm.exceptions.RealmError: Unrecoverable error. Bad transaction log in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 210
                                                                          at io.realm.internal.SharedRealm.nativeRefresh(Native Method)
                                                                          at io.realm.internal.SharedRealm.refresh(SharedRealm.java:281)
                                                                          at io.realm.HandlerController.realmChanged(HandlerController.java:450)
                                                                          at io.realm.HandlerController.handleMessage(HandlerController.java:121)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                          at dalvik.system.NativeStart.main(Native Method)

```
#### Steps & Code to Reproduce

I don't know where and when it happened exactly.
#### Version of Realm and tooling

Realm version(s): 2.1.0

Realm sync feature enabled: yes

Android Studio version: 2.2.2

Which Android version and device: Android 4.4.4 Samsung SM-G360H

**Comment by cmelchior** [comment]
Bad transaction log could indicate problems with the file somehow.
I see you are using Sync. Note that you cannot open an old Realm in Sync mode. You need to move all data there. Trying to open an old Realm as syncable will result in the error you are seeing.

If that is not the case, is it something you can reproduce?

**Comment by Zhuinden** [comment]
Do you use `begin/commitTransaction()` or `executeTransaction()`?

**Comment by kneth** [comment]
I'm closing the issue. Don't hesitate to reopen or create new issue if you keep experience the problem.

**Comment by GitGal** [comment]
Hello!
I have the same issue on realm 2.3.0

The database is running encrypted.
There are alot of processes running and manipulating the database.
It is the background processes that get this error I have not seen it in main thread yet but there is no commits running on main thread.
Both commitTransaction and executeTransaction generates this Bad transaction error.

Happy debugging! :-D

Here are some stacktraces!

io.realm.exceptions.RealmError: Unrecoverable error. Bad transaction log in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 212
	at io.realm.internal.SharedRealm.nativeRefresh(Native Method)
	at io.realm.internal.SharedRealm.refresh(SharedRealm.java:285)
	at io.realm.HandlerController.realmChanged(HandlerController.java:451)
	at io.realm.HandlerController.handleMessage(HandlerController.java:122)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

--------------

io.realm.exceptions.RealmError: Unrecoverable error. Bad transaction log in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 113
	at io.realm.internal.SharedRealm.nativeBeginTransaction(Native Method)
	at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:223)
	at io.realm.BaseRealm.beginTransaction(BaseRealm.java:328)
	at io.realm.Realm.beginTransaction(Realm.java:125)

--------------

io.realm.exceptions.RealmError: Unrecoverable error. Bad transaction log in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 113
	at io.realm.internal.SharedRealm.nativeBeginTransaction(Native Method)
	at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:223)
	at io.realm.BaseRealm.beginTransaction(BaseRealm.java:328)
	at io.realm.Realm.beginTransaction(Realm.java:125)
	at io.realm.Realm.executeTransaction(Realm.java:1299)

**Comment by kneth** [comment]
@GitGal Can't tell for sure but you might been hit by a bug in the encryption layer. We have a fix (https://github.com/realm/realm-core/pull/2465) and we hope to be able to release it soon.

**Comment by GitGal** [comment]
@kneth Ok hopefully it will fix it. :-)

**Comment by GitGal** [comment]
Hello I tried upgrading to 3.0.0 still had the same problem so now I downgraded to 0.87.4
and this stopped occuring.

**Comment by Zhuinden** [comment]
Any chance of 1.2.0 not exhibiting this problem?

**Comment by GitGal** [comment]
@Zhuinden I don't know we uppgraded from 0.87.4 -> 2.3.0 -> 3.0.0 end reverted to 0.87.4 as it was the last known to be stable.
So yes there could be a chance that 1.2.0 is not having this problem but I have not tested.
