### ISSUE TITLE
ByteCodeModifier do not modify ModelClass annotated with RealmClass

### ISSUE THREAD

**Issue by lujiajing1126** [realm/realm-java#3721]
Realm version(s): 2.0.2

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: OnePlus One A0001 Android 5.1.1

I am writing a Android Library which contains all the dependencies, so I use local jars

Then, I manually add `android-apt` plugin to simply use `io.realm:realm-transformer`

In the library scope `build.gradle` , I use `realm-android-library` and `realm-annotations` jars

```
apply plugin: 'com.android.library'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion ANDROID_BUILD_SDK_VERSION as int
    buildToolsVersion ANDROID_BUILD_TOOLS_VERSION

    defaultConfig {
        minSdkVersion ANDROID_BUILD_MIN_SDK_VERSION as int
        targetSdkVersion ANDROID_BUILD_TARGET_SDK_VERSION as int
        versionCode VERSION_CODE as int
        versionName VERSION_NAME
    }

    publishNonDefault true

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "VERSION", "\"${VERSION_NAME}\""
        }
        debug {
            buildConfigField "String", "VERSION", "\"1.0.0-rc\""
        }
    }
}

repositories {
    jcenter()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    apt 'io.realm:realm-annotations:2.0.2'
    apt 'io.realm:realm-annotations-processor:2.0.2'
    apt 'io.realm:realm-transformer:2.0.2'
}

apt {
    arguments {
        resourcePackageName android.defaultConfig.applicationId
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
    }
}
```

My Model Class:

```
package com.wosai.pushservice.pushsdk.model;

import java.util.Date;

import io.realm.RealmModel;
import io.realm.annotations.PrimaryKey;
import io.realm.annotations.RealmClass;
import io.realm.internal.Keep;

/**
 * Created by megrez on 2016/10/24.
 */
@Keep
@RealmClass
public class MessageModel implements RealmModel {
    public static final String COL_ID = "id";
    public static final String COL_READ = "isRead";
    public static final String COL_CREATE_AT = "createdAt";

    @PrimaryKey
    public String id;
    public String content;
    public boolean isRead;
    public long expiry;
    public Date createdAt;
}
```

The processor actually run because the `MessageModelRealmProxy` and `MessageModelRealmProxyInterface` are generated, but the `MessageModel` is not modified which should be modified to implements ProxyInterface according to https://github.com/realm/realm-java/blob/v2.0.2/realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy#L131-L134

so when I run the application, a cast exception occur

```
            System.err  W  java.lang.ClassCastException: com.wosai.pushservice.pushsdk.model.MessageModel cannot be cast to io.realm.g
                         W      at io.realm.f.b(MessageModelRealmProxy.java:571)
                         W      at io.realm.f.a(MessageModelRealmProxy.java:560)
                         W      at io.realm.PushSdkModuleMediator.copyOrUpdate(PushSdkModuleMediator.java:118)
                         W      at io.realm.i.a(Realm.java:1455)
                         W      at io.realm.i.a(Realm.java:884)
                         W      at com.wosai.pushservice.pushsdk.model.MessageStorage$1.call(MessageStorage.java:40)
                         W      at com.wosai.pushservice.pushsdk.model.MessageStorage$1.call(MessageStorage.java:35)
                         W      at rx.internal.operators.a.a(OnSubscribeDefer.java:44)
                         W      at rx.internal.operators.a.call(OnSubscribeDefer.java:33)
                         W      at rx.a.b(Observable.java:7463)
                         W      at rx.a.a(Observable.java:7243)
                         W      at com.wosai.pushservice.pushsdk.service.WosaiPushService.a(WosaiPushService.java:160)
                         W      at com.wosai.pushservice.pushsdk.service.WosaiPushService.a(WosaiPushService.java:57)
                         W      at com.wosai.pushservice.pushsdk.service.WosaiPushService$2$1.a(WosaiPushService.java:255)
                         W      at com.wosai.pushservice.pushsdk.service.WosaiPushService$2$1.call(WosaiPushService.java:252)
                         W      at rx.a$3.a(Observable.java:7257)
                         W      at rx.c.a.a(SafeSubscriber.java:104)
                         W      at rx.internal.b.e$1.a(ScalarSynchronousObservable.java:41)
                         W      at rx.internal.b.e$1.call(ScalarSynchronousObservable.java:30)
                         W      at rx.a.b(Observable.java:7463)
                         W      at rx.a.a(Observable.java:7243)
                         W      at com.wosai.pushservice.pushsdk.service.WosaiPushService$2.onReceive(WosaiPushService.java:252)
                         W      at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:889)
                         W      at android.os.Handler.handleCallback(Handler.java:739)
                         W      at android.os.Handler.dispatchMessage(Handler.java:95)
                         W      at android.os.Looper.loop(Looper.java:139)
                         W      at android.app.ActivityThread.main(ActivityThread.java:5302)
                         W      at java.lang.reflect.Method.invoke(Native Method)
                         W      at java.lang.reflect.Method.invoke(Method.java:372)
                         W      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                         W      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

**Comment by Zhuinden** [comment]
Byte code transformer is done by applying a Gradle plugin, not via APT.

**Comment by lujiajing1126** [comment]
@Zhuinden so how can i manually call that gradle plugin without being injecteed with extra compile files such as `realm-android-library` which is done in https://github.com/realm/realm-java/blob/master/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy

**Comment by Zhuinden** [comment]
Currently your Realm proxy class names are consumed by proguard too. 

You should apply following proguard statement :

      -keepnames public class * extends io.realm.RealmObject

And I think you'll need to register your own Gradle plugin which adds the Realm Transformer but doesn't add the dependencies.

**Comment by lujiajing1126** [comment]
Yep, obviously rewrite the plugin is an option.

Another question is why direct accessing the field of the model returns null, while I can use `realmGet$id` method to get the `id`, is that something wrong with the `proguard` rules like you mentioned above ?

```
#realm
-keep class io.realm.annotations.RealmModule
-keep class io.realm.RealmResults
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**
-keep interface io.realm.RealmCollection { *; }
-keep interface io.realm.OrderedRealmCollection
-keep class io.realm.PushSdkModuleMediator { *; }
-keep class io.realm.RealmObject
-keep interface io.realm.RealmModel

-keepclasseswithmembernames class io.realm.internal.** {
    native <methods>;
}
```

**Comment by Zhuinden** [comment]
The Realm-Transformer runs exactly to replace all direct field access with `realmGet$field` and `realmSet$field`, this is because the proxies read the field directly from the Realm

**Comment by lujiajing1126** [comment]
@Zhuinden Thx! I've solved the problem.
