### ISSUE TITLE
Unrecoverable error

### ISSUE THREAD

**Issue by BeginsDesign** [realm/realm-java#3727]
#### Code Sample

```java

// init 
 public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .directory(Environment.getExternalStoragePublicDirectory("realm"))
                .schemaVersion(1)
                .name("hm.realm")
                .build();
        Realm.setDefaultConfiguration(RealmConfig.config);
    }
}
-----------------------------------------------------------
//use
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Realm realm = Realm.getDefaultInstance();
}

```
#### Exception:
```java
FATAL EXCEPTION: main
Process: demo.com.android, PID: 20677
io.realm.exceptions.RealmError: Unrecoverable error. Operation not permitted in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp li
    at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
    at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
    at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
    at io.realm.Realm.getDefaultInstance(Realm.java:211)
    at demo.com.android.MainActivity.onCreate(MainActivity.java:41)
    at android.app.Activity.performCreate(Activity.java:5433)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
    at android.app.ActivityThread.access$900(ActivityThread.java:164)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5377)
    at java.lang.reflect.Method.invokeNative(Native Method)

                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at dalvik.system.NativeStart.main(Native Method)

```

#### Version of Realm and tooling
Realm version(s): 2.1.1

Realm sync feature enabled:?

Android Studio version: 2.2.2

Which Android version and device:   android version 4.4.2   , device samsung galaxy tabpro

**Comment by Zhuinden** [comment]
Have you obtained Runtime Permission to write in external storage?

**Comment by BeginsDesign** [comment]
yes.

```java
//manifest
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="demo.com.android">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:supportsRtl="true"
        android:name=".MyApplication"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".NestedActivity"/>
    </application>
</manifest>
```
@Zhuinden

**Comment by Zhuinden** [comment]
**Runtime** permission: http://stackoverflow.com/a/33162451/2413303

**Comment by Zhuinden** [comment]
...nevermind about Runtime permission, the phone is 4.4.2.

That's a problem. @zaki50 ?

**Comment by BeginsDesign** [comment]
If do not specify a directory does not throw excetption
```java
new RealmConfiguration.Builder()
              .directory(Environment.getExternalStoragePublicDirectory("realm"))
```

**Comment by beeender** [comment]
Same problem with #3713 , close and dup to it
