### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state

### ISSUE THREAD

**Issue by goa** [realm/realm-java#3731]
I get the following:

```
io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1763
                      at io.realm.internal.TableQuery.nativeHandoverQuery(Native Method)
                      at io.realm.internal.TableQuery.handoverQuery(TableQuery.java:541)
                      at io.realm.RealmQuery.handoverQueryPointer(RealmQuery.java:2252)
                      at io.realm.HandlerController.updateAsyncQueries(HandlerController.java:408)
                      at io.realm.HandlerController.realmChanged(HandlerController.java:444)
                      at io.realm.HandlerController.handleAsyncTransactionCompleted(HandlerController.java:167)
                      at io.realm.Realm$2$1.run(Realm.java:1384)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

From what I can tell, it sometimes occurs in this part of my code:

```
RealmAsyncTask transaction = realm.executeTransactionAsync((Realm.Transaction) bgRealm -> {
            RealmResults<UnitDownloadStatus> statuses = bgRealm
                    .where(UnitDownloadStatus.class).findAll();
            for (UnitDownloadStatus status : statuses) {
                status.deleteFromRealm();
            }
        });
```

My version is 2.1.1.

**Comment by cmelchior** [comment]
Hi @goa 
Is it something you can reproduce? Ideally in a sample project?

**Comment by goa** [comment]
It is always reproducible, however I cannot isolate that part of the code
right now because we are near a very important deadline in our project. I
currently fixed it by using Realm differently, however I will try to create
a sample project in a couple of weeks when I will have more time.

I know the bug report isn't very helpful right now. Sorry I could not do
more. I find that Realm is a great tool and want to help make it better.

**Comment by kneth** [comment]
@goa We'll looking forward to see a sample project. And good luck with your deadlines.

**Comment by kneth** [comment]
@goa Did you have time for create a small project for us?

**Comment by kneth** [comment]
I close the issue. @goa Please reopen or create a new issue when you have had time to do a small project.
