### ISSUE TITLE
com.getkeepsafe.relinker.SystemLibraryLoader.loadPath java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/user/0/package/app_lib/librealm-jni.so" >= file size: 0 >= 0

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3757]
#### Goal

> What do you want to achieve?

Probably load Realm.

#### Expected Results

Load Realm

#### Actual Results

```
Package: [REDACTED]
Version Code: [..]
Version Name: [..]
Android: 6.0.1
Android Build: MMB29K.N910CXXS2DPJ1
Manufacturer: samsung
Model: SM-N910C
Thread: main-1
CrashReporter Key: 63B28CC8-8EF5-FD20-3C56-1FFBDCF9A88ED1B02433
Start Date: Mon Nov 07 19:21:27 GMT+01:00 2016
Date: Mon Nov 07 19:21:27 GMT+01:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/user/0/[REDACTED]/app_lib/librealm-jni.so" >= file size: 0 >= 0
	at java.lang.Runtime.load(Runtime.java:332)
	at java.lang.System.load(System.java:1069)
	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:200)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:140)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:89)
	at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:352)
	at [...].AppConfig.initializeDefaultRealmConfig(AppConfig.java:46)
	at [...].AppConfig.<init>(AppConfig.java:40)
	at [...].CustomApplication.onCreate(CustomApplication.java:199)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6317)
	at android.app.ActivityThread.access$1800(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```
#### Steps & Code to Reproduce

This crash happened in 0.88.0-SNAPSHOT on some user's phone, this is the first one to have ever sent this error.

#### Code Sample

It's just a normal `Realm.getInstance()` call in `CustomApplication.onCreate()`. No migration, no encryption.

#### Version of Realm and tooling
Realm version(s): 0.88.0-SNAPSHOT

Realm sync feature enabled: No

Which Android version and device: 6.0.1, Samsung SM-N910C

---------------

My guess goes for the issue that in `Application.onCreate()`, bad things can happen, and can execute multiple times as a result of a `:remote` broadcast receiver. Honestly, I just wanted to have an issue marked for this strange error message.

**Comment by rczhang13028** [comment]
@Zhuinden excuse me, I don't know why the issue closed. How do you deal whit this issue ?  I have same problem in realm version 3.3.1

**Comment by Zhuinden** [comment]
@rczhang13028 I haven't seen this in a while, but I didn't really do anything with it... I figured it was obsolete because the version specified is quite old.

**Comment by bmunkholm** [comment]
@rczhang13028 Please create another issue with all relevant information please.

**Comment by rczhang13028** [comment]
@Zhuinden Thank you for your reply.

**Comment by rczhang13028** [comment]
@bmunkholm Sorry.Because i do not have complete bug report. when i have complete bug report, i will create another issue.Thank you.
