### ISSUE TITLE
how to solve this problem???

### ISSUE THREAD

**Issue by foreverxiongtao** [realm/realm-java#3770]
FATAL EXCEPTION: main
                                                                   Process: com.xuxian.market, PID: 11023
                                                                   java.lang.UnsatisfiedLinkError: Native method not found: io.realm.internal.SharedRealm.nativeInit:(Ljava/lang/String;)V
                                                                       at io.realm.internal.SharedRealm.nativeInit(Native Method)
                                                                       at io.realm.internal.SharedRealm.initialize(SharedRealm.java:53)
                                                                       at io.realm.Realm.init(Realm.java:193)
                                                                       at com.xuxian.market.MainActivity.onCreate(MainActivity.java:24)
                                                                       at android.app.Activity.performCreate(Activity.java:5245)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                       at dalvik.system.NativeStart.main(Native Method)
11-10 14:12:04.773 11023-11023/com.xuxian.market I/Process: Sending signal. PID: 11023 SIG: 9

**Comment by Zhuinden** [comment]
Are you using ABI Splits?

Consider not using ABI splits.

Also, do you by chance have multiple Realm versions in your project at the same time? Because then you shouldn't.

And finally, is there a chance that you have another native library which only provides armeabi?

**Comment by foreverxiongtao** [comment]
but i used the lower version of realm, such as  1.2.0 ,it  works well .

**Comment by kneth** [comment]
Which device do you use?

**Comment by zaki50** [comment]
@foreverxiongtao Realm Java 1.2.0 contains `armeabi` binary, but 2.x does not (it contains only `armeabi-v7a` for 32 bit arm).

**Comment by Zhuinden** [comment]
This issue needs to get fixed for this  https://github.com/realm/realm-java/issues/3506

**Comment by kneth** [comment]
I hope we can solve this issue (and #3506) in one of the next releases.

**Comment by cmelchior** [comment]
I'm not sure this is an architecture mismatch, since the native code has been loaded. It looks a bit similar to https://github.com/realm/realm-java/issues/3775 though. @foreverxiongtao We need more information in order to debug this. 

- What version of Realm are you trying to upgrade to?
- Have you tried with `2.3.0-SNAPSHOT`? : https://github.com/realm/realm-java#using-snapshots
- Are you using ABI splits?
- Do you app contain other libraries with native code.

**Comment by kneth** [comment]
I am closing the issue. @foreverxiongtao if you have any updates, don't hesitate to reopen or create new issue.
