### ISSUE TITLE
Error is not part of the schema for this Realm

### ISSUE THREAD

**Issue by pedrohenriquerls** [realm/realm-java#3786]
I create a project using Kotlin, Realm and Retrofit, but every time I run on emulator this error appears:

#### Stacktrace
```java

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.poupacerto.app, PID: 2451
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.poupacerto.app/com.poupacerto.app.ui.activities.SplashActivity}: java.lang.IllegalArgumentException: User is not part of the schema for this Realm
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.IllegalArgumentException: User is not part of the schema for this Realm
                      at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:172)
                      at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:90)
                      at io.realm.RealmSchema.getTable(RealmSchema.java:296)
                      at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:316)
                      at io.realm.RealmQuery.<init>(RealmQuery.java:138)
                      at io.realm.RealmQuery.createQuery(RealmQuery.java:87)
                      at io.realm.Realm.where(Realm.java:1213)
                      at com.poupacerto.app.services.DatabaseService.query(DatabaseService.kt:17)
                      at com.poupacerto.app.data.repos.UserRepo.getCurrent(UserRepo.kt:25)
                      at com.poupacerto.app.ui.presenters.SigninPresenter.loggedIn(SigninPresenter.kt:9)
                      at com.poupacerto.app.ui.activities.SplashActivity.init(SplashActivity.kt:37)
                      at com.poupacerto.app.ui.activities.SplashActivity.onCreate(SplashActivity.kt:32)
                      at android.app.Activity.performCreate(Activity.java:5231)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
```
I read a lot about errors like this and my gradle.build file looks right, he is based on your's kotlin-example anyway, I will put him below.

#### Code Sample
``` groovy
buildscript {
  ext.kotlin_version = '1.0.5'

  repositories {
    mavenCentral()
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}


apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'realm-android'

android {
  signingConfigs {
    debug {
      keyAlias 'androiddebugkey'
      keyPassword 'android'
      storeFile file('../keystore/debug.keystore')
      storePassword 'android'
    }
  }
  compileSdkVersion 24
  buildToolsVersion "24.0.0"

  defaultConfig {
    applicationId "com.poupacerto.app"
    minSdkVersion 16 //JellyBean
    targetSdkVersion 21 //Lollipop
    maxSdkVersion 24
    versionCode 112
    versionName "1.2"

    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
  }
  buildTypes {
    release {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      buildConfigField "String", "SERVER_URL", '"http://poupacerto.com/api/v1"'
    }
    debug {
      signingConfig signingConfigs.debug
      buildConfigField "String", "SERVER_URL", '"http://localhost:3000/api/v1"'
    }
  }
  sourceSets {
    main.java.srcDirs = ['src/main/kotlin', 'src/main/java']
  }
  testOptions {
    unitTests.returnDefaultValues = true
  }
  // Incremental builds currently doesn't work with Kotlin
  dexOptions {
    incremental false
//    preDexLibraries false
  }
}

repositories {
  mavenCentral()
  maven { url "https://jitpack.io" }
}

kapt {
  generateStubs = true
}


dependencies {
  compile fileTree(dir: 'libs', include: ['*.jar'])

  compile 'com.android.support:appcompat-v7:24.1.1'
  compile 'com.android.support:design:24.1.1'
  compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

  compile 'com.google.android.gms:play-services-auth:9.+'

  //Kodein
  compile 'com.github.salomonbrys.kodein:kodein:3.1.0'

  //Realm
//  compile "io.realm:realm-android-library:0.87.4@aar"
//  compile "io.realm:realm-annotations:0.87.4"
//  kapt "io.realm:realm-annotations:0.87.4"
//  kapt "io.realm:realm-annotations-processor:0.87.4"

  //Picasso
  compile 'com.squareup.picasso:picasso:2.5.2'
  //Retrofit
  compile 'com.squareup.retrofit2:retrofit:2.1.0'
//  compile 'com.squareup.okhttp3:okhttp:3.4.1'
//  compile 'com.squareup.okhttp3:logging-interceptor:3.1.2'
  compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
  compile 'com.squareup.retrofit2:converter-gson:2.1.0'
  //RXJava
  compile 'io.reactivex:rxandroid:1.2.1'
// Because RxAndroid releases are few and far between, it is recommended you also
// explicitly depend on RxJava's latest version for bug fixes and new features.
  compile 'io.reactivex:rxjava:1.1.6'

  testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
  // Testing
  testCompile 'junit:junit:4.12'
  testCompile "org.robolectric:robolectric:3.0"
  testCompile "org.mockito:mockito-core:1.10.19"
  testCompile 'org.robolectric:shadows-support-v4:3.0'

  testCompile "org.powermock:powermock-module-junit4:1.6.4"
  testCompile "org.powermock:powermock-module-junit4-rule:1.6.4"
  testCompile "org.powermock:powermock-api-mockito:1.6.4"
  testCompile "org.powermock:powermock-classloading-xstream:1.6.4"
//  testCompile 'com.squareup.okhttp3:mockwebserver:3.4.1'

  androidTestCompile 'com.android.support.test:runner:0.5'
  // Set this dependency to use JUnit 4 rules
  androidTestCompile 'com.android.support.test:rules:0.5'
  // Set this dependency to build and run Espresso tests
  androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
  configurations.all {
    resolutionStrategy.force 'com.android.support:support-annotations:23.1.1'
  }
}
```

#### Version of Realm and tooling
Realm version(s): 2.2.0
Gradle: 2.14.0
Gradle plugin: 2.2.2
Android Studio version: 2.2.2
Instant run: disabled
Which Android version: 21

**Comment by Zhuinden** [comment]
If you use Kotlin, you shouldn't use `apply plugin: 'com.neenbedankt.android-apt'`, you should use kapt by removing `apply plugin: 'com.neenbedankt.android-apt'`

Can you try that?

**Comment by pedrohenriquerls** [comment]
@Zhuinden thanks a lot for the fast reply and to solved my problem :+1: 
thanks a lot you are awesome :)
