### ISSUE TITLE
BadVersionException in TableQuery.cpp line 1131

### ISSUE THREAD

**Issue by siebeprojects** [realm/realm-java#3802]
Hi,

I am using Realm version 2.2.0 in an Android app.
I am using a Nexus 5 and Honor 7 lite. Both with android 6.0.1
Same crash happens on both phones.

I am using findFirstAsync and findAllAsync queries including storeOrUpdate queries in different threads.
Also I am removing change listeners in the UI Thread but only when the RealmObjects are valid.

If I switch between my activities several times I get this Native JNI Exception from Realm. 

I am trying to debug and pinpoint what I am doing wrong and how I should instead use Realm so it doesn't generate these native exceptions. Any help from your end in which direction I should look at would be appreciated.

I.e. does it have to do more with transactions and storing, or more with findAll and findFirst calls ?

Kind regards,

Siebe

STACKTRACE 

Fatal Exception: java.lang.Error: io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1131
       at io.realm.AndroidNotifier.throwBackgroundException(AndroidNotifier.java:138)
       at io.realm.RealmQuery.closeSharedRealmAndSendEventToNotifier(RealmQuery.java:2201)
       at io.realm.RealmQuery.access$000(RealmQuery.java:62)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2141)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1131
       at io.realm.internal.TableQuery.nativeFindWithHandover(TableQuery.java)
       at io.realm.internal.TableQuery.findWithHandover(TableQuery.java:446)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2124)
       at io.realm.RealmQuery$5.call(RealmQuery.java:2115)
       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by cmelchior** [comment]
BadVersionException is a race condition between the worker thread doing the query and the UI thread receiving the result. I thought we got rid of them all a few versions ago, so it is really unfortunate if we missed a case.

Normally it could happen if you mix asynchronous queries and synchronous writes, so I would start looking there.

Are you able to share the app/code where you see this?

**Comment by Zhuinden** [comment]
@cmelchior technically you fixed it in 0.88.3, but the object store's notifications seem to have reintroduced it

**Comment by siebeprojects** [comment]
Hi,

Unfortunately I cannot give you the code but I when I have time I can make a sample app that hopefully causes the error.

Indeed I am doing synchronized writes in background Handlers with Messages and doing async findFirst and findAll queries with onChange listeners to listen for the changes in the UI Thread.
I have managed to get it not crashing anymore while still using async change listeners and sync writes in background handlers.

I need to test but I think this may have caused some havoc.

During the same executing cycle of a Handler I did the following.
1. Background handler stores in a transaction content to a RealmObject (Object obtained with findFirst in the transaction) and writes it with storeOrUpdate.

2. The same background handler continues to execute in hte same cycle and  accesses content of the newly stored RealmObject.

3. I do believe that the error occurs when another background Handler writes in a transaction the RealmObject (newly obtained with findFirst in a different transaction) while number 2 is still executing.

I have this feeling that the Realm instance or object may not be valid anymore.
But I could be very much wrong. Other then that, I like very much the speed of Realm. 

Siebe

**Comment by kneth** [comment]
@siebeprojects Did you have a chance to create a small project showing this error?

**Comment by siebeprojects** [comment]
No unfortunately not as I cannot seem to steadily reproduce it.
It still happens occasionally but I cannot pinpoint where or how.

**Comment by kneth** [comment]
@siebeprojects The error is different but your description sounds a bit like the one in #3891.

**Comment by cmelchior** [comment]
This will most likely be fixed by #3834.

**Comment by beeender** [comment]
#3834 is merged to master. will be fixed in `v2.4.0`.
