### ISSUE TITLE
RealmObject class is not part of the schema for this Realm

### ISSUE THREAD

**Issue by nikiJava** [realm/realm-java#3817]
I have ran into a problem with Realm database. I getting this error - ***  is not part of the schema for this Realm:

```
11-19 01:47:25.533 30245-30245/com.tst.nikita.newsapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.tst.nikita.newsapp, PID: 30245
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tst.nikita.newsapp/com.tst.nikita.newsapp.presentation.view.activity.NewsListActivity}: java.lang.IllegalArgumentException: NewsModelData is not part of the schema for this Realm
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:145)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                         Caused by: java.lang.IllegalArgumentException: NewsModelData is not part of the schema for this Realm
                                                                            at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:172)
                                                                            at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:90)
                                                                            at io.realm.RealmSchema.getTable(RealmSchema.java:296)
                                                                            at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:316)
                                                                            at io.realm.RealmQuery.<init>(RealmQuery.java:138)
                                                                            at io.realm.RealmQuery.createQuery(RealmQuery.java:87)
                                                                            at io.realm.Realm.where(Realm.java:1213)
                                                                            at com.tst.nikita.newsapp.data.cache.RealmCache.getListNewsModelData(RealmCache.java:47)
                                                                            at com.tst.nikita.newsapp.data.repository.datastore.RealmNewsModelDataStore.getListNewsModelData(RealmNewsModelDataStore.java:30)
                                                                            at com.tst.nikita.newsapp.data.repository.datastore.NewsDataStoreFactory.getListNewsModelData(NewsDataStoreFactory.java:36)
                                                                            at com.tst.nikita.newsapp.data.repository.NewsDataRepository.getListNewsModelDomain(NewsDataRepository.java:36)
                                                                            at com.tst.nikita.newsapp.domain.interactor.implementations.GetMainNewsUseCase.buildBaseUseCaseObservable(GetMainNewsUseCase.java:30)
                                                                            at com.tst.nikita.newsapp.domain.interactor.implementations.UseCase.execute(UseCase.java:35)
                                                                            at com.tst.nikita.newsapp.domain.interactor.implementations.GetMainNewsUseCase.execute(GetMainNewsUseCase.java:35)
                                                                            at com.tst.nikita.newsapp.presentation.presenter.NewsListPresenter.getNewsList(NewsListPresenter.java:70)
                                                                            at com.tst.nikita.newsapp.presentation.presenter.NewsListPresenter.loadNewsList(NewsListPresenter.java:65)
                                                                            at com.tst.nikita.newsapp.presentation.presenter.NewsListPresenter.initialize(NewsListPresenter.java:61)
                                                                            at com.tst.nikita.newsapp.presentation.view.fragment.NewsListFragment.loadNewsList(NewsListFragment.java:105)
                                                                            at com.tst.nikita.newsapp.presentation.view.fragment.NewsListFragment.onViewCreated(NewsListFragment.java:82)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                                                            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
                                                                            at android.app.Activity.performStart(Activity.java:6329)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:145) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
```

My RealmObject class:

`public class NewsModelData extends RealmObject{

    @PrimaryKey
    @SerializedName("title")
    @Expose
    private String title;

    @SerializedName("created")
    @Expose
    private String created;

    @SerializedName("body")
    @Expose
    private String body;

    @SerializedName("thumbnail")
    @Expose
    private String thumbnail;

    @SerializedName("full-thumbnail")
    @Expose
    private String full_thumbnail;

    public String getBody() {
        return body;
    }
    public void setBody(String body) {
        this.body = body;
    }

    public String getFull_thumbnail() {
        return full_thumbnail;
    }
    public void setFull_thumbnail(String full_thumbnail) {
        this.full_thumbnail = full_thumbnail;
    }

    public String getThumbnail() {
        return thumbnail;
    }
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public String getCreated() {
        return created;
    }
    public void setCreated(String created) {
        this.created = created;
    }
}
`

My top-level gradle file:

```
`buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'io.realm:realm-gradle-plugin:2.2.0'
        classpath 'me.tatarka:gradle-retrolambda:3.3.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`
```

There is my module-level gradle file:

```
`apply plugin: 'com.android.application'
apply plugin: 'realm-android'

apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.neenbedankt.android-apt'
apply from: '../jacoco.gradle'


android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    dexOptions {
        incremental false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.tst.nikita.newsapp"
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            testCoverageEnabled = true
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support:cardview-v7:24.2.1'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'
    compile 'com.facebook.fresco:imagepipeline-okhttp3:0.13.0'
    compile 'com.facebook.fresco:fresco:0.13.0'
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.uphyca:stetho_realm:0.9.0'
//    compile 'io.realm:android-adapters:1.3.0'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.jakewharton.rxbinding:rxbinding:0.4.0'
    compile 'com.android.support:support-v4:24.2.1'

    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha8'
    compile 'com.google.dagger:dagger:2.7'
    apt 'com.google.dagger:dagger-compiler:2.7'
    compile ('com.annimon:stream-test:1.1.2') {
        exclude group:'org.mockito'
    }
    compile 'io.reactivex:rxjava:1.2.1'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    //testCompile
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:3.1.4'
    testCompile 'org.robolectric:shadows-support-v4:3.0'
    testCompile 'org.robolectric:shadows-multidex:3.1'
    testCompile 'org.robolectric:shadows-play-services:3.1'
    testCompile 'com.squareup.okhttp3:mockwebserver:3.4.1'
    testCompile 'org.powermock:powermock-module-junit4:1.6.6'
    testCompile 'org.powermock:powermock-module-junit4-rule:1.6.6'
    testCompile 'org.powermock:powermock-classloading-xstream:1.6.6'
    testCompile ('org.powermock:powermock-api-mockito2:1.6.6') {
            exclude group:'org.mockito'
    }
    testCompile 'org.mockito:mockito-core:2.2.16'
    testCompile 'org.hamcrest:hamcrest-core:1.3'
    //androidTestCompile
    androidTestCompile 'com.android.support.test:runner:0.4.1'
    androidTestCompile 'com.android.support.test:rules:0.4.1'
    androidTestCompile 'com.android.support:support-annotations:24.2.1'

}`
```

I have tried:

1. Clean and rebuild project.
2. Uninstall app before deploying.
3. I have realm in my project gradle and app gradle. (version 1.1.0)
4. RealmConfiguration has deleteRealmIfMigrationNeeded

```

#### Version of Realm and tooling
Realm version(s): 2.2.0

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: 5.0.1, Samsung S4

**Comment by Zhuinden** [comment]
apply `apply plugin: 'com.neenbedankt.android-apt'` before `apply plugin: 'realm-android'`

**Comment by XabierGoros** [comment]
@Zhuinden I had the same problem and your suggestion solved the problem, thanks! It wasn't necessarily important the order in the previous version v2.1.1. Perhaps it would be good to point this notes in the doc or somewhere.

Just for curiosity, what changed in v2.2.0 to make that order restriction on those two plugins?

**Comment by Zhuinden** [comment]
@XabierGoros while I'm hazy on the details, in order to support `annotationProcessor` scope instead of `apt`, the Realm gradle plugin doesn't run APT if it's on the classpath or something of the sort. 

So APT needs to be run first before applying the Realm plugin. That is my hypitheissm

**Comment by cmelchior** [comment]
@XabierGoros We added support for the `annotationProcessor` directive that was added in Build Tools 2.2. Unfortunately for us to detect if people are using `apt` or `annotationProcessor` it needs to be applied first. This was something we missed in testing, but you are right this should be clarified.

**Comment by nikiJava** [comment]
@Zhuinden, thank you very much - your decision is working.

**Comment by avinashpatnaik** [comment]
i still get the below error even after putting the line
apply plugin: 'com.neenbedankt.android-apt'

Error:Could not get unknown property 'classpath' for task ':app:transformJackWithJackForDebug' of type com.android.build.gradle.internal.pipeline.TransformTask.

**Comment by Zhuinden** [comment]
There are about @avinashpatnaik 2 things wrong with that:

1.) Jack is not supported by Realm and is deprecated, use Android Studio 3.0+ for automatic desugaring, OR use Retrolambda

2.) `android-apt` is no longer supported by Android Studio 3.0+ so there is no reason to use that either

The solution is to use a newer version of Realm, considering `annotationProcessor` scope support was added in 2.2.0.

Latest version at the time of writing is 4.3.3.
