### ISSUE TITLE
                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.realm.RealmResults.add(io.realm.RealmModel)' on a null object reference

### ISSUE THREAD

**Issue by campanoon** [realm/realm-java#3819]
My problem is I have a RealmList and my Custom ListView adapter only accepts RealmResults.

#### Actual Results

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.jmcampanon.nowcook, PID: 5357
                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.realm.RealmResults.add(io.realm.RealmModel)' on a null object reference
                      at com.example.jmcampanon.nowcook.fragments.RecipesFragment.getRecipes(RecipesFragment.java:133)
                      at com.example.jmcampanon.nowcook.fragments.RecipesFragment.onCreateView(RecipesFragment.java:85)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

#### Code Sample

```java
ArrayList<Recipe> RecetasCoinciden;

RealmResults<Recipe> Recipes = null;
        for (Recipe Receta:RecetasCoinciden){
            Recipes.add(Receta);
        }

```

**Comment by Zhuinden** [comment]
To convert a RealmList to RealmResults, do `realmList.where().findAll()`

**Comment by campanoon** [comment]
If I do this:
        RealmResults<Recipe> Recipes = RecetasCoinciden.where().findAll();
The app crash with following dump in logcat:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.jmcampanon.nowcook, PID: 5570
                  java.lang.UnsupportedOperationException: This method is only available in managed mode
                      at io.realm.RealmList.where(RealmList.java:600)
                      at com.example.jmcampanon.nowcook.fragments.RecipesFragment.getRecipes(RecipesFragment.java:130)
                      at com.example.jmcampanon.nowcook.fragments.RecipesFragment.onCreateView(RecipesFragment.java:85)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by Zhuinden** [comment]
Oh. Well your RealmList doesn't seem to belong to a managed object.

In that case, we don't know enough of your code to fix it, because you seem to be trying to use Realm wrong.

**Comment by campanoon** [comment]
I have an ArrayList and need to add it to my RealmRecipesAdapter:

```
  RealmRecipesAdapter realmAdapter = new RealmRecipesAdapter(getContext(), getAllRecipes());

                // Set the data and tell the RecyclerView to draw
                adapter.setRealmAdapter(realmAdapter);
                adapter.notifyDataSetChanged();
```
getAllRecipes() return:

```
        ArrayList<Recipe> Recipes;
```

**Comment by Zhuinden** [comment]
Why ArrayList instead of RealmResults?

**Comment by campanoon** [comment]
Because I get a list of recipes from a SharedPreferences.

**Comment by beeender** [comment]
@campanoon The `RealmList` you want to build the query on has to be a managed `RealmList` -- See https://realm.io/docs/java/latest/#what-is-the-difference-between-a-normal-java-object-and-a-realm-object for managed vs unmanaged.

**Comment by Zhuinden** [comment]
@campanoon why are you storing the recipes in SharedPreferences when you have a database in your project which is supposed to do exactly that (Realm)

**Comment by campanoon** [comment]
First, thank you for your help and sorry for my English.
I have a list of ids of ingredients stored in a SharedPreferences and I want to search the recipes stored in my database if they contain the ingredients that I have in the sharedpreferences, in that case, I return the recipes.

Each recipe contains a RealmList of Ingredients.

**Comment by beeender** [comment]
Your English it perfectly fine! Don't worry about that :)

I suppose `RecetasCoinciden` is a `RealmList`. But apparently it is an unmanged `RealmList` which means it is created by `new YourList()`. Instead, you should query a `RealmList` from Realm to make it as a managed `RealmList`.

**Comment by kneth** [comment]
@campanoon I hope the comment above solved your problem. I am closing the issue but don't hesitate to reopen or create a new issue.
