### ISSUE TITLE
io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided

### ISSUE THREAD

**Issue by rkanatza** [realm/realm-java#3862]
#### Goal

> What do you want to achieve?

Update an existing Android application using the old (pre January 2016) method for including Realm in our grade file. (https://realm.io/news/android-installation-change/) without crashes

#### Expected Results

> We expected Realm would update without crashing when we changed the way we included Realm in our application to the new way (in the article above)

#### Actual Results

>  When users update the app from the Google Play Store, the app crashes upon opening. This is occurring when users have an old version already on their phones (with the old way of including Realm). This is the stack trace we see when we re-create this crash:

`11-22 09:02:49.356 4836-4836/com.<company-name>.<client-name> E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.<company-name>.<client-name>, PID: 4836
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.<company-name>.<client-name>/com.<company-name>.<client-name>.SplashScreen}: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                  Caused by: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
                                                                     at io.realm.BaseRealm.migrateRealm(BaseRealm.java:636)
                                                                     at io.realm.Realm.migrateRealm(Realm.java:1489)
                                                                     at io.realm.Realm.migrateRealm(Realm.java:1476)
                                                                     at io.realm.Realm.createInstance(Realm.java:256)
                                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
                                                                     at io.realm.Realm.getDefaultInstance(Realm.java:195)
                                                                     at com.<company-name>.<client-name>.z_base.BaseActivity.onCreate(BaseActivity.java:50)
                                                                     at android.app.Activity.performCreate(Activity.java:6679)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
`

#### Steps & Code to Reproduce

> Describe your current debugging efforts.
(1) Installed APK on device with the old way of including Realm
(2) Submitted a new APK (with the new way of including Realm) to the Google Play Store
(3) On the device, went to the Google Play Store and updated the application
(4) Attempted to open the application, but immediately there was an error message saying the app had stopped working

#### Version of Realm and tooling
Realm version(s): ? 
The old version of Realm is 0.85.0
The new version of Realm is 0.89.0

Android Studio version: ? 2.2.2

Which Android version and device: ? Android 6 and 7 have shown crashes on multiple devices

**Comment by Zhuinden** [comment]
If you don't have `deleteIfMigrationNeeded()` set for your configuration, then did you follow the breaking change guide?

http://stackoverflow.com/a/39974275/2413303

From 0.85.0 you would have to handle the following change in 0.88.3:


You should probably upgrade to 0.88.3 by the way. If you haven't really handled the breaking changes, then you can easily crash into a wall.

**Comment by rkanatza** [comment]
Thanks, Zhuinden, for responding so quickly! 

So you are saying that we can upgrade to 0.88.3 and just add the @Required annotation to the fields we currently have marked as @PrimaryKey ?

Just want to make sure :)

**Comment by Zhuinden** [comment]
Technically you don't need to add `@Required` if you stick to 0.88.3 instead of 0.89.0

If you want to upgrade to 0.89.0, then add `@Required` on the primary key fields

But really, I don't see your code from here, but the 0.89.0 change is **very heavy**, so I need to ask two things: how do you iterate on `RealmResults<T>`? And how do you delete items from RealmResults in transactions?

Because iteration behavior changed in 0.89.0, as you can read in that SO post.

**Comment by rkanatza** [comment]
Thank you, Zhuinden. We added the deleteIfMigrationNeeded() and kept version 0.89.0.

`Realm.setDefaultConfiguration(new RealmConfiguration.Builder(getApplicationContext())
                    .name("app name"))
                    .schemaVersion(1) // changed to 1
                    .deleteRealmIfMigrationNeeded() // added this line
                    .build());`

The app no longer crashes! :)

**Comment by Zhuinden** [comment]
`.deleteRealmIfMigrationNeeded()` don't forget that this deletes the Realm file when the app first runs, is that ok?

You should also make sure that every behavior works fine.

Personally, I would recommend that if you go to 0.89.0, then you could as well go to 1.2.0

**Comment by zaki50** [comment]
I'll close this.
If you have further questions, feel free to reopen it.
