### ISSUE TITLE
Bad Realm file Header (#3)

### ISSUE THREAD

**Issue by ZeroBrain** [realm/realm-java#3880]
My app's Environment is this:

Gradle : 2.14.1
Android Gradle : 2.2.1
Realm : 2.1.1
minSdk : 15
targetSdk 23
buildTools : 23.0.3
compileSdk : 23

it's error log from Fabric

```java
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.tosslab.jandi.app/files/default.realm': Bad Realm file header (#3). in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
       at io.realm.Realm.getDefaultInstance(Realm.java:211)
       at com.tosslab.jandi.app.local.orm.repositories.realm.RealmRepository.execute(RealmRepository.java:27)
       at com.tosslab.jandi.app.local.orm.repositories.info.FolderRepository.getFolderExpands(FolderRepository.java:193)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.presenter.MainTopicListPresenter.onGetFolderExpands(MainTopicListPresenter.java:163)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment.setFolderExpansion(MainTopicListFragment.java:478)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment_.access$801(MainTopicListFragment_.java:29)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment_.setFolderExpansion(MainTopicListFragment_.java:220)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment.showList(MainTopicListFragment.java:358)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment_.access$1001(MainTopicListFragment_.java:29)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment_.showList(MainTopicListFragment_.java:238)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.presenter.MainTopicListPresenter.onLoadList(MainTopicListPresenter.java:68)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment.initViews(MainTopicListFragment.java:147)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment_.onViewChanged(MainTopicListFragment_.java:123)
       at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
       at com.tosslab.jandi.app.ui.maintab.tabs.topic.MainTopicListFragment_.onViewCreated(MainTopicListFragment_.java:80)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:700)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1364)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:765)
       at android.view.View.measure(View.java:20166)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
       at android.view.View.measure(View.java:20166)
       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1085)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3143)
       at android.view.View.measure(View.java:20166)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2644)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1599)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1891)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

after it occurred, users cannot opened app anymore. 

my app has never used Realm before.
App contained realm first time. so nothing changed realm config in app.

anyone has solution about this?

**Comment by Zhuinden** [comment]
What is the type of device?

**Comment by ZeroBrain** [comment]
<img width="666" alt="2016-12-07 4 18 19" src="https://cloud.githubusercontent.com/assets/4973428/20958403/cd5e01fe-bc98-11e6-8af9-b72a8cef7993.png">

@Zhuinden any types. I cannot figure out exactly what they are.

**Comment by ZeroBrain** [comment]
when I get this situation, should I remove Realm and re-initiate? for safety code.

**Comment by kneth** [comment]
@ZeroBrain Yes, if you remove the file, data is lost. But Realm will re-initiate (creating  classes/tables without objects) when the app restarts.

If you can explain how you use Realm, we might be able to help you to avoid these crashes :-)

**Comment by ZeroBrain** [comment]
@Zhuinden @kneth I think I solved this problem. I found why it occurred & how to solve.
I will share to you for all realm users.

summarized, it occurred by custom process. actually my custom process service don't access Realm database. but Application class initiate like this :

```java
class MyApplication extends Application {
  public onCreate() {
     Realm.init(this);
  }
}
```

you know that even we don't use something at custom process, that called Application class. I almost forgot it. that is the problem. 

so I was looking for avoid initiating at custom process. and I found. that's it.

for more details, I would share it
after sharing, I hope many dev guys don't suffer by it.

if you want, close this issues. :)

**Comment by kneth** [comment]
@ZeroBrain Thanks for sharing!

**Comment by Zhuinden** [comment]
@cmelchior this sounds like a deeper issue though.

**Comment by MikeKasperlik** [comment]
We are expiring this crash as well - not really sure how to fix that. We do also use a remote process, but we need realm there. 

It crashes in the remote process (service), not the (separate) realm in the application

```
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path 'path/to/db.realm': Bad Realm file header (#1). in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
       at io.realm.Realm.getInstance(Realm.java:227)
```

This occures at: `Realm.getInstance(getRealmConfig());`

With the following config:
```
public static RealmConfiguration getRealmConfig() {
        return new RealmConfiguration.Builder()
                .name(NEW_REALM_NAME)
                .modules(new DbModule())
                .encryptionKey(getRealmEncryptionKey())
                .schemaVersion(REALM_SCHEMA_VERSION)
                .deleteRealmIfMigrationNeeded() 
                .build();
    }
```

**Comment by kneth** [comment]
@MikeKasperlik Please remember that Realm doesn't support multiple processes yet. A service might run in another process. Said that, you might also have to grant services write permissions.

**Comment by ZeroBrain** [comment]
@MikeKasperlik if you need to access realm from other process, unfortunately you should use `ContentProvider`. now, it's the only SOLUTION that I found.

**Comment by Zhuinden** [comment]
@ZeroBrain but multiprocess access isn't supported yet, although I guess since 2.0 the processes lock each other from concurrent modification

**Comment by ZeroBrain** [comment]
@Zhuinden I mean that multi-process as `:remote` should access on ContentProvider of Android.
ContentProvider is called on Main-Process.

**Comment by KimiChiu** [comment]
@ZeroBrain Do you mean that it'll throw this exception if I use a `FirebaseMessagingService` and it is triggered while the Application is stopped? Just because the Application is initialized by the service? And you said you found a way to avoid this exception, can you post your code snippet?
Thanks!

**Comment by mihirjoshi21** [comment]
@ZeroBrain @MikeKasperlik I am experiencing the same issue but my service doesn't use a different process.
http://crashes.to/s/706cc3e62fc
How did you guys resolve this? Any help will be greatly appreciated. 


![new bitmap image](https://cloud.githubusercontent.com/assets/5195121/22299009/8bcfee4c-e348-11e6-8059-2f18eb40260f.jpg)

**Comment by kneth** [comment]
@mihirjoshi21 Can you post details about your app? Do you have multiple classes which extend `Application` and initialize Realm?

**Comment by mihirjoshi21** [comment]
I have a service but it's not in the separate process. `Real.init()` is already used in the application class.

**Comment by kneth** [comment]
Does your service access Realm?

**Comment by mihirjoshi21** [comment]
Yes

**Comment by kneth** [comment]
Can you share your app's manifest? And how you initialize and open a Realm?
