### ISSUE TITLE
 io.realm.exceptions.RealmError: Unrecoverable error. Table index out of range in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92

### ISSUE THREAD

**Issue by JContrerasPereira** [realm/realm-java#3897]
Hi, first of all, I have zero knowledge of Android development. Recently we've been receiving reports of Android smartphones crashing eventually at random points after extended use of our app.

Today we've finally managed to capture this on debug and got this stack trace.

#### Stack trace

```java

12-12 11:08:20.274 5641-5641/com.oraintechnologies.iot E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         io.realm.exceptions.RealmError: Unrecoverable error. Table index out of range in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
                                                                             at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                             at io.realm.internal.SharedRealm.a(Unknown Source)
                                                                             at io.realm.internal.SharedRealm.a(Unknown Source)
                                                                             at io.realm.p.a(Unknown Source)
                                                                             at io.realm.n.l(Unknown Source)
                                                                             at com.oraintechnologies.iot.OrainApplication.a(Unknown Source)
                                                                             at com.oraintechnologies.iot.init.Init.onCreate(Unknown Source)
                                                                             at android.app.Activity.performCreate(Activity.java:5206)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
                                                                             at android.app.ActivityThread.access$700(ActivityThread.java:140)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                                             at dalvik.system.NativeStart.main(Native Method)

```

The app is crashing when getting a Realm instance on launch, we managed to extract the realm file and it seems to be broken, tried to open it on the Realm Browser and it says the document could not be opened. I'll attach the realm file.

[10.realm.zip](https://github.com/realm/realm-java/files/646400/10.realm.zip)

Sorry I can't provide more information, the Android developer is currently away and won't be able to come back until Wednesday.

#### Version of Realm and tooling
Realm version(s): 2.2.0
Which Android version and device: Samsung Galaxy S2 - 4.1.2

**Comment by Zhuinden** [comment]
Well for someone who doesn't know much about Android dev, you made a good issue report 👍 

I'm just a community member though, so only Realm knows how to deal with corruption.

Possible causes include:
- invalid multi-process access
- failed `compact()` call
- auto-backup is not disabled on `.realm` file

**Comment by cmelchior** [comment]
@JContrerasPereira Most likely cause of this is multiprocess access to the same file. Can you post your `AndroidManifest.xml` file?

**Comment by JContrerasPereira** [comment]
Sure

```xml

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.oraintechnologies.iot">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <!-- notifications push -->
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />



    <supports-screens
        android:smallScreens="true"
        android:normalScreens="true"
        android:largeScreens="false"
        android:xlargeScreens="false"
        android:largestWidthLimitDp="840"/>

    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="false" />

    <application
        android:name=".OrainApplication"
        android:allowBackup="true"
        android:icon="@mipmap/logo_acceso"
        android:label="Orain"
        android:theme="@style/Theme.AppCompat.Light.NoActionBar">

        <!-- android:theme="@style/orain_theme" -->
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        <service
            android:name=".common.notificaciones_push.RegistrationIntentService"
            android:exported="false" />

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label=""
            android:screenOrientation="portrait" />
        <activity
            android:name=".common.init.options.ContactsManagement"
            android:icon="@mipmap/orain_cabecera"
            android:label="Orain"
            android:screenOrientation="portrait" />
        <activity
            android:name=".vending.session.options.SpecificProductInformation"
            android:icon="@mipmap/orain_cabecera"
            android:label="Información de producto"
            android:screenOrientation="portrait" />
        <activity
            android:name=".vending.session.tutorial.Tutorial"
            android:icon="@mipmap/orain_cabecera"
            android:label=""
            android:screenOrientation="portrait" />

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <activity
            android:name=".common.init.options.user_profile.AccountsAdmin"
            android:icon="@mipmap/orain_cabecera"
            android:label="Perfil"
            android:screenOrientation="portrait" />
        <activity
            android:name=".common.init.options.notifications.Notificaciones"
            android:icon="@mipmap/orain_cabecera"
            android:label=""
            android:screenOrientation="portrait" />

        <activity android:name=".common.init.options.user_profile.admin_options.InvitarAmigo" />
        <activity
            android:name=".common.init.options.user_profile.admin_options.ConfiguracionPerfilUsuario"
            android:label=""
            android:screenOrientation="portrait" />
        <activity
            android:name=".common.init.options.user_profile.admin_options.HelpInformation"
            android:label="Información y ayuda"
            android:screenOrientation="portrait" />

        <activity android:name=".ocs_vdos.session.MachineInfoOCS"
            android:label="Información"/>

        <activity android:name=".init.signin.BasicWebView" />
        <activity android:name=".RememberSessionCode" />
        <activity
            android:name=".common.init.options.user_profile.admin_options.ContactoOrain"
            android:label="Contacto"
            android:noHistory="true"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan" />

        <service
            android:name=".common.notificaciones_push.MyInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>

        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />

                <category android:name="com.codepath.gcmquickstart" />
            </intent-filter>
        </receiver>

        <service
            android:name=".common.notificaciones_push.GcmMessageHandler"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>

        <activity
            android:name=".common.messages_management.Chat"
            android:configChanges="orientation|keyboardHidden"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateAlwaysHidden" />
        <activity
            android:name=".vending.session.options.VendingMachineInfo"
            android:label="Información"
            android:screenOrientation="portrait" />

        <activity
            android:name=".vending.credits_payment.CreditsPurchaseV2"
            android:label="Recarga"
            android:screenOrientation="portrait" />
        <activity
            android:name=".vending.credits_payment.OnlinePaymentView"
            android:label="Pago"
            android:screenOrientation="portrait" />

        <activity
            android:name=".common.init.options.user_profile.admin_options.InsertCreditCardData"
            android:label="Datos tarjeta"
            android:screenOrientation="portrait" />
        <activity
            android:name=".vending.session.options.MachinesProducts"
            android:label="Productos"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".init.Sign"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".init.Init"
            android:label="@string/title_activity_init"
            android:screenOrientation="portrait"
            android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- ============OCS SERVICE ================= -->
        <activity
            android:name=".ocs_vdos.session.market.OCSmarket"
            android:label="@string/ocs_title_market"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".ocs_vdos.session.market.TypeMarketSelector"
            android:label="@string/ocs_title_market_selector"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".ocs_vdos.session.market.ShoppingCart"
            android:label="@string/title_activity_shopping_cart"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".ocs_vdos.session.market.OcsProductInformation"
            android:label="@string/title_activity_ocs_product_information"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".ocs_vdos.session.CreditCardPayment"
            android:label="@string/title_activity_credit_card_payment"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".ocs_vdos.session.OcsHelpInformation"
            android:label="@string/title_activity_ocs_help_information"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
        <activity
            android:name=".ocs_vdos.session.OCSOnlinePaymentView"
            android:label="@string/title_activity_online_payement_view"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>


    </application>


</manifest>

```

**Comment by JContrerasPereira** [comment]
Also here is a non obfuscated stack trace

```java

12-13 11:43:53.571 2529-2529/com.oraintechnologies.iot E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.oraintechnologies.iot, PID: 2529
                                                                         io.realm.exceptions.RealmError: Unrecoverable error. Table index out of range in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
                                                                             at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                             at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
                                                                             at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
                                                                             at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                                                                             at io.realm.Realm.getInstance(Realm.java:227)
                                                                             at com.oraintechnologies.iot.OrainApplication.createDatabase(OrainApplication.java:78)
                                                                             at com.oraintechnologies.iot.init.Sign$ReceptorDatos.handleMessage(Sign.java:216)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5635)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                             at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kneth** [comment]
@JContrerasPereira We'll take a look at the Realm file and see it is can provide us with any useful information.

**Comment by kneth** [comment]
@JContrerasPereira After examine your Realm file, it seems that you were hit by a known bug. It has been fixed (https://github.com/realm/realm-core/pull/2324), and we have merged it into Realm Java (https://github.com/realm/realm-java/pull/3904 - updating to Realm Core 2.2.0). You can use the fix as part of the latest snapshot. We plan to do a release very soon.
