### ISSUE TITLE
**Bugs**

### ISSUE THREAD

**Issue by osama-raddad** [realm/realm-java#3905]
```java
W/System.err: java.lang.IllegalArgumentException: Primary key value is not a long: com.demo.thedoomlord.realmtest.datacenter.User@a6ef3a8
W/System.err:     at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:446)
W/System.err:     at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:387)
W/System.err:     at io.realm.Realm.createObjectInternal(Realm.java:864)
W/System.err:     at io.realm.Realm.createObject(Realm.java:844)
W/System.err:     at com.demo.thedoomlord.realmtest.datacenter.manager.Module$1.execute(Module.java:23)
W/System.err:     at io.realm.Realm.executeTransaction(Realm.java:1253)
W/System.err:     at com.demo.thedoomlord.realmtest.datacenter.manager.Module.createModule(Module.java:20)
W/System.err:     at com.demo.thedoomlord.realmtest.datacenter.DataCenter.createUser(DataCenter.java:26)
W/System.err:     at com.demo.thedoomlord.realmtest.App.onCreate(App.java:20)
W/System.err:     at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4787)
W/System.err:     at android.app.ActivityThread.access$1600(ActivityThread.java:154)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:152)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5497)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
```

**Comment by Zhuinden** [comment]
So what is

         com.demo.thedoomlord.realmtest.datacenter.manager.Module$1.execute(Module.java:23)
         com.demo.thedoomlord.realmtest.datacenter.manager.Module.createModule(Module.java:20)
         com.demo.thedoomlord.realmtest.datacenter.DataCenter.createUser(DataCenter.java:26)

**Comment by osama-raddad** [comment]
sorry this is by mistake
