### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmError Unrecoverable error. Schema mismatch detected: another process has modified the Realm file's schema in an incompatible way in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 113

### ISSUE THREAD

**Issue by toukh** [realm/realm-java#3907]
Hi all, i have problem. This error occurred after i updated realm from 0.83 to 2.1.1. I track this error in crashlytics, how i see this error appears one time per user after app updating.
I can't repeat this crash on my device or on emulators :(

#### Actual Results

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Schema mismatch detected: another process has modified the Realm file's schema in an incompatible way in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 113
       at io.realm.internal.SharedRealm.nativeBeginTransaction(SharedRealm.java)
       at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:219)
       at io.realm.BaseRealm.beginTransaction(BaseRealm.java:328)
       at io.realm.DynamicRealm.beginTransaction(DynamicRealm.java:47)
       at io.realm.BaseRealm$4.onResult(BaseRealm.java:631)
       at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:295)
       at io.realm.BaseRealm.migrateRealm(BaseRealm.java:613)
       at io.realm.Realm.migrateRealm(Realm.java:1514)
       at io.realm.Realm.createInstance(Realm.java:273)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
       at io.realm.Realm.getInstance(Realm.java:229)
       at com.myAppPackage.app.App.initDatabase(App.java:214)
       at com.myAppPackage.app.App.onCreate(App.java:158)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6321)
       at android.app.ActivityThread.access$1800(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

#### Code Sample

    214 line is: Realm realm = Realm.getInstance(realmConfig);
    Current ver Settings.DATABASE_SCHEME_VERSION == 12, old == 11

    private void initDatabase() {
        Realm.init(this);
        RealmConfiguration realmConfig = new RealmConfiguration.Builder()
                .schemaVersion(Settings.DATABASE_SCHEME_VERSION)
                .migration(new DBMigration())
                .build();
        Realm realm = Realm.getInstance(realmConfig);
        Realm.setDefaultConfiguration(realm.getConfiguration());
        realm.close();
    }

#### Version of Realm and tooling
Realm version(s): 2.1.1
and io.realm:android-adapters:1.4.0

Android Studio version: 2.2

Which Android version and device: from 4.2.1 to 6.0.1

**Comment by Zhuinden** [comment]
This sounds very similar to https://github.com/realm/realm-java/issues/2459 ("Incompatible lock file")

**Comment by kneth** [comment]
Going from 0.83 to 2.1.1 is a big jump. The Realm file format has been changed twice (0.90.1 and 2.0.0). We have tested the change one by one but the intension is at skipping one change like you do, should work.

Can you share your migration step? In your snippet, it is impossible to see how the schema is changed.

**Comment by toukh** [comment]
Yeah, true, it's big jump. Need my DBMigration.class?

**Comment by kneth** [comment]
We don't need to see the migration step. But if you can describe the schema and the changes, we might get a better idea of how file format upgrades can go wrong.

**Comment by beeender** [comment]
Dup this to #2459
