### ISSUE TITLE
OOM crash with Realm 1.2.0

### ISSUE THREAD

**Issue by stan-ko** [realm/realm-java#3909]
Hi!

I'm facing OOM crash issue with Realm. My app creates 3-4 instances (one per thread) of Realm during execution. Maybe each created instance ignoring its further close() and stays in RAM and thats why it ends up trying to allocate more than 50 megs of RAM. My whole DB is about 3 Mb (default.realm is 3.75Mb) how comes it want 50 if I'm not using all the data/tables simultaneously? Does every instance allocates RAM for whole DB (16mb in my case) while creates its own heap?

#### Goal

Use Realm from different threads simultaneously

#### Expected Results

No OOM

#### Actual Results

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 50331648 offset: 0 in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:64)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:77)
       at io.realm.Realm.<init>(Realm.java:138)
       at io.realm.Realm.createAndValidate(Realm.java:269)
       at io.realm.Realm.createInstance(Realm.java:249)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:213)

#### Version of Realm and tooling
Realm version(s): 1.2.0. Сan't use 2.x since it crashes on Samsung devices (another issue)

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: vary
http://prntscr.com/djana1

**Comment by Zhuinden** [comment]
Well, `.getInstance()` is counted per instance, so if you do `.getInstance()` 5 times and you close 1 time, then the Realm will not get released and you can easily run out of memory if you create new versions of the Realm on different threads simultaneously.

**Comment by stan-ko** [comment]
OK, but how much RAM does one instance need? And I've got the same crash with very 1st  instance recently.

> Fatal Exception: io.realm.exceptions.RealmError
> Unrecoverable error. mmap() failed: Out of memory size: 603979776 offset: 0 in io_realm_internal_SharedGroup.cpp line 113

`
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 603979776 offset: 0 in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:86)
       at io.realm.Realm.<init>(Realm.java:135)
       at io.realm.Realm.createAndValidate(Realm.java:233)
       at io.realm.Realm.createInstance(Realm.java:214)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getInstance(Realm.java:178)
       at uk.myc00lapp.util.DBHelper.init(DBHelper.java:107)
       at uk.myc00lapp.app.MyApp.onCreate(MyApp.java:160)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6422)
       at android.app.ActivityThread.access$1800(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`
and here DBHelper.init:
`
    private static RealmConfiguration sRealmConfiguration;
    private static Realm sMainThreadRealmInstance;

    public static void init(final Context context) {
        if (sRealmConfiguration == null) {
            sRealmConfiguration = new RealmConfiguration.Builder(context.getApplicationContext())
                    .schemaVersion(20)
                    .migration(new Migration())
                    .build();
            sMainThreadRealmInstance = Realm.getInstance(sRealmConfiguration);
        }
    }
`

**Comment by kneth** [comment]
Instances as such do not require memory. But Realm is a MultiVersion Concurrent Control database which means that each instance will keep a copy/snapshot of the database alive. When an instance is closed (or refreshed = updated to latest version), Realm can reclaim the space. If you don't close a couple of instances, these versions of your database will be kept alive.

See also https://realm.io/docs/java/latest/#large-realm-file-size.
