### ISSUE TITLE
Crash on RealmThreadPoolExecutor 

### ISSUE THREAD

**Issue by mithrann** [realm/realm-java#3914]
Got another crash from crashlytics on realm asynchronous transaction. 

Stack trace:

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@9759f74 rejected from io.realm.internal.async.e@5626c9d[Running, pool size = 17, active threads = 17, queued tasks = 100, completed tasks = 37]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:89)
       at io.realm.internal.async.RealmThreadPoolExecutor.submitTransaction(SourceFile:71)
       at io.realm.Realm.executeTransactionAsync(SourceFile:1339)
       at io.realm.Realm.executeTransactionAsync(SourceFile:1274)
```  

Realm version(s): 2.2.1

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: 7.0 & Huawei Mate 9

**Comment by Zhuinden** [comment]
This means you're calling `executeTransactionAsync()` in a for-loop, even though it should be only 1 transaction.

**Comment by mithrann** [comment]
@Zhuinden  yes i saw that and fixed it.. That's why i closed the issue myself 👍

**Comment by iurysza** [comment]
@mithrann Its better to have an actual answer to it. =)
