### ISSUE TITLE
Realm complains that Primary Key value is not long, though field is defined as Integer

### ISSUE THREAD

**Issue by jraczak** [realm/realm-java#3930]
I was previously using Long/long trying to work through auto-incrementing IDs to avoid duplicates. For a variety of reasons, I moved away from long to Integer. However, Realm complains that my object's primary key is not a long (as it should not be). 

#### Actual Results

```
java.lang.IllegalArgumentException: Primary key value is not a long: com.justinraczak.android.squadgoals.models.Set@5d0e0b4
                                                                                            at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:446)
                                                                                            at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:387)
                                                                                            at io.realm.Realm.createObjectInternal(Realm.java:865)
                                                                                            at io.realm.Realm.createObject(Realm.java:845)
                                                                                            at com.justinraczak.android.squadgoals.LogWorkoutActivity.onSetsSaved(LogWorkoutActivity.java:122)
                                                                                            at com.justinraczak.android.squadgoals.EditSetsFragment.onSaveButtonPressed(EditSetsFragment.java:122)
                                                                                            at com.justinraczak.android.squadgoals.EditSetsFragment$1.onClick(EditSetsFragment.java:88)
                                                                                            at android.view.View.performClick(View.java:5639)
                                                                                            at android.view.View$PerformClick.run(View.java:22387)
                                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6088)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

#### Steps & Code to Reproduce

> I've hunted down everywhere to make sure longs aren't being passed around.

From the model:

https://github.com/jraczak/squad-goals-android/blob/master/app/src/main/java/com/justinraczak/android/squadgoals/models/Set.java#L18-L38

Where the exception is being triggered:

https://github.com/jraczak/squad-goals-android/blob/master/app/src/main/java/com/justinraczak/android/squadgoals/LogWorkoutActivity.java#L114-L143

Android Studio version: 2.2.2

**Comment by cmelchior** [comment]
The exception message is correct. It is telling you, you are trying to use the Set as a PK value.

This line here is wrong: https://github.com/jraczak/squad-goals-android/blob/master/app/src/main/java/com/justinraczak/android/squadgoals/LogWorkoutActivity.java#L122

You just created an unmanaged Set above which indicate you wanted to do:
```
Set realmSet = mRealm.copyToRealm(set);
```

`createObject` creates the managed object directly, which would completely ignore the unmanaged set you just created. The 2nd parameter is the primary key value of that object, not the object you want to create.

**Comment by jraczak** [comment]
@cmelchior Thank you so much for the quick reply! This was driving me bonkers. When I read the implementation for `createObject`, I read the "Object" part and completely missed the `primaryKeyValue`. I had changed my implementation here and using create was a remnant of the old implementation which I needed to update. Thanks again for the quick reply, really appreciate it. Back to work for me :)

**Comment by jraczak** [comment]
@cmelchior Actually, I'm back in the place of the original problem I had before. Let me know if you'd like me to open a separate issue, but I had originally changed to `createObject` because I was hitting an issue with duplicate ID values on the primary key, though I wasn't sure why. Do you have any idea what would cause this? I am implementing like so:

https://github.com/jraczak/squad-goals-android/blob/master/app/src/main/java/com/justinraczak/android/squadgoals/models/Set.java#L18-L38

**Comment by Zhuinden** [comment]
@jraczak `max()` returns `Number`, so you should do `if(number != null) { nextId = number.intValue() + 1; }`

**Comment by jraczak** [comment]
@Zhuinden Thanks, I did eventually realize that (though took a different approach to get an int out). Do you have any idea why/where I'm running into unique primary key clashes? I only create the object once, and even if it was created more than once my `autoIncrement` function should prevent duplicate keys. The error is being triggered where I invoke `copyToRealm`. Does Realm do anything during this that might be invisible to me?

**Comment by Zhuinden** [comment]
Well, make sure you only call this `getNextId` method inside transactions

**Comment by jraczak** [comment]
@Zhuinden That _worked_ (I think) for the initial creation, but when creating a second workout and attempting to save sets to it, I still get:

`io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 2`

I'm probably failing to understand the flow since I'm new to Realm. Thinks in advance for your help, really appreciate it.

**Comment by Zhuinden** [comment]
max+1 in a transaction should never exist twice. 

I do not see where that could happen.

**Comment by jraczak** [comment]
Fresh install of the app and back to square 1.

`io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 1`

Here are the relevant bits.

Activity
```
        mRealm.beginTransaction();
        
        Integer id = Set.getNewAutoIncrementId();
        Set set = new Set(id, new Date(), workout, exercise, reps, weight);
        Log.d(LOG_TAG, "Attempting to save set with id " + set.getRealmId() + " to realm");
        Set realmSet = mRealm.copyToRealm(set);
        mRealm.commitTransaction();
        
        Log.d(LOG_TAG, "id of unmanaged set is " + set.getRealmId());
        Log.d(LOG_TAG, "id of managed realm object is " + realmSet.getRealmId());
        
        mRealm.close();
```

Constructor / model
```
    @PrimaryKey
    private Integer realmId;
    @Required
    private Date date;
    private Workout workout;
    private Exercise exercise;
    private int reps;
    private float weight;

    public Set(Integer id, Date date, Workout workout, Exercise exercise, int reps, float weight) {
        this.realmId = id;
        this.date = date;
        this.workout = workout;
        this.exercise = exercise;
        this.reps = reps;
        this.weight = weight;
    }
```

Increment (in the model)
```
    public static Integer getNewAutoIncrementId() {
        Realm realm = Realm.getDefaultInstance();

        if (realm.where(Set.class).max("realmId") == null) {
            Log.d(LOG_TAG,"max table id was null, returning 1");
            realm.close();
            return 1;
        } else {
            Log.d(LOG_TAG, "incrementing max table id");
            realm.close();
            return (realm.where(Set.class).max("realmId").intValue()+1);
        }
    }
```

I've also tried calling the increment from inside the constructor instead of passing the id in at creation time.
