### ISSUE TITLE
Crash if using .modules on file extends Application

### ISSUE THREAD

**Issue by Ajtak** [realm/realm-java#3931]
#### Goal

> Usage .modules in file, which extends Application.

#### Expected Results

> I excepted usage **.modules** in file, which extends Application and set to **setDefaultConfiguration**

#### Actual Results
```java
java.lang.RuntimeException: Unable to create application cz.xxx.yyy.AppLogic: 
io.realm.exceptions.RealmException: Could not find io.realm.AppLibraryMediator
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798)
    at android.app.ActivityThread.access$1500(ActivityThread.java:170)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5576)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
 Caused by: io.realm.exceptions.RealmException: Could not find io.realm.AppLibraryMediator
    at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:300)
    at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:274)
    at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:665)
    at cz.xxx.yyy.AppLogic.onCreate(AppLogic.java:41)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4795)
    at android.app.ActivityThread.access$1500(ActivityThread.java:170) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:194) 
    at android.app.ActivityThread.main(ActivityThread.java:5576) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
 Caused by: java.lang.ClassNotFoundException: io.realm.AppLibraryMediator
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:308)
    at java.lang.Class.forName(Class.java:272)
    at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:295)
    at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:274) 
    at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:665) 
    at cz.xxx.yyy.AppLogic.onCreate(AppLogic.java:41) 
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4795) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:170) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:194) 
    at android.app.ActivityThread.main(ActivityThread.java:5576) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
 Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.AppLibraryMediator" on path: DexPathList[[zip file "/data/app/cz.xxx.yyy-1/base.apk"],nativeLibraryDirectories=[/data/app/cz.xxx.yyy-1/lib/arm, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:308) 
    at java.lang.Class.forName(Class.java:272) 
    at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:295) 
    at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:274) 
    at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:665) 
    at cz.xxx.yyy.AppLogic.onCreate(AppLogic.java:41) 
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4795) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:170) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:194) 
    at android.app.ActivityThread.main(ActivityThread.java:5576) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
	Suppressed: java.lang.ClassNotFoundException: io.realm.AppLibraryMediator
    at java.lang.Class.classForName(Native Method)
    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
    		... 19 more
```
#### Steps & Code to Reproduce

Use **.modules(new Class())**, and **setDefaultConfiguration** in file, which **extends Application**.

#### Code Sample
File extends Application:
```java

public class AppLogic extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        
        Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .schemaVersion(0)
                .migration(new MigrationClass())
                .modules(new AppLibrary())
                .build();

        Realm.setDefaultConfiguration(config);
    }
}
```
AppLibrary:
```java
@RealmModule(library = true, allClasses = true)
public class AppLibrary{
  // nothing here
}
```
#### Version of Realm and tooling
Realm version(s): 2.2.1

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: Android 5 Lolipop, tablet Lenovo

**Comment by cmelchior** [comment]
I sounds like the annotation processor isn't being triggered for your app library in that case. If you check the gradle output you should see something like "Generating: AppLibrary module"?

**Comment by Zhuinden** [comment]
Please show your gradle plugin order

**Comment by Ajtak** [comment]
Gradle output is (abridged):

> Executing tasks: [:app:assembleDebug]
> 
> Configuration on demand is an incubating feature.
> Incremental java compilation is an incubating feature.
> :app:preBuild UP-TO-DATE
> :app:preDebugBuild UP-TO-DATE
> :app:checkDebugManifest
> :app:preReleaseBuild UP-TO-DATE
> :AppLibrary:preBuild UP-TO-DATE
> :AppLibrary:preReleaseBuild UP-TO-DATE
> :AppLibrary:checkReleaseManifest
> :AppLibrary:preDebugAndroidTestBuild UP-TO-DATE
> :AppLibrary:preDebugBuild UP-TO-DATE
> :AppLibrary:preDebugUnitTestBuild UP-TO-DATE
> :AppLibrary:preReleaseUnitTestBuild UP-TO-DATE
> :AppLibrary:prepareComGetkeepsafeRelinkerRelinker122Library UP-TO-DATE
> :AppLibrary:prepareIoRealmRealmAndroidLibrary221Library UP-TO-DATE
> :AppLibrary:prepareReleaseDependencies
> :AppLibrary:compileReleaseAidl UP-TO-DATE
> :AppLibrary:compileReleaseNdk UP-TO-DATE
> :AppLibrary:compileLint UP-TO-DATE
> :AppLibrary:copyReleaseLint UP-TO-DATE
> :AppLibrary:compileReleaseRenderscript UP-TO-DATE
> :AppLibrary:generateReleaseBuildConfig UP-TO-DATE
> :AppLibrary:generateReleaseResValues UP-TO-DATE
> :AppLibrary:generateReleaseResources UP-TO-DATE
> :AppLibrary:mergeReleaseResources UP-TO-DATE
> :AppLibrary:processReleaseManifest UP-TO-DATE
> :AppLibrary:processReleaseResources UP-TO-DATE
> :AppLibrary:generateReleaseSources UP-TO-DATE
> :AppLibrary:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
> :AppLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> :AppLibrary:extractReleaseAnnotations UP-TO-DATE
> :AppLibrary:mergeReleaseShaders UP-TO-DATE
> :AppLibrary:compileReleaseShaders UP-TO-DATE
> :AppLibrary:generateReleaseAssets UP-TO-DATE
> :AppLibrary:mergeReleaseAssets UP-TO-DATE
> :AppLibrary:mergeReleaseProguardFiles UP-TO-DATE
> :AppLibrary:packageReleaseRenderscript UP-TO-DATE
> :AppLibrary:packageReleaseResources UP-TO-DATE
> :AppLibrary:processReleaseJavaRes UP-TO-DATE
> :AppLibrary:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
> :AppLibrary:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
> :AppLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> :AppLibrary:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
> :AppLibrary:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
> :AppLibrary:bundleRelease UP-TO-DATE
> :app:prepareChAcraAcra490Library UP-TO-DATE
> :app:prepareComGetkeepsafeRelinkerRelinker122Library UP-TO-DATE
> :app:prepareIoRealmRealmAndroidLibrary221Library UP-TO-DATE
> :app:prepareDebugDependencies
> :app:compileDebugAidl UP-TO-DATE
> :app:compileDebugRenderscript UP-TO-DATE
> :app:generateDebugBuildConfig UP-TO-DATE
> :app:generateDebugResValues UP-TO-DATE
> :app:generateDebugResources UP-TO-DATE
> :app:mergeDebugResources UP-TO-DATE
> :app:processDebugManifest UP-TO-DATE
> :app:processDebugResources UP-TO-DATE
> :app:generateDebugSources UP-TO-DATE
> :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
> :app:compileDebugJavaWithJavac UP-TO-DATE
> :app:compileDebugNdk UP-TO-DATE
> :app:compileDebugSources UP-TO-DATE
> :app:mergeDebugShaders UP-TO-DATE
> :app:compileDebugShaders UP-TO-DATE
> :app:generateDebugAssets UP-TO-DATE
> :app:mergeDebugAssets UP-TO-DATE
> :app:transformClassesWithRealmTransformerForDebug UP-TO-DATE
> :app:transformClassesWithDexForDebug UP-TO-DATE
> :app:mergeDebugJniLibFolders UP-TO-DATE
> :app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
> :app:processDebugJavaRes UP-TO-DATE
> :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> :app:validateSigningDebug
> :app:packageDebug UP-TO-DATE
> :app:assembleDebug UP-TO-DATE
> 
> BUILD SUCCESSFUL
> 
> Total time: 17.039 secs

**Comment by zaki50** [comment]
Is Realm's plugin applied to the library project as well?

**Comment by Ajtak** [comment]
No, i not implemented realm library to build.gradle for libraries, because when I add apply plugin: 'realm-android', so I get a compile error:
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lio/realm/DefaultRealmModule; I will try add class for all modules class with useLibrary.

**Comment by Zhuinden** [comment]
What is your Gradle plugin order

**Comment by zaki50** [comment]
You need to apply Realm's plugin to the library project to generate all proxy mediators correctly.

**Comment by kneth** [comment]
@Ajtak Were you able to resolve the issue by reordering your plugins?
