### ISSUE TITLE
Issue in CreateAllFromJson

### ISSUE THREAD

**Issue by aravindcraj** [realm/realm-java#3933]
I'm getting `java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0` error while I'm trying to store the JSON response that I got from server in String format. 

I made a StringRequest using volley to fetch the response:

 `12-21 01:01:26.519 28193-28193/com.buildmyvocab.app E/REALM_JNI: rowIndex 0 > 0 - invalid!
12-21 01:01:26.522 28193-28193/com.buildmyvocab.app E/REALM_JNI: jni: ThrowingException 2, rowIndex > available rows: 0 > 0, .
12-21 01:01:26.522 28193-28193/com.buildmyvocab.app E/REALM_JNI: Exception has been throw: rowIndex > available rows: 0 > 0
12-21 01:01:26.522 28193-28193/com.buildmyvocab.app D/AndroidRuntime: Shutting down VM
12-21 01:01:26.531 28193-28193/com.buildmyvocab.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.buildmyvocab.app, PID: 28193
                                                                      java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0
                                                                          at io.realm.internal.TableView.nativeGetSourceRowIndex(Native Method)
                                                                          at io.realm.internal.TableView.getSourceRowIndex(TableView.java:111)
                                                                          at io.realm.RealmResults.get(RealmResults.java:215)
                                                                          at com.buildmyvocab.app.network.NetworkCalls.stories(NetworkCalls.java:459)
                                                                          at com.buildmyvocab.app.activity.SigninActivity.onRequestCompleted(SigninActivity.java:242)
                                                                          at com.buildmyvocab.app.network.NetworkCalls$4.onResponse(NetworkCalls.java:163)
                                                                          at com.buildmyvocab.app.network.NetworkCalls$4.onResponse(NetworkCalls.java:145)
                                                                          at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:72)
                                                                          at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

And my network call is like this:

`StringRequest stringRequest = new StringRequest(Request.Method.GET, url, new Response.Listener<String>() {
            @Override
            public void onResponse(final String response) {
                Log.d(TAG, "onResponse() called with: response = [" + response + "]");
                    realm.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            realm.createAllFromJson(StoriesResponse.class, response);
                        }
                    });`

The API response looks like this:

`[
    {
        "id": 1,
            "word": "Compliant",
            "meaning": "(adj) obeying, submissive; following the requirements",
            "synonyms": "",
            "antonyms": "",
            "pronunciation_media_url": "",
            "card_ids": [
        2
        ],
        "updated_at": 1482084820
    },
    {
        "id": 2,
            "word": "Stolid",
            "meaning": "(adj) unemotional, showing little emotion, not easily moved",
            "synonyms": "",
            "antonyms": "",
            "pronunciation_media_url": "",
            "card_ids": [
        3
        ],
        "updated_at": 1482084911
    }
    ]`

And my POJO class looks like this:

`public class StoriesResponse extends RealmObject {

    private RealmList<Stories> stories;

    public RealmList<Stories> getStories() {
        return stories;
    }

    public void setStories(RealmList<Stories> stories) {
        this.stories = stories;
    }
}`

Line 459:

`Log.d(TAG, "stories: " + realm.where(StoriesResponse.class).findAll().get(0).getStories().get(0).getTitle());`

Sorry, for the unaligned format.

**Comment by Zhuinden** [comment]
What is line

`com.buildmyvocab.app.network.NetworkCalls.stories(NetworkCalls.java:459)`

**Comment by aravindcraj** [comment]
Log.d(TAG, "stories: " + realm.where(StoriesResponse.class).findAll().get(0).getStories().get(0).getTitle());

**Comment by Zhuinden** [comment]
It says your `StoriesResponse`'s `stories` field is an empty RealmList, so it doesn't have a `0`th element.

I assume that you're supposed to do
 
      @Override public void execute(Realm realm) { 
               realm.createAllFromJson(Stories.class, response); }  // changed class here
      }
    );

And just ditch `StoriesResponse` class as is.

     Log.d(TAG, "stories: " + realm.where(Stories.class).findAll().get(0).getTitle());

**Comment by aravindcraj** [comment]
Thank you so much @Zhuinden . It worked for me. But just wanted to know in StoriesResponse I had made a RealmList<Stories> since it is an array of stories but now in Stories class I have just the object of that class like Title and etc. 

How does it work? Isn't it should be list of stories like my previous implementation?

**Comment by Zhuinden** [comment]
`createAllFromJson` expects an *array* of items, and the class you provide it is expected to be the class of the elements inside the array.

Using `createObjectFromJson("{ [{...},{...}] }", StoriesResponse.class)` would work if what you obtain is an object, but it was an array, so that would not have worked.

**Comment by aravindcraj** [comment]
Thank you so much for being so helpful.

**Comment by aravindcraj** [comment]
But what if I have an array inside it? Like this:


`"{
"id": "1",
"name": "abc",
card_ids": [ 
"upvotes": 4,
"downvotes": 0,
"key": "value",
"key": "value"
 ]
}`

Should I make any changes in my POJO class? Is it supposed to be RealmList<Something>?

**Comment by Zhuinden** [comment]
I think this would work, this is just a question of `createAllFromJson` (which expects Array) and `createObjectFromJson` (which expects Object)
