### ISSUE TITLE
RealmFileException when call Realm.getDefaultInstance()

### ISSUE THREAD

**Issue by linchaolong** [realm/realm-java#3946]
I'm called Realm.init(context) on Application onCreate. Then RealmFileException when call Realm.getDefaultInstance()， but default.realm is exists. The following log：

12-25 02:11:29.940 29972-29972/com.linchaolong.android.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.linchaolong.android.app, PID: 29972
                                                                             io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.linchaolong.android.app/files/default.realm': Not a Realm file. in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92 Kind: ACCESS_ERROR.
                                                                                 at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                                 at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
                                                                                 at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
                                                                                 at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                                                                                 at io.realm.Realm.getDefaultInstance(Realm.java:209)
                                                                                 at com.linchaolong.android.library.orm.RealmUtils.get(RealmUtils.java:72)
                                                                                 at com.linchaolong.android.app.home.DatabaseFragment.onCreate(DatabaseFragment.java:39)
                                                                                 at android.support.v4.app.Fragment.performCreate(Fragment.java:2075)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1060)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                                 at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                                 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
                                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
12-25 02:11:30.014 2591-2591/? E/octvm: open /sys/class/power_supply/battery/status error, No such file or directory
12-25 02:11:30.015 2591-2591/? E/octvm: open /sys/class/power_supply/battery/status error, No such file or directory

**Comment by beeender** [comment]
It should be fixed by #3904 but it has not been released yet. If you can reproduce it in your side, would you please verify if the problem still exists with our snapshot release? See https://github.com/realm/realm-java#using-snapshots about how to use snapshot release.

**Comment by linchaolong** [comment]
I uninstalled after reinstall the app did not see the bug.

**Comment by beeender** [comment]
OK ... Anyway, if the problem still exist with the snapshot release, just feel free to reopen this issue.

**Comment by kimgod** [comment]
I meet the problem now .too
Unable to open a realm at path 
if you know how to fix the problem,please talk me ,thx!

**Comment by beeender** [comment]
@kimgod `v2.2.2` has been released. Please let me know if you still have this problem with `v2.2.2`

**Comment by kimgod** [comment]
@beeender 
(i sorry, i reply to you too later)
yes, I used v2.2.2 .
I deleted the app and installed it again ，next ，i fixd the problem .
And, I hava a new problem .
code :
   RealmConfiguration userConfig = new RealmConfiguration.Builder()
                .name("Cache")
                 .encryptionKey(Encryption.getKey())
                .build();
        return Realm.getInstance(userConfig);
public class Encryption {

    public static  byte[] getKey(){
        byte[] key = new byte[64];
        new SecureRandom().nextBytes(key);
        return key;
    }
}

everytime，I restart the app ,the key will different，How should I do keep the key the same？
thx~

**Comment by Zhuinden** [comment]
You need to store the key somewhere, and use that if it exists. 

You can look at https://github.com/realm/realm-android-user-store to get an idea
