### ISSUE TITLE
signal 7 (SIGBUS), code 2 (BUS_ADRERR)

### ISSUE THREAD

**Issue by ZeroBrain** [realm/realm-java#3951]
* Device : Nexus 5
* OS : Android 6.0.1
* Realm Version : 2.2.1

* When it occurred:
in other app, user share image/text to our app. when that time, it occurred after updating database.

my application avoid to initiate in multi process like this:
```java
ActivityManager activityManager =
        (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
for (ActivityManager.RunningAppProcessInfo processInfo : activityManager.getRunningAppProcesses()) {
    if (Process.myPid() == processInfo.pid) {
        if (TextUtils.equals(processInfo.processName, BuildConfig.APPLICATION_ID)) {
            Realm.init(context);
            Realm.setDefaultConfiguration(realmConfiguration());
        }
        break;
    }
}
```

* error log
```
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30X/3237893:user/release-keys'
 Revision: '11'
 ABI: 'arm'
 pid: 15476, tid: 15615, name: EventThread  >>> com.tosslab.jandi.app <<<
 signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x94675000
     r0 8d038090  r1 94674ff0  r2 00fc7f28  r3 00000008
     r4 92618fa8  r5 00fffff0  r6 00fffff0  r7 00000000
     r8 00000000  r9 00000000  sl 00fffff0  fp 92618f50
12-27 15:07:53.933 199-199/? A/DEBUG:     ip 00000000  sp 92618e30  lr 9e75a51b  pc b6c9765a  cpsr 200b0030
 backtrace:
     #00 pc 0001765a  /system/lib/libc.so (__memcpy_base+81)
     #01 pc 000e1517  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #02 pc 000e14ef  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #03 pc 000e2cab  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #04 pc 000df94b  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #05 pc 000d78b3  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #06 pc 0005786d  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so (Java_io_realm_internal_UncheckedRow_nativeSetString+76)
     #07 pc 024e57e5  /data/app/com.tosslab.jandi.app-2/oat/arm/base.odex (offset 0x15b3000)
```

**Comment by beeender** [comment]
Parsed call stack:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30X/3237893:user/release-keys'
 Revision: '11'
 ABI: 'arm'
 pid: 15476, tid: 15615, name: EventThread  >>> com.tosslab.jandi.app <<<
 signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x94675000
     r0 8d038090  r1 94674ff0  r2 00fc7f28  r3 00000008
     r4 92618fa8  r5 00fffff0  r6 00fffff0  r7 00000000
     r8 00000000  r9 00000000  sl 00fffff0  fp 92618f50
12-27 15:07:53.933 199-199/? A/DEBUG:     ip 00000000  sp 92618e30  lr 9e75a51b  pc b6c9765a  cpsr 200b0030
 backtrace:
     #00 pc 0001765a  /system/lib/libc.so (__memcpy_base+81)
     #01 pc 000e1517  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #02 pc 000e14ef  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #03 pc 000e2cab  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #04 pc 000df94b  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #05 pc 000d78b3  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so
     #06 pc 0005786d  /data/app/com.tosslab.jandi.app-2/lib/arm/librealm-jni.so (Java_io_realm_internal_UncheckedRow_nativeSetString+76)
     #07 pc 024e57e5  /data/app/com.tosslab.jandi.app-2/oat/arm/base.odex (offset 0x15b3000)

```

**Comment by beeender** [comment]
@ZeroBrain
1. Can you reproduce this issue? 
2. I can see when it crashed, the app tried to write some string into the database. How big the string is?

**Comment by ZeroBrain** [comment]
hm...let me do this again.

**Comment by ZeroBrain** [comment]
@beeender I'm not sure it's same.
when I try to reproduce this issue, I've got this error.

```
io.realm.exceptions.RealmError: Unrecoverable error. Failure when converting short string to UTF-16 error_code = 1; retcode = 0; StringData.size = 26; StringData.data = UD Email的排程和內偁; StringData as hex =  0x55 0x44 0x20 0x45 0x6d 0x61 0x69 0x6c 0xffffffe7 0xffffff9a 0xffffff84 0xffffffe6 0xffffff8e 0xffffff92 0xffffffe7 0xffffffa8 0xffffff8b 0xffffffe5 0xffffff92 0xffffff8c 0xffffffe5 0xffffff85 0xffffffa7 0xffffffe5 0x41 0x41; in_begin = 偁AA; in_end = AA; out_curr = 0xbeab67f2; out_end = 0xbeab6838; in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 136
	at io.realm.internal.UncheckedRow.nativeGetString(Native Method)
	at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:153)
	at io.realm.TopicRealmProxy.realmGet$description(TopicRealmProxy.java:358)
	at io.realm.TopicRealmProxy.createDetachedCopy(TopicRealmProxy.java:2024)
	at io.realm.InitialInfoRealmProxy.createDetachedCopy(InitialInfoRealmProxy.java:2435)
	at io.realm.DefaultRealmModuleMediator.createDetachedCopy(DefaultRealmModuleMediator.java:702)
	at io.realm.Realm.createDetachedCopy(Realm.java:1459)
	at io.realm.Realm.copyFromRealm(Realm.java:1201)
	at io.realm.Realm.copyFromRealm(Realm.java:1174)
	at com.tosslab.jandi.app.local.orm.repositories.info.InitialInfoRepository.lambda$getInitialInfo$2(InitialInfoRepository.java:34)
	at com.tosslab.jandi.app.local.orm.repositories.info.InitialInfoRepository$$Lambda$2.execute(Unknown Source)
	at com.tosslab.jandi.app.local.orm.repositories.realm.RealmRepository.execute(RealmRepository.java:28)
...
```

is this relate to CJK charset?
My service is targeting to CJK.

**Comment by beeender** [comment]
They could be the same issue! Is it possible to share your project with us and let us know the steps to reproduce it? It might be an issue that we tried to reproduce for a really long time.

If you can share it, you can send it to help@realm.io . Otherwise can you please share your email address? We can try to contact you to figure out a way to solve it.

Thanks!

**Comment by beeender** [comment]
cc @dalinaum

**Comment by ZeroBrain** [comment]
@beeender you mean you need my project's source code?
If that, I'm sorry not to share it. but I could contact to @dalinaum . I will contact to him on off-line.
Through him, I could share it.

**Comment by ZeroBrain** [comment]
I've got contact with @dalinaum . I will check it on snapshot-version.

**Comment by ZeroBrain** [comment]
@beeender @dalinaum on 2.3.0-SNAPSHOT, I tried to reproduce it. but I didn't occur anymore.
I think it would be fixed on next version. :)

**Comment by beeender** [comment]
OK! We will make a release soon. I am closing this issue now, feel free to reopen it if the issue still exist.

**Comment by ZeroBrain** [comment]
@beeender could you tell me when this patch would be released?
