### ISSUE TITLE
ThrowingException 5 - Unrecoverable error

### ISSUE THREAD

**Issue by mitchwongho** [realm/realm-java#3964]
#### Goal

> I've been performing further tests on Realms observable Realms models since I have experienced issues previously [(see issue)](https://github.com/realm/realm-java/issues/3821) in order measure memory usage and performance.

#### Expected Results

> Did not expect the error to occurs so quickly.

#### Actual Results

>  Extending a test app created @beeender , I've managed to experience an exception *ThrowingException 5 - Unrecoverable error* when the `RealmResult` exceeds 65535, which looks suspicious:

```
12-29 20:35:11.926 14227-14277/tt.test.realmrxtest E/REALM_JNI: jni: ThrowingException 5, Try again in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 123, .
12-29 20:35:11.926 14227-14277/tt.test.realmrxtest E/REALM_JNI: Exception has been throw: Unrecoverable error. Try again in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 123
```

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

I've issued a [PR](https://github.com/beeender/RealmRxTest/pull/1) on the project created by @beeender 

#### Version of Realm and tooling
Realm version(s): `2.3.0-SNAPSHOT`

Realm sync feature enabled: no

Android Studio version: 2.3 Beta 1

Which Android version and device: Nexus 5 (5.1.1)

**Comment by beeender** [comment]
Sounds like it reached a limit somewhere ... I will take a look.

**Comment by mitchwongho** [comment]
@Zhuinden on the the `insert`

**Comment by beeender** [comment]
@mitchwongho I tried with your PR, cannot reproduce the problem ...
Can you share the complete exception message here? Better with some logs before. Thanks!

**Comment by mitchwongho** [comment]
Adding a `Throwable.printStackTrace()`

```
12-30 09:20:52.270 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 115880(6MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 39MB/55MB, paused 19.693ms total 447.316ms
12-30 09:20:57.836 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 123.050ms
12-30 09:20:57.911 10520-10536/tt.test.realmrxtest I/art: Background sticky concurrent mark sweep GC freed 133070(4MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 50MB/55MB, paused 4.228ms total 209.629ms
12-30 09:20:59.320 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 101.737ms
12-30 09:20:59.344 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 644517(20MB) AllocSpace objects, 0(0B) LOS objects, 30% free, 36MB/52MB, paused 11.633ms total 449.856ms
12-30 09:21:01.728 10520-10520/tt.test.realmrxtest D/MainActivity: #1 Got Dogs {threadId=1,size=65004}
12-30 09:21:02.141 10520-10551/tt.test.realmrxtest E/REALM_JNI: jni: ThrowingException 5, Try again in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 123, .
12-30 09:21:02.142 10520-10551/tt.test.realmrxtest E/REALM_JNI: Exception has been throw: Unrecoverable error. Try again in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 123
12-30 09:21:02.142 10520-10551/tt.test.realmrxtest W/REALM_JAVA: Could not cancel transaction, not currently in a transaction.
12-30 09:21:02.144 10520-10551/tt.test.realmrxtest W/System.err: io.realm.exceptions.RealmError: Unrecoverable error. Try again in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 123
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at io.realm.internal.SharedRealm.nativeCommitTransaction(Native Method)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:224)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:349)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:338)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at io.realm.Realm.commitTransaction(Realm.java:125)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at io.realm.Realm.executeTransaction(Realm.java:1254)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at tt.test.realmrxtest.MainActivity.insertDog(MainActivity.java:127)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at tt.test.realmrxtest.MainActivity.access$000(MainActivity.java:23)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at tt.test.realmrxtest.MainActivity$9.call(MainActivity.java:97)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at tt.test.realmrxtest.MainActivity$9.call(MainActivity.java:94)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at rx.Observable$11.onNext(Observable.java:4445)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at rx.Scheduler$Worker$1.call(Scheduler.java:120)
12-30 09:21:02.145 10520-10551/tt.test.realmrxtest W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: 65536
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:187)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err: 	... 10 more
12-30 09:21:02.749 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 7.748ms
12-30 09:21:02.769 10520-10536/tt.test.realmrxtest I/art: Background sticky concurrent mark sweep GC freed 136547(4MB) AllocSpace objects, 0(0B) LOS objects, 7% free, 48MB/52MB, paused 3.404ms total 239.853ms
12-30 09:21:03.774 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 27.239ms
12-30 09:21:03.801 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 693260(24MB) AllocSpace objects, 0(0B) LOS objects, 35% free, 28MB/44MB, paused 5.074ms total 340.597ms
12-30 09:21:07.253 10520-10536/tt.test.realmrxtest I/art: Background sticky concurrent mark sweep GC freed 139222(4MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 40MB/44MB, paused 6.478ms total 268.388ms
12-30 09:21:08.235 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 105076(5MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 39MB/55MB, paused 11.930ms total 310.749ms
12-30 09:21:08.329 10520-10520/tt.test.realmrxtest D/MainActivity: #2 Got Dogs {threadId=1,size=65004}
12-30 09:21:13.437 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 134.040ms
12-30 09:21:13.502 10520-10536/tt.test.realmrxtest I/art: Background sticky concurrent mark sweep GC freed 128686(4MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 50MB/55MB, paused 2.341ms total 209.330ms
12-30 09:21:14.826 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 13.446ms
12-30 09:21:14.845 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 634465(20MB) AllocSpace objects, 0(0B) LOS objects, 30% free, 36MB/52MB, paused 9.968ms total 425.203ms
12-30 09:21:17.124 10520-10520/tt.test.realmrxtest D/MainActivity: #1 Got Dogs {threadId=1,size=65537}
12-30 09:21:18.275 10520-10536/tt.test.realmrxtest I/art: Background sticky concurrent mark sweep GC freed 135933(4MB) AllocSpace objects, 0(0B) LOS objects, 7% free, 48MB/52MB, paused 2.883ms total 201.012ms
12-30 09:21:19.275 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 691558(24MB) AllocSpace objects, 0(0B) LOS objects, 35% free, 29MB/45MB, paused 3.877ms total 317.725ms
12-30 09:21:22.681 10520-10536/tt.test.realmrxtest I/art: Background sticky concurrent mark sweep GC freed 136378(4MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 40MB/45MB, paused 4.926ms total 178.928ms
12-30 09:21:23.718 10520-10536/tt.test.realmrxtest I/art: Background partial concurrent mark sweep GC freed 105986(5MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 40MB/56MB, paused 9.643ms total 294.295ms
12-30 09:21:23.737 10520-10520/tt.test.realmrxtest D/MainActivity: #2 Got Dogs {threadId=1,size=65537}
12-30 09:24:49.771 10520-10531/tt.test.realmrxtest W/art: Suspending all threads took: 38.451ms
```

**Comment by beeender** [comment]
@mitchwongho see the exception cause:
```
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: 65536
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:187)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err:     at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
12-30 09:21:02.146 10520-10551/tt.test.realmrxtest W/System.err: 	... 10 more
```

It sounds like a rxJava limitaion?

**Comment by beeender** [comment]
I can reproduce this now. checking ...
