### ISSUE TITLE
Realm 1.2.0: createAllFromJson fails on objects with @PrimaryKey

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3965]
#### Goal

> What do you want to achieve?

Use `createAllFromJson()` 

#### Expected Results

It should read the data.

#### Actual Results

FATAL EXCEPTION: IntentService[LoadRealmDBIntentService]
                                                                io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0
                                                                    at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:727)
                                                                    at io.realm.internal.Table.addEmptyRow(Table.java:414)
                                                                    at io.realm.Realm.createObject(Realm.java:681)
                                                                    at io.realm.IngredientsRealmProxy.createUsingJsonStream(IngredientsRealmProxy.java:168)
                                                                    at io.realm.DefaultRealmModuleMediator.createUsingJsonStream(DefaultRealmModuleMediator.java:754)
                                                                    at io.realm.Realm.createAllFromJson(Realm.java:428)

#### Version of Realm and tooling
Realm version(s): 1.2.0

Realm sync feature enabled: no

Android Studio version: .

Which Android version and device: .

**Comment by Zhuinden** [comment]
Fixed by https://github.com/realm/realm-java/pull/3379 in Realm 2.0
