### ISSUE TITLE
IllegalStateException in TableQuery.java io.realm.internal.TableQuery.nativeBeginsWith

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#4105]
This is the crash report http://crashes.to/s/960b859dc84

```
Fatal Exception: java.lang.IllegalArgumentException
Illegal Argument: in_begin != in_end when converting to UTF-8; error_code = 4; 0x0025 0x092e 0x0948 0x0921 0x092e 0x0020 0x002d 0x0020 0x0924 0x0941 0x092e 0x094d 0x0939 0x093e 0x0930 0x093e 0x0020 0x0915 0x094d 0x092f 0x093e 0x0020 0x0928 0x093e 0x092e 0x0020 0x0939 0x0948 0x0020 0x005f 0x0025 0x000a 0x000a 0x0025 0x0932 0x095c 0x0915 0x093e 0x0020 0x002d 0x0020 0x006c 0x0061 0x0078 0x006d 0x0069 0x0020 0x0041 0x006e 0x0061 0x006e 0x0064 0x0020 0x004e 0x0061 0x0072 0x0061 0x0079 0x0061 0x006e 0x0020 0x0044 0x0061 0x0073 0x002e 0x0025 0x000a 0x000a 0x0025 0x092e 0x0948 0x0921 0x092e 0x0020 0x002d 0x0020 0x0936 0x094b 0x0930 0x094d 0x091f 0x0020 0x092e 0x0947 0x0902 0x0020 0x092c 0x0924 0x093e 0x0913 0x0020 0x092c 0x0939 0x094b 0x0924 0x0020 0x0932 0x0902 0x092c 0x093e 0x0020 0x0939 0x0948 0x0964 0x0025 0x000a 0x000a 0x0025 0x0932 0x095c 0x0915 0x093e 0x0020 0x002d 0x0020 0x004c 0x0041 0x004e 0x0044 0x0025 0x0020 0x000a 0x000a 0x0025 0x092e 0x0948 0x0921 0x092e 0x0020 0x002d 0x0020 0x092d 0x093e 0x0917 0x0020 0x092e 0x093e 0x0926 0x0930 0x091a 0x094b 0x0926 0x002c 0x0020 0x0932 0x0902 0x092c 0x093e 0x0020 0x0915 0x0930 0x0020 0x0964 0x0025 0x000a 0x000a 0x0025 0x0932 0x095c 0x0915 0x093e 0x0020 0x002d 0x0020 0x0915 0x094d 0x092f 0x093e 0x0020 0x0932 0x0902 0x0921 0x0025 0x000a 0x000a 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1b 0xd83d 0xde1d 0xd83d in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 892
 Raw Text
io.realm.internal.TableQuery.nativeBeginsWith (TableQuery.java)
io.realm.internal.TableQuery.beginsWith (TableQuery.java:376)
io.realm.RealmQuery.beginsWith (RealmQuery.java:1220)
```

#### Version of Realm and tooling
Realm version(s):  2.2.0

Realm sync feature enabled: no

Android Studio version: 2.1.2

**Comment by kneth** [comment]
The link above is blocked. If you don't wish to share information in public, feel free to send an email to help@realm.io.

I will try to create a unit test using the string in your report to reproduce the error.

**Comment by mihirjoshi21** [comment]
I think crashlytics share links are not working. Here is the full crashlog

```
Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: in_begin != in_end when converting to UTF-8; error_code = 4;  0x0025 0x092e 0x0948 0x0921 0x092e 0x0020 0x002d 0x0020 0x0924 0x0941 0x092e 0x094d 0x0939 0x093e 0x0930 0x093e 0x0020 0x0915 0x094d 0x092f 0x093e 0x0020 0x0928 0x093e 0x092e 0x0020 0x0939 0x0948 0x0020 0x005f 0x0025 0x000a 0x000a 0x0025 0x0932 0x095c 0x0915 0x093e 0x0020 0x002d 0x0020 0x006c 0x0061 0x0078 0x006d 0x0069 0x0020 0x0041 0x006e 0x0061 0x006e 0x0064 0x0020 0x004e 0x0061 0x0072 0x0061 0x0079 0x0061 0x006e 0x0020 0x0044 0x0061 0x0073 0x002e 0x0025 0x000a 0x000a 0x0025 0x092e 0x0948 0x0921 0x092e 0x0020 0x002d 0x0020 0x0936 0x094b 0x0930 0x094d 0x091f 0x0020 0x092e 0x0947 0x0902 0x0020 0x092c 0x0924 0x093e 0x0913 0x0020 0x092c 0x0939 0x094b 0x0924 0x0020 0x0932 0x0902 0x092c 0x093e 0x0020 0x0939 0x0948 0x0964 0x0025 0x000a 0x000a 0x0025 0x0932 0x095c 0x0915 0x093e 0x0020 0x002d 0x0020 0x004c 0x0041 0x004e 0x0044 0x0025 0x0020 0x000a 0x000a 0x0025 0x092e 0x0948 0x0921 0x092e 0x0020 0x002d 0x0020 0x092d 0x093e 0x0917 0x0020 0x092e 0x093e 0x0926 0x0930 0x091a 0x094b 0x0926 0x002c 0x0020 0x0932 0x0902 0x092c 0x093e 0x0020 0x0915 0x0930 0x0020 0x0964 0x0025 0x000a 0x000a 0x0025 0x0932 0x095c 0x0915 0x093e 0x0020 0x002d 0x0020 0x0915 0x094d 0x092f 0x093e 0x0020 0x0932 0x0902 0x0921 0x0025 0x000a 0x000a 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1d 0xd83d 0xde1b 0xd83d 0xde1d 0xd83d in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 892
       at io.realm.internal.TableQuery.nativeBeginsWith(TableQuery.java)
       at io.realm.internal.TableQuery.beginsWith(TableQuery.java:376)
       at io.realm.RealmQuery.beginsWith(RealmQuery.java:1220)
       at com.conem.app.pocketthesaurus.display.FragmentActivityMain$2.onTextChanged(FragmentActivityMain.java:174)
       at android.widget.TextView.sendOnTextChanged(TextView.java:7826)
       at android.widget.TextView.handleTextChanged(TextView.java:7885)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10066)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
       at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:257)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:451)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:95)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

![new bitmap image](https://cloud.githubusercontent.com/assets/5195121/22324444/5963c532-e3cf-11e6-9001-436a90a699bb.jpg)

**Comment by kneth** [comment]
The error message originates from the conversion from Java strings to plain UTF-8 strings (which are used by Realm Core - our storage/query engine). The Java string might have been split wrongly (for example an emoji's surrogate pair using `String.substring()`).  It is a rather long string (194 2 bytes values).

The last value is `0xD83D` which is the high surrogate on an iOS emoji: http://punchdrunker.github.io/iOSEmoji/table_html/

I suggest that you see how the string for the `beginsWith()` query is constructed.

**Comment by mihirjoshi21** [comment]
Here is how it is constructed 

`realmResults = mRealm.where(FieldModel.class).beginsWith(FIELD_WORD, String.valueOf(s).trim(),
                Case.INSENSITIVE).distinct(FIELD_WORD)`

**Comment by kneth** [comment]
It could be interesting to know what `String.valueOf(s)` was? I mean, `trim()` is supposed to remove white spaces but as I said in my previous comments, you will see this error if `trim()` has removed data which is part of a surrogate pair. `0xD38D` is the first half for an iOS emoji.

**Comment by mihirjoshi21** [comment]
`s` is a `CharSequence`  from `TextWatcher`. I tried using almost all emojis in `EditText` but unable to reproduce this issue.

**Comment by kneth** [comment]
0xd83d is half of an emoji. Are you sure that `String.valueOf()` isn't truncating the sequence? It might be safer to do `s.toString().trim()`.

**Comment by mihirjoshi21** [comment]
Alright, I will do it in next release. You can mark this as close I will reopen it if I have to.
