### ISSUE TITLE
Realm receives NPE when updating async queries after Realm is closed

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#4131]
#### Goal

> What do you want to achieve?

Write into Realm periodically and also run async queries.

#### Expected Results

No exceptions in the log

#### Actual Results

      2-01 09:53:49.315 4201-4229/com.zhuinden.realmbreak E/REALM_JAVA: java.lang.NullPointerException
                                                                       at io.realm.AndroidNotifier.completeAsyncResults(AndroidNotifier.java:120)
                                                                       at io.realm.RealmQuery.closeSharedRealmAndSendEventToNotifier(RealmQuery.java:2233)
                                                                       at io.realm.RealmQuery.access$000(RealmQuery.java:62)
                                                                       at io.realm.RealmQuery$3.call(RealmQuery.java:1863)
                                                                       at io.realm.RealmQuery$3.call(RealmQuery.java:1845)
                                                                       at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                       at java.lang.Thread.run(Thread.java:856)
      02-01 09:53:53.735 4201-4229/com.zhuinden.realmbreak E/REALM_JAVA: java.lang.NullPointerException
                                                                       at io.realm.AndroidNotifier.completeUpdateAsyncQueries(AndroidNotifier.java:145)
                                                                       at io.realm.internal.async.QueryUpdateTask.run(QueryUpdateTask.java:112)
                                                                       at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                       at java.lang.Thread.run(Thread.java:856)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

`Word` table contains 440000 entries.

```java

public class MainActivity
        extends AppCompatActivity {
    @BindView(R.id.recycler_view)
    RecyclerView recyclerView;

    Realm realm;

    Subscription subscription;

    @Override
    @SuppressWarnings("NewApi")
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);
        realm = Realm.getDefaultInstance();
        recyclerView.setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false));
        recyclerView.setAdapter(new RealmRecyclerViewAdapter<Word, ViewHolder>(this, realm.where(Word.class).findAllSortedAsync(WordFields.WORD), true) {
            @Override
            public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                return new ViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.item_row, parent, false));
            }

            @Override
            public void onBindViewHolder(ViewHolder holder, int position) {
                holder.bind(getData().get(position));
            }
        });
        subscription = Observable.interval(50, TimeUnit.MILLISECONDS).subscribeOn(Schedulers.io()).subscribe(aLong -> {
            try(Realm realm = Realm.getDefaultInstance()) {
                realm.executeTransaction(_realm -> {
                    String dogName = DogNames.values()[(((Long)(aLong)).intValue()) % DogNames.values().length].name();
                    Log.i("WRITE", "Writing to Realm at [" + aLong + "]: [" + dogName + "]");
                    Word word = new Word();
                    word.setWord(dogName);
                    CustomApplication.wordToLetters(word, dogName);
                    _realm.insert(word);
                });
            }
        });
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        @BindView(R.id.row_text)
        TextView word;

        public ViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
        }

        public void bind(Word word) {
            this.word.setText(word.getWord());
        }
    }

    @Override
    protected void onDestroy() {
        if(subscription != null && !subscription.isUnsubscribed()) {
            subscription.unsubscribe();
            subscription = null;
        }
        if(realm != null && !realm.isClosed()) {
            realm.close();
            realm = null;
        }
        super.onDestroy();
    }
}
``` 

#### Version of Realm and tooling
Realm version(s): 2.3.0

Realm sync feature enabled: no

Which Android version and device: 4.2.2

**Comment by Zhuinden** [comment]
I added complete code in https://github.com/Zhuinden/realm-error-4131

Either rotate the screen or press back, then these show up in the logs.

**Comment by zaki50** [comment]
@Zhuinden #3834 has been merged into `master` branch.
Is this issue solved in snapshot release?

**Comment by Zhuinden** [comment]
```
02-28 15:26:47.093 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
02-28 15:26:47.101 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm -1211381160
02-28 15:26:47.101 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion -1207175032
02-28 15:26:47.101 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeSetAutoRefresh -1207175032
02-28 15:26:47.101 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig -1211381160
02-28 15:26:47.101 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion -1207175032
02-28 15:26:47.101 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed -1207175032
02-28 15:26:47.105 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetTable -1207175032
02-28 15:26:47.105 25272-25272/com.zhuinden.realmbreak V/REALM_JNI:  --> Java_io_realm_internal_Collection_nativeCreateResults
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table_query -1211170488
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table_query -1211284328
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table_query -1211283328
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table_query -1211554096
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_results -1211312696
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_results -1206870688
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table -1206635448
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_shared_realm -1211188784
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_results -1211261776
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table -1211145368
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_shared_realm -1211602896
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_results -1211144440
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table -1211162656
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_shared_realm -1211715592
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_table -1206810896
02-28 15:26:47.109 25272-25285/com.zhuinden.realmbreak V/REALM_JNI:  --> finalize_shared_realm -1211402824
```

Results get properly finalized and no exception is thrown.
