### ISSUE TITLE
asObservable doesn't support backpressure

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4137]
From http://stackoverflow.com/questions/37774954/onerrornotimplementedexception-caused-by-rx-exceptions-missingbackpressureexcep

```
rx.exceptions.OnErrorNotImplementedException at rx.Observable$27.onError(Observable.java:8139)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onError(OperatorZip.java:325)
    at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:333)
    at io.realm.rx.RealmObservableFactory$5$1.onChange(RealmObservableFactory.java:143)
    at io.realm.rx.RealmObservableFactory$5$1.onChange(RealmObservableFactory.java:139)
    at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:1010)
    at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:996)
    at io.realm.HandlerController.notifyRealmResultsCallbacks(HandlerController.java:303)
    at io.realm.HandlerController.notifySyncRealmResultsCallbacks(HandlerController.java:284)
    at io.realm.HandlerController.notifyTypeBasedListeners(HandlerController.java:275)
    at io.realm.HandlerController.notifyAllListeners(HandlerController.java:262)
    at io.realm.HandlerController.realmChanged(HandlerController.java:385)
    at io.realm.HandlerController.handleMessage(HandlerController.java:116)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: rx.exceptions.MissingBackpressureException
    at rx.internal.util.RxRingBuffer.onNext(RxRingBuffer.java:352)
    at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:331)
    at io.realm.rx.RealmObservableFactory$5$1.onChange(RealmObservableFactory.java:143) 
    at io.realm.rx.RealmObservableFactory$5$1.onChange(RealmObservableFactory.java:139) 
    at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:1010) 
    at io.realm.RealmResults.notifyChangeListeners(RealmResults.java:996) 
    at io.realm.HandlerController.notifyRealmResultsCallbacks(HandlerController.java:303) 
    at io.realm.HandlerController.notifySyncRealmResultsCallbacks(HandlerController.java:284) 
    at io.realm.HandlerController.notifyTypeBasedListeners(HandlerController.java:275) 
    at io.realm.HandlerController.notifyAllListeners(HandlerController.java:262) 
    at io.realm.HandlerController.realmChanged(HandlerController.java:385) 
    at io.realm.HandlerController.handleMessage(HandlerController.java:116) 
    at android.os.Handler.dispatchMessage(Handler.java:98) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

It looks like we might not support backpressure correctly.

**Comment by Zhuinden** [comment]
At worst it should call `onBackpressureLatest`

**Comment by cmelchior** [comment]
With the move to RxJava2 this is no longer relevant. Closing.
