### ISSUE TITLE
Gson StackOverflow ,when use primarykey

### ISSUE THREAD

**Issue by itxuye** [realm/realm-java#4173]
I got this problem.
`java.lang.StackOverflowError
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
                                                                               at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:358)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
                                                                               at com.google.gson.Gson.getAdapter(Gson.java:423)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
                                                                               at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
                                                                               at com.google.gson.Gson.getAdapter(Gson.java:423)
                                                                           	at com.google.gson.in`

**Comment by itxuye** [comment]
Here is my bean.
`public class InventoryBean extends RealmObject {

  /**
   * code : XL10010
   * location : JC001
   * time : 2016-12-21 23:13:34
   */
  @PrimaryKey
  private String code;
  private String location;
  private int type;
  private String time;

  public int getType() {
    return type;
  }

  public void setType(int type) {
    this.type = type;
  }

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public String getTime() {
    return time;
  }

  public void setTime(String time) {
    this.time = time;
  }
  
}`

**Comment by Zhuinden** [comment]
1.) you are most likely using an old version of Realm

2.) 

    Gson gson = new GsonBuilder()
        .setExclusionStrategies(new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(RealmObject.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        })
        .create();

**Comment by itxuye** [comment]
@Zhuinden  I used realm 2.3.0version .And i also have used the gsonbuilder.I want gson.toJson(List<XXXX>) and have used all the doc but didn't work.

**Comment by itxuye** [comment]
@Zhuinden I should post list like this .
` @POST("api/v1/tools/inventory")
  Observable<Response<InvenoryResultBean>> doInventory(
      @Body List<InventoryBean> inventoryBeanList
 );`

**Comment by itxuye** [comment]
`Subscription subscribe = dbHelper.queryInventoryBean()
        .asObservable()
        .filter(RealmResults::isLoaded)
        .flatMap(
            new Func1<RealmResults<InventoryBean>, Observable<Response<InvenoryResultBean>>>() {
              @Override public Observable<Response<InvenoryResultBean>> call(
                  RealmResults<InventoryBean> inventoryBeen) {
                return zzjxRetrofitClient.doInventory(inventoryBeen);
              }
            })
        .map(Response::body)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(invenoryResultBean -> {
          mView.handledata(invenoryResultBean);
          mView.hideProgressBar();
        }, throwable -> {
          Logger.i(throwable.getLocalizedMessage());
          mView.hideProgressBar();
        });`

**Comment by Zhuinden** [comment]
Please format your code a bit better because currently I can't really read it

Use 3 backticks like ` ` ` java

``` java
    Subscription subscribe = dbHelper.queryInventoryBean() .asObservable() .filter(RealmResults::isLoaded) .flatMap( new Func1<RealmResults<InventoryBean>, Observable<Response<InvenoryResultBean>>>() { @Override public Observable<Response<InvenoryResultBean>> call( RealmResults<InventoryBean> inventoryBeen) { return zzjxRetrofitClient.doInventory(inventoryBeen); } }) .map(Response::body) .observeOn(AndroidSchedulers.mainThread()) .subscribe(invenoryResultBean -> { mView.handledata(invenoryResultBean); mView.hideProgressBar(); }, throwable -> { Logger.i(throwable.getLocalizedMessage()); mView.hideProgressBar(); });
```

but with whitespaces and stuff

**Comment by itxuye** [comment]
@timanglade Sorry.

**Comment by itxuye** [comment]
```java
  public RealmResults<InventoryBean> queryInventoryBean() {
    return mRealm.where(InventoryBean.class).findAllAsync();
  }
```

**Comment by itxuye** [comment]
@Zhuinden Thank you .I have solved the problem.
I used 
```java
dbHelper.getmRealm().copyFromRealm(inventoryBeen)
```

**Comment by Zhuinden** [comment]
You need to replace `return zzjxRetrofitClient.doInventory(inventoryBeen);` with `return zzjxRetrofitClient.doInventory(realm.copyFromRealm(inventoryBeen));

Oh you've just solved it, whoops

**Comment by itxuye** [comment]
@Zhuinden Thanks a lot. This is my first time to use realm .It's a great tool.
