### ISSUE TITLE
Realm crashes app on first run when using Realm version 2.2.2-2.3.1

### ISSUE THREAD

**Issue by lohnn** [realm/realm-java#4178]
Hi.

We've got a problem when using Realm version 2.2.2 or (so far) all 2.3.x versions in Android.
We initialize Realm from a ContentProvider:

```Kotlin
fun initialize(context: Context) {
  Realm.init(context)
  defaultConfiguration = RealmConfiguration.Builder()
     .name("default.realm")
     .schemaVersion(1)
     .migration(StorageMigration())
     .build()
  Realm.setDefaultConfiguration(defaultConfiguration)
}
```

All is fine and dandy in debug builds, but as soon as we do a release build using Realm 2.2.2 or 2.3.x it crashes the first time we use the Realm database. After a restart however, everything seems to be working again.

#### Stacktrace
```
Fatal Exception: io.realm.exceptions.RealmFileException: No such file or directory () in /Users/blakemeike/Working/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 94
at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:211)
at io.realm.BaseRealm.<init>(BaseRealm.java:82)
at io.realm.Realm.<init>(Realm.java:138)
at io.realm.Realm.createAndValidate(Realm.java:283)
at io.realm.Realm.createInstance(Realm.java:264)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
at io.realm.Realm.getInstance(Realm.java:227)
at se.mycompany.storagemodule.Storage$Companion.getPersistRealm(Storage.kt:58)
at se.mycompany.storagemodule.Storage$Companion.getSubscriptions(Storage.kt:113)
at se.mycompany.ui.fragment.NearMeFragment.onCreateView(NearMeFragment.kt:113)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Removing migration and using deleteRealmIfMigrationNeeded() does not help either, so it seems like it's not our migration process.

#### Version of Realm and tooling
Realm version(s):
Working: <=2.2.1
Not working: 2.2.2 - 2.3.1

Realm sync feature enabled: No

Android Studio version: 2.2.3

Which Android version and device:
The problem occurs on all devices we've tested, Android versions all way from 5.0.1 - 7.1.1

**Comment by Zhuinden** [comment]
You're going to hate my question, but can you try running `Realm.init(Context)` and the others before `super.onCreate()` in a `BaseActivity`?

**Comment by lohnn** [comment]
@Zhuinden That does fixe the crash.
However, we are using Realm in a library project, that we don't always have included in our apps. Hence the reason for us to initialize Realm in a ContentProvider.

**Comment by Zhuinden** [comment]
I guess underlying issue is that `contentProvider.getApplicationContext().getFilesDir()` returns `null` for default `directory()` parameter.

**Comment by beeender** [comment]
@Zhuinden 
I am a bit lost. When would the `contentProvider.getApplicationContext().getFilesDir()` return `null`?

@lohnn 
What is the `context` passed to `initialize`?

**Comment by lohnn** [comment]
@beeender 
```Java
public class InitContentProvider extends AbstractInitContentProvider {
    @Override
    public void init(Context context) {
        Storage.Companion.initialize(context);
    }
}
```

**Comment by lohnn** [comment]
@beeender 
ContentProvider.this.getApplicationContext() in onCreate of the ContentProvider.

**Comment by beeender** [comment]
@lohnn I added the `path` information to the `RealmFileException` in https://github.com/realm/realm-java/pull/4180 . 

Is it possible for you to share the release apk file with me so i can replace the `so` file and repack the apk to get some more information to debug? Send it to help@realm.io if you can share it privately. Thanks a lot.

**Comment by kneth** [comment]
@lohnn Since #4180 is to be released soon, I suggest that you upgrade. If the error persists, please either reopen or create new issue.
