### ISSUE TITLE
Random crash on 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4405]
1) schemaVersion_throwsIfNotUpdatedForSchemaUpgrade

```
03-30 10:00:39.196  7319  7845 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xde39095c in tid 7845 (Thread-710)
03-30 10:00:39.297   102   102 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-30 10:00:39.297   102   102 F DEBUG   : Build fingerprint: 'Android/vbox86p/vbox86p:6.0/MRA58K/genymotion08241314:userdebug/test-keys'
03-30 10:00:39.297   102   102 F DEBUG   : Revision: '0'
03-30 10:00:39.297   102   102 F DEBUG   : ABI: 'x86'
03-30 10:00:39.297   102   102 F DEBUG   : pid: 7319, tid: 7845, name: Thread-710  >>> io.realm.test <<<
03-30 10:00:39.297   102   102 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xde39095c
03-30 10:00:39.301   102   102 F DEBUG   :     eax da9f5578  ebx deb92ce4  ecx 00000004  edx da9f5578
03-30 10:00:39.301   102   102 F DEBUG   :     esi dc470cc8  edi de390958
03-30 10:00:39.301   102   102 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 000000cf  xss 0000002b
03-30 10:00:39.301   102   102 F DEBUG   :     eip de8fc16b  ebp da9f5558  esp da9f5540  flags 00210206
03-30 10:00:39.303   102   102 F DEBUG   : 
03-30 10:00:39.303   102   102 F DEBUG   : backtrace:
03-30 10:00:39.303   102   102 F DEBUG   :     #00 pc 0026b16b  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #01 pc 0016e74f  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #02 pc 002ebdcf  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #03 pc 002ec17e  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #04 pc 002f01aa  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #05 pc 002f0247  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #06 pc 00177deb  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #07 pc 001767a9  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #08 pc 0016290b  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #09 pc 00163039  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #10 pc 0017c8b0  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #11 pc 0016d671  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #12 pc 0014eed5  /data/app/io.realm.test-1/lib/x86/librealm-jni.so (_ZNSt6thread5_ImplISt12_Bind_simpleIFZN5realm5_impl10SyncClientC4ESt10unique_ptrINS2_4util6LoggerESt14default_deleteIS7_EENS2_4sync6Client13ReconnectModeEbEUlvE_vEEE6_M_runEv+75)
03-30 10:00:39.303   102   102 F DEBUG   :     #13 pc 0038cf7e  /data/app/io.realm.test-1/lib/x86/librealm-jni.so
03-30 10:00:39.303   102   102 F DEBUG   :     #14 pc 000807f3  /system/lib/libc.so (__pthread_start(void*)+56)
03-30 10:00:39.303   102   102 F DEBUG   :     #15 pc 00021952  /system/lib/libc.so (__start_thread+25)
03-30 10:00:39.303   102   102 F DEBUG   :     #16 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)
03-3
```

2) io.realm.objectserver.ProgressListenerTests.downloadProgressListener_indefinitely
```
03-30 15:54:39.591 E/AndroidRuntime(17519): FATAL EXCEPTION: Thread-3174
03-30 15:54:39.591 E/AndroidRuntime(17519): Process: io.realm.test, PID: 17519
03-30 15:54:39.591 E/AndroidRuntime(17519): junit.framework.AssertionFailedError: Test took longer than 60 seconds
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at junit.framework.Assert.fail(Assert.java:50)
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at io.realm.TestHelper.awaitOrFail(TestHelper.java:791)
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at io.realm.TestHelper.awaitOrFail(TestHelper.java:781)
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at io.realm.objectserver.ProgressListenerTests.createRemoteData(ProgressListenerTests.java:96)
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at io.realm.objectserver.ProgressListenerTests.access$100(ProgressListenerTests.java:50)
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at io.realm.objectserver.ProgressListenerTests$3.run(ProgressListenerTests.java:144)
03-30 15:54:39.591 E/AndroidRuntime(17519): 	at java.lang.Thread.run(Thread.java:818)
03-30 15:54:39.673 W/ActivityManager(  628): Error in app io.realm.test running instrumentation ComponentInfo{io.realm.test/android.support.test.runner.AndroidJUnitRunner}:
03-30 15:54:39.674 W/ActivityManager(  628):   junit.framework.AssertionFailedError
03-30 15:54:39.675 W/ActivityManager(  628):   junit.framework.AssertionFailedError: Test took longer than 60 seconds
03-30 15:54:39.799 D/AndroidRuntime(17505): Shutting down VM
03-30 15:54:40.217 I/ActivityManager(  628): Force stopping io.realm.test appid=11451 user=0: finished inst
03-30 15:54:40.221 I/ActivityManager(  628): Killing 17519:io.realm.test/u0a1451 (adj 0): stop io.realm.test
```

3) io.realm.SyncConfigurationTests.schemaVersion_bumpWhenUpgradingSchema

```
--------- beginning of crash
03-30 12:15:27.353 F/libc    (12283): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1bc in tid 12829 (Thread-2777)
03-30 12:15:27.457 I/DEBUG   (  189): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-30 12:15:27.457 I/DEBUG   (  189): Build fingerprint: 'nvidia/sb_na_wf/shieldtablet:5.1.1/LMY48C/37154_590.0364:user/release-keys'
03-30 12:15:27.457 I/DEBUG   (  189): Revision: '0'
03-30 12:15:27.457 I/DEBUG   (  189): ABI: 'arm'
03-30 12:15:27.458 I/DEBUG   (  189): pid: 12283, tid: 12829, name: Thread-2777  >>> io.realm.test <<<
03-30 12:15:27.458 I/DEBUG   (  189): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1bc
03-30 12:15:27.487 I/DEBUG   (  189):     r0 88829b74  r1 42621b38  r2 00000000  r3 000001b8
03-30 12:15:27.492 I/DEBUG   (  189):     r4 88829b78  r5 88829b78  r6 88829b74  r7 42724010
03-30 12:15:27.494 I/DEBUG   (  189):     r8 42621b38  r9 88829bd0  sl 88829bd4  fp 00000000
03-30 12:15:27.494 I/DEBUG   (  189):     ip 401d27d4  sp 88829b30  lr 79808887  pc 79776c20  cpsr 600f0030
03-30 12:15:27.495 I/DEBUG   (  189): 
03-30 12:15:27.495 I/DEBUG   (  189): backtrace:
03-30 12:15:27.495 I/DEBUG   (  189):     #00 pc 0006cc20  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.495 I/DEBUG   (  189):     #01 pc 000fe883  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.495 I/DEBUG   (  189):     #02 pc 000fcb8d  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.495 I/DEBUG   (  189):     #03 pc 000fce5b  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.495 I/DEBUG   (  189):     #04 pc 000f07ef  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.495 I/DEBUG   (  189):     #05 pc 000f0bd9  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.496 I/DEBUG   (  189):     #06 pc 001024cf  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.496 I/DEBUG   (  189):     #07 pc 000f6ed7  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.496 I/DEBUG   (  189):     #08 pc 000e4a87  /data/app/io.realm.test-1/lib/arm/librealm-jni.so (_ZNSt6thread5_ImplISt12_Bind_simpleIFZN5realm5_impl10SyncClientC4ESt10unique_ptrINS2_4util6LoggerESt14default_deleteIS7_EENS2_4sync6Client13ReconnectModeEbEUlvE_vEEE6_M_runEv+34)
03-30 12:15:27.496 I/DEBUG   (  189):     #09 pc 002c158c  /data/app/io.realm.test-1/lib/arm/librealm-jni.so
03-30 12:15:27.496 I/DEBUG   (  189):     #10 pc 000178df  /system/lib/libc.so (__pthread_start(void*)+30)
03-30 12:15:27.496 I/DEBUG   (  189):     #11 pc 00015823  /system/lib/libc.so (__start_thread+6)
03-30 12:15:28.354 I/DEBUG   (  189): 
03-30 12:15:28.354 I/DEBUG   (  189): Tombstone written to: /data/tombstones/tombstone_03
```

4) uploadProgressListener_changesOnly
```
03-30 22:13:14.607 I/TestRunner(32525): started: uploadProgressListener_changesOnly(io.realm.objectserver.ProgressListenerTests)
03-30 22:13:14.611 I/MonitoringInstrumentation(32525): Activities that are still in CREATED to STOPPED: 0
--------- beginning of crash
03-30 22:13:14.774 F/libc    (32525): Fatal signal 6 (SIGABRT), code -6 in tid 1003 (Thread-57251)
03-30 22:13:14.881 F/DEBUG   (  485): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-30 22:13:14.881 F/DEBUG   (  485): Build fingerprint: 'google/bullhead/bullhead:6.0/MDA89E/2296692:user/release-keys'
03-30 22:13:14.882 F/DEBUG   (  485): Revision: 'rev_1.0'
03-30 22:13:14.882 F/DEBUG   (  485): ABI: 'arm64'
03-30 22:13:14.883 F/DEBUG   (  485): pid: 32525, tid: 1003, name: Thread-57251  >>> io.realm.test <<<
03-30 22:13:14.884 F/DEBUG   (  485): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-30 22:13:14.879 W/debuggerd64(  485): type=1400 audit(0.0:13828): avc: denied { search } for name="io.realm.test" dev="dm-2" ino=392526 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
03-30 22:13:14.921 F/DEBUG   (  485): Abort message: 'TEST_FATAL'
03-30 22:13:14.922 F/DEBUG   (  485):     x0   0000000000000000  x1   00000000000003eb  x2   0000000000000006  x3   0000000000000000
03-30 22:13:14.922 F/DEBUG   (  485):     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
03-30 22:13:14.922 F/DEBUG   (  485):     x8   0000000000000083  x9   0000007f5298d5b0  x10  0000000000000001  x11  0000000000004000
03-30 22:13:14.923 F/DEBUG   (  485):     x12  0000000000004001  x13  0000000000000000  x14  0000000000000001  x15  00000000ffffffff
03-30 22:13:14.923 F/DEBUG   (  485):     x16  0000007f79d22568  x17  0000007f79cb4f9c  x18  0000007f79d30738  x19  0000007f5298d500
03-30 22:13:14.923 F/DEBUG   (  485):     x20  0000007f5298d440  x21  0000000000000073  x22  0000000000000006  x23  00000000000ff000
03-30 22:13:14.923 F/DEBUG   (  485):     x24  0000000000000002  x25  0000007f5d8cae30  x26  0000007f79cb1000  x27  0000007f556e7390
03-30 22:13:14.923 F/DEBUG   (  485):     x28  0000000000001000  x29  0000007f5298d2b0  x30  0000007f79cb2858
03-30 22:13:14.923 F/DEBUG   (  485):     sp   0000007f5298d2b0  pc   0000007f79cb4fa4  pstate 0000000020000000
03-30 22:13:14.930 F/DEBUG   (  485): 
03-30 22:13:14.930 F/DEBUG   (  485): backtrace:
03-30 22:13:14.931 F/DEBUG   (  485):     #00 pc 000000000006afa4  /system/lib64/libc.so (tgkill+8)
03-30 22:13:14.931 F/DEBUG   (  485):     #01 pc 0000000000068854  /system/lib64/libc.so (pthread_kill+68)
03-30 22:13:14.931 F/DEBUG   (  485):     #02 pc 0000000000023838  /system/lib64/libc.so (raise+28)
03-30 22:13:14.931 F/DEBUG   (  485):     #03 pc 000000000001dfd8  /system/lib64/libc.so (abort+60)
03-30 22:13:14.932 F/DEBUG   (  485):     #04 pc 00000000003b4f04  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (__gnu_cxx::__verbose_terminate_handler()+348)
03-30 22:13:14.932 F/DEBUG   (  485):     #05 pc 0000000000386c20  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (__cxxabiv1::__terminate(void (*)())+8)
03-30 22:13:14.932 F/DEBUG   (  485):     #06 pc 0000000000386c8c  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (std::terminate()+12)
03-30 22:13:14.932 F/DEBUG   (  485):     #07 pc 00000000003b3cac  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so
03-30 22:13:14.932 F/DEBUG   (  485):     #08 pc 0000000000067ca4  /system/lib64/libc.so (__pthread_start(void*)+52)
03-30 22:13:14.933 F/DEBUG   (  485):     #09 pc 000000000001eb84  /system/lib64/libc.so (__start_thread+16)
0
```

**Comment by Zhuinden** [comment]
File version upgrades!

**Comment by Zhuinden** [comment]
with progress notifications reverted, is this still an issue? 😕

**Comment by cmelchior** [comment]
No, it seemed that the crashing tests destabilized other tests.
Closing this.
