### ISSUE TITLE
Problems upgradeing from 2.3.0 to 3.0.0 

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-java#4424]
Hi there, 
before modifying my app I have been testing the Realm Object Server and Realm Auth in another app. Everything worked perfectly. However, when I decided to include Realm Auth to my main project everything got a mess. 

I tried to update from "io.realm:realm-gradle-plugin:2.3.0" to "io.realm:realm-gradle-plugin:3.0.0". This caused the following problem. 

> Error:Execution failed for task ':app:transformClassesWithRealmTransformerForDebug'.
> javassist.CannotCompileException: [source error] realm$injectObjectContext() not found in io.realm.internal.RealmObjectProxy

Because of this, I tried to go back to the 2.3.0 version. However, this didn't work and when running the app I get the following: 

> Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lio/realm/BaseRealm$1;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output /home/user/myapp/myapp/app/build/intermediates/transforms/dex/debug/folders/1000/1f/main /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_caf8b42f8469c752f96019a3d49a7a22c88d51b5.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_ee56cf695da059716736eae176ab0894fd0e89b3.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/bolts-applinks-1.4.0_c384f753d947b91810d40c699f78a4ec8e4f43cf.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_b460a7610b56bebd2e399c7cc22d8ceb1bd4a5cc.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_0ab3a005d008fde8efc71362bc5b9c369fa6a1b3.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_111190b1e5a4609143050d45a904feb05180ad9b.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_daaa7fcd95ef5c45a6ab0c81d48dc2b883de3c3f.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_834d7214760fb82858ac19865b3025196496a3a4.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/okio-1.9.0_93c242661af8159b33bace77e5abeafe1a14b9cd.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_02cdc50d2212212c6265af67750ecd0952f25bb3.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_96c58c5ccd3d0606b004ab8f1125b36534818d40.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_b33b64b4c1ef1ce9021af822ecfc1d9c8dd3d0b9.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_93e597de6aff24f5e1f58f4e2bc0c0923eb57a89.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/commons-cli-1.2_f8a8669f456e1c04711ec1023b95c34ce4c73f49.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_8617d1d7de5170084f01cff7b06c46d0ead8b905.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_aeff96850f3bedf6c258015c886ecb3dd62d16ef.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_4be51e69ae318c1efa844bac7f31d017d8608430.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_b870841e1203d82611aa87d1ce4825704d0d4dff.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_e3ae37ec450226a7761e5135021334a21760761c.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_0a2f15d4181c59710afae50ca09f06aca401b5a6.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_f331e24bb05328779ecf36aa71eaafa0b80fa2d0.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_7035124f4435e61017a48dbd6847287f9e4d04ec.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_9cf9aaba2a9f48ae6ace5503c33070906d103053.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_1f915dbfd5d5d2c2870e6650b92444c6df328691.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/okhttp-3.4.1_be9ae6098f02ed063e11fb7c43eae8061f2d89a9.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/stetho-1.3.1_780686a5fe9cfb7c6cb93afe6c8d127419a7c34a.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_981cda74d3828afcbe00e0bc8acf20b39576e3e1.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/jsr305-2.0.1_68ebf5de0a6fdfc024f30fd8fee9e22206ca223e.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_1718a37539b63eb5cad7913013e09be7b93a8c3e.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_0bb24521dbc07a1d813bbf80d239ff7f1d34f2f4.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_31e4134e1de34d08d97dced02db1ae7163156256.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_81a7c2ef0b753996f8f8b4e46359491e15c0e291.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/picasso-2.5.2_63e346c649b140ca4ee0b37e32adc55cc290fbbc.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/support-annotations-26.0.0-alpha1_0296275f67c9486d247bb7773efd12a34a9874f6.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_259ad58aa83c9a16d132891fe06525b2c7898c6d.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_04efe71f61ecb1147413c3637f57fdf98b0918ab.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_f04fce627eb31f423dd6093c1bef7e6f408df161.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_6e17d5f8c009516bd42669ff43351378ff2aac77.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_a5f98372ca70e7d91621f4337e3c9bcdbbbc4aae.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_422d88038c1b735a202fd6e07c7f2d06fc295bac.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_b7328f2f1ec6aed9f5ebee8df3cc21bbcef997a5.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_82a1a3d2c8e4fc832800c92b1ed60ff9c3cbc56d.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_fe4207a40dda8b6d91c5e36707d57895b989054f.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_6fa87d17bc906f8dd30d8eb443d1bcad448fe297.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_68c302a1b31cf30ad44f610ce27cd53c6bd25b40.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_58f6b28d0b85538a536a11e311cd15cbdcc8d7dc.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/realm_8fc72dad7e215f79742ff874c7dbb9033e59c59d.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_1d83b20328fe8f8c83dadbefbb6f7bcc43b7641e.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_1f67a70c5a9e82632b7ffa2be159c8d48b113310.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_6085cb66e623c3730af5a16f92ede158753b3768.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_78eb743fc93f07699dfc3790c317f7139deaefe6.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/bolts-tasks-1.4.0_30de764de80782e8b9e18b02da66bfd19f2c11fc.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/classes_e9391ea9dc1751c73262d76751159daa20489590.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/realm-annotations-2.3.0_26b4fb4212f76f9d47d13ffbc95e9e5b36a582d9.jar /home/user/myapp/myapp/app/build/intermediates/pre-dexed/debug/library-1.0.19_7a38e0f534f17b1a84e5cdbf4c81b9f0166a0347.jar}

This is the project level gradle file:
```javascript
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath "io.realm:realm-gradle-plugin:2.3.0"

    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'  }
        }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

This is the application level gradel:

```javascript
apply plugin: 'com.android.application'
apply plugin: 'realm-android'


android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'


    defaultConfig {
        applicationId "com.innotholic.org.researchfactory"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        def host = '10.210.228.253'
        debug {
            // This will automatically detect the IP address of the machine building RealmLogin.
            // It is assumed that this machine is also running the Object Server.
            // If not, replace 'host' with the IP of the machine hosting the server.
            buildConfigField "String", "OBJECT_SERVER_IP", "\"${host}\""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "OBJECT_SERVER_IP", "\"${host}\""
        }
    }

    signingConfigs {
        config {
            storeFile rootProject.file("keystore/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.config
        }
    }

}

realm {
    syncEnabled = true
}

repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:cardview-v7:25.2.0'
    compile 'com.android.support:recyclerview-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'


    //Realm
    compile 'io.realm:android-adapters:1.3.0'

    //Realm inspector https://github.com/uPhyca/stetho-realm
    compile 'com.facebook.android:facebook-android-sdk:4.15.0'
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.uphyca:stetho_realm:0.9.0'

    //Third party libraries
    compile 'com.andrewgiang.spritzertextview:library:0.3.4'
    compile 'com.crystal:crystalrangeseekbar:1.1.1'
    compile 'co.lujun:androidtagview:1.0.3'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.lorentzos.swipecards:library:1.0.9'
    compile 'com.skyfishjy.ripplebackground:library:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.karumi:expandableselector:1.0.0'
    compile 'com.wdullaer:materialdatetimepicker:3.1.3'
    compile 'com.google.android.gms:play-services-drive:10.2.1'
    compile 'com.google.android.gms:play-services-identity:10.2.1'
    compile 'com.google.android.gms:play-services-auth:10.2.1'
    compile 'com.google.android.gms:play-services-analytics:10.2.1'

}

apply plugin: 'com.google.gms.google-services'
```

I am developing locally, using ubuntu. 
Could you please ***help*** me with this?

**Comment by Zhuinden** [comment]
If you update Realm to 3.0.0, you also need to update compile 'io.realm:android-adapters:1.3.0' to 2.0.0, and the Stetho-Realm to 2.0.0, and also do a clean + rebuild

**Comment by ojarabo** [comment]
Thanks for the quick answer @Zhuinden 
Yeah, I have noticed after a while. Thanks. 
My problem now is that if I update to adapter 2.0.0, I will also have to refactor my adapters, and I don't know to what extend your adapters have been modified. 

For example, I have notice that the RealmBaseAdapter and RealmRecyclerViewAdapter used to need a Context to pass to the super class, and now is not needed anymore. 

In my RealmBaseAdapter, I am using inflater.inflate in the getView and with the new adapters, this is creating some errors. 

Could you please tell me where I can find the documentation with the added changes for the new adapters. I have seen the new examples in the github, but by looking at them, I haven't been able to asset whether it would be worthy upgrading them. 

Thanks and sorry for the inconvenience.

**Comment by Zhuinden** [comment]
The only major change was that `Context` is no longer needed because you can use `parent.getContext()` as context in your adapter

You can use `replace in path` to remove context parameter, or for adapters do Change Signature (Ctrl+F6) for their constructors

**Comment by ojarabo** [comment]
Thanks @Zhuinden 
That's great them. I will change it now.

Thanks again for everything. ;)

**Comment by Zhuinden** [comment]
Re-opened? What's wrong?

**Comment by beeender** [comment]
Hope your issue is solved. Feel free to reopen this if needed.

**Comment by ojarabo** [comment]
Hi again, 
I have reopen this thread because something is causing runtime crash after upgrading the recommended libraries. 

>    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                                      at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
                                                                                      at android.support.v7.widget.DefaultItemAnimator.animateAdd(DefaultItemAnimator.java:218)
                                                                                      at android.support.v7.widget.SimpleItemAnimator.animateAppearance(SimpleItemAnimator.java:114)
                                                                                      at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3758)
                                                                                      at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:519)
                                                                                      at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:247)
                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3607)
                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
                                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                      at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1192)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
                                                                                      at android.view.View.layout(View.java:17523)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
04-05 11:50:13.720 5878-5878/com.package.org.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/com.package.org.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.package.org.app-1/lib/x86_64, /data/app/com.package.org.app-1/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
                                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                      	... 63 more

I think that the problem is related to the gradle dependencies. In the application level gradle, I am using version 25.2.0 for the support libraries. Although I am using version 25.2.0, gradle is warning that "All com.android.support libraries must use the exact same version specification". As you can see below, I only using version 25.2.0. 

```javascript
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:cardview-v7:25.2.0'
    compile 'com.android.support:recyclerview-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha8'

    compile 'com.android.support:support-annotations:25.2.0'
    compile 'com.android.support:support-v4:25.2.0'
    compile 'com.android.support:customtabs:25.2.0'
    compile 'com.android.support:mediarouter-v7:25.2.0'

```
I am not really sure if any of your libraries is internally using any other dependency version. In any case, I think the runtime error described at the beginning is caused by the dependencies. I have been debugging the code to detect the class that is creating the error. I have detected that in class DefaultItemAnimator.java, the AnimatorCompatHelper is called, but also the class "Cannot resolve symbol". This happened after upgrading Realm to 3.0.0 and adapter 2.0.0, etc. 

I have cleaned and rebuilt the project following the solutions proposed in Stackoverflow, but nothing is working. I haven't changed any other thing beside upgrading your libraries. 

Thanks

**Comment by ojarabo** [comment]
@Zhuinden @beeender 
Sorry guys for reopened the issue yesterday and haven't written the post. I was writing the post while I was called for a meeting.

**Comment by Zhuinden** [comment]
please try using `./gradlew app:dependencies` and see if there are any libraries that bring in an older version of `com.android.support:recyclerview-v7` than 25.2.0

**Comment by ojarabo** [comment]
Yeah, that was it. 
I have updated the version to 26.0.0-alpha1 and the problem has disappeared. 

Thanks for your help. I really appreciate it ;)
