### ISSUE TITLE
Realm create failure on LineageOS 14.1

### ISSUE THREAD

**Issue by Tornaco** [realm/realm-java#4506]
Steps:
```
Realm.getInstance(new RealmConfiguration.Builder()
                .directory("ExternalStorage/XXX")
                .name("backup_sessions")
                .build());
```

Logs:
```
04-17 21:44:16.529 6538 6573 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
04-17 21:44:16.529 6538 6573 E AndroidRuntime: Process: org.newstand.datamigration, PID: 6538
04-17 21:44:16.529 6538 6573 E AndroidRuntime: io.realm.exceptions.RealmError: Unrecoverable error. Invalid argument in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 109
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at io.realm.internal.SharedRealm.(SharedRealm.java:187)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:229)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:204)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at io.realm.Realm.getInstance(Realm.java:228)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at org.newstand.datamigration.repo.BKSessionRepoService.getRealm(BKSessionRepoService.java:36)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at org.newstand.datamigration.repo.OneTimeRealmRepoService.findLast(OneTimeRealmRepoService.java:83)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at org.newstand.datamigration.ui.activity.NavigatorActivity$11.run(NavigatorActivity.java:228)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-17 21:44:16.529 6538 6573 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761)
04-17 21:44:16.534 1241 4875 W ActivityManager: Force finishing activity org.newstand.datamigration/.ui.activity.NavigatorActivity
```

**Comment by Zhuinden** [comment]
I assume `.directory("ExternalStorage/XXX")` is not a valid path

**Comment by beeender** [comment]
Dup to #4461 . Will be fixed by https://github.com/realm/realm-core/pull/2574
