### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException Android 

### ISSUE THREAD

**Issue by kaganozupek** [realm/realm-java#4512]
I seen some crashes on crashlytics and I could not reproduce this issues. But I saw a lot of crashes in crash report.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 133(requested: 1 valid: 1)
       at io.realm.internal.Collection.nativeGetRow(SourceFile)
       at io.realm.internal.Collection.getUncheckedRow(SourceFile:386)
       at io.realm.OrderedRealmCollectionImpl.get(SourceFile:106)
       at io.realm.RealmResults.get(SourceFile:53)
       at com.***.view.adapters.ChatIndexAdapter.getChatSessionAtPosition(SourceFile:568)
       at com.***.view.adapters.ChatIndexAdapter$5.onLongClick(SourceFile:451)
       at android.view.View.performLongClick(View.java:5145)
       at android.view.View$CheckForLongPress.run(View.java:20303)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5912)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

Realm version(s): 3.0.0

Realm sync feature enabled: NO

Android Studio version: 2.2.3

Which Android version and device: ?

samsung 44%
General Mobile 18%
LGE 9%

Operating Systems
Android 7   41%
Android 6   34%
Android 5   18%
Android 4   7%

**Comment by cmelchior** [comment]
Check your code at 
` com.***.view.adapters.ChatIndexAdapter.getChatSessionAtPosition(SourceFile:568)`

For some reason the size of the collection is not what you expect. It looks like you are doing `list.get(1)` when the size is 1, which only makes `get(0)` valid.

**Comment by TeamQDev** [comment]
I am getting ArrayIndexOutBoundsException in android.Following is the error.Please me out with this.

 FATAL EXCEPTION: main
                                                                                                     Process: com.mindyourelderss.MyHealthCareWishes.HomeActivity, PID: 22398
                                                                                                     java.lang.ArrayIndexOutOfBoundsException: length=16; index=-1
                                                                                                         at com.mindyourelders.MyHealthCareWishes.Connections.FragmentNewContact.validate(FragmentNewContact.java:2134)
                                                                                                         at com.mindyourelders.MyHealthCareWishes.Connections.FragmentNewContact.onClick(FragmentNewContact.java:1655)
                                                                                                         at android.view.View.performClick(View.java:4788)
                                                                                                         at android.view.View$PerformClick.run(View.java:19923)
                                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5425)
                                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:928)
                                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:723)

**Comment by beeender** [comment]
@TeamQDev Your issue doesn't seem to be Realm related?
