### ISSUE TITLE
Unable to open a realm at path '/data/data/me.latergram.latergramme/files/default.realm': Not a Realm file.

### ISSUE THREAD

**Issue by virengujariya** [realm/realm-java#4518]
#### Actual Results

>  E.g. full stack trace with exception
```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {me.latergram.latergramme/me.latergram.latergramme.activities.ViewMediaActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/me.latergram.latergramme/files/default.realm': Not a Realm file. (Not a Realm file) (/data/data/me.latergram.latergramme/files/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5062)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5085)
       at android.app.ActivityThread.access$1700(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1853)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/me.latergram.latergramme/files/default.realm': Not a Realm file. (Not a Realm file) (/data/data/me.latergram.latergramme/files/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.(SharedRealm.java:190)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:206)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:127)
       at io.realm.Realm.getDefaultInstance(Realm.java:211)
       at com.later.core.database.RealmHelper.getDefaultInstance(RealmHelper.java:25)
       at com.later.core.database.RealmHelper.close(RealmHelper.java:29)
       at me.latergram.latergramme.activities.NewBaseActivity.onDestroy(NewBaseActivity.java:653)
       at me.latergram.latergramme.activities.base.ViewMediaBaseActivity.onDestroy(ViewMediaBaseActivity.java:50)
       at me.latergram.latergramme.activities.ViewMediaActivity.onDestroy(ViewMediaActivity.java:294)
       at android.app.Activity.performDestroy(Activity.java:7102)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1170)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5040)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5085)
       at android.app.ActivityThread.access$1700(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1853)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

@Override
    protected void onDestroy() {
        super.onDestroy();
        Realm realm = getDefaultInstance(); //crashes here
        if (realm != null) {
            realm.close();
        }
    }

```

#### Version of Realm and tooling
Realm version(s): ?
io.realm:realm-gradle-plugin:3.1.1

Realm sync feature enabled: yes/no
no

Android Studio version: ?
2.3.1

Which Android version and device: ?
All issues are on Samsung running Android 6.0.1 devices

**Comment by beeender** [comment]
Did you use encryption? It seems you are using a wrong key to open a encrypted Realm.

**Comment by virengujariya** [comment]
@beeender No, I haven't used encryption key

**Comment by beeender** [comment]
I saw the exception happened in the `Activity.onDestory()`,

1. Why do you get a Realm instance in the `onDestory()` call?
2. Does the exception only happen when `getInstance()` is called in `onDestory()`?
3. What are those Sumsung devices model?
4. Can you reproduce this issue on your side?

**Comment by bmeike** [comment]
Hey @virengujariya 

Haven't heard from you in quite a while, so I am assuming that you've found a solution.  I'm going to go ahead and close this ticket.  If you are still having issues, by all means, re-open it.
