### ISSUE TITLE
Realm closed itself.

### ISSUE THREAD

**Issue by guness** [realm/realm-java#4577]
Hello Guys, I am using Realm + RxJava, I have two different usage of Realm libraries in my App.
One is UI Realm, Global, single instance, created on Application object. It is never closed. Second one is single use Realm. Method gets an instance by getDefaultInstances, execute transformation, then closes the realm.

However I got errors when using global Realm, it says realm is already closed.

you can check details on 
http://stackoverflow.com/questions/43619625/realm-closes-itself

#### Version of Realm and tooling
Realm version(s): 3.1.3

Realm sync feature enabled: no

Android Studio version: 2.3.1

Which Android version and device: Android 21, 21, 23, 24, 25 Device different devices.

You can check related crash on Fabric:

http://crashes.to/s/bdcbf234b55

**Comment by zaki50** [comment]
The stack trace on the SO says that 
```
Caused by java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
   at io.realm.BaseRealm.checkIfValid(Unknown Source)
   at io.realm.Realm.init(Unknown Source)
```
But I couldn't find any `checkIfValid()` call in `Realm.init()`;

https://github.com/realm/realm-java/blob/v3.1.3/realm/realm-library/src/main/java/io/realm/Realm.java

Could you provide a small project that reproduce this error?

**Comment by Zhuinden** [comment]
```
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity.onStart (Unknown Source)
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity.lambda$onStart$3 (Unknown Source)
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity$$Lambda$1.call (Unknown Source)
rx.Observable.create (Unknown Source)
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity.onStart (Unknown Source)
```

we need your `HomeActivity.onStart()` method

**Comment by guness** [comment]
@Zhuinden this is my onStart method:

`    @Override
    protected void onStart() {
        super.onStart();
        if (mNotificationBadge != null) {

            SVRealm.getRealmObservable().subscribe(realmInstance -> subscribeUntilDetach(realmInstance.where(Notification.class).findAllAsync().asObservable()
                    .onBackpressureLatest()
                    .switchIfEmpty(emptyNotification())
                    .map(notifications -> notifications.where().isNull("readTime").or().isEmpty("readTime").count())
                    .onBackpressureLatest()
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(count -> {
                        if (count == 0L) {
                            mNotificationBadge.setVisibility(View.GONE);
                        } else {
                            mNotificationBadge.setText(String.format(Locale.getDefault(), "%d", count));
                            mNotificationBadge.setVisibility(View.VISIBLE);
                        }
                    }, throwable -> Timber.e(throwable, "Error setting notification count"))));
        }
    }
`
and you also may need this:

`    @UiThread
    public static Observable<Realm> getRealmObservable() {
        if (Thread.currentThread() == Looper.getMainLooper().getThread()) {
            return realmSubject.first();
        } else {
            Timber.e("Illegal access to getRealmObservable");
            throw new IllegalStateException("Only UI Thread can access this realm");
        }
    }`

___________

@zaki50 I am not able to reproduce this error on, however it appears 10-20% on production.
Stacktrace on SO was from Fabric, I suspect it may not be accurate. Here same error stack from Firebase crash reporting:

`io.realm.BaseRealm.checkIfValid (BaseRealm.java)
io.realm.Realm.init (Realm.java)
<OR>.createInstance (Realm.java)
<OR>.initializeRealm (Realm.java)
<OR>.createObjectInternal (Realm.java)
<OR>.createObjectInternal (Realm.java)
<OR>.copyToRealm (Realm.java)
<OR>.insert (Realm.java)
<OR>.copyFromRealm (Realm.java)
<OR>.where (Realm.java)
<OR>.executeTransaction (Realm.java)
<OR>.executeTransactionAsync (Realm.java)
<OR>.executeTransactionAsync (Realm.java)
<OR>.copyOrUpdate (Realm.java)
<OR>.createDetachedCopy (Realm.java)
<OR>.checkMaxDepth (Realm.java)
<OR>.migrateRealm (Realm.java)
<OR>.updateSchemaCache (Realm.java)
<OR>.isInTransaction (Realm.java)
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity.lambda$onStart$3 (HomeActivity.java)
<OR>.access$100 (HomeActivity.java)
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity$$Lambda$1.call (HomeActivity.java)
rx.internal.util.ActionSubscriber.onNext (ActionSubscriber.java)
rx.observers.SafeSubscriber.onNext (SafeSubscriber.java)
rx.internal.producers.SingleProducer.request (SingleProducer.java)
rx.Subscriber.setProducer (Subscriber.java)
rx.Subscriber.setProducer (Subscriber.java)
rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted (OperatorSingle.java)
rx.internal.operators.OperatorTake$1.onNext (OperatorTake.java)
rx.internal.operators.NotificationLite.next (NotificationLite.java)
<OR>.completed (NotificationLite.java)
<OR>.error (NotificationLite.java)
<OR>.accept (NotificationLite.java)
rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept (SubjectSubscriptionManager.java)
rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext (SubjectSubscriptionManager.java)
<OR>.emitLoop (SubjectSubscriptionManager.java)
rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst (SubjectSubscriptionManager.java)
rx.subjects.BehaviorSubject$1.call (BehaviorSubject.java)
rx.subjects.BehaviorSubject$1.call (BehaviorSubject.java)
rx.subjects.SubjectSubscriptionManager.call (SubjectSubscriptionManager.java)
<OR>.addUnsubscriber (SubjectSubscriptionManager.java)
<OR>.setLatest (SubjectSubscriptionManager.java)
<OR>.getLatest (SubjectSubscriptionManager.java)
<OR>.add (SubjectSubscriptionManager.java)
rx.subjects.SubjectSubscriptionManager.call (SubjectSubscriptionManager.java)
<OR>.addUnsubscriber (SubjectSubscriptionManager.java)
<OR>.setLatest (SubjectSubscriptionManager.java)
<OR>.getLatest (SubjectSubscriptionManager.java)
<OR>.add (SubjectSubscriptionManager.java)
rx.subjects.SubjectSubscriptionManager.call (SubjectSubscriptionManager.java)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java)
rx.Observable.create (Observable.java)
<OR>.lift (Observable.java)
<OR>.compose (Observable.java)
<OR>.toSingle (Observable.java)
<OR>.concat (Observable.java)
<OR>.error (Observable.java)
<OR>.from (Observable.java)
<OR>.from (Observable.java)
<OR>.fromCallable (Observable.java)
<OR>.just (Observable.java)
<OR>.merge (Observable.java)
<OR>.merge (Observable.java)
<OR>.timer (Observable.java)
<OR>.timer (Observable.java)
<OR>.buffer (Observable.java)
<OR>.buffer (Observable.java)
<OR>.concatMap (Observable.java)
<OR>.doOnCompleted (Observable.java)
<OR>.observeOn (Observable.java)
<OR>.observeOn (Observable.java)
<OR>.observeOn (Observable.java)
<OR>.retry (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.unsafeSubscribe (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.subscribeOn (Observable.java)
rx.Observable.unsafeCreate (Observable.java)
<OR>.empty (Observable.java)
<OR>.merge (Observable.java)
<OR>.delay (Observable.java)
<OR>.delay (Observable.java)
<OR>.doOnTerminate (Observable.java)
<OR>.filter (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.subscribeOn (Observable.java)
<OR>.take (Observable.java)
rx.Observable.create (Observable.java)
<OR>.lift (Observable.java)
<OR>.compose (Observable.java)
<OR>.toSingle (Observable.java)
<OR>.concat (Observable.java)
<OR>.error (Observable.java)
<OR>.from (Observable.java)
<OR>.from (Observable.java)
<OR>.fromCallable (Observable.java)
<OR>.just (Observable.java)
<OR>.merge (Observable.java)
<OR>.merge (Observable.java)
<OR>.timer (Observable.java)
<OR>.timer (Observable.java)
<OR>.buffer (Observable.java)
<OR>.buffer (Observable.java)
<OR>.concatMap (Observable.java)
<OR>.doOnCompleted (Observable.java)
<OR>.observeOn (Observable.java)
<OR>.observeOn (Observable.java)
<OR>.observeOn (Observable.java)
<OR>.retry (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.unsafeSubscribe (Observable.java)
<OR>.subscribe (Observable.java)
<OR>.subscribeOn (Observable.java)
com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity.onStart (HomeActivity.java)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1288)
android.app.Activity.performStart (Activity.java:5977)
android.app.Activity.performRestart (Activity.java:6034)
android.app.Activity.performResume (Activity.java:6039)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:3181)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3229)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1396)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:155)
android.app.ActivityThread.main (ActivityThread.java:5689)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1029)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:824)`

**Comment by Zhuinden** [comment]
Okay, that would imply that the `Realm.getInstance(config)` called internally by [RealmObservableFactory](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java#L79) *somehow* closes both the "local Realm" inside the observable, but the `unsubscribe` seems to propagate to your Realm instance that is stored in a relay, and `doOnTerminate()` closes your global Realm.

**Comment by guness** [comment]
Just reproduced once 
```
04-29 05:30:51.231 6204-6204/? E/UncaughtException: rx.exceptions.OnErrorNotImplementedException: This Realm instance has already been closed, making it unusable.
                                                        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                        at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                                                        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
                                                        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                        at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
                                                        at rx.Subscriber.setProducer(Subscriber.java:209)
                                                        at rx.Subscriber.setProducer(Subscriber.java:205)
                                                        at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
                                                        at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:80)
                                                        at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
                                                        at rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept(SubjectSubscriptionManager.java:317)
                                                        at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitLoop(SubjectSubscriptionManager.java:290)
                                                        at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst(SubjectSubscriptionManager.java:269)
                                                        at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:109)
                                                        at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:105)
                                                        at rx.subjects.SubjectSubscriptionManager.add(SubjectSubscriptionManager.java:100)
                                                        at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:60)
                                                        at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:35)
                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                        at rx.Observable.subscribe(Observable.java:10442)
                                                        at rx.Observable.subscribe(Observable.java:10409)
                                                        at rx.Observable.subscribe(Observable.java:10214)
                                                        at com.argeusteknoloji.sikayetvar.ui.pages.home.ComplaintsFragment.onViewCreated(ComplaintsFragment.java:68)
                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
                                                        at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2191)
                                                        at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1164)
                                                        at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1157)
                                                        at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1127)
                                                        at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1426)
                                                        at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1536)
                                                        at android.view.View$PerformClick.run(View.java:19956)
                                                    	at android.os.Handler.handleCallback(Hand
```
corresponding method:
```    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        SVRealm.getRealmObservable().subscribe(realm -> {
            mComplaintsAdapter = new ComplaintsAdapter(this, mListener.getOnMediaClickedListener(),
                    realm.where(Complaint.class).equalTo("isSelf", isSelf())
                            .findAllSortedAsync("page", Sort.ASCENDING, "time", Sort.DESCENDING));
            mCardList.setAdapter(mComplaintsAdapter);

            subscribeUntilDetach(realm.where(Complaint.class).equalTo("isSelf", isSelf()).findAllAsync().asObservable()
                    .map(AbstractCollection::isEmpty)
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(isEmpty -> {
                        mCardList.setVisibility(isEmpty ? View.GONE : View.VISIBLE);
                        mEmptyView.setVisibility(isEmpty ? View.VISIBLE : View.GONE);
                    }));
        });

    }
```
This is line 68
`SVRealm.getRealmObservable().subscribe(realm -> {`

**Comment by Zhuinden** [comment]
What is `SVRealm.getRealmObservable()`?

**Comment by guness** [comment]
one more exception while finishing all activities:

```E/UncaughtException: java.lang.RuntimeException: Unable to pause activity {com.sikayetvar.mobile/com.argeusteknoloji.sikayetvar.ui.pages.HomeActivity}: rx.exceptions.CompositeException: 9 exceptions occurred. 
                                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3366)
                                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3325)
                                                                              at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3300)
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:156)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:211)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                           Caused by: rx.exceptions.CompositeException: 9 exceptions occurred. 
                                                                              at rx.exceptions.Exceptions.throwIfAny(Exceptions.java:175)
                                                                              at rx.subscriptions.CompositeSubscription.unsubscribeFromAll(CompositeSubscription.java:194)
                                                                              at rx.subscriptions.CompositeSubscription.clear(CompositeSubscription.java:153)
                                                                              at com.argeusteknoloji.sikayetvar.core.SVActivity.onPause(SVActivity.java:74)
                                                                              at android.app.Activity.performPause(Activity.java:6101)
                                                                              at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
                                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3352)
                                                                              at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3325) 
                                                                              at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3300) 
                                                                              at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:211) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5389) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
                                                                           Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                              at android.util.Log.getStackTraceString(Log.java:335)
                                                                              at android.util.Log.e(Log.java:243)
                                                                              at com.google.android.gms.internal.zzbnr.uncaughtException(Unknown Source)
                                                                              at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                              at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                           Caused by: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
                                                                              at io.realm.BaseRealm.checkIfValid(BaseRealm.java:341)
                                                                              at io.realm.RealmResults.checkForAddRemoveListener(RealmResults.java:156)
                                                                              at io.realm.RealmResults.removeChangeListener(RealmResults.java:189)
                                                                              at io.realm.rx.RealmObservableFactory$6$2.call(RealmObservableFactory.java:157)
                                                                              at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
                                                                              at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                              at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                              at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                              at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                              at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                              at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                              at rx.internal.subscriptions.SequentialSubscription.unsubscribe(SequentialSubscription.java:180)
                                                                              at rx.subscriptions.SerialSubscription.unsubscribe(SerialSubscription.java:36)
                                                                              at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                              at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                              at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                              at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                              at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                              at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                              at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                              at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                              at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                              at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                              at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                              at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                              at rx.subscriptions.CompositeSubscription.unsubscribeFromAll(CompositeSubscription.java:186)
                                                                          	at rx.subscripti```

**Comment by guness** [comment]
@Zhuinden I went with single global UI Thread only realm instance without closing it throughout the application life. I have no single line that calls **.close()** on that Realm instance. and yet, I am getting this already closed exception.

**Comment by Zhuinden** [comment]
@guness use this on UI thread only:

    @Override
    public Observable<Realm> getRealmObservable() {
        return Observable.create(new Observable.OnSubscribe<Realm>() {
            @Override
            public void call(final Subscriber<? super Realm> subscriber) {
                final Realm observableRealm = Realm.getDefaultInstance();
                subscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        observableRealm.close();
                    }
                }));
                subscriber.onNext(observableRealm);
            }
        });
    }

**Comment by guness** [comment]
@Zhuinden this looks good. however my original problem is Realm is closing itself.

**Comment by Zhuinden** [comment]
@guness i think if you replace `return realmSubject.first();` with this code above (`return ...`) then it'll fix the issue

**Comment by guness** [comment]
new data: Crash happens when app is background at 80% ratio.

**Comment by Zhuinden** [comment]
Have you tried what I said?

**Comment by guness** [comment]
I am not able to reproduce original exception, and after applying your implementation, still not reproducible. I am trying to find a solid way to reproduce it and trying to find solid fix before releasing new version to production.

At worst case, your solution is the best I have currently, tho still not answers what is wrong with my solution.

**Comment by Zhuinden** [comment]
Unfortunately I'm not sure either. It has something to do with relay and `asObservable` acting up together somehow.

**Comment by guness** [comment]
@Zhuinden `Observable.create(new Observable.OnSubscribe<Realm>` is deprecated. is there a recent API?

**Comment by Zhuinden** [comment]
technically `Observable.create()` was replaced with `Observable.unsafeCreate()`, but for background compatibility reasons the default `RealmObservableFactory` was not changed to use `Observable.fromEmitter()`.

**Comment by kneth** [comment]
Let me provide the link to the documentation: https://realm.io/docs/java/latest/#configuration

**Comment by guness** [comment]
I am using the latest Rx:

`compile 'io.reactivex:rxandroid:1.2.1'`

is it a problem?

**Comment by Zhuinden** [comment]
You can replace `RealmObservableFactory` behavior with your own `rxFactory` by implementing `RxObservableFactory`.

**Comment by guness** [comment]
I think problem is around `RealmObservableFactory`. I have removed all Rx + Realm relations, used old school implementation and it went well.

**Comment by kneth** [comment]
I am closing the issue. @guness If you have time, it would be great of you to create a small project which demonstrate the issue.
