### ISSUE TITLE
NPE when create object with realm and kotlin

### ISSUE THREAD

**Issue by GhostFlying** [realm/realm-java#4579]
I try to use realm work with kotlin but it crash when I create object with the below NPE.

java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.ProxyState.setConstructionFinished()' on a null object reference

#### Code Sample

```kotlin

Chat.kt

open class Chat(@PrimaryKey open var chatId: Long = -1) : RealmObject()

```

```kotlin
Fragment.kt

    override fun onViewCreated(view: View?, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        notification_recycler_view.layoutManager = LinearLayoutManager(appCtx)
        val realm = Realm.getDefaultInstance()
        val data = realm.where(Chat::class.java).findAll()
        notification_recycler_view.adapter = NotificationAdapter(data!!)

        realm.beginTransaction()
        val chat = realm.createObject(Chat::class.java, 1)
        realm.commitTransaction()
    }
```

#### Version of Realm and tooling
Realm version(s): ?

io.realm:realm-gradle-plugin:3.1.3

io.realm:android-adapters:2.0.0

Realm sync feature enabled: yes/no

no

Android Studio version: ?

2.3.1

Which Android version and device: ?

Android 6.0

**Comment by Zhuinden** [comment]
This has been reported before but it couldn't be reproduced. Is there a chance you can share a sample project? 

Also, try applying `realm-android` plugin AFTER `kotlin-android`.

**Comment by GhostFlying** [comment]
Issue is solved by apply realm-android after kotlin-android

And if u need the demo project, u can get it from https://github.com/GhostFlying/realm-demo

**Comment by GhostFlying** [comment]
Ops, after I add more filed, it come out again and I need to do something like uninstall app, clean project etc. to make it work again.

**Comment by Zhuinden** [comment]
If instant run is enabled, then you should disable it.

**Comment by GhostFlying** [comment]
I always disable it.

**Comment by Zhuinden** [comment]
Hrm, I ran out of ideas then. :/

In that case @zaki50 is the one who'll known what to look into.

**Comment by aaronblondeau** [comment]
I am also seeing this issue.  Seems related to build process because once the error begins happening it always happens.  I can then get it to go away by flipping back and forth between 

```
io.realm:realm-gradle-plugin:3.1.3
```

and

```
io.realm:realm-gradle-plugin:3.1.2
```

And it'll be good for a few builds, but then start happening again.

**Comment by Zhuinden** [comment]
Something is applied wrong. I'd try to **clean** instead of swapping versions. But... I don't know what breaks.

**Comment by kneth** [comment]
Also try to refresh dependencies (`--refresh-dependencies` on the command line).

**Comment by akent** [comment]
I have also started seeing this issue on my project. If I make any code change in a RealmObject derived class, it triggers it. A clean build does fix it. I'll try to repro with the demo project linked above.

**Comment by akent** [comment]
Yes, it's easy to reproduce with the example demo repo above.

1) Build and install demo app normally
2) Change some code in Chat.kt, for e.g. use Android Studio to autogenerate equals() and hashCode() methods.
3) Build and install and observe runtime crash.
4) Make clean build, rebuild and install -> all fine again.

Here's an example full stacktrace:
```05-10 20:14:03.333 22530-22530/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ghostflying.realmdemo, PID: 22530
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ghostflying.realmdemo/com.ghostflying.realmdemo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.ProxyState.setConstructionFinished()' on a null object reference
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
   at android.app.ActivityThread.-wrap12(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6121)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.ProxyState.setConstructionFinished()' on a null object reference
   at io.realm.ChatRealmProxy.<init>(ChatRealmProxy.java:76)
   at io.realm.DefaultRealmModuleMediator.newInstance(DefaultRealmModuleMediator.java:82)
   at io.realm.BaseRealm.get(BaseRealm.java:490)
   at io.realm.Realm.createObjectInternal(Realm.java:945)
   at io.realm.Realm.createObject(Realm.java:921)
   at com.ghostflying.realmdemo.MainActivity$onCreate$3.execute(MainActivity.kt:28)
   at io.realm.Realm.executeTransaction(Realm.java:1355)
   at com.ghostflying.realmdemo.MainActivity.onCreate(MainActivity.kt:28)
   at android.app.Activity.performCreate(Activity.java:6682)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
   at android.app.ActivityThread.main(ActivityThread.java:6121) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) ```

**Comment by kneth** [comment]
Realm has an annotation processor, a  bytecode transformer and a few ProGuard rules. To me, the `kapt`(Kotlin annotation processing tool) is a bit magically so I can easily imagine that it can go wrong but cleaning is the best option :-)

**Comment by Zhuinden** [comment]
And this issue is also tracked in https://github.com/realm/realm-java/issues/4579 .

**Comment by akent** [comment]
For the record the other issue tracking this is #4372
