### ISSUE TITLE
exception onDestroy method even there isn't any realm code there 

### ISSUE THREAD

**Issue by virengujariya** [realm/realm-java#4593]
#### Code Sample

I don't even have realm instance inside activity where it's throwing exception. 

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {me.latergram.latergramme/me.latergram.latergramme.activities.LabelsActivity}: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3791)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3809)
       at android.app.ActivityThread.access$1400(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
       at io.realm.BaseRealm.checkIfValid(BaseRealm.java:341)
       at io.realm.RealmResults.isLoaded(RealmResults.java:105)
       at io.realm.OrderedRealmCollectionImpl.size(OrderedRealmCollectionImpl.java:304)
       at io.realm.RealmResults.size(RealmResults.java:57)
       at me.latergram.latergramme.adapters.LabelsAdapter.getItemCount(LabelsAdapter.java:77)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:9658)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityEvent(RecyclerView.java:9631)
       at android.support.v7.widget.LinearLayoutManager.onInitializeAccessibilityEvent(LinearLayoutManager.java:239)
       at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:70)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:241)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:61)
       at android.view.View.onInitializeAccessibilityEvent(View.java:5444)
       at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5317)
       at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:20853)
       at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatIcs.java:122)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:223)
       at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:371)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:268)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatJellyBean.java:87)
       at android.view.View.sendAccessibilityEventUnchecked(View.java:5302)
       at android.support.v7.widget.RecyclerView.sendAccessibilityEventUnchecked(RecyclerView.java:3206)
       at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:21039)
       at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:21072)
       at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:7991)
       at android.view.View.onFocusChanged(View.java:5189)
       at android.view.View.clearFocusInternal(View.java:5094)
       at android.view.View.unFocus(View.java:5127)
       at android.view.ViewGroup.unFocus(ViewGroup.java:855)
       at android.view.ViewGroup.unFocus(ViewGroup.java:857)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4209)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4195)
       at android.view.ViewGroup.removeView(ViewGroup.java:4126)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1411)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2951)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:271)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at me.latergram.latergramme.activities.NewBaseActivity.onDestroy(NewBaseActivity.java:677)
       at me.latergram.latergramme.activities.base.LabelsBaseActivity.onDestroy(LabelsBaseActivity.java:28)
       at me.latergram.latergramme.activities.LabelsActivity.onDestroy(LabelsActivity.java:192)
       at android.app.Activity.performDestroy(Activity.java:6189)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1164)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3778)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3809)
       at android.app.ActivityThread.access$1400(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

#### Version of Realm and tooling
Realm version(s): ?
3.1.3

Realm sync feature enabled: yes/no
no

Android Studio version: ?
2.3.1

Which Android version and device: ?
so far OS 6 and 5

**Comment by Zhuinden** [comment]
`at me.latergram.latergramme.adapters.LabelsAdapter.getItemCount(LabelsAdapter.java:77)`

**Comment by bmeike** [comment]
@virengujariya 
  I think that @Zhuinden's analysis is right on.  I hope that helped you sort the issue.

  I'm going to close this ticket.  By all means, feel free to re-open this ticket if the problem recurs or to open a new ticket if there is anything else we can do for you.

**Comment by Zhuinden** [comment]
Also worth noting that `LabelsAdapter` doesn't seem to be a `RealmRecyclerViewAdapter`, even though it uses a `RealmResults` as its data set.

To both have this validation check out of the box and to listen for changes from Realm automatically, consider using https://github.com/realm/realm-android-adapters .
