### ISSUE TITLE
Crash on init: Realm 3.1.4,  Android 4.4.2, Multidex=true

### ISSUE THREAD

**Issue by routen** [realm/realm-java#4619]
#### Goal

Installation of APK on Samsung Tab4 running Android 4.4.2

#### Expected Results

APK Installed

#### Actual Results

```
05-09 19:19:57.474 26872-26872/com.tp.mangoandroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.tp.mangoandroid, PID: 26872
                                                                     java.lang.RuntimeException: Unable to get provider com.tp.mangoandroid.syncadapter.TxProvider: java.lang.ClassNotFoundException: Didn't find class "com.tp.mangoandroid.syncadapter.TxProvider" on path: DexPathList[[zip file "/data/app/com.tp.mangoandroid-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.tp.mangoandroid-2, /vendor/lib, /system/lib]]
                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:175)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:146)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tp.mangoandroid.syncadapter.TxProvider" on path: DexPathList[[zip file "/data/app/com.tp.mangoandroid-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.tp.mangoandroid-2, /vendor/lib, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5221)
                                                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828) 
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711) 
                                                                         at android.app.ActivityThread.access$1600(ActivityThread.java:175) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:146) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
05-09 19:19:57.484 611-3795/? W/ActivityManager:   Force finishing activity com.tp.mangoandroid/com.tp.mangoneo.main.MangoMultipleActivity
```

#### Steps & Code to Reproduce

1. Create Android project in AndroidStudio
1. Include Realm 3.1.4
1. (either in App.onCreate or onCreate of an Activity) call **Realm.init(context)** 
1. in app build file,  within "defaultConfig" set   **multiDexEnabled = true**
1. Connect Samsung Tab4 Android 4.4.2 to laptop
1. In Android Studio click green arrow to build and install APK 
1. Observe crash happening at call to Realm.init(context))

#### Step which stops crash happening

1.  set   **multiDexEnabled = false**

However, multiDex is needed for certain projects 

#### Other Android versions/devices

Exactly the same project can install and run successfully on Android 6,7 (i.e. no `java.lang.ClassNotFoundException` )

#### Code Sample

Simply, in onCreate of App class:

```java
 

@Override
    public void onCreate() {
        super.onCreate();
 
        Realm.init(this);
 
 
    }

```

#### Version of Realm and tooling
Realm version(s): 3.1.4

Realm sync feature enabled:  no

Android Studio version: 2.4 Preview 7

Which Android version and device: Android 4.4.2, Samsung Tab4

**Comment by cmelchior** [comment]
What is your minSdk? If it is below 21 you need to follow the extra steps here: https://developer.android.com/studio/build/multidex.html#mdex-gradle

**Comment by routen** [comment]
Thanks, it is 14, Will look

**Comment by Zhuinden** [comment]
Yeah you need to either `extends MultiDexApplication` or do `MultiDex.install(baseContext)` in `attachBaseContext()`
