### ISSUE TITLE
Deleting object with active listener causes Fatal signal 11 (SIGSEGV) at 0x00000178 (code=1)

### ISSUE THREAD

**Issue by michaelbukachi** [realm/realm-java#4633]
I've noticed a bug with the latest version of realm. It seems deleting an object which has an active listener causes Fatal signal 11 (SIGSEGV) at 0x00000178 (code=1) and the app just closes without even showing the anr dialog. I'm deleting the object from a background thread but the listener is on the UI thread. I've tried using object.isValid() in the listener it still crashes. Is this a bug??

**Comment by beeender** [comment]
What version are you using? Can you share the full native backtrace?

**Comment by michaelbukachi** [comment]
I'm using realm 3.0.0
This is what is shown in the stacktrace:

`05-11 20:33:00.273 15407-15407/dita.dev.myportal A/libc: Fatal signal 11 (SIGSEGV) at 0x00000178 (code=1), thread 15407 (ta.dev.myportal)`

**Comment by Zhuinden** [comment]
It is highly likely that it has been fixed in 3.1.1

**Comment by michaelbukachi** [comment]
I've update to the latest version but now I'm getting
`java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                       at io.realm.internal.UncheckedRow.nativeIsNull(Native Method)
                                                                       at io.realm.internal.UncheckedRow.isNull(UncheckedRow.java:266)
                                                                       at io.realm.OrderRealmProxy.realmGet$date(OrderRealmProxy.java:125)
                                                                       at dita.dev.myportal.HomeFragment$1.onChange(HomeFragment.java:51)
                                                                       at dita.dev.myportal.HomeFragment$1.onChange(HomeFragment.java:46)
                                                                       at io.realm.ProxyState$RealmChangeListenerWrapper.onChange(ProxyState.java:46)
                                                                       at io.realm.internal.OsObject$ObjectObserverPair.onChange(OsObject.java:67)
                                                                       at io.realm.internal.OsObject$Callback.onCalled(OsObject.java:86)
                                                                       at io.realm.internal.OsObject$Callback.onCalled(OsObject.java:71)
                                                                       at io.realm.internal.ObserverPairList.foreach(ObserverPairList.java:108)
                                                                       at io.realm.internal.OsObject.notifyChangeListeners(OsObject.java:149)
                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                       at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                       at android.os.Looper.loop(Looper.java:150)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5345)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                       at dalvik.system.NativeStart.main(Native Method)`

Don't the change listeners support deleting of objects?

**Comment by michaelbukachi** [comment]
Works now!!! Had do rebuild the entire project

**Comment by Zhuinden** [comment]
Ah, that's the row validation check that was missing and added in 3.1.4

**Comment by beeender** [comment]
@michaelbukachi great! I am closing this issue now, let me know if it needs to be reopened.
