### ISSUE TITLE
IllegalException in adapter

### ISSUE THREAD

**Issue by michaelbukachi** [realm/realm-java#4641]
Hello, a couple of my testers experience this error:
```
Fatal Exception: java.lang.IllegalStateException: Realm instance has been closed or this object or its parent has been deleted.
       at io.realm.RealmList.checkValidView(Unknown Source)
       at io.realm.RealmList.size(Unknown Source)
       at io.realm.RealmBaseAdapter.getCount(Unknown Source)
       at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:826)
       at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6728)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
       at io.realm.RealmBaseAdapter$1.onChange(Unknown Source)
       at io.realm.RealmBaseAdapter$1.onChange(Unknown Source)
       at io.realm.internal.Collection$RealmChangeListenerWrapper.onChange(Unknown Source)
       at io.realm.internal.Collection$CollectionObserverPair.onChange(Unknown Source)
       at io.realm.internal.Collection$Callback.onCalled(Unknown Source)
       at io.realm.internal.Collection$Callback.onCalled(Unknown Source)
       at io.realm.internal.ObserverPairList.foreach(Unknown Source)
       at io.realm.internal.Collection.notifyChangeListeners(Unknown Source)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```
I've checked my code and all realm instance are local except for the one in the MainActivity, for which the `close()` method is called when the activity is being destroyed; that is when a user is exiting the app. Could it be a bug in the RealmBaseAdapter?

**Comment by cmelchior** [comment]
The RealmBaseAdapter doesn't close instances, so no. Wat does your `onDestroy()` method look like?

**Comment by michaelbukachi** [comment]
protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
        if (studentResult != null) {
            studentResult.removeAllChangeListeners();
        }

        if (realm != null) {
            realm.close();
        }

    }

**Comment by Zhuinden** [comment]
I opened https://github.com/realm/realm-android-adapters/issues/112 because I think RealmBaseAdapter and RealmRecyclerViewAdapter shouldn't have different behavior if the data set is no longer valid.

**Comment by michaelbukachi** [comment]
Does that mean I have to override the `getCount()` method till it's fixed?

**Comment by Zhuinden** [comment]
Technically the Realm instance you open in `onCreateView()` and **don't close** should ***not*** be closed, but I've also had a quirky experience with the RealmCache a long time ago which is why I personally tend to have only 1 global Realm instance for the UI thread (and open Realm for bg thread with try-finally), but yes, I recommend overriding `getCount()` method and check for `getData().isValid()`

**Comment by michaelbukachi** [comment]
okay. I'll implement it

**Comment by cmelchior** [comment]
@Zhuinden thanks. Now you mention it, I do slightly recall there being some lifecycle issues with adapters and Realm even though it was closed correctly in `onDestroy`. So yes @michaelbukachi it is probably something we need to fix on our end.

**Comment by bmeike** [comment]
@michaelbukachi can you confirm that the workaround eliminates the immediate problem?  Created #4648 to track the root problem.

**Comment by zaki50** [comment]
@michaelbukachi Which version of Realm-Java are you using?

**Comment by michaelbukachi** [comment]
@bmeike I do confirm that the workaround works and I've not gotten any crashes so far

**Comment by bmeike** [comment]
@michaelbukachi Can you confirm, please, that overriding `onCount` and checking on `getData().isValid()` successfully works around the problem?  I want to make sure you are not blocked before moving on to the longer term task of finding and solving the underlying issue.  You may also want to Watch #4648 .

**Comment by michaelbukachi** [comment]
@bmeike it's working

**Comment by Zhuinden** [comment]
It will be part of patch release in realm-android-adapters as https://github.com/realm/realm-android-adapters/issues/112 is done

**Comment by bmeike** [comment]
Great!  Thanks @michaelbukachi !
Closing this ticket.  Keep your eyes on #4648 for a fix.
