### ISSUE TITLE
Crash when set the module in the RealmConfiguration

### ISSUE THREAD

**Issue by GerardPaligot** [realm/realm-java#4677]
#### Goal

Avoid crash when I specify a custom module in the Realm configuration.

#### Actual Results

It seems that the `RealmModule` annotation isn't well processed:

```console
FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to create application com.oxylane.plus.v3.application.PlusApplication: io.realm.exceptions.RealmException: Could not find io.realm.PlusAppModuleMediator
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4394)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
    Caused by: io.realm.exceptions.RealmException: Could not find io.realm.PlusAppModuleMediator
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:336)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310)
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734)
        at com.oxylane.plus.v3.application.PlusApplication.initInMemoryRealm(PlusApplication.java:170)
        at com.oxylane.plus.v3.application.PlusApplication.onCreate(PlusApplication.java:85)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.ClassNotFoundException: io.realm.PlusAppModuleMediator
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:217)
        at java.lang.Class.forName(Class.java:172)
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:331)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310) 
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734) 
        at com.oxylane.plus.v3.application.PlusApplication.initInMemoryRealm(PlusApplication.java:170) 
        at com.oxylane.plus.v3.application.PlusApplication.onCreate(PlusApplication.java:85) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.NoClassDefFoundError: io/realm/PlusAppModuleMediator
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:217) 
        at java.lang.Class.forName(Class.java:172) 
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:331) 
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310) 
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734) 
        at com.oxylane.plus.v3.application.PlusApplication.initInMemoryRealm(PlusApplication.java:170) 
        at com.oxylane.plus.v3.application.PlusApplication.onCreate(PlusApplication.java:85) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.PlusAppModuleMediator" on path: /data/app/com.oxylane.plus.debug-1.apk
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:217) 
        at java.lang.Class.forName(Class.java:172) 
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:331) 
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310) 
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734) 
        at com.oxylane.plus.v3.application.PlusApplication.initInMemoryRealm(PlusApplication.java:170) 
        at com.oxylane.plus.v3.application.PlusApplication.onCreate(PlusApplication.java:85) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5041) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
        at dalvik.system.NativeStart.main(Native Method) 
```

#### Steps & Code to Reproduce

Just execute my project and it crashs when it starts.

#### Code Sample

My gradle configuration about Realm on my root build.gradle file:

```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'io.realm:realm-gradle-plugin:3.2.1'
    }
}
```

My gradle configuration about Realm on my module build.gradle file:

```gradle
apply plugin: 'realm-android'
```

My Realm configuration on my custom Application:

> **Note:** My application is a **multidex application**!

```java
Realm.init(this);
Realm.setDefaultConfiguration(new RealmConfiguration.Builder()
        .name("plus.realm")
        .deleteRealmIfMigrationNeeded()
        .modules(new PlusAppModule())
        .build());
```

My custom Realm module:

```java
@RealmModule(classes = {StoreLocation.class, CatalogItem.class})
public class PlusAppModule {
}
```

My gradle build output about Realm:

```console
:app:transformClassesWithRealmTransformerForDebug
:app:transformClassesWithRealmTransformerForRelease
```

#### Version of Realm and tooling
Previous Realm version: My project was on 1.2.0 and everything works fine on this version.

Realm version(s): 3.2.0

Android Studio version: 3.0

Which Android version and device: KitKat

**Comment by GerardPaligot** [comment]
Ok, so for information, I had this line on my gradle build:

```console
Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
```

It seems there is an incompatibility between Realm 3 and APT but APT is now deprecated, so there isn't really a problem.

I close this issue!
