### ISSUE TITLE
Crash with "Could not find the generated proxy class"

### ISSUE THREAD

**Issue by Philluxx** [realm/realm-java#470]
The example apps crashes after start with error message "Could not find the generated proxy class". Also every simple code that uses realm.createObject(Example.class);

Caused by: io.realm.exceptions.RealmException: Could not find the generated proxy class
            at io.realm.Realm.createObject(Realm.java:387)
            at io.realm.examples.intro.RealmIntroExampleActivity.basicCRUD(RealmIntroExampleActivity.java:71)
            at io.realm.examples.intro.RealmIntroExampleActivity.realmExamples(RealmIntroExampleActivity.java:43)
            at io.realm.examples.intro.RealmIntroExampleActivity.onCreate(RealmIntroExampleActivity.java:191)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Shajeel-Afzal** [comment]
@kneth i am facing the same problem, i have read the whole conversation. Not sure @djyde has solved this problem. Can you please help?

**Comment by kneth** [comment]
@Shajeel-Afzal Can you tell a bit more about your environment, including

* version of Android Studio?
* version of Realm?
