### ISSUE TITLE
Exception has been thrown: Out of range  in .../main/cpp/io_realm_internal_Collection.cpp line 143(requested: 38 valid: 37)

### ISSUE THREAD

**Issue by CuirMoustachu** [realm/realm-java#4753]
Original title: Exception has been thrown: Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 143(requested: 38 valid: 37)

This issue was reported there : https://github.com/realm/realm-java/issues/4433 but I'm still facing to it.
This issue doesn't occur with Realm 2.3.0

### Goal
Updating all image object in background thread after they are creating earlier

### Expected Results
All updated image

### Actual Results
```
06-03 20:33:20.921 27757-27851/com.cc.realmtest E/REALM_JNI: jni: ThrowingException 2, Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 143(requested: 38 valid: 37), .
06-03 20:33:20.921 27757-27851/com.cc.realmtest E/REALM_JNI: Exception has been thrown: Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 143(requested: 38 valid: 37)
06-03 20:33:20.922 27757-27851/com.cc.realmtest E/AndroidRuntime: FATAL EXCEPTION: Thread-207353
                                                                  Process: com.cc.realmtest, PID: 27757
                                                                  java.lang.ArrayIndexOutOfBoundsException: Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 143(requested: 38 valid: 37)
                                                                      at io.realm.internal.Collection.nativeGetRow(Native Method)
                                                                      at io.realm.internal.Collection.getUncheckedRow(Collection.java:410)
                                                                      at io.realm.OrderedRealmCollectionImpl.get(OrderedRealmCollectionImpl.java:110)
                                                                      at io.realm.RealmResults.get(RealmResults.java:60)
                                                                      at com.cc.realmtest.MainActivity$2$1.run(MainActivity.java:68)
                                                                      at java.lang.Thread.run(Thread.java:818)
```

### Code Sample
At below line:

MainActivity.class
```
public class MainActivity extends AppCompatActivity {
    final static String TAG = MainActivity.class.getSimpleName();
    final static int DONE = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Realm.init(this);

        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                Realm realm = Realm.getDefaultInstance();
                Image image;
                for(int i=0;i<50;i++){
                    realm.beginTransaction();
                    image = realm.createObject(Image.class);
                    image.setImageName("bbbbb");
                    image.setUrl("aaaaaa");
                    realm.commitTransaction();
                }
                realm.close();

                Log.i(TAG, "Insert done !");

                Message msg = mHandler.obtainMessage(DONE);
                mHandler.sendMessage(msg);
            }
        });
        t1.start();
    }

    final private Handler mHandler = new Handler(){
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);

            // Called when t1 is finished
            if(msg.what == DONE){
                Thread t2 = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        Realm realm = Realm.getDefaultInstance();

                        RealmResults<Image> imageList = realm.where(Image.class)
                                .equalTo("isDownloaded",false)
                                .findAll();

                        int imageListLength = imageList.size();

                        Image image;
                        for(int i=0; i<imageListLength; i++) {
                            image = imageList.get(i);
                            realm.beginTransaction();
                            image.setInternalPath("blabla");
                            image.setDownloaded(true);
                            realm.commitTransaction();
                        }

                        realm.close();

                        Log.i(TAG, "Update done !");
                    }
                });
                t2.start();
            }
        }
    };
}
```
Image.class
```
public class Image extends RealmObject{
    String imageName;
    String internalPath;
    String url;
    boolean isDownloaded;

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public boolean isDownloaded() {
        return isDownloaded;
    }

    public void setDownloaded(boolean downloaded) {
        isDownloaded = downloaded;
    }

    public String getInternalPath() {
        return internalPath;
    }

    public void setInternalPath(String internalPath) {
        this.internalPath = internalPath;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
}
```
### Version of Realm and tooling

- Realm version(s): 3.3.1
- Realm sync feature enabled: no
- Android Studio version: 2.3.2
- Which Android version and device: 5.1.1 Sony Xperia M2

**Comment by Zhuinden** [comment]
```
3.0.0 (2017-02-28)

Breaking Changes

RealmResults is auto-updated continuously. Any transaction on the current thread which may have an impact on the order or elements of the RealmResults will change the RealmResults immediately instead of change it in the next event loop. The standard RealmResults.iterator() will continue to work as normal, which means that you can still delete or modify elements without impacting the iterator. The same is not true for simple for-loops. In some cases a simple for-loop will not work (https://realm.io/docs/java/3.0.0/api/io/realm/OrderedRealmCollection.html#loops), and you must use the new createSnapshot() method.
```

**Comment by Zhuinden** [comment]
Technically 

``` java
                        RealmResults<Image> imageList = realm.where(Image.class)
                                .equalTo("isDownloaded",false) // <--- false
                                .findAll();

                        int imageListLength = imageList.size();
                        Image image;
                        for(int i=0; i<imageListLength; i++) {
                            image = imageList.get(i);
                            realm.beginTransaction();
                            image.setDownloaded(true); // <--- true 
```

**Comment by CuirMoustachu** [comment]
Reactive as Realm, thanks a lot. It solves my issue. I've completely forgot to check the changelog.
I will work with this : 

```
for(Image image : imageList){
           realm.beginTransaction();
           image.setInternalPath("blabla");
           image.setDownloaded(true);
           realm.commitTransaction();
}
```

I saw that this iterator will use a snapshot behind the scenes, Is there a difference between this and creating a snapchot explicitly ?

**Comment by zaki50** [comment]
No difference between them.

I'm closing this issue. Feel free to reopen this if you have further question.
