### ISSUE TITLE
jni: ThrowingException 2, Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 417(requested: 1 valid: 1), .

### ISSUE THREAD

**Issue by shivamsriva31093** [realm/realm-java#4756]
I am using a RecyclerView with realm 3.3.1 .  The use case is simply to store realm objects in the database and then use SparseBoolean array to delete multiple items from the RV. 

When does the crash occur? 

The fatal crash occurs when I select multiple items to delete from the recyclerview. This exception is produced when I selected 2 items out of 2 for deletion.
**The crash happens when I am using Asus T00J Zenfone 5 and HTC one M8 both running Android 5.0. Everything runs smooth when I use the app on Android 6 or 7**

How am I deleting?

```
private void deleteSelectedItems() {
        final List<Integer> items = adapter.getSelectedItems();
        for (int pos : items) {
            adapter.removeItem(pos);
        }
    }
```
My recyclerview :
```
private class RecViewAdapter extends RealmRecViewAdapter<MediaItem, RecViewAdapter.ViewHolder> {
.
.
.
.
public void removeItem(final int pos) {
            Log.d("test", pos+" index");
            realm.executeTransaction(realm1 -> {
                getData().deleteFromRealm(pos); //getting exception at this line
                notifyDataSetChanged();
            });
        }
```

Exception:

``` 06-05 03:03:27.518 20378-20378/task.application.com.moviefinder E/REALM_JNI: jni: ThrowingException 2, Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 417(requested: 1 valid: 1), .
06-05 03:03:27.518 20378-20378/task.application.com.moviefinder E/REALM_JNI: Exception has been thrown: Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 417(requested: 1 valid: 1)
06-05 03:03:27.518 20378-20378/task.application.com.moviefinder D/AndroidRuntime: Shutting down VM
06-05 03:03:27.518 20378-20378/task.application.com.moviefinder E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: task.application.com.moviefinder, PID: 20378
                                                                                  java.lang.ArrayIndexOutOfBoundsException: Out of range  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 417(requested: 1 valid: 1)
                                                                                      at io.realm.internal.Collection.nativeDelete(Native Method)
                                                                                      at io.realm.internal.Collection.delete(Collection.java:477)
                                                                                      at io.realm.OrderedRealmCollectionImpl.deleteFromRealm(OrderedRealmCollectionImpl.java:181)
                                                                                      at io.realm.RealmResults.deleteFromRealm(RealmResults.java:60)
                                                                                      at task.application.com.moviefinder.ui.favorites.FavoritesMediaFragment$RecViewAdapter.lambda$removeItem$2(FavoritesMediaFragment.java:261)
                                                                                      at task.application.com.moviefinder.ui.favorites.FavoritesMediaFragment$RecViewAdapter$$Lambda$1.execute(Unknown Source)
                                                                                      at io.realm.Realm.executeTransaction(Realm.java:1443)
                                                                                      at task.application.com.moviefinder.ui.favorites.FavoritesMediaFragment$RecViewAdapter.removeItem(FavoritesMediaFragment.java:260)
                                                                                      at task.application.com.moviefinder.ui.favorites.FavoritesMediaFragment.deleteSelectedItems(FavoritesMediaFragment.java:165)
                                                                                      at task.application.com.moviefinder.ui.favorites.FavoritesMediaFragment.access$500(FavoritesMediaFragment.java:41)
                                                                                      at task.application.com.moviefinder.ui.favorites.FavoritesMediaFragment$3.onActionItemClicked(FavoritesMediaFragment.java:147)
                                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:3172)
                                                                                      at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:173)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImplV9.java:1801)
                                                                                      at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
                                                                                      at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                                      at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                                      at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                                                      at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                                      at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                                                      at android.view.View.performClick(View.java:4756)
                                                                                      at android.view.View$PerformClick.run(View.java:19761)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)```

**Comment by Zhuinden** [comment]
Well this is kind of tricky but as you are:

1.) executing multiple transactions

2.) deleting items from the database, which also modifies the RealmResults each time 

Technically I'll illustrate what happens like this, let's assume you have following items

`[Jack, Jill, William, Roger]`

And let's say you selected `jill` and `roger`, so you get position `[1, 3]`

You iterate the array of `[1, 3]`, expecting you'll delete `Jill` and `Roger`, right... but that is not what will happen

Execute transaction, delete position `1`, the transaction modifies Realm and updates the RealmResults immediately.

Now you have `[Jack, William, Roger]`.

then you are iterating the array further and you try to delete position `3`.

Now as you can see, RealmResults is `size 2`, and you crash with ArrayIndexOutOfBoundsException.

**Comment by Zhuinden** [comment]
A possible solution would be this:

    private void deleteSelectedItems() {
        final List<Integer> items = adapter.getSelectedItems();
        realm.executeTransaction((r) -> {
            OrderedRealmCollection<MediaItem> snapshot = adapter.getData().createSnapshot();
            for (int pos : items) {
                snapshot.deleteFromRealm(pos);
            }
        });
    }

**Comment by shivamsriva31093** [comment]
This is working great!! Thank you @Zhuinden  for resolving the issue. However, I was wondering why the previous code is working fine on Android 6.0 and above.

**Comment by Zhuinden** [comment]
Luck. It depends on what positions you had selected.

**Comment by shivamsriva31093** [comment]
I figured it out. :P Thank you anyways. ^_^
