### ISSUE TITLE
Problem with GSON serializing of RealmObject

### ISSUE THREAD

**Issue by iovorobiev** [realm/realm-java#476]
If I extend my object from RealmObject, and try to serialize it with GSON, than I getting stackoverflow error, like this

```
 java.lang.StackOverflowError
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
            at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:376)
```

You can try it on this example:

``` java
public class Temp extends RealmObject{
    private int i;


    public int getI() {
        return i;
    }

    public void setI(int i) {
        this.i = i;
    }
}
```

and

``` java
realm.beginTransaction();
Temp testClass = realm.createObject(Temp.class);
testClass.setI(1);
Gson gson = new Gson();
gson.toJson(testClass);
realm.commitTransaction();
```

If I try to do same thing with non RealmObject, than all works fine.
May be this issue with gson can help you https://code.google.com/p/google-gson/issues/detail?id=440 .

**Comment by AnixPasBesoin** [comment]
I'm having the same issue here.
I'm usign the latest version of Realm and the latest version of Gson.
I posted a [question ](http://stackoverflow.com/questions/41721800/stackoverflow-when-serializing-realmobject-with-gson)on stackoverflow.

**Comment by Zhuinden** [comment]
Gson gson = new GsonBuilder()
        .setExclusionStrategies(new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(RealmObject.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        })
        .create();
