### ISSUE TITLE
Catch Runtime Exception during realm initialization

### ISSUE THREAD

**Issue by michaelbukachi** [realm/realm-java#4772]
Referencing this issue: https://github.com/realm/realm-java/issues/4702
Is it possible to catch this exception specifically? I've just realized that this exception causes the app to crash in the background without affecting the frontal view. This however cause error logs to be sent to analytics, which is quite annoying because it's only affecting one device. So is it possible to catch so that I can ignore it if it occurs?

**Comment by michaelbukachi** [comment]
I've implemented it as so:
```
try {
        Realm.init(this);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(14)
                .migration(new Migration())
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
} catch (RuntimeException e) {
        Crashlytics.logException(e);
}
```

Is there any way to narrow down the exception to those cause by the wrong librealm.so?

**Comment by kneth** [comment]
We are using ReLinker to load `.so` files. My best guess is that you will see `UnsatisfiedLinkError`.

**Comment by michaelbukachi** [comment]
That's not it. Beyond RuntimeException there's no other error shown
```
Fatal Exception: java.lang.RuntimeException: Unable to create application dita.dev.myportal.MyPortal: up: lib/armeabi/librealm-jni.so
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4351)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by up: lib/armeabi/librealm-jni.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:85)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
       at io.realm.Realm.init(Realm.java:197)
       at dita.dev.myportal.MyPortal.onCreate(MyPortal.java:50)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4348)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by beeender** [comment]
> it's only affecting one device.

What device it is?

The exception was thrown from here https://github.com/KeepSafe/ReLinker/blob/935700583b6027ffe2f18521a24d4bbf24e01c77/relinker/src/main/java/com/getkeepsafe/relinker/ApkLibraryInstaller.java#L85

It feels like the apk file the device got doesn't have the `so` file.

Can you see the ABI information about this device anywhere?

**Comment by michaelbukachi** [comment]
Here it is:
##### OS Version: 4.4.2
##### Device: SM-G900R7
##### RAM Free: 64.5%
##### Disk Free: 73.8%

The apk does have the .so file. I  have confirmed this. Other devices are using the same apk but are not being affected by this error.

**Comment by beeender** [comment]
I am a bit confused. So this `SM-G900R7` is one of your testing device or the issue is reported by the real user?

I guess the problem is caused by installing split apk with **arm64** only so file to this device. The device is using snapdragon 801 which is a 32 bit cpu device.

Can you just install a apk with armv7a so file to this device so the problem will just be fixed?

**Comment by michaelbukachi** [comment]
Okay. Will tell the tester to do that. Though I'm still boggled up with the fact that Playstore downloaded the wrong apk version. But that's beyond realm.

Thanks:)
