### ISSUE TITLE
io.realm.exceptions.RealmError:    at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java:0)

### ISSUE THREAD

**Issue by tarunism** [realm/realm-java#4777]
Hi, 

We are using realm in production following crash has very high frequency.

io.realm.exceptions.RealmError: 
  at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java:0)
  at io.realm.internal.SharedRealm.<init>(SharedRealm.java:192)
  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:244)
  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:208)
  at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:298)
  at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
  at io.realm.Realm.getDefaultInstance(Realm.java:273)

Please help us in solving it.

**Comment by Zhuinden** [comment]
do you use encryption? What is your Realm version? Do you open the first Realm in `application.onCreate()` (yes/no)?

**Comment by tarunism** [comment]
- relax version:  "io.realm:realm-gradle-plugin:3.3.1"
- Not using any encryption
- Do you open the first Realm in application.onCreate() - YES

**Comment by tarunism** [comment]
<img width="318" alt="screen shot 2017-06-13 at 1 32 19 pm" src="https://user-images.githubusercontent.com/17875699/27072060-c64e3e78-503c-11e7-9dae-d795932a7696.png">

device list on which this crash is reported so far.

**Comment by beeender** [comment]
Can you please show the completed back trace? There should be some description text following the `RealmError` in the exception message.

**Comment by Zhuinden** [comment]
You should try making UI-thread Realm lifecycle management be driven by open activity count. 

If you have multiple processes, then opening Realm in application.onCreate() can cause trouble. 

See https://stackoverflow.com/questions/44331742/how-to-manage-realm-instance/44337690#44337690

**Comment by tarunism** [comment]
io.realm.exceptions.RealmError: 
  at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java:0)
  at io.realm.internal.SharedRealm.<init>(SharedRealm.java:192)
  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:244)
  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:208)
  at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:298)
  at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
  at io.realm.Realm.getDefaultInstance(Realm.java:273)
  at in.upstox.pro.database.BODDataSource.getStockDetail(BODDataSource.java:115)
  at in.upstox.pro.views.watchlist.WatchListFragment.getStockDetail(WatchListFragment.java:794)
  at in.upstox.pro.views.watchlist.WatchListFragment.getWatchListItemsByName(WatchListFragment.java:832)
  at in.upstox.pro.views.watchlist.WatchListFragment.updateList(WatchListFragment.java:890)
  at in.upstox.pro.views.main.CarouselActivity.updateList(CarouselActivity.java:1626)
  at in.upstox.pro.views.main.CarouselActivity.onResume(CarouselActivity.java:1487)
  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
  at android.app.Activity.performResume(Activity.java:6608)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3106)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3148)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1395)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5437)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by beeender** [comment]
@tarunism 
1. Does it happen to the previous version of Realm?
2. Can you share your apk with us? to help@realm.io if you want to share it privately.

**Comment by tarunism** [comment]
1. Yes, we are seeing it from past more than a month, also upgraded the realm as and when its available.
2. https://play.google.com/store/apps/details?id=in.upstox.pro

**Comment by beeender** [comment]
@tarunism I tried your apk, no crash on my phone :(

1. For the exception message, it should give you some thing like:
```
Caused by io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Bad file descriptor in io_realm_internal_SharedGroup.cpp line 113
at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
```
Are you sure you didn't get any description message following the `RealmError:` ? That would be very strange since at least it will show the file name and the line number. Are you using crashlytics to collect the log? Can you share the cryshlytics link about this crash with us?

2. Can you share the code how do you build the `RealmConfiguration`?

**Comment by tarunism** [comment]
@beeender 
I have taken this log from Play store console.
We are not using crashlytics.

In Applicatoin.OnCreate()

Realm.init(this);
RealmConfiguration realmConfig = new RealmConfiguration.Builder().deleteRealmIfMigrationNeeded().build();
        Realm.setDefaultConfiguration(realmConfig);

**Comment by beeender** [comment]
@tarunism can you please check the Play store console again? The exception message of `RealmError` should be there. It is critical for us to locate the issue. Thanks.

**Comment by tarunism** [comment]
@beeender Sorry, i have checked 100+ callstacks, all places its same as above :(

**Comment by beeender** [comment]
@tarunism I am guessing this might have the similar root cause with #2459 -- for some reason, when updating the apk from play store, the original app process was not killed before starting a new one.

If that is the case, since you are using `deleteRealmIfMigrationNeeded()` which is not a multi-processes safe call, it may crash the previous version of the apk process.

Are you able to see the crash trend in play store console? If my assumption is right, you will see a peak of the crash rate after you upload the new apk to play store then the crash rate gets lower afterwards. Then you might see a peak again after a new apk release.

**Comment by tarunism** [comment]
I think its not happening only in apk update case. Please have a look on following graph.

![r](https://user-images.githubusercontent.com/17875699/27296218-9df1f48c-553d-11e7-9ab2-6a3abe642adc.jpeg)

**Comment by beeender** [comment]
I have tried your apk on some of my device, no luck to reproduce the crash :(

Without the exception description it is really hard to guess what is going wrong ...

I saw some others who are using google play console could get the stack trace with valid exception description, like https://stackoverflow.com/questions/35180252/export-all-stack-traces-from-google-developer-console

I am wondering maybe there is something wrong with deobfuscating? Do https://support.google.com/googleplay/android-developer/answer/6295281?hl=en and https://stackoverflow.com/questions/44087529/cannot-figure-out-google-play-console-stack-trace-spike help?

**Comment by KunalShivnekar** [comment]
@beeender I'm @tarunism's team-mate. We are following the same deobfuscation process as described in the link you shared.
The trace shared by @tarunism were from the real-time crash feature of Play Console, which didn't have the full description. I got another one today, which has some more info. I hope this helps.

io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 167772160 offset: 0 in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 233
in at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java).nativeGetSharedRealm

**Stack Trace**
at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:244)
	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:208)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:298)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
	at io.realm.Realm.getDefaultInstance(Realm.java:273)
	at in.upstox.pro.database.BODDataSource.getStockDetail(BODDataSource.java:115)
	at in.upstox.pro.views.watchlist.WatchListFragment.getStockDetail(WatchListFragment.java:794)
	at in.upstox.pro.views.watchlist.WatchListFragment.getWatchListItemsByName(WatchListFragment.java:832)
	at in.upstox.pro.views.watchlist.WatchListFragment.onViewCreated(WatchListFragment.java:453)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1314)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1595)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2900)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6549)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.access$900(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5437)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Zhuinden** [comment]
@KunalShivnekar in that case the same thing applies as to  
https://github.com/realm/realm-java/issues/4813#issuecomment-309528769

Meaning Realm is used on a non-looping background thread pool (for example AsyncTask) and Realm instance is not closed properly, and outdated versions can't get released. 

A possible hackfix is to refresh Realm on background thread manually after you get the instance of it, but generally proper Realm lifecycle management is a better long-term solution.

**Comment by KunalShivnekar** [comment]
Ok, I'm calling refresh() on the instance returned by Realm.getDefaultInstance(). Let's see if this solves the issue.

**Comment by cmelchior** [comment]
@KunalShivnekar I assume the above solved it. Please re-open if that is not the case.
