### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method add(Lio/realm/Property;)Lio/realm/RealmObjectSchema; in class Lio/realm/RealmObjectSchema

### ISSUE THREAD

**Issue by sdaduanbilei** [realm/realm-java#4829]
>** ERROR**：
```java
Process: ch999.app.UI, PID: 7374
 java.lang.NoSuchMethodError: No virtual method add(Lio/realm/Property;)Lio/realm/RealmObjectSchema; in class Lio/realm/RealmObjectSchema; or its super classes (declaration of 'io.realm.RealmObjectSchema' appears in /data/app/ch999.app.UI-2/split_lib_dependencies_apk.apk:classes36.dex)
                                                                at io.realm.DirectDataRealmProxy.createRealmObjectSchema(DirectDataRealmProxy.java:706)
                                                                at io.realm.BaseRealmModuleMediator.createRealmObjectSchema(BaseRealmModuleMediator.java:58)
                                                                at io.realm.internal.modules.CompositeMediator.createRealmObjectSchema(CompositeMediator.java:66)
                                                                at io.realm.Realm.initializeRealm(Realm.java:440)
                                                                at io.realm.Realm.createAndValidateFromCache(Realm.java:401)
                                                                at io.realm.Realm.createInstance(Realm.java:364)
                                                                at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:346)
                                                                at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
                                                                at io.realm.Realm.getInstance(Realm.java:293)
                                                                at com.ch999.util.BaseInfo.<init>(BaseInfo.java:59)
                                                                at com.ch999.util.BaseInfo.getInstance(BaseInfo.java:64)
                                                                at ch999.app.UI.JiujiApplication.setUp(JiujiApplication.java:80)
                                                                at ch999.app.UI.JiujiApplication.access$000(JiujiApplication.java:46)
                                                                at ch999.app.UI.JiujiApplication$1.run(JiujiApplication.java:58)
                                                                at java.lang.Thread.run(Thread.java:761)
```

```
classpath 'com.android.tools.build:gradle:2.3.3'
classpath "io.realm:realm-gradle-plugin:2.3.1"
```

2.3.2 perfectly normal before, then I through the APT to introduce third-party tools, began to appear error, access to information, I remove the "apply plugin: 'android - APT" and "annotationProcessor" instead, start now has been an error, version of the drop is not normal, be badly in need of help

#### Version of Realm and tooling
Realm version(s): 3.3.2

Android Studio version: 2.3.3

Which Android version and device: 

nexus5   oneplus   android 7.1.1

**Comment by sdaduanbilei** [comment]
@realm-ci

**Comment by beeender** [comment]
try `./gradlew build --refresh-dependencies`?

**Comment by sdaduanbilei** [comment]
@beeender 
```java
Cached resource https://jcenter.bintray.com/org/apache/commons/commons-parent/9/commons-parent-9.pom is up-to-date (lastModified: Sun Aug 31 19:46:18 CST 2008).
Cached resource https://jcenter.bintray.com/io/realm/realm-annotations/3.1.1/realm-annotations-3.1.1.pom is up-to-date (lastModified: Fri Apr 07 20:29:38 CST 2017).
Cached resource https://jcenter.bintray.com/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.pom is up-to-date (lastModified: Thu Jun 25 20:09:00 CST 2015).
``` 
version  3.1.1   
The same error

**Comment by beeender** [comment]
@sdaduanbilei are you using multi dex?

**Comment by sdaduanbilei** [comment]
@beeender yes  , project is too big ,  And it's been used all the time

**Comment by beeender** [comment]
@sdaduanbilei is it possible to share your whole `build.gradle` with us?

**Comment by sdaduanbilei** [comment]
```gradle
apply plugin: 'com.android.application'
apply plugin: 'realm-android'

def cfg = rootProject.ext.configuration

android {

    compileSdkVersion cfg.compileSdkVersion
    buildToolsVersion cfg.buildToolsVersion

    defaultConfig {
        applicationId "ch999.app.UI"
        minSdkVersion cfg.minSdkVersion
        targetSdkVersion cfg.targetSdkVersion
        versionCode cfg.versionCode
        versionName cfg.versionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    testCompile 'junit:junit:4.12'
//        compile project(':BaseLib')
    compile(cfg.BaseLibVersion) {
        exclude module: 'support-v4'
        exclude module: 'BaseRes'
    }
//    compile project(':BaseRes')
    compile(cfg.BaseResVersion) {
        exclude module: 'support-v4'
        exclude module: 'BaseLib'
    }

//    compile project(':cart')
    compile('com.ch999:cart:1.8.7') {
        exclude module: 'support-v4'
        exclude module: 'BaseLib'
        exclude module: 'BaseRes'
    }
//

//    compile project(':home')
    compile('com.ch999:home:2.0.3') {
        exclude module: 'support-v4'
        exclude module: 'BaseRes'
        exclude module: 'BaseLib'
    }
*****
 compile module aar
*****
 

    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'
    annotationProcessor 'com.github.mzule.activityrouter:compiler:1.1.7'
}
```

Multiple module development

**Comment by beeender** [comment]
just to confirm, you don't accidentally have both `classpath "io.realm:realm-gradle-plugin:3.3.2"` and `classpath "io.realm:realm-gradle-plugin:2.3.1"` in your **project level** `build.gradle`, do you?

**Comment by sdaduanbilei** [comment]
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath "io.realm:realm-gradle-plugin:3.1.1"
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.12"
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by zaki50** [comment]
@sdaduanbilei  Are you using Realm in some library projects?

**Comment by sdaduanbilei** [comment]
@zaki50  every ```build.gradle``` of my library module adds the ```apply plugin: 'com.android. Library' ```

**Comment by zaki50** [comment]
How about Realm?
Do you have any dependencies to pre-built AARs that use Realm?

**Comment by Zhuinden** [comment]
Try disabling Instant Run, then cleaning your project, then running it again

**Comment by sdaduanbilei** [comment]
```java
com.ch999:BaseRes:2.1.6
|    +--- io.realm:realm-android-library:2.3.1 -> 3.3.2 (*)
|    +--- io.realm:realm-annotations:2.3.1 -> 3.3.2
|    +--- in.srain.cube:ultra-ptr:1.0.11
|    +--- com.android.support:recyclerview-v7:25.1.1 -> 25.3.1 (*)
|    +--- com.daimajia.swipelayout:library:1.2.0
```

```java
com.ch999:msgcenter:1.5.4
|    +--- io.realm:realm-android-library:3.3.2 (*)
|    +--- io.realm:realm-annotations:3.3.2
|    \--- com.android.support.constraint:constraint-layout:1.0.2 (*)
+--- com.ch999:topic:1.9.2
|    +--- io.realm:realm-android-library:3.3.2 (*)
|    +--- io.realm:realm-annotations:3.3.2
|    +--- com.android.support:appcompat-v7:25.1.0 -> 25.3.1 (*)
|    \--- com.ch999:wexxlib:1.0.7
|         +--- io.realm:realm-android-library:3.3.2 (*)
|         +--- io.realm:realm-annotations:3.3.2
|         \--- com.android.support:appcompat-v7:25.1.0 -> 25.3.1 (*)
+--- com.ch999:jshi:1.7.5
|    +--- io.realm:realm-android-library:3.3.2 (*)
|    +--- io.realm:realm-annotations:3.3.2
|    +--- com.android.support:appcompat-v7:25.1.0 -> 25.3.1 (*)
|    +--- com.nineoldandroids:library:2.4.0
|    \--- com.zhy:flowlayout-lib:1.0.3 (*)
```
```./gradlew :app:dependencies``` 

Two tips appear above, each of my librarymodules has a realm library, and I used it until I joined apt. I just had a realm version upgrade

**Comment by zaki50** [comment]
@sdaduanbilei As the output says, `com.ch999:BaseRes:2.1.6` originally has a dependency to `io.realm:realm-android-library:2.3.1` but updated to `io.realm:realm-android-library:3.3.2`.

That means `com.ch999:BaseRes:2.1.6` was compiled with `io.realm:realm-android-library:2.3.1` and contains generated code for that version.

You can't mix multiple versions of Realm since generated code does not have a compatibility across version.

To solve this, you need to recompile `com.ch999:BaseRes:2.1.6` with Realm 3.3.2.

**Comment by sdaduanbilei** [comment]
@zaki50 Great ，thank you recompile ``` com.ch999:BaseRes:**``` , And then it's normal

**Comment by PGMacDesign** [comment]
I am facing this same issue. 
I just updated from Realm `4.2.0` to `6.0.0` and am running into the same problem. 
As this is for an active app that needs the dependency to run, how do I go about converting the DB to the new version without losing the app data of my users?

**Comment by Zhuinden** [comment]
This sounds like something you should either be able to fix with a clean/rebuild, or you are using another Realm-based library that is using an outdated version of Realm *and* relies on outdated internal code.

For example, an old version of Realm-Stetho could easily cause this problem.

**Comment by PGMacDesign** [comment]
@Zhuinden Ha! Spot on correct. The issue was that my library code had switched to Realm `6.0.0` but my app using said dependency was still on `4.2.0`. Thank you very much for catching that.
