### ISSUE TITLE
io.realm.internal.SharedRealm.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by varunvairavan** [realm/realm-java#4836]
Fatal Exception: java.util.concurrent.TimeoutException: io.realm.internal.SharedRealm.finalize() timed out after 10 seconds
       at io.realm.internal.SharedRealm.nativeCloseSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.close(SharedRealm.java:310)
       at io.realm.internal.SharedRealm.finalize(SharedRealm.java:319)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)

Unable to reproduce this issue, but this is the second crash this week with the same trace.

io.realm:realm-gradle-plugin:2.0.2
io.realm:android-adapters:1.4.0

Sync not enabled

Android studio version 2.4 preview 6

<img width="934" alt="screen shot 2017-06-22 at 11 49 41 pm" src="https://user-images.githubusercontent.com/1890890/27455339-a473660a-57a5-11e7-9971-bf17a33af31d.png">

**Comment by Zhuinden** [comment]
This was fixed in Realm 2.2.2 (although 2.3.0 is more stable)

**Comment by beeender** [comment]
Please update your Realm version. I am closing this issue now. Please let us know if there is more help needed on it.
