### ISSUE TITLE
java.lang.IllegalArgumentException: Realm on disk is newer than the one specified: v4 vs. v0

### ISSUE THREAD

**Issue by ecramer** [realm/realm-java#4851]
#### Expected Results

No exception to be thrown. Correct default realm instance acquired.

#### Actual Results
```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.example.app.activities.TasksSublistActivity}: java.lang.IllegalArgumentException: Realm on disk is newer than the one specified: v4 vs. v0
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.IllegalArgumentException: Realm on disk is newer than the one specified: v4 vs. v0
       at io.realm.Realm.createAndValidateFromCache(Realm.java:394)
       at io.realm.Realm.createInstance(Realm.java:348)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:346)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
       at io.realm.Realm.getDefaultInstance(Realm.java:273)
       at com.example.app.TasksSublistActivity.setToolbarTitle(TasksSublistActivity.java:108)
       at com.example.app.activities.TasksSublistActivity.onCreate(TasksSublistActivity.java:66)
       at android.app.Activity.performCreate(Activity.java:6955)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

#### Steps & Code to Reproduce

This is happening in production in my app. I have not been able to reproduce it myself but it has happened to several users. Below I have pasted my migration code which is the only thing that has changed since this issue has started happening. I need to perform the realm migration in the background in order to show a spinner. All users have been upgrading from v3 to v4 so I have no idea where v0 even comes in to play.

#### Code Sample

This is how I am doing a database migration. It is done inside my SplashActivity:

```java

		RealmConfiguration realmConfig = new RealmConfiguration.Builder().schemaVersion(4).migration(new SchemaMigration()).build();
		try (DynamicRealm dynamicRealm = DynamicRealm.getInstance(realmConfig)) {

			if (dynamicRealm.getVersion() != -1 && dynamicRealm.getVersion() < CURRENT_SCHEMA_VERSION) {
				//show progress indicator
				showProgressDialog();

				Completable.fromAction(() -> Realm.migrateRealm(realmConfig))
						.subscribeOn(Schedulers.io())
						.observeOn(AndroidSchedulers.mainThread())
						.subscribe(() -> {
							progressDialog.dismiss();
							Realm.setDefaultConfiguration(realmConfig);
						});

			} else {
				Realm.setDefaultConfiguration(realmConfig);
			}
		}

```

The exception is thrown from varying activities from simply calling:

```java
Realm.getDefaultInstance()
```

I only ever get the realm instance by using the default. 

#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: LGE, HTC, Samsung devices running 6 and 7

**Comment by kneth** [comment]
Does `SchemaMigration.migrate()` set the schema version?

**Comment by zaki50** [comment]
Hi @ecramer

It seems that `TasksSublistActivity` was started before `Realm.setDefaultConfiguration(realmConfig);`.

Do you wait for finishing migration?

**Comment by ecramer** [comment]
Assuming that Realm.migrate is synchronous then yes, the migration completes before starting that activity. The schema version is set correctly during the migration. 

In the stack trace, line 348 in Realm.java, when I call Realm.getDefaultInstance it hits that line which seems to say that it thinks it's a DynamicRealm instead of Realm which I am actually using. Why would that be?

**Comment by ecramer** [comment]
Actually @kneth can you elaborate on your question? I'm not actually setting the schema version anywhere in the migration.

**Comment by cmelchior** [comment]
@ecramer If you don't set the version number if defaults to `0`, which is what the exception says. The exception means that the on-disk has v4, but your RealmConfiguration is set to v0 (default).

**Comment by ecramer** [comment]
@cmelchior can you point me to where this function is? The only setVersion function I see is package protected. I was under the impression that it was set using the RealmConfig schema version value. Also, curious as to why this only started happening now. This didn't start happening until I started triggering the realm migration manually. Thanks!

**Comment by cmelchior** [comment]
https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.Builder.html#schemaVersion-long-

**Comment by ecramer** [comment]
@cmelchior I feel like I am missing something
My code above shows:
`RealmConfiguration realmConfig = new RealmConfiguration.Builder().schemaVersion(4).migration(new SchemaMigration()).build();
`
This is what you linked, yes?

**Comment by ecramer** [comment]
I came across this last night: https://github.com/realm/realm-java/issues/4083

You commented on there with something that works with the current API. Do you think my problem could be that I need to close the dynamic realm before setting the default configuration?

**Comment by cmelchior** [comment]
No, the DynamicRealm shouldn't have any effect on migrations.
You migration code is running asynchronously though (`Schedulers.io()`), so if you call `Realm.getDefaultInstance()` while your migration is running, you haven't set your own default configuration yet, in which case it defaults to ours which has `schemaVersion(0)`.

To me it looks like a timing issue.

**Comment by ecramer** [comment]
@cmelchior yes I would agree, however this activity doesn't finish until the migration has completed. The sample above doesn't show that but it does in fact wait until the subscribe runs to call finish() and start a new activity.

**Comment by cmelchior** [comment]
My guess is that you have another Activity being displayed before your Splash activity starts or that people can dismiss the Splash activity.

I don't know how you detect when to display the splash activity, but if you are on Screen A, when the app goes to sleep and then wakes up, Screen A will be the first one displayed. Even if you detect that a SplashActivity needs to be displayed and you call finish() on Screen A, it will still go through all lifecycle methods before showing the SplashActivity (onStart/onResume/onPause/onStop)`. If you open the Realm in any of those, I suspect you can get into situations where this occurs.

**Comment by ecramer** [comment]
@cmelchior I see. That could very well be the issue. My RealmConfig was set in the Application class prior to this change
