### ISSUE TITLE
 java.lang.IllegalArgumentException: Each element of 'value' must be a valid managed object.

### ISSUE THREAD

**Issue by sanju93** [realm/realm-java#4863]
#### Goal

> Add data to realm

#### Expected Results

> Add data to realm

#### Actual Results

>   FATAL EXCEPTION: main
                                                                         Process: in.codemac.piyarspm.app, PID: 16559
                                                                         java.lang.IllegalArgumentException: Each element of 'value' must be a valid managed object.
                                                                             at io.realm.DBPurchaseRealmProxy.realmSet$items(DBPurchaseRealmProxy.java:184)
                                                                             at in.codemac.piyarspm.app.model.db.DBPurchase.setItems(DBPurchase.java:47)
                                                                             at in.codemac.piyarspm.app.ui.PurchaseFinalDetailsFragment.addDataToRealm(PurchaseFinalDetailsFragment.java:263)
                                                                             at in.codemac.piyarspm.app.ui.PurchaseFinalDetailsFragment.getFinalDetails(PurchaseFinalDetailsFragment.java:205)
                                                                             at in.codemac.piyarspm.app.ui.PurchaseFinalDetailsFragment$4.onClick(PurchaseFinalDetailsFragment.java:168)
                                                                             at android.view.View.performClick(View.java:5610)
                                                                             at android.view.View$PerformClick.run(View.java:22265)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

>
//declarations and initialisations
 private static RealmList<DBPurchase> purchaseRealmList = new RealmList<>();
    private static RealmList<DBPurchaseQtyItem> purchaseQtyItemRealmList = new RealmList<>();
    private static RealmList<DBPurchaseEmployee> purchaseEmployeeRealmList = new RealmList<>();
    private static int id = 1;
    DBPurchase mDBPurchase = new DBPurchase();
    DBPurchaseQtyItem mDBPurchaseQtyItem = new DBPurchaseQtyItem();
    DBPurchaseEmployee mDBPurchaseEmployee = new DBPurchaseEmployee();
    DBPurchaseItem mDBPurchaseItem = new DBPurchaseItem();
    DBEmployee mDBEmployee = new DBEmployee();

//this method gets called when I want to add data to realm
private void addDataToRealm(DBPurchase model) {
        mRealm.beginTransaction();
        DBPurchase dbPurchaseModel = mRealm.createObject(DBPurchase.class);
        dbPurchaseModel.setId(id);
        dbPurchaseModel.setAmountPayed(model.getAmountPayed());
        dbPurchaseModel.setCredit(model.getCredit());
        dbPurchaseModel.setTotalAmount(model.getTotalAmount());
        dbPurchaseModel.setItems(purchaseQtyItemRealmList);
        dbPurchaseModel.setPayedEmployees(purchaseEmployeeRealmList);
        dbPurchaseModel.setCreatedAt(model.getCreatedAt());
        dbPurchaseModel.setLastUpdatedAt(model.getLastUpdatedAt());
        purchaseRealmList.add(dbPurchaseModel);
        mRealm.commitTransaction();
        //purchaseFinalDetailsAdapter.notifyDataSetChanged();
        id++;
    }
>
//DBPurchase model class
import android.support.annotation.Nullable;

import java.util.Date;

import io.realm.RealmList;
import io.realm.RealmModel;
import io.realm.RealmObject;

public class DBPurchase extends RealmObject {

    private int id;

    private RealmList<DBPurchaseQtyItem> items;

    private double totalAmount;

    private double amountPayed;

    private double credit;

    @Nullable
    private RealmList<DBPurchaseEmployee> payedEmployees;

    private Date createdAt = new Date();

    private Date lastUpdatedAt;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public RealmList<DBPurchaseQtyItem> getItems() {
        return items;
    }

    public void setItems(RealmList<DBPurchaseQtyItem> items) {
        this.items = items;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public double getAmountPayed() {
        return amountPayed;
    }

    public void setAmountPayed(double amountPayed) {
        this.amountPayed = amountPayed;
    }

    public double getCredit() {
        return credit;
    }

    public void setCredit(double credit) {
        this.credit = credit;
    }

    public RealmList<DBPurchaseEmployee> getPayedEmployees() {
        return payedEmployees;
    }

    public void setPayedEmployees(RealmList<DBPurchaseEmployee> payedEmployees) {
        this.payedEmployees = payedEmployees;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    public void setLastUpdatedAt(Date lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }
}



```

#### Version of Realm and tooling
Realm version(s): 3.3.0

Realm sync feature enabled: yes

Android Studio version: 2.2

Which Android version and device: nexus 5 emulator noughat

**Comment by Zhuinden** [comment]
You can't set an unmanaged RealmList as the field of a managed RealmObject.

**Comment by sanju93** [comment]
@Zhuinden 
ok. I am new to this. Any links or help on how I can correct this issue?

**Comment by Zhuinden** [comment]
You can replace `createObject` with instantiation with `new`, and use `insertOrUpdate()` on it before you commit the transaction.

**Comment by sanju93** [comment]
DBPurchase dbPurchaseModel = new DBPurchase();


mRealm.insertOrUpdate(dbPurchaseModel); 
mRealm.commitTransaction();

like this?

**Comment by sanju93** [comment]
Thanks . It worked. You are an absolute genius. May I know where I can read more about managed realm list and unmanaged realmLists ? I still dont know the difference. 
https://realm.io/docs/java/latest/api/io/realm/RealmList.html
This didnt work well for me. Any tutorials or explanations that you have come across? 
Thanks you anyways. @Zhuinden

**Comment by Zhuinden** [comment]
@sanju93 managed RealmList means that the RealmList is managed by Realm, as it belongs to a managed RealmObject.

Generally it means that you can access linked objects inside it that are stored in the database.

However, unmanaged RealmList is that you created it manually with `new RealmList<>()` so it is not managed by Realm.
