### ISSUE TITLE
UnsatisfiedLinkError - Unresolved Symbols in Blackberry OS 10.3 Simulator

### ISSUE THREAD

**Issue by kapilratnani** [realm/realm-java#4869]
I know it is not a pure android device . But, kind of an android emulation. Still it would be great if realm could run here.. Thanks.

I am attaching logs of our debug build as release build logs only the stacktrace.

#### Expected Results
Realm should load
#### Actual Results
Realm crashes with below error:
D/dalvikvm(10072240): DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
W/dalvikvm(10072240): VFY: unable to resolve static field 176 (SUPPORTED_ABIS) in Landroid/os/Build;
D/dalvikvm(10072240): VFY: replacing opcode 0x62 at 0x0008
E/dalvikvm(10072240): android_update_LD_LIBRARY_PATH not found; .so dependencies will not work!
D/dalvikvm(10072240): Trying to load lib /data/app-lib/com.myproject.myApp.debug-1/librealm-jni.so b3db378
E/dalvikvm(10072240): dlopen("/data/app-lib/com.myproject.myApp.debug-1/librealm-jni.so") failed: Unresolved symbols
E/dalvikvm(10072240): android_update_LD_LIBRARY_PATH not found; .so dependencies will not work!
D/dalvikvm(10072240): Trying to load lib /data/data/com.myproject.myApp.debug/app_lib/librealm-jni.so.3.0.0 b3db378
E/dalvikvm(10072240): dlopen("/data/data/com.myproject.myApp.debug/app_lib/librealm-jni.so.3.0.0") failed: Unresolved symbols
D/AndroidRuntime(10072240): Shutting down VM
W/dalvikvm(10072240): threadid=1: thread exiting with uncaught exception (group=ab13970)
E/AndroidRuntime(10072240): FATAL EXCEPTION: main
E/AndroidRuntime(10072240): java.lang.UnsatisfiedLinkError: Unresolved symbols
E/AndroidRuntime(10072240): 	at java.lang.Runtime.load(Runtime.java:330)
E/AndroidRuntime(10072240): 	at java.lang.System.load(System.java:521)
E/AndroidRuntime(10072240): 	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
E/AndroidRuntime(10072240): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:198)
E/AndroidRuntime(10072240): 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
E/AndroidRuntime(10072240): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
E/AndroidRuntime(10072240): 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
E/AndroidRuntime(10072240): 	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:59)
E/AndroidRuntime(10072240): 	at io.realm.Realm.init(Realm.java:188)
E/AndroidRuntime(10072240): 	at com.myproject.commons.RealmProvider.init(RealmProvider.java:16)
E/AndroidRuntime(10072240): 	at com.myproject.myApp.App.initRealm(App.java:86)
E/AndroidRuntime(10072240): 	at com.myproject.myApp.App.onCreate(App.java:73)
E/AndroidRuntime(10072240): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime(10072240): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4451)
E/AndroidRuntime(10072240): 	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
E/AndroidRuntime(10072240): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
E/AndroidRuntime(10072240): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10072240): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(10072240): 	at android.app.ActivityThread.main(ActivityThread.java:5116)
E/AndroidRuntime(10072240): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10072240): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(10072240): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
E/AndroidRuntime(10072240): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(10072240): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(6873246):   Force finishing activity com.myproject.myApp.debug/com.myproject.myApp.SplashScreen

#### Steps & Code to Reproduce
It crashes on realm init. Realm.getDefaultInstance()

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: yes

Android Studio version: ?
2.3.3
Which Android version and device: ?
Android 4.3, Blackberry Z3

**Comment by Zhuinden** [comment]
Have you tried with real blackberry device or newer Realm version?

**Comment by kapilratnani** [comment]
I don't have the device. 
I haven't tried a newer realm version yet.

**Comment by kapilratnani** [comment]
Just tried realm version 3.4.0 in the Blackberry Simulator. Still same error.

**Comment by kapilratnani** [comment]
does it work in real Blackberry device with the newer version?

**Comment by beeender** [comment]
@kapilratnani a few months ago, i tested on a real bb z10, and it worked at time. We haven't received any issue about BB recently, so I assume either there is no one using the BB anymore or realm still works fine on a BB device.

**Comment by kapilratnani** [comment]
@beeender Do you still have the device? It would be great if you can help me test my app. I am not able to find the device here.
