### ISSUE TITLE
Execution failed for task ':app:transformClassesWithRealmTransformerForDebug'.

### ISSUE THREAD

**Issue by KelvinEC** [realm/realm-java#4872]
I'm trying to compile my project. If a remove the new file, project works fine, but if a create any new file results on error described on title.

```java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithRealmTransformerForDebug'.
> cannot find br.com.papodehomem.views.dialogs.OneOptionDialog$Companion: br.com.papodehomem.Views.dialogs.OneOptionDialog$Companion found in br/com/papodehomem/views/dialogs/OneOptionDialog$Companion.class

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithRealmTransformerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: cannot find br.com.papodehomem.views.dialogs.OneOptionDialog$Companion: br.com.papodehomem.Views.dialogs.OneOptionDialog$Companion found in br/com/papodehomem/views/dialogs/OneOptionDialog$Companion.class
	at javassist.CtClassType.getClassFile2(CtClassType.java:202)
	at javassist.CtClassType.makeFieldCache(CtClassType.java:873)
	at javassist.CtClassType.getMembers(CtClassType.java:864)
	at javassist.CtClassType.getDeclaredBehaviors(CtClassType.java:1012)
	at io.realm.transformer.BytecodeModifier.useRealmAccessors(BytecodeModifier.groovy:65)
	at io.realm.transformer.BytecodeModifier$useRealmAccessors$4.call(Unknown Source)
	at io.realm.transformer.RealmTransformer$_transform_closure11.doCall(RealmTransformer.groovy:140)
	at io.realm.transformer.RealmTransformer.transform(RealmTransformer.groovy:137)
	at com.android.build.api.transform.Transform.transform(Transform.java:290)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more


BUILD FAILED

Total time: 7.709 secs
```

#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: yes/no

Android Studio version: 2.3.3

Which Android version and device: Pixel, API 26.

Other informations, i`m using Kotlin version 1.1.3

Apply plugins order:
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'realm-android'
```

**Comment by sedestrian** [comment]
Hi, did you find the solution? I'm having the same problem

**Comment by emartynov** [comment]
I got the same today. Trying to clean and build without cache doesn't help. What is the problem?
