### ISSUE TITLE
 NoClassDefFoundError: Failed resolution of: Lio/realm/annotations/RealmModule

### ISSUE THREAD

**Issue by IaroslavTernovyi** [realm/realm-java#5005]
Hello guys,

I having some problem with activating Instant Run. In my project I have a single RealmModule annotated with @realmmodule. Build goes throw fine, however during run time, I get this following error only on Android Lollipop: 

```
E/AndroidRuntime: FATAL EXCEPTION: main
     Process: build, PID: 9401
     java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/annotations/RealmModule;
           at io.realm.RealmConfiguration$Builder.checkModule(RealmConfiguration.java:672)
           at io.realm.RealmConfiguration$Builder.addModule(RealmConfiguration.java:622)
           at io.realm.RealmConfiguration$Builder.modules(RealmConfiguration.java:557)
           at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
           at android.app.ActivityThread.access$1500(ActivityThread.java:151)
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:135)
           at android.app.ActivityThread.main(ActivityThread.java:5254)
           at java.lang.reflect.Method.invoke(Native Method)
           at java.lang.reflect.Method.invoke(Method.java:372)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.annotations.RealmModule" on path: DexPathList[[zip file "/data/app/build/base.apk", zip file "/data/app/build/split_lib_dependencies_apk.apk", zip file "/data/app/build/split_lib_slice_0_apk.apk", zip file "/data/app/build/split_lib_slice_1_apk.apk", zip file "/data/app/build/split_lib_slice_2_apk.apk", zip file "/data/app/build/split_lib_slice_3_apk.apk", zip file "/data/app/build/split_lib_slice_4_apk.apk", zip file "/data/app/build/split_lib_slice_5_apk.apk", zip file "/data/app/build/split_lib_slice_6_apk.apk", zip file "/data/app/build/split_lib_slice_7_apk.apk", zip file "/data/app/build/split_lib_slice_8_apk.apk", zip file "/data/app/build/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/build/lib/arm, /vendor/lib, /system/lib]]
           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
           at io.realm.RealmConfiguration$Builder.checkModule(RealmConfiguration.java:672) 
           at io.realm.RealmConfiguration$Builder.addModule(RealmConfiguration.java:622) 
           at io.realm.RealmConfiguration$Builder.modules(RealmConfiguration.java:557) 
           at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
           at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
           at android.os.Handler.dispatchMessage(Handler.java:102) 
           at android.os.Looper.loop(Looper.java:135) 
           at android.app.ActivityThread.main(ActivityThread.java:5254) 
           at java.lang.reflect.Method.invoke(Native Method) 
           at java.lang.reflect.Method.invoke(Method.java:372) 
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
           Suppressed: java.lang.ClassNotFoundException: io.realm.annotations.RealmModule
           at java.lang.Class.classForName(Native Method)
           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 19 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by Zhuinden** [comment]
What happens if you disable instant run? What happens if you clean+rebuild after enabling instant run?

**Comment by IaroslavTernovyi** [comment]
@Zhuinden 
With instant run disabled it's work fine. Nothing it's crashes with the same error

**Comment by bmeike** [comment]
@IaroslavTernovyi 
InstantRun is doing deep magic with class loaders.  It is not clear to me, immediately, what's going wrong.  I've opened #5041 to track the issue.
