### ISSUE TITLE
Exception and crash while inserting and deleting using Realm

### ISSUE THREAD

**Issue by preyesm** [realm/realm-java#5048]
Realm Version 3.4.0
Android Studio 2.2
Goal: to update the object in cache
Actual result: crash below
Expected result: to update successfully and call the addChangeListener

Code:
```Java
 static void updateClientInfo(final ClientCache clientCache) {
        if (client != null) {
           getRealm().executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.insertOrUpdate(clientCache);
                }
            });
        }
    }

private void getRealm() {
        try {
            realm = Realm.getDefaultInstance();
            System.out.println("realm created");
        } catch (RealmMigrationNeededException ex) {
            ex.printStackTrace();
            Realm.deleteRealm(RealmUtils.getRealmConfiguration());
            clearLastFetchTime();
            realm = Realm.getDefaultInstance();
           }
    }
```

BackTrace:
Fatal Exception: java.lang.IllegalStateException: Changing Realm data can only be done from inside a transaction.
       at io.realm.BaseRealm.checkIfValidAndInTransaction(SourceFile:400)
       at io.realm.Realm.insertOrUpdate(SourceFile:1252)
       at com.agendesks.android.datahandler.ClientDataHandler$8.execute(SourceFile:295)
       at io.realm.Realm.executeTransaction(SourceFile:1464)
       at com.agendesks.android.datahandler.ClientDataHandler.updateClientInfo(SourceFile:292)
       at com.agendesks.android.datahandler.ClientDataHandler.onResponse(SourceFile:173)
       at com.agendesks.android.datahandler.BaseDataHandler$1.onResponse(SourceFile:32)
       at com.agendesks.android.datahandler.BaseDataHandler$1.onResponse(SourceFile:29)
       at com.agendesks.android.datahandler.net.AbstractAgentDesksRequest.deliverResponse(SourceFile:91)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(SourceFile:99)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by nhachicha** [comment]
Hi @preyesm Are you sure the exception is thrown inside `updateClientInfo` ?  is this the corresponding line in 
```
at com.agendesks.android.datahandler.ClientDataHandler$8.execute(SourceFile:295)
```
 the `insertOrUpdate` inside `updateClientInfo` is wrapped inside a transaction already

**Comment by preyesm** [comment]
Hey @nhachicha yeah. That is where my confusion is. All my transactions are inside the exceute transaction block. but after upgrading the realm from 2.3.1 to 3.4 I have got this issue. To avoid crashes I have surrounded all my transaction with a try catch.

**Comment by nhachicha** [comment]
@preyesm  can you [share](help@realm.io) the APK to try to reproduce?

**Comment by preyesm** [comment]
@nhachicha  Sure. Should I mail to realm.io? I'll retain the code to its old state where it used to crash and also mail the steps to reproduce.

**Comment by preyesm** [comment]
@nhachicha  There is another issue.  
"final List<String> idsToDelete = new ArrayList<>();
        for (PropertyInfo propertyInfo : propertyInfoArrayList)
            idsToDelete.add(propertyInfo.getBasicId());
        ApplicationDataHandler.getRealm().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.where(PropertyCache.class).in("basicId", idsToDelete.toArray(new String[0])).findAll().deleteAllFromRealm();
            }
        });"
Error: 
 java.lang.IllegalStateException: Can't commit a non-existing write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 295
                                                                                    at io.realm.internal.SharedRealm.nativeCommitTransaction(Native Method)
                                                                                    at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:262)
                                                                                    at io.realm.BaseRealm.commitTransaction(BaseRealm.java:359)
                                                                                    at io.realm.Realm.commitTransaction(Realm.java:132)
                                                                                    at io.realm.Realm.executeTransaction(Realm.java:1404)
                                                                                    at com.agendesks.android.datahandler.db.utils.PropertyCacheUtils.deletePropertiesFromDb(PropertyCacheUtils.java:103)
                                                                                    at com.agendesks.android.datahandler.PropertyDataHandler.onResponse(PropertyDataHandler.java:298)
                                                                                    at com.agendesks.android.datahandler.BaseDataHandler$1.onResponse(BaseDataHandler.java:32)
                                                                                    at com.agendesks.android.datahandler.BaseDataHandler$1.onResponse(BaseDataHandler.java:29)
                                                                                    at com.agendesks.android.datahandler.net.AbstractAgentDesksRequest.deliverResponse(AbstractAgentDesksRequest.java:93)
                                                                                    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)

These errors are happening only in 3.4+ version, should I revert it back to 2.4 till these errors are fixed?

**Comment by nhachicha** [comment]
Hi @preyesm please send to help@realm.io

**Comment by preyesm** [comment]
@nhachicha I have mailed a copy to your id. I shall fwd that to help also. Thanks

**Comment by nhachicha** [comment]
I couldn't reproduce the crash following your steps. I've sent you an email with the video
However, you do seem to have a `java.lang.ArithmeticException: divide by zero` exception when clicking on the messages.
​
For the error two, this happens when you try to commit a transaction without being in an active one (Example, this happens when you accidentally cancel the current write transaction after an exception is being thrown).
​
Cheers

**Comment by nhachicha** [comment]
as discussed in Helpscout here's an example https://github.com/realm/realm-java/blob/32bb8d71b5096e192cbc1b037811997a5840a26b/realm/realm-library/src/androidTest/java/io/realm/RealmAsyncQueryTests.java#L223-L248 of what could trigger the `Can't commit a non-existing write transaction` exception. 

If you can isolate and reproduce the first exception we'll have a look again.

**Comment by preyesm** [comment]
@nhachicha Sure, thanks. I'll try and let you know

**Comment by nhachicha** [comment]
if you cancel the transaction within an `executeTransaction` block then this will obviously throw. 

You should not check if you're inside a transaction then cancel it, as this will cause the automatic `commit` done by the `executeTransaction` to throw.

It would help if you can post a code/pseudo code of the steps

**Comment by preyesm** [comment]
@nhachicha This is my code:
 try {
            if (ApplicationDataHandler.getRealm().isInTransaction())
                ApplicationDataHandler.getRealm().cancelTransaction();
            ApplicationDataHandler.getRealm().executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    if (realm.where(ThreadCache.class).count() != threads.size()) {
                        realm.where(ThreadCache.class).findAll().deleteAllFromRealm();
                    }
                    realm.insertOrUpdate(threads);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by Zhuinden** [comment]
If you end up in a transaction while you are already in a transaction, then you should debug your application flow as that sounds rather unpredictable.

**Comment by preyesm** [comment]
- We have chat support in our application and when a user is viewing a chat there could be multiple entities as the user scrolls through the recyler view. 
- In that case we update all the respective entities in our local cache. For which we call execute transaction for every type of entity(individual execute transaction block with same realm instance). 
- I was under the assumption that every execute transaction is a separate thread, thereby invocation  of different individual transaction block should not cause this crash. 
Please correct me if I am wrong with my assumptions.

Note: For the same code base and app flow, we never got this crash in the 2.3 version.

**Comment by Zhuinden** [comment]
`executeTransaction()` runs synchronously on the thread where you call the method.

Although I do admit, there were more "not in a write transaction" and "already in a write transaction" issues than what makes sense.

**Comment by preyesm** [comment]
But as you could see in the code sample above that I have shared, if the executeTransaction were running synchronously, then why is this issue *Changing Realm data can only be done from inside a transaction* cropping up?

**Comment by preyesm** [comment]
@nhachicha even after fixing the exception that you had pointed out, I am getting the error 2 - in this code block
 public static void deletePropertiesFromDb(final List<PropertyInfo> propertyInfoArrayList) {
        final List<String> idsToDelete = new ArrayList<>();
        for (PropertyInfo propertyInfo : propertyInfoArrayList)
            idsToDelete.add(propertyInfo.getBasicId());
        ApplicationDataHandler.getRealm().executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.where(PropertyCache.class).in("basicId", idsToDelete.toArray(new String[0])).findAll().deleteAllFromRealm();
            }
        });
    }
*Can't commit a non-existing write transaction in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 281*

**Comment by nhachicha** [comment]
There's nothing wrong with the `deletePropertiesFromDb` method AFAICT, the exception could be thrown because of another code path in the app (in which context you call `deletePropertiesFromDb`) 

As I explained earlier, the exception reflects an illegal state where somehow you end up trying to `commit` a not previously open transaction. It would be helpful to identify the path leading to this state.

**Comment by preyesm** [comment]
@nhachicha Ok, I ll check the app flow once again and revert back If i find the issue. Thanks

**Comment by preyesm** [comment]
@nhachicha you can close this issue. Based on your suggestions, I have added more checks that could cause exceptions due to which the can't commit to non-write transaction can occur. Once the release is out, if I face any other issue I'll request a re-open of the issue. 

Thanks

**Comment by nhachicha** [comment]
👍
