### ISSUE TITLE
RealmMigrationNeededException Realm on disk need to migrate from v1 to v3

### ISSUE THREAD

**Issue by FatimaSiddique** [realm/realm-java#5062]
Hi,

**Bugs**
I am getting following exception while user is upgrading from 1 to 3 db schema

#### Actual Results
```
`Fatal` Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{SplashActivity}: io.realm.exceptions.RealmMigrationNeededException: Realm on disk need to migrate from v1 to v3
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
   at android.app.ActivityThread.-wrap14(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6692)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
 Caused by io.realm.exceptions.RealmMigrationNeededException: Realm on disk need to migrate from v1 to v3
   at io.realm.Realm.createAndValidateFromCache(Realm.java:389)
   at io.realm.Realm.createInstance(Realm.java:364)
   at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:346)
   at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
   at io.realm.Realm.getDefaultInstance(Realm.java:273)
   at android.app.Activity.performCreate(Activity.java:6912)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
   at android.app.ActivityThread.-wrap14(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6692)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)**
```

Realm configuration is as follows:
#### Code Sample
```
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .name(AppConstants.DB_NAME)
                .schemaVersion(schemaVersion)
                .build();
        try {
            Realm.migrateRealm(realmConfiguration, new DBMigration()));
        } catch (Exception ignored) {
            // If the Realm file doesn't exist, just ignore.
        }
        Realm.setDefaultConfiguration(realmConfiguration);
```

I have specified DB migrations in code in which i have mentioned DB changes.
Its not mentioning which DB model is causing the issue so I am unable to identify the cause. Can you please help in resolving this issue

#### Version of Realm and tooling
Realm version(s): 3.3.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Samsung S7

**Comment by Zhuinden** [comment]
Why not specify the migration on the configuration builder?

**Comment by FatimaSiddique** [comment]
Is there any difference in both ways?

**Comment by nhachicha** [comment]
@FatimaSiddique it's just a good pattern to have the migration block alongside the configuration. Otherwise, you need to know which part of your code is going to open the Realm first then make sure to manually trigger the migration. That might be your case here, some part of your app may be trying to open the Realm before you get to this code path where you migrate manually.

Can you add the migration block as part of the conf, and see if you can reproduce?

**Comment by cmelchior** [comment]
Closing this due to inactivity. @FatimaSiddique feel free to reopen if you have further information.
