### ISSUE TITLE
Realm doesn't recognize fields of JsonObject

### ISSUE THREAD

**Issue by ErfanThinker** [realm/realm-java#5107]
#### Goal

> I am trying to use `createObjectFromRealm()` but when I give the jsonObject, Realm can't detect the fields. I am using Realm 3.5 and my app partially uses Kotlin but the classes in which I have used Realm, are using Java.

#### Expected Results

> Successful creation of nested RealmObjects like `Content` and `ContentDetail`.

#### Actual Results

>  08-15 14:40:57.350 6944-6944/ir.parsatech.isiranvrrecorder E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: ir.parsatech.isiranvrrecorder, PID: 6944
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.parsatech.isiranvrrecorder/ir.parsatech.isiranvrrecorder.activities.MainActivity}: java.lang.IllegalArgumentException: JSON object doesn't have the primary key field 'uuid'.
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
                                                                              Caused by: java.lang.IllegalArgumentException: JSON object doesn't have the primary key field 'uuid'.
                                                                                 at io.realm.ContentRealmProxy.createOrUpdateUsingJsonObject(ContentRealmProxy.java:324)
                                                                                 at io.realm.DefaultRealmModuleMediator.createOrUpdateUsingJsonObject(DefaultRealmModuleMediator.java:286)
                                                                                 at io.realm.Realm.createObjectFromJson(Realm.java:716)
                                                                                 at ir.parsatech.isiranvrrecorder.utils.TestClass.testRealm(TestClass.java:24)
                                                                                 at ir.parsatech.isiranvrrecorder.activities.MainActivity.test(MainActivity.kt:174)
                                                                                 at ir.parsatech.isiranvrrecorder.activities.MainActivity.onCreate(MainActivity.kt:74)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 

#### Steps & Code to Reproduce

> I have tried the code below and figured out there's problem with realm finding the fields of JSONObject.

#### Code Sample

```
public class TestClass {

    public static void testRealm() {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        realm.createObjectFromJson(Content.class, testXmlToJson());
        realm.commitTransaction();
        realm.close();
    }

    static JSONObject testXmlToJson()  {
        JSONObject jsonObj = new JSONObject();
        JSONArray contentDetails = new JSONArray();
        JSONObject contentDetailz = new JSONObject();
        JSONObject contentDetail1 = new JSONObject();
        JSONObject contentDetail2 = new JSONObject();
        try {
            contentDetail1.put("FileName", "test.mp3");
            contentDetail1.put("ContentTypeID", 3);
            contentDetail2.put("FileName", "2.jpg");
            contentDetail2.put("ContentTypeID", 2);
            contentDetails.put(contentDetail1);
            contentDetails.put(contentDetail2);
            contentDetailz.put("ContentDetail", contentDetails);
            contentDetailz.put("alaki", "Alaki");
            contentDetailz.put("uuid", UUID.randomUUID());
            jsonObj.put("Content", contentDetailz);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return jsonObj;
    }
}

public class Content extends RealmObject {
    @PrimaryKey private String uuid;
    private String alaki;
    private RealmList<ContentDetailModel> ContentDetail;

    public String getUuid() {
        return uuid;
    }

    public RealmList<ContentDetailModel> getContentDetails() {
        return ContentDetail;
    }

    public void setContentDetails(RealmList<ContentDetailModel> contentDetails) {
        this.ContentDetail = contentDetails;
    }
}

public class ContentDetailModel extends RealmObject {
    private String FileName;
    /**
     * ContentTypeID contract is as follows:
     * "1" Video
     * "2" Picture
     * "3" Voice
     * "4" Text
     */
    Integer ContentTypeID;
    RealmList<ContentDetailMetadataModel> ContentDetailMetadata;
//    @LinkingObjects("ContentDetail") private final RealmResults<Content> content = null;

//    public RealmResults<Content> getContent() {
//        return content;
//    }

    public String getFileName() {
        return FileName;
    }

    public void setFileName(String fileName) {
        FileName = fileName;
    }

    public Integer getContentTypeID() {
        return ContentTypeID;
    }

    public void setContentTypeID(Integer contentTypeID) {
        ContentTypeID = contentTypeID;
    }

    public RealmList<ContentDetailMetadataModel> getContentDetailMetadata() {
        return ContentDetailMetadata;
    }

    public void setContentDetailMetadata(RealmList<ContentDetailMetadataModel> contentDetailMetadataz) {
        this.ContentDetailMetadata = contentDetailMetadataz;
    }
}

```

#### Version of Realm and tooling
Realm version(s): 3.5

Realm sync feature enabled: yes

Android Studio version: 3.0.0 Beta 1

Which Android version and device: Nexus 5

**Comment by Zhuinden** [comment]
``` java

public class Content extends RealmObject {
    private RealmList<ContentDetail> ContentDetail;

    @LinkingObjects("Content") 
    private final RealmResults<Root> roots = null;
}

public class ContentDetail extends RealmObject {
    private String FileName;
    private long ContentTypeID;
    private ContentDetailMetadata ContentDetailMetadata;

    @LinkingObjects("ContentDetail") 
    private final RealmResults<Content> contents = null;
}

public class ContentDetailMetadata extends RealmObject {
    private RealmList<Metadata> Metadata;

    @LinkingObjects("ContentDetailMetadata") 
    private final RealmResults<ContentDetail> contentDetails = null;
}

public class Metadata extends RealmObject {
    private long ID;
    private String Value;

    @LinkingObjects("Metadata") 
    private final RealmResults<ContentDetailMetadata> contentDetailMetadatas = null;
}
```

**Comment by cmelchior** [comment]
```
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        Content object = realm.createObjectFromJson(Content.class, testXmlToJson().getJSONObject("Content"));
        realm.commitTransaction();
        realm.close();
```

Works for me. Remeber that the top-level JSON object _is_ the type you define in the class parameter to `createObjectFromJson`

**Comment by ErfanThinker** [comment]
@Zhuinden @cmelchior yes both of you were right, it got fixed as soon as I changed it as @cmelchior  said, the solution of @Zhuinden  should be right too but idk why I get `could not map Json` when I try it. Thanks anyway :3
