### ISSUE TITLE
The Realm is already in a write transaction

### ISSUE THREAD

**Issue by bitsydarel** [realm/realm-java#5140]
Hi, I'm getting a illegalException (The Realm is already in a write transaction). the strange things is that I don't have pending write transaction. all my transactions are step by step and i am closing realm after each step.

User Login (Remote Api) -> Get User  (Local) -> Create a List  (Local) -> Check if list already in realm  -> List not in realm -> try to add -> Crash

When I check the RealmCache in the debugger (refAndCountMap) to see how many instances of the realm are used in the current thread, it's say two which is strange, it's like when I close the DB the count don't decrease.

###### Here is the code to get the user in realm 

    override fun getUser(requestModel: UserRequestModel<Unit>): Flowable<User> {
        return Flowable.create({ emitter -> Realm.getDefaultInstance().use {
            realm -> realm.executeTransaction {

            db -> val user : LocalUser? = db.where(LocalUser::class.java)
                .equalTo(ConstantHolder.UUID, requestModel.userId)
                .findFirst()

            if (user != null) emitter.onNext(user.toDomainUser())
            else emitter.onComplete()

        } } }, BackpressureStrategy.LATEST)
    }

// i'm closing realm after the transaction
#############################################################################
here is the code to add List 

    override fun addList(requestModel: ListRequestModel<ShoppingList>): Completable {
        return requestModel.arg.isInDatabase()  // This doesnt Crash
                .flatMapCompletable { wasFound ->
                    if (wasFound) throw Exception("You already have this list! (Change Me Darel!!!)")
                    else Completable.create { emitter -> Realm.getDefaultInstance().use {
                        realm -> realm.executeTransaction {

                        db -> db.insertOrUpdate(requestModel.arg.toProxyList())

                        emitter.onComplete()

                    } } }
                }
    }

########################################################################

```
E/REALM_JNI: Exception has been thrown: The Realm is already in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 277

The Realm is already in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 277
                                                                    java.lang.IllegalStateException: The Realm is already in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 277
                                                                        at io.realm.internal.SharedRealm.nativeBeginTransaction(Native Method)
                                                                        at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:257)
                                                                        at io.realm.BaseRealm.beginTransaction(BaseRealm.java:348)
                                                                        at io.realm.BaseRealm.beginTransaction(BaseRealm.java:343)
                                                                        at io.realm.Realm.beginTransaction(Realm.java:132)
                                                                        at io.realm.Realm.executeTransaction(Realm.java:1401)
                                                                        at com.dbeginc.data.implementations.datasources.local.LocalDataSourceImpl$addList$1$1.subscribe(LocalDataSourceImpl.kt:91)
                                                                        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
                                                                        at io.reactivex.Completable.subscribe(Completable.java:1635)
                                                                        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
                                                                        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
                                                                        at com.dbeginc.data.implementations.datasources.local.LocalDataSourceImpl$isInDatabase$1$$special$$inlined$use$lambda$1.execute(LocalDataSourceImpl.kt:217)
                                                                        at io.realm.Realm.executeTransaction(Realm.java:1403)
                                                                        at com.dbeginc.data.implementations.datasources.local.LocalDataSourceImpl$isInDatabase$1.subscribe(LocalDataSourceImpl.kt:211)
                                                                        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
                                                                        at io.reactivex.Single.subscribe(Single.java:2700)
                                                                        at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
                                                                        at io.reactivex.Completable.subscribe(Completable.java:1635)
                                                                        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
                                                                        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
                                                                        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

**Comment by bitsydarel** [comment]
I'm using io.realm:realm-gradle-plugin:3.5.0

**Comment by beeender** [comment]
`executeTransaction()` will refresh the local Realm to the latest version which will trigger relevant listeners if necessary. You can see 

```
at io.realm.Realm.executeTransaction(Realm.java:1401)
                                                                        at com.dbeginc.data.implementations.datasources.local.LocalDataSourceImpl$addList$1$1.subscribe(LocalDataSourceImpl.kt:91)
                                                                        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
                                                                        at io.reactivex.Completable.subscribe(Completable.java:1635)
                                                                        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
                                                                        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
                                                                        at com.dbeginc.data.implementations.datasources.local.LocalDataSourceImpl$isInDatabase$1$$special$$inlined$use$lambda$1.execute(LocalDataSourceImpl.kt:217)
                                                                        at io.realm.Realm.executeTransaction(Realm.java:1403)
```

There are two `executeTransaction()` in the backtrace. 

To solve it, you can either move the `executeTransaction()` out of the callbacks, or use `executeTransactionAsync()` instead.

**Comment by bitsydarel** [comment]
I just switched to using executeTransactionAsync, now i'm getting "callback cannot be delivered on current Thread . Realm cannot be automatically updated on a thread without a looper" 

Realm.getDefaultInstance().use {}, kotlin use function should close the realm instance after the transaction terminated. so why the count does not decrease since the transaction is done ? 

I don't use Realm Object in my main code, i only use Realm as database to store and retrieve element so i don't use the auto update feature .

**Comment by bitsydarel** [comment]
private fun ShoppingList.isInDatabase() : Single<Boolean> {

        return Single.create { emitter -> Realm.getDefaultInstance().use {
            realm -> realm.executeTransaction {

            db -> val list = db.where(LocalShoppingList::class.java)
                .equalTo(ConstantHolder.NAME, name)
                .findFirst()

            emitter.onSuccess(list != null)

        } } }
    }

here is the first transaction, when the emitter.onSuccess is call the transaction should be done, so why the RealmCache don't decrease the number of transaction in thread... is there an way to decrease the realmCache transaction value ?

**Comment by beeender** [comment]
try to trigger the `emitter` out of the transaction block to avoid recursive calls.

**Comment by bitsydarel** [comment]
private fun ShoppingList.isInDatabase() : Single<Boolean> {

        return Single.create { emitter -> var isInDB = false

            Realm.getDefaultInstance().use {
            realm -> realm.executeTransaction { db -> isInDB = db.where(LocalShoppingList::class.java)
                    .equalTo(ConstantHolder.NAME, name)
                    .findFirst() != null
            }
                emitter.onSuccess(isInDB) } 
        }
    }

@beeender moving this emitter out fix the problem, never through that completing the emitter in the transaction could prevent the transaction to complete ... 
but kind of ugly code :(, thanks for your help!
