### ISSUE TITLE
Can't cancel a non-existing write transaction

### ISSUE THREAD

**Issue by DKKovalev** [realm/realm-java#5163]
Hello, i'm having an issue. I needed to add migration to my project and after that i caught some crashes with the following stacktrace:

```
java.lang.RuntimeException: Unable to create application com.project.app.App: java.lang.IllegalStateException: Can't cancel a non-existing write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 272
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6057)
	at android.app.ActivityThread.access$1700(ActivityThread.java:218)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:7007)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.IllegalStateException: Can't cancel a non-existing write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 272
	at io.realm.internal.SharedRealm.nativeCancelTransaction(Native Method)
	at io.realm.internal.SharedRealm.cancelTransaction(SharedRealm.java:267)
	at io.realm.BaseRealm.cancelTransaction(BaseRealm.java:372)
	at io.realm.DynamicRealm.cancelTransaction(DynamicRealm.java:48)
	at io.realm.BaseRealm$4.onResult(BaseRealm.java:661)
	at io.realm.RealmCache.doInvokeWithGlobalRefCount(RealmCache.java:489)
	at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:484)
	at io.realm.BaseRealm.migrateRealm(BaseRealm.java:634)
	at io.realm.Realm.migrateRealm(Realm.java:1692)
	at io.realm.Realm.createInstance(Realm.java:355)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:345)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:283)
	at io.realm.Realm.getDefaultInstance(Realm.java:272)
	at com.project.data.db.DbHelper$Companion.init(DbHelper.kt:67)
	at com.project.app.App.onCreate(App.java:52)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6054)
```

This is my DbHelper init method:

```
fun init(context: Context) {
            Realm.init(context)
            Realm.setDefaultConfiguration(defaultConfig())

            var realm: Realm? = null
            try {
                realm = Realm.getDefaultInstance()
            } catch (exception: IllegalArgumentException) {
                Realm.deleteRealm(defaultConfig())
            } finally {
                realm?.close()
            }
}

fun defaultConfig() = RealmConfiguration.Builder()
                .schemaVersion(MyRealmMigration.REALM_VERSION)
                .migration(MyRealmMigration())
                .build()
```

And migration class:

```
public class MyRealmMigration implements RealmMigration {

    public static final long REALM_VERSION = 1;

    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        if (oldVersion == 0) {
            RealmObjectSchema routeSchedule = schema.get("RouteSchedule");
            if (routeSchedule.getFieldType("price").equals(RealmFieldType.FLOAT)) {
                routeSchedule
                        .removeField("price")
                        .addField("price", String.class);
            }

            RealmObjectSchema routeTrip = schema.get("RouteTrip");
            if (!routeTrip.hasField("platformFrom")) {
                routeTrip.addField("platformFrom", String.class)
                        .addField("platformTo", String.class);
            }

            oldVersion++;
        }
    }
}
```

#### Version of Realm and tooling
Realm version(s): 3.2.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Various devices and versions

**Comment by Zhuinden** [comment]
Migration seems to throw an exception and the migration's transaction should get cancelled, but I do not see why.

**Comment by DKKovalev** [comment]
The thing is, i cannot reproduce this crash at all and it doesn't appear every time on every phone

**Comment by dalinaum** [comment]
Hello @DKKovalev.  I think there are 2 problems here.

1. There are some situations which cannot begin a write transaction internally.
2. BaseRealm.migrateRealm cancels a write transaction even if it is not in a transaction. 

I don't know whether the former is a bug or not yet. The latter conceals why Realm cannot begin a write transaction. I will make a patch for that first.

**Comment by dalinaum** [comment]
Can you test Realm Java 3.6.0 snapshot? https://github.com/realm/realm-java#using-snapshots
Since our next major version has a new implementation, it maybe fix your problem.

**Comment by DKKovalev** [comment]
@dalinaum Yes, i'll try the snapshot version

**Comment by cmelchior** [comment]
@DKKovalev I'll assume the above solved your issue, otherwise feel free to reopen.
