### ISSUE TITLE
Realm 3.7.0: PermissionManager.AcceptOfferCallback() - Android application crash

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5203]
Realm 3.7.0, Anroid 4.3, Gradle 4.1
I get official example from Realm doc for **acceptOffer** from here: https://realm.io/docs/java/latest/#permission-offers

Here my code snippet (Android application)

```
 private void acceptPermissionOffer(final SyncUser syncUser, String offerToken) {
        Log.d(TAG, "acceptPermissionOffer: START:");
        PermissionManager permissionManager = syncUser.getPermissionManager();
        Log.d(TAG, "acceptPermissionOffer: success created permissionManager");
        permissionManager.acceptOffer(offerToken, new PermissionManager.AcceptOfferCallback() {

            @Override
            public void onSuccess(String realmUrl, Permission permission) {
                if (BuildConfig.DEBUG)
                    Log.d(TAG, "acceptPermissionOffer: AcceptOfferCallback: onSuccess: SUCCESS_ACCEPT_PERMISSION_OFFER and realmUrl: ");
                // User can now access the Realm
                SyncConfiguration config = new SyncConfiguration.Builder(syncUser, realmUrl).build();
                Realm realm = Realm.getInstance(config);
            }

            @Override
            public void onError(ObjectServerError error) {
                     Log.e(TAG, "acceptPermissionOffer: AcceptOfferCallback: ", error);
            }
        });
}
```

But after FIRST start of Android appliction I get the next error and application is crash:

Result in Logcat:

...

```
acceptPermissionOffer: START:
acceptPermissionOffer: success created permissionManager


E/REALM	  ( 3593): /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/jni_util/java_class.cpp:50: [realm-core-2.8.6] Assertion failed: cls
E/REALM	  ( 3593): IMPORTANT: if you see this error, please send this log to help@realm.io.
F/libc	  ( 3593): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 3593 (.com.myproject )
I/DEBUG	  (  123): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG	  (  123): Build fingerprint: 'google/yakju/maguro:4.3/JWR66Y/776638:user/release-keys'
I/DEBUG	  (  123): Revision: '9'
I/DEBUG	  (  123): pid: 3593, tid: 3593, name: .com.myproject 	>>> md.com.myproject  <<<
I/DEBUG	  (  123): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
I/DEBUG	  (  123):     r0 00000027  r1 415a5f18	 r2 00000008  r3 deadbaad
I/DEBUG	  (  123):     r4 00000000  r5 be908d64	 r6 be908e70  r7 5f8fdd78
I/DEBUG	  (  123):     r8 00000032  r9 5f8fdd90	 sl 2aaaaaaa  fp 58ec5450
I/DEBUG	  (  123):     ip 00000001  sp be908d60	 lr 400e9f93  pc 400e74e8  cpsr 600f0030
I/DEBUG	  (  123):     d0  2e6f692e6d6c6165  d1	 6f79206669203a54
I/DEBUG	  (  123):     d2  6874206565732075  d3	 726f727265207369
I/DEBUG	  (  123):     d4  657361656c70202c  d5	 687420646e657320
I/DEBUG	  (  123):     d6  7420676f6c207369  d7	 7240706c6568206f
I/DEBUG	  (  123):     d8  0000000000000000  d9	 0000000000000000
I/DEBUG	  (  123):     d10 0000000000000000  d11 0000000000000000
I/DEBUG	  (  123):     d12 0000000000000000  d13 0000000000000000
I/DEBUG	  (  123):     d14 0000000000000000  d15 0000000000000000
I/DEBUG	  (  123):     d16 0000000000000001  d17 0000000000000000
I/DEBUG	  (  123):     d18 0000000000000000  d19 3fe2e66660000000
I/DEBUG	  (  123):     d20 0000000000000000  d21 c031000000000000
I/DEBUG	  (  123):     d22 0000000000000000  d23 3ff0000000000000
I/DEBUG	  (  123):     d24 c031000000000000  d25 3fe2e66660000000
I/DEBUG	  (  123):     d26 0000000000000000  d27 0000000000000000
I/DEBUG	  (  123):     d28 0000000000000000  d29 3fe2e66660000000
I/DEBUG	  (  123):     d30 3fe2e66660000000  d31 0000000000000000
I/DEBUG	  (  123):     scr 20000017
I/DEBUG	  (  123): 
I/DEBUG	  (  123): backtrace:
I/DEBUG	  (  123):     #00  pc 0001e4e8	 /system/lib/libc.so
I/DEBUG	  (  123):     #01  pc 0001c510	 /system/lib/libc.so (abort+4)
I/DEBUG	  (  123):     #02  pc 0028b42b	 /data/app-lib/md.com.myproject -1/librealm-jni.so
I/DEBUG	  (  123):     #03  pc 0028b457	 /data/app-lib/md.com.myproject -1/librealm-jni.so
I/DEBUG	  (  123): 
I/DEBUG	  (  123): stack:
I/DEBUG	  (  123):	    be908d20  be908d68	[stack]
I/DEBUG	  (  123):	    be908d24  000000d6	
I/DEBUG	  (  123):	    be908d28  40111170	/system/lib/libc.so
I/DEBUG	  (  123):	    be908d2c  415a5f18	
I/DEBUG	  (  123):	    be908d30  00000015	
I/DEBUG	  (  123):	    be908d34  400e8f75	/system/lib/libc.so (__sflush+56)
I/DEBUG	  (  123):	    be908d38  40111264	/system/lib/libc.so
I/DEBUG	  (  123):	    be908d3c  401111c4	/system/lib/libc.so
I/DEBUG	  (  123):	    be908d40  00000000	
I/DEBUG	  (  123):	    be908d44  400e9f93	/system/lib/libc.so (_fwalk+34)
I/DEBUG	  (  123):	    be908d48  400e923d	/system/lib/libc.so (_cleanup)
I/DEBUG	  (  123):	    be908d4c  be908d64	[stack]
I/DEBUG	  (  123):	    be908d50  be908e70	[stack]
I/DEBUG	  (  123):	    be908d54  5f8fdd78	/data/app-lib/md.com.myproject -1/librealm-jni.so
I/DEBUG	  (  123):	    be908d58  df0027ad	
I/DEBUG	  (  123):	    be908d5c  00000000	
I/DEBUG	  (  123):     #00  be908d60  00000032	
I/DEBUG	  (  123):	    be908d64  fffffbdf	
I/DEBUG	  (  123):	    be908d68  40111000	/system/lib/libc.so
I/DEBUG	  (  123):	    be908d6c  be908d9c	[stack]
I/DEBUG	  (  123):	    be908d70  be908d9c	[stack]
I/DEBUG	  (  123):	    be908d74  be908dac	[stack]
I/DEBUG	  (  123):	    be908d78  be908e70	[stack]
I/DEBUG	  (  123):	    be908d7c  be908d9c	[stack]
I/DEBUG	  (  123):	    be908d80  be908dac	[stack]
I/DEBUG	  (  123):	    be908d84  400e5514	/system/lib/libc.so (__pthread_clone)
I/DEBUG	  (  123):     #01  be908d88  00000000	
I/DEBUG	  (  123):	    be908d8c  5f88c42f	/data/app-lib/md.com.myproject -1/librealm-jni.so
I/DEBUG	  (  123):     #02  be908d90  00000000	
I/DEBUG	  (  123):	    be908d94  5f88c45b	/data/app-lib/md.com.myproject -1/librealm-jni.so
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near r1:
I/DEBUG	  (  123):     415a5ef8 00000001 0000128e 00002fa8 00001f40  
I/DEBUG	  (  123):     415a5f08 00001f40 00000001 00000001 0000100b  
I/DEBUG	  (  123):     415a5f18 6d206e49 69616d67 4e4a206e 6e4f5f49  
I/DEBUG	  (  123):     415a5f28 64616f4c 0000000a 6d202230 61537861  
I/DEBUG	  (  123):     415a5f38 656c706d 65746152 3834223d 22303030  
I/DEBUG	  (  123):     415a5f48 2020200a 20202020 6e696d20 6e616843  
I/DEBUG	  (  123):     415a5f58 736c656e 2231223d 78616d20 6e616843  
I/DEBUG	  (  123):     415a5f68 736c656e 2231223d 0a3e2f20 2020200a  
I/DEBUG	  (  123):     415a5f78 75413c20 456f6964 646f636e 61437265  
I/DEBUG	  (  123):     415a5f88 616e2070 223d656d 65636161 2022646c  
I/DEBUG	  (  123):     415a5f98 62616e65 3d64656c 75727422 200a2265  
I/DEBUG	  (  123):     415a5fa8 20202020 6d202020 69426e69 74615274  
I/DEBUG	  (  123):     415a5fb8 31223d65 30303036 616d2022 74694278  
I/DEBUG	  (  123):     415a5fc8 65746152 3931223d 30303032 20200a22  
I/DEBUG	  (  123):     415a5fd8 20202020 696d2020 6d61536e 52656c70  
I/DEBUG	  (  123):     415a5fe8 3d657461 30363122 20223030 5378616d  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near r5:
I/DEBUG	  (  123):     be908d44 400e9f93 400e923d be908d64 be908e70  
I/DEBUG	  (  123):     be908d54 5f8fdd78 df0027ad 00000000 00000032  
I/DEBUG	  (  123):     be908d64 fffffbdf 40111000 be908d9c be908d9c  
I/DEBUG	  (  123):     be908d74 be908dac be908e70 be908d9c be908dac  
I/DEBUG	  (  123):     be908d84 400e5514 00000000 5f88c42f 00000000  
I/DEBUG	  (  123):     be908d94 5f88c45b be908dac 59255eac 5f94e858  
I/DEBUG	  (  123):     be908da4 5f88c4b3 00000e80 5f94e844 00000000  
I/DEBUG	  (  123):     be908db4 5f94e858 5f958a60 58dc6014 58dc6014  
I/DEBUG	  (  123):     be908dc4 58dc6015 58dc6014 58dc60dd 58dc6214  
I/DEBUG	  (  123):     be908dd4 5f96b6c0 00000018 58dc6014 5f94e86c  
I/DEBUG	  (  123):     be908de4 00000006 00000000 00001002 00000000  
I/DEBUG	  (  123):     be908df4 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e04 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e14 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e24 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e34 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near r6:
I/DEBUG	  (  123):     be908e50 00000000 5f840120 be908db8 5f96b444  
I/DEBUG	  (  123):     be908e60 5f96b6e0 5f96be10 41771d90 5f6a9267  
I/DEBUG	  (  123):     be908e70 5f905be8 00000000 5f962994 00000001  
I/DEBUG	  (  123):     be908e80 58ec2d58 5f6a927f 00000001 58ea3378  
I/DEBUG	  (  123):     be908e90 57819ac8 5f6a6269 593a17fc 00000008  
I/DEBUG	  (  123):     be908ea0 5f7f48a1 58ea3378 58ec2d58 58ec2d58  
I/DEBUG	  (  123):     be908eb0 be908eec 58ea3378 58ec2d58 58ec2d58  
I/DEBUG	  (  123):     be908ec0 be908eec 5f6bfc81 593d4930 00000000  
I/DEBUG	  (  123):     be908ed0 00000000 00000000 be908f08 58ec5458  
I/DEBUG	  (  123):     be908ee0 00016128 5f84f1a7 01000408 58ec5458  
I/DEBUG	  (  123):     be908ef0 00000000 00000000 00000000 be908f18  
I/DEBUG	  (  123):     be908f00 00000000 be908eeb 593a4548 00000400  
I/DEBUG	  (  123):     be908f10 be909028 5966daae 5966daae 00000000  
I/DEBUG	  (  123):     be908f20 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908f30 be909000 00090000 be908fc8 58ec61e8  
I/DEBUG	  (  123):     be908f40 00016128 5f6d4691 00000004 00000000  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near r7:
I/DEBUG	  (  123):     5f8fdd58 74206f74 62206568 746c6975 69206e69  
I/DEBUG	  (  123):     5f8fdd68 656c706d 746e656d 6f697461 00002e6e  
I/DEBUG	  (  123):     5f8fdd78 65737341 6f697472 6166206e 64656c69  
I/DEBUG	  (  123):     5f8fdd88 6c63203a 00000073 6573552f 632f7372  
I/DEBUG	  (  123):     5f8fdd98 65522f6d 2f6d6c61 6c616572 616a2d6d  
I/DEBUG	  (  123):     5f8fdda8 722f6176 6d6c6165 6165722f 6c2d6d6c  
I/DEBUG	  (  123):     5f8fddb8 61726269 732f7972 6d2f6372 2f6e6961  
I/DEBUG	  (  123):     5f8fddc8 2f707063 5f696e6a 6c697475 76616a2f  
I/DEBUG	  (  123):     5f8fddd8 6c635f61 2e737361 00707063 6176614a  
I/DEBUG	  (  123):     5f8fdde8 63786520 69747065 68206e6f 62207361  
I/DEBUG	  (  123):     5f8fddf8 206e6565 7563636f 64657272 6554202e  
I/DEBUG	  (  123):     5f8fde08 6e696d72 20657461 20494e4a 74207962  
I/DEBUG	  (  123):     5f8fde18 776f7268 20676e69 2b632061 7865202b  
I/DEBUG	  (  123):     5f8fde28 74706563 2e6e6f69 00000000 280a3125  
I/DEBUG	  (  123):     5f8fde38 253a3225 00002933 72656854 73692065  
I/DEBUG	  (  123):     5f8fde48 70206120 69646e65 4a20676e 20617661  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near r9:
I/DEBUG	  (  123):     5f8fdd70 6f697461 00002e6e 65737341 6f697472  
I/DEBUG	  (  123):     5f8fdd80 6166206e 64656c69 6c63203a 00000073  
I/DEBUG	  (  123):     5f8fdd90 6573552f 632f7372 65522f6d 2f6d6c61  
I/DEBUG	  (  123):     5f8fdda0 6c616572 616a2d6d 722f6176 6d6c6165  
I/DEBUG	  (  123):     5f8fddb0 6165722f 6c2d6d6c 61726269 732f7972  
I/DEBUG	  (  123):     5f8fddc0 6d2f6372 2f6e6961 2f707063 5f696e6a  
I/DEBUG	  (  123):     5f8fddd0 6c697475 76616a2f 6c635f61 2e737361  
I/DEBUG	  (  123):     5f8fdde0 00707063 6176614a 63786520 69747065  
I/DEBUG	  (  123):     5f8fddf0 68206e6f 62207361 206e6565 7563636f  
I/DEBUG	  (  123):     5f8fde00 64657272 6554202e 6e696d72 20657461  
I/DEBUG	  (  123):     5f8fde10 20494e4a 74207962 776f7268 20676e69  
I/DEBUG	  (  123):     5f8fde20 2b632061 7865202b 74706563 2e6e6f69  
I/DEBUG	  (  123):     5f8fde30 00000000 280a3125 253a3225 00002933  
I/DEBUG	  (  123):     5f8fde40 72656854 73692065 70206120 69646e65  
I/DEBUG	  (  123):     5f8fde50 4a20676e 20617661 65637865 6f697470  
I/DEBUG	  (  123):     5f8fde60 00002e6e 65737341 6f697472 6166206e  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near sl:
I/DEBUG	  (  123):     2aaaaa88 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaa98 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaaa8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaab8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaac8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaad8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaae8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaaaf8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab08 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab18 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab28 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab38 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab48 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab58 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab68 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123):     2aaaab78 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near fp:
I/DEBUG	  (  123):     58ec5430 58ec1518 593a1b90 593a4950 58ec17b8  
I/DEBUG	  (  123):     58ec5440 58ec1b60 4011402c 00000020 00000e6b  
I/DEBUG	  (  123):     58ec5450 00000000 00000000 5f956360 58ec5450  
I/DEBUG	  (  123):     58ec5460 5f955950 00090000 58ec5378 00000007  
I/DEBUG	  (  123):     58ec5470 00000000 00000000 00000001 00000000  
I/DEBUG	  (  123):     58ec5480 57d474dc 57d474d0 58ea2fb0 00000028  
I/DEBUG	  (  123):     58ec5490 58dc5000 00001000 00001000 0000000c  
I/DEBUG	  (  123):     58ec54a0 58ec2e58 00000090 00000003 00000000  
I/DEBUG	  (  123):     58ec54b0 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     58ec54c0 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     58ec54d0 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     58ec54e0 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     58ec54f0 00000000 00020000 59413000 00000008  
I/DEBUG	  (  123):     58ec5500 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     58ec5510 00000000 00000000 00000500 58dc5500  
I/DEBUG	  (  123):     58ec5520 00000008 00000e08 58dc5e08 00000008  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory near sp:
I/DEBUG	  (  123):     be908d40 00000000 400e9f93 400e923d be908d64  
I/DEBUG	  (  123):     be908d50 be908e70 5f8fdd78 df0027ad 00000000  
I/DEBUG	  (  123):     be908d60 00000032 fffffbdf 40111000 be908d9c  
I/DEBUG	  (  123):     be908d70 be908d9c be908dac be908e70 be908d9c  
I/DEBUG	  (  123):     be908d80 be908dac 400e5514 00000000 5f88c42f  
I/DEBUG	  (  123):     be908d90 00000000 5f88c45b be908dac 59255eac  
I/DEBUG	  (  123):     be908da0 5f94e858 5f88c4b3 00000e80 5f94e844  
I/DEBUG	  (  123):     be908db0 00000000 5f94e858 5f958a60 58dc6014  
I/DEBUG	  (  123):     be908dc0 58dc6014 58dc6015 58dc6014 58dc60dd  
I/DEBUG	  (  123):     be908dd0 58dc6214 5f96b6c0 00000018 58dc6014  
I/DEBUG	  (  123):     be908de0 5f94e86c 00000006 00000000 00001002  
I/DEBUG	  (  123):     be908df0 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e00 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e10 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e20 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123):     be908e30 00000000 00000000 00000000 00000000  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): code around pc:
I/DEBUG	  (  123):     400e74c8 461ce00b 2b006823 e026d1fb b12468e4  
I/DEBUG	  (  123):     400e74d8 21014a18 6011447a 4b1247a0 24002027  
I/DEBUG	  (  123):     400e74e8 f7fc7018 2106ee42 e898f7fe 5180f04f  
I/DEBUG	  (  123):     400e74f8 a9029104 94022006 9403460a ec44f7fd  
I/DEBUG	  (  123):     400e7508 46224629 f7fd2002 f7fcec50 2106ee2e  
I/DEBUG	  (  123):     400e7518 e884f7fe f7fc2001 6960eada d1dc2800  
I/DEBUG	  (  123):     400e7528 bf00e7d4 deadbaad 00029b30 ffffff9c  
I/DEBUG	  (  123):     400e7538 0002cdc0 0002cda4 2400b510 aa04b088  
I/DEBUG	  (  123):     400e7548 46699002 94014620 94039400 eb92f7fd  
I/DEBUG	  (  123):     400e7558 db0642a0 b1139b07 1c419806 98069106  
I/DEBUG	  (  123):     400e7568 4620e000 bd10b008 4b1eb40e b082b5f0  
I/DEBUG	  (  123):     400e7578 447b491d f107af00 585e021c f8522101  
I/DEBUG	  (  123):     400e7588 68354b04 f852607d 31015b04 d1fa2d00  
I/DEBUG	  (  123):     400e7598 320e008a 0507f022 0220f107 0d05ebad  
I/DEBUG	  (  123):     400e75a8 f107603a 46690224 9400466d 4c04f852  
I/DEBUG	  (  123):     400e75b8 f8453204 2c004f04 f8dfd1f8 f853c030  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): code around lr:
I/DEBUG	  (  123):     400e9f70 4a0e4b0d e92d447b 260041f0 4680589c  
I/DEBUG	  (  123):     400e9f80 686768a5 f9b5e007 2b00300c 4628dd02  
I/DEBUG	  (  123):     400e9f90 430647c0 3f013554 6824d5f5 d1ef2c00  
I/DEBUG	  (  123):     400e9fa0 e8bd4630 bf0081f0 00027060 ffffffc4  
I/DEBUG	  (  123):     400e9fb0 43f0e92d fb01461e 4b16f502 4916460f  
I/DEBUG	  (  123):     400e9fc0 447bb087 aa014614 20019001 95029203  
I/DEBUG	  (  123):     400e9fd0 90049505 681a585b b1124698 f0094630  
I/DEBUG	  (  123):     400e9fe0 4630fd26 f7ffa903 4681fe9c 0000f8d8  
I/DEBUG	  (  123):     400e9ff0 4630b110 fd28f009 0f00f1b9 9c05d005  
I/DEBUG	  (  123):     400ea000 1b284639 eb30f017 46204604 e8bdb007  
I/DEBUG	  (  123):     400ea010 bf0083f0 00027012 ffffff60 46036842  
I/DEBUG	  (  123):     400ea020 60411e51 da012900 bb9ef000 f8126802  
I/DEBUG	  (  123):     400ea030 601a0b01 00004770 4a104b0f b570447b  
I/DEBUG	  (  123):     400ea040 589b4604 461e6819 f009b109 6860fcf0  
I/DEBUG	  (  123):     400ea050 60651e45 da042d00 f0004620 4605fb85  
I/DEBUG	  (  123):     400ea060 6822e003 5b01f812 68336022 4620b113  
I/DEBUG	  (  123): 
I/DEBUG	  (  123): memory map around fault addr deadbaad:
I/DEBUG	  (  123):     be8e9000-be90a000 rw- [stack]
I/DEBUG	  (  123):     (no map for address)
I/DEBUG	  (  123):     ffff0000-ffff1000 r-x [vectors]
W/ActivityManager(  373): Exception thrown during pause
W/ActivityManager(  373): android.os.DeadObjectException
W/ActivityManager(  373):	at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  373):	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:635)
W/ActivityManager(  373):	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:990)
W/ActivityManager(  373):	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3834)
W/ActivityManager(  373):	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3766)
W/ActivityManager(  373):	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:8344)
W/ActivityManager(  373):	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:8221)
W/ActivityManager(  373):	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:8900)
W/ActivityManager(  373):	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:8455)
W/ActivityManager(  373):	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager(  373): Process md.com.myproject  (pid 3593) has died.

```

**Comment by beeender** [comment]
dup to #5195
