### ISSUE TITLE
When updating to 3.6.0 or later, RealmMigrationNeededException is thrown due to (Kotlin Non-Null) String PrimaryKey 

### ISSUE THREAD

**Issue by tumbling-dice** [realm/realm-java#5235]
#### Code Sample
In realm `3.5.0` I created a RealmObject like the following.

```kotlin
open class TabModel(
    @PrimaryKey open var tag: String = "",
    @Required open var displayName: String = "",
    ...
) : RealmObject() {
    ...
}
```

#### Actual Results
When updating to `3.6.0` or higher, the following exception occurred.

```
io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Property 'TabModel.tag' has been made required.
        at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.SharedRealm.<init>(SharedRealm.java:180)
        at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
        at io.realm.BaseRealm.<init>(BaseRealm.java:124)
        at io.realm.BaseRealm.<init>(BaseRealm.java:93)
        at io.realm.Realm.<init>(Realm.java:150)
        at io.realm.Realm.createInstance(Realm.java:417)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:348)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
        at io.realm.Realm.getDefaultInstance(Realm.java:325)
        at inujini_.zen.realm.model.AccountModel$Companion.getDefault(AccountModel.kt:134)
        at inujini_.zen.job.notify.NotifyDirectMessageJob$Companion.crawl(NotifyDirectMessageJob.kt:75)
        at inujini_.zen.job.notify.NotifyDirectMessageJob$Companion.access$crawl(NotifyDirectMessageJob.kt:54)
        at inujini_.zen.job.notify.NotifyDirectMessageJob.onStartJob(NotifyDirectMessageJob.kt:42)
        at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
        	... 6 more
```

Doing `setRequired` in `RealmMigration` causes different exceptions.

```kotlin
object MyRealmMigration : RealmMigration {
    const val schemaVersion = 7L

    override fun migrate(realm: DynamicRealm?, oldVersion: Long, newVersion: Long) {
        realm ?: return
        realm.schema.let {
            var migVersion = oldVersion
            ...
            // ver 6 -> 7
            if (migVersion == 7L) {
                // TabModel
                it.get(TabModel::class.java.simpleName)?.run {
                    setRequired(TabModel::tag.name, true)
                }
                migVersion += 1L
            }
        }
    }
}
```

```
Caused by: java.lang.IllegalStateException: Illegal combination
    at io.realm.internal.Table.nativeConvertColumnToNotNullable(Native Method)
    at io.realm.internal.Table.convertColumnToNotNullable(Table.java:248)
    at io.realm.MutableRealmObjectSchema.setRequired(MutableRealmObjectSchema.java:235)
    at inujini_.zen.realm.MyRealmMigration.migrate(MyRealmMigration.kt:218) // setRequired(TabModel::tag.name, true)
    at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:719)
    at io.realm.internal.SharedRealm.runMigrationCallback(SharedRealm.java:467)
    at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
    at io.realm.internal.SharedRealm.<init>(SharedRealm.java:180)
    at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
    at io.realm.BaseRealm.<init>(BaseRealm.java:124)
    at io.realm.BaseRealm.<init>(BaseRealm.java:93)
    at io.realm.Realm.<init>(Realm.java:150)
    at io.realm.Realm.createInstance(Realm.java:417)
    at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:348)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
    at io.realm.Realm.getDefaultInstance(Realm.java:325)
    at inujini_.zen.realm.model.AccountModel$Companion.getHasAccount(AccountModel.kt:144)
    at inujini_.zen.LoginActivity.onCreate(LoginActivity.kt:17)
    at android.app.Activity.performCreate(Activity.java:6237)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

#### Supplement
* Creating `RealmObject` with version 3.6.0 or higher does not cause an exception.
* With `@PrimaryKey` other than `String` (e.g. `Int`, `Long`) , no exception occurs.

#### Version of Realm and tooling
Realm version(s): 3.6.0 - 3.7.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: 
* Android 7.0 (Sony Xperia Z5)
* Android 6.0 (Google Nexus 5)

**Comment by Zhuinden** [comment]
Have you tried making it `String?` considering it's been a nullable field in the Realm schema previously (not marked as `@Required`)?

**Comment by tumbling-dice** [comment]
No, I have never made this property `String?`.

But I found workaround. It worked by re-creating `@PrimaryKey` with `RealmMigration`.

```kotlin
realm.schema.get(TabModel::class.java.simpleName)?.run {
    if (isPrimaryKey(TabModel::tag.name) && !isRequired(TabModel::tag.name)) {
        removePrimaryKey()
        setRequired(TabModel::tag.name, true)
        addIndex(TabModel::tag.name)
        addPrimaryKey(TabModel::tag.name)
    }
}
```

**Comment by nhachicha** [comment]
@tumbling-dice please re-open in case of further issues

**Comment by wmontwe** [comment]
@tumbling-dice big thanks, you saved my day. Had the same issues migrating away from 3.5 with RealmObject classes written in Kotlin.

**Comment by Zhuinden** [comment]
@wmontwe actually there's a flag you can set so that if you make the field not nullable because you have a backing property for it but should be able to store null, then you can use

```
kapt {
  arguments {
    arg("realm.ignoreKotlinNullability", true)
  }
}
```

**Comment by wmontwe** [comment]
@Zhuinden thanks didn't know that
