### ISSUE TITLE
java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction. But isInTransaction() -> False

### ISSUE THREAD

**Issue by andrey7mel** [realm/realm-java#5246]
#### Goal

Avoid crashes.

#### Expected Results

Crashes do not happen. Transactions completes successful without crashes.
Also I want to know what kind of code can lead to this crash.

#### Actual Results

Error. StackTrace:
```java
java.lang.IllegalStateException: java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 320
	at io.realm.internal.Collection.nativeStartListening(Native Method)
	at io.realm.internal.Collection.addListener(Collection.java:490)
	at io.realm.internal.Collection.addListener(Collection.java:497)
	at ...
```
#### Steps & Code to Reproduce

100% Reproduce.
Open any file -> share to app -> app try save event to DB -> crash

#### Code Sample

Code transaction:
```java
//(DataBase.java:767)
public void saveEventSync(Event event) {
	Realm realmOut = Realm.getDefaultInstance();
	Timber.d("saveEventSync realmOut.isInTransaction(): " + realmOut.isInTransaction() + " thread: " + Thread.currentThread().getName()); 
	//Log: saveEventSync realmOut.isInTransaction(): false thread: main
	realmOut.close();

	try (Realm realmIn = getRealm()) {
		Timber.d("saveEventSync realmIn.isInTransaction(): " + realmIn.isInTransaction() + " thread: " + Thread.currentThread().getName());
		//Log: saveEventSync realmIn.isInTransaction(): false thread: main
		realmIn.executeTransaction(realm -> {
			//Crash Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 320
			Timber.d("saveEventSync executeTransaction start");
			Chat chat = realm.where(Chat.class)
					.equalTo("peer.uniquePeerId", event.getPeer().getUniquePeerId())
					.findFirst();
			Event eventRealm = realm.copyToRealmOrUpdate(event);
			if (chat != null) {
				chat.setLastEvent(eventRealm);
			}
			Timber.d("saveEventSync executeTransaction finish");
		});
	}
}
 
```

 StackTrace:
https://gist.github.com/andrey7mel/2bb88820aad15faf819547a0201eccf6
```java
D/DataBase.saveEventSync()[769]: saveEventSync realmOut.isInTransaction(): false thread: main
D/DataBase.saveEventSync()[773]: saveEventSync realmIn.isInTransaction(): false thread: main
E/REALM_JNI: jni: ThrowingException 8, Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 320, .
E/REALM_JNI: Exception has been thrown: Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 320
D/DataBase.l()[775]: saveEventSync executeTransaction start
D/DataBase.l()[783]: saveEventSync executeTransaction finish
E/ChatPresenter$$Lambda.call()[0]: java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 320
E/ChatPresenter$$Lambda.call()[0]:     at io.realm.internal.Collection.nativeStartListening(Native Method)
E/ChatPresenter$$Lambda.call()[0]:     at io.realm.internal.Collection.addListener(Collection.java:490)
E/ChatPresenter$$Lambda.call()[0]:     at io.realm.internal.Collection.addListener(Collection.java:497)
E/ChatPresenter$$Lambda.call()[0]:     at ...
```
 

#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Android 5 - 6 - 7, all devices

**Comment by beeender** [comment]
it is expected

1. `addChangeListener()` cannot be called if the Realm is in transaction.
2. the `beginTransaction()` will trigger all the listeners on the same thread to avoid inconsistent data.
3. `RealmObject.asObservable` is based on the `addChangeListener`


the easiest way to to solve this:
- just change the `executeTransaction` to `executeTransactionAsync`

**Comment by andrey7mel** [comment]
But I dont use RealmObject.asObservable() or addChangeListener(), check my code please

**Comment by beeender** [comment]
```
09-11 12:45:41.961 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at rx.internal.operators.OperatorSwitch$SwitchSubscriber.onNext(OperatorSwitch.java:155)
09-11 12:45:41.961 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at rx.internal.operators.OperatorSwitch$SwitchSubscriber.onNext(OperatorSwitch.java:77)
09-11 12:45:41.961 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
09-11 12:45:41.961 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at rx.internal.operators.OperatorCast$CastSubscriber.onNext(OperatorCast.java:69)
09-11 12:45:41.961 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
09-11 12:45:41.961 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]: at io.realm.rx.RealmObservableFactory$10$1.onChange(RealmObservableFactory.java:293)
```

Before the `beginTransaction()` , have you ever called `RealmObject.asObservable()`?

**Comment by Zhuinden** [comment]
ehhh only now do I see the complete stack trace

```
09-11 12:45:41.968 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.internal.OsObject.notifyChangeListeners(OsObject.java:244)
09-11 12:45:41.969 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.internal.SharedRealm.nativeBeginTransaction(Native Method)
09-11 12:45:41.969 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:257)
09-11 12:45:41.969 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.BaseRealm.beginTransaction(BaseRealm.java:348)
09-11 12:45:41.969 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.BaseRealm.beginTransaction(BaseRealm.java:343)
09-11 12:45:41.969 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.Realm.beginTransaction(Realm.java:132)
09-11 12:45:41.970 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at io.realm.Realm.executeTransaction(Realm.java:1401)
09-11 12:45:41.971 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.model.database.DataBase.saveEventSync(DataBase.java:774)
09-11 12:45:41.971 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.presenter.FileUploadManager.uploadFileAsync(FileUploadManager.kt:47)
09-11 12:45:41.971 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.presenter.chat.ChatPresenter.uploadFile(ChatPresenter.java:484)
09-11 12:45:41.972 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.presenter.chat.ChatPresenter.handleSendIntent(ChatPresenter.java:673)
09-11 12:45:41.972 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.view.chat.ChatFragment.handleSendIntent(ChatFragment.java:501)
09-11 12:45:41.972 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.view.chat.ChatFragment.handleBundle(ChatFragment.java:467)
09-11 12:45:41.976 9809-9809/ru.techops.brief.debug E/ChatPresenter$$Lambda.call()[0]:     at ru.techops.brief.view.chat.ChatFragment.onViewCreated(ChatFragment.java:434)
```

It says here that calling `uploadFileAsync()` is triggered **synchronously** in `ChatFragment.onViewCreated()` which tries to do **synchronous** UI thread transaction (so much for that "async"!), which triggers change listeners which seem to cause a `switchMap()` to unsubscribe and resubscribe, but resubscription fails because it's in a transaction.

**Comment by beeender** [comment]
When the listeners get triggered, the transaction hasn't been started actually.
So maybe we should support this case.

**Comment by Vaishnavi-optisol** [comment]
@Zhuinden 

I'm facing issue like realm is already in write transaction. 

I'm deleting all the database files and re-creating again. After this operation I'm trying to insert records in the table. By this time I'm getting exception like above. Please let me know your thoughts on this. 

I understand it's because realm is loading all the datas takes some time on the mean while if I do insertion process I'm getting this issue.

Async request also not working

**Comment by Zhuinden** [comment]
After a long time I've managed to figure out that this tends to happen if someone is adding a change listener to a RealmResults, inside a RealmChangeListener.

I've NEVER had an actual usecase where this is something I needed.

I'd need to see your stack trace to know more info where to look.

**Comment by Vaishnavi-optisol** [comment]
Yes I tried with handler already by delaying then it's working fine. I'm just thought if there is any right way for doing this.

**Comment by Zhuinden** [comment]
I just never add a change listener inside a change listener. :smile:

**Comment by Vaishnavi-optisol** [comment]
override fun deleteDatabase() {
        realm = Realm.getDefaultInstance()
        try {
            realm.beginTransaction()
            realm.deleteAll()
            realm.cancelTransaction()

            createDatabase()
        } catch (e: Exception) {
            Log.e(Constant.LOGGER_TAG, "Received an exception", e)
        } finally {
            realm.close()
        }
    }

private fun createDatabase() {
        realm = Realm.getDefaultInstance()
        try {
            realm.beginTransaction()
            initialDataDump.execute(realm)
            realm.cancelTransaction()         
        } catch (e: Exception) {
            Log.e(Constant.LOGGER_TAG, "Received an exception", e)
        } finally {
            realm.close()
        }
    }

open class InitialDataDump: Realm.Transaction{
    @Inject
    lateinit var gson: Gson
    @Inject
    lateinit var commonMethods: CommonMethods
    @Inject
    lateinit var databaseHelper: DatabaseBoy
    @Inject
    lateinit var databaseHelperGirl: DatabaseGirl

    override fun execute(realm: Realm) {
            //Store NotificationMenu Master Record
            realm.copyToRealm(commonMethods.constructNotificationMenuData())

            //Store LessonBoy Category Master Record
            realm.copyToRealmOrUpdate(commonMethods.constructLessonCategoryData())


            //Store Diaper Table Master Record
            realm.copyToRealm(commonMethods.constructDiaperData())

            //Store Lessons BOY Master Record
            realm.createAllFromJson(LessonBoy::class.java, databaseHelper.lessonsBoy)

            //Store Lesson Girl Master Record
            realm.createAllFromJson(LessonGirl::class.java, databaseHelperGirl.lessonsGirl)
    }

    init {
        AppController.appComponent.inject(this)
    }
}

After doing all this I'm executing this statemnt which throws me the error
override fun save(user: User) {
        realm = Realm.getDefaultInstance()
        try {
            realm.beginTransaction()
            realm.copyToRealm(user)
            realm.cancelTransaction()
        } catch (e: Exception) {
            Log.e(Constant.LOGGER_TAG, "Received an exception", e)
        } finally {
            realm.close()
        }
    }
