### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid query:  is of invalid type 'LIST'.

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5255]
POJOs

```
public class Company extends RealmObject {
    @PrimaryKey
    private long id;
    private LocalizedString name;
}

public class LocalizedString extends RealmObject {
     private RealmList<TranslatedString> translatedStringList = new RealmList<>();
}

public class TranslatedString extends RealmObject {
    private String locale;
    private String value;
}

```
Try to sort by **TranslatedString.value**

`realm.where(Company.class).findAllSorted("name.translatedStringList.value");`

But get error:

```
FATAL EXCEPTION: main
java.lang.IllegalArgumentException: 
Invalid query: field 'translatedStringList' in class 'LocalizedString' is of invalid type 'LIST'.
	at io.realm.internal.fields.FieldDescriptor.verifyColumnType(FieldDescriptor.java:277)
	at io.realm.internal.fields.FieldDescriptor.verifyInternalColumnType(FieldDescriptor.java:230)
	at io.realm.internal.fields.CachedFieldDescriptor.compileFieldDescription(CachedFieldDescriptor.java:83)
	at io.realm.internal.fields.FieldDescriptor.compileIfNecessary(FieldDescriptor.java:285)
	at io.realm.internal.fields.FieldDescriptor.getFinalColumnType(FieldDescriptor.java:213)
	at io.realm.internal.SortDescriptor.checkFieldType(SortDescriptor.java:110)
	at io.realm.internal.SortDescriptor.getInstance(SortDescriptor.java:95)
	at io.realm.internal.SortDescriptor.getInstanceForSort(SortDescriptor.java:65)
	at io.realm.internal.SortDescriptor.getInstanceForSort(SortDescriptor.java:54)
	at io.realm.RealmQuery.findAllSorted(RealmQuery.java:1797)
	at io.realm.RealmQuery.findAllSorted(RealmQuery.java:1832)
	at com.myproject.service.CompanyService.getCompanys(CompanyService.java:33)
	at com.myproject.app.MainApp$3.onSuccess(MainApp.java:304)
	at com.myproject.app.MainApp$3.onSuccess(MainApp.java:290)
	at io.realm.RealmCache$CreateRealmRunnable$1.run(RealmCache.java:142)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
   Force finishing activity com.myproject.dev/com.myproject.activity.RegistrationActivity
creenshot max retries 4 of Token{426e9cb8 ActivityRecord{425bc360 u0 com.myproject.dev/com.myproject.activity.RegistrationActivity}} appWin=Window{42291fc0 u0 Starting com.myproject.dev} drawState=4

```

**Comment by Zhuinden** [comment]
@cmelchior are you supposed to be able to sort across 2 links?

**Comment by cmelchior** [comment]
@lmdic This is working as intended. You are not able to sort a parent object based on a child list as it really doesn't make any sense, because which element in the list would you sort on?

**Comment by Zhuinden** [comment]
That's a no :smile:

**Comment by cmelchior** [comment]
@Zhuinden I believe you should be able to sort across two links, but only single object references, not through lists.
