### ISSUE TITLE
Not able to inspect Realm db using chrome browser

### ISSUE THREAD

**Issue by SemiSwan** [realm/realm-java#5260]
Hi ,

I am using Realm gradle plugin 3.7.2 and stetho realm 2.1.0 , but when I connect to chrome it crashed app and I am not able to inspect db.  I am getting below exception
09-14 17:32:57.139 8206-11244/com.sakal.sarkarnama E/AndroidRuntime: FATAL EXCEPTION: StethoWorker-main-123
                                                                     Process: com.sakal.sarkarnama, PID: 8206
                                                                     java.lang.NoClassDefFoundError: io/realm/internal/LinkView
                                                                         at java.lang.Class.getDeclaredMethods(Native Method)
                                                                         at java.lang.Class.getDeclaredMethods(Class.java:656)
                                                                         at com.facebook.stetho.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:115)
                                                                         at com.facebook.stetho.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53)
                                                                         at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60)
                                                                         at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                                         at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                                         at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                                         at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                                         at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                                         at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                                                                         at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                                         at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                                                                         at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                                                                         at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                                                                         at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                                                                         at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                                                                         at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                                                                         at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                                                                         at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                                         at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.LinkView" on path: DexPathList[[zip file "/data/app/com.sakal.sarkarnama-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.sakal.sarkarnama-2, /vendor/lib, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                         at java.lang.Class.getDeclaredMethods(Native Method) 
                                                                         at java.lang.Class.getDeclaredMethods(Class.java:656) 
                                                                         at com.facebook.stetho.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:115) 
                                                                         at com.facebook.stetho.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53) 
                                                                         at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60) 
                                                                         at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129) 
                                                                         at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111) 
                                                                         at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87) 
                                                                         at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176) 
                                                                         at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136) 
                                                                         at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44) 
                                                                         at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45) 
                                                                         at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117) 
                                                                         at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83) 
                                                                         at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84) 
                                                                         at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61) 
                                                                         at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52) 
                                                                         at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63) 
                                                                         at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33) 
                                                                         at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36) 
                                                                         at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)

**Comment by Zhuinden** [comment]
I'd assume it's because `stetho-realm 2.1.0` is not compatible with Realm 3.7.1+ because it relies on `io.realm.internal.LinkView` which was replaced by `io.realm.internal.OsList`.

https://github.com/uPhyca/stetho-realm/blob/06ca641848c6fa57d23e78181335bf9f17958ee9/stetho_realm/src/main/java/com/uphyca/stetho_realm/Database.java#L32

**Comment by zaki50** [comment]
@Zhuinden Ah, yes! I need to update `stetho-realm` to support 3.7.1 or later.
I'll work on it after the current task (perhaps in this month).

**Comment by cmelchior** [comment]
Closing this issue as it should be tracked here https://github.com/uPhyca/stetho-realm/issues/62 instead
