### ISSUE TITLE
Crash -> is not part of the schema for this Realm 

### ISSUE THREAD

**Issue by defaultbr** [realm/realm-java#5261]
#### Goal

Update app dependencies and use latest android studio (3.x)

#### Expected Results

Running app thru newest android studio and gradle

#### Actual Results

Works with old android studio + old gradle files

#### Steps & Code to Reproduce

1) Use gradle3.0.0-beta5
2) realm 3.7.2
3) Android Studio 3.0 Beta 5
4) Do any query

```
realm.where(Categoria.class).equalTo("ativo", true).findAll().sort("ordem", Sort.ASCENDING);
```

Works with
```
        classpath 'com.android.tools.build:gradle:2.2.3'

```

```
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
```

Crash with:

```
  classpath 'com.android.tools.build:gradle:3.0.0-beta5'
```
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

crash:

```
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.Atividades.MainActivity}: java.lang.IllegalArgumentException: Categoria is not part of the schema for this Realm
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
    Caused by: java.lang.IllegalArgumentException: Categoria is not part of the schema for this Realm
       at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:169)
       at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:87)
       at io.realm.RealmSchema.getTable(RealmSchema.java:177)
       at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:199)
       at io.realm.RealmQuery.<init>(RealmQuery.java:126)
       at io.realm.RealmQuery.createQuery(RealmQuery.java:78)
       at io.realm.Realm.where(Realm.java:1287)
       at com.myapp.Database.Operations.RepositoryCategoria.getAllActiveCategories(RepositoryCategoria.java:18)
       at com.myapp.Atividades.MainActivity.buildNavDrawer(MainActivity.java:932)
       at com.myapp.Atividades.MainActivity.onCreate(MainActivity.java:286)
       at android.app.Activity.performCreate(Activity.java:6672)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:6123) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 

```

#### Version of Realm and tooling
Realm version(s): ?
       3.7.2

Realm sync feature enabled: yes/no
no

Android Studio version: ?
3.0 Beta 5

Which Android version and device: ?

Android 7.0 
MOTO G4 Plus

**Comment by nhachicha** [comment]
@defaultbr did you update your model? did you try from a clean build? 
try also to invalidate the Android Studio cache (File/Invalidates Caches)

**Comment by Zhuinden** [comment]
What other gradle plugins do you apply?

**Comment by defaultbr** [comment]
@nhachicha update to what? i mean, i think i already have the latest updated model for realm configs:

```
public class Categoria extends RealmObject {
    private String id;
    private int codigo;
...
}
```

must change anything? since its working in older android studio version


@Zhuinden 

```
apply plugin: 'com.android.application'
apply plugin: 'android-apt'
apply plugin: 'realm-android'
```

**Comment by Zhuinden** [comment]
You need to remove android-apt and change all `apt` to `annotationProcessor`

**Comment by defaultbr** [comment]
@Zhuinden  thanks removing android-apt did the trick
