### ISSUE TITLE
Apply permissions: AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1301)

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5268]
Realm 3.7.2

I want to grant read only permission for Android user **readOnlyUser** :

1. Login on server by admin (owner) of Relm Object Server
2. On Activity create custom method `**initPermissionGrant()**
3. In this method use **PermissionManager.applyPermissions**
4. Use email of user as user id 

My snippet (in Activity):

 ```
 private void initPermissionGrant() {
        SyncUser ownerUser = SyncUser.currentUser();
        String readOnlyUser = editTextUserId.getText().toString().trim();
        Log.d(TAG, "initPermissionGrant: current user(owner) = " + ownerUser + ", readOnlyUser = " + readOnlyUser);

        PermissionManager pm = ownerUser.getPermissionManager();

        try {
            // Create request
            UserCondition condition = UserCondition.userId(readOnlyUser);
            AccessLevel accessLevel = AccessLevel.READ;
            PermissionRequest request = new PermissionRequest(condition, MyApplication.REALM_URL, accessLevel);
            pm.applyPermissions(request, new PermissionManager.ApplyPermissionsCallback() {

                @Override
                public void onSuccess() {
                  Log.d(TAG, "initPermissionGrant: ApplyPermissionsCallback: onSuccess: Success apply permissions");
                }

                @Override
                public void onError(ObjectServerError error) {
                  Log.e(TAG, "initPermissionGrant: ApplyPermissionsCallback: onError: " + error.getMessage(), error);
                }
            });
        } finally {
            pm.close();
        }
}
```
But when call my method `initPermissionGrant`() I get error:

```
activity.MainActivity(31629): initPermissionGrant: current user(owner) = {UserId: f1111111122222222223ddb9e828700c, AuthUrl: http://112.xx.xxx.xxx:9080/auth}, readOnlyUser = some@email.com
activity.MainActivity(31629): initPermissionGrant: Applying permissions...
activity.MainActivity(31629): REALM_URL = realm://112.xx.xxx.xxx:9080/~/myRealm
activity.MainActivity(31629): readOnlyUser = some@email.com
activity.MainActivity(31629): accessLevel = READ
 java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1301)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:248)
	at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:155)
	at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
 
 `CreateRealmRunnable` has been interrupted.
 java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1301)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:248)
	at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:155)
	at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
 
 `CreateRealmRunnable` has been interrupted.
 io.realm.exceptions.RealmMigrationNeededException: Cannot open the read only Realm. 'Permission' is missing.
	at io.realm.Realm.<init>(Realm.java:165)
	at io.realm.Realm.createInstance(Realm.java:417)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:348)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
	at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
	at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
 
 `CreateRealmRunnable` failed.

```

**Comment by Zhuinden** [comment]
I assume because the Realms managed by the PermissionManager are closed immediately and synchronously, so you might need to close the PermissionManager in the callback.

**Comment by lmdic** [comment]
OK. You are right. Now it work


```
  SyncUser ownerUser = SyncUser.currentUser();
        final PermissionManager pm = ownerUser.getPermissionManager();

        String readOnlyUser = editTextUserId.getText().toString().trim();
        UserCondition condition = UserCondition.userId(readOnlyUser);
        AccessLevel accessLevel = AccessLevel.READ;
        PermissionRequest request = new PermissionRequest(condition, MyApplication.REALM_URL, accessLevel);

        pm.applyPermissions(request, new PermissionManager.ApplyPermissionsCallback() {

            @Override
            public void onSuccess() {
                Log.d(TAG, "initPermissionGrant: ApplyPermissionsCallback: onSuccess: Success apply permissions");
                pm.close();
            }

            @Override
            public void onError(ObjectServerError error) {
                Log.e(TAG, "initPermissionGrant: ApplyPermissionsCallback: onError: " + error.getMessage(), error);
                pm.close();
            }
        });
```

But ...  has another problem.

The user in ROS has email and Realm User Id (**9328b26c6dxxxxxxxxx1b755458**).
If I use Realm User Id as **readOnlyUser** it's work ---> call callback method `ApplyPermissionsCallback: onSuccess()`

But if I use email for **readOnlyUser** I get error:


```
MainActivity(24650): initPermissionGrant: ApplyPermissionsCallback: onError: null
MainActivity(24650): UNKNOWN_ACCOUNT(612)
MainActivity(24650): The account does not exist.: No user known with ID = some@email.com
MainActivity(24650):	at io.realm.PermissionManager$PermissionManagerTask.handleServerStatusChanges(PermissionManager.java:1072)
MainActivity(24650):	at io.realm.PermissionManager$ApplyPermissionTask$2$1.onChange(PermissionManager.java:699)
MainActivity(24650):	at io.realm.PermissionManager$ApplyPermissionTask$2$1.onChange(PermissionManager.java:692)
MainActivity(24650):	at io.realm.ProxyState$RealmChangeListenerWrapper.onChange(ProxyState.java:49)
MainActivity(24650):	at io.realm.internal.OsObject$ObjectObserverPair.onChange(OsObject.java:71)
MainActivity(24650):	at io.realm.internal.OsObject$Callback.onCalled(OsObject.java:90)
MainActivity(24650):	at io.realm.internal.OsObject$Callback.onCalled(OsObject.java:75)
MainActivity(24650):	at io.realm.internal.ObserverPairList.foreach(ObserverPairList.java:109)
MainActivity(24650):	at io.realm.internal.OsObject.notifyChangeListeners(OsObject.java:245)
MainActivity(24650):	at android.os.MessageQueue.nativePollOnce(Native Method)
MainActivity(24650):	at android.os.MessageQueue.next(MessageQueue.java:132)
MainActivity(24650):	at android.os.Looper.loop(Looper.java:124)
MainActivity(24650):	at android.app.ActivityThread.main(ActivityThread.java:5103)
MainActivity(24650):	at java.lang.reflect.Method.invokeNative(Native Method)
MainActivity(24650):	at java.lang.reflect.Method.invoke(Method.java:525)
MainActivity(24650):	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
MainActivity(24650):	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
MainActivity(24650):	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by beeender** [comment]
@lmdic you have to use the user id
