### ISSUE TITLE
Android: The following changes cannot be made in additive-only schema mode:  has been made optional

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5304]
Realm 3.7.2
Server side is create on Node JS.
The client is on Android

Code that try to download data from ROS:

 ```

   private void initRealm() {
         initRealmConfigs(syncUser);
        loadData();
    }

  private void initRealmConfigs(SyncUser syncUser) {
        SyncConfiguration syncConfiguration = createSyncConfiguration(syncUser, BuildConfig.REALM_URL);
        Realm.setDefaultConfiguration(syncConfiguration);
    }

    private SyncConfiguration createSyncConfiguration(SyncUser syncUser, String realmURL) {
        SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(syncUser, realmURL)
                .trustedRootCA(ROOT_CA_PEM)
                .waitForInitialRemoteData()
                .build();       
        return syncConfiguration;
    }

    private void loadDatat() {
        Realm.getInstanceAsync(Realm.getDefaultConfiguration(), new Realm.Callback() {
            @Override
            public void onSuccess(Realm realm) {
            }

            @Override
            public void onError(Throwable throwable) {
                // Error here!
            }
        });
    }
```

When client (Android) is try to download data from Realm Object Server it's get error (throw method **onError(Throwable throwable)**):
```

E/REALM_JAVA(12374): java.lang.IllegalStateException: The following changes cannot be made in additive-only schema mode:
E/REALM_JAVA(12374): - Property 'Profile.address' has been made optional.
E/REALM_JAVA(12374): - Property 'Profile.date' has been made optional.
E/REALM_JAVA(12374):	
 at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
E/REALM_JAVA(12374):	
 at io.realm.internal.SharedRealm.<init>(SharedRealm.java:180)
E/REALM_JAVA(12374):	
 at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
E/REALM_JAVA(12374):	
 at io.realm.BaseRealm.<init>(BaseRealm.java:124)
E/REALM_JAVA(12374):	
 at io.realm.BaseRealm.<init>(BaseRealm.java:93)
E/REALM_JAVA(12374):	
 at io.realm.Realm.<init>(Realm.java:150)
E/REALM_JAVA(12374):	
 at io.realm.Realm.createInstance(Realm.java:417)
E/REALM_JAVA(12374):	
 at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:348)
E/REALM_JAVA(12374):	
 at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
E/REALM_JAVA(12374):	
 at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
E/REALM_JAVA(12374):	
 at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
E/REALM_JAVA(12374):	
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
E/REALM_JAVA(12374):	
 at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/REALM_JAVA(12374):	
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/REALM_JAVA(12374):	
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/REALM_JAVA(12374):	
 at java.lang.Thread.run(Thread.java:841)
E/REALM_JAVA(12374): 
```

**Comment by Zhuinden** [comment]
The schema for `Profile` doesn't match the schema on ROS

**Comment by beeender** [comment]
See https://realm.io/docs/java/latest/#syncing-migrations

**Comment by lmdic** [comment]
I fix the problem. In server side fields Profile.address,  Profile.date  mark as required. But on Android this fields not mandatory.  After I set annotation @Required on this fields, the problem is gone.
