### ISSUE TITLE
Realm Global file stop working with Realm 3.7.2

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-java#5340]
Hi there,
I was having a global realm file that was shared among users. Users where able to shared content. However, since I updated to 3.7.2, I am not able to share content between users. 

This is how user login 
`SyncUser.loginAsync(SyncCredentials.usernamePassword(eMail, password, true), AUTH_URL, new SyncUser.Callback() {`...
where
 `AUTH_URL = "http://" + BuildConfig.OBJECT_SERVER_IP + ":9080/auth";`

The global file is:
`COMMON_REALM_URL = "realm://" + BuildConfig.OBJECT_SERVER_IP + ":9080/" + REALM_NAME;`

and the configuration is:
```
SyncConfiguration commonRealmConfiguration = new SyncConfiguration.Builder(user, COMMON_REALM_URL).build();
Realm.setDefaultConfiguration(commonRealmConfiguration);
```
I adapted my code according to the documentation for Realm 3.7.2 to grant permission. When the global file is created, the admin user grant permissions to all users as follows:
```
private static void setPermissionsDefaultRealm(SyncUser user){
        if (user.isAdmin()){
            PermissionManager pm = user.getPermissionManager();

            UserCondition condition = UserCondition.noExistingPermissions();
            AccessLevel accessLevel = AccessLevel.WRITE;
            PermissionRequest request = new PermissionRequest(condition, COMMON_REALM_URL, accessLevel);

            pm.applyPermissions(request, new PermissionManager.ApplyPermissionsCallback() {
                @Override
                public void onSuccess() {

                }

                @Override
                public void onError(ObjectServerError error) {
                
                }
            });
        }
    }
```
There is not trace or error showing that something is going wrong. The problem is that when I query the file, only returns results for the logged user. I am doing something wrong?

**Comment by Zhuinden** [comment]
(This seems to be a *continuation* of https://github.com/realm/realm-mobile-platform/issues/189 )

In which case previous code was

``` java
    private static void setDefaultPermissionsRealm(SyncUser user){
        if (user.isAdmin()){
            Realm realm = user.getManagementRealm();
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    Boolean mayRead = true; // Grant read access
                    Boolean mayWrite = true; // Keep current permission
                    Boolean mayManage = false; // Revoke management access
                    PermissionChange change = new PermissionChange(REALM_URL,
                            "*",
                            mayRead,
                            mayWrite,
                            mayManage);
                    realm.insert(change);
                }
            });
        }
    }
```

----------

I guess my question is whether `onSuccess()` or `onError()` callbacks are called, and if it is `onError()` then what is the `ObjectServerError`.

**Comment by Zhuinden** [comment]
In the meantime, I found a relevant integration test which could give some ideas: https://github.com/realm/realm-java/blob/0c9c0282d3cfd4b6f8e48cc418fcc9a492446720/realm/realm-library/src/syncIntegrationTest/java/io/realm/PermissionManagerTests.java#L758-L807

**Comment by ojarabo** [comment]
On Success is called.

**Comment by Zhuinden** [comment]
Yup, @cmelchior might know.

**Comment by ojarabo** [comment]
@Zhuinden 
I have a small question. Permission are granted only to existing users? or future users will be granted with write level?

**Comment by ojarabo** [comment]
@Zhuinden @cmelchior 
It is working as far as the admin grant the permissions after the creation of the user. New users has to wait till the permissions are granted to them. Is this a bug? In my previous versions, this was needed to be done only once. After that, all new users were granted with same permissions. 

Thanks

**Comment by cmelchior** [comment]
The permission request does seem to be valid. When you say you query the file, only the first user's results are found. What do you mean exactly?

If the permissions were not applied correctly, new users should not even get access to the file, so it should report an error immediately when you try to open it.

If those new users can actually open the file, but their changes do not show up, it sounds like more a problem with their changes not being uploaded correctly.

If you register an error handler on their Realm, you should see any errors that happen at the session level:

```
SyncConfiguration config = new SyncConfiguration(user, url)
  .errorHandler(...)
  .build();
```

**Comment by ojarabo** [comment]
Hi @cmelchior,
To answer your question. What I meant is that, apparently, the user was only querying to a local file instead to the file in the server. 

I deleted the global file, and the app to make a fresh install. Now, it is working as it is supposed to do. 

Regarding to your suggestion. errorHandler was not called. So, I am not sure whether the global file was corrupted due to some big changes in my models. 

I will close the issue, and if it happens again, I will reopen it with more information. 

Thanks for your help.

**Comment by ojarabo** [comment]
@Zhuinden @cmelchior 
Sometimes is throwing this trace and errorHandler is called:

AuthenticateResponse - Error: UNKNOWN(-1)
                                                                              java.net.SocketTimeoutException: connect timed out
                                                                                  at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                                  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                                                                                  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                                  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                                  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                                  at java.net.Socket.connect(Socket.java:586)
                                                                                  at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
                                                                                  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:221)
                                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
                                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
                                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                                  at okhttp3.RealCall.execute(RealCall.java:69)
                                                                                  at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:146)
                                                                                  at io.realm.internal.network.OkHttpAuthenticationServer.loginToRealm(OkHttpAuthenticationServer.java:64)
                                                                                  at io.realm.SyncSession$2.execute(SyncSession.java:532)
                                                                                  at io.realm.SyncSession$2.execute(SyncSession.java:528)
                                                                                  at io.realm.internal.network.ExponentialBackoffTask.run(ExponentialBackoffTask.java:66)
                                                                                  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                  at java.lang.Thread.run(Thread.java:761)

Could it be this the previous problem?

**Comment by nhachicha** [comment]
This error is related to the part responsible of login in the user or refreshing its access token (which happens regularly in the background) maybe at some point the ROS server was not reachable due to network issue?

**Comment by ojarabo** [comment]
Thanks @nhachicha ,
Can this happen even with the localhost?

**Comment by nhachicha** [comment]
It's less likely if both your emulator/device are on the same local network, I guess it's more often when used with flaky 3G/4G for example...

**Comment by ojarabo** [comment]
Thanks @nhachicha,
It is happening locally. I am not really sure but only happen once in a while.

**Comment by nhachicha** [comment]
Does it happen sporadically on the `4.0.0-RC1` as well?

**Comment by ojarabo** [comment]
@nhachicha, 
Haven't tried. I will test it next week and post the results.

**Comment by beeender** [comment]
@ojarabo any updates? can we close this issue?
