### ISSUE TITLE
Unable to find generated Parcelable class for io.realm.RealmList generated with Parceler.                                                    at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)

### ISSUE THREAD

**Issue by lordofprograms** [realm/realm-java#5393]
```kotlin
@Parcel(value = Parcel.Serialization.FIELD, analyze = arrayOf(ImagesModel::class))
open class ImagesModel : RealmObject() {
    @ParcelPropertyConverter(ImageModelListParcelConverter::class)
    open var imagesList: RealmList<ImageModel>? = null
}

class ImageModelListParcelConverter : RealmListParcelConverter<ImageModel>() {

    override fun itemToParcel(input: ImageModel, parcel: android.os.Parcel) =
            parcel.writeParcelable(Parcels.wrap<ImageModel>(input), 0)

    override fun itemFromParcel(parcel: android.os.Parcel): ImageModel =
            Parcels.unwrap(parcel.readParcelable(ImageModel::class.java.classLoader))

}

abstract class RealmListParcelConverter<T : RealmObject> : CollectionParcelConverter<T, RealmList<T>>() {
    override fun createCollection(): RealmList<T> = RealmList()
}

@Parcel(value = Parcel.Serialization.BEAN, analyze = arrayOf(ImageModel::class))
open class ImageModel : RealmObject() {

    @PrimaryKey
    open var id: Long? = null
    open var image: String? = null
    open var name: String? = null
    open var fileName: String? = null

}
```

> I got error like: 
 org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for io.realm.RealmList, verify that your class is configured properly and that the Parcelable class io.realm.RealmList$$Parcelable is generated by Parceler.
                                                     at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
                                                     at org.parceler.Parcels.wrap(Parcels.java:85)

**Comment by Zhuinden** [comment]
https://gist.github.com/cmelchior/72c35fcb55cec33a71e1#file-realmlistparcelconverter-java or https://gist.github.com/patloew/bc32a2a1a3c0097e9c7020192fb2c78f should work
