### ISSUE TITLE
Nested Transaction Error

### ISSUE THREAD

**Issue by theshapguy** [realm/realm-java#542]
I'm getting this `java.lang.IllegalStateException: Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().` error even though I'm closing the transaction? And there is none other commits that is running in the background.

I'm sending data via a event bus.

``` java
if (resultsSize == 0){
            Realm realm = Realm.getInstance(this, "CineTime.realm");
            try{
                realm.beginTransaction();
                Movie movie = realm.createObject(Movie.class);
                movie.setName(event.movieName);
                movie.setTrailer(event.movieTrailer);
                movie.setReleaseInfo(event.movieReleaseInfo);
                movie.setPoster(event.moviePoster);
                movie.setBackdrop(event.movieBackdrop);
                movie.setOverview(event.movieOverview);
                realm.commitTransaction();
            }catch (Exception e){
                Log.e("Realm Error", "error" e);
            }

        }
```

Illegal State Exception

``` java
 11-08 21:11:00.686  22352-22352/np.com.shapath.muvi E/Realm Error﹕ Error
    java.lang.IllegalStateException: Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().
            at io.realm.internal.ImplicitTransaction.promoteToWrite(ImplicitTransaction.java:37)
            at io.realm.Realm.beginTransaction(Realm.java:706)
            at np.com.shapath.muvi.Application.MuviApplication$2.run(MuviApplication.java:97)
            at np.com.shapath.muvi.Application.MuviApplication.onEvent(MuviApplication.java:115)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:569)
            at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:500)
            at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:475)
            at de.greenrobot.event.EventBus.post(EventBus.java:365)
            at np.com.shapath.muvi.Background.FetchLatestMovieList$1.success(FetchLatestMovieList.java:70)
            at np.com.shapath.muvi.Background.FetchLatestMovieList$1.success(FetchLatestMovieList.java:51)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5059)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by riyase** [comment]
Whats wrong with this code.. im getting the same exception..                    
                    Realm realm = Realm.getDefaultInstance();
                    Location location = new Location();
                    location.setId("123");
                    location.setTitle("germany");
                    realm.beginTransaction();
                    realm.copyToRealmOrUpdate(location);
                    realm.commitTransaction();
                    realm.close();

**Comment by cmelchior** [comment]
Hi @riyase It is probably better if you create a new issue for this, but there is nothing wrong with that piece of code, so most likely you have started a transaction elsewhere that wasn't closed properly

**Comment by riyase** [comment]
the problem was.. i was not closing an opened realm instance in another function in the same activity..

**Comment by bravekingzhang** [comment]
I encountered a similar situation！This sounds weird！ may be in the design of the bug~~~

**Comment by riyase** [comment]
i think when realm crashes after a beginTransaction (and before commitTransaction), realm cannot close that instance and we cannot make transactions after that. i was getting this exception in all transaction after the crash. so catch the exception and close the instance. i didnt experienced this problem after that
