### ISSUE TITLE
MVP - Passing ReamResults from Presenter to Fragment

### ISSUE THREAD

**Issue by maelfosso** [realm/realm-java#5489]
Hi,

Please I'm a newbie on Realm and RxJava.
In my app data go from DataManager -> Presenter -> Fragment/Activity . To pass data from DataManager through Presenter I use Flowable.

#### Goal

I want to pass RealmResults from the presenter to a fragment to put into RealmRecyclerViewAdapter. 
I always got that error **Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created**

#### Expected Results

I expect the RealmResult going from Presenter to the View but I got a error

#### Actual Results
```java
java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.realm.BaseRealm.checkIfValid(BaseRealm.java:426)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.realm.RealmResults.checkForAddRemoveListener(RealmResults.java:220)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.realm.RealmResults.addChangeListener(RealmResults.java:174)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.realm.rx.RealmObservableFactory$6.subscribe(RealmObservableFactory.java:165)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:12986)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.reactivex.Flowable.subscribe(Flowable.java:12932)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
10-30 18:31:32.956 14234-14234/ W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
10-30 18:31:32.956 14234-14234/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-30 18:31:32.956 14234-14234/ W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
10-30 18:31:32.956 14234-14234/ W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
10-30 18:31:32.956 14234-14234/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-30 18:31:32.956 14234-14234/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-30 18:31:32.956 14234-14234/ W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

#### Code Sample
_**DataManager**_
```java
return realm.where(Task.class)
                    .findAllAsync()
                    .asFlowable();
```

_**Presenter**_
```java
getetCompositeDisposable().add(getDataManager()
                .getRTasks()
                .subscribeOn(getSchedulerProvider().io())
                .observeOn(getSchedulerProvider().ui())
                .subscribe(results -> {
                    Log.d(TAG, "loadTaskData() - " + results.size());

                    getMvpView().updateTasksList(results);

                    getMvpView().hideLoading();
                }, error -> {
                    error.printStackTrace();

                    getMvpView().hideLoading();
                }));
```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: yes/no - Don't what is

Android Studio version: 3.0 beta 7

Which Android version and device: ?

**Comment by Zhuinden** [comment]
You're supposed to treat RealmResults like you would treat `LiveData` from architecture components, meaning that you "post value to it" by writing to Realm on background thread in transaction, and you observe for changes **on the ui thread**.

**Comment by maelfosso** [comment]
Thanks for your answer @Zhuinden 

But please, what is **liveresults** ? What does **LiveData** mean ?

**Comment by Zhuinden** [comment]
You can also check out [this article](https://academy.realm.io/posts/creating-a-reactive-data-layer-with-realm-and-rxjava2/) about it, maybe it helps?

Anyways, you can't pass a managed RealmResults between threads, you can either treat it as a loaded live data on the UI thread, or you can use a background HandlerThread as your scheduler and use `realm.copyFromRealm()` to provide detached objects.

Once more tricky option would be

``` java
final RealmConfiguration configuration = realm.getConfiguration();
return Flowable.defer(() -> {
    return realm.where(Task.class).findAllAsync().asFlowable().filter(RealmResults::isLoaded);
}).subscribeOn(getSchedulerProvider().ui())
.observeOn(getSchedulerProvider().io())
.map((ignored) -> {
    try(Realm r = realm.getInstance(configuration)) {
        return r.copyFromRealm(r.where(Task.class).findAll());
    }
})
.observeOn(getSchedulerProvider().ui());
```

**Comment by maelfosso** [comment]
@Zhuinden Thank you.
It's working !!!
