### ISSUE TITLE
io.realm.exceptions.RealmFileException: Unable to open a realm at path '...' Incompatible histories. Expected a Realm with no or in-realm history

### ISSUE THREAD

**Issue by hangonsushant** [realm/realm-java#5534]
#### Goal

> I'm trying to initialize realm database instance from my application class 
```
mRealm = RealmDataBase.getInstance().provideRealm(this);
```
But this error I received from specific devices.

#### This is the error trace of crash from fabric

>  **Fatal Exception: java.lang.RuntimeException: Unable to create application com.app.myapp.MyApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.app.myapp/files/myapp.realm': Incompatible histories. Expected a Realm with no or in-realm history. (Incompatible histories. Expected a Realm with no or in-realm history) (/data/data/com.app.myapp/files/myapp.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 91 Kind: ACCESS_ERROR**.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5501)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.app.myapp/files/myapp.realm': Incompatible histories. Expected a Realm with no or in-realm history. (Incompatible histories. Expected a Realm with no or in-realm history) (/data/data/com.app.myapp/files/myapp.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 91
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:217)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:317)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
       at io.realm.Realm.getInstance(Realm.java:346)
       at com.app.myapp.databasehandler.RealmDataBase.provideRealm(RealmDataBase.java:46)
       at com.app.myapp.MyApplication.onCreate(MyApplication.java:105)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5498)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

#### Code Sample

```
Realm.init(mContext);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .name("myapp.realm")
                .schemaVersion(4)
                .deleteRealmIfMigrationNeeded()
                .build();
        return Realm.getInstance(config);

```

#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: no

Android Studio version: 3.0

Which Android version and device: Android Version 6 (20%) and 7(80%) , and device xiaomi(90%) and motorola (10%)

**Comment by nhachicha** [comment]
Can you share the Realm? Have you tried to open it with Realm browser? did you upgrade to a recent Realm version recently?

**Comment by hangonsushant** [comment]
Yes, I had open it with realm browser, but I have not the device on which error is throwing.
I followed the step from the documentation for adding dependencies in the app using the android studio.

**Comment by beeender** [comment]
Did you ever try to restore the Realm file while the Realm is opened? (like copying the Realm file around etc.)

**Comment by hangonsushant** [comment]
No

**Comment by beeender** [comment]
Can you share your apk with us? if it is possible, debug version of apk is preferred. You can send it to help@realm.io if you want to share it privately .

**Comment by beeender** [comment]
Sorry for the late reply. I tried your apk file, but it seems to be multi-dex problem with your apk?

```
2-28 16:40:35.546  3495  3495 E AndroidRuntime: Process: com.example.abhishekpatel.testbench, PID: 3495
12-28 16:40:35.546  3495  3495 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.example.abhishekpatel.testbench.MainApp: java.lang.ClassNotFoundException: Didn't find class "com.example.abhishekpatel.testbench.MainApp" on path: DexPathList[[zip file "/data/app/com.example.abhishekpatel.testbench-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.abhishekpatel.testbench-1/lib/x86, /data/app/com.example.abhishekpatel.testbench-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.abhishekpatel.testbench.MainApp" on path: DexPathList[[zip file "/data/app/com.example.abhishekpatel.testbench-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.abhishekpatel.testbench-1/lib/x86, /data/app/com.example.abhishekpatel.testbench-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
12-28 16:40:35.546  3495  3495 E AndroidRuntime: 	... 9 more
12-28 16:40:35.546   459  2302 W ActivityManager:   Force finishing activity com.example.abhishekpatel.testbench/.MainActivity

```

**Comment by Zhuinden** [comment]
@beeender could also be instant run problem, they should send an APK that is built with clean rebuild

**Comment by cmelchior** [comment]
Closing due to inactivity
