### ISSUE TITLE
findAllSortedAsync("date", Sort.DESCENDING) causing java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position.

### ISSUE THREAD

**Issue by RohitSurwase** [realm/realm-java#5535]
#### Goal

> I want to sort my realm results in RecyclerView according to the date inserted.

#### Expected Results

> With synchronous queries everything work fine but asynchronous queries giving me an exception.

#### Actual Results

>  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position

#### Steps & Code to Reproduce

> I've added change listener also. If I change findAllSortedAsync() with findAllSorted() it works as expected. Even findAllAsync() works fine without any sort..

#### Code Sample

```java
RealmResults<ModelItem> modelItemRealmResults = realm.where(ModelItem.class).findAllSortedAsync("date", Sort.DESCENDING);

//RealmRecyclerViewAdapter constructor:  autoUpdate=true, updateOnModification=true

//Change listener
modelItemRealmResults .addChangeListener(new OrderedRealmCollectionChangeListener<RealmResults<ModelItem>>() {
            @Override
            public void onChange(@NonNull RealmResults<ModelItem> modelItems, OrderedCollectionChangeSet changeSet) {
                // `null`  means the async query returns the first time.
                if (changeSet == null) {
                    recyclerView.getAdapter().notifyDataSetChanged();
                    return;
                }
                // For deletions, the adapter has to be notified in reverse order.
                OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
                for (int i = deletions.length - 1; i >= 0; i--) {
                    OrderedCollectionChangeSet.Range range = deletions[i];
                    recyclerView.getAdapter().notifyItemRangeRemoved(range.startIndex, range.length);
                }
                OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
                for (OrderedCollectionChangeSet.Range range : insertions) {
                    recyclerView.getAdapter().notifyItemRangeInserted(range.startIndex, range.length);
                }
                OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
                for (OrderedCollectionChangeSet.Range range : modifications) {
                    recyclerView.getAdapter().notifyItemRangeChanged(range.startIndex, range.length);
                }
            }
        });
```

#### Version of Realm and tooling
Realm version(s): > io.realm:realm-gradle-plugin:4.0.0.  (Android Studio)

Realm sync feature enabled:>  No

Android Studio version: ?> 3.0

Android version and device:> Motorola Moto G    7.1.2

**Comment by cmelchior** [comment]
What does your RecyclerViewAdapter look like? You might have been hit by this: https://github.com/realm/realm-android-adapters/issues/132

**Comment by RohitSurwase** [comment]
Yes, StableIds is enabled in adapter's constructor>  setHasStableIds(true);
And I am passing primaryKey as ID.
java```
@Override
    public long getItemId(int index) {
        //noinspection ConstantConditions
        return getItem(index).getPrimaryId();
    }
```

**Comment by beeender** [comment]
Does it have problem if you ` setHasStableIds(false);`?

**Comment by RohitSurwase** [comment]
No, I've not tried that way as I need Ids to be stable.

**Comment by beeender** [comment]
can you try to see if that is the problem?

**Comment by RohitSurwase** [comment]
Okay, wait, I'll reply after trying that way.

**Comment by RohitSurwase** [comment]
It crashed again.
I've commented **setHasStableIds(true);** and
**@Override
    public long getItemId(int index) {
        //noinspection ConstantConditions
        return getItem(index).getPrimaryId();**
But it crashed with following exception.

```java
E/UncaughtException: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{68b6b23 position=3 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{140e2e7 VFED.V... .F....I. 0,164-720,1136 #7f0f00a6 app:id/recycler_view}, adapter:com.rohitss.saveme.LinkRecyclerViewAdapter@36d2e94, layout:android.support.v7.widget.LinearLayoutManager@4261d3d, context:com.rohitss.saveme.HomeActivity@2fe6ed
                                                                               at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5421)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5603)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3644)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
                                                                               at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1710)
                                                                               at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:346)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:699)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:153)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by beeender** [comment]
Do you ever call `notifyItemXxxx()` out of the Realm listeners?

**Comment by RohitSurwase** [comment]
Yes, I've called it for a specific condition.

**Comment by RohitSurwase** [comment]
I've called it after successful deletion of RecyclerView's item on swipe.

**Comment by beeender** [comment]
You shouldn't. Realm listeners will be triggered automatically when the data changed on this/other threads. Calling `notifyItemXxx()` outside of listeners will have a great chance to cause `Inconsistency detected` exception.

> I've called it after successful deletion of RecyclerView's item on swipe.

You just need to remove the item from Realm when swiping, the listener will trigger recycle view update.

**Comment by RohitSurwase** [comment]
okay, let me try this way.

**Comment by RohitSurwase** [comment]
It's crashing. I've tried both ways with and without stable Ids enabled.

**Comment by beeender** [comment]
If you only rely on the listeners to do UI update, it should work ...

If you can provide a sample project to show the problem, we are happy to take a look.

**Comment by RohitSurwase** [comment]
I tried reversing the sort order from Sort.DESCENDING to Sort.ASCENDING and it worked without a crash. Maybe that exception is causing because in Sort.DESCENDING order items are being added from the top.
