### ISSUE TITLE
RealmIOException: Failed to access: . make_dir() failed

### ISSUE THREAD

**Issue by saravanakumarimpiger** [realm/realm-java#5546]
I get this issue when I installed app from MDM(Mobile iron) where application will be wrapped for security purpose.
But it works fine if I install from Android studio,
Can any one please give solution ?
Ream : 1.0.1
minSDK: 18
Stack trace:
 Unable to start activity ComponentInfo{forgepond.default.test/com.default.SplashActivity}:io.realm.exceptions.RealmIOException: Failed to access: . make_dir() failed: No such file or directory path: /data/user/0/com.default.test/files/default.realm.management
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: io.realm.exceptions.RealmIOException: Failed to access: . make_dir() failed: No such file or directory path: /data/user/0/com.default.test/files/default.realm.management
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
	at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
	at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
	at io.realm.BaseRealm.<init>(BaseRealm.java:81)
	at io.realm.Realm.<init>(Realm.java:139)
	at io.realm.Realm.createAndValidate(Realm.java:250)
	at io.realm.Realm.createInstance(Realm.java:230)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
	at io.realm.Realm.getInstance(Realm.java:

**Comment by beeender** [comment]
Does `/data/user/0/com.default.test/files` exist before calling `Realm.getInstance()`?

**Comment by saravanakumarimpiger** [comment]
I'm setting the configuration in application class. And calling the Realm.getInstance() in an activity that time im facing the crash.

When I do local build I'm getting this path /data/data/com.default.test/files/appname.realm.management.

When the build from MDM it makes the path as /data/user/0/com.default.test/files/appname.realm.management.

Is there any possible to create directory name as .(dot) in realm.?

**Comment by beeender** [comment]
Can you setup the debugger and set a breakpoint before `Realm.getInstance()` and some test code to check if `/data/user/0/com.default.test/files` exists on the device with MDM?

I am not familiar with MDM, but it seems the `Context.getFilesDir()` returns a non-existing path on that device which should never happen. Would you please confirm that first please?

**Comment by saravanakumarimpiger** [comment]
We tried to check the path exist or not. Its showing path exit in device with MDM

**Comment by beeender** [comment]
So you are testing with `Ream : 1.0.1`?? That is a quite old version and we fixed lots of issues after that. Would you please try with the latest version?

**Comment by Zhuinden** [comment]
4.2.0 is latest version

**Comment by saravanakumarimpiger** [comment]
Ya we migrated to 4.2.0 
Please refer https://github.com/realm/realm-java/issues/5549

**Comment by saravanakumarimpiger** [comment]
With new version, we are getting (with MDM device)
   Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/com.app.test/files/dentons.realm.management': make_dir() failed: No such file or directory. (make_dir() failed: No such file or directory) (/data/user/0/com.app.test/files/dentons.realm.management) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
                                                         at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
