### ISSUE TITLE
Crash when calling Realm.getDefaultInstance()

### ISSUE THREAD

**Issue by Meisolsson** [realm/realm-java#5551]
#### Goal
Get a default Realm instance.

#### Expected Results
Realm.getDefaultInstance() returns a Realm instance

#### Actual Results
The app crashes:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2751)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2812)
  at android.app.ActivityThread.-wrap12 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1528)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6314)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)
Caused by: java.lang.IllegalStateException: 
  at io.realm.Realm.getDefaultInstance (Realm.java:327)
  at com.meisolsson.spotifyalarm.ui.base.BaseActivity.getRealm (BaseActivity.java:151)
  at com.meisolsson.spotifyalarm.ui.MainActivity.populateAdapter (MainActivity.java:119)
  at com.meisolsson.spotifyalarm.ui.MainActivity.setupRecyclerView (MainActivity.java:115)
  at com.meisolsson.spotifyalarm.ui.MainActivity.onCreate (MainActivity.java:56)
  at android.app.Activity.performCreate (Activity.java:6757)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1119)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2704)
```
#### Steps & Code to Reproduce
I've not been able to reproduce.

#### Code Sample
**Application.java:**
```java
public class Application extends android.app.Application {

    @Override
    public void onCreate() {
        ...
        Realm.init(this);
        RealmConfiguration configuration = new RealmConfiguration.Builder()
                .schemaVersion(2)
                .migration(new AlarmifyMigration())
                .build();

        Realm.setDefaultConfiguration(configuration);
        realm = Realm.getDefaultInstance();
        ....
        super.onCreate();
    }
}
```

**BaseActivity.java:**
```java
public abstract class BaseActivity extends AppCompatActivity {
    private Realm realm;
    ...
    /**
     * @return Instance of {@link Realm}.
     */
    public Realm getRealm() {
        if (realm == null || realm.isClosed()) {
            realm = Realm.getDefaultInstance();
        }

        return realm;
    }
}
```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: no

Android Studio version: Android Studio 3.0

Which Android version and device:
**Android version:** Android 7.0
**Devices:**
* Galaxy S7 (herolte)
* Galaxy S8 Active (cruiserlteatt)
* Galaxy A7(2016) (a7xelte)

**Comment by Meisolsson** [comment]
Couple of extra notes.

1. Bugsnag getting the exception only Google Play. Bugsnag in initialized before Realm in the app so it seem like the Application class is not getting created.
2. I have no ContentProviders in the app.

**Comment by cmelchior** [comment]
Note that some libraries use the ContentProvider trick to initialize themselves first. If that results in some of your code is called, this might be the reason: https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

That said, your crash seems to happen inside an Activity, where it definitely shouldn't be possible as far as I know. It could be a vendor bug, given that it only hit Samsung, but it is a fairly new version of Android so it would be kinda surprising.

My best workaround would be to add a try/catch to your `BaseActivity` class that calls `Realm.init()` if the exception is thrown. It is a hack though

**Comment by Zhuinden** [comment]
@cmelchior actually, I think he just needs to call `super.onCreate()` in Application **before** calling `Realm.init(context)`.

**Comment by Meisolsson** [comment]
@Zhuinden I guess that could be a problem but is there a fact why that would matter? It work fine on my phone and many other to have it in the order which I have now.

**Comment by Zhuinden** [comment]
Who knows what `Application.onCreate()` does on a Samsung phone! 😄 

Jokes aside, I think in their code, `getSystemService()` runs **before** `onCreate()`, but only on Samsung devices

**Comment by Meisolsson** [comment]
Alright, I'll try that and will come back with some results later.

**Comment by cmelchior** [comment]
Good catch @Zhuinden. That does luck suspicious, I agree.

**Comment by Meisolsson** [comment]
Still happening with the `super.onCreate()` moved to the top.

**Comment by Meisolsson** [comment]
Alright, seem like it happen on most phones. Some examples: Nexus 5, Moto G, LG K8. Any chance that the `Application.onCreate()` is not called?

**Comment by cmelchior** [comment]
Possible, but without more information, it would be hard to tell. What exactly is the IllegalState message? Because judging from your code you are already opening the Realm in the Application subclass, so I'm wondering what the exact exception is?

If it is indeed the application class not being created and it is impossible to find the root cause, then you can work around it by doing something like this:

```
    public Realm getRealm() {
        if (realm == null || realm.isClosed()) {
            try { 
              realm = Realm.getDefaultInstance(); 
            } catch (IllegalStateException e) {
              if (e.getMessage().contains("Call `Realm.init(Context)` before creating a RealmConfiguration")) {
                 Realm.init(getApplicationContext());
                 realm = Realm.getDefaultInstance();
              } else {
                 throw e;
              }
            } 
        }

        return realm;
    }
```

**Comment by Meisolsson** [comment]
Well there is not message, Google Play console doesn't give me the message from what I can see. But I just saw that another thing which requires initializing from the Application and that's failing too.

Gonna guess that the `Application.onCreate()` is not called which is weird, but from what I'm seeing that would be the only possible fault.

**Comment by behelit** [comment]
Can confirm that I am also only seeing it on Android 6.0 devices.

**Comment by aayvazyan-tgm** [comment]
About 5% of my users are affected by this bug.
This issue is not related to the android version, as I see it occuring on Version 4-7.
It is also not related to the device.

My DB setup is currently very simple:

I have registered a custom Application class in my manifest:
```
<manifest
    ...
    <application
        android:name=".MainApplication"
        ...>
```
```
MainApplication extends MultiDexApplication.onCreate(){
    super.onCreate()
    Realm.init(context)
    val config = RealmConfiguration.Builder()
            .name("user-db")
            .deleteRealmIfMigrationNeeded()
            .schemaVersion(1)
            .build()
    Realm.setDefaultConfiguration(config)
}
```
Later on `Realm.getDefaultInstance` fails during `Acticity.onCreate()` for some of my users with **Call `Realm.init(Context)` before calling this method.**

**Comment by jacobocl** [comment]
Same happens in here, about 1% of my users affected. Taking into account the data from Fabric, looks like it's a bug that happens with some devices that run Android 6, because 97% of the crashes are produced in Android 6 devices.
Most affected vendors are: LG, Wiko, BQ, ZTE & Motorola.

Moreover, this has started happening when I updated from Realm 1.0.0 to Realm 5.1.0 :sweat_smile:

**Comment by cmelchior** [comment]
@jacobocl Do you get any detailed information in the IllegalStateException?

**Comment by jacobocl** [comment]
@cmelchior Not much more. This is the stacktrace:

> Fatal Exception: java.lang.IllegalStateException: Call `Realm.init(Context)` before calling this method.
       at io.realm.Realm.getDefaultInstance(Realm.java:338)
       at com.myapp.data.entity.helper.RealmHelper.getRealmInstance(RealmHelper.java:21)
       at com.myapp.data.repository.datasource.alarm.DbAlarmDataStore.deleteExpiredAlarms(DbAlarmDataStore.java:237)
       at com.myapp.data.repository.AlarmDataRepository.deleteExpiredAlarms(AlarmDataRepository.java:159)
       at com.myapp.domain.interactor.DeleteExpiredAlarmsUseCaseImpl.run(DeleteExpiredAlarmsUseCaseImpl.java:31)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

Checking the data of the stacktrace, I've seen that the crash occurs the first time that `Realm.getDefaultInstance()` is called in the application. However, `Realm.init()` is invoked before that, in Application.onCreate()

**Comment by berkayturanci** [comment]
Same to me;
```

Caused by: java.lang.IllegalStateException: 
  at io.realm.Realm.getDefaultInstance (Realm.java:271)
  at com.nonzeroapps.android.smartinventory.fragment.ListFragment.onCreate (ListFragment.java:65)

```
`realm = Realm.getDefaultInstance();  -->> ListFragment.java:65
`

I do have the following in my Application class though;

```
 Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .schemaVersion(9) // Must be bumped when the schema changes
                .migration(new RealmMigration()) // Migration to run instead of throwing an exception
                .build();

        Realm.setDefaultConfiguration(config);
```

**Comment by TheMaxCoder** [comment]
We are also seeing this crash when trying to get the default instance. happening only on Android 6.0

```
Caused by: java.lang.IllegalArgumentException: 
  at io.realm.Realm.init (Unknown Source)
                    getInstance
                    createInstance
                    initializeRealm
                    createObjectInternal$6d9349d5
                    createObjectInternal$1e283631
                    copyToRealm
                    where
                    executeTransaction
                    copyOrUpdate
                    updateSchemaCache
                    isInTransaction
```
Even trying below doesn't help

```
public static Realm getSafeRealm(Context context) {
        Realm realm;
        try {
            realm = Realm.getDefaultInstance();
        } catch (IllegalStateException e) {
            initRealm(context.getApplicationContext());
            realm = Realm.getDefaultInstance();
        }
        return realm;
    }
```

What could be the cause this issue and possible fix?

Thanks so much.

**Comment by adnan-SM** [comment]
This is something which has started happening for us off-late as well. We used to use Realm without any issues but recently when trying to call Realm.getDefaultInstance() in an Activity class this crash occurs. 

P.S : My Application class is initialising Realm in onCreate()

**Comment by calebfung** [comment]
Any update on this issue? This is happening to me on production builds running on Samsung devices but not on development builds.

**Comment by GARGUI3** [comment]
Hi, any update about this issue? This is happening to me only in Huawei P30 the other devices works correctly, thanks

**Comment by cmelchior** [comment]
@GARGUI3 Do you have a full stack trace? And what version of Realm are you using?

**Comment by GARGUI3** [comment]
Hi @cmelchior of course

The full stack trace is:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3895)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4074)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:91)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2473)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8347)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1055)
Caused by: java.lang.IllegalStateException: 
  at io.realm.Realm.getDefaultInstance (Realm.java:402)
  at io.beek.android.playbik.database.controllers.UserController.<init> (UserController.java:14)
  at io.beek.android.playbik.Player.onCreate (Player.java:118)
  at android.app.Activity.performCreate (Activity.java:8085)
  at android.app.Activity.performCreate (Activity.java:8073)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1320)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3868)
```

and the realm version is 6.0.2

Thanks

**Comment by GARGUI3** [comment]
Hi @cmelchior, any update about this issue? This happen a lot in Huawei cellphones

**Comment by GARGUI3** [comment]
Hi @cmelchior, any update about this issue? Or is there any workaround for that issue?

**Comment by clementetb** [comment]
@GARGUI3 The exception you are experiencing is caused because Realm wasn't properly initialized.

Are you calling `Realm.init(context)` and `Realm. setDefaultConfiguration` before calling this method?

**Comment by javs12** [comment]
Hi @clementetb  I am calling `Realm.init(context)` and `Realm. setDefaultConfiguration` before `Realm.getDefaultInstance` but the crash keeps happening, is there any solution?

**Comment by rorbech** [comment]
@javs12 Can you provide the stack trace and some code to reproduce this?
