### ISSUE TITLE
Inconsistency detected. Invalid view holder adapter positionViewHolder

### ISSUE THREAD

**Issue by DimaTasmuk** [realm/realm-java#5559]
I have RecyclerView with nested RealmRecyclerViewAdapter. When I run my app at first time all good. But when I reopen app, it crashes. How can I fix it?

**Bugs**: 
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{adeab34 position=4 id=0, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{15bf1af VFED..... .F....I. 0,159-1032,831 #7f080065 app:id/list}, adapter:tasmuk.com.mybudget.ui.fragment.operationlist.adapter.OperationCardAdapter@42369bc, layout:android.support.v7.widget.LinearLayoutManager@b37d45, context:tasmuk.com.mybudget.ui.activity.MainActivity@9583952
                      at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5447)
                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5629)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
                      at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3129)
                      at android.view.View.measure(View.java:19759)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                      at android.view.View.measure(View.java:19759)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.support.v7.widget.CardView.onMeasure(CardView.java:219)
                      at android.view.View.measure(View.java:19759)
                      at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8791)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1584)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:874)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                      at android.view.View.layout(View.java:17548)
                      at android.view.ViewGroup.layout(ViewGroup.java:5614)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2384)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2111)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1288)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6359)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                      at android.os.Handler.handleCallback(Handler.java:754)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:163)
                      at android.app.ActivityThread.main(ActivityThread.java:6237)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

#### Code Sample

```
public class OperationListAdapter extends RecyclerView.Adapter<BindingHolder<ItemOperationListBinding>> {

    private Context context;
    private ArrayList<OperationListResponse> realmResults;

    public OperationListAdapter(Context context, ArrayList<OperationListResponse> data) {
        this.context = context;
        this.realmResults = data;
    }

    @Override
    public BindingHolder<ItemOperationListBinding> onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        ItemOperationListBinding binding = DataBindingUtil.inflate(inflater, R.layout.item_operation_list, parent, false);
        return new BindingHolder<>(binding);
    }

    @Override
    public void onBindViewHolder(BindingHolder<ItemOperationListBinding> holder, int position) {
        OperationListResponse operationListResponse = realmResults.get(position);

        OperationCardAdapter cardAdapter = new OperationCardAdapter(context, operationListResponse.getOperations());
        holder.binding.list.setAdapter(cardAdapter);
        holder.binding.list.setLayoutManager(new LinearLayoutManager(context));

        holder.binding.tvDay.setText(operationListResponse.getDay());
        holder.binding.tvDayOfWeek.setText(operationListResponse.getDayOfWeek());
        holder.binding.tvMonthYear.setText(String.format("%s %s", operationListResponse.getMonthName(), operationListResponse.getYear()));
        holder.binding.tvDateCost.setText(String.valueOf(operationListResponse.getCost()));
        holder.binding.tvDateCurrency.setText(operationListResponse.getDateCurrency());

        if(operationListResponse.getDateType() == OperationType.INCOME) {
            holder.binding.tvDateCost.setTextColor(context.getResources().getColor(R.color.green));
            holder.binding.tvDateCurrency.setTextColor(context.getResources().getColor(R.color.green));
        } else if (operationListResponse.getDateType() == OperationType.EXPENSE) {
            holder.binding.tvDateCost.setTextColor(context.getResources().getColor(R.color.red));
            holder.binding.tvDateCurrency.setTextColor(context.getResources().getColor(R.color.red));
        }
    }

    @Override
    public int getItemCount() {
        return realmResults.size();
    }
}
```
And nested adapter:
```
public class OperationCardAdapter extends RealmRecyclerViewAdapter<Operation, BindingHolder<ItemOperationCardBinding>> {

    private Context context;

    OperationCardAdapter(Context context, OrderedRealmCollection<Operation> operations) {
        super(operations, true);
        setHasStableIds(true);
        this.context = context;
    }

    @Override
    public BindingHolder<ItemOperationCardBinding> onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        ItemOperationCardBinding binding = DataBindingUtil.inflate(inflater, R.layout.item_operation_card, parent, false);
        return new BindingHolder<>(binding);
    }

    @Override
    public void onBindViewHolder(BindingHolder<ItemOperationCardBinding> holder, int position) {
        final Operation operation = getItem(position);
        holder.binding.tvCategory.setText(operation.getCategory().getName());
        holder.binding.tvDescription.setText(operation.getDescription());
        holder.binding.tvCost.setText(String.valueOf(operation.getCost()));
        holder.binding.tvCurrency.setText(operation.getCurrency());

        if (operation.getType() == OperationType.INCOME) {
            holder.binding.tvCost.setTextColor(context.getResources().getColor(R.color.green));
            holder.binding.tvCurrency.setTextColor(context.getResources().getColor(R.color.green));
        } else if (operation.getType() == OperationType.EXPENSE) {
            holder.binding.tvCost.setTextColor(context.getResources().getColor(R.color.red));
            holder.binding.tvCurrency.setTextColor(context.getResources().getColor(R.color.red));
        }
    }
}
```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: no

Android Studio version: 3.0

Which Android version and device: Xiaomi Redmi Note 4X (API 24)

**Comment by Zhuinden** [comment]
>     private ArrayList<OperationListResponse> realmResults;

???

**Comment by DimaTasmuk** [comment]
I have main RecyclerView with CardView. In every Card I have RealmRecyclerView. In OperationListResponse I save OrderedRealmCollection<Operation> and other information that needs for showing.

**Comment by cmelchior** [comment]
Your `OperationListAdapter` doesn't seem to listen for changes in Realm, so I suspect that it is crashing because when items are added or removed?

**Comment by DimaTasmuk** [comment]
App is crashing when I reopen it. Maybe then data really removed and added again

**Comment by cmelchior** [comment]
My best advice is to look at the implementation in https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java as that shows to register listeners.
