### ISSUE TITLE
App crash due to Encryption failed on some devices 

### ISSUE THREAD

**Issue by Tesla-v6** [realm/realm-java#5584]
I have been using realm for long time i start to get fabric crash for some devices 

>Realm java version 3.7.2

>Devices 1- Huwawi ( MHA-L29 , BLA-L29 ) , 2-HTC  ( HTC Ultra 100 ) 3- Xiaomi ( MI MAX ,MI MAX 2) 

>OS version 7.0 , 7.1.1 , 8.0.0 

stack trace 
```java

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{/com.myapp.token.home.HomeActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.myapp.bar/files/app_data': Realm file decryption failed. (Realm file decryption failed) (/data/data/com.myapp.bar/files/app_data) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 91 Kind: ACCESS_ERROR.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2712)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1520)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6267)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.myapp.bar/files/app_data': Realm file decryption failed. (Realm file decryption failed) (/data/data/com.myapp.bar/files/app_data) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 91
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:217)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:317)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
       at io.realm.Realm.getDefaultInstance(Realm.java:325)
       at com.myapp.token.dashboard.presenter.DashboardPresenter.createRealm(DashboardPresenter.java:502)
       at com.myapp.token.dashboard.presenter.DashboardPresenter.onAttachView(DashboardPresenter.java:65)
       at com.myapp.token.dashboard.presenter.DashboardPresenter.onAttachView(DashboardPresenter.java:31)
       at com.myapp.token.core.PresenterFragment.attachViewToPresenter(PresenterFragment.java:89)
       at com.myapp.token.core.PresenterFragment.onStart(PresenterFragment.java:75)
       at com.myapp.token.dashboard.ui.DashboardFragment.onStart(DashboardFragment.java:394)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2907)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:613)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at com.myapp.token.home.BaseActivity.onStart(BaseActivity.java:41)
       at com.myapp.token.core.PresenterActivity.onStart(PresenterActivity.java:57)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
       at android.app.Activity.performStart(Activity.java:6887)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1520)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6267)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
```

Realm Key Generator 
```java
public class RealmKeyGenerator {

    SharedPreferences mAppSharedPrefs;

    public RealmKeyGenerator(SharedPreferences aAppSharedPrefs) {
        mAppSharedPrefs = aAppSharedPrefs;
    }


    public byte[] getRealmKey() {
        byte[] key;
        String savedKey = getStringFromPrefs(PreferenceConstants.REALM_KEY);
        if (isBlank(savedKey)) {
            key = generateKey();
            String keyString = encodeToString(key);
            saveStringToPrefs(keyString);
        } else {
            key = decodeFromString(savedKey);
        }
        return key;
    }

    public void removeRealmKey() {
        mAppSharedPrefs.edit().remove(PreferenceConstants.REALM_KEY).apply();
    }

    @NonNull
    private String getStringFromPrefs(String aKey) {
        return mAppSharedPrefs.getString(aKey, "");
    }

    private void saveStringToPrefs(String aKeyString) {
        mAppSharedPrefs.edit().putString(PreferenceConstants.REALM_KEY, aKeyString).apply();
    }

    private String encodeToString(byte[] aKey) {
        return Base64.encodeToString(aKey, Base64.DEFAULT);
    }

    private byte[] decodeFromString(String aSavedKey) {
        return Base64.decode(aSavedKey, Base64.DEFAULT);
    }

    private byte[] generateKey() {
        byte[] key = new byte[64];
        new SecureRandom().nextBytes(key);
        return key;
    }

    private boolean isBlank(String str){
    return str == null || str.trim().length == 0;
    }
}
```

Realm default instance 

```java
Realm.setDefaultConfiguration(
        new RealmConfiguration.Builder()
                .name(RealmContractor.NAME)
                .encryptionKey(new RealmKeyGenerator(getSharedPreference(PreferenceConstants.REALM_PREF_NAME,MODE_PRIVATE)).getRealmKey())
                .schemaVersion(RealmContractor.VERSION)
                .migration(new AppMigrationPlan())
                .build()
);
```
-> Realm sync feature enabled: no

**Comment by beeender** [comment]
is `Realm.setDefaultConfiguration()` only called once?
`RealmKeyGenerator.getRealmKey()` is not a thread safe method, if there is any race condition happens, the key will be different.

**Comment by Tesla-v6** [comment]
```Realm.setDefaultConfiguration()``` called once in Application class when the app first run

```java 
public class App extends MultiDexApplication {
.....

public void onCreate(){
initializeRealm();
}

private void initializeRealm() {
        Realm.init(getApplicationContext());
        Realm.setDefaultConfiguration(
        new RealmConfiguration.Builder()
                .name(RealmContractor.NAME)
                .encryptionKey(new RealmKeyGenerator(getSharedPreference(PreferenceConstants.REALM_PREF_NAME,MODE_PRIVATE)).getRealmKey())
                .schemaVersion(RealmContractor.VERSION)
                .migration(new AppMigrationPlan())
                .build()
);
    }
```

**Comment by beeender** [comment]
Do you have any remote services in the apk which are running in another process?

**Comment by Tesla-v6** [comment]
No I only only single process

**Comment by beeender** [comment]
It feels like something is wrong with generating/retrieving keys from SharedPerf, but I am a bit clueless now ... if you have a way to reproduce the issue, please let us know. Thanks.

**Comment by VenomVendor** [comment]
```java
public byte[] getRealmKey() {
    byte[] key;
    String savedKey = getStringFromPrefs(PreferenceConstants.REALM_KEY);
    if (isBlank(savedKey)) {
        key = generateKey();
        String keyString = encodeToString(key);
        saveStringToPrefs(keyString);
    } else {
        key = decodeFromString(savedKey);
    }
    return key;
}

private void saveStringToPrefs(String aKeyString) {
    mAppSharedPrefs.edit().putString(PreferenceConstants.REALM_KEY, aKeyString).apply();
}
```

**Possible reason.**
Key doesn't get saved to sharedpreference.

1. First launch, `isBlank(savedKey)` is `true`.
2. `key  = generateKey()` `// This is used to encrypt Realm, assuming the key is always saved in next step.`
3. `saveStringToPrefs(keyString);`
4. `editor.put(...).apply();` `// Hmmm, for unknown reasons, this doesn't succeed. But realm is already encrypted with this key.`
5. Next launch new key is generated, conflicting with current key.

**Fix**
In step 4, use `editor.put(...).commit();`. This is synchronous & returns `true` if value get's saved successfully.
In case of failure, do not encrypt realm, as encryption key is not saved or retry to save key.

_**This can probably be reproduced by commenting out `saveStringToPrefs(keyString);`**_

## Additional notes
`encodeToString` & `decodeFromString` can be avoided, doesn't add any value, apart from masking the real encryption key.

<hr />

```java
private boolean isBlank(String str) {
    return str == null || str.trim().length == 0;
}
```
**isBlank** is private & called only from one place `isBlank(savedKey)`. `savedKey` is definately `NonNull`. Hence `str == null` is redundant inside `isBlank`

```java
// Better blank check
private boolean isBlank(String str) {
    return str.trim().isEmpty();
}
```

**Comment by beeender** [comment]
@VenomVendor Thanks a lot for the analysis!!! 

@Tesla-v6 please take a look at the above comment to see if it help. I am closing this issue now, feel free if you still need help.
