### ISSUE TITLE
Cannot use entities defined in main and androidTest

### ISSUE THREAD

**Issue by powturns** [realm/realm-java#5586]
#### Goal

Define entity objects under androidTest that are only for test classes, but also have entities available from the main application.

#### Expected Results

`ChatMessageEntity` is defined in main app
`TestEntity` is defined in androidTest
Both should be available for use.

#### Actual Results

`io.realm.exceptions.RealmException: 'class app.model.entity.ChatMessageEntity' is not part of the schema for this Realm.`

```
:app:compileDebugJavaWithJavac
Note: Version 4.3.0 of Realm is now available: http://static.realm.io/downloads/java/latest
Note: Processing class ChatMessageEntity
Note: Creating DefaultRealmModule

...later...

:app:compileDebugAndroidTestJavaWithJavac
Note: Version 4.3.0 of Realm is now available: http://static.realm.io/downloads/java/latest
Note: Processing class TestEntity
Note: Creating DefaultRealmModule
```

If the TestEntity class is removed, then the tests can find the ChatMessageEntity. I _think_ it may be the case that the default module is getting overwritten during the `app:compileDebugAndroidTestJavaWithJavac` step. I've tried doing a custom module for the tests, but when I try to pull in ChatMessageEntity I get the following error during annotation processing: `ChatMessageEntity could not be added to the module. Only classes extending RealmObject, which are part of this project, can be added.`

```java
public class TestEntity extends RealmObject {
    @PrimaryKey
    private String id;
//...
}

public class ChatMessageEntity extends RealmObject {
    @PrimaryKey
    private String id;
//...
}
```

#### Version of Realm and tooling
Realm version(s): 4.2.0/4.3.0

Realm sync feature enabled: no

Android Studio version: 3

**Comment by Zhuinden** [comment]
If your schema differs per configuration, you might want to explicitly define your schema using `@RealmModule`.

**Comment by 51systems** [comment]
Based on the message that I'm getting from the annotation processor (see above) it doesn't seem to be possible to include classes from the main application to a module defined in  androidTest

**Comment by beeender** [comment]
It is a bit strange since the our tests have similar structures when sync enabled.

How does your project structure look like? Do you have any library modules using Realm as well? Is it only an app module in the root project?

**Comment by 51systems** [comment]
Example project:
https://github.com/51systems/RealmBugs/tree/test-entity

Make sure you're on the test-entity branch. When running in AS3 I get:
```
io.realm.exceptions.RealmException: 'class test.realm.realmtest.model.MainEntity' is not part of the schema for this Realm.
at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:240)
at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:100)
at io.realm.Realm.copyOrUpdate(Realm.java:1593)
at io.realm.Realm.copyToRealm(Realm.java:994)
at test.realm.realmtest.repository.RepositoryTest.testMainEntity(RepositoryTest.java:29)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1941)

```

Perhaps an issue with newer versions of gradle?

**Comment by beeender** [comment]
Yeah, i can reproduce the problem. checking...
