### ISSUE TITLE
RealmFileException Unable to open a realm at path 'xxx': Incompatible histories

### ISSUE THREAD

**Issue by chrisbln** [realm/realm-java#5606]
#### Goal

Call
Realm.getInstance(realmConfiguration)`
`with
```
new RealmConfiguration.Builder()
      .name(Realm.DEFAULT_REALM_NAME)
      .migration(new DefaultMigration(context))
      .schemaVersion(7)
      .build();
```
#### Expected Results

Get the Realm instance without exceptions.

#### Actual Results

```
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.moviebase/files/default.realm': Incompatible histories. Expected a Realm with no or in-realm history. (Incompatible histories. Expected a Realm with no or in-realm history) (/data/data/com.moviebase/files/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Unknown Source)
       at io.realm.internal.OsSharedRealm.(Unknown Source)
       at io.realm.internal.OsSharedRealm.getInstance(Unknown Source)
       at io.realm.internal.OsSharedRealm.getInstance(Unknown Source)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(Unknown Source)
       at io.realm.RealmCache.getCache(Unknown Source)
       at io.realm.Realm.getInstance(Unknown Source)
       at com.moviebase.data.local.RealmService.(Unknown Source)
       at com.moviebase.data.DataManager.(Unknown Source)
       at com.moviebase.injection.module.NetModule.provideIdManager(Unknown Source)
       at com.moviebase.injection.module.NetModule_ProvideDataManagerFactory.get(Unknown Source)
       at com.moviebase.injection.component.DaggerApplicationComponent.dataManager(Unknown Source)
       at com.moviebase.injection.component.DaggerActivityComponent.injectMainActivity(Unknown Source)
       at com.moviebase.injection.component.DaggerActivityComponent.builder(Unknown Source)
       at com.moviebase.ui.list.MovieListFragment.onViewCreated(Unknown Source)
```

#### Steps & Code to Reproduce

The problem occur when the App is launched in the first Fragment.
Only one user with Realm version 4.2.0, HTC M10, Android 10 got this exception.

The app is using Realm:
- Migration & DynamicRealm
- Execute a lot of transactions in AsyncTask/JobIntentService/RxJava
- Realm.compactRealm

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s):  4.2.0

Realm sync feature enabled: no

Android Studio version: 3.1

Which Android version and device: 
HTC M10
Android 7.0

**Comment by nhachicha** [comment]
Hi @chrisbln 
Are you compacting from a different process?

It would be helpful if you can provide the Realm for analysis...

You can check the similar issues as well 
https://github.com/realm/realm-java/issues/5534, https://github.com/realm/realm-java/issues/5175

**Comment by chrisbln** [comment]
Yes, I did something like that :

```
public class RealmJobService extends JobService {

  private AsyncTask<Void, Void, Boolean> task;

  @Override
  public boolean onStartJob(JobParameters params) {
    task = new RealmAsyncTask(this, false) {

      @Override
      protected Boolean doInBackground(Void... voids) {
        if (MoviebaseApplication.isActivityAvailable(RealmJobService.this)) {
          return true;
        }
       //...
      // get realmConfiguration from Dragger
       if (Realm.getGlobalInstanceCount(realmConfiguration) == 0) {
         Realm.compactRealm(realmConfiguration);
        }
        return super.doInBackground(voids);
      }

      @Override
      protected void onPostExecute(Boolean success) {
        super.onPostExecute(success);
        jobFinished(params, !success);
      }
    };

    task.execute();
    return true;
  }
}
```

**Comment by cmelchior** [comment]
Folding this issue into #5175 . But it is most likely caused by compact being called when multiple processes have the file open. Note that `getGlobalInstanceCount()`does not take into account Realms in other processes.

**Comment by Zhuinden** [comment]
I should one day do something about https://github.com/realm/realm-core/issues/2968 which would help
