### ISSUE TITLE
Nested query crashes when String field is null

### ISSUE THREAD

**Issue by andersndanielsen** [realm/realm-java#5615]
#### Goal

Nested query should return all ExerciseSets that is of Exercise if this Exercise is performed yet.

#### Expected Results

An empty list if this Exercise is not performed yet.

#### Actual Results
The app crashes with an error that doesn't make sense to me. setNumber is not queried.

Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: This field(setNumber) is not nullable.
       at io.realm.internal.TableQuery.nativeEqual(TableQuery.java)
       at io.realm.internal.TableQuery.equalTo(TableQuery.java:328)
       at io.realm.RealmQuery.equalToWithoutThreadValidation(RealmQuery.java:302)
       at io.realm.RealmQuery.equalTo(RealmQuery.java:297)
       at io.realm.RealmQuery.equalTo(RealmQuery.java:282)
       at io.strongapp.strong.data.RealmDB.getCommonExerciseSetQuery(RealmDB.java:1155)
       at io.strongapp.strong.data.RealmDB.getPersonalRecordExerciseSets(RealmDB.java:1046)
       at io.strongapp.strong.common.exercises.exercise_detail.records.ExerciseRecordsPresenter.<init>(ExerciseRecordsPresenter.java:32)
       at io.strongapp.strong.common.exercises.exercise_detail.records.ExerciseRecordsFragment.onCreateView(ExerciseRecordsFragment.java:68)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
       at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:616)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

#### Steps & Code to Reproduce

This happened after I updated realm from 2.3.0 to 4.1.1.
This only happens if exercise.getObjectId() is null.
This doesn't happen if I remove the 3rd equalTo(), or if I keep the query and its fieldName but changes the value from exercise.getObjectId() to exercise.getUniqueId(). 
#### Code Sample

```java
//The query that crashes.
private RealmQuery<ExerciseSet> getCommonExerciseSetQuery(Realm realm, Exercise exercise) {
        return realm.where(ExerciseSet.class)
                .equalTo("setGroup.user.objectId", getUser().getObjectId())
                .equalTo("setGroup.exercise.uniqueId", exercise.getUniqueId())
                .equalTo("setGroup.exercise.objectId", exercise.getObjectId())
                .equalTo("setGroup.isHidden", false)
                .isNotNull("setGroup.completionDate");
 }

public class ExerciseSet extends RealmObject {
    @Required
    private String id;
    private int setNumber; //Only local on Android
    private Integer reps;
    private Integer expectedReps;
    private Double kilograms;
    private Double expectedKilograms;
    private Double meters;
    private Double expectedMeters;
    private Integer seconds;
    private Integer expectedSeconds;
    private SetGroup setGroup;
    ... 
}

public class Exercise extends RealmObject {
   @Index
    private String uniqueId;
    @Index
    private String objectId;
    private RealmList<SetGroup> setGroups;
    ...

    public String getObjectId() {
        return objectId;
    }
}

public class SetGroup extends RealmObject {
    @Index
    private String uniqueId;
    private User user;

    @Index
    private String objectId;
    ...
    private Exercise exercise;
    private Workout workout;
    private RealmList<ExerciseSet> exerciseSets;
}
```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: 7.0 Moto G5 Plus

**Comment by andersndanielsen** [comment]
If exercise.uniqueId or user.objectId is null it crashes with message " This field(id) is not nullable."
Both fields id and setNumber is on ExerciseSet.class

**Comment by beeender** [comment]
you are query by check if `setNumber` equals to `null`, which is surely not, since `setNumber` is a `int` field and it is not nullable.

If the `setNumber` could be `null`, you should declare it as boxed type `Integer`.

**Comment by andersndanielsen** [comment]
It can't be null, and as far as I know I never query it. All the .equalTo() checks exerciseSet.setGroup, and not exerciseSet.id of .setNumber. Isn't it weird that the error message changes if I force some of the other nested fields to be null?

**Comment by beeender** [comment]
Sorry that i didn't read your description carefully. I can confirm it is bug in our side.


test case to reproduce it:

```java
    @Test
    public void equalTo_nullValueLinkedField() {
        realm.beginTransaction();
        DogPrimaryKey dog = realm.createObject(DogPrimaryKey.class, 42);
        dog.setName(null);
        Cat cat = realm.createObject(Cat.class);
        cat.setScaredOfDog(dog);
        Owner owner = realm.createObject(Owner.class);
        owner.setCat(cat);
        realm.commitTransaction();

        Owner owner1 = realm.where(Owner.class).equalTo("cat.scaredOfDog.name", (String) null).findFirst();
        assertNotNull(owner1);
    }
```

**Comment by andersndanielsen** [comment]
Thanks for quick responses! 
I guess that test will crash the app.
For now I work around this by not querying this field if it's null.
