### ISSUE TITLE
Bad Realm file header (#3) ACCESS_ERROR

### ISSUE THREAD

**Issue by ovUdemy** [realm/realm-java#5629]
#### Goal

> Prevent the crash.

#### Expected Results

> Doesn't crash.

#### Actual Results

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.app.view.activity.MainActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.app/files/data.realm': Bad Realm file header (#3). (Bad Realm file header (#3)) (/data/data/com.app/files/data.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.app/files/data.realm': Bad Realm file header (#3). (Bad Realm file header (#3)) (/data/data/com.app/files/data.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:244)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
       at io.realm.Realm.getInstance(Realm.java:353)
       at com.app.di.NetModule.provideDataRealm(NetModule.java:99)
       at com.app.di.NetModule_ProvideDataRealmFactory.get(NetModule_ProvideDataRealmFactory.java:28)
       at com.app.di.NetModule_ProvideDataRealmFactory.get(NetModule_ProvideDataRealmFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.app.di.NetModule_ProvideRealmControllerFactory.get(NetModule_ProvideRealmControllerFactory.java:31)
       at com.app.di.NetModule_ProvideRealmControllerFactory.get(NetModule_ProvideRealmControllerFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.app.di.DaggerNetComponent.injectMainActivity(DaggerNetComponent.java:195)
       at com.app.di.DaggerNetComponent.inject(DaggerNetComponent.java:95)
       at com.app.view.activity.MainActivity.dataInitialization(MainActivity.java:707)
       at com.app.view.activity.MainActivity.onCreate(MainActivity.java:169)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

#### Steps & Code to Reproduce

Can't reproduce. Happens to some users. Getting this from Fabric:
Samsung S5 - 6.0.1
Canvas Nitro - 4.4.2

#### Code Sample

Relevant code according to the stack trace. I'm injecting Realm via Dagger like so: 
```
Realm provideDataRealm(Application application) {
        Realm.init(application);

        RealmConfiguration realmConfig = new RealmConfiguration.Builder()
                .name("data.realm")
                .schemaVersion(Constants.SCHEMA_VERSION)
                .migration(new Migration())
                .build();

        return Realm.getInstance(realmConfig);
    }
```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: 
Samsung S5 - 6.0.1
Canvas Nitro - 4.4.2

**Comment by beeender** [comment]
Could be the same issue with https://github.com/realm/realm-core/issues/2258

**Comment by Zhuinden** [comment]
There should be no reason for this to happen, so my totally random guess would be that the Realm file is not excluded from the autobackup, which means there is a chance that open Realm is backed up then restored, which causes corruption.

Just a super random guess though. Most issues I know of should have been fixed by the Core in Realm-Java 4.3.1....

**Comment by thorbenprimke** [comment]
@Zhuinden - We are seeing the same exception - is the best solution when we encounter this error to delete the Realm file and create a new one?

**Comment by cmelchior** [comment]
Currently yes. We have not been able to reproduce this yet, so it is still unclear if this is a bug in Realm or something outside Realm.

**Comment by cmelchior** [comment]
Of particular interest is knowing which devices this happens on.

**Comment by Zhuinden** [comment]
> - is the best solution when we encounter this error to delete the Realm file and create a new one?

I have a fail-safe that does that, yes ¯\\_(ツ)_/¯

**Comment by ozv101** [comment]
@cmelchior had this occurrence to 45 users in the last 90 days with around 5K DAU. its very small overall. the devices and OS are all over the place (Samsung S7, Moto G4 Play...)

**Comment by thorbenprimke** [comment]
@cmelchior @Zhuinden 

Thanks for the suggestion to simply delete the Realm in this case. I added the delete fallback for this exception as well as the `incompatible histories` (https://github.com/realm/realm-java/issues/5175) exception. That seems to reasonable solution. I track the `encountered` and `successful` instances and it has about a 50% chance of recovery.

**Comment by clementetb** [comment]
Hi. Version 7 and upward of Realm had a significant updated underlying database engine that improves stability and performance. We recommend updating to version 10. Closing this issue as outdated please reopen if you experience it again.
