### ISSUE TITLE
Realm migration exception

### ISSUE THREAD

**Issue by LPFinch** [realm/realm-java#5630]
Migration error

Old schema
```java
    private String name;
    private String page;
    @PrimaryKey
    private String id;
```
New schema 
```java
    @PrimaryKey
    private String primaryKey;
    private String name;
    private String page;
    private String id;
```
Migration code
```java
    if (oldVersion == 2) {
    RealmObjectSchema infoSchema = schema.get("Info");
            infoSchema
                    .addField("primaryKey", String.class)
                    .removePrimaryKey()
                    .addPrimaryKey("primaryKey");
    oldVersion++;
    }
```
Exception
```java
Caused by java.lang.IllegalArgumentException: Field 'primaryKey' cannot be set as primary key since there are duplicated values for field 'primaryKey' in Class 'Info'.
(/Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsObjectStore.cpp:75)
       at io.realm.internal.OsObjectStore.nativeSetPrimaryKeyForObject(Unknown Source)
       at io.realm.internal.OsObjectStore.setPrimaryKeyForObject(Unknown Source)
       at io.realm.MutableRealmObjectSchema.addPrimaryKey(Unknown Source)
       at com.test.realm.migration.MyMigration.migrate(Unknown Source)
       at io.realm.BaseRealm$6.onMigrationNeeded(Unknown Source)
       at io.realm.internal.SharedRealm.runMigrationCallback(Unknown Source)
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(Unknown Source)
       at io.realm.internal.SharedRealm.(Unknown Source)
       at io.realm.internal.SharedRealm.getInstance(Unknown Source)
       at io.realm.BaseRealm.(Unknown Source)
       at io.realm.BaseRealm.(Unknown Source)
       at io.realm.Realm.(Unknown Source)
       at io.realm.Realm.createInstance(Unknown Source)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(Unknown Source)
       at io.realm.RealmCache.createRealmOrGetFromCache(Unknown Source)
       at io.realm.Realm.getInstance(Unknown Source)
```
#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: many devices

**Comment by LPFinch** [comment]
Update, if realm is empty(no Info in database) crash is gone

**Comment by Zhuinden** [comment]
You can't set the field as a primary key if it contains a value in multiple object. The primary key must be unique this is true even for `null`

**Comment by LPFinch** [comment]
Can you add this to docs?

**Comment by Zhuinden** [comment]
Well technically you can set a field to primary key as long  as it will remain unique.
