### ISSUE TITLE
Crash: **.realm.management/access_control.write.mx

### ISSUE THREAD

**Issue by hmedat2008** [realm/realm-java#5634]
New crash, I don't have any idea about it
```java

Fatal Exception: java.lang.RuntimeException: Unable to start service xx.xx.xx.services.ChatService@2d6104ad with Intent { cmp=xx.xx.xx/.services.ChatService (has extras) }: io.realm.exceptions.RealmFileException: Directory
at path '/data/data/xx.xx.xx/files/config.realm.management/access_control.write.mx' does not exist. (open("/data/data/xx.xx.xx/files/config.realm.management/access_control.write.mx") failed: No such file or directory) (/data/data/xx.xx.xx/files/config.realm.management/access_control.write.mx) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: NOT_FOUND.
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2960)
       at android.app.ActivityThread.access$2100(ActivityThread.java:158)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by io.realm.exceptions.RealmFileException: Directory
at path '/data/data/xx.xx.xx/files/config.realm.management/access_control.write.mx' does not exist. (open("/data/data/xx.xx.xx/files/config.realm.management/access_control.write.mx") failed: No such file or directory) (/data/data/xx.xx.xx/files/config.realm.management/access_control.write.mx) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:172)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:219)
       at io.realm.a.<init>(BaseRealm.java:124)
       at io.realm.a.<init>(BaseRealm.java:93)
       at io.realm.x.<init>(Realm.java:153)
       at io.realm.x.a(Realm.java:424)
       at io.realm.aq.b(RealmCache.java:342)
       at io.realm.aq.a(RealmCache.java:282)
       at io.realm.x.b(Realm.java:353)
       at xx.xx.xx.config.dataSource.ConfigLocalDataSource.a(ConfigLocalDataSource.java:126)
       at xx.xx.xx.config.configModules.ChatConfig.getInstance(ChatConfig.java:62)
       at xx.xx.xx.util.RealmWrapper.f(RealmWrapper.java:1151)
       at xx.xx.xx.services.ChatService.d(ChatService.java:136)
       at xx.xx.xx.services.ChatService.onStartCommand(ChatService.java:85)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2943)
       at android.app.ActivityThread.access$2100(ActivityThread.java:158)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

```

#### Version of Realm and tooling
Realm version(s): 4.2.0

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: 

<img width="1139" alt="screen shot 2017-12-20 at 3 49 37 pm" src="https://user-images.githubusercontent.com/4534097/34210139-75871b9e-e59d-11e7-9226-6551faac3ceb.png">

**Comment by Zhuinden** [comment]
Do you manually delete Realm files or any Realm-related files?

**Comment by hmedat2008** [comment]
for this file?, No

**Comment by tamtom** [comment]
anything?

**Comment by Zhuinden** [comment]
I'm not a Realm member and I don't know why that file could be missing when it should exist.

**Comment by tamtom** [comment]
@beeender we need help for urgent release

**Comment by beeender** [comment]
@tamtom If you have never **delete the realm file manually**, I don't have too much clue about it. 

It looks like your `ChatService` is running in a separated process, correct? Can you reproduce it?

**Comment by hmedat2008** [comment]
@cmelchior

**Comment by Zhuinden** [comment]
Can you guarantee that you don't ever manually delete the Realm file and anything related at some point when Realm could be open?

This cannot be looked into without something that reproduces it...

**Comment by cmelchior** [comment]
Without more information, we cannot really do anything about this. As stated above, most likely something outside Realm is deleting the files. We probably need an example project that reproduces this in order to be able to help.
