### ISSUE TITLE
IllegalStateException: basic_string::_S_create

### ISSUE THREAD

**Issue by ozv101** [realm/realm-java#5639]
#### Goal

> Doesn't crash.

#### Expected Results

> Doesn't crash when Realm is initialized.

#### Actual Results

> Crashes.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.app.view.activity.MainActivity}: java.lang.IllegalStateException: basic_string::_S_create
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2447)
       at android.app.ActivityThread.access$800(ActivityThread.java:163)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5438)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
Caused by java.lang.IllegalStateException: basic_string::_S_create
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:244)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
       at io.realm.Realm.getInstance(Realm.java:353)
       at com.app.di.NetModule.provideDataRealm(NetModule.java:99)
       at com.app.di.NetModule_ProvideDataRealmFactory.get(NetModule_ProvideDataRealmFactory.java:28)
       at com.app.di.NetModule_ProvideDataRealmFactory.get(NetModule_ProvideDataRealmFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.app.di.NetModule_ProvideRealmControllerFactory.get(NetModule_ProvideRealmControllerFactory.java:31)
       at com.app.di.NetModule_ProvideRealmControllerFactory.get(NetModule_ProvideRealmControllerFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.app.di.DaggerNetComponent.injectMainActivity(DaggerNetComponent.java:195)
       at com.app.di.DaggerNetComponent.inject(DaggerNetComponent.java:95)
       at com.app.view.activity.MainActivity.dataInitialization(MainActivity.java:707)
       at com.app.view.activity.MainActivity.onCreate(MainActivity.java:169)
       at android.app.Activity.performCreate(Activity.java:6033)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2310)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2447)
       at android.app.ActivityThread.access$800(ActivityThread.java:163)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5438)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```
#### Steps & Code to Reproduce

> Can't reproduce. The stacktrace isn't helpful but it does occur when Realm is initialized.

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: No

Android Studio version: 3.0.1

Which Android version and device: 
Not widespread but happened 8 times to 3 users:
5.1.1, 6.0.1, 7.0 - Kyocera, LG, Samsung

**Comment by cmelchior** [comment]
That error is from C++ and usually happens because null was parsed instead of a String, but it might be hard to speculate why. It is especially weird if it only happens for very few.

**Comment by cmelchior** [comment]
Outdated. Closing due to inactivity.
