### ISSUE TITLE
SLF4J and Realm 4.+ NoClassDefFoundError OutputEventListenerBackedLoggerContext

### ISSUE THREAD

**Issue by mlostekk** [realm/realm-java#5641]
Hello,

when using the combination of 

> classpath "io.realm:realm-gradle-plugin:4.2.0"

and 

> implementation "org.slf4j:slf4j-api:1.7.25"

with a local copy (_not included via a gradale dependency_)
 of the SLF4J implementation inside my projects (https://github.com/noveogroup/android-logger)

I get the following stracktrace 

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.xxx.app.debug, PID: 27418
                  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/gradle/internal/logging/slf4j/OutputEventListenerBackedLoggerContext;
                      at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:30)
                      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:27)
                      at org.slf4j.impl.StaticLoggerBinder.getSingleton(StaticLoggerBinder.java:0)
                      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
                      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
                      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
                      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
                      at com.xxx.app.application.App.onCreate(App.kt:88)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6186)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext" on path: DexPathList[[zip file "/data/app/com.xxx.app.debug-1/base.apk", zip file "/data/app/com.xxx.app.debug-1/split_lib_directories_apk.apk"],nativeLibraryDirectories=[/data/app/com.xxx.app.debug-1/lib/arm, /data/app/com.xxx.app.debug-1/base.apk!/lib/armeabi-v7a, /data/app/com.xxx.app.debug-1/split_lib_directories_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:30) 
                      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:27) 
                      at org.slf4j.impl.StaticLoggerBinder.getSingleton(StaticLoggerBinder.java:0) 
                      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150) 
                      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124) 
                      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412) 
                      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357) 
                      at com.xxx.app.application.App.onCreate(App.kt:88) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6186) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

This reminds me of this issues that popped up beginning of the year. https://github.com/realm/realm-java/issues/3568 and it happened already before. https://github.com/realm/realm-java/issues/3018

By the way this is also happening if i add a different implementation of "StaticLoggerBinder" to my project. It seems to work fine when realm is removed.

Is there an issue with the gradle realm plugin? Does nobody else use SLF4J?

Thanks in advance

**Comment by mlostekk** [comment]
root project gradle file


```
buildscript {
    ext.kotlin_version = '1.2.10'
    ext.java_version = JavaVersion.VERSION_1_8

    repositories {
        jcenter()
        google()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:3.1.0'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.8.2'
        classpath "io.realm:realm-gradle-plugin:3.+"
        classpath 'io.fabric.tools:gradle:1.24.5'
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.17.0'
    }

}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "http://dl.bintray.com/populov/maven" }
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.fabric.io/public' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {

    // build & sdk version
    minSdkVersion = 18
    sdkVersion = 27
    buildToolsVersion = '27.0.2'

    // library versions
    supportLibrary = '27.0.2'
    supportConstraintLayout = '1.0.2'
    playServices = '11.6.2'

    adjust = '4.11.4'
    blurry = '2.1.1'
    butterknife = '8.8.1'
    branch = '2.14.1'
    constraintLayout = '1.0.2'
    ccp = '2.1.0'
    crashlytics = '2.8.0'
    commonsio = '2.6'
    circleimageview = '2.2.0'
    eventbus = '3.0.0'
    retrofit = '2.3.0'
    fragmentArgs = '3.0.2'
    glide = '3.7.0'
    glidetransform = '2.0.2'
    gson = '2.8.2'
    isoparser = '1.1.22'
    materialdatetimepicker = '3.4.0'
    realmfieldnameshelper = '1.1.1'
    realmadapter = '2.1.1'
    qrgen = '2.3.0'
    qrreaderview = '2.0.3'
    slf4j = '1.7.25'
}

```

app build.gradle

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'
apply plugin: 'com.getkeepsafe.dexcount'
apply plugin: 'com.github.ben-manes.versions'

...
implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':videoframework')
    implementation "com.android.support:percent:$rootProject.ext.supportLibrary"
    implementation "com.android.support:appcompat-v7:$rootProject.ext.supportLibrary"
    implementation "com.android.support:recyclerview-v7:$rootProject.ext.supportLibrary"
    implementation "com.android.support:support-v4:$rootProject.ext.supportLibrary"
    implementation "com.android.support:cardview-v7:$rootProject.ext.supportLibrary"
    implementation "com.android.support:design:$rootProject.ext.supportLibrary"
    implementation "com.android.support:customtabs:$rootProject.ext.supportLibrary"
    implementation "com.android.support.constraint:constraint-layout:$rootProject.ext.supportConstraintLayout"
    implementation "com.google.firebase:firebase-auth:$rootProject.ext.playServices"
    implementation "com.google.firebase:firebase-core:$rootProject.ext.playServices"
    implementation "com.google.firebase:firebase-messaging:$rootProject.ext.playServices"
    implementation "com.google.android.gms:play-services-gcm:$rootProject.ext.playServices"
    /* kotlin */
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    /* Logging */
    implementation "org.slf4j:slf4j-api:$slf4j"
    /* Branch deep links */
    implementation "io.branch.sdk.android:library:$rootProject.ext.branch"
    /* Country code picker */
    implementation "com.hbb20:ccp:$rootProject.ext.ccp"
    /* Event bus */
    implementation "org.greenrobot:eventbus:$rootProject.ext.eventbus"
    /* Round image */
    implementation "de.hdodenhof:circleimageview:$rootProject.ext.circleimageview"
    /* Date Picker */
    implementation "com.wdullaer:materialdatetimepicker:$rootProject.ext.materialdatetimepicker"
    /* Adjust */
    implementation "com.adjust.sdk:adjust-android:$rootProject.ext.adjust"
    /* Glide  */
    compile "com.github.bumptech.glide:glide:$rootProject.ext.glide"
    compile "jp.wasabeef:glide-transformations:$rootProject.ext.glidetransform"
    /* Blur stuff */
    implementation "jp.wasabeef:blurry:$rootProject.ext.blurry"
    /* Butterknife - view binding */
    implementation "com.jakewharton:butterknife:$rootProject.ext.butterknife"
    kapt "com.jakewharton:butterknife-compiler:$rootProject.ext.butterknife"
    /* FragmentArgs - easier fragment generation */
    implementation "com.hannesdorfmann.fragmentargs:annotation:$rootProject.ext.fragmentArgs"
    kapt "com.hannesdorfmann.fragmentargs:processor:$rootProject.ext.fragmentArgs"
    /* Fabric - crash and user tracking */
    implementation("com.crashlytics.sdk.android:crashlytics:$rootProject.ext.crashlytics@aar") { transitive = true }
    /* QR reader */
    implementation("com.dlazaro66.qrcodereaderview:qrcodereaderview:$rootProject.ext.qrreaderview@aar") { transitive = true }
    /* QR */
    implementation "com.github.kenglxn.QRGen:android:$rootProject.ext.qrgen"
    /* Realm adapters */
    implementation "io.realm:android-adapters:$rootProject.ext.realmadapter"
    /* Realm static name generator */
    kapt "dk.ilios:realmfieldnameshelper:$rootProject.ext.realmfieldnameshelper"
    /* Retrofit & GSON */
    implementation "com.squareup.retrofit2:retrofit:$rootProject.ext.retrofit"
    implementation "com.squareup.retrofit2:converter-gson:$rootProject.ext.retrofit"
    /* Apache commons */
    implementation "commons-io:commons-io:$rootProject.ext.commonsio"

    //implementation "com.noveogroup.android:android-logger:1.3.5"
```

**Comment by mlostekk** [comment]
Maybe a quite important thing... When rolling back to

`classpath "io.realm:realm-gradle-plugin:3.+"`

It works fine again!!!

**Comment by mlostekk** [comment]
Nobody using SLF4J and Realm in the same project?

**Comment by nhachicha** [comment]
Hi @mlostekk is it working up to the version `4.1.1` of Realm? it will be helpful to isolate the exact version that introduced the issue.

**Comment by mlostekk** [comment]
Hey @nhachicha i have went down the history and indeed the 4.1.1 is the first one working (traveling back in time). All current releases above 4.1.1 are not working

**Comment by Zhuinden** [comment]
I wonder if this is also because of https://github.com/realm/realm-java/issues/5640#issuecomment-355497076

**Comment by nhachicha** [comment]
@mlostekk thanks for pinpointing the exact version. I doubt it's related to the Gradle plugin issue pointed by @Zhuinden since it's more related to the `RealmTransformer`, but can you give it a try please?

**Comment by mlostekk** [comment]
@nhachicha nope, its still the same error

**Comment by Zhuinden** [comment]
i'm out of ideas but you can try 4.3.2 and see if it does anything

**Comment by mlostekk** [comment]
I will setup a small demo project and let you guys now.

**Comment by mlostekk** [comment]
Here is the demo project.

https://github.com/mlostekk/RealmVsSLF4J

There are 2 ways to fix the problem

1) Remove Realm from gradle scripts
2) Remove LoggerFactory.getLogger calls

Does this help?

**Comment by nhachicha** [comment]
Thanks @mlostekk we'll have a look

**Comment by nhachicha** [comment]
Hi @mlostekk I managed to reproduce your issue, I've confirmed my doubts that this is related to the version of Javassist. For instance, using `3_21_0_ga` instead of `3_22_0_ga` works, I think something changed between this 2 releases that cause the issue 
https://github.com/jboss-javassist/javassist/compare/rel_3_21_0_ga...rel_3_22_0_ga cc @cmelchior 

_I still don't know why the classloader is looking for `org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext` at runtime though_ 

I'll push later a snapshot version that reverts the Javassist version to `3_21_0` so you can test

**Comment by nhachicha** [comment]
@mlostekk I deployed a [4.3.3-SNAPSHOT](https://github.com/realm/realm-java#using-snapshots) so you can test.

**Comment by mlostekk** [comment]
hey @nhachicha this snapshot version fixes the problem

**Comment by nhachicha** [comment]
`4.3.3` has been released

**Comment by mlostekk** [comment]
Can you quickly explain what the reason was?

**Comment by Zhuinden** [comment]
The only thing I see is that in 4.2.0

```
Internal
Updated JavaAssist to 3.22.0-GA.
```

But for whatever reason, this version causes your issue, so it was reverted to `3.21.0-GA`.

The tricky thing here is that the bytecode transformer shouldn't affect anything at runtime, so there is some kind of black magic going on here.

**Comment by mlostekk** [comment]
@Zhuinden thanks!

**Comment by chibash** [comment]
It would be very helpful if you check what will happen when you simply replace javassist.jar from 3.21.0-GA to 3.22.0-GA for SLF4J and Realm.
