### ISSUE TITLE
Latest Realm causes a crash when proguard is disabled

### ISSUE THREAD

**Issue by PaulMuriithi** [realm/realm-java#5645]
#### Goal

- To update Realm plugin to the [latest](https://realm.io/docs/java/latest) and run app even when proguard is disabled.

#### Expected Results

- Change the version in `classpath "io.realm:realm-gradle-plugin:3.7.2"` to `4.3.1` and run the app smoothly even when proguard is disabled.

#### Actual Results

- Immediately the app runs it crashes with the stacktrace:
```
FATAL EXCEPTION: main
Process: [PACKAGE NAME], PID: 18381
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;
 at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
 at io.realm.Realm.init(Realm.java:247)
 at com.loanbee.LoanBeeApplication.onCreate(LoanBeeApplication.java:27)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4994)
 at android.app.ActivityThread.-wrap1(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
 at android.os.Handler.dispatchMessage(Handler.java:111)
 at android.os.Looper.loop(Looper.java:207)
 at android.app.ActivityThread.main(ActivityThread.java:5763)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.getkeepsafe.relinker.ReLinker" on path: DexPathList[[zip file "/data/app/com.loanbee-1/base.apk"],nativeLibraryDirectories=[/data/app/com.loanbee-1/lib/arm64, /data/app/com.loanbee-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60) 
 at io.realm.Realm.init(Realm.java:247) 
 at com.loanbee.LoanBeeApplication.onCreate(LoanBeeApplication.java:27) 
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018) 
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4994) 
 at android.app.ActivityThread.-wrap1(ActivityThread.java) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
 at android.os.Handler.dispatchMessage(Handler.java:111) 
 at android.os.Looper.loop(Looper.java:207) 
 at android.app.ActivityThread.main(ActivityThread.java:5763) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
	Suppressed: java.lang.ClassNotFoundException: com.getkeepsafe.relinker.ReLinker
 at java.lang.Class.classForName(Native Method)
 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 14 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

#### Steps & Code to Reproduce

- Lowering the version to `4.3.0` works as expected
- This is gonna sound weird but `4.3.1` works with Proguard active

#### Version of Realm and tooling
Realm version(s): `4.3.0`

Realm sync feature enabled: `no`

Development environment:
```
Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

Which Android version and device: `Android 6.0`

**Comment by beeender** [comment]
Do you use kotlin in the project?

**Comment by PaulMuriithi** [comment]
Nope, I don't

**Comment by Zhuinden** [comment]
This sounds like something that a clean rebuild might fix?

**Comment by PaulMuriithi** [comment]
Thanks a lot @Zhuinden, tried today with `4.3.3` and it worked, maybe at the time there was some other issue. Closed the issue
