### ISSUE TITLE
RealmRecyclerViewAdapter: IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5679]
I use Realm 4.1.0

My adapter:

```
public class PreviewOfferBaseSortAdapter extends RealmRecyclerViewAdapter {
    protected Context context;

    public PreviewBaseSortAdapter(Context context, @Nullable OrderedRealmCollection data, boolean autoUpdate) {
        super(data, true);
        setHasStableIds(true);
        this.context = context;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater layoutInflater = LayoutInflater.from(parent.getContext());
        ViewDataBinding binding = DataBindingUtil.inflate(layoutInflater, viewType, parent, false);
        setClickHandler(binding);
        return new PreviewBaseViewHolder(binding);
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        Object obj = getItem(position);
        PreviewBaseViewHolder previewViewHolder = (PreviewBaseViewHolder) holder;
        ViewDataBinding viewDataBinding = previewViewHolder.getBinding();
        viewDataBinding.setVariable(BR.item, obj);
        viewDataBinding.executePendingBindings(); //binding must be executed immediately
    }

    @Override
    public int getItemCount() {
        return getData().size();
    }

    @Override
    public int getItemViewType(int position) {
        return getLayoutIdForPosition(position);
    }

    public void onClickImageViewFavorite(Offer offer) {
        boolean isFavorite = offer.isFavorite();
        OfferService.updateFavorite(offer.getId(), !isFavorite);
   }

    private class PreviewBaseViewHolder extends RecyclerView.ViewHolder {
        private final ViewDataBinding binding;

        private PreviewBaseViewHolder(ViewDataBinding binding) {
            super(binding.getRoot());
            this.binding = binding;
        }

        private ViewDataBinding getBinding() {
            return binding;
        }
    }

}


```

In my **OfferService**:

```
public static void updateFavorite(final int offerId, final boolean isFavorite) {
        Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    Offer offer = realm.where(Offer.class).equalTo(Offer.ID, offerId).findFirst();
                    offer.setFavorite(isFavorite);
                }
            });
        } finally {
            realm.close();
        }
}
```

But sometime(not always) I get error:

```
D/com.myproject.android.customer.ui.adapter.PreviewOfferBaseSortAdapter(23564): onClickImageViewFavorite:
D/com.myproject.android.customer.service.OfferService(23564): updateFavorite: offerId = 2, isFavorite = false
D/audio_hw_primary(  198): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
D/com.myproject.android.customer.service.OfferService(23564): updateFavorite: execute: success_change_offer_setFavorite: offer.id = 2, isFavorite = false
D/AndroidRuntime(23564): Shutting down VM
E/AndroidRuntime(23564): FATAL EXCEPTION: main
E/AndroidRuntime(23564): Process: com.myproject.android.customer.debug, PID: 23564
E/AndroidRuntime(23564): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:8 android.support.v7.widget.RecyclerView{7979a01 VFED.V... ......ID 0,0-1080,1302 #7f090183 app:id/sortRecyclerView}, adapter:com.myproject.android.customer.ui.adapter.PreviewOfferBaseSortAdapter@a3f10a6, layout:android.support.v7.widget.GridLayoutManager@a50dae7, context:com.myproject.android.customer.ui.MainActivity@2137ddc
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5628)
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
E/AndroidRuntime(23564):	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
E/AndroidRuntime(23564):	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
E/AndroidRuntime(23564):	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
E/AndroidRuntime(23564):	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:618)
E/AndroidRuntime(23564):	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3644)
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1710)
E/AndroidRuntime(23564):	at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:346)
E/AndroidRuntime(23564):	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
E/AndroidRuntime(23564):	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
E/AndroidRuntime(23564):	at android.view.Choreographer.doFrame(Choreographer.java:603)
E/AndroidRuntime(23564):	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
E/AndroidRuntime(23564):	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(23564):	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(23564):	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(23564):	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime(23564):	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23564):	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(23564):	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
W/ActivityManager(  796):   Force finishing activity com.myproject.android.customer.debug/com.myproject.android.customer.ui.MainActivity
W/Bitmap  (23564): Called reconfigure on a bitmap that is in use! This may cause graphical corruption!
I/OpenGLRenderer(  796): Initialized EGL, version 1.4
I/art	  (  796): Background partial concurrent mark sweep GC freed 9934(575KB) AllocSpace objects, 2(632KB) LOS objects, 29% free, 38MB/54MB, paused 1.094ms total 129.446ms

```

**Comment by KennyGoers** [comment]
This is a bug that has been around and still not fixed, it seems to stern
from the notification not firing but the data/list has changed and this the
eventual result that the recycler view hasn't been notified of that change,
I'm still waiting on a fix

**Comment by lmdic** [comment]
OK. I also will be waiting a fix.

**Comment by lmdic** [comment]
I update my post and put whole code of `PreviewOfferBaseSortAdapter `

**Comment by Zhuinden** [comment]
`setHasStableIds(true); not sure if this should be set to `true` unless you override `getItemId()` and return primary key or so...

**Comment by lmdic** [comment]
Yes, you are right. After I override `getItemId(int index) `the problem is gone.
So now I can remove call `notifyDataSetChanged()
`
Thanks.
