### ISSUE TITLE
monkey step is failing in releases script

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5695]
`newsreader` app crashed after monkey switched on the flight mode

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Nabil/Dev/realm/master/realm-java/examples/build.gradle' line: 69

* What went wrong:
Execution failed for task ':rxJavaExample:monkeyDebug'.
> monkey failed for AppID: io.realm.examples.rxjava
  Std out:      // activityResuming(io.realm.examples.rxjava)
  // CRASH: io.realm.examples.rxjava (pid 7045)
  // Short Msg: android.system.GaiException
  // Long Msg: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
  // Build Label: Android/vbox86p/vbox86p:6.0/MRA58K/buildbot01102000:userdebug/test-keys
  // Build Changelist: eng.buildbot.20160110.195928
  // Build Time: 1452452496000
  // io.reactivex.exceptions.UndeliverableException: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
  //    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
  //    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:604)
  //    at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
  //    at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.checkTerminated(FlowableOnBackpressureLatest.java:159)
  //    at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.drain(FlowableOnBackpressureLatest.java:121)
  //    at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onError(FlowableOnBackpressureLatest.java:75)
  //    at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onError(FlowableFromObservable.java:47)
  //    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
  //    at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:72)
  //    at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:55)
  //    at io.reactivex.Observable.subscribe(Observable.java:10842)
  //    at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
  //    at io.reactivex.Observable.subscribe(Observable.java:10842)
  //    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
  //    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
  //    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
  //    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
  //    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  //    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
  //    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  //    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  //    at java.lang.Thread.run(Thread.java:818)
  // Caused by: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
  //    at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
  //    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
  //    at java.net.InetAddress.getAllByName(InetAddress.java:215)
  //    at okhttp3.Dns$1.lookup(Dns.java:39)
  //    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
  //    at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:137)
  //    at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:82)
  //    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
  //    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
  //    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
  //    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  //    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  //    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  //    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  //    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  //    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
  //    at okhttp3.RealCall.execute(RealCall.java:69)
  //    at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
  //    at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
  //    ... 12 more
  // Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
  //    at libcore.io.Posix.android_getaddrinfo(Native Method)
  //    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
  //    at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
  //    ... 36 more
  //
  ** Monkey aborted due to error.
  Events injected: 152
  ## Network stats: elapsed time=5261ms (0ms mobile, 0ms wifi, 5261ms not connected)
  ** System appears to have crashed at event 152 of 2000 using seed 1516307337136

  Std err:
```

**Comment by Zhuinden** [comment]
If you add your own `onError` then this can be swallowed :D or `retry()` etc
