### ISSUE TITLE
Error converting bytecode to data gradle 2.3.3

### ISSUE THREAD

**Issue by brandoFS** [realm/realm-java#5718]
New to Realm, I just tried adding it to my project and I can't build anymore. getting the following message

Information:Gradle tasks [:app:assembleProductionDebug]
Warning:Ignoring Android API artifact com.google.android:android:4.0.1.2 for productionDebug
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:1 error; aborting
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:1 error; aborting
Error:java.nio.file.NoSuchFileException: /Users/brando/Dev/android/fitplan-android/Fitplan/app/build/intermediates/transforms/dex/production/debug/folders/1000/10/realm-annotations-4.3.3_94f54695bcd4803a0d92dcaac17f372e457b0b41
Information:BUILD FAILED in 27s
Information:5 errors
Information:1 warning
Information:See complete output in console

**This is my Gradle file**

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        classpath 'com.squareup.sqldelight:gradle-plugin:0.3.1'
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath "io.realm:realm-gradle-plugin:4.3.3"
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            url "https://maven.google.com"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**And the other one** 

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.21.7'
        classpath 'eu.f3rog.blade:plugin:2.2.1-beta4'
    }
}

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://dl.bintray.com/intercom/intercom-maven' }
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'com.squareup.sqldelight'
apply plugin: 'blade'
apply plugin: 'realm-android'

android {
    compileSdkVersion 26
    buildToolsVersion "27.0.2"

    defaultConfig {
        applicationId "com.fitplanapp.fitplan"

        minSdkVersion 19
        targetSdkVersion 23
        multiDexEnabled true     
    }
    dexOptions {
        javaMaxHeapSize "4g"
        jumboMode = true
    }
    }
    productFlavors {
        // maintain different versions for internal and external releases, to help clarify which version
        // a user might have.
        staging {
            versionCode 42
            versionName "V2.2.2: staging"
            minSdkVersion 19
           
        }
        production {
            versionCode 53
            versionName "V2.2.2"
        }
    }
    compileOptions{
        sourceCompatibility = 1.7
        targetCompatibility = 1.7
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-fresco.pro'
        }

        debug {
            signingConfig signingConfigs.release
        }
    }
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
    lintOptions {
        abortOnError false
    }
    realm {
        syncEnabled = true;
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'

    //Google Libs
    compile 'com.android.support:multidex:1.0.2'
    androidTestCompile 'com.android.support:multidex:1.0.2'
    androidTestCompile 'com.android.support:multidex-instrumentation:1.0.2'

    compile 'com.android.support:appcompat-v7:26.1.0'
    compile ("com.android.support:support-v4:26.1.0") {
        force = true;
    }
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:percent:26.1.0'

    compile ("com.google.android.gms:play-services-base:11.4.2") {
        force = true;
    }
    compile 'com.google.android.gms:play-services-ads:11.4.2'
    compile 'com.google.firebase:firebase-core:11.4.2'
    compile 'com.google.firebase:firebase-messaging:11.4.2'

    compile 'com.appsflyer:af-android-sdk:4.8.6@aar'
    compile 'com.bartoszlipinski:recyclerviewheader2:2.0.1'
    compile 'com.facebook.fresco:fresco:1.5.0'
    compile 'com.facebook.android:facebook-android-sdk:4.12.1'
    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'

    compile 'com.jakewharton:disklrucache:2.0.2'
    compile 'com.squareup:otto:1.3.8'
    compile 'com.timehop.stickyheadersrecyclerview:library:0.4.3@aar'
    compile 'com.chauthai.swipereveallayout:swipe-reveal-layout:1.4.0'
    compile 'jp.wasabeef:fresco-processors:2.1.0'
    compile 'uk.co.chrisjenx:calligraphy:2.1.0'

    provided 'com.google.auto.value:auto-value:1.1'
    apt 'com.google.auto.value:auto-value:1.1'

    compile 'io.reactivex:rxjava:1.1.0'
    compile 'io.reactivex:rxandroid:1.0.1'
    compile 'com.squareup.sqlbrite:sqlbrite:0.6.3'

    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'

    compile 'com.jakewharton.timber:timber:4.1.2'

    compile 'com.jakewharton:butterknife:8.1.0'
    apt 'com.jakewharton:butterknife-compiler:8.1.0'

    apt 'com.ryanharter.auto.value:auto-value-gson:0.3.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true;
    }

    //Intercom and Intercom for Firebase Push messages
    compile 'io.intercom.android:intercom-sdk-base:4.+'
    compile 'io.intercom.android:intercom-sdk-fcm:4.+'

    testCompile "org.mockito:mockito-core:2.0.97-beta"

    //Branch
    compile 'io.branch.sdk.android:library:2.+'

    //Gson
    compile 'com.google.code.gson:gson:2.7'
}

apply plugin: 'com.google.gms.google-services'

**Console output** 

AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: Dex cannot parse version 52 byte code.\nThis is caused by library dependencies that have been compiled using Java 8 or above.\nIf you are using the \u0027java\u0027 gradle plugin in a library submodule add \ntargetCompatibility \u003d \u00271.7\u0027\nsourceCompatibility \u003d \u00271.7\u0027\nto that submodule\u0027s build.gradle file.","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\njava.lang.RuntimeException: Exception parsing classes\n\tat com.android.dx.command.dexer.Main.processClass(Main.java:781)\n\tat com.android.dx.command.dexer.Main.processFileBytes(Main.java:747)\n\tat com.android.dx.command.dexer.Main.access$1200(Main.java:88)\n\tat com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1689)\n\tat com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)\n\tat com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)\n\tat com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)\n\tat com.android.dx.command.dexer.Main.processOne(Main.java:695)\n\tat com.android.dx.command.dexer.Main.processAllFiles(Main.java:592)\n\tat com.android.dx.command.dexer.Main.runMultiDex(Main.java:376)\n\tat com.android.dx.command.dexer.Main.run(Main.java:290)\n\tat com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)\n\tat com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:174)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)\n\tat com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)\n\tat com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)\n\tat com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)\n\tat com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)\n\tat com.android.dx.command.dexer.Main.parseClass(Main.java:793)\n\tat com.android.dx.command.dexer.Main.access$1600(Main.java:88)\n\tat com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1728)\n\tat com.android.dx.command.dexer.Main.processClass(Main.java:779)\n\t... 16 more\n","tool":"Dex"}
AGPBI: {"kind":"error","text":"1 error; aborting","sources":[{}]}

predex called for /Users/brando/.android/build-cache/ff1bd66502e03f2274255e57118bc562926fe125/output/jars/classes.jar
Hash unknown
predex called for /Users/brando/.android/build-cache/f5d5e5ec086280ad6718ff83d3c1a1a71690d069/output/jars/classes.jar
predex called for /Users/brando/.android/build-cache/8590cc8d1c9e59835c57836f8158e968a9fbcb16/output/jars/classes.jar
:app:transformClassesWithDexForProductionDebug FAILED
:app:transformClassesWithDexForProductionDebug (Thread[Task worker for ':',5,main]) completed. Took 7.27 secs.
:app:buildInfoGeneratorProductionDebug (Thread[Task worker for ':',5,main]) started.
:app:buildInfoGeneratorProductionDebug
Putting task artifact state for task ':app:buildInfoGeneratorProductionDebug' into context took 0.0 secs.
Executing task ':app:buildInfoGeneratorProductionDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
predex called for /Users/brando/.android/build-cache/0cbbb1a581f09205e2ed507bb57ed558a14e6172/output/jars/classes.jar
predex called for /Users/brando/.gradle/caches/modules-2/files-2.1/eu.f3rog.blade/arg/2.2.1-beta4/217a00cdfffe52033f6984bf573dd8d3c60918b1/arg-2.2.1-beta4.jar
predex called for /Users/brando/.android/build-cache/676ef684df2c346008faafb7456c4e9b30a5c599/output/jars/classes.jar
:app:buildInfoGeneratorProductionDebug (Thread[Task worker for ':',5,main]) completed. Took 0.005 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Could not read path '/Users/brando/Dev/android/fitplan-android/Fitplan/app/build/intermediates/transforms/dex/production/debug/folders/1000/10/realm-annotations-4.3.3_94f54695bcd4803a0d92dcaac17f372e457b0b41'.
> /Users/brando/Dev/android/fitplan-android/Fitplan/app/build/intermediates/transforms/dex/production/debug/folders/1000/10/realm-annotations-4.3.3_94f54695bcd4803a0d92dcaac17f372e457b0b41

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.GradleException: Could not read path '/Users/brando/Dev/android/fitplan-android/Fitplan/app/build/intermediates/transforms/dex/production/debug/folders/1000/10/realm-annotations-4.3.3_94f54695bcd4803a0d92dcaac17f372e457b0b41'.
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFileFailed(Jdk7DirectoryWalker.java:100)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFileFailed(Jdk7DirectoryWalker.java:58)
	at java.nio.file.Files.walkFileTree(Files.java:2672)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:58)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:155)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:133)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:118)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.doSnapshot(DefaultFileSystemSnapshotter.java:166)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.access$500(DefaultFileSystemSnapshotter.java:54)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$4.create(DefaultFileSystemSnapshotter.java:148)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$4.create(DefaultFileSystemSnapshotter.java:142)
	at org.gradle.cache.internal.ProducerGuard$StripedProducerGuard.guardByKey(ProducerGuard.java:115)

predex called for /Users/brando/.android/build-cache/015d2144f59147bacfc98c4a579772119cf20b62/output/jars/classes.jar

	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshotDirectoryTree(DefaultFileSystemSnapshotter.java:142)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitDirectoryTree(AbstractFileCollectionSnapshotter.java:95)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:80)
	at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:51)
	at org.gradle.api.internal.changedetection.state.DefaultGenericFileCollectionSnapshotter.snapshot(DefaultGenericFileCollectionSnapshotter.java:36)
	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:89)
	at org.gradle.api.internal.changedetection.rules.OutputFilesTaskStateChanges.snapshotAfterTask(OutputFilesTaskStateChanges.java:60)
	at org.gradle.api.internal.changedetection.rules.CachingTaskStateChanges.snapshotAfterTask(CachingTaskStateChanges.java:84)
	at org.gradle.api.internal.changedetection.rules.SummaryTaskStateChanges.snapshotAfterTask(SummaryTaskStateChanges.java:73)
	at org.gradle.api.internal.changedetection.rules.ErrorHandlingTaskStateChanges.snapshotAfterTask(ErrorHandlingTaskStateChanges.java:36)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.afterTask(DefaultTaskArtifactStateRepository.java:181)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /Users/brando/Dev/android/fitplan-android/Fitplan/app/build/intermediates/transforms/dex/production/debug/folders/1000/10/realm-annotations-4.3.3_94f54695bcd4803a0d92dcaac17f372e457b0b41
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	... 51 more

Hash unknown

* Get more help at https://help.gradle.org

BUILD FAILED in 27s

predex called for /Users/brando/.android/build-cache/5eb6cfb99f2a481ba8045666c615b62ed4f05e28/output/jars/classes.jar
109 actionable tasks: 100 executed, 9 up-to-date
predex called for /Users/brando/.android/build-cache/29c5a9da685551a39a9ba0ec43267dfa5ff68d63/output/jars/classes.jar
predex called for /Users/brando/.android/build-cache/3b258d21f522f12bf880ad0e0c1509a13b08072e/output/jars/classes.jar
PREDEX CACHE HITS:   0
PREDEX CACHE MISSES: 2

#### Version of Realm and tooling
Realm version(s):  4.3.3

Realm sync feature enabled: yes

Android Studio version: Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

Which Android version and device:

**Comment by LeslieKoma** [comment]
I, too, I also encountered the same problem

**Comment by cmelchior** [comment]
Just out of curiosity. Can you try upgrading `classpath 'com.android.tools.build:gradle:2.3.3'` to `classpath 'com.android.tools.build:gradle:3.0.0'`. `2.3.3` should work though, and most I suspect it is a caching problem. So you can try to clean all temporary folders in your project (`git clean -xfd` will work if using git)`

**Comment by brandoFS** [comment]
If I upgrade gradle from 2.3.3 to 3.0.0 right now that causes other compile errors that I've been unable to track down. I think there's an issue in one of the libraries I'm using thats why I've stayed on 2.3.3 for now
