### ISSUE TITLE
Realm decryption fails for some users

### ISSUE THREAD

**Issue by edinaleitner** [realm/realm-java#5721]
#### Expected Results

> no crash

#### Actual Results

>  
```1-26 22:40:28.870 25010 25010 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.woow.talk.activities.WoowApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.woow.talk/files/events.realm': Realm file decryption failed. (Realm file decryption failed) (/data/data/com.woow.talk/files/events.realm) in /Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 101 Kind: ACCESS_ERROR.
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5551)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6274)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path : Realm file decryption failed. (Realm file decryption failed) (/data/data/com.woow.talk/files/events.realm) in /Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 101 Kind: ACCESS_ERROR.
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.internal.SharedRealm.<init>(SharedRealm.java:172)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:219)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:209)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.aa.b(RealmCache.java:319)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.aa.a(RealmCache.java:282)
01-26 22:40:28.870 25010 25010 E AndroidRuntime: 	at io.realm.y.b(Realm.java:353)
01-```

#### Steps & Code to Reproduce

> This happens upon starting the app for some users. 
The encryption key is generated as random byte array, and it is stored in SharedPrefs as a Base64 String. Later on (next user session), this string is retrieved from SharedPrefs, and decoded Base64 into byte array again. - provided code sample below
Is there something wrong with this approach? 
We can loose our SharedPrefs (and the encryptionKey) only upon Clear Data/Uninstall but then i assume that the realm files are deleted also -  and this issue would not occur.
*Note - it is a multi-process app, but it is ensured that Realm runs on a single process (main)
#### Code Sample

```java
SharedPreferences localPrefs = PreferenceManager.getDefaultSharedPreferences(context);

if(localPrefs.contains(ENCRYPTION_KEY)) {
    keyStr = localPrefs.getString(ENCRYPTION_KEY, "");
} else {
    byte[] randomKey = new byte[64];
    new SecureRandom().nextBytes(randomKey);
    keyStr = Base64.encodeToString(randomKey, Base64.DEFAULT);
    localPrefs.edit().putString(ENCRYPTION_KEY, keyStr).commit();
}

evRealmConfig = new RealmConfiguration.Builder()
                .name("filename.realm")
                .encryptionKey(Base64.decode(keyStr, Base64.DEFAULT))
                .schemaVersion(SCHEMA_VERSION)
                .build();

Realm realm = Realm.getInstance(evRealmConfig); //crash occurs here


```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: no

Android Studio version: 3.0.1 (irrelevant)

Which Android version and device: 

Honor 8 (HWFRD) | 236 | 12.0%
HUAWEI GR5 2017 (HWBLN-H) | 104 | 5.3%
Galaxy S8+ (dream2lte) | 89 | 4.5%

**Comment by Zhuinden** [comment]
`WoowApplication.onCreate()` runs per each process

**Comment by edinaleitner** [comment]
Yes, but our second process is rather occasional, and device logs showed that the crash occurred for the main process (while second one was not alive).
Also, we run all realm-related code on a single process.

**Comment by cmelchior** [comment]
Where is the for generating the encryption key being called from? Any chance of race conditions from either other threads or processes?

**Comment by cmelchior** [comment]
Closing due to no response.
