### ISSUE TITLE
Realm Migration reseting device database (no use of deleteRealmIfMigrationNeeded)

### ISSUE THREAD

**Issue by defaultbr** [realm/realm-java#5736]
#### Goal

> Update realm from version 2 to 3 adding new class?

#### Expected Results

> Class biometric added?

#### Actual Results

> RealmMigrationNeededException: Migration is required due to the following errors

#### Code Sample

Init of realm at application class
```
        RealmConfiguration config = new RealmConfiguration.Builder()
                .schemaVersion(3) // Must be bumped when the schema changes
                .migration(new PontotelRealmMigration()) // Migration to run instead of throwing an exception
                .compactOnLaunch()
                .build();
        Realm.setDefaultConfiguration(config);
```

Biometric.kt (new class)

```
@RealmClass
open class Biometric : RealmModel {
    @PrimaryKey
    var id:String = UUID.randomUUID().toString()
    
    @Index
    var emp_oid: String? = null
    
    @Index
    var oid:String? = null

    var biometric:String? = null

    @Index
    var saved:Boolean = false
    
    @Index
    var approved:Boolean = true
}

```

Migration Class:

```
   if (oldVersion == 0) {
            oldVersion++;
        }

        if(oldVersion == 1) {
            RealmObjectSchema imeirecordSchema = schema.get("ImeiRecord");
            if(imeirecordSchema == null) imeirecordSchema = schema.create("ImeiRecord");
            if(imeirecordSchema != null) {
                if (!imeirecordSchema.hasField("logo_toolbar")) {
                    imeirecordSchema.addField("logo_toolbar", String.class);
                }
                if (!imeirecordSchema.hasField("logo_navdrawer")) {
                    imeirecordSchema.addField("logo_navdrawer", String.class);
                }
            }

            oldVersion++;
        }

        if(oldVersion == 2) {
            RealmObjectSchema biometricSchema = schema.get("Biometric");
            if(biometricSchema == null) schema.create("Biometric");
            if(biometricSchema != null) {
                if (!biometricSchema.hasField("id"))
                    biometricSchema.addField("id", String.class, FieldAttribute.PRIMARY_KEY);
                if (!biometricSchema.hasField("emp_oid"))
                    biometricSchema.addField("emp_oid", String.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("oid"))
                    biometricSchema.addField("oid", String.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("biometric"))
                    biometricSchema.addField("biometric", String.class);
                if (!biometricSchema.hasField("saved"))
                    biometricSchema.addField("saved", Boolean.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("approved"))
                    biometricSchema.addField("approved", Boolean.class, FieldAttribute.INDEXED);
            }
            oldVersion++;
        }
```

crash: 

```
02-02 00:56:56.568 27345-27345/lar21.pontotel W/System.err: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Primary Key for class 'Biometric' has been added.
    - Property 'Biometric.id' has been added.
    - Property 'Biometric.emp_oid' has been added.
    - Property 'Biometric.oid' has been added.
    - Property 'Biometric.biometric' has been added.
    - Property 'Biometric.saved' has been added.
    - Property 'Biometric.approved' has been added.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
        at io.realm.BaseRealm.<init>(BaseRealm.java:124)
        at io.realm.BaseRealm.<init>(BaseRealm.java:93)
        at io.realm.Realm.<init>(Realm.java:153)
        at io.realm.Realm.createInstance(Realm.java:424)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
        at io.realm.Realm.getDefaultInstance(Realm.java:332)
02-02 00:56:56.569 27345-27345/lar21.pontotel W/System.err:     at lar21.pontotel.Database.OldSugarDbImplementation.getImeiRecord(OldSugarDbImplementation.kt:766)
```

The OldSugarDbImplementation.kt:76 -> `realm = Realm.getDefaultInstance()`

#### Version of Realm and tooling
Realm version(s):  4.3.1 

Realm sync feature enabled: no

Android Studio version: 3.1 beta 1

Which Android version and device: Android M - Moto G4 Plus

**Comment by Zhuinden** [comment]
Can you guarantee that you're using the RealmConfiguration where the migration is actually specified?

Sometimes people use the one set up by Realm.init() without realizing it

**Comment by cmelchior** [comment]
This code here is wrong, `biometricSchema` is always `null` in the last check. Also shouldn't it be 

```
        if(oldVersion == 2) {
            RealmObjectSchema biometricSchema = schema.get("Biometric");
            if(biometricSchema == null) schema.create("Biometric");
            if(biometricSchema != null) {
                if (!biometricSchema.hasField("id"))
                    biometricSchema.addField("id", String.class, FieldAttribute.PRIMARY_KEY);
                if (!biometricSchema.hasField("emp_oid"))
                    biometricSchema.addField("emp_oid", String.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("oid"))
                    biometricSchema.addField("oid", String.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("biometric"))
                    biometricSchema.addField("biometric", String.class);
                if (!biometricSchema.hasField("saved"))
                    biometricSchema.addField("saved", Boolean.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("approved"))
                    biometricSchema.addField("approved", Boolean.class, FieldAttribute.INDEXED);
            }
            oldVersion++;
        }
```
It should be:

```
        if(oldVersion == 2) {
            RealmObjectSchema biometricSchema = schema.get("Biometric");
            if(biometricSchema == null) {
               biometricSchema = schema.create("Biometric"); 
            }
            if(biometricSchema != null) {
                if (!biometricSchema.hasField("id"))
                    biometricSchema.addField("id", String.class, FieldAttribute.PRIMARY_KEY);
                if (!biometricSchema.hasField("emp_oid"))
                    biometricSchema.addField("emp_oid", String.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("oid"))
                    biometricSchema.addField("oid", String.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("biometric"))
                    biometricSchema.addField("biometric", String.class);
                if (!biometricSchema.hasField("saved"))
                    biometricSchema.addField("saved", Boolean.class, FieldAttribute.INDEXED);
                if (!biometricSchema.hasField("approved"))
                    biometricSchema.addField("approved", Boolean.class, FieldAttribute.INDEXED);
            }
            oldVersion++;
        }
```

Having all of those safety `if`'s should also not be needed if it is a new classes added , so this should work as well. Your numbers look odd as well. I would have assumed the class was added in version 3, not 2?

```
        if(oldVersion == 3) {
            schema.create("Biometric")
                   .addField("id", String.class, FieldAttribute.PRIMARY_KEY);
                   .addField("emp_oid", String.class, FieldAttribute.INDEXED);
                   .addField("oid", String.class, FieldAttribute.INDEXED);
                   .addField("biometric", String.class);
                   .addField("saved", Boolean.class, FieldAttribute.INDEXED);
                   .addField("approved", Boolean.class, FieldAttribute.INDEXED);
            oldVersion++;
        }
```

**Comment by defaultbr** [comment]
Thanks @cmelchior 


found the error(s)

1) One module from dagger was using Realm

initRealm
initDaggerModules
setRealmMigration <--  placed it above initDagger


2) Migration numbers: At the end of migration, the last migrationNumber+1 should match the expected
