### ISSUE TITLE
BadVersionException when clear application Data

### ISSUE THREAD

**Issue by alvaromarco** [realm/realm-java#5744]
Hello guys, 

I have an app with Realm with a logout button, when click logout button clear cacheDir about app directory, remove all RealModels in my app correctly and redirect to other activity. Then I access to my app through magiclink by email, and when return to my app crash with BadVersionException. Is important to know that my app is in background when do logout and open magiclink. I don't have any problems if after do logout, kill the app and access through magiclink.
I think the bug is because the app is in background and not killed. It can be that?

#### Code 

```java
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
Caused by: io.realm.internal.async.BadVersionException: std::exception in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 251
at io.realm.internal.OsResults.nativeStartListening(Native Method)
at io.realm.internal.OsResults.addListener(OsResults.java:401)
at io.realm.internal.OsResults.addListener(OsResults.java:408)
at io.realm.RealmResults.addChangeListener(RealmResults.java:175)                                                                 

```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes/no

Android Studio version: 3.0.1

Which Android version and device: Android 7

**Comment by Zhuinden** [comment]
Sounds like you delete a Realm file manually while it is actually open, and you run an asynchronous query which doesn't really like having the open Realm being deleted from under it?

How do you delete the Realm? Or how do you clear it?

**Comment by cmelchior** [comment]
Closing due to no response.
