### ISSUE TITLE
Migration failed when add Integer Field

### ISSUE THREAD

**Issue by banbara23** [realm/realm-java#5750]
#### Goal
Add Integer Field to Model Class and Migration Class, Migration success

#### Expected Results
Migration success

#### Actual Results
Happen RealmMigrationNeededException
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.k_ikemura.realm_sample/com.example.k_ikemura.realm_sample.MainActivity}: io.realm.exceptions.RealmMigrationNeededException: Field 'couponId' does not support null values in the existing Realm file. Either set @Required, use the primitive type for field 'couponId' or migrate using RealmObjectSchema.setNullable().
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: io.realm.exceptions.RealmMigrationNeededException: Field 'couponId' does not support null values in the existing Realm file. Either set @Required, use the primitive type for field 'couponId' or migrate using RealmObjectSchema.setNullable().
    at io.realm.CouponListItemRealmProxy.validateTable(CouponListItemRealmProxy.java:743)
    at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:51)
    at io.realm.Realm.initializeRealm(Realm.java:480)
    at io.realm.Realm.createAndValidateFromCache(Realm.java:423)
    at io.realm.Realm.createInstance(Realm.java:387)
    at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:346)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
    at io.realm.Realm.getInstance(Realm.java:301)
    at com.example.k_ikemura.realm_sample.MainActivity.initRealm(MainActivity.java:28)
    at com.example.k_ikemura.realm_sample.MainActivity.onCreate(MainActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271) 
    at android.app.ActivityThread.access$800(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5146) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566) 
    at dalvik.system.NativeStart.main(Native Method) 
```

#### Steps & Code to Reproduce

1. build [this Repository branch v0](https://github.com/banbara23/RealmMigrationSample/tree/v0)
2. build [this Repository branch v1_check](https://github.com/banbara23/RealmMigrationSample/tree/v1_check)
3. App Launch
4. Crash app

#### Code Sample

My sample code link ([Github Repository](https://github.com/banbara23/RealmMigrationSample/tree/v1_check))
- [Migration](https://github.com/banbara23/RealmMigrationSample/blob/v1_check/app/src/main/java/com/example/k_ikemura/realm_sample/MyRealmMigration.java)
```java
class MyRealmMigration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        RealmObjectSchema listSchema = realm.getSchema().get("CouponListItem");
        if (oldVersion == 0) {
            RealmObjectSchema categorySchema = null;
            if (!schema.contains("CouponCategory")) {
                categorySchema
                        = schema.create("CouponCategory")
                        .addField("categoryId", Integer.class, FieldAttribute.REQUIRED);
            }
            if (!listSchema.hasField("couponId")) {
                listSchema.addField("couponId", Integer.class, FieldAttribute.REQUIRED);
                if (listSchema.hasField("id")) {
                    listSchema.transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject obj) {
                            if (TextUtils.isEmpty(obj.getString("id"))) {
                                obj.set("couponId", 0);
                            } else {
                                obj.set("couponId", Integer.valueOf(obj.getString("id")));
                            }
                        }
                    });
                }
            }
            if (listSchema.hasField("id")) {
                listSchema.removeField("id");
            }
            if (!listSchema.hasField("shopId")) {
                listSchema.addField("shopId", String.class);
            }
            if (!listSchema.hasField("periodDate")) {
                listSchema.addField("periodDate", String.class);
                if (listSchema.hasField("data")) {
                    listSchema.transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject obj) {
                            obj.set("periodDate", obj.getString("data"));
                        }
                    });
                }
            }
            if (listSchema.hasField("date")) {
                listSchema.removeField("date");
            }
            if (!listSchema.hasField("periodTimeStamp")) {
                listSchema.addField("periodTimeStamp", Long.class, FieldAttribute.REQUIRED);
            }
            if (!listSchema.hasField("startData")) {
                listSchema.addField("startData", String.class);
            }
            if (!listSchema.hasField("startDataTimeStamp")) {
                listSchema.addField("startDataTimeStamp", Long.class, FieldAttribute.REQUIRED);
            }
            if (!listSchema.hasField("couponType")) {
                listSchema.addField("couponType", Integer.class, FieldAttribute.REQUIRED);
            }
            if (!listSchema.hasField("couponCategoryIds")) {
                listSchema.addRealmListField("couponCategoryIds", categorySchema);
            }
            if (!listSchema.hasField("isToshin")) {
                listSchema.addField("isToshin", Integer.class, FieldAttribute.REQUIRED);
            }
        }
    }
}

```
- [Model](https://github.com/banbara23/RealmMigrationSample/blob/v1_check/app/src/main/java/com/example/k_ikemura/realm_sample/CouponListItem.java)
```java
public class CouponListItem extends RealmObject {

    private String shopId;

    private Integer couponId;

    private String name;

    private String thumbnail;

    private Integer type;

    private String periodDate;

    private Long periodTimeStamp;

    private Integer isRead;

    private String shopFloorName;
    private String brandName;

    private String onlineStoreType;
    private String startData;

    private Long startDataTimeStamp;
    private Integer couponType;
    private RealmList<CouponCategory> couponCategoryIds;

    private Boolean isToshin;
}

```
- [RealmConfigration](https://github.com/banbara23/RealmMigrationSample/blob/v1_check/app/src/main/java/com/example/k_ikemura/realm_sample/MainActivity.java#L21)
```java
        RealmConfiguration realmConfiguration
                = new RealmConfiguration.Builder()
                .name("app_cache.realm")
                .schemaVersion(1)
                .migration(new MyRealmMigration())
                .build();
        Realm realm = Realm.getInstance(realmConfiguration);
```
#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Android 4.3.3

**Comment by Zhuinden** [comment]
The error message is quite specific, it says

    listSchema.addField("couponId", Integer.class, FieldAttribute.REQUIRED);

You are adding a REQUIRED field, but in your model code, you have

    private Integer couponId;

which is nullable.

----

So it should be

    @Required
    private Integer couponId;

or
  
    private int couponId;

Just like the error message says.

**Comment by banbara23** [comment]
Thank you @Zhuinden 
I tried below code, but happen RealmMigrationNeededException

### model
```java
public class CouponListItem extends RealmObject {

    private int couponId; // fix
    String id;
```
#### migration
```java
class MyRealmMigration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        if (oldVersion == 0) {
            RealmObjectSchema schema = realm.getSchema().get("CouponListItem");
            schema.addField("couponId", Integer.class);
        }
    }
}
```
Error message
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.k_ikemura.realm_sample/com.example.k_ikemura.realm_sample.MainActivity}: io.realm.exceptions.RealmMigrationNeededException: Field 'couponId' does support null values in the existing Realm file. Use corresponding boxed type for field 'couponId' or migrate using RealmObjectSchema.setNullable().
```

Commit Url
https://github.com/banbara23/RealmMigrationSample/commit/443c6d125c8649fff65cc4a2163f5c1adcdce087
I fix Integer to int, removed REQUIRED.

Why does the same error happen?
Is the realm version old?

**Comment by Zhuinden** [comment]
Okay so you had two options:

1.) make the field nullable by removing `FieldAttributes.REQUIRED`

2.) make the field required by either adding `@Required` or making it into `private int` 

----

Currently you've done both, which makes it so that you are trying to make `int` as `nullable` which also doesn't work.

Do

    private int couponId; // fix

and

    schema.addField("couponId", Integer.class, FieldAttributes.REQUIRED);

**Comment by banbara23** [comment]
Thank you @Zhuinden 

Migration is success!

```java
private String shopId;
```
```java
schema.addField("couponId", Integer.class, FieldAttribute.REQUIRED);
```

**Comment by banbara23** [comment]
This
