### ISSUE TITLE
IllegalStateException after isClosed check 

### ISSUE THREAD

**Issue by anujjpandey** [realm/realm-java#5755]
#### Goal

> Want to commit files on open realm object

#### Expected Results

> When I was checking that realm is closed or not it should return me true if it is close.

#### Actual Results

>  Realm object is returning false when checking it is closed, but while using the same object it is throwing illegal state and message saying that realm object is closed.

#### Steps & Code to Reproduce

> 1. Create realm object.
2. Commit data and close object, but don't assign null to realm object.
3. Now check realm.isClosed.

#### Code Sample
 ```
protected void proceedForCommittedDataDeletion() {
        if (mRealm == null) {
            RemoteLogger.w(TAG, "Can not proceed for delete as Realm is null for " + getName());
            return;
        } else if (mRealm.isClosed()) {
            RemoteLogger.w(TAG, "Can not proceed for delete as realm closed for " + getName());
            return;
        }
       
try {
                        mRealm.executeTransaction(new Realm.Transaction() {
                            @Override
                            public void execute(Realm realm) {
                                
                            }
                        });
                    } catch (Exception e) {
                        AppLoger.e("Exception", "Message " + e.getMessage() + "\n" + RemoteLogger.getStackTrace(e));
                        e.printStackTrace();
                        RemoteLogger.e(TAG, "Error while deleting committed data " + e.getMessage(), e);
                    }
        
    }
```
```
Error while deleting committed data This Realm instance has already been closed, making it unusable., java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
	at io.realm.BaseRealm.checkIfValid(BaseRealm.java:421)
	at io.realm.BaseRealm.isInTransaction(BaseRealm.java:190)
	at io.realm.Realm.isInTransaction(Realm.java:135)
	at io.realm.Realm.executeTransaction(Realm.java:1397)
	at com.automotive.tracker.threads.BaseRealmThread.proceedForCommittedDataDeletion(BaseRealmThread.java:621)
	at com.automotive.tracker.threads.RealmDateSpecifiedThread.doTask(RealmDateSpecifiedThread.java:43)
	at com.automotive.tracker.threads.BaseRealmThread.onRepeatInterval(BaseRealmThread.java:250)
	at com.automotive.tracker.threads.BaseRealmThread.mediaSync(BaseRealmThread.java:205)
	at com.automotive.tracker.threads.RealmDateSpecifiedThread.onStartMediaSync(RealmDateSpecifiedThread.java:95)
	at com.automotive.tracker.threads.MessengerThread.onAction(MessengerThread.java:128)
	at com.automotive.tracker.threads.MessengerThread$MessengerThreadHandler.handleMessage(MessengerThread.java:173)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at com.automotive.tracker.threads.MessengerThread.run(MessengerThread.java:65)
```

#### Version of Realm and tooling
Realm version(s): 4.3.4

Realm sync feature enabled: yes

Android Studio version: 3.0.1

Which Android version and device: 19

**Comment by Zhuinden** [comment]
That's quite odd in the sense that that should be impossible.

**Comment by anujjpandey** [comment]
@Zhuinden it is happening, My operation is happening in synchronize block of a separate thread and there is no shared resources and objects, which means there is no possibility where realm object can close in between next line (# area in below code):

```
else if (mRealm.isClosed()) {
           RemoteLogger.w(TAG, "Can not proceed for delete as realm closed for " + getName());
           return;
       }
      ########################
                       mRealm.executeTransaction
```

And this is being frequently, as this block of code take place after a sleep of 5 second, which means close is returning false but accessing it is throwing exception.

I also checked your java code and I think it is from native.

**Comment by cmelchior** [comment]
Hi @anujjpandey If you are able to reproduce this in a unit test or in a sample project I'll be happy to take a look, but this something we already have covered in unit tests, so I strongly suspect a problem somewhere in your code.

**Comment by anujjpandey** [comment]
@cmelchior I'm getting it regularly. let me try if I can provide you some unit test sample

**Comment by cmelchior** [comment]
Closing due to no activity. Feel free to reopen if you are able to reproduce it somehow.
