### ISSUE TITLE
 Realm ver.3.7.2 , try to connect: java.lang.NullPointerException

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5768]
In my android Realm application I use android ver.**3.7.2**

Here snippent that try to login from my android app to  my realm object server:

```
private void loginToRealm(final String userName, String password) {
        if (BuildConfig.DEBUG)
            Log.d(TAG, "loginToRealm_userName = " + userName);

        // callback of SyncUser.loginAsync()
        SyncUser.Callback callback = new SyncUser.Callback() {
            @Override
            public void onSuccess(SyncUser user) {
                userStore.put(user);
                initRealmConfigs(user);
                loadOrganization();
            }

            @Override
            public void onError(ObjectServerError error) {
              if (BuildConfig.DEBUG)
                    Log.e(TAG, "loginToRealm: onError: ", error);
            }
        };

        SyncCredentials syncCredentials = SyncCredentials.usernamePassword(userName, password, false);
        SyncUser.loginAsync(syncCredentials, BuildConfig.REALM_AUTH_URL, callback);
}
```
But I get error:

```
loginToRealm: ---> Try_to_login by: admin@mylogin.biz to address: http:///1xx.xx.202.xx:8080/auth ...
D/REALM_JAVA( 3740): Network request (authenticate): http:///1xx.xx.xxx.65:8080/auth
 loginToRealm: onError: 
 UNKNOWN(-1)
 java.lang.NullPointerException
	at io.realm.SyncUser.<init>(SyncUser.java:102)
	at io.realm.SyncUser.login(SyncUser.java:198)
	at io.realm.SyncUser$1.run(SyncUser.java:229)
	at io.realm.SyncUser$Request$1.run(SyncUser.java:810)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
 
	at io.realm.SyncUser.login(SyncUser.java:208)
	at io.realm.SyncUser$1.run(SyncUser.java:229)
	at io.realm.SyncUser$Request$1.run(SyncUser.java:810)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
 loginToRealm: onError: result errorMsg = UNKNOWN(-1)
 java.lang.NullPointerException
	at io.realm.SyncUser.<init>(SyncUser.java:102)
	at io.realm.SyncUser.login(SyncUser.java:198)
	at io.realm.SyncUser$1.run(SyncUser.java:229)
	at io.realm.SyncUser$Request$1.run(SyncUser.java:810)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by Zhuinden** [comment]
Is it a login against ROS 1.x?

**Comment by lmdic** [comment]
Realm Object Serverv1.8.3

**Comment by Zhuinden** [comment]
It says

``` java
    SyncUser(Token refreshToken, URL authenticationUrl) {
        this.identity = refreshToken.identity(); // <-- crash
```

It's odd, it's as if the server didn't send a token.

I have no idea how this works, and Realm is working on ROS 3 as of late, so I wonder if @nhachicha knows what could be going wrong here.

**Comment by cmelchior** [comment]
Hi @lmdic 
Can you reproduce this consistently? or does it only happen sometimes?

**Comment by nhachicha** [comment]
@lmdic it will also be helpful if you can include the server log.
Do you also experience the issue when upgrading to ROS [2.x](https://docs.realm.io/platform/getting-started/install-realm-object-server/manual-install)?

**Comment by lmdic** [comment]
I found the solution. After reset ROS the problem is gone.
