### ISSUE TITLE
`deleteAll` crashes under Partial Sync

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5780]
```
io.realm.exceptions.RealmException: '__ResultSets' doesn't exist in current schema.
at io.realm.internal.ColumnIndices.getColumnInfo(ColumnIndices.java:112)
at io.realm.RealmSchema.getColumnInfo(RealmSchema.java:250)
at io.realm.ImmutableRealmSchema.get(ImmutableRealmSchema.java:43)
at io.realm.RealmSchema.getAll(RealmSchema.java:88)
at io.realm.BaseRealm.deleteAll(BaseRealm.java:615)
at io.realm.Realm.deleteAll(Realm.java:138)
at io.realm.objectserver.PartialSyncTests.lambda$clearTable$8$PartialSyncTests(PartialSyncTests.java:289)
at io.realm.objectserver.PartialSyncTests$$Lambda$8.execute(Unknown Source)
at io.realm.Realm.executeTransaction(Realm.java:1397)
at io.realm.objectserver.PartialSyncTests.clearTable(PartialSyncTests.java:288)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at io.realm.rule.RunInLooperThread$TestThread.run(RunInLooperThread.java:495)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by cmelchior** [comment]
Fixed by #5782
