### ISSUE TITLE
Out of memory crash on app launch

### ISSUE THREAD

**Issue by nkanellopoulos** [realm/realm-java#5783]
After inserting about 5 thousand objects into a realm, my app crashes upon the **next launch** while calling `Realm.getDefaultInstance()`

I tried to call `compactOnLauch()` in the default configuration, as suggested in #4998, but it did not help.

     // Init Realm
    Realm.init(this)

     val config = RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .compactOnLaunch()
                .build()
     Realm.setDefaultConfiguration(config)

Things work fine for, say, 1600 objects.

Here is my stacktrace

02-28 15:13:49.699 29535-29535/? E/REALM_JNI: jni: ThrowingException 5, mmap() failed: Out of memory size: 1342177280 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101, .
02-28 15:13:49.699 29535-29535/? E/REALM_JNI: Exception has been thrown: Unrecoverable error. mmap() failed: Out of memory size: 1342177280 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
02-28 15:13:49.701 29535-29535/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: fieldobservations, PID: 29535
                                                   io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 1342177280 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
                                                       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
                                                       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
                                                       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
                                                       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:244)
                                                       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
                                                       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
                                                       at io.realm.Realm.getDefaultInstance(Realm.java:332)
                                                       at gr.neuropublic.fieldobservations.ui.MainActivity.onCreate(MainActivity.kt:66)
                                                       at android.app.Activity.performCreate(Activity.java:5990)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

#### Version of Realm and tooling
Realm version(s): 4.3.2

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: 5.1, 6, Simulator, Nexus 4

**Comment by Zhuinden** [comment]
5000 items?

How did you end up with a Realm file that is 1.25 GB in size, then?

**Comment by nkanellopoulos** [comment]
I cannot answer this. 
You mean 1342177280 is the realm file size?
This is impressive...

 Any hints for determining what goes wrong?

**Comment by Zhuinden** [comment]
Well, not without the data inserting code

**Comment by nkanellopoulos** [comment]
It seems the error was that I had `realm.executeTransaction()` inside a for-loop, instead of vice-versa.
Thanks for your hint above!

Shall I close this issue?

**Comment by Zhuinden** [comment]
Yeah, I guess it's solved.

**Comment by faridaub** [comment]
@Zhuinden 
Could you please share how did you solved this issue? 

Caused by io.realm.exceptions.RealmError
Unrecoverable error. mmap() failed: Out of memory size: 50331648 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

Caused by io.realm.exceptions.RealmFileException
Unable to open a realm at path '/data/data/../files/realm-file.realm': Bad Realm file header (#3). (Bad Realm file header (#3)) (/data/data//files/realm-file.realm) in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
