### ISSUE TITLE
Crash Caused by io.realm.exceptions.RealmError: Unrecoverable error. Read-only file system

### ISSUE THREAD

**Issue by aleonardoleitao** [realm/realm-java#5790]
I have this exception in Fabric Crashlytics:

The crash occurs in this line:
```
Application
public class MyApplication extends MultiDexApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
    }
}
  ```

Caused by io.realm.exceptions.RealmError: Unrecoverable error. Read-only file system in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_SyncManager.cpp line 109
       at io.realm.SyncManager.nativeInitializeSyncManager(SyncManager.java)
       at io.realm.ObjectServer.init(ObjectServer.java:67)
       at java.lang.reflect.Method.invoke(Method.java)
       at io.realm.internal.SyncObjectServerFacade.init(SyncObjectServerFacade.java:56)
       at io.realm.Realm.init(Realm.java:249)
       at br.tv.horizonte.android.premierefc.PremiereApplication.onCreate(PremiereApplication.java:54)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4991)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

#### Goal

> What do you want to achieve?
I don't know reproduce this exception, I get Exception, on Fabric Crashlytics.
#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce
I don't know reproduce this exception, I get Exception, on Fabric Crashlytics.
> Describe your current debugging efforts.
I don't know reproduce this exception, I get Exception, on Fabric Crashlytics.

#### Version of Realm and tooling
Realm version(s): ?
4.3.3
Realm sync feature enabled: yes/no
yes

Android Studio version: ?
3.0.1

Which Android version and device: ?
Android 6 - Lenovo VIBE X3 Lite100%
Android 6 - Moto E with 4G LTE (2nd Gen)

**Comment by cmelchior** [comment]
Hi @aleonardoleitao 
Sorry for the late reply. Is it something you are seeing consistently or only a few devices?
The exception message is pretty clear, but how the file system is in that state is hard to say. It could possibly be some device management system kicking in, but without more information that is hard to tell.

**Comment by anujjpandey11** [comment]
@cmelchior I'm facing it consistently ... please tell me what information you require to fix this

**Comment by Zhuinden** [comment]
If you use external storage, you might want to check if it's mounted and accessible: https://stackoverflow.com/a/47464560/2413303

**Comment by clementetb** [comment]
Closing due to inactivity. Please comment in case you get more information and the issue still persists

**Comment by Zhuinden** [comment]
But it's not closed tho :smirk:
