### ISSUE TITLE
IllegalStateException: downloadAllServerChanges() cannot be called from the main thread

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5793]
ROS ver.**1.8.3**
Android realm client: **3.7.2**

In my android app:

```
public class MainApp extends MultiDexApplication {
...
public void initRealm() {
   initRealmConfigs(user);
   loadOrganization();
}

 private void initRealmConfigs(SyncUser syncUser) {
        SyncConfiguration syncConfiguration = getSyncConfiguration(syncUser, BuildConfig.REALM_URL);
        Realm.setDefaultConfiguration(syncConfiguration);
    }

    private SyncConfiguration getSyncConfiguration(SyncUser syncUser, String realmURL) {
        SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(syncUser, realmURL)
                .trustedRootCA(ROOT_CA_PEM)
                .waitForInitialRemoteData()
                .build();
        return syncConfiguration;
}

  private void loadOrganization() {
        Realm.getInstanceAsync(Realm.getDefaultConfiguration(), new Realm.Callback() {
            @Override
            public void onSuccess(Realm realm) {
                MainApp.setLoadedOrganizaionsAtLeastOnce();
            }

            @Override
            public void onError(Throwable throwable) {
            }
        });
    }
}
```

As you can see the method `loadOrganization() `is call AFTER `initRealmConfigs(user).
`Here my fragment code:

```
public class OrganizationsFragment extends Fragment {

   // called after the views binding has happened.
    @AfterViews
    void init() {
        realm = Realm.getDefaultInstance(); // THROW HERE EXCEPTION
        organizationsRealmResults = realm.where(Organization.class)
                .equalTo(Organization.READY, true)
                .findAllSorted(Organization.NAME);
 }
}

```
And as result it I success connect to realm (ROS 1.8.3) and success download all orgazations the my fragment `OrganizationsFragment `success show all organizations.

Here realm config after success login to ROS:

 ```
initRealm_CURRENT_LOGIN_USER: {UserId: 5f4602111111111111111111bdee5559, AuthUrl: https://myhost.com/auth}
 init_HAS_CURRENT_LOGIN_USER: ---> initRealmConfigs() && loadOrganization()
 initRealmConfigs: START, syncUser:
 {UserId: 5f4602f8a2333333333333333339, AuthUrl: https://myhost.com/auth}
 REALM_URL = realms:///myhost.com/my_realm
  ---> createSyncConfiguration()
 getSyncConfiguration: Success get syncConfiguration:
 syncConfiguration:
 
 realmDirectory: /data/data/com.myproject/files/realm-object-server/5f4602f8a2333333333333333339/my_realm
 realmFileName : my_realm
 canonicalPath: /data/data/com.myproject/files/realm-object-server/5f4602f8a2333333333333333339/my_realm/my_realm
 key: [length: 0]
 schemaVersion: 0
 migration: null
 deleteRealmIfMigrationNeeded: false
 durability: FULL
 schemaMediator: io.realm.DefaultRealmModuleMediator@8cdd22e0
 readOnly: false
 compactOnLaunch: null
 serverUrl: realms://myhost.com/my_realm
 user: {UserId: 5f4602f8a2333333333333333339, AuthUrl: https://myhost.com/auth}
 errorHandler: io.realm.SyncManager$1@4220f988
 deleteRealmOnLogout: false
 waitForInitialRemoteData: true
```
 

Nice.

But if I get error when try to download all organizations from ROS.

```
E/REALM_SYNC( 2939): Connection[1]: SSL handshake failed: certificate verify failed
E/REALM_JAVA( 2939): java.lang.IllegalArgumentException: Unknown error code: 117
E/REALM_JAVA( 2939):	at io.realm.ErrorCode.fromInt(ErrorCode.java:190)
E/REALM_JAVA( 2939):	at io.realm.SyncSession.notifySessionError(SyncSession.java:162)
E/REALM_JAVA( 2939):	at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:299)
E/REALM_JAVA( 2939):	at dalvik.system.NativeStart.run(Native Method)
E/REALM_JAVA( 2939): UNKNOWN(-1)
E/REALM_JAVA( 2939): Internal error (125): Operation Canceled
E/REALM_JAVA( 2939):	at io.realm.SyncSession$WaitForSessionWrapper.throwExceptionIfNeeded(SyncSession.java:695)
E/REALM_JAVA( 2939):	at io.realm.SyncSession.waitForChanges(SyncSession.java:399)
E/REALM_JAVA( 2939):	at io.realm.SyncSession.downloadAllServerChanges(SyncSession.java:336)
E/REALM_JAVA( 2939):	at io.realm.internal.SyncObjectServerFacade.downloadRemoteChanges(SyncObjectServerFacade.java:164)
E/REALM_JAVA( 2939):	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:302)
E/REALM_JAVA( 2939):	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
E/REALM_JAVA( 2939):	at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
E/REALM_JAVA( 2939):	at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
E/REALM_JAVA( 2939):	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
E/REALM_JAVA( 2939):	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/REALM_JAVA( 2939):	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/REALM_JAVA( 2939):	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/REALM_JAVA( 2939):	at java.lang.Thread.run(Thread.java:841)
```

And when I go to my framgent I get the next error in method:

`realm = Realm.getDefaultInstance(); `

```
 FATAL EXCEPTION: main
 java.lang.IllegalStateException: downloadAllServerChanges() cannot be called from the main thread.
	at io.realm.SyncSession.checkIfNotOnMainThread(SyncSession.java:410)
	at io.realm.SyncSession.downloadAllServerChanges(SyncSession.java:327)
	at io.realm.internal.SyncObjectServerFacade.downloadRemoteChanges(SyncObjectServerFacade.java:164)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:302)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
	at io.realm.Realm.getDefaultInstance(Realm.java:325)
	at com.myproject.OrganizationsFragment.init(OrganizationsFragment.java:94)
	at com.myproject.OrganizationsFragment_.onViewChanged(OrganizationsFragment_.java:77)
	at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
	at com.myproject.OrganizationsFragment_.onViewCreated(OrganizationsFragment_.java:65)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by cmelchior** [comment]
It is because you are have defined `waitForInitialRemoteData` in your `SyncConfiguration`. It will call that method internally. This should also be documented in the Javadoc for `waitForInitialRemoteData()`. You should use `getInstanceAsync` instead in that case.

**Comment by lmdic** [comment]
OK, I change:

```
 Realm.getInstanceAsync(Realm.getDefaultConfiguration(), new Realm.Callback() {
            @Override
            public void onSuccess(Realm realm) {
                organizationsRealmResults = realm.where(Organization.class)
                        .equalTo(Organization.READY, true)
                        .findAllSorted(Organization.NAME);

            }
	    });


```But now I get another error:

```
D/MyFragment(13692): init: 
V/REALM_JNI(13692):  --> Java_io_realm_internal_OsRealmConfig_nativeCreate
V/REALM_JNI(13692):  --> Java_io_realm_internal_OsRealmConfig_nativeSetInMemory -1624780032
V/REALM_JNI(13692):  --> Java_io_realm_internal_OsRealmConfig_nativeEnableChangeNotification -1624780032
V/REALM_JNI(13692):  --> Java_io_realm_internal_OsRealmConfig_nativeSetSchemaConfig -1624780032
V/REALM_JNI(13692):  --> Java_io_realm_internal_OsRealmConfig_nativeCreateAndSetSyncConfig -1624780032
V/REALM_JNI(13692):  --> Java_io_realm_internal_OsRealmConfig_nativeSetSyncConfigSslSettings -1624780032
V/REALM_JNI(13692):  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm -1624780032
V/REALM_JNI(13692):  --> Java_io_realm_internal_SharedRealm_nativeGetSchemaInfo -1615559024
V/REALM_JNI(13692):  --> Java_io_realm_internal_SharedRealm_nativeSetAutoRefresh -1615559024
V/REALM_JNI(13692):  --> Java_io_realm_SyncSession_nativeWaitForDownloadCompletion
V/REALM_JNI(13692):  --> Java_io_realm_internal_SharedRealm_nativeCloseSharedRealm -1615559024
E/REALM_JAVA(13692): UNKNOWN(-1)
E/REALM_JAVA(13692): It was not possible to download all remote changes. Has the SyncClient been started?
E/REALM_JAVA(13692):	at io.realm.SyncSession.waitForChanges(SyncSession.java:391)
E/REALM_JAVA(13692):	at io.realm.SyncSession.downloadAllServerChanges(SyncSession.java:336)
E/REALM_JAVA(13692):	at io.realm.internal.SyncObjectServerFacade.downloadRemoteChanges(SyncObjectServerFacade.java:164)
E/REALM_JAVA(13692):	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:302)
E/REALM_JAVA(13692):	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
E/REALM_JAVA(13692):	at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
E/REALM_JAVA(13692):	at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
E/REALM_JAVA(13692):	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
E/REALM_JAVA(13692):	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/REALM_JAVA(13692):	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/REALM_JAVA(13692):	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/REALM_JAVA(13692):	at java.lang.Thread.run(Thread.java:818)
E/REALM_JAVA(13692): 

```

**Comment by cmelchior** [comment]
Hi @lmdic I cannot reproduce this. Are you able to provide an example project that shows this behavior?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if you are still seeing this.
