### ISSUE TITLE
Realm No such file or directory crash 

### ISSUE THREAD

**Issue by johnryan** [realm/realm-java#5828]
#### Expected Results
App shouldn't crash

#### Actual Results
```
io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/com.truly.truly/files/default.realm) in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
	at io.realm.BaseRealm.<init>(BaseRealm.java:124)
	at io.realm.BaseRealm.<init>(BaseRealm.java:124)
	at io.realm.BaseRealm.<init>(BaseRealm.java:93)
	at io.realm.BaseRealm.<init>(BaseRealm.java:93)
	at io.realm.BaseRealm.<init>(BaseRealm.java:93)
	at io.realm.Realm.<init>(Realm.java:153)
	at io.realm.Realm.createInstance(Realm.java:424)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
	at io.realm.Realm.getDefaultInstance(Realm.java:332)
	at com.truly.sdk.models.TWVoicemail.onDownloaded(TWVoicemail.java:126)
	at com.truly.truly.util.VoicemailDownloadQueue$VoiceMailTask.onPostExecute(VoicemailDownloadQueue.java:132)
	at com.truly.truly.util.VoicemailDownloadQueue$VoiceMailTask.onPostExecute(VoicemailDownloadQueue.java:74)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

#### Version of Realm and tooling
Realm version(s): 4.3.4

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: SM-G955U / SM-G950U / Pixel 2 versions 7.x and 8.x

**Comment by Zhuinden** [comment]
Did you manually delete the Realm file? Because it sounds like the `.management` folder is missing.

**Comment by johnryan** [comment]
@Zhuinden no i don't, when the user logs out i call `realm.deleteAll()` but that's about it.

**Comment by cmelchior** [comment]
Without more information, it is hard to say what could be wrong, but it looks like something is removing your Realm file under your feet.

**Comment by johnryan** [comment]
@cmelchior do you have any suggestions on how i could gather more data? Interestingly these crashes also have no logs (which are uploaded from a locally stored file and are strangely missing as if the file were gone). I wonder if this could happen if a user deletes the app while it's running or clears the data from the settings app on their phone.

**Comment by TSG9876** [comment]
@johnryan is this happened on a rooted phone before revert back to non-rooted , this similar to the one permission related issue that  I have tested before on a rooted phone with native code like cpp  call .

**Comment by cmelchior** [comment]
@johnryan People clearing their app data while the app is running could probably lead to this sort of crash yes. Unfortunately, there isn't really any way to guard against it

**Comment by johnryan** [comment]
@cmelchior Okay if i can figure out who the user is i'll try to reach out and get more info. If i can get any more details i'll reopen. Thanks!

**Comment by Strasco** [comment]
Hey there, I'm also receiving the same error, and I couldn't find any solution for this. If I try changing the realm version in the build.gradle file(I'm using android studio) or if I try to install the app on my phone multiple times I stop receiving the error. Now if I restart my phone and install the app for the first time I get an error. I'm banging my head for quite a while now
