### ISSUE TITLE
Unrecoverable error. /data/data/com.virinchi.mychat/files/docquity.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 17469. Current pid is 6221. 

### ISSUE THREAD

**Issue by thakurSonu** [realm/realm-java#5833]
Hi please help to fix below bug. Is it due to multiple instance? 

/*** instance code ******/

 public class RealmModule {
    private static String TAG = "RealmModule";

    private static RealmConfiguration realmConfiguration;

    private RealmModule(){}

    public static Realm getDefaultInstance(Context context) {

        if (realmConfiguration == null) {

            try {

                Realm.init(context);  // add this line
                realmConfiguration = new RealmConfiguration.Builder()
                        .name(GlobalSetting.REALM_NAME)
                        .schemaVersion(2)
                        .encryptionKey(key).getBytes())
                        .modules(new RealmDocModule())
                        .migration(new RealmMigrations())
                        .build();

            }catch (Exception ex){
                //Log.e(TAG, "  ex  "+ex.getMessage());
                Crashlytics.logException(ex);
                Realm.init(context);  // add this line
                RealmConfiguration  realmConfiguration = new RealmConfiguration.Builder()
                        .name(GlobalSetting.REALM_NAME)
                        .schemaVersion(2)
                        .encryptionKey(key).getBytes())
                        .modules(new RealmDocModule())
                        .migration(new RealmMigrations())
                        .build();

                RealmController.closeRealm();
                Realm.getInstance(realmConfiguration).close();
                Log.e(TAG, "  ex  "+ex.getMessage());
            }
       }

        return Realm.getInstance(realmConfiguration);
    }
}

/*** craslystics report ******/

# OS Version: 4.4.4
# Device: Galaxy Tab3V 7.0
# RAM Free: 14.3%
# Disk Free: 15.2%

#0. Crashed: main
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.<init>(SharedRealm.java:194)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:241)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:317)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
       at io.realm.Realm.getInstance(Realm.java:348)
       at com.virinchi.Core.realm.RealmModule.getDefaultInstance(RealmModule.java:56)
       at com.virinchi.Core.realm.RealmController.getRealmInstance(RealmController.java:46)
       at com.virinchi.util.AnalysticsEvent.backgroundWork(AnalysticsEvent.java:91)
       at com.virinchi.util.AnalysticsEvent.analysticsEvent(AnalysticsEvent.java:81)
       at com.virinchi.Core.ApplicationLifecycleManager.onActivityResumed(ApplicationLifecycleManager.java:73)
       at android.app.Application.dispatchActivityResumed(Application.java:228)
       at android.app.Activity.onResume(Activity.java:1149)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:458)
       at com.virinchi.mychat.SplashActivity.onResume(SplashActivity.java:169)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
       at android.app.Activity.performResume(Activity.java:5526)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3046)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3085)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2498)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

--

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. /data/data/com.virinchi.mychat/files/docquity.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 17469. Current pid is 6221. in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 101
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.<init>(SharedRealm.java:194)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:241)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:317)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
       at io.realm.Realm.getInstance(Realm.java:348)
       at com.virinchi.Core.realm.RealmModule.getDefaultInstance(RealmModule.java:56)
       at com.virinchi.Core.realm.RealmController.getRealmInstance(RealmController.java:46)
       at com.virinchi.util.AnalysticsEvent.backgroundWork(AnalysticsEvent.java:91)
       at com.virinchi.util.AnalysticsEvent.analysticsEvent(AnalysticsEvent.java:81)
       at com.virinchi.Core.ApplicationLifecycleManager.onActivityResumed(ApplicationLifecycleManager.java:73)
       at android.app.Application.dispatchActivityResumed(Application.java:228)
       at android.app.Activity.onResume(Activity.java:1149)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:458)
       at com.virinchi.mychat.SplashActivity.onResume(SplashActivity.java:169)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
       at android.app.Activity.performResume(Activity.java:5526)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3046)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3085)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2498)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by cmelchior** [comment]
Are you using an encrypted Realm in multiple processes?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if you are still seeing this.

**Comment by ppamorim** [comment]
@cmelchior My app crashed on the location. The app is running the version 5.8.0, the device a SM-G390F running Android 8.1.0.

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. /data/data/xxx.xxx.xxxxx/files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 12635. Current pid is 13406. in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
       at io.realm.Realm.getInstance(Realm.java:428)
       at xxx.xxx.xxxxx.migration.RealmMigrationKt.encryptRealmIfNeeded(RealmMigration.kt:22)
       at xxx.xxx.xxxxx.migration.RealmMigrationKt.prepareRealmIfNeeded(RealmMigration.kt:558)
       at xxx.xxx.xxxxx.configRealm(TproApplication.kt:81)
       at xxx.xxx.xxxxx.onCreate(TproApplication.kt:62)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1127)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6097)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

Thank you.

**Comment by Zhuinden** [comment]
Any chance that you are trying to open the same encrypted Realm in two different processes at the same time? 🤔

**Comment by MrYuDan** [comment]
> Any chance that you are trying to open the same encrypted Realm in two different processes at the same time? 🤔

How can I open the same encrypted Realm in two different processes at the same time? Is it supported?

**Comment by MrYuDan** [comment]
> Are you using an encrypted Realm in multiple processes?

Hello!Can I open the same encrypted Realm in two different app at the same time?

**Comment by Zhuinden** [comment]
No
