### ISSUE TITLE
java.lang.IllegalArgumentException: Wrong key used to decrypt Realm

### ISSUE THREAD

**Issue by shashank-13** [realm/realm-java#5857]
This exception occurs when the code -> Realm,getDefaultInstance() method is called.It is getting called after I initialize the Realm configuration in the app using the below code

            RealmConfiguration config = new RealmConfiguration.Builder()
                    .encryptionKey(key)
                    .schemaVersion(0)
                    //  .name()
                    .build();
            Realm.setDefaultConfiguration(config);

The entire stack trace is ---

 java.lang.IllegalArgumentException: Wrong key used to decrypt Realm.
                                                                                     at io.realm.RealmCache.validateConfiguration(RealmCache.java:446)
                                                                                     at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
                                                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
                                                                                     at io.realm.Realm.getDefaultInstance(Realm.java:281)

Any suggestion are most welcome 
Thanks:)

**Comment by Zhuinden** [comment]
The encryption key should be the same across all launches and should not be changed to something else.

**Comment by shashank-13** [comment]
Yes it has to be the same .Seems some logic issue on my side.Any other suggestion would be helpful.

**Comment by cmelchior** [comment]
Hi @shashank-13 
As you haven't posted how you store/retrieve your key, it is hard to give any guidance on what might be wrong, but it is not a Realm error.

If you haven't already found the issue, feel free to reopen if you have extra information.

**Comment by shashank-13** [comment]
Yeah,It was a logic error on my side, not a realm issue.
