### ISSUE TITLE
Remove item Kotlin

### ISSUE THREAD

**Issue by Pabelpm** [realm/realm-java#5912]
#### Goal
I want to remove an item of a Real Database use Kotlin code

#### Expected Results
Remove the item and app continues in foreground.
#### Actual Results
The item was removed but this code kill my app after delete the item

Caused by: java.lang.IllegalStateException: **_Object is no longer valid to operate on. Was it deleted by another thread?_** 
at io.realm.internal.UncheckedRow.nativeGetLong(Native Method) 
at io.realm.internal.UncheckedRow.getLong(UncheckedRow.java:132) 
at io.realm.com_pabelpm_voicemassagevibrator_Data_ItemVibratorRealmProxy.realmGet$customVibrator(com_pabelpm_voicemassagevibrator_Data_ItemVibratorRealmProxy.java:137) 
at com.pabelpm.voicemassagevibrator.Data.ItemVibrator.getCustomVibrator(ItemVibrator.kt:15) 
at com.pabelpm.voicemassagevibrator.Adapter.VibratorAdapter$onBindViewHolder$2.accept(VibratorAdapter.kt:44) at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60) 
at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39) at android.view.View.performClick(View.java:5340)

#### Steps & Code to Reproduce
When click delete button of my adapter my presenter received this click
`val onItemClickListenerAdapter: VibratorAdapter.OnItemClickListenerAdapter = object : VibratorAdapter.OnItemClickListenerAdapter {
            override fun onClickRow(vibration: Long, sleep: Long) {
                mainActivityInterface.setProgressSeekbar(0)
                mainInteractor.vibratePattern(vibration, sleep)
            }

            override fun onClickDelete(item: ItemVibrator) {
                Repository.removeItemVibrator(item)
            }
        }`
Then call to remove Item from the repository Realm
`fun removeItemVibrator(itemVibrator: ItemVibrator) {
            val realm: Realm = Realm.getDefaultInstance()
            realm.executeTransaction { realm ->
                val result = realm.where(ItemVibrator::class.java).equalTo("id", itemVibrator.id).findAll()
                result.deleteAllFromRealm()
            }
            Log.i(TAG, "Item removed: ")
    }`

I add and get items like this:
`fun getAllVibrations(): Observable<RealmResults<ItemVibrator>> {
        val realm = Realm.getDefaultInstance()

        realm.beginTransaction()
        val realmResults: RealmResults<ItemVibrator> = realm.where(ItemVibrator::class.java).findAll()
        realm.commitTransaction()

        return Observable.create<RealmResults<ItemVibrator>>(object : ObservableOnSubscribe<RealmResults<ItemVibrator>> {
            @Throws(Exception::class)
            override fun subscribe(emitter: ObservableEmitter<RealmResults<ItemVibrator>>) {
                try {
                    emitter.onNext(realmResults)
                    emitter.onComplete()
                } catch (e: Exception) {
                    emitter.onError(e)
                }
            }
        })
    }

    fun saveItemVibrator(id: String, vibration: Long, sleep: Long) {
        val realm: Realm = Realm.getDefaultInstance()
        realm.executeTransaction { realm ->
            // Add a itemVibrator
            val realmResults = realm.createObject(ItemVibrator::class.java, id)
            realmResults.customVibrator = vibration
            realmResults.customSleep = sleep
        }
        Log.i(TAG, "Save item: $vibration , $sleep")
    }`

#### Version of Realm and tooling
Realm version(s): ?        classpath "io.realm:realm-gradle-plugin:5.0.0"

Android Studio version: ? 3.0

Which Android version and device: ? HUAWEI Android 6.0

**Comment by Zhuinden** [comment]
1.) you should be using `Realm.getDefaultInstance().use { realm ->` for that background delete transaction as per shown in the kotlin examples

2.) you are exposing RealmResults as a Single using `Observable.just()` using the most verbose way to do it, even though you could use `results.asFlowable()` to actually add a RealmChangeListener and receive future updates. Of course, this method would work only on UI thread, so you might want to set up a method like `observeAllVibrations()` which would assert that it is called on UI thread using `MainThreadDisposable.verifyMainThread()` for example.
