### ISSUE TITLE
Cannot find symbols related to Realm

### ISSUE THREAD

**Issue by aleksanderaleksic** [realm/realm-java#5929]
Hey! I have a project that builds and runs nicely from Android studio, but when i try to run `gradlew test` or `gradlew lint` from terminal it fails **(See error)**.  It only points to issues where its not finding symboles related to Realm.

The project is a multi module project with kotlin support.
I hope some of you can help me with this, have been stuck with it for days now...

#### Error

```java
e: /Users/***/***/***/***/***/***/localrepo/src/main/java/com/***/localrepo/realm/RealmWaveApiImpl.java:24: error: cannot find symbol
  private RealmWaveApiImpl(Realm realm) {
                           ^
  symbol:   class Realm
  location: class RealmWaveApiImpl
e: /Users/***/***/***/***/***/***/localrepo/src/main/java/com/***/ocalrepo/realm/RealmWaveApiImpl.java:28: error: cannot find symbol
  static RealmWaveApiImpl getInstance(Realm realm) {
                                      ^
  symbol:   class Realm
  location: class RealmWaveApiImpl
e: /Users/***/***/***/***/***/***/localrepo/src/main/java/com/***/localrepo/realm/RealmWaveApiImpl.java:78: error: cannot find symbol
  private void updateRealmWithObject(@NotNull RealmObject realmObject) {
                                              ^
  symbol:   class RealmObject
  location: class RealmWaveApiImpl
e: /Users/***/***/***/***/***/***/localrepo/src/main/java/com/***/localrepo/realm/objects/RealmUser.java:8: error: cannot find symbol
  @PrimaryKey
   ^
  symbol:   class PrimaryKey
  location: class RealmUser
e: /Users/***/***/***/***/***/***/localrepo/src/main/java/com/***/localrepo/realm/objects/wave/RealmWaveDebugSample.java:9: error: cannot find symbol
  @PrimaryKey
   ^
  symbol:   class PrimaryKey
  location: class RealmWaveDebugSample

```

#### Project `gradle.build`
```
buildscript {
    ext.kotlin_version = '1.2.30'
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.5.4"
        classpath "io.realm:realm-gradle-plugin:5.1.0"
    }
}

// SOME MORE CONFIG

```

#### App `gradle.build`
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'realm-android'

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
}

repositories {
    mavenCentral()
}

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.airthings.airthings"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 48
        versionName "1.3.0-dev"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        renderscriptTargetApi 18
        renderscriptSupportModeEnabled true
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation project(':localrepo') // REALM MODULE

    implementation project(':corentiumio')
    implementation project(':uicomponents')
    implementation project(':core')
    implementation project(':cloudio')

    implementation('com.crashlytics.sdk.android:crashlytics:2.6.6@aar') {
        transitive = true
    }
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:animated-vector-drawable:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
}

// SOME MORE CONFIG

```

#### Local repo / Realm module `gradle.build`
```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'realm-android'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'

    //kapt "io.realm:realm-annotations:5.1.0"
    //kapt "io.realm:realm-annotations-processor:5.1.0"
}

// SOME MORE CONFIG

```

#### Version of Realm and tooling
Realm version(s): 5.1.0

Realm sync feature enabled: no

Android Studio version: 3.1.2

Which Android version and device: ?

**Comment by cmelchior** [comment]
Have you tried running `./gradlew dependencies`. It will print the dependencies for your project and might give you some hint as to why they are missing.

Judging from the Gradle files you posted, it should work.

**Comment by aleksanderaleksic** [comment]
This is what i get when i run `./gradlew dependencies`

```
Parallel execution is an incubating feature.

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :localrepo
localrepo: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'io.realm:realm-annotations-processor:5.0.0', 'io.realm:realm-annotations-processor:5.0.0'.

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
```

**Comment by sashatinkoff** [comment]
....and what's next? Have you been succeed to solve the issue?

**Comment by cmelchior** [comment]
@aleksanderaleksic I assume you found a solution to your problem. If not, feel free to reopen the issue.

**Comment by aleksanderaleksic** [comment]
We had to put the issue om hold, mabye we will try again later..

**Comment by guisantogui** [comment]
Hi folks!
I'm having the same issue!
When I execute publishApk[_MY_FLAVOR_]Release I'm having the error below:

`e: C:\Users\guisa\OneDrive\Documents\Projects\Makadu\Development\Android\Makadu_Android\app\build\tmp\kapt3\stubs\anpednacRelease\br\com\makadu\makadu
evento\data\model\backendDTO\response\user\UserLocal.java:32: error: cannot find symbol
    private io.realm.RealmList<br.com.makadu.makaduevento.data.model.backendDTO.response.user.SocialNetworkDTOLocal> socialNetwork;
                    ^
  symbol:   class RealmList
  location: package io.realm
e: C:\Users\guisa\OneDrive\Documents\Projects\Makadu\Development\Android\Makadu_Android\app\build\tmp\kapt3\stubs\anpednacRelease\br\com\makadu\makadu
evento\data\model\backendDTO\response\user\SocialNetworkDTOLocal.java:7: error: cannot find symbol
public class SocialNetworkDTOLocal extends io.realm.RealmObject {
                                                   ^
  symbol:   class RealmObject
  location: package io.realm
e: C:\Users\guisa\OneDrive\Documents\Projects\Makadu\Development\Android\Makadu_Android\app\build\tmp\kapt3\stubs\anpednacRelease\br\com\makadu\makadu
evento\data\model\backendDTO\response\user\UserLocal.java:34: error: cannot find symbol
    private io.realm.RealmList<br.com.makadu.makaduevento.data.model.backendDTO.response.user.RoleDTOLocal> roles;
                    ^

**Then I got lots of similar errors and finishes with:**

e: java.lang.IllegalStateException: failed to analyze: java.lang.reflect.InvocationTargetException
        at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:135)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:63)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:96)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:405)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:920)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:950)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:919)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:404)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:355)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:800)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:682)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:83)
        at org.jetbrains.kotlin.kapt3.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:45)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:257)
        at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:212)
        at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:95)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:9
7)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:107)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:84
)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:374)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:64)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:101)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:365)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:130)
        ... 30 more
Caused by: com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.NullPointerException
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1143)
        ... 47 more
Caused by: java.lang.NullPointerException
        at io.realm.processor.Utils.initialize(Utils.java:38)
        at io.realm.processor.RealmProcessor.process(RealmProcessor.java:159)
        at org.jetbrains.kotlin.kapt3.ProcessorWrapper.process(annotationProcessing.kt:131)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
        ... 53 more

`

Any idea how to make it work?

**Comment by Zhuinden** [comment]
@guisantogui never seen that one before, you can try https://realm.io/docs/java/latest/#how-do-i-customize-dependecies-defined-by-the-realm-gradle-plugin

**Comment by samiissa** [comment]
Any news? I have the same problem with a simple android app. Only one POJO

`@Parcel(implementations = [com_example_realmtest_TestModelRealmProxy::class])
@RealmClass
open class TestModel() : RealmObject() {

    open var code : String = ""
    open var name : String = ""
    open var id : Int = 0

    constructor(code : String = "",
                name : String = "",
                id : Int = 0) : this (){
        this.code = code
        this.name = name
        this.id = id
    }

}`

Project build.gradle
`buildscript {
    ext.kotlin_version = '1.2.71'
    ext.realm_version = '5.7.0'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "io.realm:realm-gradle-plugin:$realm_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

App build.gradle
`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.realmtest"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

buildscript{

    ext.parcelerVersion = '1.1.11'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    compile "org.parceler:parceler-api:$parcelerVersion"
    kapt "org.parceler:parceler:$parcelerVersion"
}

kapt {
    generateStubs = true
    arguments {
        arg("realm.ignoreKotlinNullability", true)
    }
}`

Thanks in advance!!
