### ISSUE TITLE
Failure when converting short string to UTF-16 error_code = 1

### ISSUE THREAD

**Issue by hangonsushant** [realm/realm-java#5942]
`Caused by io.realm.exceptions.RealmError: Unrecoverable error. Failure when converting short string to UTF-16 error_code = 1; retcode = 0; StringData.size = 15; StringData.data =  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 154
       at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:157)
       at io.realm.TrendingTagsModelRealmProxy.realmGet$tag(TrendingTagsModelRealmProxy.java:102)
       at com.bee.app.bee.model.source.databasemodel.TrendingTagsModel.getTag(TrendingTagsModel.java:11)
       at com.bee.app.bee.home.HomePresenter$4.onSuccess(HomePresenter.java:185)
       at com.bee.app.bee.model.source.local.LocalDataSource$2.execute(LocalDataSource.java:67)
       at io.realm.Realm$1.run(Realm.java:1457)
       at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)`

Thrown error during this :

    ` @Override
        public synchronized void trendingTags(final JSONArray jsonArray) {

        Realm mRealm = mDatabaseHelper.provideRealm();
        if (mRealm != null) {
            mRealm.executeTransactionAsync(new Realm.Transaction() { //LocalDataSource.java:67
                @Override
                public void execute(@NonNull Realm realm) {
                    RealmResults<TrendingTagsModel> trendingTagsModelResults =
                            realm.where(TrendingTagsModel.class).findAll();
                    trendingTagsModelResults.deleteAllFromRealm();
                    for (int i = 0; i < jsonArray.length(); i++) {
                        try {
                            TrendingTagsModel trendingTagsModel = realm.createObject(TrendingTagsModel.class,
                                    jsonArray.getJSONObject(i).getInt(ResponseConstants.TAG_ID));

                            trendingTagsModel.setTagName(jsonArray.getJSONObject(i)
                                    .getString(ResponseConstants.TAG_NAME));
                            trendingTagsModel.setTagFeaturedImage(jsonArray.getJSONObject(i)
                                    .getString(ResponseConstants.TAG_FEATURED_IMAGE));

                        } catch (Exception e) {
                            Crashlytics.logException(e);
                        }
                    }
                }
            });
        }

    }`

#### Version of Realm and tooling
Realm version(s): 5.0.2

Realm sync feature enabled: no

Android Studio version: 3.1.2

Which Android version and device: 4.4, 7 and 8

**Comment by cmelchior** [comment]
Hi @hangonsushant 
I'm folding this into https://github.com/realm/realm-java/issues/5668
We have seen this a few times, but have so far been unable to reproduce it, so any info you can provide that can help us do that would be immensely useful.
