### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Table index out of range

### ISSUE THREAD

**Issue by tudorsirbu** [realm/realm-java#5943]
#### Goal

Get Realm default instance

#### Actual Results

>  E.g. full stack trace with exception
Fatal Exception: java.lang.IllegalStateException: Table index out of range
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
       at io.realm.Realm.getDefaultInstance(Realm.java:343)
       at com.pitchero.ph.utils.AppUtils.logout(AppUtils.java:29)
       at com.pitchero.ph.MainActivity$4.run(MainActivity.java:348)
       at android.app.Activity.runOnUiThread(Activity.java:6162)
       at com.pitchero.ph.MainActivity.goBackToIntroActivity(MainActivity.java:345)
       at com.pitchero.ph.MainActivity.access$300(MainActivity.java:71)
       at com.pitchero.ph.MainActivity$1.run(MainActivity.java:126)
       at android.os.Handler.handleCallback(Handler.java:869)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:6749)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

#### Code Sample
It seems to crash in this code sample when it attempts to get a Realm instance.
```java

    public static void logout(Activity context) {
        if (context == null) {
            return;
        }
        PubNubService.unsubscribeAllServices();
        RegistrationIntentService.unregister(context);
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        realm.deleteAll();
        realm.commitTransaction();
        AuthenticatorService.removeAccount(context);
        MixPanelHelper.getMixpanelApi(context).reset();
        Intent i = new Intent(context, IntroActivity.class);
        context.startActivity(i);
        context.finish();
    }

```
My Realm initialisation

```java
private void initRealm() {
        Realm.init(this);
        final RealmConfiguration.Builder builder = new RealmConfiguration.Builder()
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(SCHEMA_VERSION); // Must be bumped when the schema changes
        builder.deleteRealmIfMigrationNeeded();
        final RealmConfiguration config = builder.build();
        Realm.setDefaultConfiguration(config);
    }
```

#### Version of Realm and tooling
Realm version(s): 5.0.1

Realm sync feature enabled: no

Android Studio version: 3.1.2

Which Android version and device: Mainly android 7 (50%) but also android 8 (22%) and android 5 (15%), android 6 (13%)

**Comment by Zhuinden** [comment]
That sounds like that should only be possible if you have an open Realm, which is then deleted and possibly replaced with a Realm instance while it's open which doesn't contain every object?

So I think it's worth a try to disable auto-backup for `.realm` file.

**Comment by tudorsirbu** [comment]
Ok, I will give that a try, hopefully this will fix the issue. Thanks!
