### ISSUE TITLE
Crash on OsSharedRealm.java - io.realm.internal.OsSharedRealm.nativeGetSharedRealm

### ISSUE THREAD

**Issue by audiobukucom** [realm/realm-java#5948]
Help

Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.audiobuku/com.audiobuku.main.MainActivity}: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Class 'UserDBModel' has been added.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2794)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1518)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6242)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

Caused by io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Class 'UserDBModel' has been added.
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
       at io.realm.BaseRealm.<init>(BaseRealm.java:124)
       at io.realm.BaseRealm.<init>(BaseRealm.java:93)
       at io.realm.Realm.<init>(Realm.java:153)
       at io.realm.Realm.createInstance(Realm.java:424)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
       at io.realm.Realm.getDefaultInstance(Realm.java:332)
       at com.audiobuku.shared.database.DbFactory.create(DbFactory.kt:16)
       at com.audiobuku.main.MainActivity.<init>(MainActivity.kt:795)
       at java.lang.Class.newInstance(Class.java)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1085)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2794)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1518)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6242)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

http://crashes.to/s/983c9f10f76

**Comment by Zhuinden** [comment]
Non-Sync Realms in Realm-Java use manual schema mode which means when you add a new class, you need to add a migration that adds the class to your existing Realm file's schema

See https://realm.io/docs/java/latest/#migrations

This is exactly the same as if you were using `SQLiteOpenHelper` and you would need to handle `onUpgrade` where you add the necessary `ALTER TABLE` and `CREATE TABLE` clauses. So this is pretty normal for any database with a schema.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen.
