### ISSUE TITLE
App crash after abi apk split

### ISSUE THREAD

**Issue by srinivas3120** [realm/realm-java#5953]
Recently we added abi apk split to our app. 
App got installed with arm64-v8a architecture apk. 
`splits {
    abi {
      enable true
      reset()
      include 'x86', 'armeabi-v7a', 'arm64-v8a', 'mips', 'x86_64'
      universalApk true
    }
  }`

But, still crashing with following exception. why is it looking for lib/armeabi/librealm-jni.so ? as app got installed with arm64-v8a architecture apk.

`Fatal Exception: java.lang.RuntimeException: Unable to create application com.****.utils.App: com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/librealm-jni.so
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4565)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5263)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

for more logs:
http://crashes.to/s/03e68a830e1

**Comment by nhachicha** [comment]
@srinivas3120 
The system will fallback to `armeabi` if you have another native library not shipped with `arm64-v8a`. Is this the case for you?

**Comment by srinivas3120** [comment]
@nhachicha 
libraries shipped with arm64-v8a apk.
<img width="961" alt="screen shot 2018-05-15 at 5 00 05 pm" src="https://user-images.githubusercontent.com/8431202/40054175-83e17d06-5861-11e8-9ee8-8760c27ce34d.png">

**Comment by srinivas3120** [comment]
@nhachicha check this, it has device information along with logs. we didn't find a reproduction for this.
http://crashes.to/s/03e68a830e1

[317212.apk.zip](https://github.com/realm/realm-java/files/2007624/317212.apk.zip)

**Comment by srinivas3120** [comment]
@nhachicha @cmelchior any update on this?

**Comment by cmelchior** [comment]
Folding this into https://github.com/realm/realm-java/issues/6673
