### ISSUE TITLE
Cannot Iterate over RealmResults while conditionally deleting objects

### ISSUE THREAD

**Issue by adwaitv** [realm/realm-java#5955]
#### Goal

> What do you want to achieve?
Iterate over `RealmResults<Answer>` [ `Answer` is a `RealmModel`]

#### Expected Results

> Iterate over complete list

#### Actual Results

> Application crashes because it reaches out of bounds. Does `RealmResults` update size once its objects are deleted? This did not happen in realm 2.x. If this is the new behaviour of `RealmResults`, then how does one go abut iterating over a list whose size keeps updating? Will it be safe to use an Iterator over this list? 

Stack Trace: 
```
java.lang.ArrayIndexOutOfBoundsException: Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 108(requested: 22 valid: 22)
       at io.realm.internal.OsResults.nativeGetRow(SourceFile)
       at io.realm.internal.OsResults.a(SourceFile:330)
       at io.realm.t.get(SourceFile:124)
       at io.realm.ai.get(SourceFile:61)
       at com.socialcops.collect.plus.data.dataOperation.AnswerDataOperation.deleteAnswersForRemovedQuestionsOrOptions(SourceFile:107)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.performRestoreOperation(SourceFile:548)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.setUpDraftResponse(SourceFile:533)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.fetchQuestions(SourceFile:434)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerActivity.fetchQuestions(SourceFile:419)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.setQuestionAnswer(SourceFile:408)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.setFormIfFormRevisionChanges(SourceFile:381)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.continueToFormFetch(SourceFile:282)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerPresenter.onCreateView(SourceFile:267)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerActivity.initQuestionAnswerPresenter(SourceFile:386)
       at com.socialcops.collect.plus.questionnaire.questionAnswer.QuestionAnswerActivity.onCreate(SourceFile:346)
       at android.app.Activity.performCreate(Activity.java:6674)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2806)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6293)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1065)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

        int size = answers.size();

        for (int i = 0; i < size; i++) {
            Answer answer = answers.get(i);
            String questionId = answer.getQuestionId();
            Question question = formDataOperation.getQuestionByIdIfActive(questionId);
            // For all removed questions, remove the answer
            if (question == null) {
                realm.executeTransaction(realm1 -> answer.deleteFromRealm());
            }
      }

```

#### Version of Realm and tooling
Realm version(s): 
5.0.1

Realm sync feature enabled: no

Android Studio version: 3.1

Which Android version and device: 7.1.1

**Comment by Zhuinden** [comment]
@adwaitv you can check out https://stackoverflow.com/a/39974275/2413303 where I track this kind of stuff
