### ISSUE TITLE
Crash: E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files

### ISSUE THREAD

**Issue by nkanellopoulos** [realm/realm-java#5978]
While trying to determine if I have any memory leaks, I now trigger a garbage collection manually at the end of a long running process (many network requests with `Retrofit` composed using `RxJava`).

While running the profiler, I got this error, which seems very similar to #4002

```
E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files.
E/REALM: uncaught exception in notifier thread: St12system_error: Bad file descriptor
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 10120 (HandlerThread 1)
```

I though I should report this.
Any idea what could be causing it? 
#4002 turned out to be a Realm bug. 

Is there something I could be doing wrong and trigger this error? 
I keep Realm connections open only for the time I need them.

#### Version of Realm and tooling
Realm version(s): 4.3.4

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: Android 7.0, Samsung S7

**Comment by nkanellopoulos** [comment]
It turns out the real cause is here:

```
17:06:16.631 13945-17272/gr.example.app E/AndroidRuntime: FATAL EXCEPTION: HandlerThread 1527516376563
                                                                            Process: gr.example.app, PID: 13945
                                                                            io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/gr.example.app/files/log.realm.lock': open() failed: Too many open files. (open("/data/data/gr.example.app/files/log.realm.lock") failed: Too many open files) (/data/data/gr.example.app/files/log.realm.lock) in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
                                                                                at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
                                                                                at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
                                                                                at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
                                                                                at io.realm.BaseRealm.<init>(BaseRealm.java:124)
                                                                                at io.realm.BaseRealm.<init>(BaseRealm.java:93)
                                                                                at io.realm.Realm.<init>(Realm.java:153)
                                                                                at io.realm.Realm.createInstance(Realm.java:424)
                                                                                at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
                                                                                at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
                                                                                at io.realm.Realm.getInstance(Realm.java:353)
                                                                                at gr.example.app.utilities.RealmLogger.realmInstance(RealmLogger.kt:54)
                                                                                at gr.example.app.utilities.RealmLogger$e$1.invoke(RealmLogger.kt:62)
                                                                                at gr.example.app.utilities.RealmLogger$e$1.invoke(RealmLogger.kt:45)
                                                                                at gr.neuropublic.lib.UtilitiesKt$sam$Runnable$731e8ffe.run(Utilities.kt)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
```

This comes from my Logging component, which uses a separate Realm than the default.

**Comment by Zhuinden** [comment]
Is there any chance that you're running Realm on `Schedulers.newThread()'?

**Comment by nkanellopoulos** [comment]
I am using `Schedulers.io()`:

```
        val disposable =
            stepsObservable
                .concatMap { elem: SyncStep ->
                    Log.e("Rx", "$threadName  concatMap: ${elem.stepNumber}: ${elem.name}")

                    updateProgress(elem.name)
                    return@concatMap elem.obs()
                }
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())                
                .subscribeBy( ... )
```

**Comment by nkanellopoulos** [comment]
This is the code that causes the "too many open files" error.
It is called about 20 times/sec. Is this too much?

```kotlin
fun e(TAG: String, message: String, ex: Throwable?) {
        executeInBackground {
            val r = realmInstance()
            r.executeTransaction {
                var entry = r.createObject<LogEntry>()
                entry.tag = TAG
                entry.message = message
                entry.stackTrace = ex?.getStackTraceString()

            }
            r.close()
        }
    }
```

**Comment by Zhuinden** [comment]
But what is `executeInBackground`?

**Comment by nkanellopoulos** [comment]
@Zhuinden 

Sorry, I forgot. This function executes a block in the background:

```kotlin
fun executeInBackground(block : () -> Unit) {
    val handlerThread = HandlerThread("HandlerThread ${Date().time}");
    handlerThread.start();
    val handler = Handler(handlerThread.looper);

    handler.post(Runnable(block))
}
```

**Comment by Zhuinden** [comment]
Oh man. That explains a LOT.

Each time this method is called, you create a new HandlerThread, which can observe changes and receive updates from Realm, so opening a new Realm for a new HandlerThread each time creates a new notifier.

Any particular reason why this code isn't executed on `Executors.newSingleThreadedPool`?

**Comment by nkanellopoulos** [comment]
@Zhuinden The only reason is me not being aware of the consequences. I came across this code as the "typical" example of how to execute something in a new thread (in the context of Android).

However,  shouldn't `r.close()` unregister the Notifier and dispose of the Realm?  
Am I missing something here? 
I cannot understand how my code causes a crash.

**Comment by nkanellopoulos** [comment]
I'm closing this since we have found the cause of the problem, still I think this warrants some investigation.

**Comment by cmelchior** [comment]
This error is expected if you open Realm instances on too many looper threads. Realm creates a number of files per thread that is used to coordinate communication from other threads and processes. This is required for the interprocess communication to work.

All systems have a limit on how many file descriptors you can use, Android included, and you just happen to hit that limit.

The workaround is like @Zhuinden suggests, create a thread pool with a limited set of handler threads.

**Comment by nkanellopoulos** [comment]
@cmelchior Can I find some more info in the docs regarding what "too many threads" means? 
The threads in the code I posted should have a very short life (at least, this is what I think), so I do not expect more than 2-3 running at once.

**Comment by cmelchior** [comment]
It isn't something we have described in detail anywhere, since the number of file descriptors we use change from version to version of Realm Core. Hitting the limit also depends on what the rest of the system is doing as the file descriptor limit is pr. process.

2-3 threads should never hit the limit though, so I suspect they are not closed correctly or are running for longer than you think.

**Comment by nkanellopoulos** [comment]
@cmelchior Is there an API to check the number of open realm connections? 

This would really help when debugging anything related to Realm.

**Comment by Zhuinden** [comment]
Kind of, there is `Realm.getGlobalInstanceCount(realmConfiguration)`
