### ISSUE TITLE
'RealmString' doesn't exist in current schema.

### ISSUE THREAD

**Issue by mgohin** [realm/realm-java#6020]
When calling `realm.deleteAll();` I got this error. It's done in a transaction.

    io.realm.exceptions.RealmException: 'RealmString' doesn't exist in current schema.
	at io.realm.internal.ColumnIndices.getColumnInfo(ColumnIndices.java:112) ~[na:0.0]
	at io.realm.RealmSchema.getColumnInfo(RealmSchema.java:250) ~[na:0.0]
	at io.realm.ImmutableRealmSchema.get(ImmutableRealmSchema.java:43) ~[na:0.0]
	at io.realm.RealmSchema.getAll(RealmSchema.java:88) ~[na:0.0]
	at io.realm.BaseRealm.deleteAll(BaseRealm.java:667) ~[na:0.0]
	at io.realm.Realm.deleteAll(Realm.java:146) ~[na:0.0]

**Comment by Zhuinden** [comment]
Same as https://github.com/realm/realm-java/issues/5745

I totally forgot about it

**Comment by mgohin** [comment]
Yes I do ;)

**Comment by cmelchior** [comment]
Then you are being hit by #5745 . Sorry for that. There are work-arounds here: https://github.com/realm/realm-java/issues/5745#issuecomment-364397970

But I heard from at least 3 different sources they run into this, so we should prioritize fixing it.

I'll fold this issue into #5745
