### ISSUE TITLE
Inconsistent behavior when updating schemaVersion

### ISSUE THREAD

**Issue by ahmedre** [realm/realm-java#6026]
#### Goal

> What do you want to achieve?

I have some (readonly) Realm databases that ship with the app and load from assets. I want to be able to reflect data changes (i.e. I added new rows, deleted some rows, or modified some rows, without changing the schema) in new APKs.

> How do you try to achieve this?

I bump `.schemaVersion()` on the `RealmConfiguration` object.

#### Expected Results

> ?

I expect a `RealmMigrationNeededException` so I can handle it by doing something like:

```
  private static Realm loadRealm(RealmConfiguration configuration) {
    try {
      return Realm.getInstance(configuration);
    } catch (RealmMigrationNeededException e) {
      Realm.deleteRealm(configuration);
      return loadRealm(configuration);
    }
  }
```

Note that I expect this due to the documentation on `schemaVersion`, which says:

> Sets the schema version of the Realm. This must be equal to or higher than the schema version of the existing Realm file, if any. If the schema version is higher than the already existing Realm, a migration is needed.

#### Actual Results

>  E.g. full stack trace with exception

The `Realm` instance is returned without any complaints at all - no errors, etc - it's also the stale (old) version. You can then update the code to decrease the `schemaVersion` again and re-run it, and it will also run with no issues. It's as if the `schemaVersion` doesn't even matter at all in these cases.

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

Copy the below code into a project. Run it (and make sure the app does a Realm call when the app runs). Change the line for `.schemaVersion(2)` to `.schemaVersion(3)` without making any other changes (without modifying the database, etc). Run the app again. Expect the app to crash - it doesn't. Change it to `.schemaVersion(1)`. Re-run the app again. Expect a crash. No crash.

Note that, while playing with this in the same app (this app has different databases, all read only, and all read from assets), and I try the steps with one of the databases (that is accessed much more frequently), I observe the following thrown exception:

```
2018-06-16 20:02:01.867 23764-23812/? E/REALM_JNI: Exception has been thrown: Realm at path '/data/data/com.ayah/files/main.realm' already opened with different schema version.
2018-06-16 20:02:01.880 23764-23812/? E/realm: loadingRealm. failed.
    java.lang.IllegalStateException: Realm at path '/data/data/com.ayah/files/main.realm' already opened with different schema version.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:136)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:164)
        at io.realm.Realm.createInstance(Realm.java:435)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
        at io.realm.Realm.getInstance(Realm.java:364)
```

Some interesting observations about the above trace -

1. if I try again with a debugger attached, a `Realm` is always silently returned with no complaints and no crash. If I try again without a debugger, I get the same crash as above.

2. if I log instead, I can see that one of the `Realm.getInstance` calls silently succeeds before one of the next ones fail with this exception.

#### Code Sample

```java
class RealmUtils {
  public static Realm getDatabase(Context context) {
    return Realm.getInstance(getDatabaseConfiguration());
  }

  private static RealmConfiguration getDatabaseConfiguration() {
    return new RealmConfiguration.Builder()
        .assetFile(REALM_DB_PATH)
        .name(REALM_DB_NAME)
        .schemaVersion(2)
        .readOnly()
        .modules(new Module())
        .build();
  }
}
```

#### Version of Realm and tooling
Realm version(s): 5.3.0

Realm sync feature enabled: no

Android Studio version: 3.2 Canary 18

Which Android version and device: Emulator, Nexus 5x, API 27, Google Play Image

**Comment by nhachicha** [comment]
@ahmedre thanks for the detailed report 

1- Currently bumping the `schemaVersion` only without having actual schema changes will not trigger a migration.
2- Combining `schemaVersion` with `readOnly` doesn't really make sense 

I think what you're looking for could be handled by an overload of `asset` which should indicate whether to delete the existing Realm then copy the new one, something like: 
```
config.assetFile("file", new ReloadRealmFromAssetsCallback() {
  public boolean reloadRealm(Realm currentRealm) {
    return currentRealm.getVersion() <= 2;
  }
}
```

In the meantime, you can work around this issue by creating a new Realm file with a different version (to be shipped inside the assets) then use `getVersion` to detect the new Realm in order to manually delete then open the Realm again:
```Java
RealmConfiguration conf = new RealmConfiguration.Builder()
                    .assetFile("new_version.realm")
                    .name("my_realm")
                    .modules(new Module()).build();

            RealmConfiguration existingConf = new RealmConfiguration.Builder()
                    .name("my_realm")
                    .modules(new Module()).build();

            Realm existingRealm = Realm.getInstance(existingConf);
            if (existingRealm.getVersion() < 2) {
                // new Realm was not installed yet 
                existingRealm.close();
                Realm.deleteRealm(existingConf);
            }
            
            // now open new version of Realm    
            Realm.getInstance(conf);
```

**Comment by ahmedre** [comment]
Thanks Nabil!

Please consider the `assetFile`/`ReloadRealmFromAssetsCallback` example a feature request then :) In the meanwhile, I'll work around it.

**Comment by Zhuinden** [comment]
Actually. Version checking should happen with DynamicRealm API. then there is no schema verification.
