### ISSUE TITLE
io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 9 but was 6

### ISSUE THREAD

**Issue by woolworthpaul** [realm/realm-java#6079]
#### Goal

> 

My Requirement was to add three new columns(One Boolean type , two new String type) to the existing database. Old Realm model contained of 6 fields and now after i add the 3 new fields i have 9 in total. I created a RealmMigration class and new Realm Configuration with schemaVersion to 1.(This is the first time i am migrating local database.)

In the RealmMigration i add the new fields to the **RealmObjectSchema**  for my model class. When i try to initialise realm by using getInstance(newConfig) , the migration happened (i printed the new table columns and it showed the three new fields) but it crashed saying "io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 9 but was 6.

#### Expected Results

> 

Migration should have succeeded with the three new fields having default values.

#### Actual Results

>  

07-19 22:30:22.413 2145-2145/au.com.* E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: au.com.*, PID: 2145
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{ au.com.test*.presentation.dashboard.DashboardActivity}: io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 9 but was 6
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                                 Caused by: io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 9 but was 6
                                                                                    at io.realm.CustomerDestinationRealmProxy.validateTable(CustomerDestinationRealmProxy.java:465)
                                                                                    at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:87)
                                                                                    at io.realm.Realm.initializeRealm(Realm.java:359)
                                                                                    at io.realm.Realm.createAndValidate(Realm.java:317)
                                                                                    at io.realm.Realm.createInstance(Realm.java:282)
                                                                                    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:145)
                                                                                    at io.realm.Realm.getInstance(Realm.java:229)
                                                                                    at au.com.test*.data.realm.RealmLocalStorage.open(RealmLocalStorage.java:48)
                                                                                    at injection.modules.PersistenceModule$1.run(PersistenceModule.java:130)
                                                                                    at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
                                                                                    at io.reactivex.Completable.subscribe(Completable.java:1517)
                                                                                    at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                    at java.lang.Thread.run(Thread.java:762)*

#### Steps & Code to Reproduce

> 

Running the updated app on to the exisitng app cause the crash.

Logs printed from the app migration class indicates that the migration happened because it was printing the new table columns. Below are the logs

07-23 16:51:30.369 28663-28914/ I/AppStateMigration: Opening Storage : app_state.realm
07-23 16:51:30.369 28663-28914/ I/AppStateMigration: Opening Thread Name : realm
07-23 16:51:30.382 28663-28914/ I/AppStateMigration: Old Version : 0
07-23 16:51:30.382 28663-28914/ I/AppStateMigration: New Version : 1
07-23 16:51:30.382 28663-28914/ I/AppStateMigration: Contains : true
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: =====Current Field Names====== 
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: field : destinationId
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: field : name
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: field : address
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: field : coordinates
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: field : deliveryInstructions
07-23 16:51:30.385 28663-28914/ I/AppStateMigration: field : driverNotes
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: =====Migrated Field Names====== 
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : destinationId
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : name
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : address
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : coordinates
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : deliveryInstructions
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : driverNotes
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : isNewCustomer
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : packagingLabel
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: field : packagingCode
07-23 16:51:30.393 28663-28914/ I/AppStateMigration: Migrating Thread Name : realm

#### Code Sample

> 
   public class AppStateStorageRealmMigration implements RealmMigration {
  
    private static final String TAG = "AppStateMigration";
    private static final String CUSTOMER_DESTINATION = "CustomerDestination";
    private static final String IS_NEW_CUSTOMER = "isNewCustomer";
    private static final String PACKAGING_LABEL = "packagingLabel";
    private static final String PACKAGING_CODE = "packagingCode";
    private final Logger logger;

    public AppStateStorageRealmMigration(final Logger logger) {
        this.logger = logger;
    }

    @Override
    public void migrate(final DynamicRealm realm, final long oldVersion, final long newVersion) {

        logger.i(TAG, "Old Version : " + oldVersion);
        logger.i(TAG, "New Version : " + newVersion);

        long currentVersion = oldVersion;
        if (currentVersion == 0) {
            RealmSchema schema = realm.getSchema();

            RealmObjectSchema taskSchema = schema.get(CUSTOMER_DESTINATION);

            Set<String> originalFieldNames = taskSchema.getFieldNames();

            logger.i(TAG, "Current Field Names ");
            for (String fieldName : originalFieldNames) {
                logger.i(TAG, "field : " + fieldName);
            }

            //Adding new fields 'isNewCustomer', 'packagingLabel', 'packagingCode'
            taskSchema.addField(IS_NEW_CUSTOMER, Boolean.class)
                    .addField(PACKAGING_LABEL, String.class)
                    .addField(PACKAGING_CODE, String.class);
                    
            Set<String> migratedfieldNames = taskSchema.getFieldNames();

            logger.i(TAG, "Migrated Field Names ");
            for (String fieldName : migratedfieldNames) {
                logger.i(TAG, "field : " + fieldName);
            }
            
            currentVersion++;
        }
    }
}

#### Version of Realm and tooling

Realm version(s): ?  io.realm:realm-gradle-plugin:3.1.2

Realm sync feature enabled: NO

Android Studio version: ? 3.0

Which Android version and device: ? Testing on Android 7.0

**Comment by Zhuinden** [comment]
If this is something you can produce locally, then Realm-Java 3.7.2+ included migration OS integration which means you specifically get what field attributes are mismatched or what fields are missing etc as part of the error message

**Comment by woolworthpaul** [comment]
Thanks @Zhuinden . I will try that to get more information.

But i am still concerned why the crash was happening. When I tried printing the column names before and after adding columns inside the AppRealmMigartion it showed the expected results (columns were added ).  But the crash says that the column counts were less than expected. Confused!

**Comment by cmelchior** [comment]
I assume you somehow fixed the problem. If not, we probably need a sample project to debug this further. In that case feel free to reopen the issue.
