### ISSUE TITLE
Using realm in obfuscated library project

### ISSUE THREAD

**Issue by rahulsh12** [realm/realm-java#6089]
#### Goal

I have a library project that uses Realm. I want to use the library as an an obfuscated AAR in another project. The integration of the library is good in the project where i want to test this library.

#### Expected Results

The app to run normally. 

#### Actual Results
App crashes on Real.init() method with following stacktrace

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.incodesmile.android.example, PID: 14947
                                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/Realm;
                                                                                     at com.incode.smile.IncodeSmileCamera.init(Unknown Source:15)
                                                                                     at com.incodesmile.sdk.IncodeSmile.init(Unknown Source:9)
                                                                                     at com.incodesmile.android.example.IncodeSmileApplication.onCreate(IncodeSmileApplication.java:29)
                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
                                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.Realm" on path: DexPathList[[zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/base.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/lib/arm64, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/base.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.incodesmile.android.example-J8-hWM8Cy4JA-kvVfb0MfQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                     at com.incode.smile.IncodeSmileCamera.init(Unknown Source:15) 
                                                                                     at com.incodesmile.sdk.IncodeSmile.init(Unknown Source:9) 
                                                                                     at com.incodesmile.android.example.IncodeSmileApplication.onCreate(IncodeSmileApplication.java:29) 
                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740) 
                                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                     at android.os.Looper.loop(Looper.java:164) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

#### Steps & Code to Reproduce
If i add the realm classpath and plugin to my app gradle file, the error does not show up.

I have also tried it with the latest version of Realm

Not sure if this has something to do with obfuscation.

#### Version of Realm and tooling
Realm version(s): 5.0.0

Realm sync feature enabled: no

Android Studio version: 3.0 Beta-5

Which Android version and device: Android 8.1, Google Pixel

**Comment by rahulsh12** [comment]
This is not a Realm issue. Gradle was failing to sync dependencies through the pom file correctly.
