### ISSUE TITLE
Maximum number of fields for a realm model?

### ISSUE THREAD

**Issue by kaciula** [realm/realm-java#6144]
Is there a maximum number of fields allowed in a Real model? 

I have a model with around 250 fields (most are Ints and some Strings) and the app crashes. If I comment out some of the fields, everything is OK. This is an Android app.

`java.lang.VerifyError: some/package/MemberQuestionsRealm
        at io.realm.DefaultRealmModuleMediator.getExpectedObjectSchemaInfoMap(DefaultRealmModuleMediator.java:48)
        at io.realm.Realm.createExpectedSchemaInfo(Realm.java:193)
        at io.realm.Realm.<init>(Realm.java:164)
        at io.realm.Realm.createInstance(Realm.java:449)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
        at io.realm.Realm.getDefaultInstance(Realm.java:357)
       `

**Comment by kaciula** [comment]
I believe it's actually a Kotlin issue. I will close this until I figure it out. Sorry.
