### ISSUE TITLE
Model is not part of the schema for this Realm

### ISSUE THREAD

**Issue by edwinharly** [realm/realm-java#6154]
#### Goal

> Copy object to realm

#### Expected Results

> Object copied to realm

#### Actual Results

>  09-06 20:34:15.728 15886-15886/com.example.edwin.testrealm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.edwin.testrealm, PID: 15886
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.edwin.testrealm/com.example.edwin.testrealm.MainActivity}: io.realm.exceptions.RealmException: Dog is not part of the schema for this Realm
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: io.realm.exceptions.RealmException: Dog is not part of the schema for this Realm
        at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:180)
        at io.realm.internal.modules.CompositeMediator.copyOrUpdate(CompositeMediator.java:120)
        at io.realm.Realm.copyOrUpdate(Realm.java:1622)
        at io.realm.Realm.copyToRealm(Realm.java:1019)
        at com.example.edwin.testrealm.MainActivity.onCreate(MainActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

#### Steps & Code to Reproduce

> Just following the exact steps and code from the docs (https://realm.io/docs/java/latest/#getting-started)

#### Code Sample

```java
// Dog.kt
import io.realm.RealmObject
import io.realm.annotations.PrimaryKey

open class Dog : RealmObject() {
    @PrimaryKey
    var id: Int = 0
    var name: String? = null
    var age: Int = 0
}

// MainActivity.kt
import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.widget.Toast
import io.realm.Realm

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val dog = Dog()
        dog.id = 1
        dog.age = 5
        dog.name = "Sam"

        Realm.init(applicationContext)
        val realm = Realm.getDefaultInstance()

        realm.beginTransaction()
        val managedDog: Dog = realm.copyToRealm(dog)
        realm.commitTransaction()

        Toast.makeText(applicationContext, managedDog.name, Toast.LENGTH_LONG).show()
    }
}

```

#### Version of Realm and tooling
Realm version(s): 5.4.1

Realm sync feature enabled: yes

Android Studio version: 3.1.4

Which Android version and device: Nexus 5X API 28

**Comment by Zhuinden** [comment]
You're probably missing `apply plugin: 'kotlin-kapt'ŗ
