### ISSUE TITLE
class io.realm.sync.permissions.Role is not part of the schema for this Realm

### ISSUE THREAD

**Issue by mohan1102** [realm/realm-java#6160]
#### Goal

> What do you want to achieve?
Trying to save Realm object to Google firestore
#### Expected Results
Should save 
> ?

#### Actual Results
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.google.firebase.firestore.g.zzg$zza.zza(com.google.firebase:firebase-firestore@@17.0.5:749)
        at com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:153)
        at com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:37)
        at com.google.firebase.firestore.g.zzg$zza.zza(com.google.firebase:firebase-firestore@@17.0.5:769)
        at com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:153)
        at com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:37)
        at com.google.firebase.firestore.g.zzg$zza.zza(com.google.firebase:firebase-firestore@@17.0.5:769)
        at com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:153)
        at com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:1085)
        at com.google.firebase.firestore.UserDataConverter.convertPOJO(com.google.firebase:firebase-firestore@@17.0.5:437)
        at com.google.firebase.firestore.DocumentReference.set(com.google.firebase:firebase-firestore@@17.0.5:165)
        at com.funlabs.duez.CreateGroupActivity.addGroup(CreateGroupActivity.java:251)
        at com.funlabs.duez.CreateGroupActivity.lambda$onCreate$6$CreateGroupActivity(CreateGroupActivity.java:157)
        at com.funlabs.duez.CreateGroupActivity$$Lambda$6.onClick(Unknown Source)
        at android.view.View.performClick(View.java:5201)
        at android.view.View$PerformClick.run(View.java:21163)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.firebase.firestore.g.zzg$zza.zza(com.google.firebase:firebase-firestore@@17.0.5:747)
        at com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:153) 
        at com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:37) 
        at com.google.firebase.firestore.g.zzg$zza.zza(com.google.firebase:firebase-firestore@@17.0.5:769) 
        at com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:153) 
        at com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:37) 
        at com.google.firebase.firestore.g.zzg$zza.zza(com.google.firebase:firebase-firestore@@17.0.5:769) 
        at com.google.firebase.firestore.g.zzg.zzb(com.google.firebase:firebase-firestore@@17.0.5:153) 
        at com.google.firebase.firestore.g.zzg.zza(com.google.firebase:firebase-firestore@@17.0.5:1085) 
        at com.google.firebase.firestore.UserDataConverter.convertPOJO(com.google.firebase:firebase-firestore@@17.0.5:437) 
        at com.google.firebase.firestore.DocumentReference.set(com.google.firebase:firebase-firestore@@17.0.5:165) 
        at com.funlabs.duez.CreateGroupActivity.addGroup(CreateGroupActivity.java:251) 
        at com.funlabs.duez.CreateGroupActivity.lambda$onCreate$6$CreateGroupActivity(CreateGroupActivity.java:157) 
        at com.funlabs.duez.CreateGroupActivity$$Lambda$6.onClick(Unknown Source) 
        at android.view.View.performClick(View.java:5201) 
        at android.view.View$PerformClick.run(View.java:21163) 
        at android.os.Handler.handleCallback(Handler.java:746) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
     Caused by: io.realm.exceptions.RealmException: 'class io.realm.sync.permissions.Role' is not part of the schema for this Realm.
        at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:232)
        at io.realm.DefaultRealmModuleMediator.getSimpleClassNameImpl(DefaultRealmModuleMediator.java:161)
        at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:71)
        at io.realm.RealmSchema.getTable(RealmSchema.java:177)
        at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:200)
        at io.realm.RealmQuery.<init>(RealmQuery.java:147)
        at io.realm.RealmQuery.createQuery(RealmQuery.java:86)
        at io.realm.Realm.where(Realm.java:1357)
        at io.realm.Realm.getRoles(Realm.java:1814)
>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```public class Group extends RealmObject {
    @PrimaryKey
    private String groupId;
    private String groupType;
    private String name;
    private RealmList<GroupMember> groupMembers = new RealmList<>();
}

public class GroupMember extends RealmObject {
    @PrimaryKey
    private String id;
    private Person person;   
}

public class Person extends RealmObject {
    @PrimaryKey
    private String id;
    private String name;
}

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
5.4.1
Realm sync feature enabled: yes/no
Not sure. What it means?
Android Studio version: ?
3+
Which Android version and device: ?
N

**Comment by cmelchior** [comment]
@mohan1102 It isn't clear to me what code you are running when you see this error?

`o.realm.sync.permissions.Role` is used only be Realms being synchronized to the Realm Object Server, so i'm a bit puzzled this class is mentioned in your stack trace

**Comment by cmelchior** [comment]
Closing due to no response.
