### ISSUE TITLE
mremap() not implemented

### ISSUE THREAD

**Issue by tspecht** [realm/realm-java#619]
Hi guys,

it appears that mremap() is not implemented on all devices, at least I'm getting the following exception:

```
Unable to start activity ComponentInfo{com.my.app/com.my.app.activities.DubListActivity}: java.lang.RuntimeException: 
Unspecified exception. mremap(): failed: Function not implemented
```

It only occurs on RIM devices, specifically the Z10, Q10 and the Passport. Both 4.2.2 and 4.3

Are you able to work around this?

**Comment by Anatidae-Project** [comment]
I'm stuck on a project that has to support the DC area. It is shocking how many people are still on Blackberry out there.

I love Realm and hate the idea of moving away. So I'm adding my voice to this low priority item.

**Comment by bmunkholm** [comment]
Have you tried the latest version? I think it should be supported now although we have not tested it on a physical device.

**Comment by cotfas** [comment]
I have the same issue


java.lang.RuntimeException: Unable to create application com.cashdivider.app.application.CashdividerApp: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4403)
       at android.app.ActivityThread.access$1300(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5056)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
       at io.realm.Realm.<init>(Realm.java:207)
       at io.realm.Realm.createAndValidate(Realm.java:586)
       at io.realm.Realm.create(Realm.java:549)
       at io.realm.Realm.getInstance(Realm.java:522)
       at com.cashdivider.app.application.CashdividerApp.initRealmAPI(CashdividerApp.java:97)
       at com.cashdivider.app.application.CashdividerApp.getRealmNewInstance(CashdividerApp.java:137)
       at com.cashdivider.app.task.DailyReminderTask.isDailyNotification(DailyReminderTask.java:97)
       at com.cashdivider.app.task.DailyReminderTask.initTask(DailyReminderTask.java:50)
       at com.cashdivider.app.application.CashdividerApp.onCreate(CashdividerApp.java:71)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4400)
       at android.app.ActivityThread.access$1300(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5056)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
       at dalvik.system.NativeStart.main(NativeStart.java)


http://crashes.to/s/86e3eb46fc7

Devices 100% RIM
39% - Z10
21% - Q10
18% - PASSPORT
21% - OTHER

**Comment by Zhuinden** [comment]
Realm 0.84.2 to Realm 1.0.1, and Realm 1.1.1 to 1.2.0 should work without problem on Blackberry.

Also, I haven't heard of any Blackberry-related crashes in a while, so it probably works with latest 3.1.2+ versions as well.
