### ISSUE TITLE
Sometimes notifyChanges aren't working in realm

### ISSUE THREAD

**Issue by gelbertgel** [realm/realm-java#6210]
Realm : 5.7.0

```
public class RealmDiffResult<T extends RealmModel> implements CustomDiffResult {

    private final RealmAdapter.ManagedChangeSet<T> changes;

    public RealmDiffResult(RealmAdapter.ManagedChangeSet<T> changes) {
        this.changes = changes;
    }

    @Override
    public void dispatchUpdatesTo(RecyclerView.Adapter<?> adapter) {

        if (changes == null) {
            adapter.notifyDataSetChanged();
            return;
        }

        OrderedCollectionChangeSet changeSet = changes.getOrderedCollectionChangeSet();
        // null Changes means the async query returns the first time.
        if (changeSet.getState() == OrderedCollectionChangeSet.State.INITIAL) {
            adapter.notifyDataSetChanged();
            return;
        }

        // For deletions, the adapter has to be notified in reverse order.
        OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
        for (int i = deletions.length - 1; i >= 0; i--) {
            OrderedCollectionChangeSet.Range range = deletions[i];
            adapter.notifyItemRangeRemoved(range.startIndex, range.length);
        }


        OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
        for (OrderedCollectionChangeSet.Range range : insertions) {
            adapter.notifyItemRangeInserted(range.startIndex, range.length);
        }

        OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
        for (OrderedCollectionChangeSet.Range range : modifications) {
            adapter.notifyItemRangeChanged(range.startIndex, range.length);
        }

    }
}
```

realm notifyChanges are not working sometimes. And realm didn't update ui

**Comment by cmelchior** [comment]
Hi @gelbertgel 
It is hard to tell from the code exactly what is not working correctly. Can you provide a sample project demonstrating it not working or provide some more context, because most of this code seems to be yours and I don't know how you call it from Realm.

**Comment by Zhuinden** [comment]
I can see that this is Monarchy code, but technically Monarchy can only lose RealmResults if you don't retain reference to your LiveData.

**Comment by gelbertgel** [comment]
How can I do that @Zhuinden?

**Comment by Zhuinden** [comment]
....uh. 

    private LiveData<Monarchy.ManagedChangeSet<T>> liveData;

And then GC won't eat it. If the GC eats the LiveData, then Monarchy stops observing the LiveResults.

**Comment by gelbertgel** [comment]
```Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.arch.lifecycle.m.a(java.lang.Object)' on a null object reference
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
       at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
       at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
       at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)```
