### ISSUE TITLE
"RealmMigrationNeededException: Property has been made required" after upgrade to version 5.7

### ISSUE THREAD

**Issue by binodav** [realm/realm-java#6220]
#### Goal
Upgrade version from 1.1 to 5.7

#### Actual Results
Upgrade successfully but receive many crash reports:

```
Fatal Exception: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'DBModel.id' has been made required.
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.BaseRealm.(BaseRealm.java:134)
       at io.realm.BaseRealm.(BaseRealm.java:103)
       at io.realm.Realm.(Realm.java:161)
       at io.realm.Realm.createInstance(Realm.java:446)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
       at io.realm.Realm.getDefaultInstance(Realm.java:354)
       at com.binodav.app.fragments.EventDetail.ContentFragment.LoadContent(ContentFragment.java:262)
       at com.binodav.app.fragments.EventDetail.ContentFragment.onContentLoaded(ContentFragment.java:231)
       at com.binodav.app.task.LoadContentTask.onPostExecute(LoadContentTask.java:37)
       at com.binodav.app.task.LoadContentTask.runTask(LoadContentTask.java:17)
       at io.fabric.sdk.android.services.concurrency.AsyncTask.finish(AsyncTask.java:656)
       at io.fabric.sdk.android.services.concurrency.AsyncTask.access$500(AsyncTask.java:200)
       at io.fabric.sdk.android.services.concurrency.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:673)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

```
#### Steps & Code to Reproduce
Couldn't reproduce on my device but receive thousands of crash reports from Crashlytics.
This is the old model I never change its schema for very long time. The primary key was created from beginning. I released some app updates before but never encountered this issue, only after I upgraded Realm from version 1.1 to 5.7.

Below is my model class:

```
public class DBModel extends RealmObject {
    @PrimaryKey
    private int id;

    private String name;
   
   public int getId() {  return id;    }
   public void setId(int id) {   this.id = id;    }
   
   public String getName() {   return name;   }
   public void setName(String name) {    this.name = name;    }

}
```

#### Version of Realm and tooling

Realm version(s): 5.7

Realm Sync feature enabled: No

Android Studio version: 3.2

Android Build Tools version: ? 28.0.2

Gradle version: ? 3.2

Which Android version and device(s): ? Many

**Comment by Zhuinden** [comment]
Depending on how old the Realm file is, primary keys were made nullable in 0.89.0

**Comment by binodav** [comment]
Thanks @cmelchior for your answer. Do I need to update the migration class ? 
By the ways, I have many model class that use the primary key "id" but only this model having the issue and it seems only happen to 30% of my users with various OS and devices.

**Comment by binodav** [comment]
@Zhuinden: I'm upgrading Realm from version 1.1 to 5.7

**Comment by cmelchior** [comment]
No, you don't need a migration class for that. My change will just make the model class in line with what is on disk. However, if only a subset of users is crashing I suspect they are upgrading from an earlier version. So it would be much safer to add a migration class that can handle both cases.

**Comment by binodav** [comment]
@cmelchior After update my model class I encountered issue "Property 'DBModel.id' has been made optional."

**Comment by cmelchior** [comment]
Yes, that is expected if the model class in the file was saved with `int` instead of `Integer`.
That was what I warned about in https://github.com/realm/realm-java/issues/6220#issuecomment-427766794.

Basically I suspect you have users in the wild with versions of your Realm where the `id` is optional for some reason. So if you don't know how that happened you need to create a migration class that will convert those users to be non-nullable.

**Comment by binodav** [comment]
@cmelchior I can assure that my model id is always non-nullable with primitive type "int" from beginning since I created this model last year.  Since then I have released a few app updates without any issues (no schema change at all with realm version remains 1.1). Only recently I was forced to update Realm to 5.7 to support annotationProcessor configuration.

**Comment by binodav** [comment]
@cmelchior  I can confirm this is an issue with the latest version. When I upgrade from 1.1 to 2.2 instead of 5.7 I don't see this issue happen any more, only a group of users who updated to 5.7 previously  ( Due to instability of the app, I only did partial roll out to 5% of my users) , they encountered unsupported realm file which is understandable as they were downgrading from 5.7 to 2.2. For these cases I just need to delete the realm file. I am doing the full roll out now, so far no crash reported related to Realm.
