### ISSUE TITLE
Decryption failed () /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp

### ISSUE THREAD

**Issue by gelbertgel** [realm/realm-java#6226]
I have this error:

```
E/AndroidRuntime: FATAL EXCEPTION: realmThread
    Process: com.android.android, PID: 22440
    io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed () in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
        at io.realm.internal.OsSharedRealm.nativeCommitTransaction(Native Method)
        at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:273)
        at io.realm.BaseRealm.commitTransaction(BaseRealm.java:414)
        at io.realm.Realm.commitTransaction(Realm.java:143)
        at com.android.android.conversation.operation.message.send.SendTextOperations.newTextWithRealm(SendTextOperations.java:62)
        at com.android.android.conversation.operation.message.send.SendTextOperations$1.run(SendTextOperations.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

Realm version : 5.7.0

I can't set any data.

My crash place:

  ```
          mRealm.beginTransaction();
            Message message = messageCRUD.addMessage(friendId, currentTime, sendText, mRealm);
            addMessageAndDateNoTransaction(friendId, message, mRealm);
            addLastMessageToListNoTransaction(friendId, message, mRealm);
            mRealm.commitTransaction();  --> this line
```

**Comment by gelbertgel** [comment]
Yes all datas are visible but add new data not working

**Comment by cmelchior** [comment]
@gelbertgel is it something you can reproduce in a sample project we can look at?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if you can provide more information.
