### ISSUE TITLE
SyncUser.logout generates a StrictMode error

### ISSUE THREAD

**Issue by wbervoets** [realm/realm-java#6255]
#### Goal

Call logout() on all SyncUsers. (eg. SyncUsers.all().values())

#### Actual Results

I'm seeing this StrictMode error in my Logcat:

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'response.body().close()' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.lang.reflect.Method.invoke(Native Method)
        at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:343)
        at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:158)
        at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
        at okhttp3.RealCall.execute(RealCall.java:73)
        at io.realm.internal.network.OkHttpAuthenticationServer.logout(OkHttpAuthenticationServer.java:273)
        at io.realm.internal.network.OkHttpAuthenticationServer.logout(OkHttpAuthenticationServer.java:168)
        at io.realm.SyncUser$2.execute(SyncUser.java:348)
        at io.realm.SyncUser$2.execute(SyncUser.java:344)
        at io.realm.internal.network.ExponentialBackoffTask.run(ExponentialBackoffTask.java:79)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

#### Steps & Code to Reproduce

Call logout() on all SyncUsers. (eg. SyncUsers.all().values()) from my Application onCreate() method and after enabling StrictMode:

 if (BuildConfig.DEBUG) {
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .penaltyDeath()
                    .build());
        }

#### Version of Realm and tooling

Realm version(s): 5.7.1

Realm Sync feature enabled: Yes

Android Studio version: 3.2.1

Android Build Tools version: 28.0.3

Gradle version: 4.6

Which Android version and device(s): All

**Comment by cmelchior** [comment]
Outdated as the implementation has been completely replaced in 10.0.0-BETA.x
