### ISSUE TITLE
Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) io.realm.internal.OsObject.nativeStartListening

### ISSUE THREAD

**Issue by BoD** [realm/realm-java#6288]
#### Goal
Understand why this happens, and make it not happen

#### Actual Results
We have a live app that crashes for about 1% of our users, when inserting objects in a transaction.  Unfortunately we cannot find a way to reproduce the issue ourselves in our tests. The Realm message is `Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)`.

#### Steps & Code to Reproduce
Here is a snippet of what we do (not the actual code, but very close):
```
   fun doAllTheInserts(...) {
            launch(coroutineUIContext) {
                insertAllA(objectsA)
                insertAllB(objectsB)
                insertAllC(objectsC)  // <- crash here
                // etc...
            }
   }

   fun insertAllC(objects: List<C>) = realm.executeTransaction { realm.copyToRealmOrUpdate(objects) }

```
As you can see, we insert several types of objects, in a transaction, in the main thread, and on one of the insertions, in the middle, the error sometimes occurs.

```
Fatal Exception: java.lang.IllegalStateException: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)
       at io.realm.internal.OsObject.nativeStartListening(SourceFile)
       at io.realm.internal.OsObject.setObserverPairs(SourceFile:147)
       at io.realm.ProxyState.registerToObjectNotifier(SourceFile:179)
       at io.realm.ProxyState.onQueryFinished(SourceFile:201)
       at io.realm.internal.PendingRow.notifyFrontEnd(SourceFile:244)
       at io.realm.internal.PendingRow.access$000(SourceFile:20)
       at io.realm.internal.PendingRow$1.onChange(SourceFile:48)
       at io.realm.internal.PendingRow$1.onChange(SourceFile:45)
       at io.realm.internal.ObservableCollection$RealmChangeListenerWrapper.onChange(SourceFile:39)
       at io.realm.internal.ObservableCollection$CollectionObserverPair.onChange(SourceFile:20)
       at io.realm.internal.ObservableCollection$Callback.onCalled(SourceFile:64)
       at io.realm.internal.ObservableCollection$Callback.onCalled(SourceFile:54)
       at io.realm.internal.ObserverPairList.foreach(SourceFile:109)
       at io.realm.internal.OsResults.notifyChangeListeners(SourceFile:451)
       at io.realm.internal.OsSharedRealm.nativeBeginTransaction(SourceFile)
       at io.realm.internal.OsSharedRealm.beginTransaction(SourceFile:269)
       at io.realm.BaseRealm.beginTransaction(SourceFile:403)
       at io.realm.Realm.beginTransaction(SourceFile:146)
       at io.realm.Realm.executeTransaction(SourceFile:1417)
       at xxxx.insertAll(SourceFile:9)
       at yyyy$1.doResume(SourceFile:216)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(SourceFile:42)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(SourceFile:150)
       at kotlinx.coroutines.experimental.DispatchedContinuation.run(SourceFile:14)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

I don't see any reason why any transaction would be ongoing at that moment.

Please don't hesitate to ask if I can add any information that could help investigate this.

#### Version of Realm and tooling

Realm version(s): 5.4.1

Realm Sync feature enabled: No

Android Studio version: irrelevent

Android Build Tools version: 27.0.3

Gradle version: 4.10.2

Which Android version and device(s): Mostly Samsung high end (Galaxy s9/s8), and mostly Android 8 and 7.

**Comment by cmelchior** [comment]
It looks like you might be registering a change listener inside a transaction. This is currently not supported

**Comment by BoD** [comment]
Thanks for replying,
But as you can see in the snippet, we're not doing this, we only do inserts.  Also, if that was the case, shouldn't we expect it to systematically crash?

**Comment by cmelchior** [comment]
Ah yes, sorry.

It could also be related to your use of coroutines. I haven't used co-routines enough yet to say for sure, but I suspect it could be problematic that you are accessing the realm variable defined outside the co-routine inside it. 

But it would easier to debug if you could isolate the behaviour in a sample project. Then I can take a look at it?

**Comment by Zhuinden** [comment]
The only thing I can read from this stack trace is that the error actually happens in the RealmObjectChangeListener of a pending row created by a `findFirstAsync()` call.

**Comment by BoD** [comment]
@Zhuinden This is very interesting - are you saying there may actually be an exception in one of our listeners, but we don't see the stacktrace involved?  We do indeed use `findFirstAsync()` (unfortunately at many places in the app).

@cmelchior It could be related to coroutines indeed - we'll dig into it as well.  Unfortunately since we can't currently find a way to reproduce the issue at all, it's hard to make a sample project.

**Comment by Zhuinden** [comment]
Well on the other hand, this can only happen inside a `findFirstAsync()` call if the `realm.executeTransaction()` is happening on a thread where the pending row is trying to be notified, which in turn means you're actually doing this write on the UI thread.

If you create a coroutine context that runs the Realm write on a single-threaded executor (`.asDispatcher()`) then this crash should go away using `withContext(realmWriteDispatcher)`.

**Comment by BoD** [comment]
Are you saying it would be ok to write from another thread than the thread that created the Realm instance (in our case, the UI thread)?  I always thought that was a big no-no?

**Comment by cmelchior** [comment]
Yeah,  that doesn't work, but `Realm.getDefaultInstance().use` will open the Realm instance on the thread calling that code, then close it again after use.

**Comment by Zhuinden** [comment]
> Are you saying it would be ok to write from another thread than the thread that created the Realm instance (in our case, the UI thread)? 

No, but that's why the code I provided opens the Realm instance then closes it.

**Comment by BoD** [comment]
Oh ok.  Unfortunately we use a singleton instance so trying to change this would require a major refactoring in our app...  

But to be honest I still don't really understand why this happens (and also, only sometimes).

**Comment by Zhuinden** [comment]
Writing to Realm on UI thread is a pretty nice way to cause ANRs, so personally I was actually using singleton instance for the UI thread, and still opening/closing a new instance on background thread for background thread.

You could even do

    `Realm.getInstance(realm.configuration).use { r -> ... }`

**Comment by BoD** [comment]
Do you think this would stop to happen if I use `findAllAsync` instead of `findFirstAsync` everywhere?

**Comment by Zhuinden** [comment]
Yes.

**Comment by BoD** [comment]
Hi again.

I've been using `findAllAsync` instead of `findFirstAsync`, and now I'm seeing this:

```
Cannot create asynchronous query while in a write transaction in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 252
2018-11-09 12:08:24.632 E/RealmListLiveData:     at io.realm.internal.OsResults.nativeStartListening(Native Method)
2018-11-09 12:08:24.632 E/RealmListLiveData:     at io.realm.internal.OsResults.addListener(OsResults.java:405)
2018-11-09 12:08:24.632 E/RealmListLiveData:     at io.realm.internal.OsResults.addListener(OsResults.java:412)
2018-11-09 12:08:24.632 E/RealmListLiveData:     at io.realm.RealmResults.addChangeListener(RealmResults.java:174)
```

My understanding is this:
- I have a listener on object A
- inside this listener, when object A changes, I query object B, and add a listener on it
- these listeners happily live their lives
- later, I try to write something, in a transaction
- Realm notifies all the live listeners (for a reason that I don't understand)
- the listener for A is triggered and tries to add a new listener
- this is not allowed from inside a transaction apparently

Ideas?

**Comment by Zhuinden** [comment]
> inside this listener, when object A changes, I query object B, and add a listener on it

This is the problematic part, considering `beginTransaction()` can trigger the change listeners if opening the transaction updated the Realm version and/or forced async query to be executed synchronously (which it does), so this is totally expected that if you do UI thread writes, then `RealmChangeListener.onChange` can be called inside a transaction.

Technically the proper solution would be to do the writes on a dedicated background thread for Realm writes, but you've already said you don't feel like doing the proper solution; so the hacky solution is to put `xyz.addChangeListener` inside the RealmChangeListener into a `handler.post {`.

**Comment by BoD** [comment]
Thanks a lot for your support - I'll see what I can do and keep this issue updated.

**Comment by BoD** [comment]
Adding the `changeListener` in `handler.post` did the trick.  Thanks again.  

We'll keep in mind that we should use a different Realm instance and thread for write operations - but this won't be an easy change for us.
