### ISSUE TITLE
RealmMigrationNeededException: Migration is required due to the following errors:  Primary Key for class xxx has been removed.

### ISSUE THREAD

**Issue by Thien658jjh** [realm/realm-java#6290]
I've add new object to realm and I use Migration. 

This one in SplashScreen
   ```
RealmConfiguration config1 = new RealmConfiguration.Builder()
                .name("default.realm")
                .schemaVersion(1)
                    .migration(new Migration())
                .build();

        Realm realm = Realm.getInstance(config1); // Automatically run migration if needed
        realm.close();
```

```
   @Override
    public void migrate(@NonNull final DynamicRealm realm, long oldVersion, long newVersion) {
        // During a migration, a DynamicRealm is exposed. A DynamicRealm is an untyped variant of a normal Realm, but
        // with the same object creation and query capabilities.
        // A DynamicRealm uses Strings instead of Class references because the Classes might not even exist or have been
        // renamed.

        // Access the Realm schema in order to create, modify or delete classes and their fields.
        RealmSchema schema = realm.getSchema();
        // Migrate from version 0 to version 1
        if (oldVersion == 0) {
            schema.create("RecordRealm")
                    .addField("id", String.class, FieldAttribute.PRIMARY_KEY)
                    .addField("name", String.class)
                    .addField("storyId", String.class)
                    .addField("filePath", String.class)
                    .addField("time", int.class);
        }
    }
```

```
public class RecordRealm extends RealmObject {
    private String id;
    private String name, storyId, filePath;
    private int time;
...
```

And it gave me this error:
 ```
  Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Property 'RecordRealm.id' has been made unindexed.
    - Primary Key for class 'RecordRealm' has been removed.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:134)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:161)
        at io.realm.Realm.createInstance(Realm.java:446)
```

I don't know what can I do to fix it, I was research for the solution but couldn't find any thing. So I decide to use SQLite for that object instead ... :'(
Please help me. Thank you

**Comment by Thien658jjh** [comment]
added:
When I used this :

    ```
RealmConfiguration config1 = new RealmConfiguration.Builder()
                .name("default.realm")
                .schemaVersion(1)
                .deleteRealmIfMigrationNeeded()
                .build();

        Realm realm = Realm.getInstance(config1); // Automatically run migration if needed
        realm.close();
```

I got

```
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Provided schema version 0 is less than last set version 1.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
```

**Comment by anggrayudi** [comment]
I have the same problem too.
Even though I clear the app's data, uninstall it, and also run clean in Android Studio, this error still persists. Please fix this bug ASAP.

**Comment by Zhuinden** [comment]
This is a bug in YOUR code. You are opening the Realm with two different configurations, one of them (possibly the default config not being set to something custom) and another one are opening the same Realm with 0 and 1 schema versions respectively.

**Comment by cmelchior** [comment]
Outdated, so closing. Also, what @Zhuinden said is correct.
If this is still a problem please provide an example project we can look at.
