### ISSUE TITLE
Item is not part of the schema for this Realm

### ISSUE THREAD

**Issue by HaiNM-deha** [realm/realm-java#6307]
11-21 02:36:34.369 3798-3798/jp.peers.clos E/MainActivity$onCreate: java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.peers.clos/jp.peers.clos.views.activity.MainActivity}: io.realm.exceptions.RealmException: Item is not part of the schema for this Realm
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: io.realm.exceptions.RealmException: Item is not part of the schema for this Realm
        at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:180)
        at io.realm.internal.modules.CompositeMediator.getSimpleClassNameImpl(CompositeMediator.java:98)
        at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:71)
        at io.realm.RealmSchema.getTable(RealmSchema.java:177)

**Comment by cmelchior** [comment]
Please provide more context. Otherwise, we cannot help you. The issue template exists for a reason.

But in this case, you are trying to do something with an `Item` class that doesn't appear to be a Realm model class.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to re-open.
