### ISSUE TITLE
error in migration

### ISSUE THREAD

**Issue by hadighasemian** [realm/realm-java#6308]
my new schema version is 2 and first version was 1.
i want to add three field to my schema.
when i want to get a table schema at this line:

                RealmObjectSchema alarmSchema = schema.get("AlarmTime");
                alarmSchema.addField("alarmSt", int.class).isNullable("alarmSt");
               

error is: alarmSchema is null. and when i change code to this:

              RealmObjectSchema alarmSchema = schema.get("AlarmTime");
                if(alarmSchema == null) {
                    alarmSchema = schema.create("AlarmTime");
                }
                alarmSchema.addField("alarmSt", int.class).isNullable("alarmSt");

it say migration required.
my error at first state:

      E/AndroidRuntime: FATAL EXCEPTION: main
      Process: srf.com.hasebu, PID: 2635
      java.lang.RuntimeException: Unable to instantiate activity 
      ComponentInfo{srf.com.hasebu/srf.com.hasebu.controller.splashScreen.SplashActivity}: 
      java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmObjectSchema 
      io.realm.RealmObjectSchema.addField(java.lang.String, java.lang.Class, io.realm.FieldAttribute[])' on a 
         null object reference
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2841)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
          at android.app.ActivityThread.-wrap11(Unknown Source:0)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
          at android.os.Handler.dispatchMessage(Handler.java:105)
          at android.os.Looper.loop(Looper.java:164)
          at android.app.ActivityThread.main(ActivityThread.java:6944)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 
         'io.realm.RealmObjectSchema io.realm.RealmObjectSchema.addField(java.lang.String, 
          java.lang.Class, io.realm.FieldAttribute[])' on a null object reference
          at srf.com.hasebu.orm.realm.RealmMigrate.migrate(RealmMigrate.java:22)
          at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:781)
          at io.realm.internal.OsSharedRealm.runMigrationCallback(OsSharedRealm.java:533)
          at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
          at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
          at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
          at io.realm.BaseRealm.<init>(BaseRealm.java:135)
          at io.realm.BaseRealm.<init>(BaseRealm.java:103)
           at io.realm.Realm.<init>(Realm.java:163)
          at io.realm.Realm.createInstance(Realm.java:499)
          at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
          at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
          at io.realm.Realm.getInstance(Realm.java:428)
          at srf.com.hasebu.orm.realm.RealmManager$Companion.getNewInstance(RealmManager.kt:20)
          at srf.com.hasebu.orm.classes.UserManager$Companion.getUser(UserManager.kt:14)
          at srf.com.hasebu.controller.splashScreen.SplashActivity.<init>(SplashActivity.kt:21)
          at java.lang.Class.newInstance(Native Method)
          at android.app.Instrumentation.newActivity(Instrumentation.java:1180)
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
          at android.app.ActivityThread.-wrap11(Unknown Source:0) 
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
          at android.os.Handler.dispatchMessage(Handler.java:105) 
          at android.os.Looper.loop(Looper.java:164) 
          at android.app.ActivityThread.main(ActivityThread.java:6944) 
          at java.lang.reflect.Method.invoke(Native Method) 
          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

this is my migration:

    class RealmMig: RealmMigration {

    override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {
        var old = oldVersion
        val realmSchema = realm.schema
        println(oldVersion)
        println(newVersion)
        if (old == 1L) {
            val alarmTimeSchema = realmSchema.get("AlarmTime")
            // Add the complete state boolean field
            alarmTimeSchema!!.addField("alarmSt", Int::class.java).setNullable("alarmSt", true)
            alarmTimeSchema.transform(RealmObjectSchema.Function { obj ->
                                obj.setInt("alarmSt", 1) })
            val settingSchema = realmSchema.get("Settings")
            settingSchema!!.addField("pass",Boolean::class.java).setNullable("pass", true)
            settingSchema.addField("pass_key",String::class.java).setNullable("pass_key", true)
            settingSchema.transform(RealmObjectSchema.Function { obj ->
                obj.setBoolean("pass", false) })
            settingSchema.transform(RealmObjectSchema.Function { obj ->
                obj.setString("pass_key", "") })
            old++
        }
    }

    override fun hashCode(): Int {
        return 37
    }

    override fun equals(o: Any?): Boolean {
        return o is RealmMig
    }}

and this is my configuration:

    class RealmManager {
    companion object {
        fun getNewInstance(): Realm {
            val config = RealmConfiguration.Builder()
                    .name("hasebu.realm")
                    .schemaVersion(2)
                    .migration( RealmMigrate())
                    .build()
            Realm.setDefaultConfiguration(config)
            return Realm.getInstance(config)
        }}}

and this is AlarmTime class:

    open class AlarmTime : RealmObject() {
    var id:Long? = null
    var name:String? = null
    var repeat:Repeat?=null
    var createdAt:Long = DateHolder().time
    var version = 0
    var hour: Int = 12
    var minute: Int = 0
    var alarm: Boolean = false
    var alarmSt: Int = 0
    var active: Boolean = true
    var state = 1
    var pin: Boolean = false
    init {
        id = getNextId()
        createdAt = DateHolder().time
    }
    fun getNextId():Long{
        var realm = RealmManager.getNewInstance()
        return try {
            val number = realm.where(AlarmTime::class.java).max("id")
            if (number != null) {
                number.toLong() + 1
            } else {
                1000
            }
        } catch (e: Exception) {
            1000
        }
    }
    fun getTime(): String? {
        return StringHelper.toPersianNumber("$hour:$minute")
    }
    fun getStory(context: Context): String {
        return repeat!!.getNotificationTitle(context) +" "+
                context.getString(R.string.at_time) + " "+
                getTime()+" "+
                context.getString(R.string.do_this)
    } }

this is setting class

     open class Settings: RealmObject() {
      @PrimaryKey
    var id:Long? = null
    var reviewTime:AlarmTime?=null
    var calculatingTime:AlarmTime?=null
    var pass:Boolean=false
    var pass_key:String=""
    var createdAt:Long = DateHolder().time
    var version = 0
    var state = 1
    init {
        id = getNextId()
        createdAt = DateHolder().time
    }
    fun getNextId():Long{
        var realm = RealmManager.getNewInstance()
        return try {
            val number = realm.where(Settings::class.java).max("id")
            if (number != null) {
                number.toLong() + 1
            } else {
                1000
            }
        } catch (e: Exception) {
            1000
        }
    }}

android studio 3.2.1
i am using kotlin 1.3 and realm 5.8.0
    syncEnabled = false
samsung a3 2017
android 8

**Comment by hadighasemian** [comment]
its really confusing
when i install app on new device not installed yet, migration will execute???????
the realm instance is being created by single class every where

**Comment by hadighasemian** [comment]
and another thing:
when i rename realm, problem will be solved

**Comment by cmelchior** [comment]
From the information, you have given I don't see any immediate errors. However, it isn't surprising that renaming the Realm works, as that means you will create a new file that doesn't require a migration.

My guess is that the Realm on disk is somehow different than what you expect it to be. You can try to download the Realm and open it in Realm Studio to see what it actually contains?

Otherwise, we need an example project to be able to debug this further.

**Comment by cmelchior** [comment]
Closing due to inactivity. If this is still an issue please provide an example project demonstrating the issue and re-open the issue.
