### ISSUE TITLE
RealmFileException: No such file or directory

### ISSUE THREAD

**Issue by stevenduan17** [realm/realm-java#6370]
#### Goal
No crash

#### Actual Results
When run Realm.getDefaultInstance()  app crashed.

#### Steps & Code to Reproduce
I just  init realm in application
  Realm.init(this)
    val config = RealmConfiguration.Builder()
      .name("tj.realm")
      .schemaVersion(2)
      .deleteRealmIfMigrationNeeded()
      .build()
    Realm.setDefaultConfiguration(config)

Then in an Activity use copyToRealmOrUpdate success. But to Another activity crashed on  Realm.getDefaultInstance()

Here‘s the logs:

java.lang.RuntimeException: Unable to start activity ComponentInfo{tj.tunnel/tj.tunnel.ui.patrol.PatrollingActivity}: io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/tj.tunnel/files/tj.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/tj.tunnel/files/tj.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)

#### Version of Realm and tooling

Realm version(s): v5.8.0

Realm Sync feature enabled: No

Android Studio version: 3.2.0

Android Build Tools version: 28.0.0

Gradle version: 3.2.1

Which Android version and device(s): Mi8 android 8.1

**Comment by Zhuinden** [comment]
I would think this can only happen if you manually delete the Realm file somewhere while the Realm is open

**Comment by stevenduan17** [comment]
@Zhuinden but actually I have do nothing.

**Comment by cmelchior** [comment]
Outdated, so closing. We probably need an example project demonstrating this issue to guess what the problem could be, but yes, it appears that _something_ deleted the Realm file.
