### ISSUE TITLE
Rejected Execution Exception

### ISSUE THREAD

**Issue by skiewalker12** [realm/realm-java#6380]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3976910 rejected from java.util.concurrent.ThreadPoolExecutor@6e149395[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at com.saama.mdp.flow.DAGExecutor.execute(DAGExecutor.java:238)
	... 33 more

**Comment by Zhuinden** [comment]
You're probably calling `executeTransactionAsync` in a for loop, but there is a maximum limit of 100 jobs it accepts.

**Comment by skiewalker12** [comment]
Thanks. Got it. Working fine now

**Comment by skiewalker12** [comment]
The problem was that i had mentioned execution service to shutdown.
