### ISSUE TITLE
io.realm.exceptions.RealmException: CityRealm is not part of the schema for this Realm

### ISSUE THREAD

**Issue by lanzhu1993** [realm/realm-java#6383]
#### Goal

when I use databinding and realm ，When I call query, App Crashed, the error log as follows

#### Actual Results
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gykj.rollcall/com.gykj.rollcall.ui.login.LoginActivity}: io.realm.exceptions.RealmException: CityRealm is not part of the schema for this Realm
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: io.realm.exceptions.RealmException: CityRealm is not part of the schema for this Realm
        at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:180)
        at io.realm.internal.modules.CompositeMediator.getSimpleClassNameImpl(CompositeMediator.java:98)
        at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:71)
        at io.realm.RealmSchema.getTable(RealmSchema.java:177)
        at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:200)
        at io.realm.RealmQuery.<init>(RealmQuery.java:147)
        at io.realm.RealmQuery.createQuery(RealmQuery.java:86)
        at io.realm.Realm.where(Realm.java:1357)
        at com.gykj.rollcall.ui.login.LoginActivity.initData(LoginActivity.java:41)
        at com.gykj.mvvmlibrary.base.BaseActivity.onCreate(BaseActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 

#### Steps & Code to Reproduce
 Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .directory(file)
                .name("roll_call.realm") //文件名
                .schemaVersion(1)
                .build();
        Realm.setDefaultConfiguration(config);

@RealmClass
public class CityRealm extends RealmObject {

    private String cityCode;
    private String cityName;
    private String cityPingyin;
    private String province;

    public String getCityCode() {
        return cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getCityPingyin() {
        return cityPingyin;
    }

    public void setCityPingyin(String cityPingyin) {
        this.cityPingyin = cityPingyin;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

}

RealmResults<CityRealm> all = Realm.getDefaultInstance().where(CityRealm.class).findAll();

#### Version of Realm and tooling

Realm version(s): 5.4.2

Realm Sync feature enabled: Yes

Android Studio version: 3.2.0

Android Build Tools version: 28.0.2

Gradle version: 4.6

Which Android version and device(s): android 8.0 & huawei

**Comment by lanzhu1993** [comment]
Please help me ,Thanks

**Comment by lanzhu1993** [comment]
In my another project, I use the MVP design patterns, there will be no problem, but using DataBinding MVVM, can appear such circumstance.

**Comment by cmelchior** [comment]
Is the `CityRealm` class part of our app module or is it pulled in as part of a library module?

**Comment by sp-clinks** [comment]
I've got the same exception when I try to query an app class in  the MainActivity of our app which has a library module with its internal realm classes. The realm classes in the library(aar) can be used  normally inside. Is it not possible to use realm classes of app independently from its library?

**Comment by hokusaiblue** [comment]
I've got the same exception when I try to query an app class in the MainActivity of our app which has a library module with its internal realm classes. The realm classes in the library(aar) can be used normally inside. Is it not possible to use realm classes of app independently from its library?
