### ISSUE TITLE
io.realm.exceptions.RealmMigrationNeededException

### ISSUE THREAD

**Issue by unengchan** [realm/realm-java#6389]
ERROR:
 Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Property 'Card.card_type' has been added.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at com.unengchen.testrealmmigration.model.RealmHelper.getInstance(RealmHelper.java:29)
        at com.unengchen.testrealmmigration.MainActivity.onCreate(MainActivity.java:21)

 Code：
private static RealmConfiguration mConfiguration = new RealmConfiguration.Builder()
            .schemaVersion(5)
            .migration(new MyRealmMigration())
            .name("test.realm")
            .build();

    private static RealmConfiguration mCardConfiguration = new RealmConfiguration.Builder()
            .schemaVersion(2)
            .migration(new CustomRealmMigration())
            .name("test_card.realm")
            .build();

    public static Realm getInstance(){
        return Realm.getInstance(mConfiguration);
    }

    public static Realm getCardRealm(){
        return Realm.getInstance(mCardConfiguration);
    }

/**
 * Created by unengchan on 2019/1/8
 */
public class Card extends RealmObject {

    private String card_id;

    private String name;

    // new filed
    private String card_type;

}

/**
 * Created by unengchan on 2019/1/8
 */
public class Person extends RealmObject {

    @PrimaryKey
    private String name;
    private String sex;

    private String age;

    private String address;

    private Integer id;

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    private int coco;

    public void setCoco(int coco) {
        this.coco = coco;
    }

    public int getCoco() {
        return coco;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return address;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

/**
 * Created by unengchan on 2019/1/8
 */
public class CustomRealmMigration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {

        RealmSchema schema = realm.getSchema();
        if (oldVersion == 0) {
            schema.create("Card")
                    .addField("card_id", String.class)
                    .addField("name", String.class);
            oldVersion++;
        }

        if (oldVersion == 1) {
            schema.get("Card")
                    .addField("card_type", String.class);
            oldVersion++;
        }

    }
}

/**
 * Created by unengchan on 2019/1/8
 */
public class MyRealmMigration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {

        RealmSchema schema = realm.getSchema();
        Log.d("MyRealmMigration", "-------" + oldVersion);
        if (oldVersion == 0) {
            schema.create("Person")
                    .addField("name", String.class, FieldAttribute.PRIMARY_KEY)
                    .addField("sex", String.class);
            oldVersion++;
        }
        Log.d("MyRealmMigration", "-------" + oldVersion);

        if (oldVersion == 1) {
            schema.get("Person").addField("age", String.class);
            oldVersion++;
        }

        if (oldVersion == 2) {
            schema.get("Person").addField("address", String.class);
            oldVersion++;
        }

        if (oldVersion == 3) {
            schema.get("Person").addField("id", Integer.class);
            oldVersion++;
        }

        if (oldVersion == 4) {
            schema.get("Person").addField("coco", int.class);
        }
    }
}

Use：
        Realm realm = RealmHelper.getInstance();
        RealmResults<Person> people = realm.where(Person.class).findAll();
        Log.d(MainActivity.class.getSimpleName(), "------" + people.size());

        Realm cardRealm = RealmHelper.getCardRealm();
        RealmResults<Card> all = cardRealm.where(Card.class).findAll();
        Log.d(MainActivity.class.getSimpleName(), "---card---" + all.size());

**Comment by Zhuinden** [comment]
You are not specifying the RealmModels that should be part of a given configuration's schema, so BOTH configurations have ALL realmModels.

You need to use `@RealmModule` and specify `modules(...)` to make sure only the RealmModels you want are added to the configurations' schemas.

**Comment by unengchan** [comment]
private static RealmConfiguration mConfiguration = new RealmConfiguration.Builder()
            .schemaVersion(5)
            .migration(new MyRealmMigration())
            .name("test.realm")
            .addModule(Person.class)
            .build();



    private static RealmConfiguration mCardConfiguration = new RealmConfiguration.Builder()
            .schemaVersion(1)
            .migration(new CustomRealmMigration())
            .name("test_card.realm")
            .addModule(Card.class)
            .build();


/**
 * Created by unengchan on 2019/1/8
 */
@RealmModule
public class Card extends RealmObject {

    private String card_id;

    private String name;}



/**
 * Created by unengchan on 2019/1/8
 */
@RealmModule
public class Person extends RealmObject {

    @PrimaryKey
    private String name;
    private String sex;

    private String age;

    private String address;

    private Integer id;}


ERROR:
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:133)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 107 more
Caused by: java.lang.NullPointerException
	at io.realm.processor.ModuleMetaData.getClassListFromModule(ModuleMetaData.java:339)
	at io.realm.processor.ModuleMetaData.validateNamingPolicies(ModuleMetaData.java:168)
	at io.realm.processor.ModuleMetaData.preProcess(ModuleMetaData.java:114)
	at io.realm.processor.RealmProcessor.preProcessModules(RealmProcessor.java:209)
	at io.realm.processor.RealmProcessor.process(RealmProcessor.java:162)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)


HELPER
Can you give me a simple example?

**Comment by unengchan** [comment]
thanks
