### ISSUE TITLE
RealmObject moved to another package get lost by Realm

### ISSUE THREAD

**Issue by Maikals** [realm/realm-java#6403]
#### Goal
I want to move the actual RealmObjects to another package
#### Actual Results
Realm don't find the entities in the new location and say that the entities are new.

2019-01-15 16:08:16.762 24301-24301/es.ofertia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: es.ofertia.android, PID: 24301
    io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Class 'ListEntity' has been added.
    - Class 'ProductEntity' has been added.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)
        at es.ofertia.android.presentation.ui.fragments.ShoppingListGridFragment.initContent(ShoppingListGridFragment.java:69)
        at es.ofertia.android.presentation.ui.fragments.ShoppingListGridFragment.onResume(ShoppingListGridFragment.java:105)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
2019-01-15 16:08:17.226 24301-24301/es.ofertia.android E/UncaughtException: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Class 'ListEntity' has been added.
    - Class 'ProductEntity' has been added.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)
        at es.ofertia.android.presentation.ui.fragments.ShoppingListGridFragment.initContent(ShoppingListGridFragment.java:69)
        at es.ofertia.android.presentation.ui.fragments.ShoppingListGridFragment.onResume(ShoppingListGridFragment.java:105)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

#### Steps & Code to Reproduce
I only moved the entities from a package to another one in the same module.

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: No

Android Studio version: 3.3

Android Build Tools version: 28.0.3

Gradle version: 4.10.1

Which Android version and device(s): 5.+ in any device

**Comment by cmelchior** [comment]
Our proxy classes encode the package path as part of the final class name, but moving classes should be fine since the simple name is the same, so it should translate to the same simple name in the Realm file. 

I suspect there might be issues with the build instead. Have you tried doing a full clean + rebuild?

**Comment by Maikals** [comment]
Yes, I tried to remove the build folder too and invalidate caches and restart. The thing is that if I relocate the RealmObjects to it's original package, all work fine again.

**Comment by cmelchior** [comment]
Closing due to inactivity. If this is still a problem, please reopen the issue.
