### ISSUE TITLE
Incompatible lock file

### ISSUE THREAD

**Issue by loste42** [realm/realm-java#6406]
#### Goal
Understand causes of this issue and possible fixes

#### Actual Results
```
io.realm.exceptions.RealmFileException: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. (Incompatible lock file. Shared info version doesn't match, 771 10.) (/data/data/...) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java:-2)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
```

#### Steps & Code to Reproduce

The crash appears after new releases of the app with a high peek and going down afterwards. I read about it in some old issues and that it might have been fixed with #2902. It is not reproducable.

Is there maybe provide any kind of checklist, which could lead to this error? Or some things that we shouldn't do?

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: Yes

Android Studio version: 3.2.1

Which Android version and device(s): the latest occurrences were mostly(96%) on Samsung Galaxy S8 with Android 8.0.0

**Comment by cmelchior** [comment]
This looks really odd. We have seen this before, but then it was related to people upgrading from a really old version of Realm: https://github.com/realm/realm-java/issues/2459#issuecomment-321786764

I don't know if that could be the case for you?

**Comment by cmelchior** [comment]
Closing due to no response
