### ISSUE TITLE
Out of memory size error after new app release

### ISSUE THREAD

**Issue by mcr93** [realm/realm-java#6407]
#### Goal
May you have an idea why this error occurs after every app release to a few user?

#### Actual Results

io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 872415232 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java:-2)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at app.data.AppKitRealm.newRealmInstance(AppKitRealm.kt:49)
        at app.appkit.data.model.ConfigKt.storeConfig(Config.kt:210)
        at app.appkit.applyConfig(AppKit.kt:177)
        at app.appkit.<init>(AppKit.kt:139)
        at app.appkit.client.AppKitApplication.onCreate(AppKitApplication.kt:72)
        at de.app.onCreate(App.kt:116)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
        at android.app.ActivityThread.-wrap3(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

#### Steps & Code to Reproduce
We can not reproduce it. It always happens after a new app release to a few users.

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: No

Gradle version: 3.2.1

Which Android version and device(s): Android Version > 6, Devices: Samsung, Sony, Huawei, Motorola

**Comment by cmelchior** [comment]
It looks like it attempts to open a Realm that this 872 MB.  This will most likely fail on 32-bit devices which commonly can only open up to ~400 MB.

Realms should rarely reach this size unless you are holding on to older versions of Realm due to threading issues. You can find more info here: https://realm.io/docs/java/latest/#faq-large-realm-file-size

One way to check it is using `Realm.getGlobalInstanceCount(config)` if that number is high it means you have open Realms on a lot of threads which sometimes can lead to unexpected file growth.

**Comment by mcr93** [comment]
The error occurs mostly on 64 bit devices. But we found some missing close() calls which might be the problem. Moreover there are two other errors which occur for some days after app release to a few user:

java.lang.RuntimeException: Unable to create application de.App: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/de.app/files/appkit.v4.realm': Top ref not aligned (485169). top_ref[0]: 76731, top_ref[1]: 2EB58, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0. (Top ref not aligned (485169). top_ref[0]: 76731, top_ref[1]: 2EB58, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0) (/data/data/de.app/files/appkit.v4.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6158)
        at android.app.ActivityThread.access$1200(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/de.app/files/appkit.v4.realm': Top ref not aligned (485169). top_ref[0]: 76731, top_ref[1]: 2EB58, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0. (Top ref not aligned (485169). top_ref[0]: 76731, top_ref[1]: 2EB58, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0) (/data/data/de.app/files/appkit.v4.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java:-2)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at app.appkit.data.AppKitRealm.newRealmInstance(AppKitRealm.kt:49)
        at app.appkit.data.model.ConfigKt.storeConfig(Config.kt:210)
        at app.appkit.AppKit.applyConfig(AppKit.kt:177)
        at app.appkit.AppKit.<init>(AppKit.kt:139)
        at app.appkit.client.AppKitApplication.onCreate(AppKitApplication.kt:72)
        at de.app.App.onCreate(App.kt:116)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6153)
        at android.app.ActivityThread.access$1200(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

java.lang.RuntimeException: Unable to create application de.App: io.realm.exceptions.RealmFileException: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. (Incompatible lock file. Shared info version doesn't match, 771 10.) (/data/data/de.app/files/appkit.v4.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: INCOMPATIBLE_LOCK_FILE.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6061)
        at android.app.ActivityThread.-wrap1(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: io.realm.exceptions.RealmFileException: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. (Incompatible lock file. Shared info version doesn't match, 771 10.) (/data/data/de.app/files/appkit.v4.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java:-2)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at app.appkit.data.AppKitRealm.newRealmInstance(AppKitRealm.kt:49)
        at app.appkit.data.model.ConfigKt.storeConfig(Config.kt:210)
        at app.appkit.AppKit.applyConfig(AppKit.kt:177)
        at app.appkit.AppKit.<init>(AppKit.kt:139)
        at app.appkit.client.AppKitApplication.onCreate(AppKitApplication.kt:72)
        at de.app.App.onCreate(App.kt:116)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6058)
        at android.app.ActivityThread.-wrap1(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Could this be related to the missing close statements, too?

**Comment by Zhuinden** [comment]
Sounds like multi-process access in such a way that it breaks 🤔

**Comment by Zhuinden** [comment]
You need to call `realm.close()` *paired with `getInstance()` calls.

**Comment by bschiranth** [comment]
Hey @Zhuinden  just curious , when it throws this error  "Out of memory size: 872415232 " , is the number  872415232  the size of one realm file or the total size of all realm files for that project (say there are 10 realm configurations)?

**Comment by Zhuinden** [comment]
I think it is most likely just one Realm file.

**Comment by bschiranth** [comment]
If the file size has reached 1GB, then how many open realm instances could be causing this issue? Around 1000 or something ?

**Comment by cmelchior** [comment]
It is just one Realm file. It isn't directly related to the number of open Realm instances as such, but the fact that 1 instance is holding on to a version of the Realm data while other threads are moving forward. You can read more about it here: https://realm.io/docs/java/latest/#faq-large-realm-file-size

But most commonly this happens if you have a Realm on a background thread that isn't closed correctly.

**Comment by cmelchior** [comment]
Closing due to inactivity. If this is still an issue, please reopen the issue.
