### ISSUE TITLE
App crashes on Android emulator 64 bit.

### ISSUE THREAD

**Issue by Zzumer** [realm/realm-java#6420]
Hello!

#### Actual Results

App crashes on Android emulator with API 28 64 bit.
From logcat:
```
2019-02-05 15:59:14.829 8242-8274/com.test2 E/SoLoader: Error when loading lib: dlopen failed: "/data/data/com.test2/lib-main/librealmreact.so" is 32-bit instead of 64-bit lib hash: 380c1cceef165ad58ea7421e1b476f63 search path is /data/app/com.test2-B46bbsEkBfEeK4u1a9TZYQ==/lib/x86_64
2019-02-05 15:59:14.829 8242-8274/com.test2 E/SoLoader: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: "/data/data/com.test2/lib-main/librealmreact.so" is 32-bit instead of 64-bit
2019-02-05 15:59:14.831 8242-8274/com.test2 E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.test2, PID: 8242
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: "/data/data/com.test2/lib-main/librealmreact.so" is 32-bit instead of 64-bit
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
        at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:56)
        at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:40)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:764)
```

#### Steps & Code to Reproduce
react-native init test
cd test
npm install --save realm
react-native link realm
after running the emulator react-native run-android

#### Version of Realm and tooling

Realm version(s): 2.23.0

Realm Sync feature enabled: No

Android Studio version: 3.3

Android Build Tools version: 28.0.3

Gradle version: 4.7

Which Android version and device(s): Android emulator API 28 X86_64

**Comment by Zhuinden** [comment]
Doesn't this belong to `realm-js`?

**Comment by Zzumer** [comment]
I'm sorry for being inattentive
