### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: No implementation found for long io.realm.internal.Property.nativeGetFinalizerPtr() (

### ISSUE THREAD

**Issue by cscheidappguardus** [realm/realm-java#6431]
#### Goal
Initialize Realm model.

#### Actual Results
This issue only seems to happening occasionally on a LG G7, Android 8.0.0.  The device should use aarch64/arm64-v8a and I confirmed that our apk has a librealm-jni.so for arm64-v8a.

The error message (below) seems to be related to this issue:
https://github.com/realm/realm-java/issues/5960
Unfortunately, there is no resolution with the issue.

Other issues we found seem to be related to Proguard/DexGuard settings but we turned them off.

We have pursued all solutions mentioned in the other realm issues without luck. If you could provide any assistance in troubleshooting or things to try, we'd be very thankful.

Here the exception:
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : FATAL EXCEPTION: main
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : Process: us.appguard.trusticamobile.debug, PID: 16492
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : java.lang.UnsatisfiedLinkError: No implementation found for long io.realm.internal.Property.nativeGetFinalizerPtr() (tried Java_io_realm_internal_Property_nativeGetFinalizerPtr and Java_io_realm_internal_Property_nativeGetFinalizerPtr__)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.internal.Property.nativeGetFinalizerPtr(Native Method)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.internal.Property.<clinit>(Property.java:68)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.internal.Property.convertFromRealmFieldType(Property.java:77)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.internal.OsObjectSchemaInfo$Builder.addPersistedProperty(OsObjectSchemaInfo.java:62)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.DeviceInfoRealmProxy.createExpectedObjectSchemaInfo(DeviceInfoRealmProxy.java:449)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.DeviceInfoRealmProxy.<clinit>(DeviceInfoRealmProxy.java:94)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at io.realm.DeviceInfoRealmProxy.getSimpleClassName(DeviceInfoRealmProxy.java:472)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.utils.gson.GsonSingleton.<init>(GsonSingleton.java:101)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.utils.gson.GsonSingleton.getGson(GsonSingleton.java:62)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.utils.identification.IdentificationSingleton.<clinit>(IdentificationSingleton.java:89)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.utils.identification.IdentificationSingleton.checkDeviceStateIsDeprovisioned(IdentificationSingleton.java:391)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.utils.policy.PolicyItemEnforcer.runInitializationErrorCheck(PolicyItemEnforcer.java:135)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.utils.policy.PolicyItemEnforcer.runPolicyAndProvisioningChecks(PolicyItemEnforcer.java:92)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.ui.base.BaseActivity.onCreate(BaseActivity.java:48)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at us.appguard.trusticamobile.ui.splash.SplashActivity.onCreate(SplashActivity.java:107)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.Activity.performCreate(Activity.java:6980)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2837)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2959)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.ActivityThread.-wrap11(Unknown Source:0)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:105)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.os.Looper.loop(Looper.java:164)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:6759)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
2019-02-15 08:42:15.781	ERROR:	AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
#### Steps & Code to Reproduce
Unfortunately we can't share our code.

#### Version of Realm and tooling

Realm version(s): ?
io.realm:realm-gradle-plugin:4.3.3 (we also tried version 5.9.0 with the same results)

Realm Sync feature enabled: Yes/No
Yes

Android Studio version: 3.1.1

Android Build Tools version: 28.0.2

Gradle version: 4.6

Which Android version and device(s): ?
LG G7, Android 8.0.0

**Comment by cmelchior** [comment]
It could hint at the native code not being loaded, but that should only happen if `Realm.init()` isn't called. When in the app lifecycle do you call this?

`Realm.init()` is practically free if already called, so you could attempt to put it into all your activities onCreate, but that doesn't really explain why you are seeing this in the first place.

What exactly are you doing in `checkDeviceStateIsDeprovisioned`? It looks like you are doing something with GSON which uses reflection.

**Comment by cmelchior** [comment]
Closing due to inactivity. Please re-open if this is still an issue.
