### ISSUE TITLE
Configurations cannot be different if used to open the same file. 

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-java#6440]
When i am go back from app and enter again (application not destroyed) i have a check if the user logged in and then i set Realm configuration. 
But i receive this error, i don't understand why, the configurations build from the same method and look same in the error report.
```
 New configuration: 
    realmDirectory: /data/user/0/com.stockmanagment.next.app/files/realm-object-server/6c33d42a0710ddb347ce55de8e7e7917/6c33d42a0710ddb347ce55de8e7e7917
    realmFileName : project-name
    canonicalPath: /data/data/com.stockmanagment.next.app/files/realm-object-server/6c33d42a0710ddb347ce55de8e7e7917/6c33d42a0710ddb347ce55de8e7e7917/project-name
    key: [length: 0]
    schemaVersion: 1
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: FULL
    schemaMediator: io.realm.DefaultRealmModuleMediator@639520ec
    readOnly: false
    compactOnLaunch: null
    serverUrl: realms://stock-and-inventory.us1a.cloud.realm.io/6c33d42a0710ddb347ce55de8e7e7917/project-name
    user: {UserId: 6c33d42a0710ddb347ce55de8e7e7917, AuthUrl: https://stock-and-inventory.us1a.cloud.realm.io/auth}
    errorHandler: io.realm.SyncManager$1@b799407
    deleteRealmOnLogout: false
    waitForInitialRemoteData: false
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 

    Cached configuration: 
    realmDirectory: /data/user/0/com.stockmanagment.next.app/files/realm-object-server/6c33d42a0710ddb347ce55de8e7e7917/6c33d42a0710ddb347ce55de8e7e7917
    realmFileName : project-name
    canonicalPath: /data/data/com.stockmanagment.next.app/files/realm-object-server/6c33d42a0710ddb347ce55de8e7e7917/6c33d42a0710ddb347ce55de8e7e7917/project-name
    key: [length: 0]
    schemaVersion: 1
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: FULL
    schemaMediator: io.realm.DefaultRealmModuleMediator@639520ec
    readOnly: false
    compactOnLaunch: null
    serverUrl: realms://stock-and-inventory.us1a.cloud.realm.io/6c33d42a0710ddb347ce55de8e7e7917/project-name
    user: {UserId: 6c33d42a0710ddb347ce55de8e7e7917, AuthUrl: https://stock-and-inventory.us1a.cloud.realm.io/auth}
    errorHandler: io.realm.SyncManager$1@b799407
    deleteRealmOnLogout: false
    waitForInitialRemoteData: false
```

Method i using to get configuration:
```
private SyncConfiguration getSyncConfiguration() {

        String path = "/~/project-name";
        String url = AppConsts.REALM_URL + path;

        SyncConfiguration.Builder config = SyncUser.current().createConfiguration(url)
                .fullSynchronization()
                .schemaVersion(1)
                .initialData(realm -> {
                    createDefaultStore(realm);
                });


        return config.build();
    }

Realm.setDefaultConfiguration(getSyncConfiguration());
```

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: Yes

Android Studio version: 3.3.1?

Gradle version:4.10.1 ?

**Comment by cmelchior** [comment]
Without being 100% sure, I suspect that `initialData` block is the problem. You are creating two different anonymous classes in Java which means that the default `equals()` check will return false for them.

Have you tried extracting the lambda into a static variable that is re-used?

**Comment by pavelpoley** [comment]
@cmelchior i have removed `initialData` and it is work now

**Comment by Zhuinden** [comment]
The trick is that you should implement `hashCode` and `equals` in your initialData

**Comment by pavelpoley** [comment]
@Zhuinden I am not really understand, i need to extend Realm.Transaction class and override equals?

**Comment by Zhuinden** [comment]
implement, but yes

**Comment by pavelpoley** [comment]
@Zhuinden But what if i logged in synced with Realm then switch to another Realm then switched back to first one, in the first time i have initial data to create some default objects , in the second i don't have initial data?

`private SyncConfiguration createSyncConfiguration(String projectName, boolean isExist) {

        String path = "/~/" + projectName;
        String url = AppConsts.REALM_URL + path;

        SyncConfiguration.Builder config = SyncUser.current().createConfiguration(url)
                .fullSynchronization()
                .schemaVersion(1);

        if (!isExist)
            config.initialData(initial);

        return config.build();
    }`

**Comment by Zhuinden** [comment]
I'd assume the trick is that you should specify the initial data instead of a random `isExist` boolean flag.
