### ISSUE TITLE
 No outside changes to a Realm is allowed while iterating a living Realm collection while iterating realmlist in coroutines context

### ISSUE THREAD

**Issue by CuirMoustachu** [realm/realm-java#6473]
#### Goal
I'm trying to iterate over a RealmList in a coroutines context. A new coroutines is launched everytime when a change occured in the realm list

#### Actual Results
```
java.util.ConcurrentModificationException: No outside changes to a Realm is allowed while iterating a living Realm collection.
        at io.realm.internal.OsResults$Iterator.checkValid(OsResults.java:116)
        at io.realm.internal.OsResults$Iterator.hasNext(OsResults.java:74)
```
iteratorOsResults is null

#### Steps & Code to Reproduce
```

var job = Job()
var uiScope = CoroutineScope(Dispatchers.Main + job)

override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val realm = Realm.getDefaultInstance()
        val images = realm.where<Image>().findAllAsync()
        images.addChangeListener(RealmChangeListener {
            if(it!=null){
                displayImages(it)
            }
        })
    }

    fun displayImages(images: List<Image>){
        uiScope.launch {
            images.forEach { // <- CRASH OCCURS HERE
                delay(2000) // Simulate suspend operation
            }
        }
    }
```

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: No

Kotlin version: 1.3.21
Kotlin coroutines version: 1.1.1

**Comment by Zhuinden** [comment]
``` kotlin
/**
 * Performs the given [action] on each element.
 */
@kotlin.internal.HidesMembers
public inline fun <T> Iterable<T>.forEach(action: (T) -> Unit): Unit {
    for (element in this) action(element)
}
```

Interesting, Kotlin seems to use iterators so this shouldn't happen. 

However you can try using `images.createSnapshot().foreach` and see if it helps.

**Comment by CuirMoustachu** [comment]
Yes it helps thank you. Did you reproduce it ?

**Comment by CuirMoustachu** [comment]
It happens only when a suspend operation is inside the forEach and after the first iteration. The list is no longer valid after the first iteration because of the suspend operation apparently.

**Comment by bmunkholm** [comment]
Closing as it appears resolved.
