### ISSUE TITLE
Native Crash Deleting Data

### ISSUE THREAD

**Issue by mandrachek** [realm/realm-java#6480]
Realm 5.8.0 - User is on a Samsung Galaxy S5, Android 6.0.1. Haven't been able to reproduce. Crashlytics reports ~720MB of ram free, stack trace follows:

```
Caused by java.lang.OutOfMemoryError: std::bad_alloc in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 142 
       at io.realm.internal.OsResults.nativeClear(OsResults.java)
       at io.realm.internal.OsResults.clear(OsResults.java:371)
       at io.realm.OrderedRealmCollectionImpl.deleteAllFromRealm(OrderedRealmCollectionImpl.java:223)
       at io.realm.RealmResults.deleteAllFromRealm(RealmResults.java:72)
       at IntentService$13.execute(IntentService.java:768)
       at io.realm.Realm.executeTransaction(Realm.java:1493)
       at IntentService.getVillages(IntentService.java:763)
       at IntentService.doWork(IntentService.java:108)
       at BackgroundIntentService.onHandleWork(BackgroundIntentService.java:83)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

The code:

```
// pulls list of categories from the server, there's about a dozen
final List<ChecklistCategory> checklistCategories = checklistCategoryResponse.body();

if (checklistCategories != null && !checklistCategories.isEmpty()) {
       try (Realm realm = Realm.getDefaultInstance()) {
         realm.executeTransaction(new Realm.Transaction() {
           @Override
           public void execute(Realm realm) {
             // delete all the old items.
             realm.where(ChecklistItemStatus.class).findAll().deleteAllFromRealm();
             realm.where(ChecklistItem.class).findAll().deleteAllFromRealm();
             realm.where(Checklist.class).findAll().deleteAllFromRealm();
             realm.where(ChecklistCategory.class).findAll().deleteAllFromRealm();
             // set the new ones.
             realm.copyToRealmOrUpdate(checklistCategories);
           }
         });
       }
     }
}
``````

**Comment by cmelchior** [comment]
I'm not exactly sure what to say. Something in your app is using too much memory. Maybe you are inserting too much data? Maybe that memory is being used on something else. I don't know how accurate Crashlytics is in reporting native memory usage.

You can also try to rewrite the delete code to `realm.delete(ChecklistItemStatus.class)` which doesn't have the overhead of running a query first.

**Comment by cmelchior** [comment]
Closing due to inactivity. If this is still a problem please reopen the issue.
