### ISSUE TITLE
 java.lang.RuntimeException: Unable to create application com.hmbl.hm.OtherApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null

### ISSUE THREAD

**Issue by BryceCui** [realm/realm-java#6494]
this is my  log
```
2019-04-17 11:21:12.861 17566-17566/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hmbl.hm:pushcore, PID: 17566
    java.lang.RuntimeException: Unable to create application com.hmbl.hm.OtherApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6637)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:184)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:123)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
        at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
        at io.realm.Realm.initializeRealm(Realm.java:322)
        at io.realm.Realm.init(Realm.java:265)
        at com.hmbl.hm.common.HMApplication.onCreate(HMApplication.java:163)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
```

* Tinker is used in the project and inherits DefaultApplicationLike. It is used in the oncreate method as follows.
```
  Realm.init(mContext);
  RealmConfiguration config = new 
  RealmConfiguration.Builder().name("HeMa.realm").schemaVersion(0).build();
  Realm.setDefaultConfiguration(config);
```
 I want to know what is the cause of this problem，Please inform thank you！

**Comment by jovezhougang** [comment]
------------------ 原始邮件 ------------------
发件人: "崔鹏宇"<notifications@github.com>; 
发送时间: 2019年4月17日(星期三) 中午11:32
收件人: "realm/realm-java"<realm-java@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [realm/realm-java]  java.lang.RuntimeException: Unable to createapplication com.hmbl.hm.OtherApplication:com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null(#6494)




this is my  log
 2019-04-17 11:21:12.861 17566-17566/? E/AndroidRuntime: FATAL EXCEPTION: main     Process: com.hmbl.hm:pushcore, PID: 17566     java.lang.RuntimeException: Unable to create application com.hmbl.hm.OtherApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6637)         at android.app.ActivityThread.-wrap2(Unknown Source:0)         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)         at android.os.Handler.dispatchMessage(Handler.java:108)         at android.os.Looper.loop(Looper.java:166)         at android.app.ActivityThread.main(ActivityThread.java:7529)         at java.lang.reflect.Method.invoke(Native Method)         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)      Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null         at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:184)         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)         at android.app.ActivityThread.-wrap2(Unknown Source:0)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)          at android.os.Handler.dispatchMessage(Handler.java:108)          at android.os.Looper.loop(Looper.java:166)          at android.app.ActivityThread.main(ActivityThread.java:7529)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)       Caused by: java.lang.reflect.InvocationTargetException         at java.lang.reflect.Method.invoke(Native Method)         at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180)         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)          at android.app.ActivityThread.-wrap2(Unknown Source:0)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)          at android.os.Handler.dispatchMessage(Handler.java:108)          at android.os.Looper.loop(Looper.java:166)          at android.app.ActivityThread.main(ActivityThread.java:7529)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)       Caused by: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so         at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:123)         at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)         at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)         at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)         at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)         at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)         at io.realm.Realm.initializeRealm(Realm.java:322)         at io.realm.Realm.init(Realm.java:265)         at com.hmbl.hm.common.HMApplication.onCreate(HMApplication.java:163)         at java.lang.reflect.Method.invoke(Native Method)          at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180)          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)          at android.app.ActivityThread.-wrap2(Unknown Source:0)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)          at android.os.Handler.dispatchMessage(Handler.java:108)          at android.os.Looper.loop(Looper.java:166)          at android.app.ActivityThread.main(ActivityThread.java:7529)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)    
Tinker is used in the project and inherits DefaultApplicationLike. It is used in the oncreate method as follows.
    Realm.init(mContext);   RealmConfiguration config = new    RealmConfiguration.Builder().name("HeMa.realm").schemaVersion(0).build();   Realm.setDefaultConfiguration(config);  
I want to know what is the cause of this problem，Please inform thank you！
 
&mdash;

**Comment by Zhuinden** [comment]
> Caused by: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so

**Comment by cmelchior** [comment]
Yes, you need to verify that the `.so` files are correctly packaged inside the APK.
