### ISSUE TITLE
Crash on deleteRealm only on Huawei

### ISSUE THREAD

**Issue by jphidenis** [realm/realm-java#6495]
#### Goal
We would like to be crash free on Huawei devices. But we have a crashes (exclusive to Huaweis)
on Realm.deleteRealm(config)

#### Actual Results
```
Caused by java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file: /data/data/eu.qonto.qonto/files/qontodb.realm
       at io.realm.BaseRealm.deleteRealm(BaseRealm.java:691)
       at io.realm.Realm.deleteRealm(Realm.java:1792)
       at com.qonto.qonto.data.dao.AppDatabase.getRealmInstance(AppDatabase.java:44)
       at com.qonto.qonto.data.dao.AppDatabase.initRealm(AppDatabase.java:35)
       at com.qonto.qonto.data.dao.AppDatabase.(SourceFile:23)
       at com.qonto.qonto.database.DatabaseModule.provideAppDatabase(DatabaseModule.java:14)
       at com.qonto.qonto.database.DatabaseModule_ProvideAppDatabaseFactory.proxyProvideAppDatabase(DatabaseModule_ProvideAppDatabaseFactory.java:49)
       at com.qonto.qonto.database.DatabaseModule_ProvideAppDatabaseFactory.provideInstance(DatabaseModule_ProvideAppDatabaseFactory.java:35)
       at com.qonto.qonto.database.DatabaseModule_ProvideAppDatabaseFactory.get(DatabaseModule_ProvideAppDatabaseFactory.java:28)
       at com.qonto.qonto.database.DatabaseModule_ProvideAppDatabaseFactory.get(DatabaseModule_ProvideAppDatabaseFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.qonto.qonto.data.repository.LoginRepository_Factory.provideInstance(LoginRepository_Factory.java:71)
       at com.qonto.qonto.data.repository.LoginRepository_Factory.get(LoginRepository_Factory.java:48)
       at com.qonto.qonto.data.repository.LoginRepository_Factory.get(LoginRepository_Factory.java:14)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.qonto.qonto.api.di.ApiModule_ProvidePubSubControllerFactory.provideInstance(ApiModule_ProvidePubSubControllerFactory.java:81)
       at com.qonto.qonto.api.di.ApiModule_ProvidePubSubControllerFactory.get(ApiModule_ProvidePubSubControllerFactory.java:55)
       at com.qonto.qonto.api.di.ApiModule_ProvidePubSubControllerFactory.get(ApiModule_ProvidePubSubControllerFactory.java:17)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.qonto.qonto.QontoApp.onCreate(QontoApp.java:88)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6636)
       at android.app.ActivityThread.access$2000(ActivityThread.java:268)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7539)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
#### Version of Realm and tooling

Realm version(s): 5.10.0

Realm Sync feature enabled: No

Android Studio version: 3.4 RC3

Android Build Tools version: 28.0.3

Gradle version: 5.3.1

Which Android version and device(s): Only Huawei (Honor 8X, P20 pro, P20, Mate9, Honor 9, Mate 20 Pro, nova 3, P10 plus, Honor View 10, Mate 10 Pro, honor 10 lite, Mate 9 Pro, HONOR View 20, Marte 20) : 100% of them running on OS 9.

Here is our AppDatabase Class : 
```
class AppDatabase(
    val context: Context,
    val qontoPrefs: SharedPreferencesQonto
) {

    private lateinit var realm: Realm

    init {
        if (Looper.myLooper() == Looper.getMainLooper()) {
            initRealm()
        } else {
            runBlocking(Dispatchers.Main) {
                initRealm()
            }
        }
    }

    private fun initRealm() {
        Realm.init(context)
        val config = getRealmConfig()
        Realm.setDefaultConfiguration(config)
        realm = getRealmInstance(config)
    }

    private fun getRealmInstance(config: RealmConfiguration) =
        try {
            Realm.getDefaultInstance()
        } catch (e: RealmFileException) {
            Timber.e(e, "Error initializing Realm database")
            try {
                Realm.deleteRealm(config)
                qontoPrefs.removeSessionMembership()
            } catch (e: IllegalStateException) {
                Timber.e(
                    e,
                    """
                    Error deleting the database:
                    - Number of global instances ${Realm.getGlobalInstanceCount(config)}
                    - Number of local instances ${Realm.getLocalInstanceCount(config)}
                    - Current thread id: ${Thread.currentThread().id}
                    """.trimIndent()
                )
                throw e
            }
            Realm.getDefaultInstance()
        }

    private fun getRealmConfig(): RealmConfiguration {
        return RealmConfiguration.Builder()
            .name(RealmUtils.REALM_FILENAME)
            .schemaVersion(1)
            .encryptionKey(RealmUtils().getEncryptionKey(qontoPrefs))
            .deleteRealmIfMigrationNeeded()
            .migration { _, _, _ ->
                qontoPrefs.removeSessionMembership()
            }
            .build()
    }

    fun deleteAll() = realm.executeTransaction {
        realm.deleteAll()
    }
}
```

**Comment by jphidenis** [comment]
Could you help us on that matter? This is our #1 source of crash in app

**Comment by cmelchior** [comment]
It would be helpful to understand what is throwing the `RealmFileException` file exception in the first place. Without understanding the root cause it is difficult to guess what the underlying problem is.

**Comment by cmelchior** [comment]
Closing due to inactivity. If this is still an issue, feel free to reopen the issue.
