### ISSUE TITLE
Realm file decryption failed error

### ISSUE THREAD

**Issue by pkhivesara** [realm/realm-java#6503]
Realm on Android fails to open the encrypted database on random devices.

#### Actual Results
Unable to open a realm at path '/data/data/xxx.xxx.xxx/files/default.realm': Realm file decryption failed Path:. (Realm file decryption failed Path: /data/data/xxx.xxx.xxx/files/default.realm) (/data/data/xxx.xxx.xxx/files/default.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
       at io.realm.Realm.getInstance(Realm.java:428)

#### Steps & Code to Reproduce
The app crashes with the above exception on the Google Pixel 3XL running Android 9 and Note 4 running Android 6, however it runs fine on OnePlus5t and 6 running Android 9 and Galaxy s9 running Android 8.

Here is the code i am using for getting the keys for encrypting and decrypting the database

```
@TargetApi(23)
public class EncryptionKeyStore {

    private static boolean isApi23() {
        return (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M);
    }

    public static byte[] generateOrGetRealmEncryptionKey(Context context) {
        ensureInstance();

        Context appContext = context.getApplicationContext();
        byte[] encryptedRealmKey = sInstance.loadEncryptedRealmKey(appContext);
        if (encryptedRealmKey == null || !sInstance.keystoreContainsEncryptionKey()) {
            final byte[] realmKey = sInstance.generateKeyForRealm();
            sInstance.generateKeyInKeystore(context);
            encryptedRealmKey = sInstance.encryptAndSaveKeyForRealm(appContext, realmKey);
            Arrays.fill(realmKey, (byte) 0);
        }
        return sInstance.decryptKeyForRealm(encryptedRealmKey);
    }

    @SuppressLint("CommitPrefEdits")
    public static void reset(Context context) {
        ensureInstance();
        sInstance.getPreference(context).edit().clear().apply();
    }

    private static void ensureInstance() {
        if (sInstance == null) {
            sInstance = new EncryptionKeyStore();
        }
    }

    private boolean keystoreContainsEncryptionKey() {
        try {
            return mKeyStore.containsAlias(KEY_ALIAS);
        } catch (KeyStoreException e) {
            throw new RuntimeException(e);
        }
    }

    private byte[] generateKeyForRealm() {
        final byte[] keyForRealm = new byte[RealmConfiguration.KEY_LENGTH];
        mSecureRandom.nextBytes(keyForRealm);
        return keyForRealm;
    }

    private void generateKeyInKeystore(Context context) {
        try {
            if (isApi23()) {
                final KeyGenerator keyGenerator;
                keyGenerator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER_NAME);

                final KeyGenParameterSpec keySpec = new KeyGenParameterSpec.Builder(
                        KEY_ALIAS,
                        KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                        .setBlockModes(KeyProperties.BLOCK_MODE_CBC)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_PKCS7)
                        .setUserAuthenticationRequired(false)
                        .build();

                try {
                    keyGenerator.init(keySpec);
                } catch (InvalidAlgorithmParameterException e) {
                    throw new RuntimeException(e);
                }
                keyGenerator.generateKey();
            } else {
                Calendar start = new GregorianCalendar();
                Calendar end = new GregorianCalendar();
                end.add(Calendar.YEAR, 25);

                KeyPairGeneratorSpec spec =
                        new KeyPairGeneratorSpec.Builder(context)
                                .setAlias(KEY_ALIAS)
                                .setSubject(new X500Principal("CN=" + KEY_COMMON_NAME))
                                .setSerialNumber(BigInteger.valueOf(1337))
                                .setStartDate(start.getTime())
                                .setEndDate(end.getTime())
                                .build();

                final KeyPairGenerator kpGenerator = KeyPairGenerator.getInstance(TYPE_RSA, KEYSTORE_PROVIDER_NAME);
                kpGenerator.initialize(spec);
                kpGenerator.generateKeyPair();
            }
        } catch (NoSuchAlgorithmException | NoSuchProviderException | InvalidAlgorithmParameterException e) {
            throw new RuntimeException(e);
        }
    }

    private KeyStore prepareKeyStore() {
        try {
            KeyStore ks = KeyStore.getInstance(KEYSTORE_PROVIDER_NAME);
            ks.load(null);
            return ks;
        } catch (KeyStoreException | NoSuchAlgorithmException | CertificateException | IOException e) {
            throw new RuntimeException(e);
        }
    }

    private Cipher prepareCipher() {
        final Cipher cipher;
        try {
            cipher = Cipher.getInstance(CIPHER);
        } catch (NoSuchAlgorithmException | NoSuchPaddingException e) {
            throw new RuntimeException(e);
        }
        return cipher;
    }

    private byte[] encryptAndSaveKeyForRealm(Context context, byte[] keyForRealm) {
        final KeyStore ks = prepareKeyStore();
        final Cipher cipher = prepareCipher();

        final byte[] iv;
        final byte[] encryptedKeyForRealm;
        try {
            final Key key;
            if (isApi23()) {
                key = ks.getKey(KEY_ALIAS, null);
            } else {
                final KeyStore.PrivateKeyEntry privateKeyEntry;
                try {
                    privateKeyEntry = (KeyStore.PrivateKeyEntry) ks.getEntry(KEY_ALIAS, null);
                    key = privateKeyEntry.getCertificate().getPublicKey();
                } catch (UnrecoverableEntryException e) {
                    throw new RuntimeException("key for encryption is invalid", e);
                }
            }
            cipher.init(Cipher.ENCRYPT_MODE, key);

            encryptedKeyForRealm = cipher.doFinal(keyForRealm);
            iv = cipher.getIV();
        } catch (InvalidKeyException | UnrecoverableKeyException | NoSuchAlgorithmException
                | KeyStoreException | BadPaddingException | IllegalBlockSizeException e) {
            throw new RuntimeException("key for encryption is invalid", e);
        }

        final int ivLength = ((iv != null) ? iv.length : 0);
        final byte[] ivAndEncryptedKey = new byte[Integer.SIZE + ivLength + encryptedKeyForRealm.length];

        final ByteBuffer buffer = ByteBuffer.wrap(ivAndEncryptedKey);
        buffer.order(ORDER_FOR_ENCRYPTED_DATA);
        buffer.putInt(ivLength);
        if (ivLength > 0) {
            buffer.put(iv);
        }
        buffer.put(encryptedKeyForRealm);
        saveEncryptedRealmKey(context, ivAndEncryptedKey);
        return ivAndEncryptedKey;
    }

    private byte[] decryptKeyForRealm(byte[] ivAndEncryptedKey) {
        final Cipher cipher = prepareCipher();
        final KeyStore ks = prepareKeyStore();

        final ByteBuffer buffer = ByteBuffer.wrap(ivAndEncryptedKey);
        buffer.order(ORDER_FOR_ENCRYPTED_DATA);

        final int ivLength = buffer.getInt();
        final byte[] iv = (ivLength > 0) ? new byte[ivLength] : null;
        final byte[] encryptedKey = new byte[ivAndEncryptedKey.length - Integer.SIZE - ivLength];

        if (iv != null) {
            buffer.get(iv);
        }
        buffer.get(encryptedKey);

        try {
            final Key key = ks.getKey(KEY_ALIAS, null);

            if (iv != null) {
                final IvParameterSpec ivSpec = new IvParameterSpec(iv);
                cipher.init(Cipher.DECRYPT_MODE, key, ivSpec);
            } else {
                cipher.init(Cipher.DECRYPT_MODE, key);
            }

            return cipher.doFinal(encryptedKey);
        } catch (InvalidKeyException e) {
            throw new RuntimeException("key is invalid.");
        } catch (UnrecoverableKeyException | NoSuchAlgorithmException | BadPaddingException
                | KeyStoreException | IllegalBlockSizeException | InvalidAlgorithmParameterException e) {
            throw new RuntimeException(e);
        }
    }

    private byte[] loadEncryptedRealmKey(Context context) {
        final SharedPreferences pref = getPreference(context);
        final String encodedEncryptionKey = pref.getString(STORAGE_PREF_KEY, null);
        if (encodedEncryptionKey == null) {
            return null;
        }
        return Base64.decode(encodedEncryptionKey, Base64.DEFAULT);
    }

    private void saveEncryptedRealmKey(Context context, byte[] ivAndEncryptedKey) {
        String encodedEncryptionKey = Base64.encodeToString(ivAndEncryptedKey, Base64.NO_WRAP);
        getPreference(context).edit()
                .putString(STORAGE_PREF_KEY, encodedEncryptionKey)
                .apply();
    }

    private SharedPreferences getPreference(Context context) {
        return context.getSharedPreferences(STORAGE_PREF_NAME, Context.MODE_PRIVATE);
    }

}
```

I am lost as to how to resolve this.

**Comment by bmunkholm** [comment]
How many % of your app installs are experiencing this issue and how often? Do you have any stats that shows which devices/OS-versions are most affected?

**Comment by pkhivesara** [comment]
It is just one Verizon Pixel 3XL running Android 9 which is causing trouble. And since i don't have physical access to the device, I can't really debug it. Any suggestions as how to proceed?

**Comment by bmunkholm** [comment]
@pkhivesara I thought originally you said it also occurs on Note 4 with Android 6? 
It's really hard for both you and us if there is no way to reproduce the issue. Somehow you need to debug your code above to ensure that the key you use to encrypt the realm is the same you use to decrypt it. All that code it outside the scope of realm and not something we can help you debug.

**Comment by fahimjubayer-dsi** [comment]
I am facing the same issue on Xiaomi Redmi Note 6 Pro running Android 9.

**Comment by cmelchior** [comment]
Unless we have a repo case it is hard to tell if you are providing the proper encryption key or not. With the Realm Java 6.0.1 release, there are no know bugs in the encryption layer.

**Comment by cmelchior** [comment]
Closing as outdated. If this still happens please re-open the issue, but we do need some way of reproducing this in order to rule out that it isn't the wrong encryption key being used.

**Comment by AzhimkulovAzamat** [comment]
I upgraded Realm Java to version 6.0.1. It didn't help, I still see this issue.

**Comment by NeuronKarrde** [comment]
Have the same issue on Huawei P20 lite(android 9). all other devices work fine. 
Also If try create db without EncryptionKey, have issue Invalid mnemonic. top_ref[0]
