### ISSUE TITLE
Is there any case that close realm except for invoking realm.close()?

### ISSUE THREAD

**Issue by wlxyhy** [realm/realm-java#6514]
During life circle of Activity, I open realm in onCreate() , close realm in onStop() and, open realm in onStart() after  onStop() invoked. It looks no problem, however, our users come up with this crash:
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
	at io.realm.BaseRealm.checkIfValid(SourceFile:433)
	at io.realm.RealmList.c(SourceFile:739)
	at io.realm.RealmList.size(SourceFile:554)
	at com.easilydo.mail.ui.emaildetail.EmailDetailPageFragment.a(SourceFile:1165)
	at com.easilydo.mail.ui.emaildetail.EmailDetailPageFragment.a(SourceFile:1152)
	at com.easilydo.mail.ui.emaildetail.EmailDetailPageFragment.toggleShowContactLayouts(SourceFile:827)
	at com.easilydo.mail.databinding.FragmentEmailDetailPageBindingImpl$OnClickListenerImpl.onClick(SourceFile:1005)
	at android.view.View.performClick(View.java:5609)
	at android.view.View$PerformClick.run(View.java:22263)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
It seems that the realm is closed when user click button, it's obvious the realm.close() wasn't invoked at that time, is there any other case make realm closed?

**Comment by Zhuinden** [comment]
> It seems that the realm is closed when user click button, it's obvious the realm.close() wasn't invoked at that time, is there any other case make realm closed?

Try to put your app in background, bring foreground, and THEN press the button

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we only use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Forum](https://forums.realm.io/).

Thanks for your help!
