### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Out of range Bulk update!

### ISSUE THREAD

**Issue by idok595** [realm/realm-java#6521]
#### Goal
To update the same property i query 

#### Actual Results
```
 Caused by: java.lang.ArrayIndexOutOfBoundsException: Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 334(requested: 20103 valid: 20103)
        at io.realm.internal.OsResults.nativeSetBoolean(Native Method)
        at io.realm.internal.OsResults.setBoolean(OsResults.java:408)
        at io.realm.RealmResults.setBoolean(RealmResults.java:270)
```

#### Steps & Code to Reproduce
````
realm.where(Product.class)
                .equalTo("priceInfoUpToDate",false)
                .findAll()
                .setBoolean("priceInfoUpToDate",true);
````
#### Version of Realm and tooling

Realm version(s): ?
5.8.0

Realm Sync feature enabled: Yes/No
No
Android Build Tools version: ?
3.4.0
Gradle version: ?
3.4.0
Which Android version and device(s): ?
Android 9 Galaxy S10+

**Comment by Zhuinden** [comment]
This is fixed in 5.11.0 .
