### ISSUE TITLE
Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

### ISSUE THREAD

**Issue by adi9090** [realm/realm-java#6530]
#### Goal

Solve mentioned issue.
#### Actual Results

I was developing this app for a while and everything was working fine with Realm, no issues at all. After I needed to set app to be system application and after starting it I've got this error. 
Please note that before posting this I've read all issues of mentioning of this error and almost all suggested that database is corrupted which should not be case here.
This is happening on Android TV box running Android Pie. I've deleted application, have done factory reset of the box and on calling Realm.getDefaultInstance() I'm getting this crash.
As I said, everything was working fine until I've made this app as system app, before that no issues at all. Also all Realm related code is extracted in separate Android module.

This is the realm configuration that I'm using:
`RealmConfiguration.Builder()
            .directory(externalCacheDir)
            .deleteRealmIfMigrationNeeded()
            .modules(Realm.getDefaultModule(), CacheRealmModule())
            .build()`

Below is exception stack trace which is happening on calling Realm.getDefaultInstance():
`io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:136)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)`

#### Version of Realm and tooling

Realm version(s): 5.11.0

**Comment by adi9090** [comment]
Just have find out that if I remove `android:sharedUserId="android.uid.system"` from manifest file and sign app with same JKS file that OS image is build with, it is working fine.

**Comment by adi9090** [comment]
Issue is solved with configuring selinux for our app. Now everything is working fine.
