### ISSUE TITLE
io.realm.exceptions.RealmFileException: Unable to open a realm at path

### ISSUE THREAD

**Issue by CnyNer** [realm/realm-java#6555]
#### Error
io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.xx.qq/files/xx_realm_v4_11_0.realm.lock': open() failed: Too many open files Path: /data/data/com.xx.qq/files/xx_realm_v4_11_0.realm.lock. (open("/data/data/com.xx.qq/files/xx_realm_v4_11_0.realm.lock") failed: Too many open files Path: /data/data/com.xx.qq/files/xx_realm_v4_11_0.realm.lock) (/data/data/com.xx.qq/files/xx_realm_v4_11_0.realm.lock) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
	at io.realm.BaseRealm.<init>(BaseRealm.java:135)
	at io.realm.BaseRealm.<init>(BaseRealm.java:103)
	at io.realm.Realm.<init>(Realm.java:163)
	at io.realm.Realm.createInstance(Realm.java:499)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
	at io.realm.Realm.getDefaultInstance(Realm.java:407)
	at com.xx.qq.util.RealmHelper.getInstance(RealmHelper.java:24)
	at com.xx.qq.AccountManager.getCurrentAccountCopyFromRealm(AccountManager.java:159)
	at com.xx.qq.util.Util.getBaseRequestParams(Util.java:1634)
	at com.xx.qq.network.HttpInterceptor.changeToStandardRequest(HttpInterceptor.java:192)
	at com.xx.qq.network.HttpInterceptor.intercept(HttpInterceptor.java:77)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

#### Version of Realm and tooling

Realm version(s): ?
5.9.1

Realm Sync feature enabled: Yes/No
No

Android Studio version: ?
3.3.1

Android Build Tools version: ?
3.0.1

Gradle version: ?
4.4

Which Android version and device(s): ?
vivo xiaomi and more

**Comment by Zhuinden** [comment]
"Too many open files" means you are probably using `Schedulers.newThread()` for your Realm operations, instead of a dedicated single-thread executor exposed as a scheduler.

**Comment by CnyNer** [comment]
How to solve？

**Comment by Zhuinden** [comment]
Don't use Schedulers.newThread().

**Comment by CnyNer** [comment]
but i dont user Schedulers.newThread() in our project。

**Comment by cmelchior** [comment]
It might be the same underlying cause as https://github.com/realm/realm-java/issues/6569 . Please check if any of that applies to you.

**Comment by cmelchior** [comment]
Closing due to inactivity. Please reopen this if it is still an issue.
