### ISSUE TITLE
E/REALM_JNI: jni: ThrowingException 5, mmap() failed: Out of memory size: 369098752 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

### ISSUE THREAD

**Issue by ilshatL** [realm/realm-java#6558]
#### Goal

Load data without Out Of Memory error

#### Actual Results

`2019-07-16 08:16:46.589 24058-24265/com.lx2.crm E/REALM_JNI: jni: ThrowingException 5, mmap() failed: Out of memory size: 369098752 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101, .
2019-07-16 08:16:46.589 24058-24265/com.lx2.crm E/REALM_JNI: Exception has been thrown: Unrecoverable error. mmap() failed: Out of memory size: 369098752 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
2019-07-16 08:16:46.595 24058-24058/com.lx2.crm D/InputTransport: Input channel constructed: fd=85
2019-07-16 08:16:46.596 24058-24058/com.lx2.crm D/ViewRootImpl@97f9606[Toast]: setView = android.widget.LinearLayout{153a21d V.E...... ......I. 0,0-0,0} TM=true MM=false
2019-07-16 08:16:46.596 24058-24058/com.lx2.crm V/Toast: Text: Иагр in android.widget.Toast$TN@b6f0c92
2019-07-16 08:16:46.597 24058-24265/com.lx2.crm E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.lx2.crm, PID: 24058
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 369098752 offset: 0 in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:244)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
        at io.realm.Realm.getDefaultInstance(Realm.java:332)
        at com.lx2.crm.TyreRealmLoad.doInBackground(TyreRealmLoad.java:57)
        at com.lx2.crm.TyreRealmLoad.doInBackground(TyreRealmLoad.java:20)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)` 

#### Steps & Code to Reproduce

Im trying to load large json file divided to 3 parts in async task. Each of them 60-70Mb. My async task:

```
public class TradeinGetAsyncCarbayRefs extends AsyncTask<String, String, JSONObject> {
    Context _ctx;
    ProgressDialog progressDialog;
    realmCallback callback = null;
    TradeinGetAsyncCarbayRefs(Context c){
        _ctx = c;
    }
    TradeinGetAsyncCarbayRefs(Context c, realmCallback callback){
        _ctx = c;
        this.callback = callback;
    }

    protected void onPreExecute() {
        super.onPreExecute();
        progressDialog = new ProgressDialog(_ctx);
        progressDialog.setCancelable(false);
        progressDialog.show();

    }

    protected JSONObject doInBackground(final String... params) {
        Log.d("JsonGet", "Старт загрузки справочника Карбей");
        Realm realm = Realm.getDefaultInstance();
        try{
            progressDialog.setMessage("Очистка старых справочников...");
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.delete(TradeInCarbay.class);
                }
            });
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.delete(CarbayBrand.class);
                }
            });
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.delete(CarbayModels.class);
                }
            });
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.delete(CarbayModifications.class);
                }
            });
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.delete(CarbayDataLink.class);
                }
            });
            Log.d("JsonGet", "Справочники удалены!");
            // Insert multiple items using an InputStream
            progressDialog.setMessage("Загрузка справочника Карбей...");
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    try {
                        URL url = new URL(params[0]);
                        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                        connection.connect();
                        InputStream stream = connection.getInputStream();
                        realm.createAllFromJson(TradeInCarbay.class, stream);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            });

            Log.d("JsonGet", "Старт загрузки регистра Карбей1");
            progressDialog.setMessage("Загрузка регистра Карбей часть 1...");
    
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    try {
                        URL url = new URL(params[1]);
                        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                        connection.connect();
                        InputStream stream = connection.getInputStream();
                        realm.createAllFromJson(CarbayBrand.class, stream);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            });

            Log.d("JsonGet", "Старт загрузки регистра Карбей2");
            progressDialog.setMessage("Загрузка регистра Карбей часть 2...");

            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    try {
                        URL url = new URL(params[2]);
                        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                        connection.connect();
                        InputStream stream = connection.getInputStream();
                        realm.createAllFromJson(CarbayBrand.class, stream);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            });

            Log.d("JsonGet", "Старт загрузки регистра Карбей3");
            progressDialog.setMessage("Загрузка регистра Карбей часть 3...");

            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    try {
                        URL url = new URL(params[3]);
                        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                        connection.connect();
                        InputStream stream = connection.getInputStream();
                        realm.createAllFromJson(CarbayBrand.class, stream);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            });
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            realm.close();
        }
        return null;
    }

    @Override
    protected void onPostExecute(JSONObject response) {
        super.onPostExecute(response);
        Log.d("JsonGet", "Загрузки регистра Карбей окончена!");
        if (progressDialog.isShowing()){
            progressDialog.dismiss();
        }
        Toast.makeText(_ctx, "Загрузка регистра Карбей завершена!",Toast.LENGTH_LONG).show();
        if(callback!=null){
            callback.done();
        }
    }

    public interface realmCallback{
        void done();
    }
}
```

My Realm model

```
public class TradeInCarbay extends RealmObject {
    private String field_link;
    private String field_code;
    private String field_name;
    private String question_link;
    private String question_name;

    public String getField_link() {
        return field_link;
    }

    public void setField_link(String field_link) {
        this.field_link = field_link;
    }

    public String getField_code() {
        return field_code;
    }

    public void setField_code(String field_code) {
        this.field_code = field_code;
    }

    public String getField_name() {
        return field_name;
    }

    public void setField_name(String field_name) {
        this.field_name = field_name;
    }

    public String getQuestion_link() {
        return question_link;
    }

    public void setQuestion_link(String question_link) {
        this.question_link = question_link;
    }

    public String getQuestion_name() {
        return question_name;
    }

    public void setQuestion_name(String question_name) {
        this.question_name = question_name;
    }
}

public class CarbayBrand  extends RealmObject {
    @PrimaryKey
    private String brand_ref;
    private String brand_name;
    private RealmList<CarbayModels> models;

    public String getBrand_ref() {
        return brand_ref;
    }

    public void setBrand_ref(String brand_ref) {
        this.brand_ref = brand_ref;
    }

    public String getBrand_name() {
        return brand_name;
    }

    public void setBrand_name(String brand_name) {
        this.brand_name = brand_name;
    }

    public RealmList<CarbayModels> getModels() {
        return models;
    }

    public void setModels(RealmList<CarbayModels> models) {
        this.models = models;
    }
}

public class CarbayModels extends RealmObject {
    @PrimaryKey
    private String model_link;
    private String model_name;
    private RealmList<CarbayModifications> modificatins;

    public String getModel_link() {
        return model_link;
    }

    public void setModel_link(String model_link) {
        this.model_link = model_link;
    }

    public String getModel_name() {
        return model_name;
    }

    public void setModel_name(String model_name) {
        this.model_name = model_name;
    }

    public RealmList<CarbayModifications> getModificatins() {
        return modificatins;
    }

    public void setModificatins(RealmList<CarbayModifications> modificatins) {
        this.modificatins = modificatins;
    }
}

public class CarbayModifications extends RealmObject {
    @PrimaryKey
    private String modifLink;
    private String modifName;
    private RealmList<CarbayDataLink> dataList;

    @LinkingObjects("modificatins")
    private final RealmResults<CarbayModels> models = null;

    public String getModifLink() {
        return modifLink;
    }

    public void setModifLink(String modifLink) {
        this.modifLink = modifLink;
    }

    public String getModifName() {
        return modifName;
    }

    public void setModifName(String modifName) {
        this.modifName = modifName;
    }

    public RealmList<CarbayDataLink> getDataList() {
        return dataList;
    }

    public void setDataList(RealmList<CarbayDataLink> dataList) {
        this.dataList = dataList;
    }

    public RealmResults<CarbayModels> getModel() {
        return models;
    }
}

public class CarbayDataLink  extends RealmObject {
    private String data;
    private String name;

    private String link;

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }
}
```
The error out of memory throws when i try to get new instance of realm with `Realm.getDefaultInstance()` in any place of my code. My Realm configuration:

```
public class CRMApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        // Configure Realm for the application
        Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder()
                .schemaVersion(1)
                .migration(new CRMRealmMigration())
                .build();
        Realm.setDefaultConfiguration(config);
    }
}




#### Version of Realm and tooling

Realm version(s): 4.3.3

Realm Sync feature enabled: default

Android Studio version: 3.2.1

Android Build Tools version: 27.0.3

Gradle version: 3.1.2

Which Android version and device(s): 8.1

**Comment by cmelchior** [comment]
You are running out of memory. Keep in mind that the entire content of a write transaction needs to fit in memory, so depending on the device even 70 MB might be too much.

**Comment by ilshatL** [comment]
i have 2Gb memory on device, where free 600-800Mb
