### ISSUE TITLE
io.realm.exceptions.RealmException: 'class User' is not part of the schema for this Realm.

### ISSUE THREAD

**Issue by sp-clinks** [realm/realm-java#6567]
#### Goal
I'd like to define and use RealmObjects in our App module  with a library which has its own RealmObjects for its internal processes.
This issue is the almost the same as #6383, But I can't move the class to the library since it's made by a third-party company.

#### Actual Results
Any access to those objects from the MainActivity causes the following exception.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{clinks.jp.k_nemoto.eco2/clinks.jp.k_nemoto.eco2.MainActivity}: io.realm.exceptions.RealmException: 'class clinks.jp.k_nemoto.eco2.User' is not part of the schema for this Realm.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: io.realm.exceptions.RealmException: 'class clinks.jp.k_nemoto.eco2.User' is not part of the schema for this Realm.
        at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:234)
        at io.realm.DefaultRealmModuleMediator.getSimpleClassNameImpl(DefaultRealmModuleMediator.java:66)
        at io.realm.internal.RealmProxyMediator.getSimpleClassName(RealmProxyMediator.java:72)
        at io.realm.RealmSchema.getTable(RealmSchema.java:177)
        at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:200)
        at io.realm.RealmQuery.<init>(RealmQuery.java:155)
        at io.realm.RealmQuery.createQuery(RealmQuery.java:94)
        at io.realm.Realm.where(Realm.java:1431)
        at clinks.jp.k_nemoto.eco2.MainActivity.doRealm(MainActivity.java:48)
        at clinks.jp.k_nemoto.eco2.MainActivity.onCreate(MainActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:24
```
#### Steps & Code to Reproduce
Realm.init(getApplicationContext());
Realm realm = Realm.getDefaultInstance(); 
RealmQuery<User> query = realm.where(User.class);
RealmResults<User> users = query.findAll();

#### Version of Realm and tooling
Realm version(s): 5.10.0

Realm Sync feature enabled: No

Android Studio version: 3.4.2

Android Build Tools version: 28.0.3

Gradle version: 5.1.1

Which Android version and device(s): android 8.0 (HUAWEI Mate10 lite)

**Comment by ppamorim** [comment]
Are you using custom object types on your default instance?

**Comment by cmelchior** [comment]
Have you tried defining your own `RealmModule` with all the model classes needed? We are not able to automatically detect Realm model classes across module boundaries, so in that case, you need to enumerate them. You can read more here: https://realm.io/docs/java/latest/#schemas

**Comment by sp-clinks** [comment]
@cmelchior 
Thanks to your comments in the moduleExample project, I managed to use the both modules.

**Comment by sp-clinks** [comment]
@cmelchior 
Thanks to your comments in the moduleExample project, I managed to use the both modules.

**Comment by Mefor07** [comment]
I know this might be late but it might help someone for future sake. You might wanna check that you added the @RealmClass notation to your class.
