### ISSUE TITLE
Concurrent modification exception in a single transaction

### ISSUE THREAD

**Issue by dariuszseweryn** [realm/realm-java#657]
Hello,

I am experimenting with using your (so far) great library as a main database for an Android application.
I was trying to make an Android Service which would handle making updates to the DB in one transaction.

I get a JSON of objects which I need to bind afterwards into a relation.
It goes something like this:

```
Realm realm = Realm.getInstance(context);
realm.beginTransaction();

for (ObjectA objectA : objectAsFromJson) {
    RealmAObject realmAObject = realm.createObject(RealmAObject.class);
    realmAObject.setId(objectA.getId());
    realmAObject.setUpdateTimestamp(timestamp);
} 

for (ObjectB objectB : objectBsFromJson) {
    RealmBObject realmBObject = realm.createObject(RealmBObject.class);
    realmBObject.setProperty(objectB.getProperty());
    RealmResults<RealmAObject> realmAsObjectsMatching = realm
        .where(RealmAObject)
        .between("id", objectB.getMinId(), objectB.getMaxId())
        .findAll();

    for (RealmAObject realmAObject : realmAsObjectsMatching) { // <=== Exception!
        realmAObject.getRealmBsObjects().add(realmBObject);
        realmBObject.getRealmAsObjects().add(realmAObject);
        realmAObject.setUpdateTimestamp(timestamp);
    }
}

realm.commitTransaction();
realm.close();
```

The exception:
```
java.util.ConcurrentModificationException: No outside changes to a Realm is allowed while iterating a RealmResults. Use iterators methods instead.
 at io.realm.RealmResults.assertRealmIsStable(RealmResults.java:405)
 at io.realm.RealmResults.access$200(RealmResults.java:44)
 at io.realm.RealmResults$RealmResultsIterator.hasNext(RealmResults.java:422)
...
```
Using iterator does not help. The exception is thrown on Iterator.hasNext().

I may be missing something but here is how I understand how the Realm is working:
Until realm.commitTransaction() is being called - all changes are visible inside the Realm instance on which all operations are being performed.

Now the fun part, if I change:
```
    RealmResults<RealmAObject> realmAsObjectsMatching = realm
        .where(RealmAObject)
        .between("id", objectB.getMinId(), objectB.getMaxId())
        .findAll();

    for (RealmAObject realmAObject : realmAsObjectsMatching) { // <=== Exception!
        realmAObject.getRealmBsObjects().add(realmBObject);
        realmBObject.getRealmAsObjects().add(realmAObject);
        realmAObject.setUpdateTimestamp(timestamp);
    }
```
to
```
    for (int i = objectB.getMinId(); i <= objectB.getMaxId(); i++) {
        RealmAObject realmAObject = realm.where(RealmAObject.class).equalTo("id", i).findFirst();
        realmAObject.getRealmBsObjects().add(realmBObject);
        realmBObject.getRealmAsObjects().add(realmAObject);
        realmAObject.setUpdateTimestamp(timestamp);
    }
```
No exception is being thrown.

Is it a bug or do I misuse the Realm?

I have some questions about removing items from the DB but I will probably make another topic.

Best Regards.

**Comment by cmelchior** [comment]
Hi @dariuszseweryn 
Yes, we should clarify our documentation on that point :) 
Apart from that I assume you found a workaround. Please reopen if that is not the case.
