### ISSUE TITLE
io.realm.exceptions.RealmFileException: Unable to open a realm at path

### ISSUE THREAD

**Issue by unengchen** [realm/realm-java#6627]
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.zcla.bankaccesscontrol/files/log_info.realm': Invalid top array (ref, [0], [1], [2]): 12432, 24, 4320, 24576 Path:. (Invalid top array (ref, [0], [1], [2]): 12432, 24, 4320, 24576 Path: /data/data/com.zcla.bankaccesscontrol/files/log_info.realm) (/data/data/com.zcla.bankaccesscontrol/files/log_info.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at com.zcla.bankaccesscontrol.helper.RealmHelper.getLogRealm(RealmHelper.java:101)
        at com.zcla.bankaccesscontrol.global.GlobalActivity.initData(GlobalActivity.java:107)
        at com.zcla.bankaccesscontrol.activity.ScreensaverActivity.initData(ScreensaverActivity.java:56)
        at com.unengchen.basesdk.view.BaseActivity.onCreate(BaseActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:7036)
        at android.app.Activity.performCreate(Activity.java:7027)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Zhuinden** [comment]
You should fill out the issue template when posting an issue.

**Comment by cmelchior** [comment]
Closing as out-dated.

@unengchen If you are using encryption try upgrading to at least Realm Java 6.0.1. If this doesn't help feel free to re-open the issue.
