### ISSUE TITLE
MissingLibraryException: librealm-jni.so Realm 6.1.0

### ISSUE THREAD

**Issue by yesidlazaro** [realm/realm-java#6727]
#### Goal
init realm calling Realm.init(context)
#### Actual Results
Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librealm-jni.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
        at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
        at io.realm.Realm.initializeRealm(Realm.java:322)
        at io.realm.Realm.init(Realm.java:265)

looks like the tool is not including the library .so,but  if i use the previous version 6.0.2 its works fine. see images

debug apk with realm 6.0.2 android studio 3.5.3 build tools 3.5.3 , device nexus 6 android 6.0.1
![alt text](https://i.imgur.com/5vllpa7.png "6.0.2")

debug apk with realm 6.1.0 android studio 3.5.3 build tools 3.5.3 , device nexus 6 android 6.0.1
![alt text](https://i.imgur.com/XPwrIRP.png "6.1.0")

#### Steps & Code to Reproduce
just call Realm.init method in a your oncreate method of your application class.
#### Version of Realm and tooling

Realm version(s): 6.1.0

Realm Sync feature enabled: No

Android Studio version: 3.5.3

Android Build Tools version: 3.5.3

Gradle version: 5.4.1

Which Android version and device(s): Nexus 5 with android 6.0.1

**Comment by nhachicha** [comment]
The `armeabi-v7a` shared library is included in the AAR https://bintray.com/realm/maven/download_file?file_path=io%2Frealm%2Frealm-android-library%2F6.1.0%2Frealm-android-library-6.1.0.aar could clean your maven local repository and post your gradle configs?

**Comment by yesidlazaro** [comment]
its included but the output apk or .aab is not including it.

**Comment by cmelchior** [comment]
Sounds like there is a problem in how you are building the app bundle then?

**Comment by yesidlazaro** [comment]
i don't think so, in the screenshots above i show whats is the result with a previous version of realm. is like the plugin fails putting the .so for armeabi-v7

**Comment by KelvinEC** [comment]
Facing Same Issue Here. 

`java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.loopkey.indigo/br.com.loopkey.indigo.presentation.view.activity.FirstScreenActivity}: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librealm-jni.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [].
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librealm-jni.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [].
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
        at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
        at io.realm.Realm.initializeRealm(Realm.java:322)
        at io.realm.Realm.init(Realm.java:265)
        at br.com.loopkey.indigo.data.Database.<init>(Database.java:36)
        at br.com.loopkey.indigo.di.module.DataModule.provideDatabase(DataModule.java:144)
        at br.com.loopkey.indigo.di.module.DataModule_ProvideDatabaseFactory.get(DataModule_ProvideDatabaseFactory.java:27)
        at br.com.loopkey.indigo.di.module.DataModule_ProvideDatabaseFactory.get(DataModule_ProvideDatabaseFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at br.com.loopkey.indigo.di.module.DataModule_ProvideNetworkLoginFactory.get(DataModule_ProvideNetworkLoginFactory.java:40)
        at br.com.loopkey.indigo.di.module.DataModule_ProvideNetworkLoginFactory.get(DataModule_ProvideNetworkLoginFactory.java:12)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at br.com.loopkey.indigo.di.module.ActivityModule_ProvideLoopKeyLoginFactory.get(ActivityModule_ProvideLoopKeyLoginFactory.java:28)
        at br.com.loopkey.indigo.di.module.ActivityModule_ProvideLoopKeyLoginFactory.get(ActivityModule_ProvideLoopKeyLoginFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at br.com.loopkey.indigo.di.component.DaggerApplicationComponent$ActivityComponentImpl.getFirstScreenPresenter(DaggerApplicationComponent.java:483)
        at br.com.loopkey.indigo.di.component.DaggerApplicationComponent$ActivityComponentImpl.injectFirstScreenFragment(DaggerApplicationComponent.java:870)
        at br.com.loopkey.indigo.di.component.DaggerApplicationComponent$ActivityComponentImpl.inject(DaggerApplicationComponent.java:714)
        at br.com.loopkey.indigo.presentation.view.fragment.FirstScreenFragment._initializeInjector(FirstScreenFragment.java:81)
        at br.com.loopkey.indigo.presentation.view.fragment.BaseFragment.onCreate(BaseFragment.java:50)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6699)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by KelvinEC** [comment]
Updating, after generating .aab file, I inspected them and the library is there. After I see on which devices the errors are occurring, all of them are rooted devices. Any other devices still working as expectedly.

**Comment by sudokai** [comment]
@kelvin-lima How did you solve this?

**Comment by kelvin-lima** [comment]
@sudokai  as i said, the problem only occurs on Rooted devices. I ignored them and now I'm currently migrating to SQLite+Room, because this bug and some other reasons.

**Comment by ianpward** [comment]
hey @kelvin-lima would you mind emailing me at ian.ward@mongodb.com - I would love to pick your brain on some of the other reasons that drove you to migrate to SQLite+Room

**Comment by ahulyk** [comment]
Do we have any updates or workaround?

**Comment by yesidlazaro** [comment]
@ahulyk i will close the issue, later 2 weeks i found was a issue in the android studio build tool

**Comment by kdotdi** [comment]
What kind of issue in the android studio build tool?

**Comment by ahulyk** [comment]
Still getting this on some devices.
I'm using CI to build app bundle with following config:

`com.android.tools.build:gradle:3.6.3`
`gradle-5.6.4`

Any ideas?

**Comment by kelvinharron** [comment]
Found one instance of this crash for a user in a release apk, we're stuck on 6.1.0 but did any fixes get pushed for 7.0.0 and up? The `librealm-jni-so` is present for `armeabi-v7a` in the apk.

```
h.f.a.c: Could not find 'librealm-jni.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary()(ApkLibraryInstaller.java:173)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal()(ReLinkerInstance.java:180)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary()(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary()(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary()(ReLinker.java:57)
	at io.realm.internal.RealmCore.loadLibrary()(RealmCore.java:60)
	at io.realm.Realm.initializeRealm()(Realm.java:322)
	at io.realm.Realm.init()(Realm.java:265)
```

Realm version(s): 6.1.0

Realm Sync feature enabled: No

Android Studio version: 4.0.1

Android Build Tools version: 28.0.3

Gradle version: 5.4.1

Which Android version and device(s): Clover C300 with Android 4.4.2

**Comment by paktech1** [comment]
was facing the same issue, stopped using aab, is the issue fixed on io.realm:realm-gradle-plugin:7.0.0 ? is it safe to use android bundle now ?

**Comment by imarindam** [comment]
How to avoid this error for armeabi-v7a? I have users with armeabi-v7a architecture and they are rating 1 star because of this issue. I have uploaded apk instead of bundle but still error not resolved for armeabi-v7a devices.

**Comment by paktech1** [comment]
i was able to reduce the apk size by 5mb using split apk, 
realm gradle: classpath "io.realm:realm-gradle-plugin:7.0.0-beta-SNAPSHOT"

// APK splitting
    splits {
        abi {
            // Enable APK splitting wrt architecture
            enable true

            // Reset the architectures for which you need to build the APKs for
            reset()

            // Include the architectures for which Gradle is building APKs
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'

            // Set this to false if you don't want an APK that has native code for all architectures
            universalApk false
        }
    }

    // Assign codes to each architecture
    project.ext.versionCodes = ['x86': 0, 'x86_64': 1, 'armeabi-v7a': 2, 'arm64-v8a': 3]

    // Add the architecture-specific codes above to base version code, i.e. the version code specified in the defaultConfig{} block
    // Example: 2000 is the base version code -> 2000 (x86), 2001 (x86_64), 2002 (armeabi-v7a) & 2003 (arm64-v8a) would be the version codes for the generated APK files
    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.versionCodeOverride = project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1 + android.defaultConfig.versionCode
        }
    }

upload apks to developer console x86, x86_64, armeabi-v7a, arm64-v8a respectively.

**Comment by CrandellWS** [comment]
I updated from `6.x.x` to `10.0.1` 

Everything seems to be working fine and that error went away

**Comment by nolanamy** [comment]
Using aab in production; seeing this on both `6.1.0` and `10.4.0`.

The 65 occurrences in the last 30 days were on rooted Android 4.3 devices exclusively.

**Comment by freakdragon** [comment]
Using aab with `io.realm:realm-gradle-plugin:10.5.1`.  Still facing issue in Galaxy M12 Android 11, Galaxy J2 Core Android 8.1.0.

**Comment by mujahid-dzinemedia** [comment]
moving to SQLite+Room

**Comment by JayasimhaMH** [comment]
I'm using realm in react native app lunching time app is crashing any help me....?

**Comment by exaland** [comment]
1. Go to Realm Website
2. Click in FAQ
3. Search "Couldn’t load librealm-jni.so”

You will see update information
TDLR;

In Realm documentation you can find the following:

Couldn’t load “**librealm-jni.so”** If your app uses other native libraries that don’t ship with support for 64-bit architectures, Android will fail to load Realm’s **librealm-jni.so** file on ARM64 devices. This is because Android cannot load 32-bit and 64-bit native libraries concurrently. The best solution would be to have all libraries provide the same set of supported ABIs, but sometimes that may not be doable if you are using a 3rd-party library. See VLC and Realm Library conflicts.

The workaround to this issue is to exclude Realm’s ARM64 library from the APK file by adding the following code to the app’s build.gradle. You can refer to Mixing 32- and 64-bit Dependencies in Android for more information.
```

android {
    //...
    packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
    }
    //...
}
```
Also, there is a bug with Android Gradle Plugin 1.4.0 betas that leads it to improperly pack .so files included in jar files (see Realm Java issue 1421). To solve this problem, you can revert to Android Gradle Plugin 1.3.0 or use Android Gradle Plugin 1.5.0+.

We are aware of a number of 3rd party libraries, frameworks and management apps which do not have 64-bit support yet:

Parallel Space—but you can advice your users to install the 64 bit version instead. RenderScript—NDK r14 will probably support 64 bit. Unity3d.

Nota: Hello, this is appear again if i'm using proguard on my release buildTypes
