### ISSUE TITLE
RealmFileException and Android Auto Backup

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#6728]
#### Goal
I'm trying to find out why I've been receiving reports like the ones in https://github.com/realm/realm-java/issues/6632 and discuss their potential relation to Android Auto Backup.

#### Actual Results

Example of reports I've been getting:
```
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/<app>/files/database.realm': Invalid top array (ref: 39115056, size: 0)
Exception backtrace:
<backtrace not supported on this platform> Path:Exception backtrace:
<backtrace not supported on this platform>. (Invalid top array (ref: 39115056, size: 0)
Exception backtrace:
<backtrace not supported on this platform> Path: /data/data/<app>/files/database.realm
Exception backtrace:
<backtrace not supported on this platform>) (/data/data/<app>/files/database.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:8)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:12)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:11)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:2)
       at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:6)
       at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:7)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

#### Steps & Code to Reproduce

I've read that copying the file can cause the issue. The only situation where the file is copied is when it is backed up by Android Auto Backup.

My database is not encrypted nor is the Android Backup file. 

These are the relevant configuration parts:
```
<application
        android:allowBackup="true"
        android:fullBackupContent="@xml/backup_rules">
```

```
<full-backup-content>
    <include
        domain="file"
        path="database.realm" />
</full-backup-content>
```

Do I need to have any other special considerations?

#### Version of Realm and tooling

Realm version: 6.1.0

Realm Sync feature enabled: No

Which Android version: 8, 9, 10

**Comment by cmelchior** [comment]
I read up on backup last year and at least the docs claim that the backup and restore should only happen after the app has been completely killed. Exactly in order to avoid interaction with any functionality in the app. So I don't think that is the cause unless there is a vendor-specific bug in the implementation.

That said, the error you report there is consistent with a corrupted file.

Do you use encryption? Also are there a pattern to which devices are affected?

**Comment by jpmcosta** [comment]
I do not not use encryption. I've seen it happen "a lot" in Android 10 devices, which makes me think that it might be related to system updates.
