### ISSUE TITLE
Unrecoverable error. Decryption failed Exception backtrace: () in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144

### ISSUE THREAD

**Issue by wuhenzhizao** [realm/realm-java#6743]
#### Goal
No Crash

#### Actual Results
After upgrade from 5.13.x to 6.0.0, App Crashed when launch due to Decryption failure.

#### Error

io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed
Exception backtrace:
 () in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
	at io.realm.internal.OsSharedRealm.nativeCommitTransaction(Native Method)
	at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:273)
	at io.realm.BaseRealm.commitTransaction(BaseRealm.java:416)
	at io.realm.Realm.commitTransaction(Realm.java:145)
	at io.realm.Realm.executeTransaction(Realm.java:1494)

#### Version of Realm and tooling

Realm version(s): 6.0.0

Realm Sync feature enabled: No

**Comment by nhachicha** [comment]
@wuhenzhizao How are you retrieving the encryption key and building the `RealmConfiguration` are you using the `setDefaultConfiguration` ?

**Comment by wuhenzhizao** [comment]
@nhachicha ，wu never used setDefaultConfiguration in program but several custom realm configuration, like this:
Realm.getInstance(config)

**Comment by rorbech** [comment]
6.0.0 did have some issues around encrypted Realm addressed in later release. 

Closed as outdated. Please reopen with recent info if needed.

**Comment by vangivang** [comment]
We are seeing this crash as well in crashlytics. Mostly on HUAWEI (Y9 Prime 2019):

Using io.realm:realm-gradle-plugin:6.0.2.

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed
Exception backtrace:
<backtrace not supported on this platform> () in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
       at io.realm.internal.OsSharedRealm.nativeCommitTransaction(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:273)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:416)
       at io.realm.Realm.executeTransaction(Realm.java:1494)
