### ISSUE TITLE
Core 10 breaks encryption stress test

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6792]
https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-6785/11/tests

Unit test that triggers it is this one: https://github.com/realm/realm-java/blob/v10/realm/realm-library/src/androidTest/java/io/realm/RealmTests.java#L4568

realm-core-10.0.0-alpha.3 seems to a break an encryption stress test in a fairly consistent manner (but not always)

**Comment by cmelchior** [comment]
Caught this error: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-6793/9/
```
03-10 09:54:41.505 E/REALM   (11789): uncaught exception in notifier thread: N5realm5_impl17TransactLogParser14BadTransactLogE: Bad transaction log
03-10 09:54:41.509 E/libc++abi(11789): terminating with uncaught exception of type realm::_impl::TransactLogParser::BadTransactLog: Bad transaction log
--------- beginning of crash
03-10 09:54:41.510 F/libc    (11789): Fatal signal 6 (SIGABRT), code -6 in tid 11890 (roidJUnitRunner)
03-10 09:54:41.511 I/PgedBinderListener( 4594): kstate callback type:8 value1=11789 value2=KILLED
03-10 09:54:41.619 F/DEBUG   (12755): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-10 09:54:41.620 F/DEBUG   (12755): Build fingerprint: 'Huawei/ALE-L21/hwALE-H:6.0/HuaweiALE-L21/C900B500:user/release-keys'
03-10 09:54:41.620 F/DEBUG   (12755): Revision: '0'
03-10 09:54:41.620 F/DEBUG   (12755): ABI: 'arm64'
03-10 09:54:41.620 F/DEBUG   (12755): pid: 11789, tid: 11890, name: roidJUnitRunner  >>> io.realm.test <<<
03-10 09:54:41.620 F/DEBUG   (12755): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-10 09:54:41.829 F/DEBUG   (12755): Abort message: 'terminating with uncaught exception of type realm::_impl::TransactLogParser::BadTransactLog: Bad transaction log'
03-10 09:54:41.829 F/DEBUG   (12755):     x0   0000000000000000  x1   0000000000002e72  x2   0000000000000006  x3   0000000000000000
03-10 09:54:41.829 F/DEBUG   (12755):     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
03-10 09:54:41.829 F/DEBUG   (12755):     x8   0000000000000083  x9   fefeff7e831972ff  x10  7f7f7f7fff7f7f7f  x11  0101010101010101
03-10 09:54:41.829 F/DEBUG   (12755):     x12  0000000000000071  x13  0000000000000000  x14  0000000000000000  x15  0007983a3a983a12
03-10 09:54:41.829 F/DEBUG   (12755):     x16  0000007f8e2b1618  x17  0000007f8e23ffe4  x18  00000000ffffffe0  x19  0000007f841a8510
03-10 09:54:41.829 F/DEBUG   (12755):     x20  0000007f841a8450  x21  0000000000000000  x22  0000000000000006  x23  0000007f841a7e90
03-10 09:54:41.829 F/DEBUG   (12755):     x24  0000007f841a7d70  x25  0000007f841a7db0  x26  0000007f8e23d000  x27  0000007f88e04fa0
03-10 09:54:41.829 F/DEBUG   (12755):     x28  0000000000001000  x29  0000007f841a7c30  x30  0000007f8e23e098
03-10 09:54:41.829 F/DEBUG   (12755):     sp   0000007f841a7c30  pc   0000007f8e23ffec  pstate 0000000020000000
03-10 09:54:41.876 F/DEBUG   (12755): 
03-10 09:54:41.876 F/DEBUG   (12755): backtrace:
03-10 09:54:41.876 F/DEBUG   (12755):     #00 pc 000000000006afec  /system/lib64/libc.so (tgkill+8)
03-10 09:54:41.876 F/DEBUG   (12755):     #01 pc 0000000000069094  /system/lib64/libc.so (pthread_kill+68)
03-10 09:54:41.876 F/DEBUG   (12755):     #02 pc 000000000002208c  /system/lib64/libc.so (raise+28)
03-10 09:54:41.876 F/DEBUG   (12755):     #03 pc 000000000001c998  /system/lib64/libc.so (abort+60)
03-10 09:54:41.876 F/DEBUG   (12755):     #04 pc 0000000000beb7a4  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (abort_message+236)
03-10 09:54:41.876 F/DEBUG   (12755):     #05 pc 0000000000beb8fc  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_ZL28demangling_terminate_handlerv+260)
03-10 09:54:41.876 F/DEBUG   (12755):     #06 pc 0000000000be87ec  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_ZSt11__terminatePFvvE+12)
03-10 09:54:41.876 F/DEBUG   (12755):     #07 pc 0000000000be80f4  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (__cxa_rethrow+196)
03-10 09:54:41.876 F/DEBUG   (12755):     #08 pc 00000000003a7764  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_ZZN5realm5_impl20ExternalCommitHelper12DaemonThreadC1EvENK3$_0clEv+268)
03-10 09:54:41.876 F/DEBUG   (12755):     #09 pc 00000000003a7608  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_ZNSt6__ndk18__invokeIZN5realm5_impl20ExternalCommitHelper12DaemonThreadC1EvE3$_0JEEEDTclclsr3std6__ndk1E7forwardIT_Efp_Espclsr3std6__ndk1E7forwardIT0_Efp0_EEEOS6_DpOS7_+24)
03-10 09:54:41.876 F/DEBUG   (12755):     #10 pc 00000000003a7568  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_ZNSt6__ndk116__thread_executeINS_10unique_ptrINS_15__thread_structENS_14default_deleteIS2_EEEEZN5realm5_impl20ExternalCommitHelper12DaemonThreadC1EvE3$_0JEJEEEvRNS_5tupleIJT_T0_DpT1_EEENS_15__tuple_indicesIJXspT2_EEEE+32)
03-10 09:54:41.876 F/DEBUG   (12755):     #11 pc 00000000003a6f18  /data/app/io.realm.test-1/lib/arm64/librealm-jni.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm5_impl20ExternalCommitHelper12DaemonThreadC1EvE3$_0EEEEEPvSD_+120)
03-10 09:54:41.876 F/DEBUG   (12755):     #12 pc 00000000000684e4  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
03-10 09:54:41.876 F/DEBUG   (12755):     #13 pc 000000000001d544  /system/lib64/libc.so (__start_thread+16)
03-10 09:54:43.655 D/HwBatteryService( 3336): onUEvent fcp_values = 0
03-10 09:54:43.887 E/NativeCrashListener( 3336): Exception dealing with report
03-10 09:54:43.887 E/NativeCrashListener( 3336): android.system.ErrnoException: read failed: EAGAIN (Try again)
03-10 09:54:43.887 E/NativeCrashListener( 3336): 	at libcore.io.Posix.readBytes(Native Method)
03-10 09:54:43.887 E/NativeCrashListener( 3336): 	at libcore.io.Posix.read(Posix.java:169)
03-10 09:54:43.887 E/NativeCrashListener( 3336): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
03-10 09:54:43.887 E/NativeCrashListener( 3336): 	at android.system.Os.read(Os.java:367)
03-10 09:54:43.887 E/NativeCrashListener( 3336): 	at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:250)
03-10 09:54:43.887 E/NativeCrashListener( 3336): 	at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:141)
```

**Comment by cmelchior** [comment]
This has been fixed by https://github.com/realm/realm-core/pull/3687
