### ISSUE TITLE
Flaky Test: threadStressTest

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6854]
`threadStressTest[Encryption: true, ReuseThreads: true] – ThreadStressTests`

Might be related to the new Scheduler changes in ObjectStore, so keeping track of it here.
https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-6839/17
```
--------- beginning of crash
05-14 19:33:23.064 E/AndroidRuntime( 7599): FATAL EXCEPTION: HandlerWorker: 1
05-14 19:33:23.064 E/AndroidRuntime( 7599): Process: io.realm.test, PID: 7599
05-14 19:33:23.064 E/AndroidRuntime( 7599): java.lang.IllegalStateException: Cannot get versionId, this could be related to a non existing read/write transaction
05-14 19:33:23.064 E/AndroidRuntime( 7599): 	at io.realm.internal.OsSharedRealm.getVersionID(OsSharedRealm.java:366)
05-14 19:33:23.064 E/AndroidRuntime( 7599): 	at io.realm.Realm$1$1.run(Realm.java:1627)
05-14 19:33:23.064 E/AndroidRuntime( 7599): 	at android.os.Handler.handleCallback(Handler.java:739)
05-14 19:33:23.064 E/AndroidRuntime( 7599): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-14 19:33:23.064 E/AndroidRuntime( 7599): 	at android.os.Looper.loop(Looper.java:148)
05-14 19:33:23.064 E/AndroidRuntime( 7599): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-14 19:33:23.066 W/ActivityManager(  880): Error in app io.realm.test running instrumentation ComponentInfo{io.realm.test/androidx.test.runner.AndroidJUnitRunner}:
05-14 19:33:23.067 W/ActivityManager(  880):   java.lang.IllegalStateException
05-14 19:33:23.067 W/ActivityManager(  880):   java.lang.IllegalStateException: Cannot get versionId, this could be related to a non existing read/write transaction
```

**Comment by cmelchior** [comment]
This bug hasn't appeared again, so assume it has been fixed or a fluke. Closing
