### ISSUE TITLE
Caused by io.realm.exceptions.RealmError Unrecoverable error. Failure when converting long string to UTF-16 error_code = 2; retcode = 0;

### ISSUE THREAD

**Issue by OlegNovosad** [realm/realm-java#6879]
#### Goal
Issue / crash fix

#### Actual Results
Happened issue similar to: https://github.com/realm/realm-java/issues/5668

Exception itself:

```java
Caused by io.realm.exceptions.RealmError
Unrecoverable error. Failure when converting long string to UTF-16 error_code = 2; retcode = 0; StringData.size = 6466; StringData.data = <long data here under NDA>
```

Here is a stack trace that can be provided (other stuff is under NDA):

```java
/Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161
       at io.realm.internal.CheckedRow.nativeGetString(CheckedRow.java)
       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:2)
       at io.realm.DynamicRealmObject.getString(DynamicRealmObject.java:25)
```

Issue occurred during migration of string to byte array.

#### Steps & Code to Reproduce
Steps cannot be retrieved so far as it was reported by crashlytics. App cannot be provided as it is under NDA.

#### Version of Realm and tooling

Realm version(s): 6.0.2

Realm Sync feature enabled: No

Realm Encryption: Yes

Android Studio version: 3.6.1

Android Build Tools version: latest

Gradle version: latest

Which Android version and device(s): **devices** = Samsung, Blackview, latest device with crash Samsung A6, **state** = mostly background, **operating systems** = Android 8, 9, 10.

**Comment by Priyanshi-Z** [comment]
Is there any fix for this ?

**Comment by cmelchior** [comment]
error_code = 2 seems to be an buffer issue. I'm not 100% sure this is something we can do much about as it indicate we are running out of memory. 

But for similar issues see https://github.com/realm/realm-java/issues/7101 and https://github.com/realm/realm-java/issues/7081#issuecomment-689500799

**Comment by Priyanshi-Z** [comment]
@cmelchior Thanks for responding but in my case,  error code 1
`

io.realm.exceptions.RealmError: Unrecoverable error. Failure when converting short string to UTF-16 error_code = 1; retcode = 0; StringData.size = 15; StringData.data = ȨРin /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161       at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:157)
--


`

**Comment by Priyanshi-Z** [comment]
@cmelchior I have created a new issue for the same #7126

**Comment by edualonso** [comment]
Closing due to inactivity.
