### ISSUE TITLE
Unable to open a realm at path, Invalid top array. Data extraction possible?

### ISSUE THREAD

**Issue by NickMoutsios** [realm/realm-java#6955]
#### Goal
Is it possible to extract data from a corrupted realm file?

#### Actual Results
I have a production incident regarding the database of a client. The database cannot be opened currently, here is the stack trace:

```
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.product/files/dbfile.realm': Invalid top array (ref, [0], [1], [2]): 63493856, 24, 133887992, 1342177280 Path:. (Invalid top array (ref, [0], [1], [2]): 63493856, 24, 133887992, 1342177280 Path: /data/data/com.example.product/files/dbfile.realm) (/data/data/com.example.product/files/dbfile.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)
```

#### Steps & Code to Reproduce
I do not know what caused this, or to reproduce it for that matter, but I do have the realm file, which is around 485 MB in size and I could communicate any details privately.

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:5.9.1

Realm Sync feature enabled: No

Encryption used: No

Android Studio version: 3.5

Android Build Tools version: 29.0.2

Gradle version: 5.1.1

Which Android version and device(s): ?

**Comment by NickMoutsios** [comment]
To whoever that can help with this. I have the database that produces this exception. But I cannot share it in public nor I can reproduce the circumstances that resulted in the said database file. I could share this file in private though. The question is if there is a way to peek in the file and save the data?

**Comment by bmunkholm** [comment]
We do have tools in realm-core that can open the file. It might be a little involved though. Perhaps @jedelbo can give you a pointer to where you can find it and build it.

**Comment by jedelbo** [comment]
The tools we have are very low-level and can only be of use, if you know the file format. I can have a look at the file, if you would like that. You can send the file to jorgen.edelbo (at) mongodb.com.

**Comment by rorbech** [comment]
@NickMoutsios Did you supply a file to @jedelbo for diagnostics and/or have you been able to gather any information about what initially caused it?

**Comment by NickMoutsios** [comment]
@rorbech @jedelbo @bmunkholm thank you for your response! The customer finally decided to not keep the data so we can let this go. In case it happens again, it is good to know there might be a chance of restoring the data.
