### ISSUE TITLE
Compound Pojo (all members are not simple data type) and  io.realm.exceptions.RealmException: Could not find the generated proxy class error

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#698]
My questions
1. Is it possible to use a class (extends RealmObject) that has a non-simple member variable? Please see example below
2. Not sure if this , or anything else is causing the Could Not find generated proxy class error. Why would there be a proxy class, I can't see any annotations anywhere

I have the following Pojo:

    public class Feed {

        int id;
        public String text;
        public String time_created;
        String time_modified;
        int comments_count;
        int likes_count;
        String feed_type;
        int obj_id;
        String image;
        String user_name;
        String user_earthmile_points;
        boolean liked;
        boolean commented;
        boolean is_private;
        String url;
        int feed_creator_id;
    }

    import io.realm.RealmObject;
    
    public class RealmFeed extends RealmObject{
        Feed obj;
    
        public Feed getObj() {
            return obj;
        }
    
        public void setObj(Feed obj) {
            this.obj = obj;
        }
    }

**And I am doing the following**

    public void writeNewFeedstoDatabase(ArrayList<Feed> newsFeedList){
        Realm realm = Realm.getInstance(this.getActivity());            // getActivity() to be called after onAttach in fragment, called here in onActivityCreated, so should be fine

        for (Feed feed:newsFeedList){
            realm.beginTransaction();    // Error =  io.realm.exceptions.RealmException: Could not find the generated proxy class
            RealmFeed f = realm.createObject(RealmFeed.class);
            f.setObj(feed);
            realm.commitTransaction();

        }

**Full Error**

    Process: com.example.somghosh.testandroid, PID: 32321
    io.realm.exceptions.RealmException: Could not find the generated proxy class
            at io.realm.Realm.createObject(Realm.java:211)
            at com.example.somghosh.testandroid.pager.ScreenNewsHome.writeNewFeedstoDatabase(ScreenNewsHome.java:95)
            at com.example.somghosh.testandroid.pager.ScreenNewsHome.consumeApiData(ScreenNewsHome.java:84)
            at com.example.somghosh.testandroid.pager.ScreenNewsHome.access$200(ScreenNewsHome.java:33)
            at com.example.somghosh.testandroid.pager.ScreenNewsHome$1.success(ScreenNewsHome.java:65)
            at com.example.somghosh.testandroid.pager.ScreenNewsHome$1.success(ScreenNewsHome.java:62)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by cmelchior** [comment]
@somghosh 
I assume you found a workaround for now. Please reopen if that is not the case.
