### ISSUE TITLE
Can not access Realm

### ISSUE THREAD

**Issue by namtran303** [realm/realm-java#6989]
#### Goal
Access to Realm

#### Actual Results

> Fatal Exception: io.realm.exceptions.RealmException: Exception happens when initializing Realm in the background thread.
at io.realm.BaseRealm$InstanceCallback.onError(BaseRealm.java:874)
at io.realm.Realm$Callback.onError(Realm.java:1843)
at io.realm.RealmCache$CreateRealmRunnable$2.run(RealmCache.java:169)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8016)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

> Caused by io.realm.ObjectServerError
at io.realm.SyncSession$WaitForSessionWrapper.throwExceptionIfNeeded(SyncSession.java:728)
at io.realm.SyncSession.waitForChanges(SyncSession.java:427)
at io.realm.SyncSession.downloadAllServerChanges(SyncSession.java:353)
at io.realm.internal.SyncObjectServerFacade.downloadRemoteChanges(SyncObjectServerFacade.java:166)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:302)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
at io.realm.RealmCache$CreateRealmRunnable.run(RealmCache.java:115)
at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

#### Steps & Code to Reproduce
I tried to reproduce issue but I can not.I think issue happen when have many access to realm.

#### Version of Realm and tooling
Currently, I using 'io.realm:realm-gradle-plugin:4.3.2'

Realm Sync feature enabled: Yes

Android Studio version:3.6.1

Android Build Tools version: 28.0.3

Gradle version: 3.4.1

Which Android version and device(s): all (android 7, 8, 9, 10)

**Comment by bmunkholm** [comment]
@namtran303 Could you please use the issue template?

**Comment by namtran303** [comment]
Could you please help me check it.
Thanks

**Comment by bmunkholm** [comment]
It would be great if you can still try to reproduce this as it's have for us to do. We havn't seen this issue before.
Perhaps you could also try upgrading to the latest version?
Is this happening in production or locally? Do you see it repeatedly or have you only seen it once.

**Comment by namtran303** [comment]
While i implement Realm then it working normally, 
But when i release product to store then i get 1140 crash from user.
I don't know why, i tried reproduce at my side but not. I think it occur when have many user connect to realm together.
I will tried to update version, so Please help me investigate this issue.

Thanks

**Comment by bmunkholm** [comment]
Without a way for us to reproduce this error, we can't really troubleshoot it. If that many users are able to hit the bug, it seems like you need to add better tests to cover what the users are doing? 
I don't think this is related to the number of users. They don't connect to each others devices even when using sync. Each device only connects to the Realm Cloud. But changes from others will go through Realm Cloud and end up on an individuals device when syncing.

**Comment by cmelchior** [comment]
Closing due to inactivity. If this still is an issue, feel free to reopen.
