### ISSUE TITLE
Unrecoverable error. Key not found in ../io_realm_internal_OsResults.cpp line 475

### ISSUE THREAD

**Issue by Jeff11** [realm/realm-java#7005]
I want to delete specific items with this realm query:
```
realm.use { realm ->
  realm.executeTransaction { realm ->
    realm.where<ModelItem>()
      .equalTo("note.sent", true)
      .findAll()
      .deleteAllFromRealm()
  }
}
```

#### Actual Results
Crash in `.findAll()`:
```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Key not found in /Users/eduardo.lopez/git/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 475
       at io.realm.internal.OsResults.nativeEvaluateQueryIfNeeded(OsResults.java)
       at io.realm.internal.OsResults.load(OsResults.java:664)
       at io.realm.RealmResults.load(RealmResults.java:142)
       at io.realm.RealmQuery.createRealmResults(RealmQuery.java:2397)
       at io.realm.RealmQuery.findAll(RealmQuery.java:1778)
       at myapp.name.ui.main.StreamFragment$onCreate$1$1.execute(StreamFragment.java:113)
       at io.realm.Realm.executeTransaction(Realm.java:1489)
       at myapp.name.ui.main.StreamFragment.onCreate(StreamFragment.java:97)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2884)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:484)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1312)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1555)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1608)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:455)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2333)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2117)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2055)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1957)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3056)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2990)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:458)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
       at com.hannesdorfmann.mosby3.mvp.MvpActivity.onStart(MvpActivity.java:66)
       at myapp.name.ui.base.BaseMVPActivity.onStart(BaseMVPActivity.java:126)
       at myapp.name.ui.main.MainActivity.onStart(MainActivity.java:312)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
       at android.app.Activity.performStart(Activity.java:6992)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2921)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:251)
       at android.app.ActivityThread.main(ActivityThread.java:6598)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

#### Steps & Code to Reproduce
```
@RealmClass
open class ModelItem(
  @PrimaryKey var uri: String = "",
  var note: ModelNote? = null
) : RealmModel

@RealmClass
open class ModelNote(
  @PrimaryKey var uri: String = "",
  var sent: Boolean = false
) : RealmModel
```

#### Version of Realm and tooling
Realm version(s): 7.0.1

The crash started with Realm 7.0.0. The only difference is the error message, which now has Eduardos name in it @edualonso.
7.0.0: ```Unrecoverable error. Key not found in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 475```

7.0.1: ```Unrecoverable error. Key not found in /Users/eduardo.lopez/git/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 475```

**Comment by alexdpayne** [comment]
I'm getting these errors too, first on 7.0.0 then still on 7.0.1

**Comment by edualonso** [comment]
I have tried the code you provided @Jeff11 and I cannot reproduce the crash. In any case, this looks an awful lot like https://github.com/realm/realm-java/issues/6992 - merging both together.
