### ISSUE TITLE
Realm.getDefaultInstance crashes when downgrade from v7 to v6

### ISSUE THREAD

**Issue by HiroyukTamura** [realm/realm-java#7046]
#### Goal
downgrade Realm from v7 to v6 without a crash on the same device

#### Actual Results
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.realmtest, PID: 12986
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.realmtest/com.example.realmtest.MainActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.realmtest/files/default.realm': Invalid top array (ref: 800, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path:Exception backtrace:
    <backtrace not supported on this platform>. (Invalid top array (ref: 800, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path: /data/data/com.example.realmtest/files/default.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/com.example.realmtest/files/default.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.realmtest/files/default.realm': Invalid top array (ref: 800, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path:Exception backtrace:
    <backtrace not supported on this platform>. (Invalid top array (ref: 800, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path: /data/data/com.example.realmtest/files/default.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/com.example.realmtest/files/default.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)
        at com.example.realmtest.MainActivity.onCreate(MainActivity.kt:14)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        	... 11 more
```

#### Steps & Code to Reproduce
I created a really simple [sample repo](https://github.com/HiroyukTamura/RealmTest/tree/master/app)
1. set version realm-gradle-plugin to 7.0.1
2. build and install
3. set version realm-gradle-plugin to 6.0.2
4. build and install

then the crash occurs

#### Version of Realm and tooling

Realm version(s): v7.0.1, v6.0.2

Realm Sync feature enabled: No

Android Build Tools version: 30.0.1

Gradle version: 6.1.1
Android Gradle Plugin: 4.0.1

Which Android version and device(s): 29

**Comment by ppamorim** [comment]
@HiroyukTamura Are you sure you can downgrade? Remember that the Realm file version cannot be downgraded.

**Comment by HiroyukTamura** [comment]
> file version cannot be downgraded

so, is it impossible to downgrade realm-gradle-plugin ?

I'm searching for workarounds of https://github.com/realm/realm-java/issues/6992, and if downgrade is not supported, it's serious for me...

**Comment by rorbech** [comment]
You cannot downgrade an upgraded file, thus downgrading requires to delete the file. 

Any input on how to reproduce your version of #6992 would be most appreciated.

**Comment by rorbech** [comment]
Closing this issue. Please post any input on how to reproduce #6992 there.
