### ISSUE TITLE
Sorting results breaks query chaining

### ISSUE THREAD

**Issue by gautamjain** [realm/realm-java#707]
I think I've come across a weird bug on v0.76 - if you generate a sorted `RealmResults`, then query chaining starts throwing exceptions.  (I'm not sure if this also happened on older versions of Realm.)

Here's a somewhat contrived example:

```
// Without sorting, it works fine
// RealmList<Contact> contacts = realm.where(Group.class).findFirst().

// With sorting, it doesn't work
RealmResults<Contact> contacts = realm.where(Group.class).findFirst().getContacts()
                                            .where().findAll("key", RealmResults.SORT_ORDER_ASCENDING);

// ArrayIndexOutOfBoundsException
RealmResults<Contact> statusContacts = contacts.where().equalTo("status", 1).findAll();

// IllegalArgumentException: Field 'key': type mismatch. 
RealmResults<Contact> keyContacts = contacts.where().equalTo("key", "A").findAll();

```

All other source files are available here: 
https://github.com/gautamjain/DebugRealm/tree/master/app/src/main/java/io/gautam/debugrealm

**Comment by emanuelez** [comment]
Thank you for the report and the example! We'll look into it right away.

**Comment by cmelchior** [comment]
A fix has been merged to master. It will part of the next release.

**Comment by GerritHoekstra** [comment]
@cmelchior 
Is this fixed in 0.80.0? I'm using the following code:
```java
TimeTableHolder timetableHolder = mRealm.where(TimeTableHolder.class)
		.equalTo("name", classOrTeacher)
		.equalTo("type", type.getId())
		.equalTo("location", location.getName())
		.findFirst();

if(timetableHolder != null) {
	RealmList<TimeTable> timetable = timetableHolder.getTimetable();
	
	long from = Long.parseLong("1426723200");
	long to = Long.parseLong("1426809600");

	return timetable.where()
			.between("fromTime", from, to)
			.findAll();
} else {
	return null;
}
```

But then I get this error:
```
    java.lang.IllegalArgumentException: Field 'fromTime': type mismatch. Was INTEGER, expected DATE.
            at io.realm.RealmQuery.getColumnIndices(RealmQuery.java:164)
            at io.realm.RealmQuery.between(RealmQuery.java:751)
```

This is weird because my fromTime is a date type:
```java
    @SerializedName("fromTime")
	private Date fromTime;
```

**Comment by emanuelez** [comment]
You are correct, `fromTime` is `Date` type, and that's what Realm is complaining about. You are using longs to compare dates. `from` and `to` should be `Date` instances.

**Comment by GerritHoekstra** [comment]
Thanks, I've changed it to `Date` instances and now it's working perfectly!

**Comment by emanuelez** [comment]
Great to hear! :)
