### ISSUE TITLE
Robolectric tests are failing with Realm 7.0.7 on JDK 11

### ISSUE THREAD

**Issue by tmtrademarked** [realm/realm-java#7128]
#### Goal
We're trying to update our app to use JDK 11 in order to take advantage of new tooling. (Many libraries are starting to think about requiring this, and we don't want to end up stuck)

#### Actual Results
We're using a somewhat strange system in our tests to generate test data from JSON. We parse a resource as a JSON object and then use Moshi to transform the object into a Realm object. But with JDK 11, it looks like something isn't happy in how the classes are loaded during Robolectric runs:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class io.realm.RealmModel (java.lang.String is in module java.base of loader 'bootstrap'; io.realm.RealmModel is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @72bc6553)

	at com.blueapron.service.server.RealmListConverter.fromJson(RealmListConverter.java:46)
	at com.blueapron.service.server.RealmListConverter.fromJson(RealmListConverter.java:21)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:226)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:188)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:46)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
	at com.blueapron.base.JsonHelper.parseString(JsonHelper.java:95)
	at com.blueapron.base.JsonHelper.parseJson(JsonHelper.java:63)
	at com.blueapron.service.services.BaseUnitTest.parseJson(BaseUnitTest.java:316)
	at com.blueapron.service.services.BaseUnitTest.getConfig(BaseUnitTest.java:422)
	at com.blueapron.service.client.RemoteConfigTest.setUpConfig(RemoteConfigTest.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

#### Steps & Code to Reproduce
Unfortunately, it's difficult to produce a sample, because I suspect this is a deep interplay between many libraries in our stack - it's some combination of Moshi, Robolectric, Realm, and JDK 11 that gets unhappy.

Any suggestions for debugging this further or working around it are most welcome!

#### Version of Realm and tooling

Realm version(s): 7.0.7

Realm Sync feature enabled: No

Android Studio version: 4.0.1

Gradle version: 6.3

**Comment by tmtrademarked** [comment]
As an interesting note, I tweaked my approach to try creating an in-memory Realm to use that to parse out the JSON object instead of Moshi. But when I do that, I get the following error:

```
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librealm-jni.dylib'. Looked for: [armeabi-v7a], but only found: [].

	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
	at io.realm.Realm.initializeRealm(Realm.java:322)
	at io.realm.Realm.init(Realm.java:265)
	at com.blueapron.service.services.BaseUnitTest.getConfig(BaseUnitTest.java:422)
	at com.blueapron.service.services.BaseUnitTest.init(BaseUnitTest.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This makes me suspect that the root issue here *might* have something to do with exactly how the Realm libraries are loaded up in Robolectric. Maybe there's some bad interaction with JDK 11 classloading that makes the Realm library not be available?

**Comment by cmelchior** [comment]
The first error indicates that whatever created the JSON might have gotten something wrong. At least the serializer error seems quite clear to me. It would probably try to output the JSON to the terminal there to see if it is as expected.

For the 2nd error. You cannot really load the Realm library for real in Robolectric since it will attempt to load the native code for the platform you are running and right now we only support mobile architectures. This is also why you see us stubbing Realm in these tests here: https://github.com/realm/realm-java/blob/master/examples/unitTestExample/src/test/java/io/realm/examples/unittesting/ExampleActivityTest.java

**Comment by tmtrademarked** [comment]
Thanks for taking a look, @cmelchior ! For the second issue, that makes sense - I completely forgot that the Realm library doesn't actually load for real under Robolectric. I know that's something that's been discussed in other contexts.

For the primary issue, though, this doesn't appear to be an issue with generating the JSON itself, but only with parsing the JSON into a Realm object. When I output the raw JSON object here under JDK 8, I get the following:
```
{
  "id": "singleton",
  "features": [
    "flexible_plan_selection"
  ],
  "holdback_groups": [],
  "minimum_version": 13050202,
  "stripe_key": "totally_a_real_key",
  "urls": {
    "id": "singleton",
    "account_settings": "https:\/\/sage.blueapron.com\/my-blue-apron#settings",
    "freshness": "https:\/\/www.blueapron.com\/pages\/freshness-guarantee",
    "marketplace": "https:\/\/sage.blueapron.com\/market",
    "privacy": "https:\/\/sage.blueapron.com\/pages\/privacy",
    "reactivation": "https:\/\/sage.blueapron.com\/account#reactivate",
    "recycling": "https:\/\/sage.blueapron.com\/my-blue-apron#recycle",
    "signup": "https:\/\/sage.blueapron.com\/users\/sign_up",
    "support": "https:\/\/support.blueapron.com",
    "terms": "https:\/\/sage.blueapron.com\/pages\/terms",
    "recipe_comments": "https:\/\/sage.blueapron.com\/recipes\/{recipe_slug}\/comments",
    "wine_a_la_carte": "https:\/\/sage.blueapron.com\/market#wine",
    "blog": "https:\/\/blog.blueapron.com"
  },
  "a_la_carte_enabled": false,
  "a_la_carte_redirect_copy": "Open Browser",
  "a_la_carte_redirect_title": "Sorry for the Inconvenience",
  "a_la_carte_redirect_url": "https:\/\/sage.blueapron.com",
  "kickback_enabled": false,
  "kickback_value": "0",
  "kickback_terms_url": "https:\/\/www.blueapron.com\/pages\/referral-terms"
}
```

And under JDK 11, we get the following:
```
{
  "id": "singleton",
  "features": [
    "flexible_plan_selection"
  ],
  "holdback_groups": [],
  "minimum_version": 13050202,
  "stripe_key": "totally_a_real_key",
  "urls": {
    "id": "singleton",
    "account_settings": "https:\/\/sage.blueapron.com\/my-blue-apron#settings",
    "freshness": "https:\/\/www.blueapron.com\/pages\/freshness-guarantee",
    "marketplace": "https:\/\/sage.blueapron.com\/market",
    "privacy": "https:\/\/sage.blueapron.com\/pages\/privacy",
    "reactivation": "https:\/\/sage.blueapron.com\/account#reactivate",
    "recycling": "https:\/\/sage.blueapron.com\/my-blue-apron#recycle",
    "signup": "https:\/\/sage.blueapron.com\/users\/sign_up",
    "support": "https:\/\/support.blueapron.com",
    "terms": "https:\/\/sage.blueapron.com\/pages\/terms",
    "recipe_comments": "https:\/\/sage.blueapron.com\/recipes\/{recipe_slug}\/comments",
    "wine_a_la_carte": "https:\/\/sage.blueapron.com\/market#wine",
    "blog": "https:\/\/blog.blueapron.com"
  },
  "a_la_carte_enabled": false,
  "a_la_carte_redirect_copy": "Open Browser",
  "a_la_carte_redirect_title": "Sorry for the Inconvenience",
  "a_la_carte_redirect_url": "https:\/\/sage.blueapron.com",
  "kickback_enabled": false,
  "kickback_value": "0",
  "kickback_terms_url": "https:\/\/www.blueapron.com\/pages\/referral-terms"
}
```

... which look the same to me. So I think there's something different about the classloader behavior here in JDK 11 that is somehow causing the transformation to fail. (Not sure if this is something in Realm or something in one of the other libraries mentioned above - but I figured that maybe this is something other Realm users have seen)

**Comment by tmtrademarked** [comment]
I ended up solving this if anyone finds this thread. The problem was that I had a JSON adapter for Moshi declared slightly incorrectly. I had previously used `RealmListConverter<T extends RealmModel> extends JsonAdapter<RealmList<T>>`, which worked fine on JDK 8. But String *isn't* a RealmModel, and JDK 11 seemed to enforce this differently. The fix was simple - just use `RealmListConverter<T> extends JsonAdapter<RealmList<T>>` instead. Voila!
