### ISSUE TITLE
Migration example crashes

### ISSUE THREAD

**Issue by IgorGanapolsky** [realm/realm-java#7157]
#### Goal
Run the **realmmigrationexample**

#### Actual Results
Crash:
2020-10-15 10:48:55.152 9576-9576/examples.realm.io.migration E/AndroidRuntime: FATAL EXCEPTION: main
    Process: examples.realm.io.migration, PID: 9576
    java.lang.RuntimeException: Unable to start activity ComponentInfo{examples.realm.io.migration/io.realm.examples.realmmigrationexample.MigrationExampleActivity}: io.realm.exceptions.RealmFileException: Opening Realm files of format version 2 is not supported by this version of Realm (Database has an unsupported version and cannot be upgraded
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/examples.realm.io.migration/files/default0.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: FORMAT_UPGRADE_REQUIRED.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: io.realm.exceptions.RealmFileException: Opening Realm files of format version 2 is not supported by this version of Realm (Database has an unsupported version and cannot be upgraded
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/examples.realm.io.migration/files/default0.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: FORMAT_UPGRADE_REQUIRED.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(:175)
        at io.realm.internal.OsSharedRealm.getInstance(:251)
        at io.realm.a$d.a(:833)
        at io.realm.w.n(:680)
        at io.realm.a.o(:805)
        at io.realm.v.o(:1773)
        at io.realm.examples.realmmigrationexample.MigrationExampleActivity.onCreate(:69)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        	... 11 more

#### Version of Realm and tooling

Realm version(s): 7.0.8

Realm Sync feature enabled: No

Android Studio version: 4.2 Canary 13

Android Build Tools version: 4.2.0-alpha13

Gradle version: 6.6.1

Which Android version and device(s): Samsung S10 - Android 10

**Comment by rorbech** [comment]
Created issue #7169 to upgrade the migration example's Realms to Core 6 compatible format.
