### ISSUE TITLE
populate realm with assetFile

### ISSUE THREAD

**Issue by mkarcher98** [realm/realm-java#7166]
#### Goal
I wanna give an exist assist file to RealmConfiguration class and set it as defaut and get it when I call getDefaultInstance method of Realm class

#### Actual Results
at the line of getting Instance the exception throws:
2020-10-25 23:27:05.421 24074-24074/? E/REALM_JNI: jni: ThrowingException 5, No such object in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106, .
2020-10-25 23:27:05.421 24074-24074/? E/REALM_JNI: Exception has been thrown: Unrecoverable error. No such object in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
2020-10-25 23:27:05.426 24074-24074/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: [pkg], PID: 24074
    io.realm.exceptions.RealmError: Unrecoverable error. No such object in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:172)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:248)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getDefaultInstance(Realm.java:403)
        at [pkg].introActivities.Intro2Activity.onCreate(Intro2Activity.java:29)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

#### Steps & Code to Reproduce
        Realm.init(this);
        RealmConfiguration realmConfig = new RealmConfiguration.Builder()
                .assetFile("databases.realm")
                .name("myRealm.realm")
                .build();
        Realm.setDefaultConfiguration(realmConfig);

        Realm realm = Realm.getDefaultInstance(); <--throws exception-->

#### Version of Realm and tooling

Realm version(s): 10

Realm Sync feature enabled: Yes/No

Android Studio version: 4.1

Android Build Tools version: 29.0.3

Gradle version: 6.5

Which Android version and device(s): android10 (API29)- AVD device Pixel 3a XL 29

**Comment by rorbech** [comment]
How did you generate the `databases.realm`? Is the file valid and able to open with Realm Studio?

**Comment by mkarcher98** [comment]
its a ready database which has given to me to work with, and its located in assets folder and yes it's valid for realm studio

**Comment by rorbech** [comment]
It could be a matter of a schema mismatch that we do not catch correctly and trigger a migration exception, but it is hard to judge without more information. 

Are you able to compose a minimal reproducing example and maybe also share the `databases.realm` file with us. You can email it to claus.rorbech@mongodb.com.

**Comment by ozv101** [comment]
@cmelchior @mkarcher98 im getting that exact same exception, but only on emulator. works on both a phone and tablet. im using a pre-filled Realm db as well. initializing like so: 

```
if (!RealmUtils.fileFound("data.realm", context.filesDir)) {
    RealmUtils.copyBundledRealmFile(
          context,
          context.resources.openRawResource(R.raw.data),
           "data.realm"
    )
}

Realm.init(context)
val config = RealmConfiguration.Builder()
           .name("data.realm")
           .schemaVersion(SCHEMA_VERSION)
           .build()

Realm.getInstance(config)
