### ISSUE TITLE
Unhelpful exception when calling toFlow on an invalid RealmResults

### ISSUE THREAD

**Issue by jd565** [realm/realm-java#7176]
#### Goal
Exception or error should not be thrown, or have information about what has gone wrong

#### Actual Results
Exception from CallbackFlowBuilder:
    java.lang.IllegalStateException: 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
    Otherwise, a callback/listener may leak in case of external cancellation.
    See callbackFlow API documentation for the details.
        at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:348)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

#### Steps & Code to Reproduce
I have a DAO class with this function:
    fun getMessages(): Flow<List<RealmMessage>> {
        return Realm.getInstance(config).use { r ->
            r.where<RealmMessage>()
                .sort("timestamp", Sort.DESCENDING)
                .findAll()
                .toFlow()
        }
    }

I am then collecting this flow through compose with `collectAsState(initial = emptyList(), context = Dispatchers.Main)`.
I have allowed queries on the UI thread.

Looking at RealmResultsExtensions I can see that the `if (!results.isValid) { return@callbackFlow }` is being hit in the debugger, and then the above exception is thrown because `awaitClose` is never called.

The debugger seems to suggest that it can't get the results because it throws an exception so I am probably doing something wrong with trying to get the results on the wrong thread, but it would be useful if the error would point at what I am doing wrong (and it probably shouldn't just crash if the results are invalid)

#### Version of Realm and tooling

Realm version(s): 10.0.0

Realm Sync feature enabled: No

Android Studio version: 4.2 canary 15

**Comment by jd565** [comment]
In my case the realm is being closed before the flow callback is started so the results are invalid

**Comment by rorbech** [comment]
Yes, seems like there is an internal `callbackFlow`-check that we haven't been hitting in our test. We actually don't leak any callback as they are not subscripted on this case, but we should of course emit a more appropriate error. We will take it into consideration along with #7164 and #7165. Thanks!
