### ISSUE TITLE
Objects can only be removed from inside a write transaction

### ISSUE THREAD

**Issue by Mr-Ramzan** [realm/realm-java#7186]
#### To remove an object from Realm
I want to remove An Object from the Realm using Kotlin.

#### Actual Results[Exception occurs]
       `E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.atomicskills.chatteach, PID: 3976
    java.lang.IllegalStateException: Objects can only be removed from inside a write transaction.
        at io.realm.RealmList.remove(RealmList.java:370)
        at com.atomicskills.chatteach.view.chat.FragmentPrivateChatTeacher$deleteConfirmDialog$3.onClick(FragmentPrivateChatTeacher.kt:601)
        at android.view.View.performClick(View.java:7156)
        at android.view.View.performClickInternal(View.java:7129)
        at android.view.View.access$3500(View.java:803)
        at android.view.View$PerformClick.run(View.java:27543)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:7510)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)`

#### Steps & Code to Reproduce
                     `var realm = Realm.getDefaultInstance()
                        val results = realm.where<RealmPrivateChatTeacher>().equalTo("_key",item._key).findAll()
                        realm.executeTransaction {
                            if(results !=null && results.isNotEmpty())
                                results.deleteAllFromRealm()
                        }`

#### Version of Realm and tooling

Realm version(s): "io.realm:realm-gradle-plugin:10.0.0"

Realm Sync feature enabled: No

Android Studio version:    4.0

Android Build Tools version: 28

Gradle version: 6.1.1

Which Android version and device(s):  10

**Comment by Mr-Ramzan** [comment]
Further Clearance below is init code:
         `Realm.init(this)

            Realm.setDefaultConfiguration(RealmConfiguration.Builder()

                .deleteRealmIfMigrationNeeded()

                .build())`

**Comment by cmelchior** [comment]
Are you sure that is the correct code?

The error happens here: 
```
at com.atomicskills.chatteach.view.chat.FragmentPrivateChatTeacher$deleteConfirmDialog$3.onClick(FragmentPrivateChatTeacher.kt:601)
```
Are you 100% you are not trying to delete things outside a write transaction there?

This code here is largely correct, although I would do this instead:

```
Realm.getDefaultInstance().use { realm ->
    realm.executeTransactionAsync { bgRealm -> {
        realm.where<RealmPrivateChatTeacher>().equalTo("_key",item._key).findAll().deleteAllFromRealm()
    }}
}
```

**Comment by Mr-Ramzan** [comment]
Thank you for the quickest response. I just find out that even if data is in an Arraylist that you got from Realm cannot be removed or altered outside the Transaction block.

              var realm = Realm.getDefaultInstance()
                realm.executeTransactionAsync {
                    item.users!!.remove(RoutingAppController.instance!!.currentUser?._key!!)
                }``

The above code was like this below that was causing the issue. 

              `item.users!!.remove(RoutingAppController.instance!!.currentUser?._key!!)`

This line caused the issue. and I was shocked at what am I doing wrong here. 
you may close the issue But I request to refer me a study topic so I can better understand this behavior.

My Regards,

**Comment by cmelchior** [comment]
Yes, all modifications to Realm data has to happen inside a write transaction in order to fulfill our ACID guarantees. Maybe this will help to understand it better?https://realm.io/docs/kotlin/latest/#writes
