### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed (size: 1048576, offset: 0: 

### ISSUE THREAD

**Issue by shajiangteng** [realm/realm-java#7231]
realm version 6.1.0
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed (size: 1048576, offset: 0: Operation not permitted in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
	at io.realm.internal.OsSharedRealm.nativeCommitTransaction(Native Method)
	at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:273)
	at io.realm.BaseRealm.commitTransaction(BaseRealm.java:416)
	at io.realm.Realm.commitTransaction(Realm.java:145)
	at io.realm.Realm.executeTransaction(Realm.java:1494)
	at cn.lineshine.framework.receiver.AlarmReceiver.adrChange(AlarmReceiver.java:132)
	at cn.lineshine.framework.receiver.AlarmReceiver.onReceive(AlarmReceiver.java:72)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3046)
	at android.app.ActivityThread.-wrap18(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by rorbech** [comment]
@shajiangteng Please fill out the details asked in our template when filing an issue. This helps us understand and reply to your request. 

Besides describing some more details about when and how often this happens, please also provide information about:
- The devices where this is experienced
- Where you store the Realms
- Whether you are using encryption

You can find the template for filing issues below

#### Goal


#### Actual Results


#### Steps & Code to Reproduce




#### Version of Realm and tooling

Realm version(s): ?

Realm Sync feature enabled: Yes/No

Android Studio version: ?

Android Build Tools version: ?

Gradle version: ?

**Comment by rorbech** [comment]
Closing due to inactivity. Please post further details as requested above if you need further assistance.
