### ISSUE TITLE
Clash on Update when Migration is needed

### ISSUE THREAD

**Issue by DevHachi** [realm/realm-java#7237]
#### Goal
Run Migration

#### Actual Results
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {de.telekom.intern.infomapp/de.quimron.yoomind.connect.MainActivity}: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'dbAppProfile.subscribedTemplates' has been made optional.
- Property 'dbCollection.articleIds' has been made optional.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4538)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4570)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

#### Steps & Code to Reproduce
As soon as I update the app from one Version to another this crash occures. But only on the release build.
Here are the relevant code snippets. I don't have any clue why this is happening I tried a bunch of test with the debug Build an d it works but on the Production Version it doesn't work.

`open class dbAppProfile(
    @PrimaryKey var id: Int = UUID.randomUUID().variant(),
...
    var subscribedTemplates: RealmList<Int> = RealmList(),
...
) : RealmObject()`

`open class dbCollection(
    @Required @PrimaryKey var id: String = UUID.randomUUID().toString(),
    var serverID: Int = -1,
    var colorCode: String? = null,
    @Required var title: String = "",
    var description: String? = null,
    var isTemplate: Boolean = false,
    var articleIds: RealmList<Int> = RealmList(),
    var customerType: String = ""
) : RealmObject()`

This is the migration that seems to be wrong, but I don't get what it wrong. This is inside of the migrate function.
`class Migration : RealmMigration {
    override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {

        val schema = realm.schema

        var currentVersion = oldVersion.toInt()

        if(currentVersion == 0) {
            val collScheme = schema.create("dbCollection")
            collScheme.addField("id", String::class.java, FieldAttribute.PRIMARY_KEY).setRequired("id", true).transform {
                it["id"] = UUID.randomUUID().variant()
            }
            collScheme.addField("serverID", Int::class.java)
            collScheme.addField("colorCode", String::class.java)
            collScheme.addField("title", String::class.java).setRequired("title", true)
            collScheme.addField("description", String::class.java)
            collScheme.addField("isTemplate", Boolean::class.java)
            collScheme.addRealmListField("articleIds", Int::class.javaObjectType)
            collScheme.addField("customerType", String::class.java, FieldAttribute.REQUIRED).transform {
                it["customerType"] = "pk"
            }
            schema.get("dbAppProfile")
                ?.addRealmListField("subscribedTemplates", Int::class.javaObjectType)

            currentVersion++
        }

        if(currentVersion == 1) {
            schema.get("dbAppProfile")
                ?.addField("pictureUrl", String::class.java, FieldAttribute.REQUIRED)?.transform {
                    it["pictureUrl"] = ""
                }
                ?.addField("firstName", String::class.java)
                ?.addField("lastName", String::class.java)
            currentVersion++
        }

        if(currentVersion == 2) {
            val articleSchema = schema.get("dbArticle")
            articleSchema?.addField("articleUrl", String::class.java)
                ?.transform {
                    it.set("articleUrl", "")
                }
            currentVersion++
        }
        if(currentVersion == 3) {
            val profileSchema = schema.get("dbAppProfile")
            profileSchema?.addRealmListField("articleSync", Int::class.javaObjectType)
            profileSchema?.addRealmListField("categorySync", Int::class.javaObjectType)
            currentVersion++
        }
        if(currentVersion == 4) {
            val editorsChoiceSchema = schema.create("dbEditorsChoice")
            editorsChoiceSchema.addField("id", String::class.java, FieldAttribute.PRIMARY_KEY, FieldAttribute.REQUIRED).transform {
                it["id"] = "1"
            }
            editorsChoiceSchema.addRealmListField("articles", Int::class.javaObjectType)
            editorsChoiceSchema.addRealmListField("categories", Int::class.javaObjectType)
            editorsChoiceSchema.addRealmListField("collections", Int::class.javaObjectType)

            val offlineContentInfoSchema = schema.create("dbOfflineContentInfo")
            offlineContentInfoSchema.addField("id", String::class.java, FieldAttribute.PRIMARY_KEY, FieldAttribute.REQUIRED).transform {
                it["id"] = "1"
            }
            offlineContentInfoSchema.addField("maxArticles", Int::class.javaObjectType)
            offlineContentInfoSchema.addField("maxCategories", Int::class.javaObjectType)
            offlineContentInfoSchema.addField("maxCollections", Int::class.javaObjectType)
            //not needed yet activate for next migration
           //            currentVersion++
        }
    }`

### Some Additional Information
Tried adding the `@Required` to those fields, which do solve the problem on the release build but then I get an crash on the debug build.

`2020-12-08 16:36:57.965 com.telekom.serviceprofi.infomappe.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.telekom.serviceprofi.infomappe.staging, PID: 11568
    java.lang.RuntimeException: Unable to resume activity {com.telekom.serviceprofi.infomappe.staging/de.quimron.yoomind.connect.MainActivity}: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Property 'dbAppProfile.subscribedTemplates' has been made required.
    - Property 'dbCollection.articleIds' has been made required.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Property 'dbAppProfile.subscribedTemplates' has been made required.
    - Property 'dbCollection.articleIds' has been made required.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:136)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:360)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
        at io.realm.Realm.getInstance(Realm.java:428)
        at de.quimron.yoomind.connect.manager.DataManager.<init>(DataManager.kt:21)
        at de.quimron.yoomind.connect.dagger.components.DaggerAppComponent.getDataManager(DaggerAppComponent.java:52)
        at de.quimron.yoomind.connect.Base.getDataManager(Base.kt:31)
        at de.quimron.yoomind.connect.screens.base.BaseScreen.getDataManager(BaseScreen.kt:196)
        at de.quimron.yoomind.connect.screens.base.BaseScreen.onResume(BaseScreen.kt:99)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2589)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2756)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
2020-12-08 16:36:57.965 com.telekom.serviceprofi.infomappe.staging E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:204)
        at de.quimron.yoomind.connect.base.BaseActivity.onPostResume(BaseActivity.kt:112)
        at android.app.Activity.performResume(Activity.java:8160)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        	... 11 more`

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:6.0.2

Realm Sync feature enabled: No.

Android Studio version: 4.1.1

Android Build Tools version: 29.0.3

Gradle version: 4.0.1

Which Android version and device(s): Samsung / Android 10

**Comment by DevHachi** [comment]
I have found the problem why I had differernt errors on debug and release. Sorry was not your problem.
For all others who may have run into a similar problem. 
The problem was that my latest QA Version was before the rollout of my last Prod Release.
Old QA Version: `var subscribedTemplates: RealmList<Int> = RealmList()`
Old Prod Version: `@Required var subscribedTemplates: RealmList<Int> = RealmList()`

Of course that leads to different versions in the database and thats why I had different error messages with the new QA and Release.

So for anyone who is reading this be careful when you set `@Required`

Some further notice I also had to set migration for the realm field list like this: 
`schema.get("dbAppProfile")?.addRealmListField("subscribedTemplates", Int::class.javaObjectType)?.setRequired("subscribedTemplates", true)`
