### ISSUE TITLE
Reenable tests for MongoCollection.findOneAndUpdate 

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7238]
* findOneAndUpdate_noUpdates
* findOneAndReplace_noUpdates
* findOneAndUpdate_emptyCollection
* findOneAndReplace_noUpsert

All seem to fail due to a bug on the server. This was discovered when bumping to the `2020-12-08` server image.

The above tests have been disabled until this has been fixed. So this issue is mostly to remember to re-enable them.

**Comment by nhachicha** [comment]
@cmelchior This fails with a different exception using `MONGODB_REALM_SERVER=2021-01-13`.
```
01-16 17:10:42.059  6702  6733 E TestRunner: ----- begin exception -----
01-16 17:10:42.060  6702  6733 E TestRunner: MONGODB_ERROR(realm::app::ServiceError:12): WriteNull can only write while positioned on a Element or Value but is positioned on a TopLevel
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.internal.jni.OsJNIResultCallback.onError(OsJNIResultCallback.java:60)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.internal.objectstore.OsMongoCollection.nativeFindOneAndUpdate(Native Method)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.internal.objectstore.OsMongoCollection.findOneAndModify(OsMongoCollection.java:516)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.internal.objectstore.OsMongoCollection.findOneAndUpdate(OsMongoCollection.java:422)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.internal.objectstore.OsMongoCollection.findOneAndUpdate(OsMongoCollection.java:416)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.mongodb.mongo.MongoCollection$18.run(MongoCollection.java:606)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.internal.async.RealmResultTaskImpl.get(RealmResultTaskImpl.java:92)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at io.realm.mongodb.MongoClientTest.findOneAndUpdate_noUpdates(MongoClientTest.kt:700)
01-16 17:10:42.060  6702  6733 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
```
you might want to revisit tests disabled because of this.
