### ISSUE TITLE
Exception backtrace : backtrace not supported on this platform

### ISSUE THREAD

**Issue by gopi-krishna-1086** [realm/realm-java#7240]
Facing with this Issue since two days. This error uppears when it creating the background thread. Any Soluion provided will be appreciated.

E/REALM_JNI: jni: ThrowingException 8, Column name too long
    Exception backtrace:
    <backtrace not supported on this platform>, .
    Exception has been thrown: Column name too long
    Exception backtrace:
    <backtrace not supported on this platform>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testapp, PID: 29950
    java.lang.IllegalStateException: Column name too long
    Exception backtrace:
    <backtrace not supported on this platform>
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getInstance(Realm.java:424)
        at com.example.testapp.TestActivity.lambda$onCreate$0$TestActivity(TestActivity.java:44)
        at com.example.testapp.-$$Lambda$TestActivity$KAFC3NPKFyAM3uZUUF2OzggqUvI.onResult(Unknown Source:2)
        at io.realm.internal.mongodb.Request$3.run(Request.java:90)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:7234)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by edualonso** [comment]
Hi @gopi-krishna-1086 
The error you are posting suggests you are using a name that is too long for the respective column: `java.lang.IllegalStateException: Column name too long`. Valid column names can contain up to 63 characters.
