### ISSUE TITLE
Wrong transactional state, using dynamic realm

### ISSUE THREAD

**Issue by SerhioSavi** [realm/realm-java#7258]
I faced with problem in firebase crashlytics, and I can't repeat it. I am using dynamic realm before provideRealm for dagger, because I need to migrate users to another database realm, which doesn't change. How can I solve this problem? Realm version 10.2.0. I also use function toFlow() and coroutines in project.

error:

```
Fatal Exception: java.lang.RuntimeException: Unable to create application ru.rt.mobileoffice.core.MobileOffice: java.lang.IllegalStateException: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)
 Exception backtrace:
 <backtrace not supported on this platform>
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567)
        at android.app.ActivityThread.access$1400(ActivityThread.java:223)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1886)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7548)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

```
 Caused by java.lang.IllegalStateException: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)
 Exception backtrace:
 <backtrace not supported on this platform>
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getDefaultInstance(Realm.java:403)
        at ru.rt.mobileoffice.core.RealmModule.provideRealm(RealmModule.kt:26)
        at ru.rt.mobileoffice.core.RealmModule_ProvideRealmFactory.provideRealm(RealmModule_ProvideRealmFactory.java:29)
        at ru.rt.mobileoffice.core.RealmModule_ProvideRealmFactory.get(RealmModule_ProvideRealmFactory.java:21)
        at ru.rt.mobileoffice.core.RealmModule_ProvideRealmFactory.get(RealmModule_ProvideRealmFactory.java:8)
        at ru.rt.mobileoffice.core.model.common.EncryptedUserDataStorage_Factory.get(EncryptedUserDataStorage_Factory.java:30)
        at ru.rt.mobileoffice.core.model.common.EncryptedUserDataStorage_Factory.get(EncryptedUserDataStorage_Factory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at ru.rt.mobileoffice.server.ServerApi_Factory.get(ServerApi_Factory.java:30)
        at ru.rt.mobileoffice.server.ServerApi_Factory.get(ServerApi_Factory.java:9)
        at ru.rt.mobileoffice.core.maintenanceModeChecker.MaintenanceModeCheckerRepository_Factory.get(MaintenanceModeCheckerRepository_Factory.java:21)
        at ru.rt.mobileoffice.core.maintenanceModeChecker.MaintenanceModeCheckerRepository_Factory.get(MaintenanceModeCheckerRepository_Factory.java:8)
        at ru.rt.mobileoffice.core.maintenanceModeChecker.MaintenanceModeCheckerModule_ProvideMaintenanceModeCheckerFactory.get(MaintenanceModeCheckerModule_ProvideMaintenanceModeCheckerFactory.java:26)
        at ru.rt.mobileoffice.core.maintenanceModeChecker.MaintenanceModeCheckerModule_ProvideMaintenanceModeCheckerFactory.get(MaintenanceModeCheckerModule_ProvideMaintenanceModeCheckerFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at ru.rt.mobileoffice.core.DaggerDiComponent.getMaintenanceModeChecker(DaggerDiComponent.java:1215)
        at ru.rt.mobileoffice.core.MobileOffice.createDaggerGraph(MobileOffice.java:41)
        at ru.rt.mobileoffice.core.MobileOffice.onCreate(MobileOffice.java:52)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6562)
        at android.app.ActivityThread.access$1400(ActivityThread.java:223)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1886)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7548)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
 
```

my code:
app class:

```
 @Override
     public void onCreate() {
         super.onCreate();
         initRealm(getBaseContext());
         sFirebaseService = FirebaseAnalytics.getInstance(this);
         FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(!BuildConfig.DEBUG);
         createDaggerGraph(this);
        sDiComponent.getRemoteConfig().fetchValues();  // Не забыть зафетчить RemoteConfig!!
         AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
         initializeStetho();
     }
 
     private void initRealm(Context context) {
         Realm.init(context);
         Realm.setDefaultConfiguration(new RealmConfiguration.Builder()
                 .deleteRealmIfMigrationNeeded()
                 .allowWritesOnUiThread(true)
                 .allowQueriesOnUiThread(true)
                 .build());
     }
```
 
RealmModule:
 
```
  @Provides
     fun provideUsersRealm(): UsersRealm {
         val realm = Realm.getInstance(RealmConfiguration.Builder()
                 .name("users_realm.realm")
                 .allowWritesOnUiThread(true)
                 .allowQueriesOnUiThread(true)
                 .modules(UsersRealmModule())
                 .build())
         return UsersRealm(realm)
     }

 @Provides
     fun provideRealm(): Realm {
         if (needToMigrateUsersToNewDb()) {
             migrateUsers()
         }
         return Realm.getDefaultInstance()
     }
 
  private fun migrateUsers() {       
         val users: List<UserRealm> = getUsersFromDynamicRealm()
         val usersRealm = provideUsersRealm()
         usersRealm.realm.use { realm ->
             realm.executeTransaction { rlm ->
                 rlm.copyToRealmOrUpdate(users)
             }
         }
         migrationIsComplete()
     }
 
 private fun getUsersFromDynamicRealm(): List<UserRealm> {
         val dynamicRealm = DynamicRealm.getInstance(RealmConfiguration.Builder()
                 .deleteRealmIfMigrationNeeded()
                 .allowWritesOnUiThread(true)
                 .allowQueriesOnUiThread(true)
                 .build())
         val results = mutableListOf<UserRealm>()
         try {
             val realmResults: RealmResults<DynamicRealmObject> = dynamicRealm.where(UserRealm.CLASS_NAME).findAll()
             for (`object` in realmResults) {
                 val login: String? = `object`.getString(UserRealm.LOGIN)
                 val encryptedPass: String? = `object`.getString(UserRealm.ENCRYPTED_PASS)
                 val timeOfEntry: Date? = `object`.getDate(UserRealm.DATE)
                 results.add(UserRealm(login, encryptedPass, timeOfEntry))
             }
         } catch (e: Exception) {
         }
         return results
     }


    private fun needToMigrateUsersToNewDb() = PreferencesUtils.getBoolean(R.string.preferences_need_to_migrate_users_to_new_db, true)

    private fun migrationIsComplete() = PreferencesUtils.putBoolean(R.string.preferences_need_to_migrate_users_to_new_db, false)
```

**Comment by nhachicha** [comment]
Hi @SerhioSavi since this happens randomly the only thing I suspect is that dagger is trying to inject another instance of Realm (by calling `provideRealm`) while the initial `migrateUsers` has not yet completed ... have you tried using `@Singleton` with the `provideRealm`? Another possibility is that `needToMigrateUsersToNewDb` is returning a cached value (`false`) even though the migration has completed,  you can observe if you're actually setting the value of the preference by registering a `OnSharedPreferenceChangeListener`

**Comment by SerhioSavi** [comment]
> Hi @SerhioSavi since this happens randomly the only thing I suspect is that dagger is trying to inject another instance of Realm (by calling `provideRealm`) while the initial `migrateUsers` has not yet completed ... have you tried using `@Singleton` with the `provideRealm`? Another possibility is that `needToMigrateUsersToNewDb` is returning a cached value (`false`) even though the migration has completed, you can observe if you're actually setting the value of the preference by registering a `OnSharedPreferenceChangeListener`

I reproduced this problem, it happed when invokes` migrateUsers()` and in this time realm faced with a changed scheme, and dynamic realm had a flag `deleteRealmIfMigrationNeeded()`.
After that dagger tried to invoke `provideRealm()` to get Realm instance and after that I had this crash.. I suppose that sometimes instance can't be gotten because realm deleting is still in process. I decided to `close() `dynamic realm instance and I had no problem with that. 

```
private fun getUsersFromDynamicRealm(): List<UserRealm> {
        val dynamicRealm = DynamicRealm.getInstance(RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .allowWritesOnUiThread(true)
                .allowQueriesOnUiThread(true)
                .build())
        val results = mutableListOf<UserRealm>()
        try {
            val realmResults: RealmResults<DynamicRealmObject> = dynamicRealm.where(UserRealm.CLASS_NAME).findAll()
            for (`object` in realmResults) {
                val login: String? = `object`.getString(UserRealm.LOGIN)
                val encryptedPass: String? = `object`.getString(UserRealm.ENCRYPTED_PASS)
                val timeOfEntry: Date? = `object`.getDate(UserRealm.DATE)
                results.add(UserRealm(login, encryptedPass, timeOfEntry))
            }
        } catch (e: Exception) {
        }
        dynamicRealm.close()
        return results
    }
```

**Comment by nhachicha** [comment]
Hi @SerhioSavi yes deleting will not succeed if you have an open dynamic or regular Realm still open. Closing it as you did should be good.
