### ISSUE TITLE
io_realm_internal_OsSharedRealm.cpp line 106

### ISSUE THREAD

**Issue by HXGRoot** [realm/realm-java#7267]
#### 106
Realm.getdefaultInstance() loses permission after configuring android: sharedUserID ="android.uid.system

**Comment by HXGRoot** [comment]
Error is as follows

**2021-01-14 15:21:45.813 9531-9531/? E/zygote: setrlimit(RLIMIT_CORE) failed for pid 9531: Operation not permitted
2021-01-14 15:21:46.864 9531-9531/com.beidou.bdtxwatch E/REALM_JNI: jni: ThrowingException 5, Permission denied in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106, .
2021-01-14 15:21:46.864 9531-9531/com.beidou.bdtxwatch E/REALM_JNI: Exception has been thrown: Unrecoverable error. Permission denied in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
2021-01-14 15:21:46.877 9531-9531/com.beidou.bdtxwatch E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.beidou.bdtxwatch, PID: 9531
    io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getDefaultInstance(Realm.java:403)
        at com.beidou.bdtxwatch.util.BDDatabase.getRealm(BDDatabase.java:22)
        at com.beidou.bdtxwatch.util.BDDatabase.query(BDDatabase.java:243)
        at com.beidou.bdtxwatch.mode.Contact.addPlatformContact(Contact.java:67)
        at com.beidou.bdtxwatch.activity.MainActivity.initData(MainActivity.java:43)
        at com.beidou.bdtxwatch.activity.BaseActivity.onCreate(BaseActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7025)
        at android.app.Activity.performCreate(Activity.java:7016)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1217)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2812)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6747)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)**


**Before sending this error, I added android: sharedUserID ="android.uid.system" to AndroidManifest.xml**

```java
public static Realm getRealm(){
        return Realm.getDefaultInstance();
    }
    public static void init(Context context){
        int version = 1;
        Realm.init(context);
        RealmConfiguration config = new  RealmConfiguration.Builder()
                .name("myRealm.realm")
                .schemaVersion(version)
                .allowWritesOnUiThread(true)
                .build();
        Realm.setDefaultConfiguration(config);
    }

// This error occurs with getRealm()
```

**Comment by nhachicha** [comment]
Hi @HXGRoot are you working on a custom ROM? this looks similar to https://github.com/realm/realm-java/issues/3644  have you tried adding these SELinux rules https://github.com/realm/realm.io/pull/4541/files ?

**Comment by HXGRoot** [comment]
Unable to access https://github.com/realm/realm.io/pull/4541/files

```java
Realm.init(context);
Realm mRealm = Realm.getDefaultInstance();

// The same error will be sent
```

**Comment by HXGRoot** [comment]
Before sending this error, I added android: sharedUserID ="android.uid.system" to AndroidManifest.xml.
Before that it was in normal use。

**Comment by nhachicha** [comment]
@HXGRoot  sorry I meant this link https://realm.io/docs/java/latest/#how-to-use-realm-in-system-apps-on-custom-roms

**Comment by edualonso** [comment]
Closing due to inactivity. Let us know if the link in the previous comment didn't work it out.
