### ISSUE TITLE
Unrecoverable error. No such object after updating Realm from v7 to v10.X.X

### ISSUE THREAD

**Issue by Riflin** [realm/realm-java#7314]
Goal
Update the realm plugin to version 10.X.X

Actual Results
The app crashes when accessing the realm database for the first time after updating the realm version.

The error thrown is the following:

io.realm.exceptions.RealmError: Unrecoverable error. No such object in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
        at io.realm.BaseRealm.<init>(BaseRealm.java:138)
        at io.realm.BaseRealm.<init>(BaseRealm.java:105)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:495)
        at io.realm.RealmCache.createInstance(RealmCache.java:481)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getInstance(Realm.java:424)
        at com.gs.gsobjects.realm.RealmManager.getRealm(RealmManager.java:40)
        at com.gs.gsdeviceserver.data.services.conversaciones.TrabajadoresService.hayTrabajadores(TrabajadoresService.java:63)
        at com.gs.gsdeviceserver.domain.usecase.db.get.CheckTrabajadores.hayTrabajadores(CheckTrabajadores.kt:10)
        at com.gs.gsdeviceserver.app.splash.presenter.SplashPresenterImpl.setDataUpdated(SplashPresenterImpl.java:277)
        at com.gs.gsdeviceserver.app.splash.SplashActivity.onCreate(SplashActivity.java:59)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

If I clear the app data, the application runs without any problem.

It only happens in some devices (Samsung Galaxy A6, for example). In other devices (Samsung XCover 4S) it does not crash.

Steps & Code to Reproduce

I have an application using Realm. I wanted to update it from version 7.0.5 to 10.X, but after doing that, the app cannot start (it checks the realm database in the splash screen) because it crash with the above error, so the only step to reproduce it is upgrade the realm version. If the app data is cleared, the application works again without a problem. And, as stated above, it does not happen in every device, but just in Galaxy A6 (as far as we have noticed).

Version of Realm and tooling

Realm version(s): 10.3.1 (it also happened with 10.1.0) after updating from 7.0.5.

Realm Sync feature enabled: No

Android Studio version: 4.1.2

Android Build Tools version: 29.0.3

Gradle version: 6.5

Which Android version and device(s): Android 10 on a Samsung XCover 4S

**Comment by jedelbo** [comment]
Unfortunately there is too little information for us to figure out what causes this problem. It could be a query that returns an object key that subsequently cannot be used to find the actual object. In order to proceed here, we would need the actual realm file that causes this problem to occur. Would that be possible?

**Comment by Riflin** [comment]
Hi. 

Here it is. I hope you can find the reason why this is happening. If you need anything else, please tell me :)


[DBRealm.zip](https://github.com/realm/realm-java/files/6028106/DBRealm.zip)

**Comment by jedelbo** [comment]
I was able to upgrade the realm file without any problems in Linux environment. @cmelchior can you see any reason as to why this would fail on some devices? Would we have the possibility to try to open the file in some Android context?
Assigning back to realm-java.

**Comment by rorbech** [comment]
I will try to see if I can grab the schema definition through studio and open the realm on Android

**Comment by rorbech** [comment]
I managed to reproduce the stack trace when I use the above realm as the initial realm using `assetFile` on a 32-bit emulator. I have asked @jedelbo to rerun his upgrade on a 32-bit platform, to see if we can get closer to the root cause.
