### ISSUE TITLE
Android crash  Too many open files

### ISSUE THREAD

**Issue by NunoPontes** [realm/realm-java#7370]
#### Goal
On some devices, when trying to retrieve data frmo the DB it crashes.

The methods that I'm using are protected with try catch and error handling on the catch, however this crashes inside of Realm. I think Realm should throw the exception so we can treat them.

From the error I assumed that I wasn't closing realm files, however I checked and I always retrieve the values like so:

Realm.getDefaultInstance()
            .use { realm ->}

which should close the files automatically.

#### Actual Results
```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
       at io.realm.BaseRealm.<init>(BaseRealm.java:138)
       at io.realm.BaseRealm.<init>(BaseRealm.java:105)
       at io.realm.Realm.<init>(Realm.java:159)
       at io.realm.Realm.createInstance(Realm.java:495)
       at io.realm.RealmCache.createInstance(RealmCache.java:481)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
       at io.realm.Realm.getDefaultInstance(Realm.java:403)
       at com.test.test.Database.User.UserCRUD.getToken(UserCRUD.kt:112)
       at com.test.test.Services.MyFirebaseMessagingService.onMessageReceived(MyFirebaseMessagingService.kt:37)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.0.1:13)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.0.1:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.5.0:6)
       at java.lang.Thread.run(Thread.java:764)
```

#### Steps & Code to Reproduce

This is the code that causes the app to crash. I can't reproduce it, but I have users getting this crash. I've got this info from Firebase Crashlytics.

```
fun getToken(): String? {
        try {
            Realm.getDefaultInstance().use { realm ->
                // No need to close the Realm instance manually
                return realm.where(Users::class.java)
                    .findFirst()!!
                    .token
            }
        } catch (e: Exception) {
            Timber.e(e.toString())
            return ""
        }
    }
```

#### Version of Realm and tooling
Realm version(s): 10.3.1

Realm Sync feature enabled: No

Android Studio version: 4.1.3

Gradle version: 4.1.3

Which Android version and device(s): 

* Zenfone 3 - Android 8

**Comment by cmelchior** [comment]
Hi @NunoPontes 

Sorry for the late reply. An open Realm instance roughly uses 8 file descriptors. Even if you have it open across multiple threads. When you call `Realm.getInstance()` it goes through our caching layer, so in most cases you don't actually open the file again.

So most likely something else is causing you to have a lot of open files and it just happens to be Realm that triggers you to go above the limit.

Note, you can debug Realm resources using `Realm.getGlobalInstanceCount(config)`. This will report the number of threads you have the Realm open at. `Realm.getLocalInstanceCount(config)` report how many times you called `Realm.getInstance()` on a particular thread.

More likely I assume you have some other code in your app that are not freeing up resources, maybe images being loaded? This blog post also goes into more details on how you might be able to debug this: https://medium.com/@smdevidan/keeping-file-descriptors-fds-in-check-on-android-24778973a173

I hope the above helps?
