### ISSUE TITLE
Updating app crash RealMigrationNeededException but RealmObjects haven't been modified

### ISSUE THREAD

**Issue by johnsabilla** [realm/realm-java#7401]
#### Goal
Hello, I recently released a new version of my app and upon updating to it, app immediately crashes due to
"io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors"

Goal is to update the app, run the realm migration without a crash. 

#### Actual Results
The app crashes with io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:

Property 'HistoryLogModel.bytes' has been made optional.  **(unmodified for this release)**
Property 'StatusDataModel.data' has been made optional. **(unmodified for this release)**
Property 'TelemetryLogModel.data' has been made optional. **(unmodified for this release)**
Property 'TelemetryLogModel.timeStamp' has been made optional. **(modified for this release and migration is created)**

With the exception of TelemetryLogModel.timeStamp, the rest of these properties were not modified for this release.

The original version of the app had **io.realm:realm-gradle-plugin:7.0.2**
The the most recent ver has **io.realm:realm-gradle-plugin:7.0.8**

Looking at the changelog, there are no breaking changes between these two versions.

##### Stacktrace 
```
--------- beginning of crash
03-25 11:21:45.649  1830  1830 E AndroidRuntime: FATAL EXCEPTION: main
03-25 11:21:45.649  1830  1830 E AndroidRuntime: Process: com.nicolbolas.magic, PID: 1830
03-25 11:21:45.649  1830  1830 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.nicolbolas.magic.ProtectedApp: com.nicolbolas.magic.MessageGuardException_TWlncmF0aW9uIGlzIHJlcXVpcmVkIGR1ZSB0byB0aGUgZm9sbG93aW5nIGVycm9yczoKLSBQcm9wZXJ0eSAnSGlzdG9yeUxvZ01vZGVsLmJ5dGVzJyBoYXMgYmVlbiBtYWRlIG9wdGlvbmFsLgotIFByb3BlcnR5ICdTdGF0dXNEYXRhTW9kZWwuZGF0YScgaGFzIGJlZW4gbWFkZSBvcHRpb25hbC4KLSBQcm9wZXJ0eSAnVGVsZW1ldHJ5TG9nTW9kZWwuZGF0YScgaGFzIGJlZW4gbWFkZSBvcHRpb25hbC4KLSBQcm9wZXJ0eSAnVGVsZW1ldHJ5TG9nTW9kZWwudGltZVN0YW1wJyBoYXMgYmVlbiBtYWRlIG9wdGlvbmFsLg: Migration is required due to the following errors:
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'HistoryLogModel.bytes' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'StatusDataModel.data' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'TelemetryLogModel.data' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'TelemetryLogModel.timeStamp' has been made optional. (RmluZ2VycHJpbnQgMjAyMDA2MjkgWysuLisuLl0gYXJtNjQtdjhhOmFybTY0LXY4YSAzMC8yLjEuMC8tIGdvb2dsZS9ibHVlbGluZS9ibHVlbGluZToxMS9SUTJBLjIxMDMwNS4wMDYvNzExOTc0MTp1c2VyL3JlbGVhc2Uta2V5cw==)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6720)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.android.internal.os.Device.fp(RmluZ2VycHJpbnQgMjAyMDA2MjkgWysuLisuLl0gYXJtNjQtdjhhOmFybTY0LXY4YSAzMC8yLjEuMC8tIGdvb2dsZS9ibHVlbGluZS9ibHVlbGluZToxMS9SUTJBLjIxMDMwNS4wMDYvNzExOTc0MTp1c2VyL3JlbGVhc2Uta2V5cw==:0)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: Caused by: com.nicolbolas.magic.MessageGuardException_TWlncmF0aW9uIGlzIHJlcXVpcmVkIGR1ZSB0byB0aGUgZm9sbG93aW5nIGVycm9yczoKLSBQcm9wZXJ0eSAnSGlzdG9yeUxvZ01vZGVsLmJ5dGVzJyBoYXMgYmVlbiBtYWRlIG9wdGlvbmFsLgotIFByb3BlcnR5ICdTdGF0dXNEYXRhTW9kZWwuZGF0YScgaGFzIGJlZW4gbWFkZSBvcHRpb25hbC4KLSBQcm9wZXJ0eSAnVGVsZW1ldHJ5TG9nTW9kZWwuZGF0YScgaGFzIGJlZW4gbWFkZSBvcHRpb25hbC4KLSBQcm9wZXJ0eSAnVGVsZW1ldHJ5TG9nTW9kZWwudGltZVN0YW1wJyBoYXMgYmVlbiBtYWRlIG9wdGlvbmFsLg: Migration is required due to the following errors:
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'HistoryLogModel.bytes' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'StatusDataModel.data' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'TelemetryLogModel.data' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'TelemetryLogModel.timeStamp' has been made optional. (RmluZ2VycHJpbnQgMjAyMDA2MjkgWysuLisuLl0gYXJtNjQtdjhhOmFybTY0LXY4YSAzMC8yLjEuMC8tIGdvb2dsZS9ibHVlbGluZS9ibHVlbGluZToxMS9SUTJBLjIxMDMwNS4wMDYvNzExOTc0MTp1c2VyL3JlbGVhc2Uta2V5cw==)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.ProtectedApp.onCreate(Unknown Source:169)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6715)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	... 9 more
03-25 11:21:45.649  1830  1830 E AndroidRuntime: Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'HistoryLogModel.bytes' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'StatusDataModel.data' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'TelemetryLogModel.data' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: - Property 'TelemetryLogModel.timeStamp' has been made optional.
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:137)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.BaseRealm.<init>(BaseRealm.java:104)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.Realm.<init>(Realm.java:163)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.Realm.createInstance(Realm.java:499)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.RealmCache.createInstance(RealmCache.java:507)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:473)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:414)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:428)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.repo.RealmRepository.initialize(RealmRepository.kt:132)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.components.TKG.restoreRepo(TKG.kt:57)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.components.AppComponentStore.<init>(AppComponentStore.kt:176)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.App.initializeComponentStore(App.kt:327)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.App.initializeSecondaryComponents(App.kt:238)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.App.setup(App.kt:218)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.App.onCreate(App.kt:189)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.ProtectedApp.ajcmiqvwAG(Native Method)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.ProtectedApp$R$font.jorgkwmf(Unknown Source:653)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.ProtectedApp$R$font.eDnHas(Unknown Source:99)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.ProtectedApp$R$font.wpHrAw(Unknown Source:147)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	at com.nicolbolas.magic.ProtectedApp.onCreate(Unknown Source:117)
03-25 11:21:45.649  1830  1830 E AndroidRuntime: 	... 11 more
```

##### Migration file 
```
class MagicRealmMigrations: RealmMigration {

    override fun hashCode(): Int {
        return MagicRealmMigrations::javaClass.hashCode()
    } 

    override fun equals(other: Any?): Boolean {
        if (null == other) {
            return false
        }
        return other is MagicRealmMigrations
    }

    override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {
        val schema = realm.schema
        var localOldVersion = oldVersion

        if (localOldVersion < 1L) {
            val profileSettingsSchema = schema.get("ProfileSettings")
            profileSettingsSchema?.addField("hasUploaded", Boolean::class.java)
            localOldVersion++
        }

        if (localOldVersion == 1L) {
            val telemetryLogSchema = schema.get("TelemetryLogModel")
            telemetryLogSchema?.removePrimaryKey()
            localOldVersion++
        }

        if(localOldVersion == 2L) {
            val telemetryLogSchema = schema.get("TelemetryLogModel")
            telemetryLogSchema?.addField("id", Long::class.java)

            val telemetryLogs = realm.where("TelemetryLogModel")
                .sort("timeStampSeconds", Sort.ASCENDING)
                .findAll()
            for((counter, log) in telemetryLogs.withIndex()) {
                    log.set("id", counter)
            }

            telemetryLogSchema?.addPrimaryKey("id")
            localOldVersion++
        }
    }
}
```

##### Realm Objects

open class StatusDataModel(@PrimaryKey open var id: Long = 0,
                           var statusDataType: Int = 0,
                           var data: String = "",
                           var timeUTCMillis: Long = 0) : RealmObject()

open class TelemetryLogModel(@PrimaryKey var id: Long = 0,
                             var data: String = "",
                             var timeStampSeconds: Long = 0,
                             var timeStamp: String = "",
                             var uploaded: Boolean = false,
                             var code: Int = 0): RealmObject()

open class HistoryLogModel(@PrimaryKey open var sequenceNumber: Long = 0,
                             open var bytes: ByteArray = ByteArray(0),
                             open var typeId: Int = 0,
                             open var pumpTimeSeconds: Long = 0) : RealmObject()

##### Instantiating realm
```
Log.d(TAG, "Database accessed from default location.")
val config = RealmConfiguration.Builder()
            .schemaVersion(realmSchemaVersion)
            .migration(MagicRealmMigrations())
            .also {
                k?.let { key ->
                    it.encryptionKey(key)
                }
            }
            .build()
this.config = config
Realm.getInstance(config)
```

#### Steps & Code to Reproduce
As soon as I update from one version to another the crash occurs immediately. 

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:7.0.8

Realm Sync feature enabled: No

Android Studio version: 4.1.3

Android Build Tools version: 29.0.2

Gradle version: 4.0.0

Which Android version and device(s): 
Samsung Galaxy S9 Android 11
Google Pixel 3 Android 11

**Comment by cmelchior** [comment]
Hi @johnsabilla Sorry for the late reply. That looks really strange. At least I'm not seeing anything in your code that should be causing this. Is it something you can reproduce?

**Comment by CherryLover** [comment]
I have same problem, it's on firebase crashlytics, my db structure has long time not to change. In my test time, I was not happen. Do you has some idea to help me troubleshoot the problem?

**Comment by johnsabilla** [comment]
@cmelchior yes it's reproducible. sorry for the late reply. I fellow Android engineer suggested this solution: https://github.com/realm/realm-java/issues/6690

It seems that realm classes needs to be excluded from obfuscation. I will update you if this fixes the problem once we release an update.

**Comment by bmunkholm** [comment]
@johnsabilla Closing as we haven't heard back. If this is still an issue, please ping me and I'll reopen.
