### ISSUE TITLE
Embedded migrations broke between 10.3.1 and 10.4.0

### ISSUE THREAD

**Issue by tmtrademarked** [realm/realm-java#7402]
#### Goal
Fix previous functioning schema migrations in our application.

#### Actual Results
Running our migrations creates the following error. On 10.3.1, these exact migrations run just fine - they only started causing a problem on 10.4.0.

```
java.lang.IllegalStateException: Cannot change table to embedded without backlink columns. Table must be embedded in at least one other table.
at io.realm.internal.Table.nativeSetEmbedded(Native Method)
at io.realm.internal.Table.setEmbedded(Table.java:725)
at io.realm.RealmObjectSchema.setEmbedded(RealmObjectSchema.java:459)
at com.blueapron.service.cache.MigrationManager$UpgradeFrom108.migrate(MigrationManager.java:1092)
at com.blueapron.service.cache.MigrationManager.migrate_inner(MigrationManager.java:131)
at com.blueapron.service.cache.MigrationManager.migrate(MigrationManager.java:116)
at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:867)
```

#### Steps & Code to Reproduce
We are running a migration that adds a new class called `Image`, and wants it to be embedded. The migration code looks like this:

```
private class UpgradeFrom108 extends BaseMigration {
        UpgradeFrom108() {
            super(108);
        }

        @Override
        public boolean migrate(DynamicRealm realm) {
            RealmSchema schema = realm.getSchema();

            RealmObjectSchema imageSchema = schema.create("Image")
                    .addField("url", String.class)
                    .addField("alt_text", String.class);
            imageSchema.setEmbedded(true);

            RealmObjectSchema basicContentSchema = schema.create("BasicContent")
                    .addField("title", String.class)
                    .addField("target_url", String.class)
                    .addRealmObjectField("image", imageSchema);
            basicContentSchema.setEmbedded(true);

            RealmObjectSchema variantSchema = Objects.requireNonNull(schema.get("Variant"));
            RealmObjectSchema contentStreamCardSchema = schema.create("ContentStreamCard")
                    .addField("analytics_event", String.class)
                    .addField("display_priority", int.class)
                    .addField("style", int.class)
                    .addField("title", String.class)
                    .addRealmObjectField("basic_content", basicContentSchema)
                    .addRealmObjectField("variant", variantSchema)
                    .addField("content_type", int.class);
            contentStreamCardSchema.setEmbedded(true);

            RealmObjectSchema contentStreamContainerSchema = schema.create("ContentStreamContainer")
                    .addField("id", String.class)
                    .setRequired("id", true)
                    .addField("display_priority", int.class)
                    .addRealmListField("children", contentStreamCardSchema);
            contentStreamContainerSchema.setEmbedded(true);

            schema.create("ContentStream")
                    .addField("id", String.class)
                    .setRequired("id", true)
                    .addPrimaryKey("id")
                    .addRealmListField("containers", contentStreamContainerSchema)
                    .addField("retain", boolean.class);
            return true;
        }
    }
```

Some of the relevant object schemas are as follows:
```
@RealmClass(embedded = true)
open class Image : RealmObject() {
    @JvmField var url: String? = null
    @JvmField var alt_text: String? = null
}

@RealmClass(embedded = true)
open class BasicContent : RealmObject() {
    @JvmField var body: String? = null
    @JvmField var target_url: String? = null
    @JvmField var image: Image? = null
}

// ... and so forth.
```

#### Version of Realm and tooling

Realm version(s): 10.4.0 - Realm 10.3.1 is working just fine.

Realm Sync feature enabled: No

Android Studio version: 4.1.3

**Comment by tmtrademarked** [comment]
The error message makes it seem like we might have to create the schemas in reverse order somehow during the migration? Like, create the `Image` schema, create the `BasicContent` schema, etc, then mark them as embedded once the previous tables exist?

Is that a correct interpretation of what this means? If so, can you help me understand why this worked in 10.3.1 and fails in 10.4.0? There doesn't appear to be a note about this in the changelog, so I'm trying to figure out if this was some sort of intentional new validation that is important, and what that might mean for our existing users who have already run the previous migration under 10.3.1.

**Comment by ganfra** [comment]
Got the exact same issue, reverting to 10.3.1 make it works...

**Comment by cmelchior** [comment]
Thank you for reporting this. We will look into it.

**Comment by ganfra** [comment]
Do you have any intel to share about that?

**Comment by clementetb** [comment]
On 10.4.0 we have enhanced the schema validation. Now you must first create the different object schema and link them, and later set any object as embedded. The reason is that before you might create an orphan embedded object, now we validate that the embedded object has a parent.

1. define child
2. define parent
3. parent.add(child)
4. child.setEmbedded

@tmtrademarked , try with this migration:
```
private class UpgradeFrom108 extends BaseMigration {
    UpgradeFrom108() {
        super(108);
    }

    @Override
    public boolean migrate(DynamicRealm realm) {
        RealmSchema schema = realm.getSchema();

        RealmObjectSchema imageSchema = schema.create("Image")
                .addField("url", String.class)
                .addField("alt_text", String.class);

        RealmObjectSchema basicContentSchema = schema.create("BasicContent")
                .addField("title", String.class)
                .addField("target_url", String.class)
                .addRealmObjectField("image", imageSchema);
        imageSchema.setEmbedded(true);

        RealmObjectSchema variantSchema = Objects.requireNonNull(schema.get("Variant"));
        RealmObjectSchema contentStreamCardSchema = schema.create("ContentStreamCard")
                .addField("analytics_event", String.class)
                .addField("display_priority", int.class)
                .addField("style", int.class)
                .addField("title", String.class)
                .addRealmObjectField("basic_content", basicContentSchema)
                .addRealmObjectField("variant", variantSchema)
                .addField("content_type", int.class);
        basicContentSchema.setEmbedded(true);

        RealmObjectSchema contentStreamContainerSchema = schema.create("ContentStreamContainer")
                .addField("id", String.class)
                .setRequired("id", true)
                .addField("display_priority", int.class)
                .addRealmListField("children", contentStreamCardSchema);
        contentStreamCardSchema.setEmbedded(true);

        schema.create("ContentStream")
                .addField("id", String.class)
                .setRequired("id", true)
                .addPrimaryKey("id")
                .addRealmListField("containers", contentStreamContainerSchema)
                .addField("retain", boolean.class);
        contentStreamContainerSchema.setEmbedded(true);
        return true;
    }
}
```

**Comment by tmtrademarked** [comment]
It appears that this does work - thanks! But as a suggestion, it seems like this might want to be added to the documentation for migrations or embedded objects? This new requirement was not obvious.
