### ISSUE TITLE
Realm incompatible with AndroidX Test suite mock activity

### ISSUE THREAD

**Issue by ink404** [realm/realm-java#7407]
#### Goal
Create and use a test configuration for realm

#### Actual Results

attempting to set the test config in the @Before of my test 
```
        Realm.init(ApplicationProvider.getApplicationContext())
        val testConfig = RealmConfiguration.Builder()
            .allowWritesOnUiThread(true)
            .allowQueriesOnUiThread(true)
            .inMemory()
            .build()
        Realm.setDefaultConfiguration(testConfig)
```
causes this crash
```
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librealm-jni.dylib'. Looked for: [armeabi-v7a], but only found: [].

	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
	at io.realm.Realm.initializeRealm(Realm.java:318)
	at io.realm.Realm.init(Realm.java:261)
	at com.company.myapp.data.MyClassNameTest.setupRealm(ClassNameTest.kt:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
note: ClassNameTest, and package name were changed from their original values

#### Steps & Code to Reproduce
code that causes crash
```
// package omitted 

import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.common.truth.Truth.assertThat
import io.realm.Realm
import io.realm.RealmConfiguration
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.runBlockingTest
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

@ExperimentalCoroutinesApi
@RunWith(AndroidJUnit4::class)
@Config(sdk = [29])
class ClassNameTest {

  // irrelevant members omitted

    @Before
    fun setupRealm() {
        Realm.init(ApplicationProvider.getApplicationContext())
        val testConfig = RealmConfiguration.Builder()
            .name("test-instance")
            .allowWritesOnUiThread(true)
            .allowQueriesOnUiThread(true)
            .inMemory()
            .build()
        Realm.setDefaultConfiguration(testConfig)

        // irrelevant inits omitted
    }

   // irrelevant tests omitted

}
```
note: I've tried with and without the advice at: https://docs.mongodb.com/realm-legacy/docs/java/latest/#faq-librealm-jni
```
android {
    //...
    packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
    }
    //...
}
```
and see the same failure

#### Version of Realm and tooling

Realm version(s): 10.4.0

Realm Sync feature enabled: No

Android Studio version: 4.2 beta 6

Android Build Tools version: 4.1.3

Gradle version: 6.8.3

Which Android version and device(s): target SDK 29, Device N/A Unit Test

**Comment by cmelchior** [comment]
Hi @ink404 

Yes, Unfortunately running Realm this way isn't supported as we only provide binaries for mobile platforms, not on the desktop. We have an example here, showing how things can be mocked when using Robolectric https://github.com/realm/realm-java/tree/master/examples/unitTestExample, but we do realize this is far from ideal.

This issue is already being tracked here: https://github.com/realm/realm-java/issues/904, so I'll be folding this issue into that one. But we unfortunately do not have any timeline for it.
