### ISSUE TITLE
A RealmObject with no @PrimaryKey cannot be updated

### ISSUE THREAD

**Issue by nowiwr01** [realm/realm-java#7424]
0

**Comment by nowiwr01** [comment]
How it was used:

**ViewModel**
```kotlin
launch {
   interactor.moveToFolder(request)
}
```
where *launch* is from *kotlinx.coroutines* Builders.common.kt

**Inrecactor**
```kotlin
suspend fun moveToFolder(request: Request): Result<Unit, Error> {
    return try {
        Result.Success(repository.moveToFolder(request))
    } catch (throwable: Throwable) {
        Result.Fail(Error.MoveToFolderError)
    }
}
```

**Repository**
```kotlin
override suspend fun moveToFolder(request: Request)  {
    db.createMovingRequest(request)
}
```

**Database**
```kotlin
override fun createMovingRequest(request: Request) {
    Realm.getDefaultInstance().use {
        try {
            it.executeTransaction { realm ->
                val requests = realm.where<MovingRequest>().findFirst() ?: MovingRequest()
                requests.requestList.add(0, MovingToFolderRequest(request.postId, request.folderId))
                realm.copyToRealmOrUpdate(requests)
            }
        } catch (e: Exception) {
            Log.d("NewResult", "createMovingRequest() error: ${e.message}}")
        }
    }
}
```

If I stay with ```it.executeTransaction``` it cause exception from previous comment in *catch* block. 
But if I change it to ```it.executeTransactionAsync``` it throws an error with the following stacktrace:
```
2021-04-14 17:36:55.081 19534-19534/com.example.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android, PID: 19534
    io.realm.exceptions.RealmException: Async transaction failed
        at io.realm.Realm$1$2.run(Realm.java:1657)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: A RealmObject with no @PrimaryKey cannot be updated: class com.example.logic.domain.folders.move.MovingRequest
        at io.realm.Realm.checkHasPrimaryKey(Realm.java:1729)
        at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1090)
        at com.example.logic.local.db.realm.DatabaseImplRealm$createMovingRequest$$inlined$use$lambda$1.execute(DatabaseImpl.kt:446)
        at io.realm.Realm$1.run(Realm.java:1601)
        at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
````

**Comment by nowiwr01** [comment]
Ok, I think I've found a "solution" to the problem.
I noticed that I was missing something and when I replaced the implementation at the repository level the problem was gone.
 
I replaced the implementation above with
```kotlin
override suspend fun moveToFolder(request: Request) = withContext(Dispatchers.IO)  {
    db.createMovingRequest(request)
}
```
and change ```it.executeTransaction``` to ```it.executeTransactionAsync```. 

But I am still wondering why the error indicated a problem related to @PrimaryKey? 🙂

**Comment by nowiwr01** [comment]
But in my case I can't use ```it.executeTransactionAsync```, because it doesn't update my request in database. 
So, the problem is still relevant

**Comment by cmelchior** [comment]
Hi @nowiwr01 Sorry for the late reply.

I can see that you are using ` Realm.getDefaultInstance()`. Are you setting the default configuration somewhere? Otherwise it will not use the migration block you defined.

If that isn't the issue, we probably need a more fully fledged example as it is a bit hard to see where it could go wrong from the code you posted.

**Comment by nowiwr01** [comment]
Hi @cmelchior, sorry for the late feedback. 

Yes, in my code it looks something like this:
```kotlin
class DatabaseInitializer(private val localStorageDao: LocalStorageDao, context: Context) {

    init {
        Realm.init(context)
        
        val configuration = RealmConfiguration.Builder()
            .schemaVersion(5)
            .migration(MigrationBlock(context).apply {
                setStorage(localStorageDao)
            })
            .name("default.realm")
            .build()
            
        Realm.setDefaultConfiguration(configuration)
    }
    
}
```
Also I've tried to not use `Realm.getDefaultInstance()` by

```kotlin
class DatabaseImpl(private val config: RealmConfiguration? = null) : DataBase {

    private var realm: Realm? = null

     init {
        open()
    }
    
    override fun open() {
        if (realm == null) {
            realm = if (config != null) {
                Realm.getInstance(config)
            } else {
                Realm.getDefaultInstance()
            }
        }
    }
}
```
and use **realm** from above in **Database** something like this:

```kotlin
override fun createMovingRequest(request: Request) {
    try {
        realm!!.executeTransaction { 
            val requests = it.where<MovingRequest>().findFirst() ?: MovingRequest()
            requests.requestList.add(0, MovingToFolderRequest(request.postId, request.folderId))
            it.copyToRealmOrUpdate(requests)
        }
    } catch (e: Exception) {
        Log.d("NewResult", "createMovingRequest() error: ${e.message}}")
    }
}
```

but the error is still here :с

**Comment by clementetb** [comment]
@nowiwr01 what does setStorage(localStorageDao) do? and why are you using the migration result to set it up?

**Comment by cmelchior** [comment]
Hi @nowiwr01 Is this still an issue?
