### ISSUE TITLE
Configurations cannot be different if used to open the same file. 

### ISSUE THREAD

**Issue by xysedhasan** [realm/realm-java#7493]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.rubikkube.deafmatrimony, PID: 5320
    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.rubikkube.deafmatrimony/app.rubikkube.deafmatrimony.activities.UserInfoActivity}: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
    Cached configuration: 
    realmDirectory: /data/user/0/app.rubikkube.deafmatrimony/files
    realmFileName : default-realm
    canonicalPath: /data/user/0/app.rubikkube.deafmatrimony/files/default-realm
    key: [length: 0]
    schemaVersion: 0
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: MEM_ONLY
    schemaMediator: io.realm.DefaultRealmModuleMediator@7f9f5edf
    readOnly: false
    compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@f129e5e
    maxNumberOfActiveVersions: 9223372036854775807
    
    New configuration: 
    realmDirectory: /data/user/0/app.rubikkube.deafmatrimony/files
    realmFileName : default-realm
    canonicalPath: /data/user/0/app.rubikkube.deafmatrimony/files/default-realm
    key: [length: 0]
    schemaVersion: 0
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: MEM_ONLY
    schemaMediator: io.realm.DefaultRealmModuleMediator@7f9f5edf
    readOnly: false
    compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@1e2423f
    maxNumberOfActiveVersions: 9223372036854775807
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3338)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3487)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
    Cached configuration: 
    realmDirectory: /data/user/0/app.rubikkube.deafmatrimony/files
    realmFileName : default-realm
    canonicalPath: /data/user/0/app.rubikkube.deafmatrimony/files/default-realm
    key: [length: 0]
    schemaVersion: 0
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: MEM_ONLY
    schemaMediator: io.realm.DefaultRealmModuleMediator@7f9f5edf
    readOnly: false
    compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@f129e5e
    maxNumberOfActiveVersions: 9223372036854775807
    
    New configuration: 
    realmDirectory: /data/user/0/app.rubikkube.deafmatrimony/files
    realmFileName : default-realm
    canonicalPath: /data/user/0/app.rubikkube.deafmatrimony/files/default-realm
    key: [length: 0]
    schemaVersion: 0
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: MEM_ONLY
    schemaMediator: io.realm.DefaultRealmModuleMediator@7f9f5edf
    readOnly: false
    compactOnLaunch: io.realm.DefaultCompactOnLaunchCallback@1e2423f
    maxNumberOfActiveVersions: 9223372036854775807
        at io.realm.RealmCache.validateConfiguration(RealmCache.java:579)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:444)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
        at io.realm.Realm.getDefaultInstance(Realm.java:403)
        at app.rubikkube.deafmatrimony.activities.UserInfoActivity.onCreate(UserInfoActivity.java:178)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
        	... 11 more

**Comment by cmelchior** [comment]
Hi @xysedhasan 

Sorry for the late reply.

This sort of error usually happens if you are using one of our closures like `initialData or `compactOnLaunch`. The reason is. that we uses Java equals semantics to compare the configurations and if you create an anonymous lamda it is actually an entire new object that will fail the default equals check (which uses the memory address).

The work-around is to either store a static reference to the configuration or override `equals`/`hashCode` for that particular lamda.
