### ISSUE TITLE
Crash when minifyEnabled is set to true

### ISSUE THREAD

**Issue by Trailqueen** [realm/realm-java#7563]
### How frequently does the bug occur?

All the time

### Description

App crashes on startup when minify is enabled.
Do I need to add anything to the proguard-rules ?

### Stacktrace & log output

```shell
2021-09-10 10:29:05.868 20578-20578/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
        at c.a.a.a.e.V0(ManagerFragment.kt:5)
        at i.m.b.i0.q(FragmentStateManager.java:8)
        at i.m.b.i0.k(FragmentStateManager.java:11)
        at i.m.b.c0.S(FragmentManager.java:8)
        at i.m.b.c0.w(FragmentManager.java:5)
        at i.m.b.p.onStart(FragmentActivity.java:22)
        at i.b.c.g.onStart(AppCompatActivity.java:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:6997)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: io.realm.exceptions.RealmException: Could not find io.realm.RealmConfig$CommonModuleMediator
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:11)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:4)
        at j.b.e.l.g$b.b(SyncConfiguration.java:20)
        at c.a.a.b.c.<clinit>(RealmConfig.kt:4)
        at c.a.a.a.e.V0(ManagerFragment.kt:5) 
        at i.m.b.i0.q(FragmentStateManager.java:8) 
        at i.m.b.i0.k(FragmentStateManager.java:11) 
        at i.m.b.c0.S(FragmentManager.java:8) 
        at i.m.b.c0.w(FragmentManager.java:5) 
        at i.m.b.p.onStart(FragmentActivity.java:22) 
        at i.b.c.g.onStart(AppCompatActivity.java:1) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334) 
        at android.app.Activity.performStart(Activity.java:6997) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6710) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
     Caused by: java.lang.ClassNotFoundException: io.realm.RealmConfig$CommonModuleMediator
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:4)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:4) 
        at j.b.e.l.g$b.b(SyncConfiguration.java:20) 
        at c.a.a.b.c.<clinit>(RealmConfig.kt:4) 
        at c.a.a.a.e.V0(ManagerFragment.kt:5) 
        at i.m.b.i0.q(FragmentStateManager.java:8) 
        at i.m.b.i0.k(FragmentStateManager.java:11) 
        at i.m.b.c0.S(FragmentManager.java:8) 
        at i.m.b.c0.w(FragmentManager.java:5) 
        at i.m.b.p.onStart(FragmentActivity.java:22) 
        at i.b.c.g.onStart(AppCompatActivity.java:1) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334) 
        at android.app.Activity.performStart(Activity.java:6997) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6710) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.RealmConfig$CommonModuleMediator" on path: DexPathList[[zip file "/data/app/com.***.android--PQ2N9hk2y_kvMn3p2Y9KA==/base.apk"],nativeLibraryDirectories=[/data/app/com.***.android--PQ2N9hk2y_kvMn3p2Y9KA==/lib/arm64, /data/app/com.***.android--PQ2N9hk2y_kvMn3p2Y9KA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:4) 
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:4) 
        at j.b.e.l.g$b.b(SyncConfiguration.java:20) 
        at c.a.a.b.c.<clinit>(RealmConfig.kt:4) 
        at c.a.a.a.e.V0(ManagerFragment.kt:5) 
        at i.m.b.i0.q(FragmentStateManager.java:8) 
        at i.m.b.i0.k(FragmentStateManager.java:11) 
        at i.m.b.c0.S(FragmentManager.java:8) 
        at i.m.b.c0.w(FragmentManager.java:5) 
        at i.m.b.p.onStart(FragmentActivity.java:22) 
        at i.b.c.g.onStart(AppCompatActivity.java:1) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334) 
        at android.app.Activity.performStart(Activity.java:6997) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6710) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Set minify enabled to true and start app

### Version

10.8.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Multiple android versions

### Build environment

Android Studio version: 4.1.3
Android Build Tools version: 30.0.3

**Comment by cmelchior** [comment]
It looks like you have a `Common` module defined somewhere that it cannot find.

Realm ships with the needed proguard rules for this, so you shouldn't need to add anything yourself.

Can you post your Common module class?

Also, what does your project structure look like? Is everything inside one `app` module or in different modules? If the later, can you outline what the structure is?

**Comment by Trailqueen** [comment]
I have two modules. The CommonModule which includes the classes, that anyone should have access to and another module for user/task specific classes.

```
@RealmModule(classes = [Common::class, UserNames::class])
    open class CommonModule

    fun commonConfig(): SyncConfiguration {

        return SyncConfiguration
            .Builder(app.currentUser(), "common=common")
            .waitForInitialRemoteData(30, TimeUnit.SECONDS)
            .modules(CommonModule())
            .build()
    }

```

**Comment by Trailqueen** [comment]
I found the error on my side:
I had the Module Classes inside my RealmConfig class. This caused the error when minify was enabled.
Moving these classes out removes the issue.
