### ISSUE TITLE
In memory Realm doesn't get deleted after Realm close. io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed Exception backtrace: <backtrace not supported on this platform> () in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144. (76K Occurrences)

### ISSUE THREAD

**Issue by fzandroid** [realm/realm-java#7573]
### How frequently does the bug occur?

Every time

### Description

Upgraded from 5.13.1 to 7.0.0 as part of regular SDK upgrade. 

- Added encryption key while creating in-memory realm config.

After these changes were pushed to production, there was a very high number of crashes in Play Store Console and Firebase Crashlytics. 
 

### Stacktrace & log output

```shell
Fatal Exception: io.realm.exceptions.RealmException: Async transaction failed
       at io.realm.Realm$1$2.run(Realm.java:1657)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7081)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
Caused by io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed
Exception backtrace:
<backtrace not supported on this platform> () in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
       at io.realm.internal.OsSharedRealm.nativeCommitTransaction(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:283)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:441)
       at io.realm.Realm.commitTransaction(Realm.java:145)
       at io.realm.Realm$1.run(Realm.java:1607)
       at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

### Can you reproduce the bug?

Yes

### Reproduction Steps

Step 1 - App version 1 creates an in-memory realm configuration upon consumer's demand.
Step 2 - App version 2 creates an in-memory realm configuration upon consumer's demand but with an encryption key.
Step 3 - When a user migrates from App version 1 to App version 2, the app crashes.

### Version

7.0.0

### What SDK flavor are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Android 8,9,10,11

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by clementetb** [comment]
`Unrecoverable error. Decryption failed` is caused when you try to open an existing Realm with an invalid encryption data.

Could you check that the encryption key used to open such Realms is correct?
Have you been able to reproduce it?

**Comment by fzandroid** [comment]
Thanks for getting back. Yes, we can reproduce the issue every time now. Here is a use case that causes this crash -
1) App version 1 creates an in-memory realm configuration upon consumer's demand.
2) App version 2 creates an in-memory realm configuration upon consumer's demand but with an encryption key.
3) When a user migrates from App version 1 to App version 2, the app crashes.

As per the documentation, such Realm configurations are deleted from the memory after the realm closes but we can find memxxxx.realm files in the device file system. This in-memory file persistence causes the app to crash when the same file is tried to open with an encryption key. Here is a sample project we have created :

First comment line#188

build the app and install

uncomment line 188

build the app and install 

app crash all the time

**Comment by clementetb** [comment]
@fzandroid in-memory Realms write some data into the disk that is only closed when the latest Realm gets closed, and it is not cleared once it starts again after for example an update.

I am going to raise the issue with the Core team. Meanwhile, a solution to avoid the clash would be to change the in-memory Realm file name.

**Comment by fzandroid** [comment]
Thanks for providing the workaround. I tested the flow again and looks like in-memory Realm DB isn't getting deleted even after Realm has successfully closed. Will you be providing a fix for this in the coming releases?
From the consumer's perspective, our expectation is that we shouldn't have any in-memory Realm files in the application directory after Realm has closed. Is that correct?

**Comment by AlexanderZap** [comment]
How frequently does the bug occur?
Every time

Version
* "io.realm:realm-gradle-plugin:10.17.0"

Description
* Added encryption key while creating in-memory realm config.

Stacktrace

```
E/REALM_JNI: jni: ThrowingException 6, Decryption failed: 'unable to decrypt after 0 seconds (retry_count=0, from=i != bytes_read, size=4096)' () in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144, .
E/REALM_JNI: Exception has been thrown: Unrecoverable error. Decryption failed: 'unable to decrypt after 0 seconds (retry_count=0, from=i != bytes_read, size=4096)' () in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
E/ErrorHandlerImpl: ErrorHandler
    io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed: 'unable to decrypt after 0 seconds (retry_count=0, from=i != bytes_read, size=4096)' () in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
        at io.realm.internal.OsSharedRealm.nativeCommitTransaction(Native Method)
        at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:292)
        at io.realm.BaseRealm.commitTransaction(BaseRealm.java:459)
        at io.realm.Realm.commitTransaction(Realm.java:138)
        at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

```
 E/ErrorHandlerImpl: ErrorHandler
    io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed: 'unable to decrypt after 0 seconds (retry_count=0, from=i != bytes_read, size=4096)' () in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
```

`E/libc++abi: terminating with uncaught exception of type realm::util::DecryptionFailed: Decryption failed: 'unable to decrypt after 0 seconds (retry_count=0, from=iv1 == 0, size=4096)'`

Reproduction Steps
1. clean installation app
2. works with realm from multiple processes
3. get an unhandled exception

Can you reproduce the bug?
Yes

Are you using encryption?
Yes, using encryption

Platform OS and version(s)
Android 8.1,13
