### ISSUE TITLE
NullPointerException if calling a setter on the model proxy

### ISSUE THREAD

**Issue by thuytrinh** [realm/realm-java#758]
Model:
```java
public class TextModel extends RealmObject {
  private String text;
  private String fontPath;
  private float size;
  private float x;
  private float y;
  private int gravity;

  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public String getFontPath() {
    return fontPath;
  }

  public void setFontPath(String fontPath) {
    this.fontPath = fontPath;
  }

  public float getSize() {
    return size;
  }

  public void setSize(float size) {
    this.size = size;
  }

  public float getX() {
    return x;
  }

  public void setX(float x) {
    this.x = x;
  }

  public float getY() {
    return y;
  }

  public void setY(float y) {
    this.y = y;
  }

  public int getGravity() {
    return gravity;
  }

  public void setGravity(int gravity) {
    this.gravity = gravity;
  }
}
```

Test:
```java
import android.test.AndroidTestCase;

import io.realm.Realm;
import io.realm.RealmResults;

import static org.assertj.core.api.Assertions.assertThat;

public class TextModelTest extends AndroidTestCase {
  public void testShouldPersistTextModel() {
    String databaseFileName = "TextModelTest_" + System.currentTimeMillis();
    Realm realm = Realm.getInstance(getContext(), databaseFileName);

    realm.beginTransaction();

    TextModel expected = realm.createObject(TextModel.class);
    assertNotNull(expected);

    // NPE took place here!
    expected.setText("Awesome!");
    expected.setFontPath("/awesome_font.ttf");
    expected.setSize(47f);
    expected.setX(4f);
    expected.setY(7f);
    expected.setGravity(74);

    realm.commitTransaction();

    RealmResults<TextModel> results = realm.where(TextModel.class).findAll();
    assertThat(results).hasSize(1);

    TextModel actual = results.first();
    assertThat(actual.getText()).isEqualTo(expected.getText());
    assertThat(actual.getFontPath()).isEqualTo(expected.getFontPath());
    assertThat(actual.getSize()).isEqualTo(expected.getSize());
    assertThat(actual.getX()).isEqualTo(expected.getX());
    assertThat(actual.getY()).isEqualTo(expected.getY());
    assertThat(actual.getGravity()).isEqualTo(expected.getGravity());

    Realm.deleteRealmFile(getContext(), databaseFileName);
  }
}
```

Test output:
```
Running tests
Test running started
java.lang.NullPointerException
at io.realm.TextModelRealmProxy.setText(TextModelRealmProxy.java:34)
at com.thuytrinh.quotemaker.model.TextModelTest.testShouldPersistTextModel(TextModelTest.java:21)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

Finish
```

**Comment by thuytrinh** [comment]
Oops, when I went home, relaunched Android Studio and rerun the test to figure it out. The test passed. I don't know what caused the failure before. I'll reopen the issue if it happens again.

**Comment by nipun-mohan** [comment]
Try this
expected.setText(relam.copyToRealmOrUpdate("Awesome!"));
