### ISSUE TITLE
Exception links to 404 page

### ISSUE THREAD

**Issue by Jeff11** [realm/realm-java#7588]
### How frequently does the bug occur?

Seen once

### Description

The exception links to a 404 page: https://realm.io/news/android-installation-change/

### Stacktrace & log output

```shell
java.lang.ExceptionInInitializerError: RealmTransformer doesn't seem to be applied. Please update the project configuration to use the Realm Gradle plugin. See https://realm.io/news/android-installation-change/
        at io.realm.RealmConfiguration.<clinit>(RealmConfiguration.java:79)
        at io.realm.RealmConfiguration.access$000(RealmConfiguration.java:67)
        at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:545)
        at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:531)
        at io.realm.Realm.initializeRealm(Realm.java:319)
        at io.realm.Realm.init(Realm.java:261)
        at de.startupfreunde.bibflirt.ApplicationMain.onCreate(ApplicationMain.kt:107)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Can you reproduce the bug?

Yes, always

### Version

10.8.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Android Studio version: Android Studio Chipmunk | 2021.2.1 Canary 3
Build #AI-212.5284.40.2112.7855545, built on October 26, 2021

Android Build Tools version: 7.2.0-alpha03

Gradle version: 7.2.0-alpha03

**Comment by nathan-contino-mongo** [comment]
Thanks for letting us know about this. I've created a PR to fix this with a link to our docs installation page instead: https://github.com/realm/realm-java/pull/7589
