### ISSUE TITLE
Looking for clarification on vector crash

### ISSUE THREAD

**Issue by tSquaredd** [realm/realm-java#7655]
### How frequently does the bug occur?

Sometimes

### Description

Noticing a weird crash log coming through crashlytics lately. There are 2 different stack traces coming from the same crash site / log on crashlytics. The most common being: 

```
Fatal Exception: java.lang.IllegalStateException: vector
       at io.realm.internal.OsSharedRealm.nativeCommitTransaction(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:283)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:450)
       at io.realm.Realm.executeTransaction(Realm.java:1594)
       ...
```

And occasionally:
```
Fatal Exception: java.lang.OutOfMemoryError: std::bad_alloc in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144 
       at io.realm.internal.OsSharedRealm.nativeCommitTransaction(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:283)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:450)
       at io.realm.Realm.executeTransaction(Realm.java:1594)
       ...
```

I can not share a ton of internal code but the area that it appears to be crashing is during this block on the execute transaction line. 
```
Realm.getDefaultInstance().use { realm ->
    realm.executeTransaction { transactionRealm ->
        layout.updateInRealm(transactionRealm)
    }
}
```

Mainly wondering what the vector crash could relate to, I have not been able to find much in searching for it. When looking for the out of memory crash I mainly see mentions of not closing realms properly. Recently I started using `toFlow` for observing changes and I believe I am closing the realms properly but that could be a possible issue. This is how I am doing that: 

```kotlin
class SomeRealmRepository {
    val flowRealm: Realm by lazy { Realm.getDefaultInstance() }

    fun getSomeObjects(): Flow<List<SomeObject>?> {
        return flowRealm.where<SomeObject>()
            ... // adding to query
            .findAllAsync()
            .toFlow()
    }

    fun close() {
        flowRealm.close()
    }
}
```

Then in my viewModel
```kotlin
    override fun onCleared() {
        super.onCleared()
        someRealmRepository.close()
    }
```

and my view model is scoped to fragment:
```kotlin
private val viewModel: SomeViewModel by viewModels()
```

I know this is not a ton of information to work with and will be happy to provide additional details if I can. 

### Can you reproduce the bug?

Not yet

### Version

10.7.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Many Android versions and devices

### Build environment

Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 2
Android Build Tools version: 7.0.3
Gradle version: 7.0.2

**Comment by bmunkholm** [comment]
@tSquaredd Thanks for reporting this and sorry about the late reply! We are a bit backlogged atm. I would suggest you trace down the OutOfMemory situation, it's likely the root cause. My best suggestion is to stress test your app while monitoring memory usage to see if you are doing anything wrong. Otherwise it may just be related to users using your app on a low-memory device? From our end it's tricky to get much further without more info unfortunately.

**Comment by edualonso** [comment]
Closing due to inactivity.
