### ISSUE TITLE
java.lang.NoClassDefFoundError  Failed resolution of: Lcom/google/android/gms/common/R$string

### ISSUE THREAD

**Issue by fei116fei** [realm/realm-java#7703]
### How frequently does the bug occur?

All the time

### Description

help me，Gradle Plugin Version 4.1.2 , Gradle Version 6.5 。Android Studio 2021.2.1 Patch 1,Realm Version 5.15.2      7.0.0     10.0.0

### Stacktrace & log output

```shell
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/R$string;
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:4)
        at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@17.1.0:160)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.1.0:248)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.1.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2435)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.1.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:8414)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7927)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7672)
        at android.app.ActivityThread.access$2700(ActivityThread.java:279)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loopOnce(Looper.java:206)
        at android.os.Looper.loop(Looper.java:296)
```

### Can you reproduce the bug?

Yes, always

### Version

10.0.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Windows 10

### Build environment

Android Studio version: 2021.2.1 Patch 1
Android Build Tools version: 28.0.3
Gradle version: 6.5

**Comment by edualonso** [comment]
Hi @fei116fei. Could you share your `build.gradle` configuration files?

**Comment by edualonso** [comment]
Closing due to inactivity. Please reopen if you can provide the requested information
