### ISSUE TITLE
Getting lots of ANR

### ISSUE THREAD

**Issue by arifur-nureca** [realm/realm-java#7730]
### How frequently does the bug occur?

All the time

### Description

Getting lots of ANRs reported through Firebase Crashlytics tagged as Root blocking

### Stacktrace & log output

```shell
main (native): tid=1 systid=19686 
#00 pc 0x4b48c libc.so (syscall + 28)
#01 pc 0x4f074 libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb0dfc libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*) + 216)
#03 pc 0x4b45e4 split_config.arm64_v8a.apk!librealm-jni.so (std::__ndk1::mutex::lock() + 12)
       at io.realm.mongodb.sync.Sync.nativeReconnect(Native method)
       at io.realm.mongodb.sync.Sync.notifyNetworkIsBack(Sync.java:267)
       at io.realm.mongodb.sync.Sync.access$100(Sync.java:65)
       at io.realm.mongodb.sync.Sync$1.onChange(Sync.java:100)
       at io.realm.internal.network.NetworkStateReceiver.onReceive(NetworkStateReceiver.java:84)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8063)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

```

main (native): tid=1 systid=28226 
#00 pc 0x5ffdc libc.so (syscall + 28)
#01 pc 0x23f4d7 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 86)
#02 pc 0x1feecb libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*) + 858)
#03 pc 0x338753 split_config.armeabi_v7a.apk 
#04 pc 0x313411 split_config.armeabi_v7a.apk (Java_io_realm_internal_objectstore_OsApp_nativeCreate + 3296)
       at io.realm.internal.objectstore.OsApp.nativeCreate(Native method)
       at io.realm.internal.objectstore.OsApp.<init>(OsApp.java:31)
       at io.realm.mongodb.App.init(App.java:189)
       at io.realm.mongodb.App.<init>(App.java:180)
       at com.package.name$Companion.initMongoDbApp(Application.kt:540)
       at com.package.name.Application.resetMongoDbRetrofit(Application.kt:400)
       at com.package.name.Application.initMongoDbReceiver(Application.kt:376)
       at com.package.name.Application.onCreate(Application.kt:190)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
       at android.app.ActivityThread.access$1600(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### Can you reproduce the bug?

Not yet

### Version

10.11.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android ( 8.1.0, 11, 12)

### Build environment

Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526
Android Build Tools version: 7.2.2
Gradle version: 7.3.3-all

**Comment by cmelchior** [comment]
Hi @arifur-nureca Sorry for the late reply. The two reports are two different errors. Are any of them something you can reproduce or tell us how to replicate?
