### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. transaction_ended

### ISSUE THREAD

**Issue by silicon-pranit** [realm/realm-java#7742]
### How frequently does the bug occur?

All the time

### Description

1. This issue has **64046** crash events affecting **12175** users
2. We are not able to reproduce this one on our end

### Stacktrace & log output

```shell
<backtrace not supported on this platform> in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 901
       at io.realm.internal.Table.nativeWhere(Table.java)
       at io.realm.internal.Table.where(Table.java:638)
       at io.realm.RealmQuery.<init>(RealmQuery.java:154)
       at io.realm.RealmQuery.createQuery(RealmQuery.java:94)
       at io.realm.Realm.where(Realm.java:1564)
       at in.bizanalyst.dao.GroupDao.getAll(GroupDao.java:43)
       at in.bizanalyst.dao.GroupDao.getGroupsByParent(GroupDao.java:70)
       at in.bizanalyst.dao.CustomerDao.getQuery(CustomerDao.java:498)
       at in.bizanalyst.dao.CustomerDao.getAllByGroup(CustomerDao.java:235)
```

### Can you reproduce the bug?

Not yet

### Version

10.11.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Android SDK: 23, 25, 27, 28, 29, 30, 31, 32, 33

### Build environment

Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
Android Build Tools version: 33.0.0
Gradle version: 7.2.2

**Comment by edualonso** [comment]
Hi @silicon-pranit. In order for us to understand what is happening we need a native stack trace from your crash report - see https://developer.android.com/ndk/guides/ndk-stack. We cannot help you otherwise since the error appears to be happening at a C level in Core.

**Comment by silicon-pranit** [comment]
Noted! I will make necessary changes & will update on the thread.

**Comment by silicon-pranit** [comment]
@edualonso is this any helpful?

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> in.bizanalyst <<<

backtrace:
  #00  pc 0x00000000007649fc  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/split_config.arm64_v8a.apk!librealm-jni.so
  #01  pc 0x00000000007b558c  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/split_config.arm64_v8a.apk!librealm-jni.so
  #02  pc 0x00000000007b5cc0  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/split_config.arm64_v8a.apk!librealm-jni.so
  #03  pc 0x000000000050b02c  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/split_config.arm64_v8a.apk!librealm-jni.so (Java_io_realm_internal_OsSharedRealm_nativeGetTableRef+172)
  #04  pc 0x00000000000a45b4  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.odex (art_jni_trampoline+180)
  #05  pc 0x0000000002097c10  /memfd:/jit-cache (io.realm.RealmSchema.getTable+752)
  #06  pc 0x0000000002130ccc  /memfd:/jit-cache (io.realm.RealmSchema.getSchemaForClass+444)
  #07  pc 0x00000000021314d4  /memfd:/jit-cache (io.realm.RealmQuery.<init>+356)
  #08  pc 0x0000000002129f0c  /memfd:/jit-cache (in.bizanalyst.dao.GroupDao.getGroupsByParent+172)
  #09  pc 0x0000000002176a4c  /memfd:/jit-cache (in.bizanalyst.dao.GroupDao.getGroupsByParentList+124)
  #10  pc 0x00000000001365b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568)
  #11  pc 0x00000000001450cc  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276)
  #12  pc 0x00000000002e2898  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #13  pc 0x00000000002dd924  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+900)
  #14  pc 0x00000000005a34e0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368)
  #15  pc 0x0000000000130994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #16  pc 0x00000000015ab768  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (in.bizanalyst.pojo.realm.Group.getGroupListForFilter+260)
  #17  pc 0x00000000005a37e0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
  #18  pc 0x0000000000130994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
  #19  pc 0x0000000001613254  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (in.bizanalyst.viewmodel.CustomerViewModel$getGroupListFilter$1.invokeSuspend+92)
  #20  pc 0x00000000005a6e68  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
  #21  pc 0x0000000000134594  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
  #22  pc 0x00000000017100fa  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+26)
  #23  pc 0x00000000005a243c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740)
  #24  pc 0x0000000000130a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #25  pc 0x0000000001bfc98c  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.DispatchedTask.run+236)
  #26  pc 0x00000000005a243c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740)
  #27  pc 0x0000000000130a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #28  pc 0x0000000001c066bc  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.internal.LimitedDispatcher.run+24)
  #29  pc 0x00000000005a243c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740)
  #30  pc 0x0000000000130a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #31  pc 0x0000000001c0954e  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.scheduling.TaskImpl.run+4)
  #32  pc 0x00000000005a243c  /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740)
  #33  pc 0x0000000000130a14  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
  #34  pc 0x0000000001c091a2  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely)
  #35  pc 0x00000000005a6e68  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
  #36  pc 0x0000000000134594  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
  #37  pc 0x0000000001c08584  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask+28)
  #38  pc 0x00000000005a6e68  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
  #39  pc 0x0000000000134594  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
  #40  pc 0x0000000001c08656  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker+56)
  #41  pc 0x00000000005a6e68  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
  #42  pc 0x0000000000134594  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
  #43  pc 0x0000000001c08612  /data/app/in.bizanalyst-YXejlvBGrommnCHiRHIBhw==/oat/arm64/base.vdex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run)
  #44  pc 0x00000000002b31c8  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.17429910035047654377)+240)
  #45  pc 0x0000000000591dd8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024)
  #46  pc 0x000000000013f468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
  #47  pc 0x0000000000136334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #48  pc 0x00000000001450ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #49  pc 0x00000000004b0c48  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #50  pc 0x00000000004b1cf8  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #51  pc 0x00000000004f2248  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #52  pc 0x00000000000e2364  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #53  pc 0x0000000000083d98  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by clementetb** [comment]
@silicon-pranit We cannot use that stacktrace to debug because it is not complete, there are some missing values like the build-id. 

[Here is an example of a full stacktrace](https://github.com/realm/realm-java/issues/7731#issuecomment-1280600262)
