### ISSUE TITLE
Caused by j8.b: Could not find 'librealm-jni.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

### ISSUE THREAD

**Issue by adaonder** [realm/realm-java#7767]
### How frequently does the bug occur?

Sometimes

### Description

Caused by j8.b: Could not find 'librealm-jni.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
       at io.realm.Realm.initializeRealm(Realm.java:348)
       at io.realm.Realm.init(Realm.java:263)
       at com.globme.common.data.local.realm.LocalRealmDB.realConfiguration(LocalRealmDB.java:27)
       at com.globme.timeware.application.Application.onCreate(Application.java:34)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7233)
       at android.app.ActivityThread.access$1700(ActivityThread.java:292)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

### Stacktrace & log output

```shell
Caused by j8.b: Could not find 'librealm-jni.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
       at io.realm.Realm.initializeRealm(Realm.java:348)
       at io.realm.Realm.init(Realm.java:263)
       at com.globme.common.data.local.realm.LocalRealmDB.realConfiguration(LocalRealmDB.java:27)
       at com.globme.timeware.application.Application.onCreate(Application.java:34)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7233)
       at android.app.ActivityThread.access$1700(ActivityThread.java:292)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

### Can you reproduce the bug?

-- select --

### Version

10.13.2-transformer-api

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 12

### Build environment

Android Studio version: Android Studio Electric Eel | 2022.1.1 Patch 1
Android Build Tools version: Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Gradle version: gradle:7.4.1

**Comment by cmelchior** [comment]
Hi @adaonder 

We have seen this happen in a few cases:

- If you are using App Bundles and are using an APK that was copied from another device. This usually requires a rooted device.
- If the app was downloaded from a 3rd party app store that didn't package the so files correctly (see above).
- If you are running the app in an emulator that don't match exactly the architecture you are building for.

All of these things are unfortunately outside our control.

If you somehow are able to reproduce this, we would love to get the details.

**Comment by adaonder** [comment]
Hi @cmelchior

I think the source of the problem is app bundles(.aab). I download the app from Google Play Store. 
The problem comes out like that, but it doesn't always happen. 
it happened on first install, i saw samsung galaxy s10 lite with android 12 once then i couldn't catch it again. 
I was using google room db now I am using real library.

**Comment by edualonso** [comment]
Hi @adaonder 
Unfortunately we can't help you with this unless you provide us with a way to reproduce the error. Please let us know if you find a way to do it.

**Comment by Koster35** [comment]
Hi, we just started seeing this same issue today in our Crashlytics console.
We are using Realm 10.10.1 and have been for about a year now, but haven't seen this appear until today. We deploy our app using AABs, rather than APKs.
So far, it has only appeared on Android 8 and 10 devices. LGE Nexus 5X devices running Android 8.1 are most affected. No device this has occurred on is rooted.

We have not reproduced this issue ourselves, but I will provide more information as I am able to. Thanks.

**Comment by adaonder** [comment]
Realm.init(context); I was getting it when I typed it in Application. Now I wrote it in Activity I no longer get this error.

**Comment by adaonder** [comment]
@edualonso Realm.init(context); I was getting it when I typed it in Application. Now I wrote it in Activity I no longer get this error.

**Comment by adaonder** [comment]
@edualonso  this method Realm.init(context); I was getting it when I typed it in Application. Now I wrote it in Activity I no longer get this error.

**Comment by 0neel** [comment]
We experience the same issue. The interesting detail is that the crash mostly (99%) happens on HONOR devices which may mean it's somehow related to missing Google service. Is that possible?

**Comment by onderadaidenfit** [comment]
@clementetb 

I already saw it by chance once, it didn't happen yet. It was constantly coming up on firebase.

**Comment by onderadaidenfit** [comment]
maybe there is a bug in android. But I first saw this error in your library. There was this error when the application was in the extended class. The command there is Realm.init().

**Comment by adaonder** [comment]
@cmelchior, @clementetb,  You can close this thread if you want. because this error hasn't come yet since I changed my code.

**Comment by clementetb** [comment]
Initializing the code in `Application` shouldn't be the issue.

@adaonder On what callback were you invoking `Realm.init`, was it on `onCreate` or `attachBaseContext`?

**Comment by adaonder** [comment]
@clementetb 

Old Code: 

`@Override
    public void onCreate() {
        super.onCreate();
        instance = this;
        LocalRealmDB.getInstance().realConfiguration(getApplicationContext());
    }`
    
    And
    
    LocalRealmDB class; 
    
    `public static LocalRealmDB getInstance() {
        return new LocalRealmDB();
    }`
    
    `public void realConfiguration(Context context) {
    
        Realm.init(context);
        
        RealmConfiguration configuration = new RealmConfiguration.Builder().schemaVersion(SCHEMA_V_NOW).name(realmName).build()
        
        Realm.setDefaultConfiguration(configuration);
        
    }`

**Comment by juckrit** [comment]
Is there any update on this issue, I still have this problem

**Comment by GSSPawanKumarSingh** [comment]
> The same problem Unable to create application com.intertel.myenel.MyEnelApplication: com.getkeepsafe.relinker.b: Could not find 'librealm-jni.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
> 
> Pixel 6 pro

Getting same error in my firebase crashanalytics dashboard.
