### ISSUE TITLE
Can't get flow for first item in DB

### ISSUE THREAD

**Issue by Kolyall** [realm/realm-java#7778]
### How frequently does the bug occur?

-- select --

### Description

My db can only contain 1 element or not have any element and i would like to observe this element so i made a flow
```
 suspend inline fun <reified T : RealmObject> firstItemChangeListenerFlow(): Flow<T?> {
        return withContext(Dispatchers.Main) {
            val realmInstance = Realm.getInstance(
RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .schemaVersion(dbVersionNumber.toLong())
                .encryptionKey(encryptionKey)
                .modules(baseModule, *additionalModules)
                .name("$name.realm").build()
)
 

            realmInstance
                .where(T::class.java)
                .findFirst()
                .toFlow()
                .map { firstItem ->
                    firstItem?.let { realmInstance.copyFromRealm(it) }
                }
        }
            .flowOn(Dispatchers.Main)
    }
```

### Stacktrace & log output

```shell
java.lang.IllegalArgumentException: Only valid managed objects can be copied from Realm.
        at io.realm.Realm.checkValidObjectForDetach(Realm.java:1891)
        at io.realm.Realm.copyFromRealm(Realm.java:1551)
        at io.realm.Realm.copyFromRealm(Realm.java:1524)
```
```


### Can you reproduce the bug?

Always

### Reproduction Steps

_No response_

### Version

10.13.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android

### Build environment

Android Studio version: Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-139-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (221.6095)
    com.intellij.marketplace (221.6008.18)
    com.intellij.javafx (1.0.4)
    co.anbora.labs.kse (1.2.2)
    JUnit4-Parallel-Runner (1.5)
    com.atlassian.bitbucket.references (2022.1.223)
    com.thoughtworks.gauge (221.6008.13)
    com.developerphil.adbidea (1.6.8)

Current Desktop: ubuntu:GNOME


Android Build Tools version: 7.4.1
Gradle version: https\://services.gradle.org/distributions/gradle-7.6-bin.zip

**Comment by clementetb** [comment]
Hi, we are missing some code details in the snippet you posted, how are you instantiating `realmInstance`? It doesn't look like valid code, as it appears that the instance is not open, would you mind posting some valid example?

**Comment by Kolyall** [comment]
@clementetb fixed example, please, take a look above

**Comment by rorbech** [comment]
Hi @Kolyall. I am not able to reproduce your observation. Are you able to supply a minimal project that reproduces the issue that we can inspect? 

Please note that it is not allowed to perform writes and queries on the UI/Main thread without explicitly opting in to that on the configuration builder
```
configurationBuilder.allowQueriesOnUiThread(true)
```
so your issue might be an side effect of some other error. But again, I am not able to replicate your observation so please provide a minimal project that reproduces the error for us to investigate the issue.

**Comment by cmelchior** [comment]
Hi @Kolyall We assume you found a solution for this. If not, feel free to reopen it.
