### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH

### ISSUE THREAD

**Issue by victorjimbei** [realm/realm-java#7894]
### How frequently does the bug occur?

Always

### Description

Hello, 
I was testing our appliaction with an Android emulator with [Android 15 with support for 16KB](https://developer.android.com/guide/practices/page-sizes) page sizes, and it crashed with the below stacktrace when trying to init the Realm instance. 

### Stacktrace & log output

```shell
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.testapp.qa/app_lib/librealm-jni.so.10.18.0" (new hash type from the future?)                                                               at java.lang.Runtime.load0(Runtime.java:933)                                                                at java.lang.System.load(System.java:1729)                      at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)               at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)                     at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)                                         at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)                                      at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)                                      at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)                                                       at io.realm.Realm.initializeRealm(Realm.java:348)                                                               at io.realm.Realm.init(Realm.java:263)
```

### Can you reproduce the bug?

Always

### Reproduction Steps

I've created a sample app to reproduce this bug and pushed it on [github](https://github.com/victorjimbei/RealmSampleApplication). 
Steps to reproduce: 
1. Clone the RealmSampleApplication project.
2. Create an Android emulator following steps from this page: https://developer.android.com/guide/practices/page-sizes#16kb-emulator
3. Build and run the app. 
4. It will crash as soon as the `Realm.init(this)` is called.

### Version

10.18.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android 15 Beta 2 (Android API VanillaIceCream (Google APIs Page Size 16KB))

### Build environment

Android Studio version: Android Studio Koala | 2024.1.1 Beta 2
Android Build Tools version: 35-rc4
Gradle version: 8.4.1

**Comment by VicMikhailau** [comment]
The same issue.

**Comment by yd-threra-and** [comment]
We are also encountering this issue with the Realm SDK on Android 15 emulators with 16 KB page sizes.

We are in the middle of developing our next official release that will support Android 15, and this issue is critical for our progress. Could you please provide any updates on the status of this issue? Is there a planned fix for both the Java and Kotlin SDKs?

**Comment by victorjimbei** [comment]
A similar issue for [the kotlin version ](https://jira.mongodb.org/browse/RKOTLIN-1105) is in progress.

**Comment by Mihir3646** [comment]
On Realm.init(this);
getting the same error in lib version 10.18.0

 Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: cannot locate symbol "ExecuteProgram" referenced by "/data/data/com.freeit.java/app_lib/librealm-jni.so.10.18.0"...
java.lang.Runtime.load0 (Runtime.java:933)
java.lang.System.load (System.java:1729)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:204)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:134)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:57)
io.realm.internal.RealmCore.loadLibrary (RealmCore.java:60)
io.realm.Realm.isInstantApp (Realm.java:318)
io.realm.Realm.initializeRealm (Realm.java:344)
io.realm.Realm.init (Realm.java:47)

**Comment by swankjesse** [comment]
I saw a similar crash with an unrelated cause. I was able to fix it in our NDK project by following the Android guide, [Support 16 KB page sizes](https://developer.android.com/guide/practices/page-sizes#cmake).

**Comment by ridcully99** [comment]
So, is this project now abandoned  by MongoDB? This issue here will break all apps using Realm on Android devices with the new 16KB page size and they don't even care.

**Comment by Mihir3646** [comment]
> So, is this project now abandoned by MongoDB? This issue here will break all apps using Realm on Android devices with the new 16KB page size and they don't even care.

Yes, it's almost 2 months, and still no update on this. Really !!!

**Comment by mannodermaus** [comment]
I ended up compiling Realm myself with the 16 KB page size flags, and this caused our crash on launch to go away. While it's a pretty simple change, it needs some more thorough testing (esp. with the object server library, which we aren't using in our project). https://github.com/realm/realm-java/pull/7897

**Comment by asadwaheed1** [comment]
I am having the same problem on android emulator running android 15

**Comment by ABINAYASEL** [comment]
I am facing same issue, when will be the new version released with this fix?

**Comment by jzbrooks** [comment]
We ran into this issue and #7894 appears to have solved it for us. Closing this issue might make sense.

**Comment by helloyzp** [comment]
在做Android15的16kb设备适配，Realm初始化就发生崩溃crash，sdk使用的是[Realm - Java SDK](https://www.mongodb.com/zh-cn/docs/atlas/device-sdks/sdk/java/install/#std-label-java-install)，版本10.17.0，Android系统使用的是Android studio的模拟器的16KB Page Size Google APIs镜像，Realm初始化崩溃报错的日志：
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.superex.ex/app_lib/librealm-jni.so.10.17.0" (new hash type from the future?)
                                                                                                    	at java.lang.Runtime.load0(Runtime.java:933)
                                                                                                    	at java.lang.System.load(System.java:1729)
                                                                                                    	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
                                                                                                    	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:206)
                                                                                                    	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                                                    	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
                                                                                                    	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
                                                                                                    	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
                                                                                                    	at io.realm.Realm.initializeRealm(Realm.java:348)
                                                                                                    	at io.realm.Realm.init(Realm.java:263)

于是把Realm升级到最新版10.19.0，Realm初始化继续崩溃crash报错：
Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x773873378018 in tid 11230), pid 11230 

如何解决？

**Comment by helloyzp** [comment]
> We are also encountering this issue with the Realm SDK on Android 15 emulators with 16 KB page sizes.
> 
> We are in the middle of developing our next official release that will support Android 15, and this issue is critical for our progress. Could you please provide any updates on the status of this issue? Is there a planned fix for both the Java and Kotlin SDKs?

现在修复了吗，已经是2025年7月29日了

**Comment by helloyzp** [comment]
> I am having the same problem on android emulator running android 15 with 16KB page size rom

Is it fixed now?

**Comment by Mihir3646** [comment]
I think the 16KB page size issue fixed in version [10.19.0](https://github.com/realm/realm-java/blob/main/CHANGELOG.md#10190-2024-09-13)

**Comment by helloyzp** [comment]
> I think the 16KB page size issue fixed in version [10.19.0](https://github.com/realm/realm-java/blob/main/CHANGELOG.md#10190-2024-09-13)

Obviously not, crashes during initialization

**Comment by Mihir3646** [comment]
> > I think the 16KB page size issue fixed in version [10.19.0](https://github.com/realm/realm-java/blob/main/CHANGELOG.md#10190-2024-09-13)
> 
> Obviously not, crashes during initialization

I am also using this lib in my project, but resolved it after version update.
Did you check proGuard rules?

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep @interface io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule { *; }

-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }

-keep class io.realm.internal.KeepMember
-keep @io.realm.internal.KeepMember class * { @io.realm.internal.KeepMember *; }

-dontwarn javax.**
-dontwarn io.realm.**
-dontwarn io.reactivex.android.**

-keep class io.realm.RealmCollection
-keep class io.realm.OrderedRealmCollection
-keepclasseswithmembernames class io.realm.** {
    native <methods>;
}
```
