### ISSUE TITLE
ClassCastException in RealmProcessor

### ISSUE THREAD

**Issue by jenzz** [realm/realm-java#795]
I'm getting the following error when trying to compile my app:

```
Caused by: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.TypeElement
	at io.realm.processor.RealmProcessor.process(RealmProcessor.java:75)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 65 more
```

Any ideas?

**Comment by jenzz** [comment]
Never mind. My bad.

The culprit was a no longer existing custom annotation I left somewhere in the code.
Still interesting though that the `RealmProcessor` complained about it first..

**Comment by kboyarshinov** [comment]
I'm also getting this. @jenzz What was your problem?

**Comment by jenzz** [comment]
@kboyarshinov Hmm, iirc there was still a reference to an annotation in the code which no longer existed.
I am using Dagger for DI and usually create a custom annotation for every dependency I want to inject.

For some reason the `RealmProcessor` was the first to complain about it.
So, I think, in other words, this isn't necessarily a Realm-related issue.
Maybe just check if your code still compiles when excluding Realm entirely?

**Comment by kboyarshinov** [comment]
@jenzz Thanks. I'm also using Dagger for DI. I'll check it for compilation without Realm.

**Comment by JulienDev** [comment]
Same here, I upgraded to ButterKnife 7 and @InjectView which does not exist anymore was causing the same error.
