### ISSUE TITLE
Got a RealmMigrationException even without changing the schema. 

### ISSUE THREAD

**Issue by ImGauravC** [realm/realm-java#796]
It says "Column count doesn't match". This happens a few times for some users and when it happens, expectedly, the app refuses to start up. How could it throw RealmMigrationException with the first version of the app?

**Comment by cmelchior** [comment]
Hi @ImGauravC 

"Column count doesn't match" and RealmMigrationExceptions are two separate concepts.

1) RealmMigrationExceptions happens the first time you open a Realm instance and the Realm on disk doesn't match the realm classes in your app. It should *never* happen from a fresh install. Perhaps they had a test-app installed with the same package name?

2) "Column count doesn't match" can happen during a query, where the input parameters doesn't match the schema of the Realm. We recently fixed a bug  which might be what you are seeing?  https://github.com/realm/realm-java/pull/721

Without further information it is hard to say what is going wrong. Please see https://github.com/realm/realm-java#filing-issues

**Comment by ImGauravC** [comment]
This is the stacktrace I get.

```java
io.realm.exceptions.RealmMigrationNeededException
       at io.realm.Realm.createAndValidate(Realm.java:513)
       at io.realm.Realm.create(Realm.java:414)
       at io.realm.Realm.getInstance(Realm.java:332)
       at io.realm.Realm.getInstance(Realm.java:294)
       at io.realm.Realm.getInstance(Realm.java:275)
       at [package_name].MessageSender.sendMessage(MessageSender.java:40)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at [package_name].CustomHandlerThread.run(CustomHandlerThread.java:167)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at io.realm.Realm.createAndValidate(Realm.java:509)
       at io.realm.Realm.create(Realm.java:414)
       at io.realm.Realm.getInstance(Realm.java:332)
       at io.realm.Realm.getInstance(Realm.java:294)
       at io.realm.Realm.getInstance(Realm.java:275)
       at [package_name].MessageSender.sendMessage(MessageSender.java:40)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at [package_name].CustomHandlerThread.run(CustomHandlerThread.java:167)
Caused by: java.lang.IllegalStateException: Column count does not match
       at io.realm.MessageModelRealmProxy.validateTable(MessageModelRealmProxy.java:245)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at io.realm.Realm.createAndValidate(Realm.java:509)
       at io.realm.Realm.create(Realm.java:414)
       at io.realm.Realm.getInstance(Realm.java:332)
       at io.realm.Realm.getInstance(Realm.java:294)
       at io.realm.Realm.getInstance(Realm.java:275)
       at [package_name].MessageSender.sendMessage(MessageSender.java:40)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at [package_name].CustomHandlerThread.run(CustomHandlerThread.java:167)

**Comment by cmelchior** [comment]
Hi @ImGauravC 
Thank you for the stack trace. The validateTable method is called when first opening the Realm, and it should never throw an error on a empty Realm.

Is the Realm empty or do you provide a prefilled Realm with your app?

**Comment by cmelchior** [comment]
I assume you got this working. If not, please add additional information.

**Comment by ramden** [comment]
Got the same. It is prefilled. Added a new Table and trying to create a linked list in the migration (adding column to an existing table

Table realmstrings = realm.getTable(RealmString.class);
topicUserTable.addColumnLink(ColumnType.LINK_LIST, "recommusers", realmstrings);

Error:
java.lang.RuntimeException: Unable to create application com.yoversusno.yovsno.App: io.realm.exceptions.RealmMigrationNeededException: Field count does not match - expected 1 but was 0

Field count 0 ?
