### ISSUE TITLE
Eclipse, none of the two libraries work (Nexus 5 - Android 5.0.1 & Unitech PA700 Android 4.1.1)

### ISSUE THREAD

**Issue by andreborud** [realm/realm-java#817]
I'm trying to use realm 0.78.0 in a library project I have as a part of a bigger app. 

Whenever I try to run it on my nexus 5 I get the following error when I try to initialize realm:

Nexus 5 - Android 5.0.1: full .jar in /lib or eclipse jar with .so files in /lib or /libs
```
Process: es.treenovum.openeyelauncher.ui, PID: 9116
java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 	at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/Realm;
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:210)
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:1)
 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 	... 3 more
 Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.Realm" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/es.treenovum.openeyelauncher.ui-1/base.apk"],nativeLibraryDirectories=[/data/app/es.treenovum.openeyelauncher.ui-1/lib/arm, /vendor/lib, /system/lib]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 	... 7 more
 	Suppressed: java.lang.ClassNotFoundException: io.realm.Realm
 		at java.lang.Class.classForName(Native Method)
 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 8 more
 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

if full .jar is in /libs
```
The library 'realm-0.78.0.jar' contains native libraries that will not run on the device.
Additionally some of those libraries will interfer with the installation of the application because of their location in lib/
lib/ is reserved for NDK libraries.
The following libraries were found:
  - lib/armeabi/libtightdb-jni.so
  - lib/armeabi-v7a/libtightdb-jni.so
  - lib/mips/libtightdb-jni.so
  - lib/x86/libtightdb-jni.so
```

Though the app should be specifically built for a Unitech PA700 device, running it there instead gives the following errors depending on where the .jar is:

Unitech PA700 .so in /lib .jar in /libs Android 4.1.1
```
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
 	at java.lang.Thread.run(Thread.java:856)
 Caused by: java.lang.ExceptionInInitializerError
 	at io.realm.Realm.<init>(Realm.java:159)
 	at io.realm.Realm.createAndValidate(Realm.java:441)
 	at io.realm.Realm.create(Realm.java:420)
 	at io.realm.Realm.getInstance(Realm.java:336)
 	at io.realm.Realm.getInstance(Realm.java:298)
 	at io.realm.Realm.getInstance(Realm.java:279)
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:210)
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:1)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
 	... 4 more
 Caused by: java.lang.UnsatisfiedLinkError: Couldn't load tightdb-jni: findLibrary returned null
 	at java.lang.Runtime.loadLibrary(Runtime.java:365)
 	at java.lang.System.loadLibrary(System.java:538)
 	at io.realm.internal.TightDB.loadLibrary(TightDB.java:144)
 	at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:31)
 	... 14 more
```

Unitech PA700 full .jar in /lib Android 4.1.1
```
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
 	at java.lang.Thread.run(Thread.java:856)
 Caused by: java.lang.NoClassDefFoundError: io.realm.Realm
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:210)
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:1)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
 	... 4 more
```

Not sure if this is something I'm doing wrong or if its a bug in realm. Suggestions?

**Comment by emanuelez** [comment]
Hello André,

As you can see in our [documentation](http://realm.io/docs/java/0.78.0/#installation) you should copy all the contents of the eclipse folder (the small jar file and the four folders, not the .so files) into the **libs** folder of your project, not lib, as you mention.

Can you please try this out and report back? :)

**Comment by andreborud** [comment]
Ooops, thats what I get for not reading the full instructions thinking I know it all! :)

It removes the error I had before, but I get a different one:

```


 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 	at java.lang.Thread.run(Thread.java:818)
 Caused by: io.realm.exceptions.RealmException: Could not find the generated io.realm.CategoryRealmProxy class: Annotation processor may not have been executed.
 	at io.realm.Realm.initializeRealm(Realm.java:498)
 	at io.realm.Realm.createAndValidate(Realm.java:448)
 	at io.realm.Realm.create(Realm.java:420)
 	at io.realm.Realm.getInstance(Realm.java:336)
 	at io.realm.Realm.getInstance(Realm.java:298)
 	at io.realm.Realm.getInstance(Realm.java:279)
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:210)
 	at es.treenovum.paedocuments.services.OfflineService$WidgetOpsNewest.doInBackground(OfflineService.java:1)
 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 	... 3 more
```

I'm using Java 1.7, I've added the annotations processor and the jar. Any idea?

**Comment by bmunkholm** [comment]
The proxy classes that Realm generates from your models could not be found. You need to include a path to those as well.

**Comment by andreborud** [comment]
@bmunkholm  Not really sure what you mean I should do?

**Comment by andreborud** [comment]
Figured it out with the help of stackoverflow: http://stackoverflow.com/a/26332602/964887

Thanks for you help guys and quick answers.
