### ISSUE TITLE
Couldn't load tightdb-jni

### ISSUE THREAD

**Issue by samyboy89** [realm/realm-java#837]
I'm trying to support Android 3.2, on a Sony GS8 with Google TV, but Realm is making it crash. I get the following error:

    Caused by: java.lang.UnsatisfiedLinkError: Couldn't load tightdb-jni: findLibrary returned null

jus by calling:

    Realm.getInstance(mContext);

Is there a solution?

**Comment by emanuelez** [comment]
Hello,

can you please provide the whole stacktrace?

On Sat, Feb 7, 2015 at 11:31 PM, Sam Mathias Weggersen <
notifications@github.com> wrote:

> I'm trying to support Android 3.2, on a Sony GS8 with Google TV, but Realm
> is making it crash. I get the following error:
>
> Caused by: java.lang.UnsatisfiedLinkError: Couldn't load tightdb-jni: findLibrary returned null
>
> jus by calling:
>
> Realm.getInstance(mContext);
>
> Is there a solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/837>.
>



-- 
*Emanuele Zattin* (@emanuelez <https://twitter.com/emanuelez>)
SW Engineer & CI Specialist

**Comment by samyboy89** [comment]
02-07 22:20:05.216    3216-3216/? E/AndroidRuntime﹕ FATAL EXCEPTION: main java.lang.ExceptionInInitializerError
     at io.realm.Realm.<init>(Realm.java:159)
     at io.realm.Realm.createAndValidate(Realm.java:441)
     at io.realm.Realm.create(Realm.java:418)
     at io.realm.Realm.getInstance(Realm.java:336)
     at io.realm.Realm.getInstance(Realm.java:298)
     at io.realm.Realm.getInstance(Realm.java:279)
     at com.test.menu.MenuSection.<init>(MenuSection.java:53)
     at com.test.menu.Menu.changeMenu(Menu.java:172)
     at com.test.menu.Menu.makeMenuChange(Menu.java:162)
     at com.test.menu.Menu.access$100(Menu.java:38)
     at com.test.menu.Menu$4.onKey(Menu.java:143)
     at android.view.View.dispatchKeyEvent(View.java:4598)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1161)
     at android.widget.ListView.dispatchKeyEvent(ListView.java:2061)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at com.android.internal.policy.impl.tv.TvWindow$DecorView.superDispatchKeyEvent(TvWindow.java:1155)
     at com.android.internal.policy.impl.tv.TvWindow.superDispatchKeyEvent(TvWindow.java:790)
     at android.app.Activity.dispatchKeyEvent(Activity.java:2316)
     at com.android.internal.policy.impl.tv.TvWindow$DecorView.dispatchKeyEvent(TvWindow.java:1111)
     at android.view.ViewRoot.deliverKeyEventPostIme(ViewRoot.java:2946)
     at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2916)
     at android.view.ViewRoot.handleMessage(ViewRoot.java:2093)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:132)
     at android.app.ActivityThread.main(ActivityThread.java:4196)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:491)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
     at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Couldn't load tightdb-jni: findLibrary returned null
     at java.lang.Runtime.loadLibrary(Runtime.java:425)
     at java.lang.System.loadLibrary(System.java:554)
     at io.realm.internal.TightDB.loadLibrary(TightDB.java:144)
     at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:31)
     at io.realm.Realm.<init>(Realm.java:159)
     at io.realm.Realm.createAndValidate(Realm.java:441)
     at io.realm.Realm.create(Realm.java:418)
     at io.realm.Realm.getInstance(Realm.java:336)
     at io.realm.Realm.getInstance(Realm.java:298)
     at io.realm.Realm.getInstance(Realm.java:279)
     at com.test.menu.MenuSection.<init>(MenuSection.java:53)
     at com.test.menu.Menu.changeMenu(Menu.java:172)
     at com.test.menu.Menu.makeMenuChange(Menu.java:162)
     at com.test.menu.Menu.access$100(Menu.java:38)
     at com.test.menu.Menu$4.onKey(Menu.java:143)
     at android.view.View.dispatchKeyEvent(View.java:4598)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1161)
     at android.widget.ListView.dispatchKeyEvent(ListView.java:2061)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1163)
     at com.android.internal.policy.impl.tv.TvWindow$DecorView.superDispatchKeyEvent(TvWindow.java:1155)
     at com.android.internal.policy.impl.tv.TvWindow.superDispatchKeyEvent(TvWindow.java:790)
     at android.app.Activity.dispatchKeyEvent(Activity.java:2316)
     at com.android.internal.policy.impl.tv.TvWindow$DecorView.dispatchKeyEvent(TvWindow.java:1111)
     at android.view.ViewRoot.deliverKeyEventPostIme(ViewRoot.java:2946)
     at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2916)
     at android.view.ViewRoot.handleMessage(ViewRoot.java:2093)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:132)
     at android.app.ActivityThread.main(ActivityThread.java:4196)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:491)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
     at dalvik.system.NativeStart.main(Native Method)

**Comment by samyboy89** [comment]
I get this if I run it in Android Emulator - Google TV:

    Caused by: java.lang.UnsatisfiedLinkError: libm.so: cannot open shared object file: No such file or directory
    at java.lang.Runtime.loadLibrary(Runtime.java:430)
    at java.lang.System.loadLibrary(System.java:554)
    at io.realm.internal.TightDB.loadLibrary(TightDB.java:144)
    at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:31)
    at io.realm.Realm.<init>(Realm.java:159)
    at io.realm.Realm.createAndValidate(Realm.java:441)
    at io.realm.Realm.create(Realm.java:418)
    at io.realm.Realm.getInstance(Realm.java:336)
    at io.realm.Realm.getInstance(Realm.java:298)
    at io.realm.Realm.getInstance(Realm.java:279)

**Comment by samyboy89** [comment]
In addition, it does work on every other device and version of android that I've tried the application on.

**Comment by cmelchior** [comment]
When you say Google TV, I assume you mean the old one and not the new Android TV?
This blog post here seems to indicate that it might not play as nice with native libs as we might wish:
http://blog.xfce.org/2012/10/

**Comment by samyboy89** [comment]
Yes, I mean the old Google TV. Well, I see there's not much for you too do. Thanks anyway.
