### ISSUE TITLE
NullPointerException on project build

### ISSUE THREAD

**Issue by FHellmann** [realm/realm-java#842]
When I want to build my project, I receive the following NullPointerException and I don't know how to fix this. Can someone tell me if this is my fault and if so, how to solve the issue?

Thanks!

```java
15:28:53.267 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:28:53.273 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJava'.
15:28:53.278 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:28:53.283 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:28:53.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:28:53.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
15:28:53.299 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:28:53.304 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
15:28:53.311 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:28:53.316 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:28:53.321 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:28:53.327 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
15:28:53.332 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
15:28:53.336 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
15:28:53.341 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
15:28:53.346 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
15:28:53.351 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
15:28:53.356 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
15:28:53.361 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:28:53.366 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
15:28:53.371 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
15:28:53.375 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:28:53.381 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:28:53.387 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
15:28:53.392 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
15:28:53.397 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
15:28:53.402 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
15:28:53.407 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
15:28:53.412 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
15:28:53.416 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
15:28:53.422 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
15:28:53.427 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
15:28:53.432 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
15:28:53.437 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
15:28:53.442 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
15:28:53.447 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
15:28:53.452 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
15:28:53.457 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:28:53.461 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
15:28:53.466 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
15:28:53.471 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:28:53.476 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:28:53.481 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
15:28:53.487 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:28:53.492 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
15:28:53.497 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
15:28:53.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:28:53.505 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
15:28:53.510 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
15:28:53.517 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
15:28:53.522 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: java.lang.NullPointerException
15:28:53.526 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.Main.compile(Main.java:469)
15:28:53.531 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
15:28:53.536 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:42)
15:28:53.541 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
15:28:53.545 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:97)
15:28:53.551 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
15:28:53.556 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
15:28:53.561 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
15:28:53.566 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
15:28:53.571 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:158)
15:28:53.576 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:138)
15:28:53.581 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:92)
15:28:53.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
15:28:53.591 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
15:28:53.596 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
15:28:53.601 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
15:28:53.606 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
15:28:53.612 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:28:53.617 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:28:53.621 [ERROR] [org.gradle.BuildExceptionReporter]        ... 47 more
15:28:53.625 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
15:28:53.630 [ERROR] [org.gradle.BuildExceptionReporter]        at com.squareup.javawriter.JavaWriter.beginMethod(JavaWriter.java:391)
15:28:53.635 [ERROR] [org.gradle.BuildExceptionReporter]        at com.squareup.javawriter.JavaWriter.beginMethod(JavaWriter.java:368)
15:28:53.640 [ERROR] [org.gradle.BuildExceptionReporter]        at io.realm.processor.RealmProxyClassGenerator.emitAccessors(RealmProxyClassGenerator.java:245)
15:28:53.646 [ERROR] [org.gradle.BuildExceptionReporter]        at io.realm.processor.RealmProxyClassGenerator.generate(RealmProxyClassGenerator.java:214)
15:28:53.651 [ERROR] [org.gradle.BuildExceptionReporter]        at io.realm.processor.RealmProcessor.process(RealmProcessor.java:259)
15:28:53.656 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
15:28:53.661 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
15:28:53.666 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
15:28:53.671 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
15:28:53.675 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
15:28:53.680 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
15:28:53.685 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
15:28:53.690 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.tools.javac.main.Main.compile(Main.java:439)
15:28:53.695 [ERROR] [org.gradle.BuildExceptionReporter]        ... 65 more
15:28:53.701 [ERROR] [org.gradle.BuildExceptionReporter]
```

**Comment by cmelchior** [comment]
Realm requires getters and setters for all private fields, I am guessing you are missing some? We have fixed this so the error message should be clearer here https://github.com/realm/realm-java/issues/668. It will be part of the next release.

**Comment by FHellmann** [comment]
Thank you! This problem is solved.

Now I try to use some functional methods in my model classes, but Realm only want to have getter and setter methods. Is there a way to use some functional methods? For example data.increment() or something like.

**Comment by cmelchior** [comment]
Currently no, the reason being that it is too easy to accidentally reference the fields directly instead of using the accessors, which could lead to some subtle bugs we currently cannot warn against.

You can add static methods though.
