### ISSUE TITLE
NullPointerException at io.realm.Realm.getInstance

### ISSUE THREAD

**Issue by sliwakowski** [realm/realm-java#884]
I've updated my application that is now using realm as database ( so it's first version with Realm ). I tried to test this app on various devices and recently released an Android version and it's working for a lot of users ( minimum 10.000 ). But in for some users not and here is Google Play error reports I get :

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.xxx.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2237)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5135)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at io.realm.Realm.getInstance(Realm.java:397)
at io.realm.Realm.getInstance(Realm.java:359)
at io.realm.Realm.getInstance(Realm.java:340)
at com.xxx.xxx.Api.DataProvider.getOffers(DataProvider.java:30)
at com.xxx.xxx.OffersFragment.refreshData(OffersFragment.java:97)
at com.xxx.xxx.OffersFragment.onActivityCreated(OffersFragment.java:93)
at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:967)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
at android.app.Activity.performStart(Activity.java:5241)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2210)
```

in DataProvider.getOffers at line 30 i wrote :
```
final Realm realm = Realm.getInstance(context);
```

Users that reported this issue are using : Xperia Z3 , Xperia M2 and Xperia Z Compact on android 4.4

**Comment by cmelchior** [comment]
Hi @sliwakowski 
This is mostly likely an issue in your fragment lifecycle, since that null pointer is your context being ```null``` . That particular line of code is here: https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/Realm.java#L397

What are you using as context? The activity context is only available between onAttach and onDetach, so if you are using the context from getActivity() that might be why? 

Realm just uses the context to get the files directory, so using the Application context is a lot safer:

```
Realm.getInstance(MyApp.getContext())

public class MyApp extends Application {
  
  private static Context context;

  public void onCreate() {
    context = this;
  }

  public static getContext() {
    return context;
  }
}
```

**Comment by sliwakowski** [comment]
Thanks for your reply.

I'm creating instance of fragment ( where I invoke method using Realm ) in my main activity, and assign this activity to field in fragment object. Then I use this activity as context. Is it wrong ?

**Comment by cmelchior** [comment]
It could be, depending on your code. The Android lifecycle is a tricky beast especially when it comes to Fragment/Activities, and doing it manually is very easy to get wrong, especially if you have stuff like AsyncTasks or other background threads running. 

If you really need a reference to the activity I would get it/remove it using the methods described here: http://developer.android.com/guide/components/fragments.html#CoordinatingWithActivity

If not, I would use the method I described.

**Comment by cmelchior** [comment]
Hi @sliwakowski 
I assume you found a solution that worked for you. Feel free to add additional information if that is not the case.
