### ISSUE TITLE
SIGSEGV and subsequent out of memory issues

### ISSUE THREAD

**Issue by matzipan** [realm/realm-java#937]
Hello guys,

I have been trying to track down some SIGSEGV errors which seem to be happening somewhere in this area of code- I am not sure how to pin point it:
```
r.beginTransaction();

            if (isReload || categoryId == ApplicationConstants.CATEGORY_SEARCH_ID) {
-------------------- 
POINTER X
---------------------
                // call the function directly to avoid screen flicker when the commitTransaction
                // triggers the update on the adapter
                RealmResults<Article> articles = getCurrentCategoryArticles();
                for (int i = 0; i < articles.size(); i++) {
                    if (articles.get(i).getCategories().size() == 1) {
                        articles.get(i).removeFromRealm();
                        i--;
                    } else {
                        articles.get(i).getCategories().remove(cat);
                    }
                }
            }

            if (isReload) {
                r.where(Category.class).equalTo("id", categoryId)
                        .findFirst()
                        .setLastUpdated(Calendar.getInstance().getTimeInMillis()); //this can't be placed in its own function because realm doesn't support nested transactions
                itemsToLoad = true;
            }

            // there is an assumption made in the way the articles are loaded.
            // if more than PAGE_COUNT articles are posted before the cache is invalidated,
            // some articles might be missing
            try {
                if (jsonPosts != null) {
                    if (jsonPosts.length() != 0) {
                        for (int i = 0; i < jsonPosts.length(); i++) {
                            JSONObject item = new JSONObject(jsonPosts.get(i).toString());

                            Article existingArticle = getItemById(item.getInt("id"));
                            if (existingArticle != null) {
                                if (!existingArticle.getCategories().contains(cat)) {
                                    existingArticle.getCategories().add(cat);
                                }
                            } else {
                                Article article = r.createObject(Article.class);

                                article.setId(item.getInt("id"));
                                article.setTitle(Html.fromHtml(item.getString("title")).toString());
                                article.setContent(item.getString("content"));
                                article.setAuthor(Html.fromHtml(((JSONObject) item.get("author")).getString("name")).toString());
                                article.getCategories().add(cat);

                                try {
                                    article.setDescription(Html.fromHtml(item.getString("excerpt")).toString());
                                } catch (JSONException e) {
                                }


                                try {
                                    article.setThumbnail(item.getString("thumbnail"));
                                } catch (JSONException e) {
                                }

                                try {
                                    article.setImage(item.getJSONObject("thumbnail_images").getJSONObject("medium").getString("url"));
                                } catch (JSONException e) {
                                }

                                try {
                                    article.setUrl(item.getString("url"));
                                } catch (JSONException e) {
                                }

                                try {
                                    article.setDate(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ENGLISH).parse(item.getString("date")));
                                } catch (ParseException e) {
                                }
                            }
                        }
                    } else {
                        itemsToLoad = false;
                    }
                }

                r.commitTransaction();
            } catch (Exception e) {
                r.cancelTransaction();
                throw e;
            }
```

This crashes the app and subsequent app launches, with this exception: 
```
03-09 04:00:17.610  12755-12755/uk.co.entrepreneurhandbook.EHReader E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: uk.co.entrepreneurhandbook.EHReader, PID: 12755
    io.realm.internal.OutOfMemoryError: std::bad_alloc in io_realm_internal_table.cpp line 302
            at io.realm.internal.Table.nativeMoveLastOver(Native Method)
            at io.realm.internal.Table.moveLastOver(Table.java:373)
            at io.realm.RealmObject.removeFromRealm(RealmObject.java:61)
            at uk.co.entrepreneurhandbook.EHReader.ArticlesListDataSource.emptyCurrentCategory(ArticlesListDataSource.java:146)
            at uk.co.entrepreneurhandbook.EHReader.ArticlesListDataSource.<init>(ArticlesListDataSource.java:53)
            at uk.co.entrepreneurhandbook.EHReader.ArticlesListViewFragment.onActivityCreated(ArticlesListViewFragment.java:68)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:967)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```
And line 146 is down here: 
```
private void emptyCurrentCategory() {
        Realm r = Realm.getInstance(context);
        Category currentCategory = r.where(Category.class).equalTo("id", categoryId).findFirst();

        r.beginTransaction();
        RealmResults<Article> articles = getCurrentCategoryArticles();
        for (int i = 0; i < articles.size(); i++) {
            if (articles.get(i).getCategories().size() == 1) {
                articles.get(i).removeFromRealm(); <-------- 146
                i--;
            } else {
                articles.get(i).getCategories().remove(currentCategory);
            }
        }
        r.commitTransaction();
    }
```

I am unsure how to proceed in helping you guys with this issue. I believe the code at pointer X seems to be somehow corrupting the realm.

Please advise.

**Comment by cmelchior** [comment]
Hi @matzipan 
It looks like you are getting hit by this bug: https://github.com/realm/realm-java/pull/889
We already have made a fix which is in our SNAPSHOT release (and we hope to make a proper release this week).

Can you try using 0.79.2-SNAPSHOT to see if this fixes your problem. You can see how here: https://github.com/realm/realm-java/issues/936

**Comment by matzipan** [comment]
I am trying right now. I have just managed to locate the problem to the ```r.beginTransaction();```

**Comment by matzipan** [comment]
Seems to have done the trick! Thanks a million. Awesome product.
