### ISSUE TITLE
A lot of ANR when i use realm with changed folder.

### ISSUE THREAD

**Issue by rimidalv** [realm/realm-java#997]
Caused by: java.lang.RuntimeException: Unspecified exception. open() failed: No such file or directory in io_realm_internal_SharedGroup.cpp line 101

I tried to open realm (was version 0.77.0). And i receive this ANR from next devices:
Android 4.4: Xperia Z3 (D6603), Xperia Z3 (SOL26), Xperia Z2 (D6503), Galaxy Note3 (hlte), Galaxy S3 (c1lgt)
Android 5.1: Nexus 5 (hammerhead), 
Android 5.0: Nexus 4 (mako), Xperia Z3 (D6603), Nexus 6 (shamu)
and other.

My code in onCreate method to open realm:

        String currentRecordPath = StorageSettings.getInstance(context).getCurrentRecordPath();
        String fileName = "database.realm";
        File writeableFolder = new File(currentRecordPath);
        if(!writeableFolder.exists()){
            writeableFolder.mkdirs();
        }
        Realm realm = Realm.getInstance(writeableFolder, fileName);
        return realm;

Full stack trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rimidalv.dictaphone/com.rimidalv.dictaphone.MainActivity}: android.view.InflateException: Binary XML file line #76: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2367)
at android.app.ActivityThread.access$800(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5274)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
Caused by: android.view.InflateException: Binary XML file line #76: Error inflating class fragment
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
at android.support.v7.app.ActionBarActivityDelegateBase.a(Unknown Source)
at android.support.v7.app.e.setContentView(Unknown Source)
at com.rimidalv.dictaphone.MainActivity.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5977)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
... 10 more
Caused by: java.lang.RuntimeException: Unspecified exception. open() failed: Not a directory in io_realm_internal_SharedGroup.cpp line 101
at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
at io.realm.internal.SharedGroup.<init>(Unknown Source)
at io.realm.Realm.<init>(Unknown Source)
at io.realm.Realm.createAndValidate(Unknown Source)
at io.realm.Realm.create(Unknown Source)
at io.realm.Realm.getInstance(Unknown Source)
at com.rimidalv.dictaphone.db.a.a(Unknown Source)
at com.rimidalv.dictaphone.fragments.MenuFragment.onCreate(Unknown Source)
at android.app.Fragment.performCreate(Fragment.java:2040)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1045)
at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1147)
at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2116)
at android.app.Activity.onCreateView(Activity.java:5326)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
... 20 more

**Comment by cmelchior** [comment]
Hi @rimidalv 
Are you sure the call to .mkdirs() actually succeed?
Realm throws an exception because the directory you just created doesn't exist, which is the case if ```writeableFolder.mkdirs()``` return false. I assume the StorageSetting class is a custom class, what path does ```getCurrentRecordPath()``` point to?

**Comment by rimidalv** [comment]
I'll check it.
29 марта 2015 г. 20:21 пользователь "Christian Melchior" <
notifications@github.com> написал:

**Comment by kneth** [comment]
By the way, version 0.77.0 is a very old version (early January 2015). Is it possible for you to try latest version and see if the issue is the same?

**Comment by rimidalv** [comment]
but in 0.80.0 i have this bug https://github.com/realm/realm-java/issues/1001
I'll write my own test project on weekend to check this behavior.

**Comment by cmelchior** [comment]
Hi @rimidalv 
Have you been able to reproduce this?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if there is any new information on this.
